### ISSUE TITLE
Missing a correctness test-suite and a performance benchmark

### ISSUE THREAD

**Issue by sebpop** [ARM-software/ComputeLibrary#10]
This library needs a correctness suite of tests and a performance benchmark.  If ARM expects contributions from the community, please make sure the community has the right tools to not regress in correctness and in performance.

**Comment by psyhtest** [comment]
@sebpop That's an excellent point! Such tests and benchmarks should run across Linux, Android, Windows systems, with an automatic and systematic way to compare performance and detect regressions across a wide variety of NEON and Mali based devices.

May I suggest basing such tests and benchmarks on the open-source [Collective Knowledge](https://github.com/ctuning/ck) framework (CK), which I believe is the only solution available for the task in hand! [ARM already use CK](https://github.com/ctuning/ck/wiki/Demo-ARM-TechCon'16) to design highly efficient and reliable computer systems.

**Comment by AnthonyARM** [comment]
This is a good point: for the moment our tests suites are internal only but we'll consider adding them to the public repository in the future.

**Comment by GeorgeARM** [comment]
Closing this as in v17.09 release a custom-made validation and benchmarking framework was added.
