### ISSUE TITLE
`CpuInfo::num_threads_hint()` returns incorrect number of big cores on Apple M1

### ISSUE THREAD

**Issue by alvoron** [ARM-software/ComputeLibrary#1000]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=22.05 Build options: {'arch': 'armv8.2-a', 'debug': '0', 'examples': '1', 'opencl': '0', 'mali': '0', 'neon': '1', 'cppthreads': '1', 'benchmark_examples': 'true', 'validate_examples': 'true'} Git hash=b'a175e887d64450decf80ea47d4049832c5805565'

**Platform:**
Apple Mini with M1

**Operating System:**
macOS Monterey

**Problem description:**
`CpuInfo::num_threads_hint()` doesn't get the number of big cores on M1. Instead of that the function returns the total number of all cores.

**Comment by morgolock** [comment]
Hi @alvoron 

Thanks for raising this, please see the patch fixing the issue: https://review.mlplatform.org/c/ml/ComputeLibrary/+/9006


Hope this helps.
