### ISSUE TITLE
FP16 tanh activation has high relative error around 0

### ISSUE THREAD

**Issue by jondea** [ARM-software/ComputeLibrary#1002]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
present on main branch

**Platform:**
All aarch64 when using CPU backend

**Operating System:**
Linux/any

**Problem description:**
Relative error of FP16 `tanh` is very high around x=0 (have seen ~20%, but may be higher closer to zero). FP32 `tanh` uses a different approximation around 0 to fix this, but it is not present in FP16.

This came up as an issue when trying to integrate ACL with oneDNN https://github.com/oneapi-src/oneDNN/pull/1452. I will investigate further to see what a reasonable maximum relative error would be.

**Comment by jondea** [comment]
Patch to fix this is in review here: https://review.mlplatform.org/c/ml/ComputeLibrary/+/8480

**Comment by morgolock** [comment]
Thanks for the fix @jondea
