### ISSUE TITLE
Space-to-depth bug

### ISSUE THREAD

**Issue by puneetmatharu** [ARM-software/ComputeLibrary#1003]
## Problem description

I'm working with a fork of the ACL library and I'm currently looking into adding space-to-depth support for a use-case that I have. Whilst looking into what was already there, I noticed a bug in the output shape calculation.

#### Issue

There appears to be a bug in the calculation of the output shape:

https://github.com/ARM-software/ComputeLibrary/blob/aabef6c0584f06f4c0f4b61fb787d80374240619/arm_compute/core/utils/misc/ShapeCalculator.h#L1162-L1176

cf. Tensorflow docs [here](https://www.tensorflow.org/api_docs/python/tf/nn/space_to_depth). In short, the space-to-depth transformation should result in a _reduction_ in the height and weight and an _increase_ in the number of channels -- the opposite of what the code above says. 

## Solution

I believe lines 1171-1173 should be changed to:

```c++
output_shape.set(idx_width, input->tensor_shape()[idx_width] / block_shape);
output_shape.set(idx_height, input->tensor_shape()[idx_height] / block_shape);
output_shape.set(idx_depth, input->tensor_shape()[idx_depth] * (block_shape * block_shape));
```

**Comment by morgolock** [comment]
Hi @puneetmatharu 

Thanks for raising this. We have fixed the problem with this patch https://review.mlplatform.org/c/ml/ComputeLibrary/+/8668

**Comment by puneetmatharu** [comment]
Excellent, thanks for sorting that out! I'll close the issue now.
