### ISSUE TITLE
Question for how to debug the source code

### ISSUE THREAD

**Issue by huzq85** [ARM-software/ComputeLibrary#1004]
I am wondering whether we have a manual for how to debug the ACL source code. I went through the folder contribute_guide and found no information about debugging there. It would be very appreciable if we have such kind of manual, particularly for those who want to contribute to this project.

**Comment by morgolock** [comment]
Hi @huzq85 

Debugging will depend on what platform you are running it. I'd recommend using `gdb` on Linux. Debugging ACL is not different from debugging any other aarch64 binary, you would need to know a little bit of `gdb` and build the library with `debug=1`.

What are you trying to debug?

Let's know if you have any specific questions. 

Hope this helps.

**Comment by huzq85** [comment]
> Hi @huzq85
> 
> Debugging will depend on what platform you are running it. I'd recommend using `gdb` on Linux. Debugging ACL is not different from debugging any other aarch64 binary, you would need to know a little bit of `gdb` and build the library with `debug=1`.
> 
> What are you trying to debug?
> 
> Let's know if you have any specific questions.
> 
> Hope this helps.

hi, @morgolock ,
Thank you for your helpful information! I am able to debug the ACL lib right now based on your approach. I appreciate your help!
