### ISSUE TITLE
NESlice doesn't match specification when end coordinate(s) is negative

### ISSUE THREAD

**Issue by dgurulev** [ARM-software/ComputeLibrary#1007]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
`
arm_compute_version=v22.08 Build options: {'Werror': '1', 'debug': '1', 'neon': '1', 'opencl': '0', 'os': 'linux', 'arch': 'armv8a'} Git hash=b'aabef6c0584f06f4c0f4b61fb787d80374240619'
`

**Platform/Operating System:**
qemu-aarch64 version 6.2.0 (Debian 1:6.2+dfsg-2ubuntu6.5) on Ubuntu 22.04 LTS

**Problem description:**

Accordingly to specification of [NESlice](https://arm-software.github.io/ComputeLibrary/latest/classarm__compute_1_1_n_e_slice.xhtml#a5c2f378cb28b6c33a699fcf3d24b7ab3):
`End coordinates can be negative, which represents the number of elements before the end of that dimension.`
This behavior is aligned with both popular AI frameworks like _[TensorFlow](https://www.tensorflow.org/api_docs/python/tf/slice)_, _PyTorch_ and [NumPy](https://numpy.org/doc/stable/user/basics.indexing.html#slicing-and-striding). For example,
```
>>> import tensorflow as tf
>>> t = tf.constant([1, 2, 3, 4, 5, 6])
>>> print(t[1:-1])
tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)
```
[NESlice.patch.txt](https://github.com/ARM-software/ComputeLibrary/files/10055076/NESlice.patch.txt)

```
>>> import torch.nn as nn
>>> t = torch.tensor([1, 2, 3, 4, 5, 6])
>>> print(t[1:-1])
tensor([2, 3, 4, 5])
```

```
>>> import numpy as np
>>> t =  np.array([1, 2, 3, 4, 5, 6])
>>> print(t[1:-1])
[2 3 4 5]
```

So, for given tensor _input: { 6 }_ _starts: { 1 }_ _ends: { -1 }_ we expect _output: { 4 }_. Actually we got validation failure since [NESlice::validate](https://github.com/ARM-software/ComputeLibrary/blob/aabef6c0584f06f4c0f4b61fb787d80374240619/src/runtime/NEON/functions/NESlice.cpp#L50) expects _output: { 5 }_. This is because negative value at _ends_ coordinate(s) is interpreted as a non-zero bit(s) at _end_mask_ passed to _NEStridedSliceKernel_ what, in turn, is interpreted as ["ends[i] is ignored and the fullest possible range in that dimension is used"](https://arm-software.github.io/ComputeLibrary/latest/classarm__compute_1_1_n_e_strided_slice_kernel.xhtml#af43fbb802f4fb29811b41c8c14004474). 

**Details:**
_NESlice_ working though [NEStridedSliceKernel](https://github.com/ARM-software/ComputeLibrary/blob/aabef6c0584f06f4c0f4b61fb787d80374240619/src/core/NEON/kernels/NEStridedSliceKernel.cpp#L64) and calculates _exp_output_shape_ in this way
[NESlice::validate](https://github.com/ARM-software/ComputeLibrary/blob/aabef6c0584f06f4c0f4b61fb787d80374240619/src/runtime/NEON/functions/NESlice.cpp#L50) => [NEStridedSliceKernel::validate](https://github.com/ARM-software/ComputeLibrary/blob/aabef6c0584f06f4c0f4b61fb787d80374240619/src/core/NEON/kernels/NEStridedSliceKernel.cpp#L156) => [validate_arguments](https://github.com/ARM-software/ComputeLibrary/blob/aabef6c0584f06f4c0f4b61fb787d80374240619/src/core/NEON/kernels/NEStridedSliceKernel.cpp#LL41C8-L41C26) => [compute_strided_slice_shape](https://github.com/ARM-software/ComputeLibrary/blob/aabef6c0584f06f4c0f4b61fb787d80374240619/arm_compute/core/utils/misc/ShapeCalculator.h#LL1019C20-L1019C47) => [compute_strided_slice_output_shape](https://github.com/ARM-software/ComputeLibrary/blob/aabef6c0584f06f4c0f4b61fb787d80374240619/src/core/utils/helpers/tensor_transform.cpp#LL139C13-L139C47) => [calculate_end_on_index](https://github.com/ARM-software/ComputeLibrary/blob/aabef6c0584f06f4c0f4b61fb787d80374240619/src/core/utils/helpers/tensor_transform.cpp#L72) =>
```
// Reset in case of begin mask present
if(arm_compute::helpers::bit_ops::is_bit_set(end_mask, index) && !shrink_axis)
{
    stop = (stride > 0) ? std::numeric_limits<int>::max() : std::numeric_limits<int>::lowest();
}

<skip>

// Final clamp
stop = (stride > 0) ? utility::clamp(stop, 0, dim_size) : utility::clamp(stop, -1, dim_size - 1);
```
So, _stop_ is calculated as input's full range and this matches specification of [NEStridedSliceKernel](https://arm-software.github.io/ComputeLibrary/latest/classarm__compute_1_1_n_e_strided_slice_kernel.xhtml#af43fbb802f4fb29811b41c8c14004474). The thing is the way how _NESlice_ [generates](https://github.com/ARM-software/ComputeLibrary/blob/aabef6c0584f06f4c0f4b61fb787d80374240619/src/runtime/NEON/functions/NESlice.cpp#L61) _end_mask_ by [construct_slice_end_mask](https://github.com/ARM-software/ComputeLibrary/blob/aabef6c0584f06f4c0f4b61fb787d80374240619/src/core/utils/helpers/tensor_transform.cpp#L172) function to be passed to _NEStridedSliceKernel_:
```
int32_t construct_slice_end_mask(Coordinates ends)
{
    // Create end mask
    int32_t end_mask = 0;
    for(unsigned int i = 0; i < ends.num_dimensions(); ++i)
    {
        if(ends[i] < 0)
        {
            end_mask |= 1 << i;
        }
    }

    return end_mask;
}
```

Finally, we either need to fix _NESlice_ behavior or make a correction in the documentation to describe actual one.
A fix may be quite quick and simple - just get rid off [end_mask](https://github.com/ARM-software/ComputeLibrary/blob/aabef6c0584f06f4c0f4b61fb787d80374240619/src/runtime/NEON/functions/NESlice.cpp#LL61C25-L61C33) calculation and pass zero as _end_mask_ to NEStridedSliceKernel:: [validate](https://github.com/ARM-software/ComputeLibrary/blob/aabef6c0584f06f4c0f4b61fb787d80374240619/src/runtime/NEON/functions/NESlice.cpp#L63)/[configure](https://github.com/ARM-software/ComputeLibrary/blob/aabef6c0584f06f4c0f4b61fb787d80374240619/src/runtime/NEON/functions/NESlice.cpp#L46), see attached patch.

Reproducer (_slice.cpp_, no test case w/ negative value at _ends_ found at [tests/validation/NEON/Slice.cpp](https://github.com/ARM-software/ComputeLibrary/blob/aabef6c0584f06f4c0f4b61fb787d80374240619/tests/validation/NEON/Slice.cpp)):
```
#include "arm_compute/core/Types.h"
#include "arm_compute/runtime/NEON/functions/NESlice.h"
#include "arm_compute/runtime/Tensor.h"

using namespace arm_compute;

int main()
{
        auto test = [](TensorInfo input, TensorInfo output, Coordinates starts, Coordinates ends)
        { return NESlice::validate(&input, &output, starts, ends); };

        //Passed
        assert(bool(test(
                TensorInfo(TensorShape(6U), 1, DataType::F32),
                TensorInfo(TensorShape(4U), 1, DataType::F32),
                Coordinates( 1), Coordinates(5)
        )));

        //Failed
        assert(bool(test(
                TensorInfo(TensorShape(6U), 1, DataType::F32),
                TensorInfo(TensorShape(4U), 1, DataType::F32),
                Coordinates( 1), Coordinates(-1)
        )));
}
```
```
aarch64-linux-gnu-g++ slice.cpp -g -O0 -I <arm_compute-repo> -I <arm_compute-repo>/include -L <arm_compute-repo>/build -o slice -larm_compute-static
```

**Comment by morgolock** [comment]
Hi @dgurulev 

Thanks for reporting this.

Could you please submit your patch for review, please see the section **How to submit a patch** in https://arm-software.github.io/ComputeLibrary/latest/contribution_guidelines.xhtml
