### ISSUE TITLE
A problem about Tebsors' DataType for NEGEMMLowp.cpp

### ISSUE THREAD

**Issue by duhuanxianzi** [ARM-software/ComputeLibrary#101]
Hi, I have some problems about Tensors' DataType for NEGEMMLowp.cpp

**For neon_gemmlowp_test.cpp**
Tensor input0;
Tensor input1;
Tensor output;
.
.
.
input0.allocator()->init(TensorInfo(src_shape, 1, DataType::F32));
input1.allocator()->init(TensorInfo(src_shape, 1, DataType::F32));
output.allocator()->init(TensorInfo(src_shape, 1, DataType::F32));
.
.
.
NEGEMMLowp gemm_low8;
gemm_low8.configure(&input0, &input1, &output, a_offset, b_offset, output_offset, output_mult_int, shift);
.
.
.
gemm_low8.run(); //Test Runtime
.
.
.
When DataType::F32 is changed into DataType::F16, it appears an error as the program runs:

terminate called after throwing an instance of 'std::runtime_error'
  what():  in configure src/core/NEON/kernels/NEGEMMTranspose1xWKernel.cpp:69: Data type not supported
Aborted

it seems there are a few bugs in DataType::F16. How can I solve it?

**Comment by gmiodice** [comment]
Hi @duhuanxianzi 

currently DataType::F16 is not supported on NEON and not supported by NEGEMMLowp. 

In order to use NEGEMMLowp, the data type must be DataType::U8.

Thanks

**Comment by duhuanxianzi** [comment]
Thanks a lot!

**Comment by GeorgeARM** [comment]
Closing issue! Reopen if needed!
