### ISSUE TITLE
terminating with uncaught exception of type std::runtime_error: in get_mali_hw_info

### ISSUE THREAD

**Issue by Saikatsaha1996** [ARM-software/ComputeLibrary#1013]
Os `Android`
Android version `12`
Cpu `Dimensity 8100`
GPU `Mali -G610 MC6`
Using in `Termux`
Termux cannot find the OpenCL driver..
With adreno OpenCL GPU no issues..
Only facing with `Mali GPU`

I want to build `compute library..`
But i can't build..

Because my device cannot find OpenCL library..

I also checked in clinfo tool 
Still number of platforms 0 reporting..

Where I can find OpenCL library?

when i `export LD_LIBARY_PATH` not working..
![IMG_20221209_200116](https://user-images.githubusercontent.com/72664192/206724912-23a58412-6c7f-4349-9dc1-66a7588779f9.jpg)
![IMG_20221209_200034](https://user-images.githubusercontent.com/72664192/206724925-9c86d1fd-6418-42e1-bd77-c1435e8789cc.jpg)

**Comment by Saikatsaha1996** [comment]
@morgolock is it my Mali GPU driver issue?

![IMG_20221209_221048](https://user-images.githubusercontent.com/72664192/206750343-8f0ca3f6-a0bf-48b6-ac46-06d629e22594.jpg)

**Comment by Saikatsaha1996** [comment]
Never faced this issue with Adreno gpu..
My fast Mali GPU Android device.. 
But i am unable to call OpenCL in Android..

**Comment by Saikatsaha1996** [comment]
So Arm-Mali G610 GPU haven't OpenCL driver? 😑

# #
![IMG_20221210_053301](https://user-images.githubusercontent.com/72664192/206820064-309c6860-e929-4421-9631-96e5738e638b.jpg)
![IMG_20221210_053207](https://user-images.githubusercontent.com/72664192/206820067-dbd2af9d-9dd0-48ed-80b5-bfcd19f3338d.jpg)
![IMG_20221210_053227](https://user-images.githubusercontent.com/72664192/206820068-ece9b1e3-cbc7-4ad0-93a9-2322f6619242.jpg)

**Comment by Saikatsaha1996** [comment]
@morgolock in Mali GPU G-610 OpenCL not available?

![Screenshot_2022-12-11-22-11-09-073_com primatelabs geekbench5](https://user-images.githubusercontent.com/72664192/206916689-e52f7ef1-8614-478b-b853-9b52cea5bbf3.jpg)

**Comment by Saikatsaha1996** [comment]
> @morgolock in Mali GPU G-610 OpenCL not available?
> 
> ![Screenshot_2022-12-11-22-11-09-073_com primatelabs geekbench5](https://user-images.githubusercontent.com/72664192/206916689-e52f7ef1-8614-478b-b853-9b52cea5bbf3.jpg)

New generation Mali GPU driver has complex..
No Android benchmark application working for this OpenCL loader issue... 
But termux development team solved this issue..
I will closing..
![Screenshot_2022-12-12-07-54-34-217_com termux](https://user-images.githubusercontent.com/72664192/206947619-33c02e9b-dfcf-4f52-90a8-e4e11aaadfde.jpg)
![Screenshot_2022-12-12-07-54-45-810_com termux](https://user-images.githubusercontent.com/72664192/206947627-1f3cdd78-0664-42b9-a970-9779c340e641.jpg)

**Comment by Saikatsaha1996** [comment]
🥲

`terminating with uncaught exception of type std::runtime_error: in get_mali_hw_info tests/framework/instruments/MaliCounter.cpp:62: Failed to check version.
[1]    21024 abort      benchmark_cl_gemm_native --instruments=ALL`

![Screenshot_2022-12-19-06-12-10-512_com termux](https://user-images.githubusercontent.com/72664192/208328429-d06242ef-66d1-4b2f-8a8f-627ec1640aa9.jpg)
![Screenshot_2022-12-19-06-15-21-376_com termux](https://user-images.githubusercontent.com/72664192/208328472-36adc4f7-4b1d-440b-91ff-ef735ee4b1af.jpg)

**Comment by Saikatsaha1996** [comment]
> 

![Screenshot_2023-01-10-00-50-15-547_com termux](https://user-images.githubusercontent.com/72664192/211390176-df95c4f9-44a2-468f-8738-f1d4c3976795.jpg)

**Comment by Saikatsaha1996** [comment]
> Hi @Saikatsaha1996
> 
> Please share the plain text output from the command line instead of screenshots, it's easier to help with plaintext.
> 
> From looking at the images it seems the device is not properly configured, either the drivers or a problem with `LD_LIBRARY_PATH`
> 
> Can you please share the output of the commad `ls /dev/mali0 -al` ?
> 
> Hope this helps

```
~ $ ls /dev/mali0 -al
crw-rw-rw- 1 system graphics 10, 113 Jan  7 07:06 /dev/mali0
~ $
```

**Comment by morgolock** [comment]
Hi @Saikatsaha1996 

I'd suggest using `adb shell` rather than `Termux`. I'd run `clinfo` within an `adb shell` to see if OpenCL is working. If that's working the next step is running `arm_compute_validation`.

This looks like a problem with the device configuration or `Termux`
