### ISSUE TITLE
Build ERROR (VFP register)

### ISSUE THREAD

**Issue by Shipley1105** [ARM-software/ComputeLibrary#1028]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

**Platform:**
armv7a
**Operating System:**
linux

**Problem description:**
Build ComputeLibrary-19.05 using Scon 4.3 , toolchain set to arm-gcc-7.3-linux-musleabi-
got following error
> error build/src/core/NEON/kernels/arm_gemm/kernels/**/ used **VFP** registerarguments , build/libarm_compute_core.so does not
and
> failed to merge target specific data of file build/src/core/NEON/kernels/arm/gemm/kernels/a32_sgemm_x8x6/a55r1.os

**Comment by morgolock** [comment]
Hi @Shipley1105 

Could you please share the command used to build the library?

**Comment by Shipley1105** [comment]
scons Werror=1 -j8 debug=0 asserts=1 neon=1 opencl=0 embed_kernels=1 os=linux arch=armv7a

**Comment by Shipley1105** [comment]
I guess ComputeLibrary is not compatiable with arm-gcc7.3-linux-musleabi, do you have any solution? @morgolock

**Comment by morgolock** [comment]
Hi @Shipley1105 

Please take a look at the library's documentation https://arm-software.github.io/ComputeLibrary/latest/how_to_build.xhtml#S1_2_linux

We use `gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf` to build for`armv7a`


```
To cross-compile the library in debug mode, with Arm® Neon™ only support, for Linux 32bit:

scons Werror=1 -j8 debug=1 neon=1 opencl=0 os=linux arch=armv7a
```

Hope this helps.
