### ISSUE TITLE
Use quantization Gemm plus bias-add in a neural network

### ISSUE THREAD

**Issue by yd2102** [ARM-software/ComputeLibrary#1030]
Hi,

I have questions on how to plug ACL's quantization Gemm into a neural network (e.g. Bert). The Gemm's weight has already been quantized by the ML framework (more specifically, I'm looking at PyTorch QNNPACK).

So from what I've gathered, it seems I have to run the quantized Gemm using these stages:
```
Option 1: [FLOAT32 input] -> [NEQuantizationLayer] -> [NEGEMMLowpMatrixMultiplyCore configured with GEMMLowpOutputStageInfo] -> [NEDequantizationLayer] -> [FLOAT32 output]
Option 2: [FLOAT32 input] -> [NEQuantizationLayer] -> [NEGEMMLowpMatrixMultiplyCore] -> [NEGEMMLowpOutputStage] -> [NEDequantizationLayer] -> [FLOAT32 output]
```

Here are my questions:
1) Are the above stages correct way to plug in ACL's quantized Gemm? Are there performance or memory tradeoffs between Option 1 vs Option 2 above?
2) I need to add the FLOAT32 bias. How does bias-add fit into the quantized Gemm computation? I noticed there appear to be places I can supply bias tensor: [here - tensor C](https://github.com/ARM-software/ComputeLibrary/blob/main/arm_compute/runtime/NEON/functions/NEGEMMLowpMatrixMultiplyCore.h#L98), and [here - tensor bias](https://github.com/ARM-software/ComputeLibrary/blob/main/arm_compute/runtime/NEON/functions/NEGEMMLowpOutputStage.h#L81), but they expect INT32 data type. What mechanisms should I use to convert bias from FLOAT32 to INT32?
3) From [this](https://github.com/ARM-software/ComputeLibrary/blob/master/examples/neon_gemm_qasymm8.cpp#L226) example, it shows that NEGEMMLowpOutputStage requires QuantizationInfo, whose fields depend on the non-quantized FLOAT32 Gemm computation result "dst0". What's the proper way of coming up with the scale and zero_point values from the FLOAT32 result here?

Thanks!

**Comment by morgolock** [comment]
Hi @yd2102 
ACL does not support mixed precision configurtions in `CpuGemm` or `CpuGemmLowpMatrixMultiplyCore` where input is `float` and the weights are quantized.
Please see:
https://github.com/ARM-software/ComputeLibrary/blob/main/src/cpu/operators/CpuGemmLowpMatrixMultiplyCore.h#L81
https://github.com/ARM-software/ComputeLibrary/blob/main/src/cpu/operators/CpuGemm.h#L77

Assuming you have a tflite model, I think the best approach for what you would like to do is to use ArmNN's `ExecuteNetwork`. This tool supports mixed data types as mentioned above and will take `float` input and dequantize the weights at runtime when running a convolution workload.

Hope this helps.

**Comment by yd2102** [comment]
> ACL does not support mixed precision configurtions in CpuGemm or CpuGemmLowpMatrixMultiplyCore where input is float and the weights are quantized.

Hi @morgolock 
I think I didn't state the problem clearly sorry. In the case I'm studying, the network input (matrix A0) is float32, and the weight (matrix B) is already quantized to uint8. So if I first quantize matrix A0 (through `NEQuantizationLayer`), then I get an uint8 matrix A1. Now both A1 and B are uint8, in this case `CpuGemmLowpMatrixMultiplyCore` indeed supports these data types:
https://github.com/ARM-software/ComputeLibrary/blob/main/src/cpu/operators/CpuGemmLowpMatrixMultiplyCore.h#L81
https://github.com/ARM-software/ComputeLibrary/blob/main/src/cpu/operators/CpuGemmLowpMatrixMultiplyCore.h#L84

If I understand it correctly, if we want uint8 `dst` from `CpuGemmLowpMatrixMultiplyCore` then we need to supply `GEMMLowpOutputStageType::QUANTIZE_DOWN_FIXEDPOINT`. If we simply want int32 `dst`, we can leave that `gemm_info` to default:
https://github.com/ARM-software/ComputeLibrary/blob/main/src/cpu/operators/CpuGemmLowpMatrixMultiplyCore.h#L101

Thanks!

**Comment by GGGGxxxxxxxxr** [comment]
I assume it is pretty simple.
Currently I have modified the backend of CpuGEMMConv2d to set the DST tensor as INT32 datatype.
You could just quantized down your output and convert it into FP32 then perform bias addition.
Or,  you could transform your bias (considering the correct accumulated scale in this condition) into integer.
