### ISSUE TITLE
Problem with SpaceToDepth layer

### ISSUE THREAD

**Issue by allnes** [ARM-software/ComputeLibrary#1036]
Hi!
When I used NESpaceToDepth layer, I got wrong values in random indexes.

That is configuration were with current bug:
- `arm_compute::DataType::F32` with `block_size=2`
- `arm_compute::DataType::F32` with `block_size=3 ` and `arm_compute::DataLayout::NCHW`
- `arm_compute::DataType::S8 ` with `block_size=2`
- `arm_compute::DataType::S8 ` with `block_size=3 ` and `arm_compute::DataLayout::NCHW`

**Comment by GGGGxxxxxxxxr** [comment]
Hi @allnes ,

I have not used this operator but I have planned to use it in the future.

Could you please explain the wrong value in more details?

I suppose I would look at the backend implementation of this and try to find out the bug

**Comment by GGGGxxxxxxxxr** [comment]
I have tried DepthtoSpace Operator for PixelShuffle purpose, I cannot get the correct result either.
I have implemented based on NHWC layout.

**Comment by GGGGxxxxxxxxr** [comment]
I have figured out the issue.

For example, as you configured it in NCHW layout, I would explain in NCHW layout.

If I want to convert Tensor from (2,2,12) to (4,4,3) (blocksize= 2)

The first channel of the output would take data from INPUT Channel 1, 4, 7, 10.

But as you might expect it to take the data from INPUT CHANNEL 1,2,3,4.

**Comment by allnes** [comment]
> 

thank you for answer!
