### ISSUE TITLE
Why does NEScale.run() run much slower than cv::resize with any InterpolationPolicy in OpenCV？

### ISSUE THREAD

**Issue by duhuanxianzi** [ARM-software/ComputeLibrary#105]
Hi, I have some problem about NEScale.cpp. Compared between  NEScale and cv::resize function, I found NEScale.run() run much slower than cv::resize with any InterpolationPolicy in OpenCV. Why?

 **neon_resize_test.cpp**
 Image     src, dst;

    unsigned int width = 1024;
    unsigned int height = 1024;

    unsigned int resize_width = 1256;
    unsigned int resize_height = 1256;
     
     src.allocator()->init(TensorInfo(width, height, Format::U8));
    TensorInfo dst_tensor_info(resize_width, resize_height, Format::U8);

    dst.allocator()->init(dst_tensor_info);

    NEScale resize;
    resize.configure(&src, &dst, InterpolationPolicy::BILINEAR, BorderMode::UNDEFINED);

       //Allocate all the images
        src.allocator()->allocate();
	dst.allocator()->allocate();
       .
       .
      resize.run();   //Test runtime
       .
       .

**Comment by mpflanzer** [comment]
How did you compile the library? To get optimal performance it has to be compiled with `debug=0`.

**Comment by duhuanxianzi** [comment]
I am sure debug=0 when compling the library

**Comment by mpflanzer** [comment]
Great, thanks for confirming. Which platform are you using for the comparison?
Have you tried running the scale function multiple times in a loop to compute the average of the runtime?

**Comment by duhuanxianzi** [comment]
Yes, I run the scale funtion 100 times in a loop.

**Comment by szcv** [comment]
@duhuanxianzi 
Have you solve that problem? I also found that NEScale.run() run much slower than cv::resize?And other arm ComputeLibrary functions also showed bad performance than opencv function.

**Comment by zanazakaryaie** [comment]
Hi to all

I also experienced slower performance with NEScale compared to cv::resize in OpenCV. 

@duhuanxianzi
Could you please help me to use NEColorConvert instead of cvtColor with CV_BGR2GRAY?

**Comment by mpekatsoula** [comment]
@zanazakaryaie You can find the supported color formats [here](https://github.com/ARM-software/ComputeLibrary/blob/52ba29e936b8e711e8acdfe819e36f884d4f3fe1/arm_compute/core/Types.h#L50) and the supported conversions [here](https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/NEON/functions/NEColorConvert.h).
Unfortunately BGR2GRAY is not supported by ACL.
