### ISSUE TITLE
Can Khadas Edge2 board be supported? 

### ISSUE THREAD

**Issue by zyujie-ioo** [ARM-software/ComputeLibrary#1056]
I modified the ARM-CL and tested it on the Khadas Vim3 Pro board. Now I want to utilize a more efficient CPU and GPU. Could I directly transplant my code to the Khadas Edge2 board?

**Comment by zyujie-ioo** [comment]
Thank you! It is very helpful.  By the way, is there a way to include the NPU invocation of the Khadas Edge2 board in the existing ARM-CL?

**Comment by morgolock** [comment]
Hi @zyujie-ioo 

ACL only supports ARM CPUs and GPUs.

Hope this helps.

**Comment by zyujie-ioo** [comment]
Okay, thanks. Do you know any compiler which supports executing the model using the CPU, GPU, and NPU of the Khadas Edge2 board? I checked ARM-NN, but there seemed to be no support for this board's NPU.

**Comment by morgolock** [comment]
Hi @zyujie-ioo 

For Linux you can use gcc > 6.3
For Android any recent version of the ndk will support armv8.2

Hope this helps.
