### ISSUE TITLE
why CLCannyEdge and NECannyEdge is removed from the new ACL version ?

### ISSUE THREAD

**Issue by lovelypp777** [ARM-software/ComputeLibrary#1058]
I noticed that in the older version of ACL, this canny edge detection help class, but after v20.11, it is removed totally. I think canny is so usual. I don't know why and what's the replacement of it,
thanks!

**Comment by morgolock** [comment]
Hi @lovelypp777 

In 20.11 we decided that the library's focus should machine learning and deprecated most of the computer vision functions and kernels. In 21.05 we removed the CV functions and kernels from the library.

I'd suggest looking into OpenCV for an alternative implementation of Canny Edge for ARM, see more details in https://opencv.org/arm/ 

Hope this helps.
