### ISSUE TITLE
How to add a new backend?

### ISSUE THREAD

**Issue by DandanXu1007** [ARM-software/ComputeLibrary#1059]
Hi! How to add a new backend? for example riscv.

**Comment by morgolock** [comment]
Hi @DandanXu1007 

A new backend will require major changes to the library, we had an OpenGLES backend which we deprecated and removed.

The following patches removing the GLES backend could give you an idea of the changes required to add a new backend.

https://review.mlplatform.org/c/ml/ComputeLibrary/+/5097
https://review.mlplatform.org/c/ml/ComputeLibrary/+/5314

Hope this helps.
