### ISSUE TITLE
alexnet example

### ISSUE THREAD

**Issue by kaishijeng** [ARM-software/ComputeLibrary#107]
Is there available of an example of CNN network, like alexnet implementation using ComputeLibrary?

Thanks,

**Comment by AnthonyARM** [comment]
Not yet, but we're working on it.

**Comment by jialiang19** [comment]
Dear Anthony: 
Can you please give us a approximate time when the alexnet implementation using ComputeLibrary would be finished? 
Thank you so much!

**Comment by AnthonyARM** [comment]
Should be out this week (We're finalising the release)

**Comment by kaishijeng** [comment]
Anthony,

I saw there is a benchmark of Alexnet exaample in v17.06. Is there an instruction of how to build this benchmark and run it?

Thanks.

**Comment by AnthonyARM** [comment]
Yes, in the [documentation] (https://arm-software.github.io/ComputeLibrary/v17.06/tests.xhtml)

**Comment by AnthonyARM** [comment]
Yes, in the [documentation](https://arm-software.github.io/ComputeLibrary/v17.06/tests.xhtml)
