### ISSUE TITLE
How to add a new operator to ACL

### ISSUE THREAD

**Issue by zxros10** [ARM-software/ComputeLibrary#1071]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

**Platform:**
mali gpu 

**Operating System:**
linux

**Problem description:**
I need add a new operator to acl. I read the document https://arm-software.github.io/ComputeLibrary/latest/adding_operator.xhtml , but still confused, can you give me a MR or commit about add new operator? Opencl and Neon all need， thanks!

**Comment by morgolock** [comment]
Hi @zxros10 

Please have a look at these patches adding the logical operators both on Neon and CL

https://review.mlplatform.org/c/ml/ComputeLibrary/+/4448
https://review.mlplatform.org/c/ml/ComputeLibrary/+/4438

Hope this helps,

**Comment by zxros10** [comment]
Thanks
