### ISSUE TITLE
 ACL implementation for Filtering functions like FIR/IIR

### ISSUE THREAD

**Issue by musicwei** [ARM-software/ComputeLibrary#1072]
ACL now has convolution algorithms ,any plan to implementation Filtering functions,or add examples which use convolution  to implement a FIR algorithms .

**Comment by morgolock** [comment]
Hi @musicwei 

Thank you for this feature request, we will discuss it with the team.

**Comment by morgolock** [comment]
Hi @musicwei 

We have no plans to implement this in ACL, the main focus of the library is machine learning operators.
