### ISSUE TITLE
Errors while build configuration using cmake.

### ISSUE THREAD

**Issue by sachindia86** [ARM-software/ComputeLibrary#1075]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

**Platform:** ARM64

**Operating System:** Ubuntu

**Problem description:**
I am trying to create a configuration to work with an Eclipse IDE tool. I am getting following errors while using cmake.

ubuntu@ip-172-31-17-56:~/github/ComputeLibrary$ cmake -S ./src
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:23 (target_sources):
  Cannot specify sources for target "arm_compute_graph" which is not built by
  this project.

CMake Error at CMakeLists.txt:105 (target_sources):
  Cannot specify sources for target "arm_compute_sve" which is not built by
  this project.

CMake Error at CMakeLists.txt:328 (target_sources):
  Cannot specify sources for target "arm_compute_sve2" which is not built by
  this project.

CMake Error at CMakeLists.txt:347 (target_sources):
  Cannot specify sources for target "arm_compute" which is not built by this
  project.

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.22)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/github/ComputeLibrary/CMakeFiles/CMakeOutput.log".
ubuntu@ip-172-31-17-56:~/github/ComputeLibrary$

**Comment by sleepy-hat** [comment]
Hi @sachindia86 

Please try to compile using the CMakeLists.txt at the root of the repository as the source for CMake, i.e. run
`cmake -S .` instead of `cmake -S ./src`

Hope this helps
