### ISSUE TITLE
Why do the resnet50 results of arm neon cnn not correspond to pytorch?

### ISSUE THREAD

**Issue by NNUCJ** [ARM-software/ComputeLibrary#1076]
1. MY Goal:
&emsp;&emsp;  Using arm neon CNN to build resnet50 and compare the results with Pytorch. I have saved weights of Pytorch as numpy, and  loaded the corresponding weights on Neon CNN. 

2. Problems:
&emsp;&emsp; The value of Feature Map cannot be aligned with Pytorch starting from the 3x3 conv2d() layer of the first bottleneck（The section between # comments in the network structure of the following code）.
```
ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      ##########################
      [error begin]
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
    ############################
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
```
3. Test Script
&emsp;&emsp;Using the same input data and convolutional weights([download link](https://github.com/NNUCJ/github_issue/tree/master/data)) to compare the output results of conv2d in acl and pytorch。

- pytorch
```
input = np.load("input.npy")
conv2_weights = np.load("layer1_0_conv2_weight.npy")
state_dict = {"weight": torch.from_numpy(conv2_weights)}
conv2d_model = nn.Conv2d(64, 64, kernel_size=3, stride=1,padding=1, groups=1, bias=False, dilation=1)
conv2d_model.load_state_dict(state_dict)
test_out = conv2d_model(torch.from_numpy(input).unsqueeze(0))
```
- [arm neon cpp](https://github.com/NNUCJ/github_issue/blob/master/scripts/neon_test_conv.cpp)

**Comment by morgolock** [comment]
Hi @NNUCJ 

The easiest way to run models on ACL is to use[ ArmNN's `ExecuteNetwork`](https://github.com/ARM-software/armnn/tree/branches/armnn_24_02/tests/ExecuteNetwork
)

Using ExecuteNetwork you can run tflite models as shown below:
```
root@odroid:~/pablo# LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./ExecuteNetwork  -m mobilenet_v2_1.0_224_quant.tflite  -c GpuAcc --iterations=10 -f tflite-binary  -i input -o output | grep Inference
Inference time: 132.36 ms
Inference time: 131.83 ms
Inference time: 131.63 ms
Inference time: 131.93 ms
Inference time: 131.73 ms
Inference time: 131.86 ms
Inference time: 131.77 ms
Inference time: 131.76 ms
Inference time: 131.81 ms
Inference time: 132.32 ms
```
You can output the result to a file and compare with pytorch.

We have a resnet50 graph example in ACL but this is provided as an experimental tool and we don't distribute the weights.  You could try to extract the weights from the model  https://github.com/ARM-software/ComputeLibrary/blob/main/examples/graph_resnet50.cpp#L256 but this is not straight-forward.

The best option is to use `ExecuteNetwork`

Hope this helps,
