### ISSUE TITLE
TensorAllocator::allocate()  failed in some cases

### ISSUE THREAD

**Issue by ghostsun89** [ARM-software/ComputeLibrary#108]
Hi guys,
I wrote a program to evaluate the SCONV performance with ACL(v17.05) and found when the conv paras are large,  the program will be killed when it executes the TensorAllocator::allocate() method.

The conv parameters setting are: ni=1, ci=512, hi=176, wi=176, kernel_size=11, pad=1, stride=1, co=512

I calculated the size of input tensor, it's about 60MB, not too big. So I wonder what cause the program killed. Are there any limit in memory use?

I posted my test code below and please try if your guys can reproduce the same issue:
`
	
	#include "arm_compute/runtime/NEON/NEFunctions.h"
	#include "arm_compute/core/Types.h"
	#include "test_helpers/Utils.h"
	using namespace arm_compute;
	using namespace test_helpers;
	void main_neon_convlayer(int argc, const char **argv)
	{	
	constexpr unsigned int kh=11, kw=11;  //kernel size
	
	constexpr unsigned int sh=1, sw=1, ph=1, pw=1;   //stride size & padding size
	
	constexpr unsigned int ni=1, ci=512, hi=176, wi=176;  //[N, C, H, W]
	
	constexpr unsigned int ho = (hi+2*ph-kh)/sh+1;
	
	constexpr unsigned int wo = (wi+2*pw-kw)/sw+1;
	
	constexpr unsigned int no = ni, co = ci;
	
	auto *src_data = new float[ni*ci*hi*wi];
	auto *dst_data = new float[no*co*ho*wo];
	auto *weights_data = new float[kh*kw*ci*co];
	auto *bias_data = new float[1*co*1*1];

	for(unsigned int batch = 0; batch < ni; batch++){
		for(unsigned int featuremaps = 0; featuremaps < ci; featuremaps++){
			for(unsigned int height = 0; height < hi; height++){
				for(unsigned int width = 0; width < wi; width++){
					src_data[batch * (ci*hi*wi) + featuremaps * (hi*wi) + height * wi + width] = static_cast<float>(1);
				}
			}
		}
	}

	for(unsigned int batch = 0; batch < no; batch++){
		for(unsigned int featuremaps = 0; featuremaps < co; featuremaps++){
			for(unsigned int height = 0; height < ho; height++){
				for(unsigned int width = 0; width < wo; width++){
					dst_data[batch * (co*ho*wo) + featuremaps * (ho*wo) + height * wo + width] = static_cast<float>(10);
				}
			}
		}
	}

	for(unsigned int ofm = 0; ofm<co; ofm++){
		for(unsigned int ifo = 0; ifo<ci; ifo++){
			for(unsigned int kernel_h = 0; kernel_h<kh; kernel_h++){
				for(unsigned int kernel_w = 0; kernel_w<kw; kernel_w++){
					weights_data[ofm * (ci*kh*kw) + ifo * (kh*kw) + kernel_h * kw + kernel_w] = static_cast<float>(1);
				}
			}
		}
	}

	for(unsigned int i=0; i<1*co*1*1; i++){
		bias_data[i] = static_cast<float>(0);
	}

	NEConvolutionLayer neconv;
	Tensor input, weights, biases, output;
	const TensorShape shape_input(wi, hi, ci, ni);
	input.allocator()->init(TensorInfo(shape_input, 1, DataType::F32));
	const TensorShape shape_weights(kw, kh, ci, co);
	weights.allocator()->init(TensorInfo(shape_weights, 1, DataType::F32));
	const TensorShape shape_bias(co);
	biases.allocator()->init(TensorInfo(shape_bias, 1, DataType::F32));
	const TensorShape shape_output(wo, ho, co, no);
	output.allocator()->init(TensorInfo(shape_output, 1, DataType::F32));
	PadStrideInfo neconv_info(sw, sh, pw, ph, DimensionRoundingType::CEIL);
	neconv.configure(&input, &weights, &biases, &output, neconv_info);
	input.allocator()->allocate();
	Window input_window;
	input_window.use_tensor_dimensions(input.info());
	Iterator input_it(&input, input_window);
	execute_window_loop(input_window, [&](const Coordinates &id)
	{
		*reinterpret_cast<float *>(input_it.ptr()) = src_data[id[3]*ci*hi*wi + id[2]*hi*wi + id[1]*wi + id[0]];
	},
	input_it);
	weights.allocator()->allocate();
	Window weights_window;
	weights_window.use_tensor_dimensions(weights.info());
	Iterator weights_it(&weights, weights_window);
	execute_window_loop(weights_window, [&](const Coordinates &id)
	{
		*reinterpret_cast<float *>(weights_it.ptr()) = weights_data[id[3]*ci*kh*kw + id[2]*kh*kw + id[1]*kw + id[0]];
	},
	weights_it);
	biases.allocator()->allocate();
	Window bias_window;
	bias_window.use_tensor_dimensions(biases.info());
	Iterator bias_it(&biases, bias_window);
	execute_window_loop(bias_window, [&](const Coordinates &id)
	{
		*reinterpret_cast<float *>(bias_it.ptr()) = bias_data[id[0]];
	},
	bias_it);
	output.allocator()->allocate();	
	neconv.run();
	Window output_window;
	output_window.use_tensor_dimensions(output.info());
	Iterator output_it(&output, output_window);
	execute_window_loop(output_window, [&](const Coordinates &id)
	{
		dst_data[id[3]*co*ho*wo + id[2]*ho*wo + id[1]*wo + id[0]] = *reinterpret_cast<float *>(output_it.ptr());
	},
	output_it);

	delete[] src_data;
	delete[] dst_data;
	delete[] weights_data;
	delete[] bias_data;
	}
	int main(int argc, const char **argv)
	{
	return test_helpers::run_example(argc, argv, main_neon_convlayer);
	}`
Thanks
Criss

**Comment by GeorgeARM** [comment]
Hello @ghostsun89 ,

This happens because the memory required to actually run this layer with our current implementation is huge. The reason behind this is that we implement the Convolution Layer using the im2col + sgemm + col2im practice, which requires reshaping of the input tensor into a matrix. The use case you have has a big kernel size, small stride and a big number of feature maps, leading to a big matrix for im2col.
We are currently implementing direct convolution routines for such cases.

**Comment by ghostsun89** [comment]
@GeorgeARM Thanks. Your answer is clear.

**Comment by GeorgeARM** [comment]
Closing this. We are planning to resolve this issue in future releases.
