### ISSUE TITLE
why compile_commands.json not generated?

### ISSUE THREAD

**Issue by Shipley1105** [ARM-software/ComputeLibrary#1086]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
23.11
**Platform:**

**Operating System:**

Ubuntu

**Problem description:**
I use `scons Werror=1 -j8 debug=0 asserts=1 neon=0 opencl=1 embed_kernels=1 os=linux arch=armv8a export_compile_commands=True`, but compile_commands.json is not generated in build folder, Could someone help me ?

**Comment by Red-Eyed** [comment]
Add 
`export CMAKE_EXPORT_COMPILE_COMMANDS=1`
Before compiling

**Comment by sleepy-hat** [comment]
Hi @Shipley1105 

You can output the compile commands during the SCons build by appending `export_compile_commands=1 build/compile_commands.json` to your build command.

For example:
`scons arch=armv8a os=linux neon=1 export_compile_commands=1 build/compile_commands.json`

You also need to have SCons >= 4.0 installed and available in your environment.
