### ISSUE TITLE
Performance in NCHW layout operations

### ISSUE THREAD

**Issue by allnes** [ARM-software/ComputeLibrary#1088]
Hello!

I saw that you write about NCHW to NHWC transfer.

<img width="862" alt="Screenshot 2024-01-29 at 14 15 16" src="https://github.com/ARM-software/ComputeLibrary/assets/15063471/b0fa7a7a-512d-4f44-8a10-2bc16f9c144b">

Could you provide list of layers in next release which will be affected?

**Comment by morgolock** [comment]
Hi @allnes 

There won't be any layers affected in 24.02. This deprecation notice is an advanced warning about our decision to focus the development efforts on NHWC in the future releases. In order to get the best performance it's better to use NHWC.

Hope this helps.
