### ISSUE TITLE
[OpenVINO 2023.2.0] ComputeLibrary/libarm_compute-static.a] sh: Argument list too long

### ISSUE THREAD

**Issue by saininav** [ARM-software/ComputeLibrary#1089]
arm_compute_version : v23.08
Openvino version: 23.2.0 [https://github.com/openvinotoolkit/openvino/tree/2023.2.0]
Build System: Yocto [Cross compilation]

ARM-ComputeLibrary is a hard dependency to build OpenVINO for ARM. It throws following error while building with YOCTO build system.

scons: *** [/data/xxxxxxx/workspace/poky/build-arm/tmp/work/cortexa57-poky-linux/openvino-inference-engine/2023.2.0/build/src/plugins/intel_cpu/thirdparty/ComputeLibrary/libarm_compute-static.a] sh: Argument list too long

Tried to pass MAXLINELENGTH, but Scons does not recognize it. 
| Unknown variables: MAXLINELENGTH

Ref:
https://github.com/openvinotoolkit/openvino/tree/2023.2.0/src/plugins/intel_cpu/thirdparty

**Comment by morgolock** [comment]
Hi @saininav 

Can you please share the command you used to build ACL?

**Comment by saininav** [comment]
/data/saininav/workspace/poky/build-arm/tmp/work/cortexa57-poky-linux/openvino-inference-engine/2023.2.0/recipe-sysroot-native/usr/bin/cmake -E env CC=aarch64-poky-linux-gcc CXX=aarch64-poky-linux-g++ /data/saininav/workspace/poky/build-arm/tmp/work/cortexa57-poky-linux/openvino-inference-engine/2023.2.0/recipe-sysroot-native/usr/bin/scons neon=1 opencl=0 openmp=0 cppthreads=1 examples=0 Werror=0 gemm_tuner=0 reference_openmp=0 validation_tests=0 benchmark_tests=0 data_layout_support=all arch=arm64-v8a estate=64 build_dir=/data/saininav/workspace/poky/build-arm/tmp/work/cortexa57-poky-linux/openvino-inference-engine/2023.2.0/build/src/plugins/intel_cpu/thirdparty/ComputeLibrary install_dir=/data/saininav/workspace/poky/build-arm/tmp/work/cortexa57-poky-linux/openvino-inference-engine/2023.2.0/build/src/plugins/intel_cpu/thirdparty/ComputeLibrary/install --jobs=8 debug=1 asserts=1 logging=0 os=linux build=cross_compile compiler_prefix="/data/saininav/workspace/poky/build-arm/tmp/work/cortexa57-poky-linux/openvino-inference-engine/2023.2.0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/" extra_cxx_flags=-Wsuggest-override\ \ -mcpu=cortex-a57\ -march=armv8-a+crc\ -mbranch-protection=standard\ -fstack-protector-strong\ \ -O2\ -D_FORTIFY_SOURCE=2\ -Wformat\ -Wformat-security\ -Werror=format-security\ \ --sysroot=/data/saininav/workspace/poky/build-arm/tmp/work/cortexa57-poky-linux/openvino-inference-engine/2023.2.0/recipe-sysroot\ \ -O2\ -pipe\ -g\ -feliminate-unused-debug-types\ -fcanon-prefix-map\ \ -fmacro-prefix-map=/data/saininav/workspace/poky/build-arm/tmp/work/cortexa57-poky-linux/openvino-inference-engine/2023.2.0/git=/usr/src/debug/openvino-inference-engine/2023.2.0\ \ -fdebug-prefix-map=/data/saininav/workspace/poky/build-arm/tmp/work/cortexa57-poky-linux/openvino-inference-engine/2023.2.0/git=/usr/src/debug/openvino-inference-engine/2023.2.0\ \ -fmacro-prefix-map=/data/saininav/workspace/poky/build-arm/tmp/work/cortexa57-poky-linux/openvino-inference-engine/2023.2.0/build=/usr/src/debug/openvino-inference-engine/2023.2.0\ \ -fdebug-prefix-map=/data/saininav/workspace/poky/build-arm/tmp/work/cortexa57-poky-linux/openvino-inference-engine/2023.2.0/build=/usr/src/debug/openvino-inference-engine/2023.2.0\ \ -fdebug-prefix-map=/data/saininav/workspace/poky/build-arm/tmp/work/cortexa57-poky-linux/openvino-inference-engine/2023.2.0/recipe-sysroot=\ \ -fmacro-prefix-map=/data/saininav/workspace/poky/build-arm/tmp/work/cortexa57-poky-linux/openvino-inference-engine/2023.2.0/recipe-sysroot=\ \ -fdebug-prefix-map=/data/saininav/workspace/poky/build-arm/tmp/work/cortexa57-poky-linux/openvino-inference-engine/2023.2.0/recipe-sysroot-native=\ \ -fvisibility-inlines-hidden\ -fsigned-char\ -ffunction-sections\ -fdata-sections\ -fdiagnostics-show-option\ -Wall\ -Wundef\ -Wmissing-declarations\ -Wno-error=deprecated-declarations\ -Wno-cpp\ -Wno-undef\ -Wno-missing-declarations\ -Wno-macro-redefined\ -Wno-array-bounds\ -Wno-stringop-overflow\ -Wno-restrict\ -Wno-suggest-override\ -fopenmp\ -fvisibility-inlines-hidden\ \ -Wall\ -Wno-unknown-pragmas\ -fvisibility=internal\ -Wno-undef\ -fPIC\ -Wno-suggest-override --silent fixed_format_kernels=True /data/saininav/workspace/poky/build-arm/tmp/work/cortexa57-poky-linux/openvino-inference-engine/2023.2.0/build/src/plugins/intel_cpu/thirdparty/ComputeLibrary/libarm_compute-static.a

**Comment by morgolock** [comment]
Hi @saininav 

Can't you just remove `/data/saininav/workspace/poky/build-arm/tmp/work/cortexa57-poky-linux/openvino-inference-engine/2023.2.0/` from your command? It's repeated multiple times adding a big number of characters.

An alternative would be building ACL with cmake see https://arm-software.github.io/ComputeLibrary/latest/how_to_build.xhtml

Hope this helps.
