### ISSUE TITLE
CpuGemmConv2d optimization affects performance on Apple M2/M2 Pro

### ISSUE THREAD

**Issue by alvoron** [ARM-software/ComputeLibrary#1092]
PR https://review.mlplatform.org/c/ml/ComputeLibrary/+/10526 makes CpuGemmConv2d slower on Apple M2 / M2 Pro.

The numbers below were collected on M2 Pro.
On `mobilenet-v2-1.0-224` CpuGemmConv2d takes 3.18 ms before the PR and 4.12 after the PR was merged.
`resnet-50-pytorch` - 16.37 ms before the PR; 19.67 ms after the PR

So, we have 20-30% performance degradation on CNN.

@sicong-li-arm @gunes-arm @aniraj01

**Comment by morgolock** [comment]
Hi @alvoron 

Thanks for reporting this.

Would you please let us know how many inferences/iterations you are running?

**Comment by alvoron** [comment]
I run model 30 sec and calculate average exec time of each operation type.
So, I have 7319 iterations of `mobilenet-v2-1.0-224` and 1536 iterations of `resnet-50-pytorch`.

**Comment by gunes-arm** [comment]
Hi @alvoron 

The mentioned patch should affect the start-up time, i.e. the first iteration only. I wonder if your runs configure() each time, or configure() only in the first iteration and run() in the remaining ones.

**Comment by alvoron** [comment]
OpenVINO uses oneDNN to call ACL's convolution. It seems oneDNN calls configure once: 
https://github.com/openvinotoolkit/oneDNN/blob/f82148befdbdc9576ec721c9d500155ee4de8060/src/cpu/acl/acl_gemm_convolution.hpp#L44

**Comment by jondea** [comment]
> OpenVINO uses oneDNN to call ACL's convolution. It seems oneDNN calls configure once via `acl_gemm_convolution_fwd_t::create_resource()` method: https://github.com/openvinotoolkit/oneDNN/blob/f82148befdbdc9576ec721c9d500155ee4de8060/src/cpu/acl/acl_gemm_convolution.hpp#L44

With `DNNL_VERBOSE` enabled, is OpenVINO recreating the resource or is it getting oneDNN cache hits? Some frameworks have their own caching mechanisms

**Comment by alvoron** [comment]
It seems the issue could be reproduced via `benchdnn` without OpenVINO.

ACL build command:
`scons neon=1 opencl=0 openmp=0 cppthreads=1 os=macos data_layout_support=all arch=arm64-v8.2-a build=native --jobs=8 os=macos build=native compiler_cache=ccache compiler_prefix="/Library/Developer/CommandLineTools/usr/bin/" --silent fixed_format_kernels=True`

onednn configure command (run in onednn root dir):
`ACL_ROOT_DIR=$PWD/../ComputeLibrary cmake -B build -DCMAKE_BUILD_TYPE=Release -DDNNL_USE_ACL=ON -DCMAKE_RULE_MESSAGES=OFF -DACL_LIBRARY=$PWD/../ComputeLibrary/build/libarm_compute.dylib -DACL_CORE_LIBRARY=$PWD/../ComputeLibrary/build/libarm_compute_core.dylib -DACL_GRAPH_LIBRARY=$PWD/../ComputeLibrary/build/libarm_compute_graph.dylib`

benchdnn build command:
`cmake --build build --target benchdnn --parallel 7`

The reproducer:
`DYLD_LIBRARY_PATH=$PWD/../ComputeLibrary/build ./build/tests/benchdnn/benchdnn --mode=P --conv --reset --allow-enum-tags-only=0 --engine=cpu --dir=FWD_B --alg=direct --dt=f32:f32:f32  --stag=acdb --wtag=any --dtag=acdb  --attr-scratchpad=user mb1_ic1280oc1001_ih1oh1kh1sh1dh0ph0_iw1ow1kw1sw1dw0pw0`

On M2 Pro I've got `min(ms):0.255333 avg(ms):0.357945` on ACL SHA `c5ab4df0c11dc66db47f2070edc719923af3367e` and `min(ms):0.042875 avg(ms):0.0624329` on SHA `4a9dbedfbfa66c2612c7461e60cd867b8aea825b`.

@morgolock could you please try to repeat these steps?

**Comment by morgolock** [comment]
Hi @alvoron 

Thanks for reporting this performance regression and providing so much detail.

We have merged a [patch](https://review.mlplatform.org/c/ml/ComputeLibrary/+/11240) fixing the problem into the main development branch and we will do a patch release of 24.02 including the fix mentioned above.

Hope this helps
