### ISSUE TITLE
CPUInfo::get().has_fp16() returns true on RaspberryPi 4

### ISSUE THREAD

**Issue by alvoron** [ARM-software/ComputeLibrary#1096]
Platform: Raspberry Pi4
ACL version: 24.02
ACL build command: `scons arch=armv7a neon=1 os=linux opencl=0 build=native -j 4 Werror=false fixed_format_kernels=1 multi_isa=0 openmp=0 cppthreads=1`

`CPUInfo::get().has_fp16()` returns true on RaspberryPi 4 (Cortex-A72). I believe, it should be false.

**Comment by alvoron** [comment]
UPD: The issue is reproducible on 32-bit Debian and not reproducible on 64-bit Debian.

**Comment by morgolock** [comment]
Hi @alvoron 

Please see the following patch fixing the problem: https://review.mlplatform.org/c/ml/ComputeLibrary/+/11242

Hope this helps

**Comment by alvoron** [comment]
@morgolock I implemented the same approach in our code :)
As soon as the fix is included in ACL release I'll upgrade ACL version and remove our custom code.

Thank you.
