### ISSUE TITLE
SingleThreadScheduler.cpp missing ?

### ISSUE THREAD

**Issue by vivek-path** [ARM-software/ComputeLibrary#110]
When I attempt 
scons Werror=0 -j8 debug=0 neon=1 opencl=0 os=bare_metal arch=armv7a cppthreads=0 openmp=0

I see:
build/arm_compute/libarm_compute-static.a(INESimpleFunction.o): In function `arm_compute::INESimpleFunction::run()':
INESimpleFunction.cpp:(.text+0x16): undefined reference to `arm_compute::CPPScheduler::get()'
INESimpleFunction.cpp:(.text+0x22): undefined reference to `arm_compute::CPPScheduler::multithread(arm_compute::ICPPKernel*, unsigned int)'
..
..
..
With cppthreads disabled can I expect any examples to compile ?
or is this missing : src/runtime/CPP/SingleThreadScheduler.cpp ?

**Comment by morgolock** [comment]
Hi @vivek-path ,  you're right, the file src/runtime/CPP/SingleThreadScheduler.cpp is missing. I think we haven't yet published the changelist including the single-thread and openmp schedulers.

The SingleThread scheduler should always build by default no matter what options you specify when you build the library.

We'll fix the problem soon.

**Comment by GeorgeARM** [comment]
Closing as its fixed in the next release. Reopen in case of an issue.
