### ISSUE TITLE
File not found conv1_weights.npy in Example graph_resnet50.cpp in computeLibrary

### ISSUE THREAD

**Issue by RavikumarLav** [ARM-software/ComputeLibrary#1104]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
->V24.02.1
**Platform:**
->Neon
**Operating System:**
->Linux

File not found conv1_weights.npy in Example graph_resnet50.cpp in computeLibrary.
Hello
I am trying test graph_resnet50.cpp on arm a78 core but getting  failed at convolution layer  file conv1_weights.npy not found
             << ConvolutionLayer(
                     7U, 7U, 64U,
                     get_weights_accessor(data_path, "**/cnn_data/resnet50_model/conv1_weights.npy**", weights_layout),
                     std::unique_ptr<arm_compute::graph::ITensorAccessor>(nullptr), PadStrideInfo(2, 2, 3, 3))
                     .set_name("conv1/convolution")
              << BatchNormalizationLayer(
                     get_weights_accessor(data_path, "**/cnn_data/resnet50_model/conv1_BatchNorm_moving_mean.npy**"),
                     get_weights_accessor(data_path, "/cnn_data/resnet50_model/conv1_BatchNorm_moving_variance.npy"),
                     get_weights_accessor(data_path, "/cnn_data/resnet50_model/conv1_BatchNorm_gamma.npy"),
                     get_weights_accessor(data_path, "/cnn_data/resnet50_model/conv1_BatchNorm_beta.npy"),
                     0.0000100099996416f)
                     .set_name("conv1/BatchNorm")

I am not able find these files in repo please let us know Where we can get these weights in the git repo to test above example.
**Problem description:**

**Comment by morgolock** [comment]
Hi @RavikumarLav 


The best way to run models is be to use ArmNN's `ExecuteNetwork`. You can download the resnet50  tflite model and run it with ArmNN. 

For more information about this please have a look at https://github.com/ARM-software/ComputeLibrary/issues/1077#issuecomment-1792265699

Hope this helps
