### ISSUE TITLE
CANNOT LINK EXECUTABLE: library "libOpenCL.so" not found

### ISSUE THREAD

**Issue by JasOnRadC1iFfe** [ARM-software/ComputeLibrary#111]
Using NDK standalone toolchains, I have compiled my library and convolution with option OpenCL=1. But after I pushed it on Android device(With ARM mali GPU), I could not run the cl_convolution_aarch64 successfully but facing the error: CANNOT LINK EXECUTABLE: library "libOpenCL.so" not found
![image](https://cloud.githubusercontent.com/assets/5286913/26097405/0115fc68-3a57-11e7-8516-8c9fe7af9e92.png)

I found that my Android device has no libOpenCL.so in its system libraries but with the /system/lib64/egl/libGLES_mali.so instead. So I tried to create a symlink between mali.so and openCL.so

Here is my command (I am not sure if it is right or not): 
> ln -s /system/lib64/egl/libGLES_mali.so  /system/lib64/libOpenCL.so

Since the device is not rooted, I can not modify the system files, which comes out the error below:
![image](https://cloud.githubusercontent.com/assets/5286913/26097368/e9969264-3a56-11e7-8382-a524068be4b4.png)

So, should I recompile the example with the libGLES_mali.so that pulling out from my device, or could you guys tell me how to create the fine symlink without rooting the device?

**Comment by AnthonyARM** [comment]
Try to create the symlink somewhere where you have permissions: like for example where you uploaded the binary:
```ln -s /system/lib64/egl/libGLES_mali.so /data/local/tmp/libOpenCL.so```
Then just set `LD_LIBRARY_PATH` to point at that directory:
```LD_LIBRARY_PATH=. ./cl_convolution_aarch64```

**Comment by JasOnRadC1iFfe** [comment]
Perfectly fixed! Very appreciated!!

**Comment by AnthonyARM** [comment]
No worries :)
