### ISSUE TITLE
How to set priority of the application running on GPU?

### ISSUE THREAD

**Issue by qianfei11** [ARM-software/ComputeLibrary#1111]
**Output of 'strings libarm_compute.so | grep arm_compute_version':** arm_compute_version=v24.04 Build options: {'arch': 'arm64-v8a', 'neon': '1', 'opencl': '1', 'embed_kernels': '1', 'extra_cxx_flags': '-fPIC -Wno-error=maybe-uninitialized', 'benchmark_tests': '0', 'validation_tests': '0', 'os': 'linux'} Git hash=b'4fda7a803eaadf00ba36bd532481a33c18952089'

**Platform:** Hikey960 (Mali-G71)

**Operating System:** Linux

**Problem description:** I want to test the job preemption on Mali GPU, and I find the `cl_khr_priority_hints` extension on OpenCL, but my GPU (Mali-G71) does not have this feature. Is there any way to set the priority of a GPU application? Or, is there any where else I can ask for the answer?

**Comment by morgolock** [comment]
Hi @qianfei11 

A better place to discuss this would be [Arm Developer Forum](https://community.arm.com/support-forums/). Please try asking there.

Hope this helps.
