### ISSUE TITLE
Accuracy problem for NEPoolingLayer - PoolingType::AVG - RoundingType::CEIL - DataLayout::NCHW 

### ISSUE THREAD

**Issue by allnes** [ARM-software/ComputeLibrary#1113]
Hi,

I try to use NEPoolingLayer - PoolingType::AVG - RoundingType::CEIL - DataLayout::NCHW in our OpenVINO CPU plugin and my tests is failed by accuracy.

**Output of 'strings libarm_compute.so | grep arm_compute_version':**

arm_compute_version.embed - f2eda6665c12d568e179f5b0e7a24ccdc0ac824d

**Platform:**

Mac Studio - Apple M2 Max

**Operating System:**

MacOS Sonoma - Version 14.5 (23F79)

**Reproducer:**
[main.cpp.txt](https://github.com/user-attachments/files/15902941/main.cpp.txt)
[avg_pool_ref.hpp.txt](https://github.com/user-attachments/files/15902940/avg_pool_ref.hpp.txt)

**Data where it was reproduced:**
[arg.txt](https://github.com/user-attachments/files/15902955/arg.txt)
[out_acl.txt](https://github.com/user-attachments/files/15902956/out_acl.txt)
[out_ref.txt](https://github.com/user-attachments/files/15902957/out_ref.txt)

**Debug log from application:**
[log.txt](https://github.com/user-attachments/files/15902968/log.txt)

**Comment by morgolock** [comment]
Hi @allnes 

Could you please try using NHWC rather than NCHW? NCHW has been deprecated as stated in the github page:

> Deprecation Notice 24.01 announcement: NCHW data format specific optimizations will gradually be removed from the code base in future releases. The implication of this is that the user is expected to translate NCHW models into NHWC in order to benefit from the optimizations.

You'll get the best performance using NHWC.

Hope this helps

**Comment by allnes** [comment]
Thank you for answer
