### ISSUE TITLE
armcompute on Mali

### ISSUE THREAD

**Issue by Subarukun** [ARM-software/ComputeLibrary#112]
Hi,

Currently we are looking to implement Neural Network on Mali GPU .Can you point us to any Mobile device/hardware platform that has Opencl drivers implementation.

Also can you tell us which platform or hardware are you using to validate the ARM compute CL methods(function/module) implementations on Mali.

Thanks.

**Comment by AnthonyARM** [comment]
Hi, 

I'd recommend using a Linux development board rather than an Android device if possible. Something like:
HiKey Kirin 960 (Mist recent dev board, bifrost gpu, 64 bit cpu) 
Firefly rk3399 (64bit cpu, Midgard GPU) 
Firefly Rk3288 (32 bit cpu, older Midgard gpu) 

You also have a selection of Chromebooks if you prefer a laptop form factor. 

Hope this helps

**Comment by Subarukun** [comment]
Thanks..

**Comment by kaishijeng** [comment]
Does Hikey Kirin 960 have a linux development board? I only see Android support, not Ubuntu. on this board.
>>HiKey Kirin 960 (Most recent dev board, bifrost gpu, 64 bit cpu)

Thanks,

**Comment by AnthonyARM** [comment]
It hasn't been released yet but [Linaro and Huawei are working on it] (https://www.xda-developers.com/linaro-and-huawei-announce-the-hikey-960-a-professional-arm-board-for-development/)

**Comment by Subarukun** [comment]
Hi Anthony,

As per the Samsung documentation given in the below link. They are saying that Samsung Exynos 7870 Octa will support opencl 1.2 .This chipset is used in the samsung galaxy on Nxt and Samsung Galaxy J7.
So if we got hold on one of this phones .Can we run arm compute CL code ? or are there any other dependencies..

https://www.notebookcheck.net/Samsung-Exynos-7870-Octa-Notebook-Processor.185344.0.html

Thanks

**Comment by AnthonyARM** [comment]
Hi,

We haven't tested on these particular phones, but if they have a Mali Midgard ( 6xx or above) or Mali Bifrost (G7x) GPU then it should work yes.
Sometimes manufacturers decide to not enable OpenCL on their platform, so you might want to check on internet first whether or not other people successfully managed to run OpenCL content on these phones.

Regarding the library: you are right, there is no dependency other than having a fairly recent ( r8p0 or above: i.e less than 2 years old) working OpenCL 1.1 driver.

**Comment by Subarukun** [comment]
ok thanks..
