### ISSUE TITLE
NEGEMMLowpMatrixMultiplyCore: why QASYMM8 sources are not supported for F32 output

### ISSUE THREAD

**Issue by eshoguli** [ARM-software/ComputeLibrary#1122]
In accordance with documentation [NEGEMMLowpMatrixMultiplyCore](https://arm-software.github.io/ComputeLibrary/v24.06/classarm__compute_1_1_n_e_g_e_m_m_lowp_matrix_multiply_core.xhtml) `F32` dequantised output is supported only for `QASYMM8_SIGNED` values in `src0` and `scr1`:

src0 | src1 | src2 | dst
-- | -- | -- | --
QASYMM8_SIGNED | QASYMM8_SIGNED | F32 | F32

Why `F32` is not supported for `QASYMM8` sources? Are you going to support `QASYMM8` sources in the future? Thanks!

**Comment by morgolock** [comment]
Hi @eshoguli 

The following [patch](https://review.mlplatform.org/c/ml/ComputeLibrary/+/11900) adds support for 
```
Valid data type configurations:
     * |src0           |src1               |src2     |dst            |
     * |:--------------|:------------------|:--------|:--------------|
     * |QASYMM8        |QASYMM8_SIGNED     |F32      |F32            |
```

Could you please confirm this is what you need?

**Comment by eshoguli** [comment]
It works from https://review.mlplatform.org/ml/ComputeLibrary, thanks!
