### ISSUE TITLE
gemm+silu fused operator is not supported in ACL

### ISSUE THREAD

**Issue by TianyuLi0** [ARM-software/ComputeLibrary#1125]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v24.04 Build options: {'Werror': '1', 'build_dir': '//acl/build', 'debug': '0', 'neon': '1', 'opencl': '0', 'os': 'linux', 'openmp': '1', 'cppthreads': '0', 'arch': 'armv8.2-a', 'multi_isa': '1', 'fixed_format_kernels': '1', 'build': 'native'} Git hash=b'4fda7a803eaadf00ba36bd532481a33c18952089'

**Platform:**
Neoverse N2

**Operating System:**
Ubuntu 22.04

**Problem description:**
gemm+silu fused operator is not supported in ACL

LLM use case:  llama like models use [silu](https://github.com/huggingface/transformers/blob/765732e92c17a17682a5efd4aa4323e5ab01fe07/src/transformers/models/llama/configuration_llama.py#L125) activation with gemm.

Similar issue
https://github.com/ARM-software/ComputeLibrary/issues/1083

**Comment by morgolock** [comment]
Hi @TianyuLi0 

We currently don't have plans to implement silu in ACL. 

[KleidiAI](https://www.arm.com/markets/artificial-intelligence/software/kleidi) is better suited to accelerate the type of workloads you find in these models than ACL. Please have a look at this [article](https://community.arm.com/arm-community-blogs/b/ai-and-ml-blog/posts/generative-ai-on-mobile-on-arm-cpu) discussing LLM acceleration on mobile CPUs.

Alternatively you are welcome to submit a patch contributing to ACL.  Please see our [contribution guide](https://arm-software.github.io/ComputeLibrary/latest/usergroup1.xhtml) for more information on how to add a new operator 

- [Contribution Guidelines](https://arm-software.github.io/ComputeLibrary/latest/contribution_guidelines.xhtml)
- [How to Add a New Operator](https://arm-software.github.io/ComputeLibrary/latest/adding_operator.xhtml)

Hope this helps
