### ISSUE TITLE
CLTensorAllocator::allocate fails (_mapping = NULL)

### ISSUE THREAD

**Issue by joel-mi** [ARM-software/ComputeLibrary#113]
I'm trying to use Arm Compute Library for running on MALI GPU; the command I'm entering on Cygwin64 Terminal for this purpose is :
scons.bat Werror=1 -j1 debug=1 asserts=1 neon=0 opencl=1 embed_kernels=1 os=android arch=arm64-v8a
I'm using Android Studio as IDE under Windows-7
The first tensor I'm trying to load with actual data is the weights 4D-tensor used by CLConvolutionLayer, and it results in a crash - this seems to be due to _mapping = NULL as result of CLTensorAllocator::allocate

I previously used Arm Compute Library for running on NEON and I didn't see any problem of this kind. My code is the same in both cases - I just changed NEConvolutionLayer to CLConvolutionLayer and Tensor to CLTensor; I also added a call to CLScheduler::default_init
Is there some additional change I should make in my code for working with openCL ? Maybe some additional initialization for memory allocations ?
Thanks,
Joel

**Comment by mpflanzer** [comment]
You need to map `CLTensor`s before you can access them from the host code. (And unmap them before running the CL functions). Have a look at this example in the documentation: https://arm-software.github.io/ComputeLibrary/v17.05/index.xhtml#S4_4_2_cl_neon

**Comment by joel-mi** [comment]
OK, I'll try that - but note that I'm NOT mixing openCL and NEON in the same application, these are 2 different versions of my application - its either openCL or NEON, but no mix

**Comment by joel-mi** [comment]
Seems to be working now - Thanks !

**Comment by joel-mi** [comment]
re-opening just for a small remark / suggestion for improving documentation :
- in documentation, the matter of map / unmap is mentioned only in relation to mixing openCL and NEON kernels, although it applies also to using openCL only (without NEON kernels); I think it would be worth mentioning that
