### ISSUE TITLE
CMake lacks `install` target

### ISSUE THREAD

**Issue by BwL1289** [ARM-software/ComputeLibrary#1132]
**Platform:**
Aarch64 Linux

**Problem description:**
When trying to compile from source using CMake and Ninja, I see the following error:
```
30.90 ninja: error: unknown target 'install'
```

It seems CMake lacks an `install` target. 

Have tried manually installing libs, its symlinks, and headers automatically but to no avail.

Here's an [example](https://github.com/aws/aws-iot-device-sdk-embedded-C/pull/1519/files#diff-7021d478f66d585e3f9025b7212b1ca40b1db63995592041e28b5dd819c06e53R1) of how AWS implemented this for their C SDK.

This is likely an extension of #1048.

**Comment by BwL1289** [comment]
@morgolock any chance to make this a priority?

**Comment by morgolock** [comment]
Hi @BwL1289 

Thanks for raising this, I'll discuss it with the team.

**Comment by BwL1289** [comment]
Thank you.

**Comment by BwL1289** [comment]
Hi @morgolock. Not trying to be a bother. Please let me know if the team thought this was worth prioritizing. Thank you!

**Comment by morgolock** [comment]
Hi @BwL1289 

Yes we will do it, I will ask for this to be in the next release. Once I get confirmation I will let you know.

**Comment by BwL1289** [comment]
Thanks @morgolock.

**Comment by BwL1289** [comment]
@morgolock yes that helps. Thank you.

**Comment by BwL1289** [comment]
@morgolock do you have an updated timeline? Thank you.

**Comment by morgolock** [comment]
Hi @BwL1289 

We are currently discussing it, once we have a good idea of the effort I will give you an update. I'll know more in the coming days.

Hope this helps

**Comment by BwL1289** [comment]
@morgolock following up again. Can you please let me know if the team plans to fix this?

**Comment by morgolock** [comment]
Hi @BwL1289 

The following [patch](https://review.mlplatform.org/c/ml/ComputeLibrary/+/12844) will solve the problem. This fix will be present in v24.11

Hope this helps

**Comment by BwL1289** [comment]
@morgolock thank you.

**Comment by BwL1289** [comment]
FWIW, I forked this repo and implemented the change manually. I can confirm it works.

**Comment by morgolock** [comment]
Hi @BwL1289 

Apologies for the confusion, I've reopened the issue.

We cannot merge the PR on github unfortunately, we only publish a snapshot of the main dev repo on github and if we merge a PR it will go out of sync with the release branch in the dev repo.

Apologies for the confusion. This patch will be present in our next release 24.11.1.
