### ISSUE TITLE
When used msvc clang-cl, kernel a64_fp16_4x4_3x3 isn't built

### ISSUE THREAD

**Issue by allnes** [ARM-software/ComputeLibrary#1135]
Hi,
I used Windows system on Snapdragon ARM CPU and noticed that kernel can't build: 
`arm_conv::winograd::weight_transform::a64_fp16_4x4_3x3` 
and other fp16 kernels in:
`src/core/NEON/kernels/convolution/winograd/input_transforms`
`src/core/NEON/kernels/convolution/winograd/output_transforms`
`src/core/NEON/kernels/convolution/winograd/weight_transforms`
This problem create failure of our build in OpenVINO on this system. 
Could you tell are there reasons for that?

**Comment by morgolock** [comment]
Hi @allnes 

Presently we support only `armv8a` targets for Windows, could you please let us know which options are you using to build ACL when you see this error?

**Comment by allnes** [comment]
Hi this command was generated:
`scons neon=1 opencl=0 openmp=0 cppthreads=1 examples=0 Werror=0 gemm_tuner=0 reference_openmp=0 validation_tests=0 benchmark_tests=0 data_layout_support=all arch=arm64-v8.2-a estate=64 os=windows build=native `

**Comment by allnes** [comment]
armv8a arch disable fp16 kernels, do you have plan to support arm64-v8.2-a instruction set?

**Comment by morgolock** [comment]
HI @allnes 

Yes, we will look into adding support for `arm64-v8.2-a`

**Comment by morgolock** [comment]
Hi @allnes 

The following [patch](https://review.mlplatform.org/c/ml/ComputeLibrary/+/12156) fixes the linker errors.

Hope this helps.

**Comment by allnes** [comment]
Hi @morgolock 

Thank you, patch is worked, we'll wait for the release
