### ISSUE TITLE
Possible bug in `CpuIm2ColKernel.cpp`

### ISSUE THREAD

**Issue by VladislavZavadskyy** [ARM-software/ComputeLibrary#1140]
Hello, I'm trying to make sense of the code, and stumbled onto [this piece of code](https://github.com/ARM-software/ComputeLibrary/blob/de7288cb71e6b9190f52e50a44ed68c309e4a041/src/cpu/kernels/CpuIm2ColKernel.cpp#L309):
```c++
_convolved_dims  = scaled_dimensions(src->dimension(width_idx), dst->dimension(height_idx), _kernel_width,
                                     _kernel_height, _conv_info, _dilation);
```

Shouldn't it be `src->dimension(height_idx)`?

Sorry in advance if this is intended, as I've said I'm only trying to make sense of it all, to add a custom kernel. I would be grateful if you could explain why `dst` is there, if it's not a bug. Thanks!

**Comment by morgolock** [comment]
Hi @VladislavZavadskyy 

Thanks for raising this. This [patch](https://review.mlplatform.org/c/ml/ComputeLibrary/+/12552) solves the problem.

Hope this helps
