### ISSUE TITLE
How to use the provided SVE GEMM code？

### ISSUE THREAD

**Issue by yohuna77777** [ARM-software/ComputeLibrary#1142]
Hello, I am considering using the SVE instruction set to optimize GEMM operators. I found that although the repository has relevant codes, there is no example telling me how to call these gemm based on the SVE instruction set. Can you provide a relevant usage example?I am looking forward to your reply!

**Comment by morgolock** [comment]
Hi @yohuna77777 

The library will take care of this for you, there is no need to do anything different when calling the operators. At runtime, the library will check if the cpu supports SVE and if this is the case choose the best SVE kernel for the given workload. 

When you build the library just make sure that you use the option `multi_isa=1`. The prebuilt binaries we publish for Linux or Android they are both multi_isa.

Please see the [sgemm example](https://github.com/ARM-software/ComputeLibrary/blob/main/examples/neon_sgemm.cpp) included in the library. 

Hope this helps.

**Comment by yohuna77777** [comment]
> Hi @yohuna77777
> 
> The library will take care of this for you, there is no need to do anything different when calling the operators. At runtime, the library will check if the cpu supports SVE and if this is the case choose the best SVE kernel for the given workload.
> 
> When you build the library just make sure that you use the option `multi_isa=1`. The prebuilt binaries we publish for Linux or Android they are both multi_isa.
> 
> Please see the [sgemm example](https://github.com/ARM-software/ComputeLibrary/blob/main/examples/neon_sgemm.cpp) included in the library.
> 
> Hope this helps.

Thanks for your reply. I used the prebuilt version (v24.08) to compile examples/neon_sgemm.cpp. After running the executable file, I disassembled and checked the corresponding code and found that the sve register was not used, but the neon register was used. That is to say, NEGEMM does not contain the sve optimized operator. Which runtime operator should I call to use the sve kernel? (The above experiment was conducted on an arm server that supports sve256)
