### ISSUE TITLE
Does this provide support for SVE2 on ARM Cortex A76?

### ISSUE THREAD

**Issue by Abhranta** [ARM-software/ComputeLibrary#1144]
Hi, I am bit of a beginner here and I need some help with this

**Output of 'strings libarm_compute.so | grep arm_compute_version':**

**Platform:**
Raspberry Pi 5 (ARM Cortex A76)
**Operating System:**
Linux

**Problem description:**
I actually want to run llama3 8B model on a pi. For this I am using llama.cpp. Whenever I try to run it via NEON or SVE2 optimized quant types (Q4_0_4_4 and Q4_0_8_8 respectively), it doesn't run fast enough. I am getting a 2 token/sec with NEON and 1.5 token/sec with SVE2. Can using this library help ?

**Comment by morgolock** [comment]
Hi @Abhranta 

[KleidiAI](https://www.arm.com/markets/artificial-intelligence/software/kleidi) is better suited to accelated the type of workloads you find in these models than ACL. Please have a look at this [article](https://community.arm.com/arm-community-blogs/b/ai-and-ml-blog/posts/generative-ai-on-mobile-on-arm-cpu) discussing LLM acceleration on mobile CPUs.

Hope this helps
