### ISSUE TITLE
Example programs fail to build due to link problems - build script presumes availability of statically built libstdc++

### ISSUE THREAD

**Issue by andrew-wja** [ARM-software/ComputeLibrary#115]
When building the library via scons using this command line, some of the example programs fail to build.

`scons -j8 arch=arm64-v8a opencl=no neon=yes cppthreads=no openmp=no os=bare_metal`

This is the relevant error message from scons:

```
aarch64-linux-gnu-g++ -o build/arm_compute/neon_scale -static build/arm_compute/examples/neon_scale.o build/arm_compute/test_helpers/Utils.o -Lbuild -Lbuild/arm_compute -L. -larm_compute-static
/usr/lib/gcc/aarch64-linux-gnu/6.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
scons: *** [build/arm_compute/neon_copy_objects] Error 1
/usr/lib/gcc/aarch64-linux-gnu/6.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
scons: *** [build/arm_compute/neon_convolution] Error 1
/usr/lib/gcc/aarch64-linux-gnu/6.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
scons: *** [build/arm_compute/neon_scale] Error 1
scons: building terminated because of errors.
```

The issue is the use of `-static` in the build line for the example programs. Not all platforms provide a statically built libstdc++. If the intention is to link only the Compute Library statically, the build line can be changed to accomodate that by removing `-static`, and adding `-Wl -Bstatic ` immediately before `-larm_compute-static`.

**Comment by andrew-wja** [comment]
Just to clarify: the library itself builds just fine, the only build failures are the example programs. Disabling the building of the example programs results in a successful build of the library.

**Comment by AnthonyARM** [comment]
I'm confused: typically you cannot use shared libraries on bare metal which is why everything has to be linked statically (including the libc++) 
Which platform are you targeting?

**Comment by andrew-wja** [comment]
I'm targeting arm-v8a (the A-53 core specifically). For sure, things need to be built statically for the bare metal, and the library _successfully_ builds statically for the bare metal. 

It is the example programs which fail to build statically, not the library. However, because the example programs are an unconditional part of the build process, the build fails overall even though the static build of the library succeeds.

**Comment by AnthonyARM** [comment]
Not if you use the latest version of the library: there is an `examples=0` flag now available to exclude the build of the examples
