### ISSUE TITLE
Generating embed_kernels for GPU implementation

### ISSUE THREAD

**Issue by vijaypalvai** [ARM-software/ComputeLibrary#116]
Hi 

We are trying to generate clembed files to embed CL kernels in libarm_compute.so. we are using cmake build env. i am trying to understand the following construct. 

 **Generate embed files**
    if env['embed_kernels']:
        cl_files  = Glob('src/core/CL/cl_kernels/*.cl') + Glob('src/core/CL/cl_kernels/*.h')
        source_list = []
        for file in cl_files:
            source_name = file.rstr()
            source_list.append(source_name)
            embed_files.append(source_name + "embed")
        generate_embed = env.Command(embed_files, source_list, action=resolve_includes)
        Default(generate_embed)

my understanding from above is: the all kernels from cl_kernel folder are copied and renamed to .clembed and include files are replaced inline. 

could someone please confirm and clarify what does the following two lines do:
        Default(generate_embed)

is this including the clembed files into libarm_compute.so ?

Thanks in advance.

Regards

**Comment by AnthonyARM** [comment]
The Default line is actually just a SCons command to tell it to execute this action by default (When no specific target is provided on the build line) so you can just ignore it. 

The rest of the code is like you said to inline the includes and embed the source code inside the binary.

**Comment by vijaypalvai** [comment]
Really appreciate your quick reply,  Thank you.
actually my goal is to improve time performance of execution of cl kernels, with EMBEDDED_KERNELS, CLschedule would still do Load, build and execute 
i am trying to replace this with just execute. something like offline compilation of CL kernels, so the performance time could be improved.
https://www.fixstars.com/en/opencl/book/OpenCLProgrammingBook/online-offline-compilation/

I  am trying to compile the kernels externally using Opencl compiler.

**Comment by AnthonyARM** [comment]
I'm not sure what you mean by "compile the kernels externally using Opencl compiler".

You should be able to just use the online compiler and save the built programs:
```
clCreateProgramWithSource();
…
clBuildProgram();
…
clCreateKernel();
…
clCreateKernel();
…
clGetProgramInfo(CL_PROGRAM_BINARY_SIZES);
…
clGetProgramInfo(CL_PROGRAM_BINARIES);
…
fwrite(kernel.bin)
```

It is important to call `clCreateKernel` or the binary you will read back will be so LLVM IR rather than the actual binary (Which means it will be slow to load)

**Comment by vijaypalvai** [comment]
@AnthonyARM , thank you for your replies, yes, i was able to generate CL kernel binary by following the API calls you listed above.
