### ISSUE TITLE
Question on the sample code "Multi-threading"

### ISSUE THREAD

**Issue by JasOnRadC1iFfe** [ARM-software/ComputeLibrary#118]
Here I want to use partial cores of my CPU. And I found the solution at Section Multi-threading. But here I can't find where this variable "_threads" comes from? Do you have any declaration for it? 

 ![image](https://cloud.githubusercontent.com/assets/5286913/26383508/c0634166-4065-11e7-83a5-d6719ef5368e.png)

**Comment by JasOnRadC1iFfe** [comment]
I guess this is a private variable in Class since the variable has an underscore as prefix.

**Comment by AnthonyARM** [comment]
You are right `_threads` is a private member of the class (It's the pool of threads), if you want to set the number of threads from your application you can do: 
```arm_compute::Scheduler::get().set_num_threads(num_threads);```

[See documentation](https://arm-software.github.io/ComputeLibrary/v17.05/classarm__compute_1_1_c_p_p_scheduler.xhtml#ae9dc1846ff1612778bbac85d46344aef)
