### ISSUE TITLE
Mixing NE-Layers and CL-Layers in same implementation

### ISSUE THREAD

**Issue by joel-mi** [ARM-software/ComputeLibrary#119]
Till now we've been trying implementations that are either all-NEON or all-CL, so that all tensors were of the same type - either Tensor or CLTensor. This way, we could easily use the same tensor as output of layer N and input to layer N+1, with no need to copy data from one layer to the next.

How is this going to change in a mixed implementation ? For example, if layer N runs on NEON (NE-Layer) and layer N+1 runs on GPU (CL-Layer) ?
Will we then have to define 2 tensors - one of type Tensor for output from layer N, and one of type CL Tensor for input to layer N+1, and copy the data from 1st tensor to 2nd tensor ? Or is there a way to avoid that ?

**Comment by AnthonyARM** [comment]
This is explained in the [documentation](https://arm-software.github.io/ComputeLibrary/v17.05/index.xhtml#S4_4_2_cl_neon): OpenCL objects can be used in NEON functions but this is the application's responsibility to map / unmap the objects before switching from one device to the other.

We've got an example demonstrating this: have a look at `examples/neoncl_scale_median_gaussian.cpp`

**Comment by joel-mi** [comment]
I got it working
Thanks !

**Comment by GeorgeARM** [comment]
Closing! Reopen if needed!
