### ISSUE TITLE
is Concat function supported ?

### ISSUE THREAD

**Issue by joel-mi** [ARM-software/ComputeLibrary#124]
Does Arm Compute Library provide a way of concatenating 2 input tensors into 1 output tensor ?

**Comment by steniu01** [comment]
The DepthCacatenateKernel provided by the library can concatenate two input tensors along the depth dimension.

**Comment by steniu01** [comment]
We haven't released the depth concatenate function yet but it is under our plan.

**Comment by joel-mi** [comment]
@steniu01 
do you know when it will be made available ?

**Comment by steniu01** [comment]
@joel-mi , the CLDepthConcatenate function will be available in the next release, which is coming at next few weeks. It is a memory copy based depth concatenate implementation.  
We don't have NEDepthConcatenate implementation yet, but don't see a problem to add into our next quarter plan.

**Comment by joel-mi** [comment]
thanks !

**Comment by GeorgeARM** [comment]
Closing the question. Concat function will be part of next release for CL. Reopen if required.
