### ISSUE TITLE
arm compute mali version on android phones

### ISSUE THREAD

**Issue by mkamrao** [ARM-software/ComputeLibrary#125]
Hello

Could you please suggest the Android phones on which the ARM Compute library for Mali GPU has been tested. 

Thanks
kamrao

**Comment by AnthonyARM** [comment]
Hi,

It should work on most of the recent Mediatek, Huawei or Samsung Mali based phones. (Mate 8, Mate 9, Honor 7, Note 4, Note 5, etc.)

**Comment by mkamrao** [comment]
Thank you.

**Comment by mkamrao** [comment]
Hello Anthony

We are planning to procure Samsung galaxy Note4 or Huawei Honor 7 Android phone and use the ARM Compute library (Mali version) for our application. 
- Was the Mali version tested on these phones (unrooted phones) 
-  do you foresee any issues with respect to OpenCL compatibility for ARM Compute library on these phones

If not, could you please suggest any Android phones on which the ARM Compute library (Mali version) has been successfully used and tested.

Thank you
kamrao

**Comment by AnthonyARM** [comment]
Hi,

We haven't tried on the Note4 but I believe OpenCL is available on it so it should work. (We've successfully tested on the Note 5 though)

The Honor 7 we have didn't have OpenCL enabled, so unless there has been an update for this platform I don't believe this will work. (However the library has been tested on the P9, mate 8 and mate 9)

Hope this helps,

Anthony

**Comment by kaishijeng** [comment]
Anthony,

  How do you test computelibrary on an Andorid pohone which is a java-based system but computelibrary is a c library?

Thanks,

**Comment by mkamrao** [comment]
Hello Anthony...Thank you, for your inputs.

**Comment by AnthonyARM** [comment]
Refer to the Android documentation to find out how to load C/C++ library from Java [Sample Hello JNI](https://developer.android.com/ndk/samples/sample_hellojni.html)

**Comment by mkamrao** [comment]
Hello Anthony

We are using ARM Compute library and created an application using the CNN layer APIs.
(We have used Samsung Galaxy Note 5 as suggested by you in above email chain. The OpenCL version in this phone is OpenCL1.1v1.r7p0).

We are getting error in "CLScheduler::get().default_init()", while running the application:
(Inside CLKernelLibrary::get().init("", cl::Context::getDefault(), cl::Device::getDefault()) at cl::Context::getDefault()  ) and application exits.

Could you please suggest on what could be the issue.

Thank you
kamrao

**Comment by AnthonyARM** [comment]
As explained in these comments( [comment 1](https://github.com/ARM-software/ComputeLibrary/issues/135#issuecomment-309370689) / [comment 2](https://github.com/ARM-software/ComputeLibrary/issues/135#issuecomment-311281464)) this is probably because the libOpenCL.so library isn't found in your path.

**Comment by mkamrao** [comment]
Hello Anthony

The program exits even before reaching dlopen() in CLSymbols(), as mentioned above.

Also, we have made sure, the path is hard-coded for libGLES_mali.so (as per your comments 1/2 ) - but, still the issue persists as above.

**Comment by AnthonyARM** [comment]
If you do:
```cpp
cl::Context context = cl::Context::getDefault();
cl::CommandQueue queue = cl::CommandQueue::getDefault();
```
in your application, does it work ?

Also 
```cpp
CLKernelLibrary::get().init("", cl::Context::getDefault(), cl::Device::getDefault()) 
```
This is incorrect, the first parameter should be empty (If the kernels are embedded in the library just set it to "."

**Comment by mkamrao** [comment]
Hello Anthony

Tried the above steps.

Now, the application exits with error immediately after: cl::Context context = cl::Context::getDefault();

**Comment by AnthonyARM** [comment]
Well, it fails before you try to use the library, therefore it means it's a problem with your device and OpenCL set up: your application doesn't manage to create an OpenCL context.

**Comment by mkamrao** [comment]
ok. Thank you.
