### ISSUE TITLE
v17.05 failed to build CL examples

### ISSUE THREAD

**Issue by shiwf** [ARM-software/ComputeLibrary#126]
In v17.05 changlog, "Library does not link against OpenCL anymore (It uses dlopen / dlsym at runtime instead to determine whether or not OpenCL is available)." As I understand, we didn't need libOpenCL.so to build the arm compute library any more, but when I built the library and examples with the command below:
"CXX=clang++ CC=clang scons Werror=1 -j8 debug=0 neon=0 opencl=1 embed_kernel=1 os=android arch=armv7a examples=1", I met errors that cannot find "-lOpenCL".
Did we still need the libOpenCL to build the examples or the examples code need to update for v17.05?
Thanks.

**Comment by AnthonyARM** [comment]
You don't need libOpenCL.so to build the library, however you need it to build the examples.
So either build with `examples=0` or link against the stub OpenCL library provided in the repo.

**Comment by shiwf** [comment]
Oh, I see, thanks.
