### ISSUE TITLE
Detect ISA features at runtime

### ISSUE THREAD

**Issue by afaerber** [ARM-software/ComputeLibrary#13]
Linux distros can't tell at build time whether the ARMv7-A hardware a user will run it on will support NEON (e.g., tegra20 did not). Therefore the library should drop the `neon=1` build-time option and instead detect availability or absence of NEON at initialization time.

Same for `arch=arm64-v8a` vs. `arch=arm64-v8.2-a` probably.

**Comment by AnthonyARM** [comment]
I think the API level of the ARM Compute Library is too low for a feature like this: the library doesn't provide any technology (OpenCL / NEON) abstraction: you need to instantiate kernels / functions for a particular technology therefore what would you expect to happen if you instantiate a NEON kernel on a platform which doesn't support NEON ?

I think a runtime configuration would only work in a higher level library where for example you instantiate a "Convolution" function and let the library decides if it's going to run on NEON or OpenCL.

**Comment by afaerber** [comment]
Well, consider it general feedback that this library still looks very Android-y, apparently expecting to be built per target system as opposed to once per base architecture for Linux. At least the documentation will need improvements to tell Linux distros how it's supposed to be built not knowing the hardware. If always enabling NEON is safe even when running on non-NEON systems, that would be a very helpful sentence to add, for instance.

For a pure NEON-only library there is already http://projectne10.github.io/Ne10/ from your ARM colleagues that you could've contributed to instead of rolling a new one.

Therefore it seemed to me the idea of arm_compute was to have some form of abstraction of hardware features like NEON and OpenCL, i.e. a higher-level library as you put it. But I admit to not having studied the API because I stumbled over the build instructions already.

**Comment by AnthonyARM** [comment]
I'm sorry, I don't understand what you mean: why do you need to know your target system to compile for Linux ?
[As stated in the documentation](https://arm-software.github.io/ComputeLibrary/v17.03.1/index.xhtml#S3_2_linux): the only thing you need to know is the target architecture of your CPU.

As far as I know the tegra20 is the only SoC armv7 and above which doesn't have NEON.

ARM Compute provides a collection of optimised NEON / OpenCL routines to accelerate libraries / applications development but it doesn't aim at abstracting any HW / Technology from the user.

The overlap of features with NE10 is very limited which is why we decided to create a separate library.

**Comment by afaerber** [comment]
I mean this [RPM specfile](https://build.opensuse.org/package/view_file/home:a_faerber:mali/arm_compute/arm_compute.spec?expand=1) snippet:

```
scons os=linux build=native Werror=0 \
%ifarch %ix86 x86_64
      arch=x86 neon=0 opencl=1 \
%else
%ifarch aarch64
      arch=arm64-v8a neon=1 \
%else
%ifarch armv7hl
      arch=armv7-a neon=0 \
%endif
%endif
      opencl=1 \
%endif
      ...
```

Even for `arch=` we would never be able to specify `arm64-v8.2-a` because at build-time we don't distinguish whether we will run on 8.0, 8.1, 8.2, etc. Thus, wherever possible, any such detailed options should be detected at run-time (by the library or its caller) rather than determined at build-time. The only thing you should need to know at build-time is whether the compiler supports it, and that can be detected by compile-tests (i.e., in `sconscript`). Multiple libraries on Linux went through that learning experience of not using, e.g., autoconf tests to auto-detect NEON on the host because build host and target host may be very different, therefore my alertness to this issue.

As you can see, it is quite a hassle to translate from system output (e.g., `uname -m` returning `aarch64` or `armv7l` / `armv8l` respectively) or from RPM macros (e.g., `%_target_cpu`) on a native build system to the arguments you expect. And certain values can never be supplied in my scenario because the exact target system is unknown (it varies) or for fear that aggressively enabling all options might break running on systems without.

Also note that your `arch=` values differ yet again from gcc, which uses `-march=armv8.2-a` (without `64-`). How do you expect people to handle ILP32, as `arm64-v8a` or `armv7a`? And what about other architectures? If `arch=x86` should be used on ARMv6 or, e.g., ppc64 or s390x as well, that would again be non-obvious.

Because tegra20 exists among our users and because ARM has assured us it is architecturally perfectly valid not to have NEON on ARMv7-A, as a generic distro we can't assume NEON to be available for our `armv7hl` builds (same for armhf on Debian, I'd assume). Thus conservatively using `neon=0` above, and my question was whether you consider it safe for distros (that *may* end up running on tegra20 without NEON) to build using `neon=1`? This is not clearly stated in the above documentation for anyone not consuming the library themselves. The Linux example does specify `neon=1` (and many other options beyond `arch=`) on the command line, and the Build Options explanation in the preceding section is just an imprecise "Enable Neon support". I do not find "the only thing you need to know is the target architecture of your CPU" anywhere in that documentation, and not knowing the exact architecture of the target host in advance is precisely what I've been trying to tell you before!

The [function summary](https://developer.arm.com/technologies/compute-library) says nothing about functions specific to NEON but rather describes seemingly high-level operations, which implies to me multiple alternative backends for the same set of functions, which in turn suggests no `neon=1` for non-NEON systems.

The bigger question here is whether you actually want your new Open Source library to be picked up and become widely available on Linux distributions? I assumed so from reading the announcement on news sites referring to the description on that arm.com page and from the use of the standard OpenCL API with documented stub library, avoiding direct dependencies on the sadly ill-supported and even less documented Mali drivers for Linux, but maybe I was mistaken...

**Comment by morgolock** [comment]
Hi @afaerber 

ACL requires neon support to run the accelerated CPU code; there is no fallback path for the functions in the absence of neon capabilities. The library performs some checks at runtime to attempt to detect things like the presence of the dot product instruction and float16 and then uses this knowledge to choose the best GEMM kernels.

In the absence of neon support there is not much ACL can do on the CPU side as there is no fallback path written in C++. I understand your concern and I think it would be nice to have something like this but unfortunately there are no plans to do it presently.
