### ISSUE TITLE
questions in reading convolution9x9.cl

### ISSUE THREAD

**Issue by donggua215** [ARM-software/ComputeLibrary#132]
Recently I've been work with this compute library, convolution is used in blur captured image on my platform. When reading the convolution kernel, I got confused.

From convolution9x9, it calls convolution1x9() 9 times, each time with different start of image address, and different row of filter matrix. 

Why each time the image offset is defined starting from its upper 4 rows ? 

The offset specified by (-4,-4) (-4, -3), (-4, -2), (-4, -1), (-4, 0), (-4, 1), (-4, 2), (-4, 3), (-4, 4) , seems convolution1x9() will fetch different column pixels data from image, each column start from x: (row -1), y: [-4, 4].  But when get into convolution1x9() implemention, seems the data it fetched are all within the upper -4 row.

```cpp
short8 convolution9x9(
    Image      *src,
    const short mat0, .....
    const short mat80, uint scale)
{
    VEC_DATA_TYPE(DATA_TYPE, 8)
    pixels;

    pixels = convolution1x9(offset(src, -4, -4), mat0, mat1, mat2, mat3, mat4, mat5, mat6, mat7, mat8);
    pixels += convolution1x9(offset(src, -4, -3), mat9, mat10, mat11, mat12, mat13, mat14, mat15, mat16, mat17);
    pixels += convolution1x9(offset(src, -4, -2), mat18, mat19, mat20, mat21, mat22, mat23, mat24, mat25, mat26);
    pixels += convolution1x9(offset(src, -4, -1), mat27, mat28, mat29, mat30, mat31, mat32, mat33, mat34, mat35);
    pixels += convolution1x9(offset(src, -4, 0), mat36, mat37, mat38, mat39, mat40, mat41, mat42, mat43, mat44);
    pixels += convolution1x9(offset(src, -4, 1), mat45, mat46, mat47, mat48, mat49, mat50, mat51, mat52, mat53);
    pixels += convolution1x9(offset(src, -4, 2), mat54, mat55, mat56, mat57, mat58, mat59, mat60, mat61, mat62);
    pixels += convolution1x9(offset(src, -4, 3), mat63, mat64, mat65, mat66, mat67, mat68, mat69, mat70, mat71);
    pixels += convolution1x9(offset(src, -4, 4), mat72, mat73, mat74, mat75, mat76, mat77, mat78, mat79, mat80);

    if(scale > 0)
    {
        pixels /= (VEC_DATA_TYPE(DATA_TYPE, 8))scale;
    }

    return convert_short8_sat(pixels);
}
```

In convolution1x9, it reads in 16 pixels in one time, coeff-s are not vector, so I think the final result will be ( left1_coeff*temp.s0 + left2_coeff * temp.s1 + left3_coeff*temp.s2 + left4_coeff*temp.s3 + middle_coeff*temp.s4 + right1_coeff*temp.s5 + right2_coeff*temp.s6 + right3.coeff*temp.s7 + right4.coeff*temp.s8).

```cpp
VEC_DATA_TYPE(DATA_TYPE, 8)
convolution1x9(
    __global const uchar *left_pixel,
    const short           left1_coeff,
    const short           left2_coeff,
    const short           left3_coeff,
    const short           left4_coeff,
    const short           middle_coeff,
    const short           right1_coeff,
    const short           right2_coeff,
    const short           right3_coeff,
    const short           right4_coeff)
{
    uchar16 temp = vload16(0, left_pixel);

    VEC_DATA_TYPE(DATA_TYPE, 8)
    left1 = CONVERT(temp.s01234567, VEC_DATA_TYPE(DATA_TYPE, 8));
    VEC_DATA_TYPE(DATA_TYPE, 8)
    left2 = CONVERT(temp.s12345678, VEC_DATA_TYPE(DATA_TYPE, 8));
    VEC_DATA_TYPE(DATA_TYPE, 8)
    left3 = CONVERT(temp.s23456789, VEC_DATA_TYPE(DATA_TYPE, 8));
    VEC_DATA_TYPE(DATA_TYPE, 8)
    left4 = CONVERT(temp.s3456789a, VEC_DATA_TYPE(DATA_TYPE, 8));
    VEC_DATA_TYPE(DATA_TYPE, 8)
    middle = CONVERT(temp.s456789ab, VEC_DATA_TYPE(DATA_TYPE, 8));
    VEC_DATA_TYPE(DATA_TYPE, 8)
    right1 = CONVERT(temp.s56789abc, VEC_DATA_TYPE(DATA_TYPE, 8));
    VEC_DATA_TYPE(DATA_TYPE, 8)
    right2 = CONVERT(temp.s6789abcd, VEC_DATA_TYPE(DATA_TYPE, 8));
    VEC_DATA_TYPE(DATA_TYPE, 8)
    right3 = CONVERT(temp.s789abcde, VEC_DATA_TYPE(DATA_TYPE, 8));
    VEC_DATA_TYPE(DATA_TYPE, 8)
    right4 = CONVERT(temp.s89abcdef, VEC_DATA_TYPE(DATA_TYPE, 8));

    return left1 * (VEC_DATA_TYPE(DATA_TYPE, 8))left1_coeff + left2 * (VEC_DATA_TYPE(DATA_TYPE, 8))left2_coeff + left3 * (VEC_DATA_TYPE(DATA_TYPE, 8))left3_coeff + left4 * (VEC_DATA_TYPE(DATA_TYPE,
            8))left4_coeff + middle * (VEC_DATA_TYPE(DATA_TYPE, 8))middle_coeff + right1 * (VEC_DATA_TYPE(DATA_TYPE, 8))right1_coeff + right2 * (VEC_DATA_TYPE(DATA_TYPE,
                    8))right2_coeff + right3 * (VEC_DATA_TYPE(DATA_TYPE, 8))right3_coeff + right4 * (VEC_DATA_TYPE(DATA_TYPE, 8))right4_coeff;
}
```

I still couldn't get understand the meaning of this convolution kernel, Could any one point out my misunderstanding and explain this. Thanks a lot.

**Comment by AnthonyARM** [comment]
Each call to `convolution1x9()` calculates one row (1x9) of the convolution for 8 pixels.
It's called 9 times (once for each row of the convolution)
The result is the accumulation of the 81 multiplications (For 8 pixels) which is then divided by the scale and stored in the output image.

The coefficients get automatically expanded to a matching size vector, which means the final result will remain a vector

**Comment by donggua215** [comment]
So each time call to convolution1x9(), passed 1st parameter offset(-4, n) means different row data of image, but not different column data?  This will make sense.

But from the helper function below ,img->stride_x represent width*bpp, img->stride_y represent height*bpp, x is always fixed to be -4, y range from [-4, 4]. 

__global inline uchar *offset(const Image *img, int x, int y)
{
    return img->ptr + x * img->stride_x + y * img->stride_y;
}

if current processing pixel is at (m,n), 4*img->stride_x will points to upper 4 row position pixel of image (m-4, n) , if this position plus y*img->stride_y,  is it will result in the position  move left 4 column (m-4, n-y)

So seems the 9 times are all processing the same row pixel of image.  Is there any misunderstanding of me?

**Comment by AnthonyARM** [comment]
offset returns a pointer to some relative coordinates (It doesn't change the pointer in the `img` structure.
stride_x is the size of a pixel
stride_y is the size of a row
therefore `4 * img->stride-x` will point at 4 **columns** to the right (Not rows)

**Comment by donggua215** [comment]
The following comment tell me the stride_x is the image dimension in X (size of pixels for a row). stride_y is the image dimension in Y (size of pixels of a column). 

typedef struct Image                                                                                  
{   
    __global uchar *ptr;                           /**< Pointer to the starting postion of the buffer */
    int             offset_first_element_in_bytes; /**< The offset of the first element in the source image */ 
    int             stride_x;                      /**< Stride of the image in X dimension (in bytes) */
    int             stride_y;                      /**< Stride of the image in Y dimension (in bytes) */**
} Image;                                                                                              


Maybe this mislead me, I will check the other  implementation code again.

Thanks for you explain.

**Comment by donggua215** [comment]
I finally find where the stride_[x|y|z] are calculated, it works as your explained.

std::tuple<Strides, size_t, size_t> TensorInfo::calculate_padding_requirements(const PaddingSize &padding)
{
    // Calculate resulting stride for the X, Y and Z dimension
    const size_t stride_x = element_size();
    const size_t stride_y = (padding.left + _tensor_shape[0] + padding.right) * stride_x;
    const size_t stride_z = _tensor_shape.num_dimensions() == 1 ? 0 : (padding.top + _tensor_shape[1] + padding.bottom) * stride_y;

    Strides      required_strides;
    size_t       required_total_size           = 0;
    const size_t required_offset_first_element = padding.left * stride_x + padding.top * stride_y;

    switch(_tensor_shape.num_dimensions())
    {
        case 1:
            required_strides    = compute_strides(*this, stride_x);
            required_total_size = stride_y;
            break;
        case 2:
            required_strides    = compute_strides(*this, stride_x, stride_y);
            required_total_size = stride_z;
            break;
        default:
        {
            required_strides = compute_strides(*this, stride_x, stride_y, stride_z);

            const unsigned int idx_last_dimension = _tensor_shape.num_dimensions() - 1;

            required_total_size = _tensor_shape[idx_last_dimension] * required_strides[idx_last_dimension];
            break;
        }
    }

    return std::make_tuple(required_strides, required_offset_first_element, required_total_size);
}

**Comment by donggua215** [comment]
resolved

**Comment by AnthonyARM** [comment]
> stride_x is the image dimension in X (size of pixels for a row).

No it's not, the `stride_x` documentation is  
> Stride of the image in X dimension (in bytes)

It means it's the size of one element along the X dimension, i.e the size of a pixel
