### ISSUE TITLE
Cannot build the example and some problem in ide

### ISSUE THREAD

**Issue by ppplinday** [ARM-software/ComputeLibrary#133]
Hi:

I download this program in Linux ubuntu16, I do everything to following to the documentation.
At first, I build the library following the documentation.
![1](https://user-images.githubusercontent.com/23491538/27075987-6f96d640-505e-11e7-8190-defb0ff6f99e.png)
everything is fine and I get the build folder
![2](https://user-images.githubusercontent.com/23491538/27076025-928b7b9c-505e-11e7-898e-794fdf2e5590.png)
However, when I try to run the example by this way
![3](https://user-images.githubusercontent.com/23491538/27076046-a470c5ec-505e-11e7-8b84-4b07d712afd8.png)
Some mistakes happen
![4](https://user-images.githubusercontent.com/23491538/27076069-b342a928-505e-11e7-8fbe-952efb643988.png)
PS:the Chinese means "cannot find"
I install opencl-dev so that the final result is 
![5](https://user-images.githubusercontent.com/23491538/27076155-eabdc496-505e-11e7-98d1-7323b71164d5.png)
I don't know how to run the examples and the cross compile is also cannot find -larm_compute and -lOpenCl
![7](https://user-images.githubusercontent.com/23491538/27076903-1092115c-5061-11e7-9a78-f84254f9140e.png)

The second issue is that I try to download this program in Clion in ubuntu and it cannot build because the program cannot find the "arm_neon.h".
As a result, I download "arm_neon.h" and it also cannot work for lots of error such as '__Int8*8_t' does not name  a type
![6](https://user-images.githubusercontent.com/23491538/27076381-a50f32da-505f-11e7-82a3-b1261df82e10.png)

Any help is very appreciate and very grateful.
Have a good day!!!!!!

**Comment by AnthonyARM** [comment]
> Note
These two commands assume libarm_compute.so is available in your library path, if not add the path to it using -L

If it can't find the libraries it means they're not in your library path, therefore you need to add "-L" with the path to the folder which contains the libraries.

But if you've built the library using scons the examples should already have been built and should be in your `build` folder.

Regarding your IDE / arm_neon.h: your IDE doesn't seem to be set up to cross-compile (arm_neon.h comes with the cross-compiler) and also it's bypassing the library's build system (SCons).

**Comment by ppplinday** [comment]
Thanks a lots of!!!!
I understand the second issue.
But I cannot solve the first issue. I built the library using scons but the examples had not been built.
Anyway, I will try to add "-L" to the path at first but what is the commend?
Thanks! Your help is very appreciate!

**Comment by ppplinday** [comment]
When I add "-L", it has something wrong again.
/usr/bin/ld: skipping incompatible /home/try1/build/arm_compute/libarm_compute.so when searching for -larm_compute
So, what I need to do?

**Comment by AnthonyARM** [comment]
Are you sure you're building natively on the target ?

Also, are you sure the target matches ? ( armv7a for 32bit, / arm64-v8a for 64 bit)

When you run scons with examples=1 (The default), the examples should get built in `build/examples`

**Comment by ppplinday** [comment]
Yes, I am sure that I built natively and the target matches(my OS is 64bit so that I use those two commends:
scons Werror=1 -j8 debug=0 asserts=1 neon=0 opencl=1 embed_kernels=1 os=linux arch=arm64-v8a(for build the library)
g++ examples/cl_convolution.cpp test_helpers/Utils.cpp -I. -Iinclude -std=c++11 -larm_compute -lOpenCL -o cl_convolution(To compile natively (i.e directly on an ARM device) for OpenCL)

And I run scons without examples=1(you can see the commend I list which is from the documentation)

And thanks for your patience to help me!

**Comment by ppplinday** [comment]
And this is my new commend to run the examples, I hope it can help.
 g++ examples/neon_convolution.cpp test_helpers/Utils.cpp -I. -Iinclude -std=c++11 -L/home/zhoupeilin/dowaload/tryfinal1/build/arm_compute -larm_compute -o neon_convolution

**Comment by ppplinday** [comment]
If I use this commend:
arm-linux-gnueabihf-g++ examples/cl_convolution.cpp test_helpers/Utils.cpp -I. -Iinclude -std=c++11 -mfpu=neon -L/home/zhoupeilin/download/tryfinal1/build/arm_compute -L. -larm_compute -lOpenCL -o cl_convolution

it shows that:
/home/zhoupeilin/dowanload/tryfinal1/build/arm_compute/libarm_compute.so: file not recognized: not in executable format
collect2: error: ld returned 1 exit status

**Comment by AnthonyARM** [comment]
`arm-linux-gnueabihf-g++` is 32bit, it should be `aarch64-linux-gnu-g++` for 64

**Comment by ppplinday** [comment]
I try this commend:
aarch64-linux-gnu-g++ examples/cl_convolution.cpp test_helpers/Utils.cpp -I. -Iinclude -std=c++11 -L/home/zhoupeilin/dowaload/tryfinal1/build/arm_compute -L. -larm_compute -lOpenCL -o cl_convolution

and it also shows that it cannot find the -lOpenCL like this:
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: cannot find -lOpenCL
collect2: error: ld returned 1 exit status

**Comment by ppplinday** [comment]
What it means is that I need the libopencl?But I already download opencl and it can find it if I use g++

**Comment by ppplinday** [comment]
ok, everything is fine and I solve all the problem finally,
Thank you very much!!!!!!!!!!!

**Comment by FantasyJXF** [comment]
Thank you @ppplinday  I recently met this problem
