### ISSUE TITLE
what is the difference between _threads[t].start(kernel, win) and kernel->run(win);

### ISSUE THREAD

**Issue by samsun639** [ARM-software/ComputeLibrary#136]
Hello,
I am curious about the multithread function of CPPScheduler::multithread(), 
why the n-1 threads use "_threads[t].start()", the last thread use "kernel->run()"(In another word, why the last thread not use "_threads[t].start()")?  Looks they all means "Execute the kernel on the passed window". 
```
       for(int t = 0; t < num_threads; ++t)
        {
            Window win = max_window.split_window(split_dimension, t, num_threads);
            win.set_thread_id(t);
            win.set_num_threads(num_threads);

            if(t != num_threads - 1)
            {
                _threads[t].start(kernel, win);
            }
            else
            {
                kernel->run(win);
            }
        }

```

Thanks.

**Comment by AnthonyARM** [comment]
It's to avoid an unnecessary context switch: if you have 4 cores, instead of having a main thread and 4 working threads, we have 1 main thread + 3 workers and the main thread processes one of the workloads too.

**Comment by samsun639** [comment]
wow! thanks for rapid and clear explanation.
One more question, I use systrace tool to see that the timecost&tiestamp of each thread (I set to number threads to 4) while running conv3x3, it looks only two threads have the same workload(timestamps are the same), other two are not.
Is that mean the image src I used cannot be divided to 4 part equally?

**Comment by AnthonyARM** [comment]
That's odd, if you look inside the slice_window function you will see that you should have at least 3 identical slices and the 4th one (the one running in the main thread) might be different if it's not an exact multiple. 
What platform are you running on? Maybe you have a big LITTLE system and some threads run on small cores and others on big cores?

**Comment by samsun639** [comment]
Yes, it is a big LITTLE system, Main thread run on big core, other 3 working threads run on little cores,
From the systrace, can see the main thread run faster than the 3 working threads. but the 3 working threads looks not identical , it is not a big problem.
