### ISSUE TITLE
Reading weights from .caffemodel file to tensor

### ISSUE THREAD

**Issue by mo-morikawa** [ARM-software/ComputeLibrary#138]
Is there any code available for reading weight for a deep network such as AlexNet from a .caffemodel file? I am writing an AlexNet implementation with ComputeLibray, and would like to test it using the weights from the Caffe model.

**Comment by jialiang19** [comment]
Hey, mo-morikawa: I am currently writing an AlexNet implementation with ComputeLibrary as well, and I am wondering if your implementation would be able to do training? currently, I am not sure if it is possible to do training with Arm Compute Library.

**Comment by mo-morikawa** [comment]
@jialiang19 In the library, I don't see any of the methods that are needed for training. Even if we could do that, it will take very long to do that on a phone. So, I am thinking of loading the weights from a saved .caffemodel file.

**Comment by gunasekaran7** [comment]
@mo-morikawa Were you able to load weights from .caffemodel?
