### ISSUE TITLE
Training with ARM Compute Library? 

### ISSUE THREAD

**Issue by jialiang19** [ARM-software/ComputeLibrary#139]
Is it possible to do training of the Neural network with ARM computing library? Can you possibly give some hints of how to get started with the training of the neural network with ARM computing library? Thanks!!

**Comment by GeorgeARM** [comment]
Hello @jialiang19,

Unfortunately, Compute Library is only capable of performing inference at the moment.
We assume that the "heavy" and time consuming part of training happens off-line.
Is there a specific reason that you want to do training?

**Comment by jialiang19** [comment]
Thank you @GeorgeARM  for the reply. I am currently an intern in a professor's lab in the U.K., and we are really interested in the performance of the ARM Compute Library, so I am currently just trying to implement Alexnet with ARM Compute library and later test it. At this moment, we do not need to do training with Computing Library. But Is it part of the plan that your team will add the training functionality of the library in the future?

**Comment by GeorgeARM** [comment]
Hello @jialiang19,

We have AlexNet implemented in ACL and should be part as a benchmark in the next release (start of next week). At the moment I can't comment that we will for sure add training functionality soon but If requested we will for sure consider it.
I am closing this issue. Feel free to reopen in any case. If you have any feature request create a respective issue.

Thanks,
George
