### ISSUE TITLE
Any example for loading pretraining module and weight

### ISSUE THREAD

**Issue by ppplinday** [ARM-software/ComputeLibrary#140]
Do you have any simple example for loading pretraining (for example: alexnet, vgg16 and mnist) module and its weight coding by ARM Compute Library? 

If not, could you tell me which function should I use to load the module and weight and how to use.
Thanks!!!

**Comment by ppplinday** [comment]
HI, and I have another question.
If I used Tensorflow to load pretraing module and weight and freeze them, can I load them by ARM Compute Library?

**Comment by AnthonyARM** [comment]
I'm not sure I understand the question: loading weights is not different from loading an image (and you have several examples of that in the library or in closed issues) 

There isn't any function in the library to load files directly from TensorFlow or Caffe, but nothing prevents you from saving them yourselves to a file then loading them in a Compute Library tensor.

**Comment by ppplinday** [comment]
Thanks for ur answer.
