### ISSUE TITLE
How to use a pretraining model?

### ISSUE THREAD

**Issue by ppplinday** [ARM-software/ComputeLibrary#142]
I know we cannot train the model by ARM Compute Library. As a result, can we use a pretraining model to validate and how? Any examples or hints can help me a lot.

**Comment by ppplinday** [comment]
And it means how to fill the weight to my model? I hope I can explain the question accurately. Thanks.

**Comment by AnthonyARM** [comment]
The Compute Library is a low level library, which doesn't have the concept of graph, which means you need to build your graph by hand one layer at the time.
You can connect layers to each other by using the output tensor of one as the input of the next one.
Regarding the weights: it's the user's responsibility to load and parse the file containing the weights and to put them in a tensor (Like you would do for an image).

**Comment by ppplinday** [comment]
I got it! Thank you very much!
