### ISSUE TITLE
Error "Undefined reference to" in compiling

### ISSUE THREAD

**Issue by ppplinday** [ARM-software/ComputeLibrary#143]
When I compiled the example(neon_convolution.cpp) by ARM Compute Library, it show:

neon_dnn.cpp:(.text+0x214): undefined reference to `arm_compute::NEConvolutionLayer::NEConvolutionLayer()'
neon_dnn.cpp:(.text+0x224): undefined reference to `arm_compute::NEConvolutionLayer::NEConvolutionLayer()'
neon_dnn.cpp:(.text+0x250): undefined reference to `arm_compute::NEFullyConnectedLayer::NEFullyConnectedLayer()'
neon_dnn.cpp:(.text+0x290): undefined reference to `arm_compute::NESoftmaxLayer::NESoftmaxLayer()'
......

And I used this commend:
aarch64-linux-android-g++ examples/neon_dnn.cpp test_helpers/Utils.cpp -I. -Iinclude -std=c++11 -larm_compute-static -L/home/zhoupeilin/download/t2/build/arm_compute -L. -o cl_convolution_aarch64 -static-libstdc++ -pie -lOpenCL

I already add this commend:-L/home/zhoupeilin/download/t2/build/arm_compute     to make sure it can find the path. If I don`t add this commend, it show that:
/aarch64-linux-android-4.9/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find -larm_compute-static
collect2: error: ld returned 1 exit status

BTW: I success complied the example(cl_convolution.cpp), because I think that cl_convolution.cpp doesn`t include some function like NEConvolutionLayer. But I still cannot run cl_convolution in my computer(Linux and intel cpu), it shows that "cannot execute binary file exec format error"

Any hints and help are appreciate!!!

**Comment by AnthonyARM** [comment]
The problem is likely that you compiled the library with neon=0
All functions starting with NE need neon=1 and all those starting with CL require opencl=1

Also if you're using the Android aarch64 toolchain then you need to run the binary on an ARM 64bit Android device (Not a Linux Intel machine)

**Comment by ppplinday** [comment]
Thank you sooooooooooooooooo much!!!!!!!!!
