### ISSUE TITLE
A bug in NEFullyConnectedLayer and the weights

### ISSUE THREAD

**Issue by ppplinday** [ARM-software/ComputeLibrary#146]
HI, I have a issue about the NEFullyConnectedLayer and the weights.
My coding is including input, output and only one fullyconnectedlayer.
This is my code:
`

    std::cout << "start!!!" << std::endl;

    unsigned int inputnumber = 3;
    unsigned int fcnumber = 5;
    TensorShape ishape(inputnumber);
    TensorShape fcshape(fcnumber);

    Tensor itensor, fctensor;
    itensor.allocator() -> init(TensorInfo(ishape, 1, DataType::F32));
    fctensor.allocator() -> init(TensorInfo(fcshape, 1, DataType::F32));

    TensorShape weightsshape(inputnumber, fcnumber);
    TensorShape biasesshape(fcnumber);
    Tensor weights, biases;
    weights.allocator() -> init(TensorInfo(weightsshape, 1, DataType::F32));
    biases.allocator() -> init(TensorInfo(biasesshape, 1, DataType::F32));

    NEFullyConnectedLayer fc;
    fc.configure(&itensor, &weights, &biases, &fctensor);

    weights.allocator()->allocate();

    float * inputw = (float *)weights.buffer();
    for(int i = 0; i < weightsshape.total_size(); ++ i) inputw[i] = i + 1;
    weights.print(std::cout, IOFormatInfo::PrintRegion::ValidRegion);
`

However, my weights` output shows that
![bug1](https://user-images.githubusercontent.com/23491538/27473590-4489f654-5832-11e7-92c4-5cee13946954.png)

It should like this:
![bug2](https://user-images.githubusercontent.com/23491538/27473615-53a0cb7c-5832-11e7-9031-fd7b08395809.png)

What`s more, if I delete this one:
fc.configure(&itensor, &weights, &biases, &fctensor);
The weights` output is right. As a result, I think there are some bug in the NEFullyConnectedLayer or I miss some important aspects.
Any helps or hints are appreciate!!!

**Comment by gmiodice** [comment]
Hi @ppplinday

the reason why the weights tensor doesn't stores correctly the values when you call configure(), is due to the padding bytes used for performing the NEFUllyConnectedLayer.

https://arm-software.github.io/ComputeLibrary/v17.03.1/#S4_6_images_tensors

In order to store correctly the values into a 2D tensor like weights, you should have something like this: (not tested)

uint8_t *inputw = weights.buffer() + weights.info()->offset_first_element_in_bytes();
for(int y = 0; y < fcnumber; y++)
{
    for(int x = 0; x < inputnumber; ++ x)
    {
        *(inputw + x * weights.info()->element_size() + y * weights.info()->strides_in_bytes()[1]) = x + y * inputnumber;
    }
}

weights.print(std::cout, IOFormatInfo::PrintRegion::ValidRegion);

Let us know if it works.

Hope this can help,
Gian Marco

**Comment by ppplinday** [comment]
It cannot work and I am trying other way. It is very important to store in 3D or 4D tensor.
And I do not know what the meaning of num_channels is in this definition:
TensorInfo(const TensorShape &tensor_shape, size_t num_channels, DataType data_type, size_t fixed_point_pos = 0);

**Comment by ppplinday** [comment]
@gmiodice Thanks for your help! I think both of us need to try how to make it work and share the answer.
It works like this way:
int k = 1;
    float *inputw = (float *)weights.buffer() + weights.info() -> offset_first_element_in_bytes();
    for(int i = 0; i < fcnumber; ++ i){
        for(int j = 0; j < inputnumber; ++ j){
            inputw[i * weights.info()->element_size() + j] = k++;
        }
    }

**Comment by ppplinday** [comment]
@gmiodice I try this way and it works.
`
    for(int y = 0; y < fcnumber; ++ y){
        for(int x = 0; x < inputnumber; ++ x){
            *reinterpret_cast<float *>(weights.buffer() + weights.info()->offset_element_in_bytes(Coordinates(x, y))) = y * inputnumber + x;
        }
    }


`
