### ISSUE TITLE
How to fill this parameter and what does it mean?

### ISSUE THREAD

**Issue by ppplinday** [ARM-software/ComputeLibrary#150]
In here:
TensorInfo(const TensorShape &tensor_shape, size_t num_channels, DataType data_type, size_t fixed_point_pos = 0);
I do not know what the channels mean and how to fill it? Does it have any relationship with the input image?
Any helps or hints are appreciate!!!

**Comment by gmiodice** [comment]
Hi @ppplinday ,

num_channels essentially expresses the number of interleaved values for the same element. To be more precise, for example, in the case of an RGB image with 3 interleaved channels, this values should be equal to 3 and for complex images where we have real and imaginary part this should be 2:

i.e. RGB image with interleaved values:
|r0|g0|b0|r1|g1|b1|...

Currently all Machine Learning functions support just planar images so this value should be 1

Thanks,
Gian Marco

**Comment by ppplinday** [comment]
Thanks for your help @gmiodice 
I got it but I want to know more.
If I have a input RGB image(224 * 224), how to fill the TensorShape and how to init the Tensor?

At the beign, I do not know what the channel means so that my coding like:
TensorShape inputshape(224,224,3);
Tensor input;
input.allocator()->init(TensorInfo(inoutshape, 1, DataType::F32));

I want to know how to init the tensor. Thanks for you help!!!

**Comment by gmiodice** [comment]
Hi @ppplinday ,

In order to fill your input tensor, you could use something like the following code once you have allocated the tensor:

Tensor input;
Window window;
window.use_tensor_dimensions(tensor->info());

Iterator out(&tensor, window)

// Each iteration stores a single value
execute_window_loop(window, [&](const Coordinates &id)
{
    float value = src_image[id.x() + id.y() * width + id.z() * width * height]
    *reinterpret_cast<float*>(out.ptr()) = value;
}, out);

Let me know if it works,
Thanks,

**Comment by ppplinday** [comment]
@gmiodice 
It worked and thanks!
