### ISSUE TITLE
build failure "fatal error: algorithm: No such file or directory"

### ISSUE THREAD

**Issue by joel-mi** [ARM-software/ComputeLibrary#151]
Hi
I'm trying to build the library on Cygwin64 Terminal, with the following command :
scons Werror=1 -j1 debug=1 asserts=1 neon=1 opencl=1 embed_kernels=1 os=android arch=armv7a

Build fails with the following error :
./arm_compute/core/Dimensions.h:29:21: fatal error: algorithm: No such file or directory
 #include <algorithm>

Can you help with this problem ?

**Comment by mpflanzer** [comment]
Sounds like an issue when scons is run from the Windows Command line and from Cygwin for the same build. Then it get's confused with `\` vs. `/`.

The recommend way to build with Windows is to use the Bash on Ubuntu on Windows subsystem whenever possible. If that is not available Cygwin builds should also work fine.

Can you try the following steps to see if it works:
1. Download and install Cygwin. When installing Cygwin make sure you select the `scons` package to be installed. (You probably want git as well).
2. Get the toolchain that you want to use. (For Android use one of the standalone toolchains. For Linux Linaro provides Windows builds of gcc for example.)
3. Make a fresh clone of the repository or at least `git clean -dfx`. **The latter will remove all untracked and modified files!**
4. Run the scons command

*All commands should be executed in the Cygwin terminal __not in the Windows commandline__*

**Comment by mpekatsoula** [comment]
Reopen if needed
