### ISSUE TITLE
Questions about Benchmark

### ISSUE THREAD

**Issue by XiaoMaol** [ARM-software/ComputeLibrary#158]
Hey, 

I am trying out the new release of the library, especially the new benchmark features. However, I encountered several problems: 

Question 1:
Running the command
```
./arm_compute_benchmark -- ./data
``` 
I get the following automatic initialization from the program:  
```
Using 1 CPU thread
Run on (8 X 1400 MHz CPU s)
2017-07-03 10:53:51
***WARNING*** Library was built as DEBUG. Timings may be affected.
```
So I am wondering if I could run all those tests using GPU. I have OpenCL and GPU setup on my machine. If I could, how can I test them with GPU? In addition, could I possibly use more threads if CPU to test those tests? 

Questions 2: 
I have tried to run ``` ./arm_compute_benchmark -- ./data ``` several times, However, every time the program unexpectedly ended with the following error message without finishing all the tests
![benchmark_problems](https://user-images.githubusercontent.com/29860073/27790369-1305e1ac-5fe8-11e7-92d3-6aee5d377189.png)

Do we have to provide all the sample input ourself? Or are they contained in the library somewhere?  

Question 3: 
Besides the information from https://arm-software.github.io/ComputeLibrary/v17.06/tests.xhtml, is there any more documentations or tutorials about how to use the benchmark? Is there a way that we can write and integrate our own test into your test suit? 

Thanks!

**Comment by AnthonyARM** [comment]
Hi,
Sorry, only just realised we had forgotten to upload the `data` folder. It should be fixed now.
Could you please update to the `HEAD` of master and let me know if it works ?

**Comment by XiaoMaol** [comment]
Hey @AnthonyARM: 

I have downloaded the newly updated ```data``` folder, and I move the folder into ```ComputLibrary/build/tests```. Then I ran the ```  ./arm_compute_benchmark -- ./data ``` several times, as suggested by the documentation. However, I kept getting the same error. 
![issue_158_2](https://user-images.githubusercontent.com/29860073/27833041-e9b476b0-60c8-11e7-8384-2ab6444f1b8b.png)

By the way, Can we also use GPU for Benchmark Testing? Thanks!

**Comment by AnthonyARM** [comment]
Hi,

I managed to reproduce the issue on my end, however it doesn't occur with our internal repository, so it's likely to be a bug introduced by our release script.
However, it's not trivial to debug and we are in the process to replace Google benchmark with our own framework, so the bug should go away once this is done.

**Comment by imageje** [comment]
@AnthonyARM 
Could you tell me whether bugs is fixed? I also met this message as below:
BitwiseAndLarge/neon_bitwise_and/1/threads:1               15548763 ns   15548631 ns         45 Wall clock=15.519 Wall clock_max=15.6988 Wall clock_min=15.4649
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Cannot load image with extension '/data/images/'
Aborted

**Comment by AnthonyARM** [comment]
We're still working on removing Google benchmark and Boost dependencies, it's still going to take some time but it should be finished for the next major release (September)

**Comment by GeorgeARM** [comment]
Google benchmark dependency is now removed. Closing issue.
