### ISSUE TITLE
upgrading to V17.06 : problems in linking with Arm Compute Library

### ISSUE THREAD

**Issue by joel-mi** [ARM-software/ComputeLibrary#159]
Hi,
I've been using V17.05 till now, and I'm currently trying to upgrade to V17.06
When trying to link to the library, I'm getting errors that I didn't see with V17.05 - attached
Do you understand those errors ? Can you help with that ?
[output.txt](https://github.com/ARM-software/ComputeLibrary/files/1119174/output.txt)

I also noticed something else, that doesn't seem to be related to the link failure but I'd like to have it clarified :
When I built the library with V17.05, I used to get 2 .a files : libarm_compute_core-static.a and libarm_compute-static.a; with V17.06, I'm getting only libarm_compute-static.a; is this as expected ? Maybe it has to do with the fact that I'm now building the library with "examples = 0" option ? I didn't do so with V17.05 (I'm not sure if there was such an option then)

**Comment by joel-mi** [comment]
I've rebuilt the library with examples included (i.e. without "examples = 0" option), and it seems that it solved the problem encountered at linking
I'll make sure that my build is OK now and from my viewpoint, we can close the issue - although you might be interested in investigating the problem with "examples = 0" option.

**Comment by AnthonyARM** [comment]
Hi Joel,

That's odd, are you sure your build directory was completely clean before you started your build ?
If you have a look at the [SConstruct](https://github.com/ARM-software/ComputeLibrary/blob/v17.06/SConstruct) file, you'll see that `examples` is declared on line 45 and used only on line 205. 
Please let us know if you see other linking errors and we'll have a closer look (It might be possible there are some side effects in the examples/SConscript file, but I had a quick look and couldn't see anything)
