### ISSUE TITLE
Docs: Unexpected See also for valid_region

### ISSUE THREAD

**Issue by afaerber** [ARM-software/ComputeLibrary#16]
The [manual padding bullet point](https://arm-software.github.io/ComputeLibrary/v17.03.1/index.xhtml#padding) has a probably unintended "See also" heading in the middle of the sentence.

**Comment by afaerber** [comment]
Caused by `@sa` in `docs/arm_compute.dox` line 532. Better double-check other occurrences, too.

**Comment by AnthonyARM** [comment]
Thanks for reporting the bug.
Fixed @sa bugs on lines 450, 532 and 567

**Comment by AnthonyARM** [comment]
Fixed in v17.04 (Re-open if not)
