### ISSUE TITLE
Upgrading to 17.06

### ISSUE THREAD

**Issue by Szonek** [ARM-software/ComputeLibrary#160]
Hi, after upgrading to latest Compute Library release I've got problem with examples.
Scons arguments:
> Werror=no -j8 debug=0 asserts=0 neon=0 opencl=1 embed_kernels=1 os=linux arch=x86_64

When I want to run ./cl_convolution I got error:
> ./cl_convolution: symbol lookup error: ./cl_convolution: undefined symbol:_ZN11arm_compute22get_target_from_deviceERN2cl6DeviceE

In release 17.05 I had not such error.
Thanks in advice!

**Comment by Szonek** [comment]
I resolved this issue.
Error don't says about it but I had to add shared libraries (libarm_compute.so and libarm_compute_core.so).

**Comment by AnthonyARM** [comment]
Thanks for the bug report.
Do you mean you had to change the SCons file to explicitly link against arm_compute.so ?

**Comment by Szonek** [comment]
I had to update ldconfig.

**Comment by AnthonyARM** [comment]
Can you post your changes here and we'll make sure to include it in the next release

**Comment by Szonek** [comment]
I haven't made any changes in your files. Just the error didn't show that the problem is with not linked shared libraries.

**Comment by GeorgeARM** [comment]
Closing issue. Reopen if needed.
