### ISSUE TITLE
Keras backend integration

### ISSUE THREAD

**Issue by mzakharocsc** [ARM-software/ComputeLibrary#163]
Any thoughts on whether this library can be used as  keras backend? ([keras.io](http://keras.io)) If yes, any plans to add support for this?

**Comment by AnthonyARM** [comment]
I don't see why not, but we currently don't have any plans to add support for it ourselves.
I can't promise anything, but I would imagine someone would be more likely to add support in TensorFlow  (Then you would be able to use Keras on top of TF)

**Comment by GeorgeARM** [comment]
Closing issue. Reopen if needed. Duplicate of #7. Integration should be done at TF level
