### ISSUE TITLE
Comparison with Naive C code

### ISSUE THREAD

**Issue by sagarkar10** [ARM-software/ComputeLibrary#170]
I am running Darknet yolo on my arm64 and after profiling it i get something like this:
Each image detection takes 13s apx.
```
Native Darknet-tiny-yolo

CPU: ARM Cortex-A53, speed 1200 MHz (estimated)
Counted CPU_CYCLES events (Cycle) with a unit mask of 0x00 (No unit mask) count 100000
samples  %        symbol name
3487351  96.0589  gemm_cpu(int, int, int, int, int, float, float*, int, float*, int, float, float*, int)
44363     1.2220  im2col_cpu
26081     0.7184  forward_maxpool_layer
21006     0.5786  normalize_cpu
18509     0.5098  activate_array
12829     0.3534  fill_cpu
6398      0.1762  scale_bias
6372      0.1755  add_bias
3761      0.1036  rand_uniform
1165      0.0321  make_convolutional_layer
1086      0.0299  load_image_stb(char*, int)
426       0.0117  resize_image(image, int, int)
244       0.0067  stbi__parse_zlib(stbi__zbuf*, int)
146       0.0040  stbi__idct_block(unsigned char*, int, short*)

```

where as when I run the complete set up with ArmCompute and neon support I have this profile-report:
One image takes 12.5sec approx.
```
Darknet-tiny-yolo with ARMCompute (Neon support and no CL)

CPU: ARM Cortex-A53, speed 1200 MHz (estimated)
Counted CPU_CYCLES events (Cycle) with a unit mask of 0x00 (No unit mask) count 100000
samples  %        symbol name
5616463  75.2805  void matrix_matrix_multiply_f32<false>(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, arm_compute::Window const&, float) [clone .constprop.47]
449370    6.0231  arm_compute::TensorInfo::offset_element_in_bytes(arm_compute::Coordinates const&) const
369867    4.9575  TinyYolo::forward_batchnorm(arm_compute::Tensor&, vector<float>, vector<float>, vector<float>, vector<float>, int, int, int, int, bool)
268774    3.6025  gemm_interleave_32bit_elements(arm_compute::ITensor const*, arm_compute::ITensor*, arm_compute::Window const&)
199573    2.6750  arm_compute::NEIm2ColKernel::run_generic(arm_compute::Window const&)
97815     1.3111  arm_compute::NECol2ImKernel::run(arm_compute::Window const&)
75907     1.0174  stbi_zlib_compress(unsigned char*, int, int*, int)
61899     0.8297  TinyYolo::activate_tensor(arm_compute::Tensor&, TinyYolo::ACTIVATION)
60273     0.8079  arm_compute::TensorAllocator::lock()
54473     0.7301  arm_compute::NEConvolutionLayerWeightsReshapeKernel::run(arm_compute::Window const&)
38270     0.5130  void arm_compute::NEPoolingLayerKernel::pooling2<(arm_compute::PoolingType)0>(arm_compute::Window const&, arm_compute::Window const&)
37979     0.5091  load_image_stb(char*, int)
30598     0.4101  stbi_write_png_to_mem(unsigned char*, int, int, int, int, int*)
14468     0.1939  arm_compute::NEGEMMTranspose1xWKernel::run(arm_compute::Window const&)
12177     0.1632  arm_compute::error_on_coordinates_dimensions_gte(char const*, char const*, int, arm_compute::Coordinates const&, unsigned int)
12112     0.1623  arm_compute::Tensor::info() const
12090     0.1620  arm_compute::Tensor::buffer() const
11990     0.1607  stbi__parse_zlib(stbi__zbuf*, int)
11981     0.1606  arm_compute::ITensorAllocator::info()
5822      0.0780  stbiw__zlib_flushf(unsigned char*, unsigned int*, int*)
3192      0.0428  TinyYolo::initialize_wb(arm_compute::Tensor&, _IO_FILE*)
1785      0.0239  stbi__create_png_image_raw(stbi__png*, unsigned char*, unsigned int, int, unsigned int, unsigned int, int, int) [clone .isra.13]
1689      0.0226  save_image_png(image, char const*)
1453      0.0195  stbi__convert_format(unsigned char*, int, int, unsigned int, unsigned int)
1301      0.0174  stbi__zbuild_huffman(stbi__zhuffman*, unsigned char*, int)
1234      0.0165  nms_comparator(void const*, void const*)

```

The darknet code is simple cblass gemm function.
I used it in my intel-core with mkl and got an increase in performace around 8 times, was expecting to ger similar results.
Please let me know where I am doing it wrong. And how can I optimise it.
Note: I am using the weights file trained in darknet, and both are profiled on around 50 runs.
Thanks

**Comment by sagarkar10** [comment]
@AnthonyARM Any suggestion on this?

**Comment by GeorgeARM** [comment]
Hello @sagarkar10,

Your expectations are not comparable. Because you got 8x in an intel core using mkl does not mean you will have the same speedup.
Can you give us more info on your setup?
Do you build with debug=0 and assert=0? For performance measurements you should disable debug and asserts
How do you run the model multiple times? You should configure your model and then rerun the already configured model multiple times. If you configure you model in every test run then probably some weight reshaping will take every time, which is time consuming.

**Comment by sagarkar10** [comment]
Hi @GeorgeARM I am not reconfiguring the model again and again, and all the compiler flags ike debug and assert are set to 0. How do u suggest to gain the speed up. 
Sorry for the late reply.

**Comment by AnthonyARM** [comment]
I'm confused: what's your baseline using ? Is it OpenBLAS ?

**Comment by sagarkar10** [comment]
@AnthonyARM The darknet framework is using CBLAS and gemm functions

**Comment by AnthonyARM** [comment]
If CBLAS already contain some NEON optimisations then it's normal for the gap to be small.
Anyway, we're currently still working on adding new features, once this is done we will optimise further some of the key algorithms like GEMM.

**Comment by GeorgeARM** [comment]
Closing issue. Kernel optimizations will follow once adding new features in the library is done. GEMM is one of the highest priority ones.

**Comment by dcsgan** [comment]
HI @sagarkar10 . How did you profile the darknet code and got the statisctics ? Which tool you used to obtain the profile report.?

**Comment by sagarkar10** [comment]
@dcsgan I have used oprofile

**Comment by gregoiregentil** [comment]
@sagarkar10 Where did you find darknet + ARM Compute Library? There are a few darket-nnpack variants which have some neon optimizations and there is also yolo2_light but I haven't found a darknet accelerated with Compute Library on Google or Github?

I guess that here, we are talking about pure Neon, no OpenCL.
