### ISSUE TITLE
Calculation error in nepoolinglayer

### ISSUE THREAD

**Issue by sparrow0629** [ARM-software/ComputeLibrary#172]
I found a calculation error, and just paste my test data here
The input data is 3x5
{0.168426, 0.663761, 0.119523, -0.030098, -0.008632;
 0.345623, 0.758206, 0.109123, -0.024056, -0.011653;
 0.291084, 0.463759, -0.000870, -0.004330, 0.165582;}

the kernel type is MAX
the kernel size is 3
stride is 2
pad is 0
DimensionRoundingType is CEIL

the outputs are shown as 
{0.758206 0.119523 0.291084;
 -0.000870 0.165582 0.000000;}
apparently they are wrong.

the accurate outputs should be
{0.758206 0.165582 0.165582;
 0.463759 0.165582 0.165582;}

How to solve this problem?
Thanks

**Comment by GeorgeARM** [comment]
Hello @sparrow0629,

Can you post your example code so that we can have a look?
Thank you in advance.

**Comment by GeorgeARM** [comment]
Closing this issue as there isn't any update. Reopen if needed.
