### ISSUE TITLE
alexnet mali profiling

### ISSUE THREAD

**Issue by Subarukun** [ARM-software/ComputeLibrary#173]
I have created the alexnet app using armcompute mali library. The app displays the camera preview along with alexnet outputs after processing.

So the problem here is alexnet processing fps keeps on varying  from 4 to 8 fps  and not constant . Is this expected behaviour. 

Note : I am using gettimeofday to check the profiling . Mobile I am using is samsung galaxy note5.

Thanks in advance.

**Comment by GeorgeARM** [comment]
Hello @Subarukun ,

I would expect more or less the model to have a stable fps after the first run.
Can you give us some more info on your setup?
Do you create the model once? Do you run a single batch every time or you merge more than one in each run?

**Comment by Subarukun** [comment]
The app starts at 8 fps and keeps on decreasing and stables at 4 fps . But the same app with arm-compute neon is giving 3 fps stable. I assume difference in fps should be more for CPU vs GPU.

Regarding the setup: I have created the camera preview app with android studio .I Integrated the armcompute library into Android studio project using the CMakeFile .

Alexnet model is created once during init (like network.build, network.allocate in AlexNet.h) .Alexnet process is run for every frame rendered by camera until the app is exited. No batch processing is done.

**Comment by AnthonyARM** [comment]
How do you configure your device ? Is it rooted ?
You should override both the CPU and mali's governor if you want consistent results

**Comment by Subarukun** [comment]
Android device is not rooted. However we monitored with CPU-Z app .CPU clock speed scaled according to load(CPU clock is peak when our application is running)but there is no change in  gpu clock speed 

It would be fantastic if you can give the CPU vs GPU profile comparison of Alexnet from your end.

**Comment by AnthonyARM** [comment]
There is some benchmarking data available via CK as mentioned by @psyhtest in [this comment](https://github.com/OAID/caffeOnACL/issues/2#issuecomment-314358871)

**Comment by AnthonyARM** [comment]
and [here too](https://github.com/ARM-software/ComputeLibrary/issues/174#issuecomment-314846505)

**Comment by Subarukun** [comment]
Thanks for your inputs Do you have benchmarking numbers for Alexnet using the armcompute library for both CPU(ARM)/GPU(MALI) .

It would be great to have these for our reference.

**Comment by ysh329** [comment]
Anyone knows how to adjust GPU frequency? Thanks in advance! :rofl:

**Comment by GeorgeARM** [comment]
@Subarukun  in the latest release (v17.09) a custom-made testing and benchmarking infrastructure was added. Alexnet benchmark is part of it for both CPU and GPU.

**Comment by GeorgeARM** [comment]
Closing. Reopen if needed. Alexnet graph example is now available for benchmarking.
