### ISSUE TITLE
ARM Computing Library Performance v.s. Caffe or Tensorflow Performance on ARM Mali GPU?

### ISSUE THREAD

**Issue by XiaoMaol** [ARM-software/ComputeLibrary#174]
Dear all: 

I am really interested in the comparison of the performance of AlexNet by ARM Computing Library and AlexNet by Caffe or Tensorflow on ARM Mali GPU. 

Has anyone yet done a performance comparison like this? I am currently trying to do this performance comparison by myself, but I have trouble to install Caffe or TensorFlow on ARM Mali GPU. I am just wondering if it is even possible to install Caffe or TensorFlow on ARM Mali GPU? 

Thanks.

**Comment by psyhtest** [comment]
@XiaoMaol, of course it is possible to use Caffe on Mali. (I will not speak about TensorFlow).

For example, please have a look at [public benchmarking results](https://nbviewer.jupyter.org/github/dividiti/ck-caffe-firefly-rk3399/blob/master/script/batch_size-libs-models/analysis.20170531.ipynb) obtained via [CK-Caffe](http://github.com/dividiti/ck-caffe) on a [Firefly-RK3399](http://en.t-firefly.com/en/firenow/Firefly_RK3399) platform.

Benchmarking AlexNet via [CK](http://github.com/ctuning/ck) is work-in-progress...

**Comment by XiaoMaol** [comment]
CK-Caffe is indeed a great way to download Caffe, and I found that ARM Computing Library is faster than the Caffe on the Mali GPU.
