### ISSUE TITLE
Does Compute Library support OpenCL 1.1 Embedded Profile?

### ISSUE THREAD

**Issue by gunasekaran7** [ARM-software/ComputeLibrary#175]
I am using imx6 processor which does support only OpenCL1.1 Embedded profile. Can Compute Library with OpenCL support be supported on this platform?

**Comment by AnthonyARM** [comment]
It's unlikely to work: for performance reasons the Compute Library requires non-uniform-workgroup sizes which means your GPU needs to have either CL2.x support or the arm-non-uniform-workgroup-size extension.

You could hack the library to not use non-uniform workgroup sizes by removing the flag from [here](https://github.com/ARM-software/ComputeLibrary/blob/v17.06/src/core/CL/CLKernelLibrary.cpp#L584)
And you need to force `lws` to null [here](https://github.com/ARM-software/ComputeLibrary/blob/v17.06/src/core/CL/ICLKernel.cpp#L60)

I haven't tested it, I can't guarantee this will work.

**Comment by gunasekaran7** [comment]
@AnthonyARM , I tried that and It didn't work. Is there anything else I can do to make it work?

**Comment by AnthonyARM** [comment]
What error do you get ?

I'm afraid it's unlikely to work without a bit of hacking.
You can still use the NEON path to get an idea of the features available in the library, and it should still bring some speed up compare to regular C/C++ code.

**Comment by GeorgeARM** [comment]
Closing issue. OpenCL 1.1 Embedded Profile is not supported. Reopen if needed.
