### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by AmirElAttar** [ARM-software/ComputeLibrary#176]
I built the neon_convolution example using the command:
g++ ./examples/neon_convolution.cpp utils/Utils.cpp  -I. -I utils -std=c++11 -L./lib/linux-arm64-v8a-neon -larm_compute -larm_compute_core -o neon_convolution 
it build successfully against either: linux-arm64-v8a-neon , or linux-arm64-v8a-neon-debug 
version v17.06
running using no args, getting the following runtime error:
./neon_convolution: symbol lookup error: ./neon_convolution: undefined symbol: _ZN11arm_compute10TensorInfoC1ERKNS_11ITensorInfoE

**Comment by AnthonyARM** [comment]
Are you building against the pre-built binaries uploaded on Github or your own builds ?

**Comment by GeorgeARM** [comment]
Closing this issue, as there is no update. Reopen if needed.
