### ISSUE TITLE
How can I set the number of threads in V17.06 ?

### ISSUE THREAD

**Issue by duhuanxianzi** [ARM-software/ComputeLibrary#177]
Hi, I found that the library will use all cores on default.
In some cases, I need to run it with given number of threads. how can I set the number?

In 17.05 and 17.04 version, I put "NEScheduler::get().force_number_of_threads(num_threads);" at the beginning of my program to control the number of threads. In addition, "NEScheduler.h" should be also include in the header files.

And calling arm_compute::Scheduler::get().set_num_threads(num_threads); at the beginning of my program is of no effect.

So how can I set the number of threads in V17.06 ?

**Comment by AnthonyARM** [comment]
Which scheduler are you using ? `set_num_threads()` is indeed the correct way to set the number of threads.

What do you mean: "is of no effect" ?
Could you please provide an example ?

**Comment by duhuanxianzi** [comment]
Thanks very much, I found I lose "()" in "Scheduler::get().set_num_threads(num_threads)". Now everything is OK

**Comment by duhuanxianzi** [comment]
You can close this issue, and response to my next issue. 

Thanks a lot!
