### ISSUE TITLE
A question about NEGEMMLowp.cpp between ACL 17.05 and ACL 17.06

### ISSUE THREAD

**Issue by duhuanxianzi** [ARM-software/ComputeLibrary#179]
Hi, I found NEGEMMLow.cpp is a liittle different between ACL 17.05 and ACL 17.06.

In ACL 17.05 from line 58 to line 59, its detail is as follow:
   line 58:    shape_tmp_b.set(0, b->info()->dimension(1) * 4);
   line 59:    shape_tmp_b.set(1, std::ceil(b->info()->dimension(0) / 4.f));

In ACL 17.06 from line 58 to line 59, its detail is as follow:
    line 58:   shape_tmp_b.set(0, b->info()->dimension(1) * 16);
    line 59:   shape_tmp_b.set(1, std::ceil(b->info()->dimension(0) / 16.f));

Then, I test respectively the speed of gemmlowp in ACL 17.05 and 17.06, the test file is as follows:

**neon_gemmlowpmutiply_test.cpp**
.
.
.
Tensor input0;
Tensor input1;
Tensor output;

/* [Initialize tensors] */

// Initialize src tensor
constexpr unsigned int width_src1_image = 8;	//A col--dimension(0)
constexpr unsigned int height_src1_image = 1024; //A row--dimension(1)

constexpr unsigned int width_src2_image = 1024;
constexpr unsigned int height_src2_image = 8;

constexpr unsigned int ifm_src_img = 1;

const TensorShape src_shape1(width_src1_image, height_src1_image, ifm_src_img);
const TensorShape src_shape2(width_src2_image, height_src2_image, ifm_src_img);
const TensorShape src_shape3(width_src2_image, height_src1_image, ifm_src_img);

//size_t size1 = src_shape.total_size();

//std::cout << size1 << std::endl;

input0.allocator()->init(TensorInfo(src_shape1, 1, DataType::U8));	//neon_dnn的F32->U8
input1.allocator()->init(TensorInfo(src_shape2, 1, DataType::U8));	//neon_dnn的F32->U8
output.allocator()->init(TensorInfo(src_shape3, 1, DataType::U8));	//neon_dnn的F32->U8

input0.allocator()->allocate();
input1.allocator()->allocate();
output.allocator()->allocate();

int32_t a_offset = 0;

int32_t b_offset = 0;

int32_t output_offset = 0;

int32_t output_mult_int = 1;

int32_t shift = 0; 

NEGEMMLowp gemm_low8;
gemm_low8.configure(&input0, &input1, &output, a_offset, b_offset, output_offset, output_mult_int, shift);

	//End of Time t---duhuan 2017/4/12
	double avg = 50;
	double totalTime = 0.0;
	for (int i = 0; i < avg; i++)
	{
		//NEGEMMLowp gemm_low8;
		double st = getCurrentTime();
		//your code
		//gemm_low8.configure(&input0, &input1, &output, a_offset, b_offset, output_offset, output_mult_int, shift);
		gemm_low8.run();
		double et = getCurrentTime();
		totalTime += et - st;
	}
	std::cout << "Run time: " << totalTime / avg << "ms" << std::endl;
.
.
.

As a result, if I don't change any context in ACL 17.06, the speed of test file in ACL 17.06 is approximately 30% slower than that in ACL 17.05. But if I modify the context of line 58 and line 59 of NEGEMMLowp.cpp in ACL 17.06 to be same as that in ACL 17.05. Detail is as follows:

In ACL 17.06 from line 58 to line 59, it is changed into follows:
    line 58:   shape_tmp_b.set(0, b->info()->dimension(1) * 4);
    line 59:   shape_tmp_b.set(1, std::ceil(b->info()->dimension(0) / 4.f));

On the contrary, the speed of test file in ACL 17.06 is approximately 30% faster than that in ACL 17.05. 

Why is that? What is the meanings of line 58 to line 59?

**Comment by duhuanxianzi** [comment]
No body?

**Comment by GeorgeARM** [comment]
`GEMMLowp` has changed a lot from `v17.06` until `v17.12`. Thus, I am closing this issue and open a new one if needed.
