### ISSUE TITLE
How to init src tensor and weights from custom data?

### ISSUE THREAD

**Issue by wonderzy** [ARM-software/ComputeLibrary#180]
Is there any examples showing how to init src tensor or the conv weights from custom data? 
The current code uses `src.allocator()->allocate();`
Then I print the src tensor,  which is initialized all zero.

In the neon_convolution.cpp, there is `ppm.init_image(src, Format::U8);`
But when I look inside, it seems just use the shape to init the image.allocator()
Any suggestions, thanks.

**Comment by AnthonyARM** [comment]
The actual copy of the image data happens in [fill_image](https://github.com/ARM-software/ComputeLibrary/blob/v17.06/utils/Utils.h#L142)

You also have an example in the [documentation](https://arm-software.github.io/ComputeLibrary/v17.06/architecture.xhtml#S4_6_4_working_with_objects)

**Comment by wonderzy** [comment]
It works. Thx a lot.

**Comment by wonderzy** [comment]
Hi, how can I do it with a 4-dim tensor like weight?It seems that the window only support XYZ @AnthonyARM

**Comment by AnthonyARM** [comment]
What do you mean ? The window supports up to 6 dimensions

**Comment by wonderzy** [comment]
Yes, I have seen it. Thanks.
