### ISSUE TITLE
Batch size for Mali version

### ISSUE THREAD

**Issue by mkamrao** [ARM-software/ComputeLibrary#181]
Hello

We are trying to check the CPU usage with various batch sizes for Alexnet network created using the ARM Compute Mali version.
However, we have noted that there is not much gain in performance by increasing the batch size.

Is this expected behavior? On other GPU platforms like nvidia, increasing the batchsize improves the performance vastly.
Do you have any sample code on how to configure the batch size using the Mali APIs.

Thanks
kamrao

**Comment by AnthonyARM** [comment]
Hi,
Currently the Compute Library is functional but not fully optimised.
Batching is one of the areas which has been implemented naively for the moment and we'll get back to it once we're done adding new features.

**Comment by mkamrao** [comment]
ok. Thank you.

Kamrao
