### ISSUE TITLE
how to init weights (4D-tensor)

### ISSUE THREAD

**Issue by wlgns0105** [ARM-software/ComputeLibrary#182]
I don't know how to init 4D or more tensor..
I'm looking at 'examples/neon_copy_objects.cpp' and referencing the part that fills tensor using
Window, Iterator, execute_window_loop

I think

execute_window_loop(input_window, [&](const Coordinates & id)
{
    *reinterpret_cast<float *>(input_it.ptr()) = src_data[id.z() * (width * height) + id.y() * width + id.x()];
},
input_it);

is for filling 3-D tensor (with id.x(), id.y(), id.z()). How can I extend it to 4-D tensor? is there next member after x, y, z ?

**Comment by wonderzy** [comment]
just with id[3] @wlgns0105

**Comment by wlgns0105** [comment]
Thanks I think it works

**Comment by victorygogogo** [comment]
id[3]*(id.z() * (width * height) + id.y() * width) + id.x()  ???@wlgns0105

**Comment by wlgns0105** [comment]
id[3] * (width * height * channel) + id.z() * (width * height) + id.y() * width + id.x()

or 

id[3] * (width * height * channel) + id[2] * (width * height) + id[1] * width + id[0]

is same @victorygogogo

**Comment by victorygogogo** [comment]
@wlgns0105  thank you . do you have a quick way to map a point to the tensor  ?

**Comment by wlgns0105** [comment]
No, i mapped one by one @victorygogogo
