### ISSUE TITLE
The Library use hard or softfp when compile with neon=1？

### ISSUE THREAD

**Issue by wonderzy** [ARM-software/ComputeLibrary#184]

**Comment by AnthonyARM** [comment]
By default the library uses hard float everywhere, almost every OS in the past 4 years has fully switched to hard float

**Comment by AnthonyARM** [comment]
hard float is used by default on Linux.
Android still uses soft-float.
So, it depends which OS you're running on

**Comment by wonderzy** [comment]
Another question: It seems that the conv output and weights and biases shares the same fixed_point_number? That's why? Actually, the weights is always small, and the biases is almost the same with the output? If they shares the same fixed_point_number, then the weights is loss more accuracy,right? @AnthonyARM

**Comment by gmiodice** [comment]
Hi @wonderzy ,

you are right and currently it is a limitation for the functions with fixed point support. However this is just an initial implementation which will help us to understand the next steps based on the feedback received.

Thanks,
Gian Marco
