### ISSUE TITLE
Need way to add custom compiler flags

### ISSUE THREAD

**Issue by afaerber** [ARM-software/ComputeLibrary#19]
Our package build processes require to add [RPM macro `%{optflags}`](https://build.opensuse.org/project/prjconf/openSUSE:Factory) to `CXXFLAGS`.
It seems that `flags` is assembled in `sconscript` without any way to extend it with custom options?

**Comment by AnthonyARM** [comment]
Would an extra scons option do the job ?

`scons extra_cxx_flags="-DMyFlag=1 -DFOO"`

**Comment by afaerber** [comment]
Absolutely. The contents needs to be appended at the end, so that, e.g., `-O` options can be overridden.

**Comment by AnthonyARM** [comment]
Fixed in v17.04 (Re-open if you still see the issue)
