### ISSUE TITLE
How to set sysroot when compiling with ACL ?

### ISSUE THREAD

**Issue by wonderzy** [ARM-software/ComputeLibrary#193]
I met the link error when cross compile on linux using `scons Werror=0 -j8 debug=0 asserts=0 neon=1 opencl=0 os=android arch=armv7a.`
When
 `/data/3rdparty/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ -o build/libarm_compute_core.so -shared build/src/core/AccessWindowAutoPadding.os build/src/core/AccessWindowStatic.os build/src/core/AccessWindowTranspose.os build/src/core/Error.os build/src/core/HOGInfo.os build/src/core/Helpers.os build/src/core/IAccessWindow.os build/src/core/IDistribution.os build/src/core/IDistribution1D.os build/src/core/IKernel.os build/src/core/ITensor.os build/src/core/MultiImageInfo.os build/src/core/PyramidInfo.os build/src/core/SubTensorInfo.os build/src/core/TensorInfo.os build/src/core/Utils.os build/src/core/Validate.os build/src/core/CPP/ICPPSimpleKernel.os build/src/core/CPP/kernels/CPPCornerCandidatesKernel.os build/src/core/CPP/kernels/CPPDetectionWindowNonMaximaSuppressionKernel.os build/src/core/CPP/kernels/CPPSortEuclideanDistanceKernel.os build/src/core/NEON/kernels/NEAbsoluteDifferenceKernel.os build/src/core/NEON/kernels/NEAccumulateKernel.os build/src/core/NEON/kernels/NEActivationLayerKernel.os build/src/core/NEON/kernels/NEArithmeticAdditionKernel.os build/src/core/NEON/kernels/NEArithmeticSubtractionKernel.os build/src/core/NEON/kernels/NEBatchNormalizationLayerKernel.os build/src/core/NEON/kernels/NEBitwiseAndKernel.os build/src/core/NEON/kernels/NEBitwiseNotKernel.os build/src/core/NEON/kernels/NEBitwiseOrKernel.os build/src/core/NEON/kernels/NEBitwiseXorKernel.os build/src/core/NEON/kernels/NEBox3x3Kernel.os build/src/core/NEON/kernels/NECannyEdgeKernel.os build/src/core/NEON/kernels/NEChannelCombineKernel.os build/src/core/NEON/kernels/NEChannelExtractKernel.os build/src/core/NEON/kernels/NECol2ImKernel.os build/src/core/NEON/kernels/NEColorConvertKernel.os build/src/core/NEON/kernels/NEConvolutionKernel.os build/src/core/NEON/kernels/NECumulativeDistributionKernel.os build/src/core/NEON/kernels/NEDepthConcatenateKernel.os build/src/core/NEON/kernels/NEDepthConvertKernel.os build/src/core/NEON/kernels/NEDerivativeKernel.os build/src/core/NEON/kernels/NEDilateKernel.os build/src/core/NEON/kernels/NEDirectConvolutionLayerBiasAccumulateKernel.os build/src/core/NEON/kernels/NEDirectConvolutionLayerKernel.os build/src/core/NEON/kernels/NEErodeKernel.os build/src/core/NEON/kernels/NEFastCornersKernel.os build/src/core/NEON/kernels/NEFillArrayKernel.os build/src/core/NEON/kernels/NEFillBorderKernel.os build/src/core/NEON/kernels/NEFillInnerBorderKernel.os build/src/core/NEON/kernels/NEGEMMInterleave4x4Kernel.os build/src/core/NEON/kernels/NEGEMMLowpMatrixMultiplyKernel.os build/src/core/NEON/kernels/NEGEMMMatrixAccumulateBiasesKernel.os build/src/core/NEON/kernels/NEGEMMMatrixAdditionKernel.os build/src/core/NEON/kernels/NEGEMMMatrixMultiplyKernel.os build/src/core/NEON/kernels/NEGEMMTranspose1xWKernel.os build/src/core/NEON/kernels/NEGaussian3x3Kernel.os build/src/core/NEON/kernels/NEGaussian5x5Kernel.os build/src/core/NEON/kernels/NEGaussianPyramidKernel.os build/src/core/NEON/kernels/NEHOGDescriptorKernel.os build/src/core/NEON/kernels/NEHOGDetectorKernel.os build/src/core/NEON/kernels/NEHarrisCornersKernel.os build/src/core/NEON/kernels/NEHistogramKernel.os build/src/core/NEON/kernels/NEIm2ColKernel.os build/src/core/NEON/kernels/NEIntegralImageKernel.os build/src/core/NEON/kernels/NELKTrackerKernel.os build/src/core/NEON/kernels/NELocallyConnectedMatrixMultiplyKernel.os build/src/core/NEON/kernels/NEMagnitudePhaseKernel.os build/src/core/NEON/kernels/NEMeanStdDevKernel.os build/src/core/NEON/kernels/NEMedian3x3Kernel.os build/src/core/NEON/kernels/NEMinMaxLocationKernel.os build/src/core/NEON/kernels/NENonLinearFilterKernel.os build/src/core/NEON/kernels/NENonMaximaSuppression3x3Kernel.os build/src/core/NEON/kernels/NENormalizationLayerKernel.os build/src/core/NEON/kernels/NEPixelWiseMultiplicationKernel.os build/src/core/NEON/kernels/NEPoolingLayerKernel.os build/src/core/NEON/kernels/NERemapKernel.os build/src/core/NEON/kernels/NEScaleKernel.os build/src/core/NEON/kernels/NEScharr3x3Kernel.os build/src/core/NEON/kernels/NESobel3x3Kernel.os build/src/core/NEON/kernels/NESobel5x5Kernel.os build/src/core/NEON/kernels/NESobel7x7Kernel.os build/src/core/NEON/kernels/NESoftmaxLayerKernel.os build/src/core/NEON/kernels/NETableLookupKernel.os build/src/core/NEON/kernels/NEThresholdKernel.os build/src/core/NEON/kernels/NETransposeKernel.os build/src/core/NEON/kernels/NEWarpKernel.os build/src/core/NEON/kernels/NEWeightsReshapeKernel.os -Lbuild/-L/data/3rdparty/android-ndk-r12b/platforms/android-21/arch-arm/usr/lib -L/data/3rdparty/android-ndk-r12b/platforms/android-21/arch-arm/usr/lib -Lbuild/-L/data/3rdparty/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x -L/data/3rdparty/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x -ldl -lc -lm -lstdc++ -landroid -llog`
There is the error
```
/data/3rdparty/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot open crtbegin_so.o: No such file or directory
/data/3rdparty/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot open crtend_so.o: No such file or directory
/data/3rdparty/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: build/src/core/Error.os: requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/data/3rdparty/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: build/src/core/Utils.os: requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/data/3rdparty/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: build/src/core/NEON/kernels/NEActivationLayerKernel.os: requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/data/3rdparty/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: build/src/core/NEON/kernels/NEArithmeticAdditionKernel.os: requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/data/3rdparty/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: build/src/core/NEON/kernels/NEArithmeticSubtractionKernel.os: requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
build/src/core/Utils.os:Utils.cpp:function arm_compute::build_information(): error: undefined reference to '__dso_handle'
build/src/core/Utils.os:Utils.cpp:function arm_compute::string_from_format(arm_compute::Format): error: undefined reference to '__dso_handle'
build/src/core/Utils.os:Utils.cpp:function arm_compute::string_from_channel(arm_compute::Channel): error: undefined reference to '__dso_handle'
build/src/core/Utils.os:Utils.cpp:function arm_compute::string_from_data_type(arm_compute::DataType): error: undefined reference to '__dso_handle'
collect2: error: ld returned 1 exit status
scons: *** [build/libarm_compute_core.so] Error 1
scons: building terminated because of errors.
```
And I think I add --sysroot=/data/3rdparty/android-ndk-r12b/platforms/android-21/arch-arm/ to the end can fix it, but I don't know how to add this in Sconscript? Could you tell me that?
And another question: it seems that when os is Android, ACL use softfp. When I change this to hard, then  it gives me the following error . I don't know why. Maybe my ndk is not hard supported?
```
/data/3rdparty/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /data/3rdparty/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/libgcc.a(unwind-arm.o) uses VFP register arguments, output does not
/data/3rdparty/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /data/3rdparty/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/libgcc.a(pr-support.o) uses VFP register arguments, output does not
/data/3rdparty/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /data/3rdparty/android-ndk-r12b/platforms/android-21/arch-arm/usr/lib/libdl.so uses VFP register arguments, output does not
/data/3rdparty/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /data/3rdparty/android-ndk-r12b/platforms/android-21/arch-arm/usr/lib/libstdc++.so uses VFP register arguments, output does not
/data/3rdparty/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /data/3rdparty/android-ndk-r12b/platforms/android-21/arch-arm/usr/lib/libandroid.so uses VFP register arguments, output does not
/data/3rdparty/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /data/3rdparty/android-ndk-r12b/platforms/android-21/arch-arm/usr/lib/liblog.so uses VFP register arguments, output does not
/data/3rdparty/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /data/3rdparty/android-ndk-r12b/platforms/android-21/arch-arm/usr/lib/libm.so uses VFP register arguments, output does not
/data/3rdparty/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /data/3rdparty/android-ndk-r12b/platforms/android-21/arch-arm/usr/lib/libc.so uses VFP register arguments, output does not
build/src/core/Utils.os:Utils.cpp:function arm_compute::build_information(): error: undefined reference to '__dso_handle'
build/src/core/Utils.os:Utils.cpp:function arm_compute::string_from_format(arm_compute::Format): error: undefined reference to '__dso_handle'
build/src/core/Utils.os:Utils.cpp:function arm_compute::string_from_channel(arm_compute::Channel): error: undefined reference to '__dso_handle'
build/src/core/Utils.os:Utils.cpp:function arm_compute::string_from_data_type(arm_compute::DataType): error: undefined reference to '__dso_handle'

```

**Comment by AnthonyARM** [comment]
1) It doesn't look like you're using the [NDK standalone toolchain](https://arm-software.github.io/ComputeLibrary/v17.06/index.xhtml#S3_3_android)
2) You need to use the NDK r14 (Both the versions before and after are broken, that's the only one we know works for sure)

**Comment by wonderzy** [comment]
Yes, it works. But I don't there is any difference between hard and softfp on efficiency. @AnthonyARM
