### ISSUE TITLE
How to fill CLTensor with custom data?

### ISSUE THREAD

**Issue by nevenp** [ARM-software/ComputeLibrary#196]
I have troubles with filling CLTensor with custom data. I followed this tutorial: https://arm-software.github.io/ComputeLibrary/v17.04/index.xhtml#S4_6_4_working_with_objects and it works for Tensor, but when I use CLTensor instead of Tensor, application is killed.

**Comment by mpflanzer** [comment]
Do you `map`/`unmap` the `CLTensor` before/after accessing it from the host side? Here is a small example how to do it: https://arm-software.github.io/ComputeLibrary/v17.04/index.xhtml#S4_4_2_cl_neon
