### ISSUE TITLE
No soname set

### ISSUE THREAD

**Issue by afaerber** [ARM-software/ComputeLibrary#20]
The shared libraries `libarm_compute_core.so` and `libarm_compute.so` are not versioned. The version would need to be set in per-library linker flags and could initially be 0. The idea is to have `libarm_compute.so.0`, with `libarm_compute.so` as symlink for development.

The `build_library` function in `sconscript` may need to be extended to accommodate this in the `static=False` case?

**Comment by afaerber** [comment]
Test case: `objdump -p build/libarm_compute.so | grep SONAME`

**Comment by AnthonyARM** [comment]
This will be added in the next release, thanks for suggesting it.

**Comment by AnthonyARM** [comment]
Fixed in v17.04 (Re-open if you still see the issue)
