### ISSUE TITLE
OpenCL GPU acceleration for caffeOnACL and mxnetOnACL

### ISSUE THREAD

**Issue by JammyZhou** [ARM-software/ComputeLibrary#200]
When trying caffeOnACL and mxnetOnACL on my ARM64 Linux box, I found that OpenCL was actually not used in the classification demo following the instructions at:

https://github.com/OAID/mxnetOnACL/tree/master/acl_openailab
https://github.com/OAID/caffeOnACL/tree/master/acl_openailab

Did I miss something?

**Comment by psyhtest** [comment]
@JammyZhou May I suggest asking (OAID)[https://github.com/OAID), not here?

**Comment by JammyZhou** [comment]
Okay, I will ask OAID. I thought it is a generic topic for OpenCL acceleration with ACL.
