### ISSUE TITLE
How can I print some variables in configure() function ?

### ISSUE THREAD

**Issue by imageje** [ARM-software/ComputeLibrary#204]
If I want to print some variables in configure() function of ARM Compute Library, how can I set ?

For example, I'm running NEON_cnn.cpp and I want to know more variables. 
I add printf()/cout in configure() of  NEConvolutionLayer.cpp, but there are any response.
Is there any other options for using cout()/printf() ?

**Comment by mpflanzer** [comment]
Using `printf` or `cout` should be perfectly fine. Are you sure the function for which you added the output is actually called?

Are you developing for Android or Linux? Could you use gdb to confirm that the function is called?

**Comment by morgolock** [comment]
Be aware you can't print the tensors contents in the configure() method as they have not yet been allocated.

**Comment by GeorgeARM** [comment]
Closing. Reopen if needed.
