### ISSUE TITLE
17.04v is missing arm_compute

### ISSUE THREAD

**Issue by Valentin4869** [ARM-software/ComputeLibrary#205]
The provided binaries for version 17.04 seems to be missing the arm_compute folder.

**Comment by mpflanzer** [comment]
Is there any reason why you need to use the 17.04 release and not the more recent 17.06?

**Comment by Valentin4869** [comment]
I'm running on an old linux version that doesn't have g++-4.9 (the file is there, but it can't detect it).

**Comment by mpflanzer** [comment]
I strongly recommend to use the latest version as we improved the performance of many functions and also added new functions.

For which platform do you want to compile? Usually you would need something like arm-linux-gnueabihf-g++ in your PATH environment. You can also use CXX to point to a specific compiler.

**Comment by Valentin4869** [comment]
I'm compiling opencl code for an old lubuntu version on an ARM machine on the Mali gpu. But we'll get a more recent version later so I'll leave this for now and try NEON for now. Thanks.
