### ISSUE TITLE
odd number padding mechanism is different from tensorflow

### ISSUE THREAD

**Issue by wlgns0105** [ARM-software/ComputeLibrary#208]
When odd number of zero padding is needed to do the convolution, the result is different from tensorflow's mechanism

ARM Compute Library function gives more padding on left and top, but tensorflow gives more padding on right and bottom

for example if src tensor dimension is 8x8x3 and w0 dimension is 5x5x3x1 with stride 2 convolution,
output tensor (out_conv0) dimension is 4x4x1, and you need total 3 line of zero padding
(pad_left + pad_right = 3, pad_top + pad_bottom = 3)

if I use PadStrideInfo(2,2,2,2), it dumps 1 zero padding on right and bottom and works as 
pad_left = 2, pad_right = 1, pad_top = 2, pad_bottom = 1

but tensorflow gives more padding on right and bottom like
pad_left = 1, pad_right = 2, pad_top = 1, pad_bottom = 2

if I use PadStrideInfo(2,2,1,1), the output tensor dimension becomes 3x3x1

**Comment by AnthonyARM** [comment]
I don't understand what the problem is ?

**Comment by wlgns0105** [comment]
If I make same CNN model with compute library and load parameters trained from Tensorflow, the classification result is different because of the way of padding

**Comment by AnthonyARM** [comment]
I still don't understand: padding should be irrelevant, you should be saving and loading the data only, not the padding bytes, no ?

**Comment by wlgns0105** [comment]
for example
src : 4x4x1, weight : 3x3x1x1, out_conv : 2x2x1 (stride = 2, need 1 zero padding)
src filled with 2, weight filled with 1

Tensorflow padded src                             library padded src
2 2 2 2 0                                                   0 0 0 0 0                                                   
2 2 2 2 0                                                   0 2 2 2 2                                                   
2 2 2 2 0                                                   0 2 2 2 2                                                   
2 2 2 2 0                                                   0 2 2 2 2                                                   
0 0 0 0 0                                                   0 2 2 2 2                                                   

output (2x2x1)
Tensorflow                                                library
18  12                                                       8    12
12  8                                                         12  18 

loaded src and weights are same but results are different

**Comment by gmiodice** [comment]
Hi @wlgns0105,

from your consideration it seems that in TensorFlow you can decide where is gonna be applied the first convolution kernel chaging pad_left, pad_right, pad_bottom and pad_top using https://www.tensorflow.org/api_docs/python/tf/pad. Is this your consideration?

If so, currently in the Compute Library you can specify only the same amount of paddings for dimension X and Y of the tensor so you cannot control the values for the pad_left, pad_right, pad_top and pad_bottom explicitly.

Hope this can help.
Thanks

**Comment by wlgns0105** [comment]
thanks for the reply
