### ISSUE TITLE
Alternately swap CLTensors

### ISSUE THREAD

**Issue by nevenp** [ARM-software/ComputeLibrary#209]
I have one input and one output CLTensor allocated. Input tensor is filled with the input data. I want to configure multiple CNN layers in the beginning without allocating input and output CLTensors for each layer. Afterwards, I need to pass input CLTensor through the first layer and obtain the first output. Then I need to swap input and output tensors so that input of the next layer is the output from the previous layer and so on. How to do that?

**Comment by AnthonyARM** [comment]
If you're using the library's CLTensor class then you can re-use a tensor only if the TensorInfo matches (i.e same dimensions and types).

If you just want to re-use the memory backing the CLTensor then I guess you'll have to either modify the CLTensor class to use a memory pool, or to re-use the memory handle of another tensor.

Note: in both cases you will only be able to re-use memory for the tensors you use to connect the layers together (i.e your input / output buffers), all the temporary buffers inside the functions will still remain allocated.

We've got plans to add a memory manager to the library so the alternative is to wait :)

Hope this helps
