### ISSUE TITLE
GEMM/dense layer problem (v17.3.1)

### ISSUE THREAD

**Issue by Valentin4869** [ARM-software/ComputeLibrary#210]
I can't seem to get the correct output from GEMM when multiplying two matrices. I just want the standard matrix multiplication, but I keep getting strange results. I'm using version 17.03.1 btw. The code below tests standard matrix multiplication by multiplying a 3x3 matrix with itself.

X*X should be 
(30.000000) (36.000000) (42.000000) 
(66.000000) (81.000000) (96.000000) 
(102.000000) (126.000000) (150.000000) 

But instead I get 
(38.000000) (14.000000) (17.000000) 
(20.000000) (98.000000) (46.000000) 
(57.000000) (68.000000) (9.000000) 

```
#include "arm_compute/runtime/NEON/NEFunctions.h"
#include "arm_compute/core/Types.h"
#include "Utils.h"
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/time.h>
#include <stdarg.h>
using namespace arm_compute;
using namespace test_helpers;




Tensor* CreateTensor2d(unsigned int x, unsigned int y){

Tensor *X=new Tensor;

const TensorShape x_shape(x,y);

X->allocator()->init(TensorInfo(x_shape, 1, DataType::F32));

return X;
}

//fill tensor with row-major-ordered data
void FillTensor(Tensor* X, float* src, int sz){

  X->allocator()->allocate();


for(int i=0; i<sz; i++)
reinterpret_cast<float*>( X->buffer())[i]=src[i];

}


void DisplayTensor(Tensor* X, int m, int n, int offset){

  int i, j;

	for (i = 0; i < m; ++i) {
		for (j = 0; j < n; ++j)
			printf("(%f) ",  reinterpret_cast<float*>(X->buffer())[offset + i * n + j]);

		printf("\n");
	}
 
  
}


int main(int argc, const char **argv)
{
printf("Begin\n");


float x[]={1,2,3,
           4,5,6,
           7,8,9};


Tensor* result;
Tensor* X;
NEGEMM mult1;


X=CreateTensor2d(3,3);
result=CreateTensor2d(3,3);
mult1.configure(X,X,NULL, result,1.0,0);


FillTensor(X,x,3*3);

FillTensor(result,NULL,0);

mult1.run();
DisplayTensor(X,3,3,0);

printf("--------Output--------\n");

DisplayTensor(result,3,3,0);
printf("\n");


return 0;

}

```

**Update:** when compiling with debug libs, I get an error complaining about the dimensions of the input (3d output of the maxpooling layer) not being consistent with the weights, but I'm following one of the examples provided, which suggests this might be a limitation in the earlier release (17.3.1) and it was fixed in later releases. Is there any way to reshape it without having to copy the contents of the maxpooling tensors to a new tensor, just to get it working in the older release?

**Comment by Valentin4869** [comment]
Copying the 3d output tensor's contents to an appropriately reshaped tensor fixes the problem, but most likely at some additional small cost in running time.

**Comment by AnthonyARM** [comment]
Reshaping is needed in order to increase performance of the matrix multiply (Which is otherwise terrible for the cache from a memory access pattern point of view)

However the reshaping of the weights only occurs for the first run of the function, so the cost should be negligible.
