### ISSUE TITLE
Which operation could be used to implement the group convolution operation?

### ISSUE THREAD

**Issue by lhCheung1991** [ARM-software/ComputeLibrary#213]
Hi,

I am writing the MobileNets by ACL, I wonder if there is any interface could be used to implement the group convolution operation.

Thank you.

**Comment by steniu01** [comment]
@lhCheung1991 , we are implementing the CL depthwise separable convolution layer and adding the mobilenet into our benchmarking model. It should be ready in the coming release.

**Comment by lhCheung1991** [comment]
@steniu01 
I am looking forward to it! BTW, do you plan to implement the NEON version to depthwise separable convolution layer?

**Comment by steniu01** [comment]
I am afraid unlikely. It is not planned for the coming release.

**Comment by lhCheung1991** [comment]
@steniu01 
All right, thank you very much for your opinion. Is there any operation for me to implement depthwise separable convolution for NEON version?

**Comment by steniu01** [comment]
@lhCheung1991,  Depthwise separable convolution layer function can be implemented by using depthwise convolution layer and a 1x1 direct convolution layer. We have already provided the NEDirectConvolutionLayer, so what you need is depthwise convolution layer. 
There are no kernels can be used directly in the released version to build up depthwise convolution layer. In the trunk version we implemented four new kernels to achieve the depthwise convolution layer: 
CLDepthwiseIm2ColKernel : Reshape the source to be prepared for GEMV
CLDepthwiseWeightsReshapeKernel : Reshape the weights to be prepared for GEMV
CLGEMMMatrixVectorMultiplyKernel :  Apply a GEMV with the output from the above two kernels. 
CLDepthwiseVectorToTensorKernel : Takes the 1D tensor that's been produced by the MatrixVectorMultiply
 kernel and reshapes it to given width and height

**Comment by GeorgeARM** [comment]
Closing issue. Depthwise separable convolution for CL is part of 17.09 release.
We implement grouping convolution using subtensors and we use it in the alexnet system test [here](https://github.com/ARM-software/ComputeLibrary/blob/master/tests/networks/AlexNetNetwork.h).
Reopen issue if needed.
