### ISSUE TITLE
GEMM Matrix Multiply Optimization Questions

### ISSUE THREAD

**Issue by jmoguill** [ARM-software/ComputeLibrary#214]
Hi,
I have a question regarding GEMM Matrix multiply in OpenCL.  It seems in CLGEMM.cpp that there's logic to check if the tensor is in vector format, and if not, then it runs an interleave and transpose kernel to convert to vector format.  I would like to gain some understanding of this logic.  Suppose that we are multiplying two matrices A and B, where A is stored as a tensor of shape (1024,1024) and B is stored as a tensor of shape (1024,1024).  Is this logic converting A to (1024*1024, 1)?  Is it possible for us to do this reshape offline before we run the GEMM kernel?  Some sample code would be great.  
Thanks,
Jeff

**Comment by gmiodice** [comment]
Hi @jmoguill,

essentially the logic withing CLGEMMMatrixMultiplyKernel only checks if the first input tensor is a matrix or not. If so, it runs a special kernel for the case "vector by matrix".

Regarding your question:  Is it possible for us to do this reshape offline before we run the GEMM kernel?

The answer is: yes, it is. A good example where we use the matrix B already reshaped is CLConvolutionLayer: https://github.com/ARM-software/ComputeLibrary/blob/master/src/runtime/CL/functions/CLConvolutionLayer.cpp

Hope this can help you.
Gian Marco
