### ISSUE TITLE
Is there any way to configure multi-threading for all operations (v17.03.1)?

### ISSUE THREAD

**Issue by Valentin4869** [ARM-software/ComputeLibrary#215]
I would like to benchmark my code and compare the results with and without multi-threading, but the only way I can seem to do this is by manually launching the kernels used by each Function and run them as `_krn.run(krn.window())_ `_(I wonder if this is the correct way of running the kernel on a single thread_). Is there an easier way to disable multi-threading for all operations without having to change the code so much?

Thanks

**Comment by AnthonyARM** [comment]
You can call `Scheduler::get().set_num_threads( num_threads );` at the beginning of your program like we do in [benchmarking suite](https://github.com/ARM-software/ComputeLibrary/blob/v17.06/tests/benchmark/main.cpp#L93)

**Comment by Valentin4869** [comment]
Thank you, but Scheduler doesn't seem to be available for v17.03.1. Anyway, as a work around, I used _taskset_ to assign the desired CPU cores to the program before executing the tests.
