### ISSUE TITLE
Unable to execute OpenCL programs (v17.06) on RK3399

### ISSUE THREAD

**Issue by Valentin4869** [ARM-software/ComputeLibrary#217]
I am trying to build and run the OpenCL examples, namely cl_convolution.cpp but the program crashes on the line   `CLScheduler::get().default_init();` with the following output:

```
*** Error in `./cl_convolution': free(): invalid pointer: 0x0000000020e4bb08 ***
Aborted (core dumped)
```
The device is an RK3399 with 64-bit ARM processors and a Mali T860 GPU running Ubuntu 16.04. I tried compiling using the following commands:

`aarch64-linux-gnu-g++ cl_convolution.cpp utils/Utils.cpp -std=c++14 -lOpenCL -l arm_compute -o cl_convolution`

Also tried `-lmali` instead of '-lOpenCL', with the same problem. How can I fix this? Thanks

**Comment by Valentin4869** [comment]
I even tried with a minimal example as follows:
```

#include "arm_compute/runtime/CL/CLFunctions.h"
#include "arm_compute/core/Types.h"
#include "utils/Utils.h"
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/time.h>
#include <stdarg.h>
#include <iostream>


using namespace arm_compute;



int main(int argc, const char **argv)
{
printf("Begin\n");


CLTensor A;
const TensorShape a_shape(5,5);

A.allocator()->init(TensorInfo(a_shape, 1, DataType::F32));

printf("allocating A...\n");
A.allocator()->allocate();
printf("allocation successful.\n");

return 0;

}
```

With the following error outputs:

```
_Begin
allocating A..._
terminate called after throwing an instance of 'cl::Error'
what():  clCreateBuffer
Aborted (core dumped)
```

**Comment by AnthonyARM** [comment]
In the second case you need to have `ARM_COMPUTE_CL` defined a the top of your file in order for the CL exceptions to be handled correctly (At the moment it's impossible to tell what's wrong in clCreateBuffer)

We've got several of these boards in the office and they work fiine, can you try with the compilers we recommend in the documentation and using c++11 instead of 14 ?

**Comment by Valentin4869** [comment]
@AnthonyARM could you please clarify what you mean by "the compilers recommended in the docs"? In the docs, it says to compile using `aarch64-linux-gnu-g++`, which is what I do here. I also tried `arm-linux-gnueabihf-g++`, but I'm guessing this creates a 32-bit program, which I can't run on the current machine. 

As for the second case, I defined ARM_COMPUTE_CL and the error message doesn't seem to change to include additional detail on the error. Also tried with c++11, but the problem persists.

I wonder if I need to `apt-get upgrade` or something or do something else to the system? But I'm guessing not, because standard OpenCL programs work with no issues. I'm also not sure where I got the aarch64 compiler, and doing `apt-get install g++-aarch64-linux-gnu` tells me  `Package 'gcc-aarch64-linux-gnu' has no installation candidate`. 

Did you have to set up anything on the device before compiling ACL programs?

**Comment by Valentin4869** [comment]
It seems this might be GPU driver related issue. These errors come up whenever a section of code is reached that targets OpenCL to MIDGARD (for example `_target(GPUTarget::MIDGARD)`). And I can't seem to find a guide to help with installing/updating the Mali driver.

**Comment by Valentin4869** [comment]
Installed the driver from https://github.com/rockchip-linux/libmali, but still same problem.

**Comment by Valentin4869** [comment]
Going a little deeper, the error seems to occur at the line (CLScheduler.h):
`    CLKernelLibrary::get().init("./cl_kernels", cl::Context::getDefault(), cl::Device::getDefault());`

I wonder if the first argument is causing the error, since the folder cl_kernels does not exist anywhere in the headers folders and it's only found in the source folders. But putting the folder in the same directory as the executable doesn't fix it either.

**Comment by AnthonyARM** [comment]
If you've compiled the library with `embed_kernels=1` then this parameter is irrelevant and it doesn't matter that this folder doesn't exist.

What happens if you do `cl::Context::getDefault()` and `cl::Device::getDefault()` on their own before calling the `init()` method ?

**Comment by Valentin4869** [comment]
I didn't compile my own binaries; I'm using the ones provided on this page. What is the value  of `embed_kernels` in the provided binaries?

Standard OpenCL programs run fine, even with the C++ wrapper. So calling `cl::Context::getDefault()` and other OpenCL functions does not produce any errors.

**Comment by AnthonyARM** [comment]
`embed_kernels` means the sources for the OpenCL kernels are embedded inside the library binary instead of read from file at runtime.
That's why I'm saying that having a `cl_kernels` folder shouldn't make a difference.
All libraries uploaded on Github have been compiled with `embed_kernels=1` therefore I don't think that's where your problem comes from .

Can you try to catch the `cl::Error` in your code in order to print the error number ? (Like [here](https://github.com/ARM-software/ComputeLibrary/blob/v17.06/utils/Utils.cpp#L82))

If you say you manage to create your own context and device then you could try to manually call the `init` functions of the `CLKernelLibrary` and `CLScheduler` with them (Like [default_init()](https://github.com/ARM-software/ComputeLibrary/blob/v17.06/arm_compute/runtime/CL/CLScheduler.h#L54) does)

**Comment by Valentin4869** [comment]
Thank you for your help. In the second code, the error was -34 (invalid context). But I've already built the library before seeing your answer, and using the self-built library for some reason resolves all the errors (cl_convolution runs without errors). Is there a list of all build options used for the provided binaries on this page? I wonder what was causing the error. I changed two options from the default configuration before building: target arch to _arm64-v8a_, and of course `embeded_kernels=True`.

**Comment by AnthonyARM** [comment]
Glad it works !

You can use `strings libarm_compute.so | grep arm_compute_version` to find out what parameters were used.

It's odd that the pre-built binaries don't work for you because we test them on some boards before we release them and they worked then.

**Comment by Valentin4869** [comment]
I'm not exactly sure what was causing the errors, since the build options seem to be about the same. But I guess the issue is resolved now.

**Comment by steniu01** [comment]
I had exact same problem when I built the ARM compute library with toolchain 4.9 and the application with toolchain 5.4. After compile the library and application with same toolchain, it works.
