### ISSUE TITLE
Have no global pooling operation

### ISSUE THREAD

**Issue by SunAriesCN** [ARM-software/ComputeLibrary#221]
I'm writting the squeezenet with ACL, but I just found that ACL have no global pooling operation as the 'pool10' there. How can I deal with this problem?

**Comment by gmiodice** [comment]
Hi @SunAriesCN,

and thanks for your question. 
Global Pooling operation on OpenCL for ARM Mali GPUs will be available in the Compute Library with the next release (end of September).
Which device do you need global pooling for? ARM CPUs or ARM GPUs?

**Comment by SunAriesCN** [comment]
Hello @gmiodice,
Maybe both of them, CPUs and GPUs, because I want to let my application run on our mobile devices as well as possible. But now I really need the NEON version to evaluate how far can ComputeLibrary go.

**Comment by gmiodice** [comment]
Hi @SunAriesCN ,

Global Pooling support for both NEON (CPU) and OpenCL (GPU) with FP32 data type has been added in the latest release 17.10.

https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/core/NEON/kernels/NEPoolingLayerKernel.h

https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/core/CL/kernels/CLPoolingLayerKernel.h

Hope this can help,
Gian Marco

**Comment by SunAriesCN** [comment]
Oh, that‘s cool, thanks.
