### ISSUE TITLE
Anyone knows how to adjust GPU frequency? 

### ISSUE THREAD

**Issue by ysh329** [ARM-software/ComputeLibrary#225]
ARM Mali GPU.
Thanks in advance! :rofl:

**Comment by fvella** [comment]
What board do you have?

**Comment by ysh329** [comment]
@fvella 
RK3399
- CPU: A72+A53
- GPU: Mali-T860

I only found these lines below, and don't know how to adjust and fix freq. next :rofl: 

```shell
yuanshuai@firefly:/sys/class/misc/mali0/device/devfreq/ff9a0000.gpu$ ls
available_frequencies  cur_freq  governor  max_freq  polling_interval  subsystem    trans_stat
available_governors    device    load      min_freq  power             target_freq  uevent
yuanshuai@firefly:/sys/class/misc/mali0/device/devfreq/ff9a0000.gpu$ cat cur_freq 
200000000
yuanshuai@firefly:/sys/class/misc/mali0/device/devfreq/ff9a0000.gpu$ cat available_frequencies 
200000000 297000000 400000000 500000000 594000000 800000000
```

**Comment by fvella** [comment]
You can modify the frequency by changing the governor. 
Feel free to use our script https://github.com/ctuning/ck-env/tree/master/platform.init/firefly-linux 
or (better) use CK (https://github.com/ctuning/ck) it manages the frequency of GPU or CPU for you.

**Comment by ysh329** [comment]
@fvella Thanks, my big brother! :+1:

**Comment by ysh329** [comment]
@fvella Execuse, bother you again 🤣 . I recently wanted to adjust gpu frequency but failed using scripes [https://github.com/ctuning/ck-env/tree/master/platform.init/firefly-linux](https://github.com/ctuning/ck-env/tree/master/platform.init/firefly-linux) as below:

```shell
**$ sudo ./ck-print-gpu-freq 
*** Current GPU frequency:
cat: /sys/devices/platform/ff9a0000.gpu/devfreq/ff9a0000.gpu/cur_freq: No such file or directory

*** Min frequency:
cat: /sys/devices/platform/ff9a0000.gpu/devfreq/ff9a0000.gpu/available_frequencies: No such file or directory

*** Max frequency:
./ck-print-gpu-freq: line 21: all_freq: bad array subscript

*** Available GPU frequencies:
cat: /sys/devices/platform/ff9a0000.gpu/devfreq/ff9a0000.gpu/available_frequencies: No such file or directory

*** Current GPU governor:
cat: /sys/devices/platform/ff9a0000.gpu/devfreq/ff9a0000.gpu/governor: No such file or directory

*** Available GPU governor:
cat: /sys/devices/platform/ff9a0000.gpu/devfreq/ff9a0000.gpu/available_governors: No such file or directory
```

Besides, I found something as below:



```shell
yuanshuai@firefly:/sys/class/misc/mali0/device$ ls
clock                     core_mask  dtlb  dvfs_under_lock  fbdev  modalias  power_policy  subsystem      uevent
core_availability_policy  driver     dvfs  dvfs_upper_lock  misc   power     sc_split      time_in_state
```

**Comment by ysh329** [comment]
@fvella sorry. I fixed after reboot. 🤣

**Comment by tigert1998** [comment]
It seems that the script in [firefly-linux](https://github.com/ctuning/ck-env/tree/master/platform.init/firefly-linux) can only set the governor for GPU. Are there any methods to directly set a fixed frequency GPU? For instance, we have `/sys/devices/system/cpu/cpu4/cpufreq/scaling_setspeed` for setting CPU frequency.

**Comment by psyhtest** [comment]
@tigert1998 Nice!

The scripts we have for [HiKey970](https://github.com/ctuning/ck-env/tree/master/platform.init/hikey970-linux) is an untested copy from [HiKey960](https://github.com/ctuning/ck-env/tree/master/platform.init/hikey970-linux), as we don't have a HiKey970 board. Please feel free to send a PR with any changes you find useful!
