### ISSUE TITLE
manage 4D tensors

### ISSUE THREAD

**Issue by liviolima80** [ARM-software/ComputeLibrary#227]
Hi,
I have a text file with the weights of a convolutional layer and I want to load it to a 4D Tensor with size (5, 5, 3, 20). Are there any ways to use the Window object and the execute_window_loop function even if the Window object has only 3 dimension? Or I have to directly access to the Tensor ptr and loop over the 4 dimensions?
Thanks

**Comment by morgolock** [comment]
Hi @liviolima80 

Have you had a look at the documentation:
[https://arm-software.github.io/ComputeLibrary/v17.06/architecture.xhtml#S4_6_4_working_with_objects](url) ?

That's an example that shows how to fill a tensor.

**Comment by GeorgeARM** [comment]
Closing as documentation provides guidelines on this. Reopen if needed
