### ISSUE TITLE
undefined reference to `arm_compute::graph::Graph::Graph()'

### ISSUE THREAD

**Issue by nevenp** [ARM-software/ComputeLibrary#232]
I built the library for Android, statically linked libarm_compute_core-static.a, libarm_compute-static.a and libam_compute_test_framework.a and still end up with the undefined reference to graph. All functions from previous release work well.

**Comment by AnthonyARM** [comment]
Graph symbols are in `arm_compute_graph`. 

What are you building? Are you using the graph API? (You shouldn't need to link against it otherwise)

**Comment by nevenp** [comment]
I am building the library as it is explained here: https://arm-software.github.io/ComputeLibrary/v17.09/index.xhtml#S3_3_1_library. I am trying to use graph API, but my application can't find graph symbols. I put using namespace arm_compute::graph; and using namespace arm_compute::graph_utils;, but when I try to do this: Graph graph;, I end up with the undefined reference.

**Comment by AnthonyARM** [comment]
There is a problem with the documentation: the graph is in a separate library
