### ISSUE TITLE
how to build benchmark with 17.09?

### ISSUE THREAD

**Issue by kaishijeng** [ARM-software/ComputeLibrary#233]
Is there a document to describe how to build benchmark and run it?

Thanks,

**Comment by AnthonyARM** [comment]
It's all in the documentation:
[How to build the library and the examples](https://arm-software.github.io/ComputeLibrary/v17.09/index.xhtml#S3_how_to_build)

[Running tests](https://arm-software.github.io/ComputeLibrary/v17.09/tests.xhtml#tests_running_tests)

**Comment by chengshengchan** [comment]
Just add benchmark_tests=1 / validation_tests=1.
17.09 seems doesn't need other libraries, like "libbenchmark.a".

**Comment by kaishijeng** [comment]
Thanks,
