### ISSUE TITLE
OpenVX on arm

### ISSUE THREAD

**Issue by peter73421** [ARM-software/ComputeLibrary#236]
Hello all,

Is there any OpenVX implementation for ARM? I can find this https://gpuopen.com/compute-product/amd-openvx/ but not for ARM devices. 

Thanks,
Peter

**Comment by AnthonyARM** [comment]
Hi,
No there isn't but you can use the Khronos [Openvx 1.0.1 Sample Implementation](https://www.khronos.org/registry/vx/sample/openvx_sample_1.0.1.tar.bz2)
