### ISSUE TITLE
Compile error on half.hpp

### ISSUE THREAD

**Issue by wonderzy** [ARM-software/ComputeLibrary#237]
In file included from ./support/Half.h:36:0,
                 from ./arm_compute/core/Types.h:29,
                 from ./arm_compute/core/IAccessWindow.h:29,
                 from ./arm_compute/core/AccessWindowStatic.h:28,
                 from src/core/AccessWindowStatic.cpp:24:
include/half/half.hpp:275:8: error: missing space between ‘""’ and suffix identifier
   half operator""_h(long double);

**Comment by AnthonyARM** [comment]
We've never seen that error, could you please tell us what compiler version you're using and what SCons options?

**Comment by wonderzy** [comment]
scons on linux armv7a debug=0 assert=0
