### ISSUE TITLE
Trained Model to run the example

### ISSUE THREAD

**Issue by rayjs** [ARM-software/ComputeLibrary#238]
Hi,

Where can I find the model to run this sample? Is there some model zoo?

https://github.com/ARM-software/ComputeLibrary/blob/master/examples/graph_lenet.cpp

Thank you.

**Comment by GeorgeARM** [comment]
Hello @rayjs ,

No, its not available on model zoo.
What we used for this was the first caffe example that can be found [here](https://github.com/BVLC/caffe/tree/master/examples/mnist)
If you follow this example you will train a model from caffe and then you can use our caffe conversion script from [here](https://github.com/ARM-software/ComputeLibrary/blob/master/scripts/caffe_data_extractor.py) to extract the weights.
Then run the example.
We will add more complex models that you can find their weights in model zoo in the next releases.

Hope this helps.

**Comment by GeorgeARM** [comment]
Hello @rayjs,

Did you manage to run the example?

**Comment by rayjs** [comment]
Hi @GeorgeARM 

No I did not run the example, Sorry. You may close this issue.

Thanks
