### ISSUE TITLE
How do we restrict OpenCL to use ARM CPU only, vs. Mali only?

### ISSUE THREAD

**Issue by adroit91** [ARM-software/ComputeLibrary#24]
If we want to benchmark performance that we get from OpenCL kernels making only the CPU, and then only the GPU, or both, any suggestions on that?

PS: Great job! The embedded world needed this.

**Comment by AnthonyARM** [comment]
Hi,

Thanks for your support !

By default the library will use the default cl::Context and default cl::CommandQueue

We haven't actually tried that, but I imagine it should be as simple as setting the cl::CommandQueue and cl::Context manually at the beginning of your test:

```cpp
    CLScheduler::get().default_init();
    cl::Context context( CL_DEVICE_TYPE_CPU ); /* or CL_DEVICE_TYPE_GPU */
    cl::CommandQueue queue( context);
    CLScheduler::get().init(context, queue);
```
Let me know if this does what you want.

Using both at the same time will be more tricky as currently the Runtime scheduler will use only a single queue. However this would be definitely possible if you were using the library at the Core level (i.e only the CLKernels not the CLFunctions) but that would be more work.

Hope this helps,

**Comment by AnthonyARM** [comment]
Please reopen if it doesn't solve your problem
