### ISSUE TITLE
The ComputeLibrary Performance

### ISSUE THREAD

**Issue by qfmy** [ARM-software/ComputeLibrary#241]
Does this library rely on the ARM HPC tool？Is there any performance compared to OpenBLAS like the picture below?
![dgemm-vs-openblas-a57](https://user-images.githubusercontent.com/6381724/31501325-87dcf246-af9c-11e7-842e-27e479eaffc6.png)
(https://developer.arm.com/products/software-development-tools/hpc/arm-performance-libraries/benchmarks)
Recently, I test the GEMM of ComputeLibrary, but the performance is worse than the OpenBLAS. Any one can help me? @AnthonyARM  Thanks a  lot!

**Comment by ysh329** [comment]
@qfmy Hi, my big brother. I wanna ask [How can I benchmark GEMM perforamce · Issue #275 · ARM-software/ComputeLibrary](https://github.com/ARM-software/ComputeLibrary/issues/275).

**Comment by AnthonyARM** [comment]
@qfmy In the more recent releases a lot of work went into NEON optimisations, and the Compute Library should now be faster than OpenBLAS in most cases.
Have you tried any recent release ?

**Comment by qfmy** [comment]
@AnthonyARM yeap，the Compute Library has been faster than before， thanks a lot!
