### ISSUE TITLE
 The problem of compiling ComputeLibrary

### ISSUE THREAD

**Issue by zt383154** [ARM-software/ComputeLibrary#242]
I use the following compile commands.
CXX=clang++ CC=clang scons Werror=1 -j8 debug=0 neon=1 opencl=0 os=android arch=armv7a
The following error occurred.
![11](https://user-images.githubusercontent.com/31474773/31541144-4cb623a0-b040-11e7-9d57-a33604254d5e.jpg)
I don't know how to solve it.
Any one can help me?

**Comment by qfmy** [comment]
There is no need to add CXX=clang++ CC=clang when you use scons. You can refer to the SConstruct on the root directory. Hope it helps you out.

**Comment by AnthonyARM** [comment]
Are you sure you're using the recommended version of the ndk, with the right libc++ ? ([r14 + gnustl](https://arm-software.github.io/ComputeLibrary/v17.10/index.xhtml#S3_3_android))

**Comment by zt383154** [comment]
Yes, I'm using is android-ndk-r14b +gunstl.   @AnthonyARM 
 
MY_TOOLCHAINS is my build toolchains path.
First, I build toolchain with command.
$NDK/build/tools/make_standalone_toolchain.py --arch arm --install-dir $MY_TOOLCHAINS/arm-linux-androideabi-4.9 --stl gnustl

Then, add the toolchains to PATH.
export PATH=$PATH:$MY_TOOLCHAINS/aarch64-linux-android-4.9/bin:$MY_TOOLCHAINS/arm-linux-androideabi-4.9/bin

Finally, compile it with command.
CXX=clang++ CC=clang scons Werror=1 -j8 debug=0 neon=1 opencl=0 os=android arch=armv7a

**Comment by FreshZZ** [comment]
the same problem....

**Comment by FreshZZ** [comment]
@zt383154 
I know how to solve it. use
$NDK/build/tools/make_standalone_toolchain.py --arch arm --install-dir $MY_TOOLCHAINS/arm-linux-androideabi-4.9 --stl gnustl --api 21

**Comment by AnthonyARM** [comment]
Thanks for helping, could you explain please what fixed it?
Is it `--api 21` ?

**Comment by zt383154** [comment]
Thank you very much. I've built it successfully with the way you provided it. @FreshZZ

**Comment by ymbaek** [comment]
`--api 21` is working. Thank you very much. @FreshZZ . Even if `--api 21` flag is not used for NDK toolchain build, ACL 17.09 is successfully built. However, 17.10 is failed.

**Comment by mdigiorgio** [comment]
Closing the issue as it seems to be solved. Reopen if needed.
