### ISSUE TITLE
how to init a tensor with a float point ??

### ISSUE THREAD

**Issue by victorygogogo** [ARM-software/ComputeLibrary#246]
how to init a tensor with a float point ??

who can help me ?

**Comment by mpekatsoula** [comment]
Hi @victorygogogo ,

You can check [here](https://arm-software.github.io/ComputeLibrary/v17.09/architecture.xhtml#S4_6_4_working_with_objects) on how to work with Tensors.

**Comment by victorygogogo** [comment]
@mpekatsoula      execute_window_loop(input_window, [&](const Coordinates & id)
    {
        std::cout << "Setting item [" << id.x() << "," << id.y() << "," << id.z() << "]\n";
        *reinterpret_cast<float *>(input_it.ptr()) = src_data[id.z() * (width * height) + id.y() * width + id.x()];
    },
    input_it);

by this way to init the tensor ,how about the efficiency,if I have a big array data ??

**Comment by mpekatsoula** [comment]
You can create an iterator to iterate through each row and use memcpy as seen in the output tensor, instead of copying each element.

`    execute_window_loop(output_window, [&](const Coordinates & id)
    {
        std::cout << "Copying one row starting from [" << id.x() << "," << id.y() << "," << id.z() << "]\n";
        // Copy one whole row:
        memcpy(dst_data + id.z() * (width * height) + id.y() * width, output_it.ptr(), width * sizeof(float));
    },
    output_it);`

**Comment by victorygogogo** [comment]
assume I have three ptrs ,all ptrs have data,if I fill the tensors with memcpy may cost much time ,do you have a way to decrease memcpy  ??

**Comment by GeorgeARM** [comment]
Hello @victorygogogo,

The reason that you have to do a memcpy is that you don't know how much padding your tensor will have. In case your tensor have padding you cannot avoid the memcpy. But if you configure your functions and no padding is required for the tensor then you could essentially set the ptrs memory directly to the tensor. We do no have an interface for this yet as the cases that padding is not required are rare. We will look into into though.

Hope this helps.

**Comment by victorygogogo** [comment]
I use NEDirectConvolutionLayer to have a test ,the input data is already ok.
NEDirectConvolutionLayer  can handle pad data ,am I right ?so I think not need consider the padding.
I get a different result use NEDirectConvolutionLayer  compare to cpu .
I use this way as below to init a tensor , am I right ?it is a 4d tensor.
    Window weight_window;
    weight_window.use_tensor_dimensions(neweights.info()->tensor_shape(),Window::DimY);
	Iterator neweights_it(&neweights, weight_window);
	execute_window_loop(weight_window, [&](const Coordinates & id)
    {
        memcpy(neweights_it.ptr(),weight + id[3] * (this->blobs_[0]->width() * this->blobs_[0]->height() * this->blobs_[0]->channels()) + id[2] * (this->blobs_[0]->width() * this->blobs_[0]->height()) + id[1] * this->blobs_[0]->width(),this->blobs_[0]->width()*sizeof(float));
    },neweights_it);

**Comment by victorygogogo** [comment]
@GeorgeARM  I use this way to map ptr to tensor ,
neweights.buffer() = (uint8_t *)weight;
newweights is a tensor ,weight is a ptr.
there is a build error.
cay you tell me how to map a tensor to a ptr ?

**Comment by AnthonyARM** [comment]
You can't replace the pointer inside the object, you have to copy the data in it as explained in the [documentation](https://arm-software.github.io/ComputeLibrary/v17.10/architecture.xhtml#S4_6_4_working_with_objects)

**Comment by victorygogogo** [comment]
I  refer to the document then I realize this fucntion ,But fill the tensor with a ptr ,cost more than 100ms  ,    so I want to reduce the time to void memcpy.

**Comment by GeorgeARM** [comment]
Hello @victorygogogo,
Create a tensor, initialize the shape, allocate and fill directly if you know that no padding is needed.
example pseudocode:
```
// Create, initialize and allocate tensor
Tensor weights;
weights.allocator()->init(...);
weights.allocator()->allocate();

// Take buffer from tensor and directly fill
auto *ptr = reinterpret_cast<T>(weights.buffer());
// Use ptr to fill the data
```

**Comment by GeorgeARM** [comment]
Closing issue. You cannot assign a pointer directly to Tensor backing memory, but you can create one allocate and fill in-place. Reopen if needed!
