### ISSUE TITLE
The result calculated by NEDirectConvolutionLayer and NEConvolutionLayer are different

### ISSUE THREAD

**Issue by zt383154** [ARM-software/ComputeLibrary#247]
I used NEConvolutionLayer，and the calculation is correct, and then changed the NEConvolutionLayer to NEDirectConvolutionLayer, and the results were quite different.

The program is similar to the following:
```
//assume input,kernel_size_w,kernel_size_h,and the other variables are ready.
NEConvolutionLayer  conv; 
//NEDirectConvolutionLayer  conv; 
const TensorShape weights_shape(kernel_size_w, kernel_size_h, input_shape.z(), out_num);
const TensorShape biases_shape(out_num);
const TensorShape out_shape(out_width,out_height,out_num);

weights.allocator()->init(TensorInfo(weights_shape, 1, DataType::F32));
weights.allocator()->allocate();
load weights......
biases.allocator()->init(TensorInfo(biases_shape, 1, DataType::F32));
load biases......
out.allocator()->init(TensorInfo(out_shape, 1, DataType::F32));
out.allocator()->allocate();
conv.configure(input,&weights,&biases,&out,PadStrideInfo(stride_w,stride_h,pad_w,pad_h));
conv.run()
```
When using NEConvolutionLayer , can get the correct result，but use NEDirectConvolutionLayer, the result is incorrect and very bad. Why is it different? Who can tell me why? Thank you

**Comment by AnthonyARM** [comment]
You need to call allocate after configure (not before).
The reason is that configure changes the padding requirements of the tensor.

**Comment by zt383154** [comment]
@AnthonyARM The problem has been solved, thank you very much.

**Comment by victorygogogo** [comment]
@zt383154  I use NEDirectConvolutionLayer in caffe ,but I have the different result with cpu convlution.
can you give me some suggestion ??
I user window fill tensor too.

**Comment by victorygogogo** [comment]
NEConvolutionLayer  and NEDirectConvolutionLayer  which one is fast  ?

**Comment by zt383154** [comment]
For 1*1 and 3*3 kernel, NEDirectConvolutionLayer is faster than NEConvolutionLayer. @victorygogogo

**Comment by victorygogogo** [comment]
you mean 55 NEConvolutionLayer is faster ?  but I test NEDirectConvolutionLayer and NEConvolutionLayer is lower than cpu ,do you have the same result  ?

**Comment by zt383154** [comment]
I only tested 1*1 and 3*3, and 5*5 didn't test. @victorygogogo

**Comment by victorygogogo** [comment]
@zt383154  OK ,I kwow now.
