### ISSUE TITLE
A question about opencl work size setting in ComputeLibrary

### ISSUE THREAD

**Issue by doldre** [ARM-software/ComputeLibrary#248]
I am reading ComputeLibrary code for using it better. But I found something I don't understand.
In [src/core/CL/kernels/CLGEMMMatrixMultiplyKernel.cpp](https://github.com/ARM-software/ComputeLibrary/blob/master/src/core/CL/kernels/CLGEMMMatrixMultiplyKernel.cpp#L66), It setting a fix _lws_hint.
```cpp
    if(output->info()->dimension(1) == 196)
    {
        _lws_hint = cl::NDRange(1, 7);
    }
    else
    {
        _lws_hint = cl::NDRange(8, 8);
    }
```

In [src/core/CL/ICLKernel.cpp](https://github.com/ARM-software/ComputeLibrary/blob/master/src/core/CL/ICLKernel.cpp#L39), It  just check lws is less or equal than gws on every dimension. 
```cpp
 if((valid_lws[0] <= gws[0]) && (valid_lws[1] <= gws[1]) && (valid_lws[2] <= gws[2]))
    {
        lws = valid_lws;
    }
```

I insert printf [here](https://github.com/ARM-software/ComputeLibrary/blob/master/src/core/CL/ICLKernel.cpp#L71) to see the value of gws and lws.  The result is
> gws dim = 3
lws dim = 2
gws = {20, 250, 1}
lws = {8, 8, 1}

Because It does't ensure 
> number of work-items specified by global_work_size is evenly divisable by size of work-group given by local_work_size. 

Why ComputeLibrary will not cause CL_INVALID_WORK_GROUP_SIZE(-54).
> if local_work_size is specified and **number of work-items specified by global_work_size is not evenly divisable by size of work-group given by local_work_size** or does not match the work-group size specified ... 

This question is very confusing for me. Because I encountered CL_INVALID_WORK_GROUP_SIZE(-54) before,And I try to set similar local work size like ComputeLibrary but there always be a CL_INVALID_WORK_GROUP_SIZE. Why ComputeLibrary worked very  well. 

Thanks very much for your help.

**Comment by AnthonyARM** [comment]
This restriction is only true for OpenCL < 2.0, which is why we're using
either OpenCL 1.2 + `-cl-arm-non-uniform-work-group-size` or `-cl-std=CL2.0` to compile our kernels in the [CLKernelLibrary](https://github.com/ARM-software/ComputeLibrary/blob/v17.10/src/core/CL/CLKernelLibrary.cpp#L594)

**Comment by doldre** [comment]
It perfect solved my question. Thank you again.
Where can I find a compilation options list for detail. Are these opts in OpenCL standord?

**Comment by GeorgeARM** [comment]
Hello @doldre,
It is part of the standard for OpenCL 2.0 and above. Arm provides it as an extension in OpenCL 1.2.
Hope this helps.

**Comment by doldre** [comment]
Thanks, it's very helpful.
