### ISSUE TITLE
  Runtime problem

### ISSUE THREAD

**Issue by daming5432** [ARM-software/ComputeLibrary#249]
when i run the example of opencl have this error: ERROR in load_program src/core/CL/CLKernelLibrary.cpp:673: Kernel file ./cl_kernels/convolution3x3.cl does not exist.

**Comment by AnthonyARM** [comment]
Recompile the library with `embed_kernels=1` or copy  `src/core/CL/cl_kernels/` to your working directory

**Comment by daming5432** [comment]
Thank you very much. now this error is not appear，but the new error is” “CANNOT LINK EXECUTABLE: cannot locate symbol "__aeabi_memcpy4" referenced by "/data/local/tmp/cl_convolution_arm"...“  some one say this is the problem about android sdk version, but i do not us sdk.

**Comment by AnthonyARM** [comment]
If you are targeting Android, you have to use the NDK toolchains as explained in the [documentation](https://arm-software.github.io/ComputeLibrary/v17.10/index.xhtml#S3_3_android)
That's because Android uses a different libc from regular Linux compilers.

**Comment by daming5432** [comment]
Thank you very much.Now the neoncl_scale_median_gaussian.cpp  sample can run. But when i build the example of graph_alexnet.cpp it show error like this :./libarm_compute_graph-static.a(Tensor.o):src/graph/Tensor.cpp:function arm_compute::graph::Tensor::set_target(arm_compute::graph::TargetHint): error: undefined reference to 'arm_compute::CLTensor::CLTensor()'

**Comment by AnthonyARM** [comment]
Do you build the example by hand or using `SCons` ? Are you sure you built with both `opencl=1` and `neon=1` ?

**Comment by daming5432** [comment]
Yes, this is my option :CXX=clang++ CC=clang scons Werror=1 -j8 debug=0 assert=0 neon=1 opencl=1 os=android arch=armv7a embed_kernels=1

**Comment by daming5432** [comment]
and compile the demo like this:arm-linux-androideabi-clang++ examples/graph_lenet.cpp utils/Utils.cpp -I. -Iinclude -std=c++11 -larm_compute-static -larm_compute_core-static -larm_compute_graph-static -L. -o alexnet_convolution_arm -static-libstdc++ -pie -lOpenCL -DARM_COMPUTE_CL

**Comment by giorgio-arena** [comment]
When compiling a graph example, you also need to add utils/GraphUtils.cpp to your command.
Additionaly, the linking order would be graph / compute / core.

Your final command will be something like:
arm-linux-androideabi-clang++ examples/graph_lenet.cpp utils/Utils.cpp utils/GraphUtils.cpp -I. -Iinclude -std=c++11 -larm_compute_graph-static -larm_compute-static -larm_compute_core-static -L. -o alexnet_convolution_arm -static-libstdc++ -pie -lOpenCL -DARM_COMPUTE_CL

**Comment by GeorgeARM** [comment]
Closing issue. Reopen if needed. Issue was wrong command.
