### ISSUE TITLE
Some wrong in building the library 

### ISSUE THREAD

**Issue by ydmo** [ARM-software/ComputeLibrary#25]
CXX=clang++ CC=clang scons Werror=1 -j8 debug=0 asserts=1 neon=0 opencl=1 embed_kernels=1 os=android arch=armv7a

and then:

test_helpers/Utils.cpp:89:56: error: use of undeclared identifier 'errno'
                  << "ERROR " << err.what() << " " << (errno ? strerror(errno) : "") << std::endl;
                                                       ^
test_helpers/Utils.cpp:89:73: error: use of undeclared identifier 'errno'
                  << "ERROR " << err.what() << " " << (errno ? strerror(errno) : "") << std::endl;
                                                                        ^
2 errors generated.
scons: *** [build/test_helpers/Utils.o] Error 1
scons: building terminated because of errors.

please help~
Thanks a lot

**Comment by mpflanzer** [comment]
Thanks for letting us know about this issue. It seems to be the same as reported in this pull request #11 
The solution is to add `#include <cerrno>` at the beginning of `Utils.cpp`.

Could you please try if that solves the issue for you?

**Comment by AnthonyARM** [comment]
The pull request has been merged, this problem should be fixed. 
Please re-open if you still see the issue
