### ISSUE TITLE
make tensor.buffer point to a ptr ,build error

### ISSUE THREAD

**Issue by victorygogogo** [ARM-software/ComputeLibrary#250]
Tensor neinput;
''''init ...........''''

neinput.buffer() = (uint8_t*)bottom_data;

there is a build error .

**Comment by GeorgeARM** [comment]
Hello @victorygogogo,
What you are trying to do is wrong. You cannot do that. You cannot assign a pointer to the buffer.
You have to either copy the pointer data to the buffer or allocate the tensor and fill the buffer directly.

**Comment by victorygogogo** [comment]
how to allocate the tensor and fill the buffer directly ?
