### ISSUE TITLE
*.npy import using utils::load_trained_data

### ISSUE THREAD

**Issue by hrahoy** [ARM-software/ComputeLibrary#252]
Hello, I am trying to import trained CNN model by tensorflow.

I successfully exported weights and biases using numpy.save, 
and got conv1_w.npy conv2_w.npy ~ etc.
now I am stuck in importing.

How can I use utils::load_trained_data?

My code is like this, 
utils::load_trained_data(w1, "conv1_w.npy");
but it doesn't work well.

If I print all values of tensor, 
there are garbage values in first 20 weights.

Here blows are {tensor index} : {expected value} {imported value by ACL utils}

1 1 1 1: 0.093923 223668528.000000 
2 1 1 1: 0.326995 0.000000 
3 1 1 1: -0.117111 0.000000 
4 1 1 1: -0.160309 4489864774406922829824.000000 
5 1 1 1: 0.029763 0.000000 
1 2 1 1: 0.071430 0.000000 
2 2 1 1: 0.078665 0.000000 
3 2 1 1: -0.263717 76830765899902958769767626833920.000000 
4 2 1 1: -0.068656 17177135798093348864.000000 
5 2 1 1: -0.076336 67425655331976262975488.000000 
1 3 1 1: -0.098368 0.000000 
2 3 1 1: 0.080823 18727951024126427167784905474048.000000 
3 3 1 1: 0.218396 0.000000 
4 3 1 1: -0.113672 279041594268752367625779019776.000000 
5 3 1 1: -0.052352 0.000000 
1 4 1 1: 0.037643 0.000000 
2 4 1 1: -0.048042 0.000000 
3 4 1 1: -0.134158 0.000000 
4 4 1 1: 0.070288 13306610747884738862421990832540221440.000000 
5 4 1 1: 0.095696 0.000000 
1 5 1 1: -0.012641 0.093923 
2 5 1 1: -0.002426 0.326995 
3 5 1 1: 0.071112 -0.117111 
4 5 1 1: -0.156406 -0.160309 
5 5 1 1: -0.013958 0.029763 
1 1 1 2: -0.058150 0.071431 
2 1 1 2: 0.227068 0.078665 
3 1 1 2: 0.584990 -0.263717 
4 1 1 2: -0.421481 -0.068656 
5 1 1 2: 0.170601 -0.076336 
1 2 1 2: 0.191293 -0.098368 
...
..

What should I do to fix this problem?
I already checked those *.npy files have no problem.

thank you.

**Comment by AnthonyARM** [comment]
Are you sure you're accessing the data from your tensor correctly ? (i.e taking into account the padding the library might have added)
You can find more information [here](https://arm-software.github.io/ComputeLibrary/v17.10/architecture.xhtml#S4_6_4_working_with_objects)
If you did, please share your code with us.

**Comment by GeorgeARM** [comment]
Hello @hrahoy,

Has this been resolved?

**Comment by AnthonyARM** [comment]
No updates, closing.

**Comment by ymbaek** [comment]
I've ever met the same issue.  
In my case, .npy data is well loaded using NPYLoader like [here.](https://arm-software.github.io/ComputeLibrary/v18.03/architecture.xhtml#S4_6_images_tensors) But utils::load_trained_data makes same issue like @hrahoy .
