### ISSUE TITLE
How to fill a 4DTensor?

### ISSUE THREAD

**Issue by qfmy** [ARM-software/ComputeLibrary#253]
Hi, There only 3 dim(arm_compute::Window::DimX, arm_compute::Window::DimY, arm_compute::Window::DimZ), so , how can I fill a 4DTensor with a ptr?

**Comment by mpekatsoula** [comment]
Hi @qfmy ,

You can have a look at the documentation [here](https://arm-software.github.io/ComputeLibrary/v17.06/architecture.xhtml#S4_6_4_working_with_objects) on how to work with Tensors. For accessing 4th dimension you can use id[3].

**Comment by GeorgeARM** [comment]
Closing issue! Reopen if needed.
