### ISSUE TITLE
Image Format YUV_420_888

### ISSUE THREAD

**Issue by yge58** [ARM-software/ComputeLibrary#254]
My dear friends,

I want to ask about image format, specifically, what is the correct image format of input image?
Say I want to use this TensorInfo constructor 'https://github.com/ARM-software/ComputeLibrary/blob/bf8b01dfbfdca124673ade33c5eac8f3748d7abd/arm_compute/core/TensorInfo.h#L121'
Which format should I use? https://github.com/ARM-software/ComputeLibrary/blob/bf8b01dfbfdca124673ade33c5eac8f3748d7abd/arm_compute/core/Types.h#L42

- Issue No.1  

I am developing an Android NDK app, using preview image format AIMAGE_FORMAT_YUV_420_888, as listed in [here](https://developer.android.com/ndk/reference/ndk_image_8h.html)

The issue is I did not see YUV_420_888 being supported which is OK because Android NDK provides a function to to convert NDK's image format (YUV_420_888) into ACL's image format(RGB888). 

But is there a image format converter built in ACL? e.g. NEON-capable image format converter, I believe it is faster than NDK's because of NEON.
And will you add YUV_420_888 to the supported image format list?

-    Issue No.2  

Caffe uses BGR, not RGB.  If I port caffe weights into ACL. Will you add BGR image format?

Regards,

**Comment by AnthonyARM** [comment]
Hi,
Have you tried using the `IYUV` format for your `AIMAGE_FORMAT_YUV_420_888` ?

We don't currently have plans to add BGR support to the library.
Which functions would you need it for ?

**Comment by yge58** [comment]
Dear @AnthonyARM ,

Thank you for your reply. Current I am integrating Caffe2 with NDK camera API. Compute library will be add soon. 
My goal is to achieve fast classification, either using Caffe or Compute Library. That is why I am asking the source input image format. 
Well, Caffe uses BGR for input image format. I think Compute library will have to use BGR if the pretrained weights come from Caffe.
If indeed we have to use BGR for input image format. The functions I may think of is to have
a YUV to BGR image format converter with NEON/OpenCL support.

I may be wrong, thank you for the help.

**Comment by yge58** [comment]
The following is the specification of Android AIMAGE_FORMAT_YUV_420_888.
I think IYUV is the same, I will confirm this.
`/**
     * Multi-plane Android YUV 420 format.
     *
     * <p>This format is a generic YCbCr format, capable of describing any 4:2:0
     * chroma-subsampled planar or semiplanar buffer (but not fully interleaved),
     * with 8 bits per color sample.</p>
     *
     * <p>Images in this format are always represented by three separate buffers
     * of data, one for each color plane. Additional information always
     * accompanies the buffers, describing the row stride and the pixel stride
     * for each plane.</p>
     *
     * <p>The order of planes is guaranteed such that plane #0 is always Y, plane #1 is always
     * U (Cb), and plane #2 is always V (Cr).</p>
     *
     * <p>The Y-plane is guaranteed not to be interleaved with the U/V planes
     * (in particular, pixel stride is always 1 in {@link AImage_getPlanePixelStride}).</p>
     *
     * <p>The U/V planes are guaranteed to have the same row stride and pixel stride, that is, the
     * return value of {@link AImage_getPlaneRowStride} for the U/V plane are guaranteed to be the
     * same, and the return value of {@link AImage_getPlanePixelStride} for the U/V plane are also
     * guaranteed to be the same.</p>
     *
     * <p>For example, the {@link AImage} object can provide data
     * in this format from a {@link ACameraDevice} through an {@link AImageReader} object.</p>
     *
     * <p>This format is always supported as an output format for the android Camera2 NDK API.</p>
     *
     * @see AImage
     * @see AImageReader
     * @see ACameraDevice
     */
    AIMAGE_FORMAT_YUV_420_888       = 0x23,`
