### ISSUE TITLE
how to build a perf lib for arm computer lib ?

### ISSUE THREAD

**Issue by victorygogogo** [ARM-software/ComputeLibrary#256]
how to build a perf lib for arm computer lib ?

I use the build command like this ?

scons Werror=1 -j8 debug=0 asserts=1 neon=1 opencl=0 embed_kernels=0 os=android arch=arm64-v8a

who can give me some advice ?

**Comment by AnthonyARM** [comment]
It will go faster if you use `asserts=0`, however this will disable almost all validation of the parameters so make sure to test first with `asserts=1` during development.

**Comment by victorygogogo** [comment]
yes, in develop I use "asserts=1",so there is not another build switch to speed up the rate without "assers=0"?

**Comment by AnthonyARM** [comment]
That's correct: `asserts=0 debug=0` is what you need to use

**Comment by victorygogogo** [comment]
can you explain about embed_kernels ??

**Comment by AnthonyARM** [comment]
With `embed_kernels=1` all the OpenCL kernels in `src/core/CL/cl_kernels` are embedded inside the library binary. With `embed_kernels=0` they are loaded from files at runtime (Which means you need to have the folder with all the OpenCL kernels on the target)

**Comment by GeorgeARM** [comment]
Closing issue. Reopen if needed.
