### ISSUE TITLE
The result of NEConvolutionLayer is incorrect when the DataType is QS16

### ISSUE THREAD

**Issue by qfmy** [ARM-software/ComputeLibrary#259]
I have tried all datatype for NEConvolutionLayer (F32, QS16, QS8) . The result is incorrect when the datatype is QS16. 
![6c2ef64b-358d-4b49-b821-ff6e0635efc4](https://user-images.githubusercontent.com/6381724/31923173-d22cf9fa-b8ab-11e7-87b1-2deb2a7448f6.jpg)
Any one can help me? Thanks a lot!

**Comment by AnthonyARM** [comment]
We're going to need more information than that to help.
Please provide a way for us to reproduce the problem

**Comment by qfmy** [comment]
Hi,@AnthonyARM 
I the result of NEGEMM is same as NEConvolutionLayer when the datatype is QS16, The code below can reproduce the problem.
 `
#include <string>
#include "../inc/arm_compute/runtime/NEON/NEFunctions.h"
#include "../inc/arm_compute/core/Types.h"
#include "utils/Utils.h"

using namespace arm_compute;

int16_t my3x3_a[] =
        {
                1, 2, 1, 1,
                2, 4, 2, 2,
                1, 2, 1, 3
        };

int16_t my3x3_b[] =
        {
                1, 2, 1,
                1, 2, 4,
                2, 2, 1,
                2, 1, 3
        };

// int8_t my3x3_a[] =
//         {
//                 1, 2, 1, 1,
//                 2, 4, 2, 2,
//                 1, 2, 1, 3
//         };

// int8_t my3x3_b[] =
//         {
//                 1, 2, 1,
//                 1, 2, 4,
//                 2, 2, 1,
//                 2, 1, 3
//         };

template <typename T,typename P>
void fill_2d_tensor(T &tensor, P *data_ptr)
{
    unsigned int x = 0;
    unsigned int y = 0;
    unsigned int i = 0;

    unsigned int loop_num = 0;

    const unsigned int width  = tensor.info()->dimension(0);
    const unsigned int height = tensor.info()->dimension(1);

    loop_num = width * height;

    while(i < loop_num)
    {
        *reinterpret_cast<P *>(tensor.buffer() + tensor.info()->offset_element_in_bytes(Coordinates(x, y))) = data_ptr[i];
        i++;
        x++;
        if(x == width) ++ y, x = 0;
    }
}

template <typename T,typename P>
void get_2d_tensor(T &tensor, P *data_ptr)
{
    unsigned int x = 0;
    unsigned int y = 0;
    unsigned int i = 0;

    unsigned int loop_num = 0;

    const unsigned int width  = tensor.info()->dimension(0);
    const unsigned int height = tensor.info()->dimension(1);

    loop_num = width * height;

    while(i < loop_num)
    {
        data_ptr[i] = *reinterpret_cast<P *>(tensor.buffer() + tensor.info()->offset_element_in_bytes(Coordinates(x, y)));
        i++;
        x++;
        if(x == width) ++ y, x = 0;
    }
}

int main()
{ 
    Tensor    A,B,D;
    NEGEMM    mygemm;

    int16_t *out = (int16_t *)malloc(9*sizeof(int16_t));
    // int8_t *out = (int8_t *)malloc(9*sizeof(int8_t));

    int i = 0;
    int j = 0;

    TensorShape s_a(4, 3, 1);//w,h,b
    TensorShape s_b(3, 4, 1);//w,h,b
    TensorShape s_d(3, 3, 1);//w,h,b

    A.allocator()->init(TensorInfo(s_a,1,DataType::QS16));
    B.allocator()->init(TensorInfo(s_b,1,DataType::QS16));
    D.allocator()->init(TensorInfo(s_d,1,DataType::QS16));

    // A.allocator()->init(TensorInfo(s_a,1,DataType::QS8));
    // B.allocator()->init(TensorInfo(s_b,1,DataType::QS8));
    // D.allocator()->init(TensorInfo(s_d,1,DataType::QS8));

    mygemm.configure(&A, &B, NULL, &D, 1.0, 0);

    A.allocator()->allocate();
    B.allocator()->allocate();
    D.allocator()->allocate();

    fill_2d_tensor(A, my3x3_a);

    fill_2d_tensor(B, my3x3_b);

    mygemm.run();

    get_2d_tensor(D,out);

    for (i = 0; i < 3; i++)
    {
        for (j = 0; j < 3; j++)
            printf("%d ",out[i * 3 + j]);
        printf("\n");
    }

    free(out);
    return 0;
}
`
Anything wrong with my code? Thanks a lot!

**Comment by GeorgeARM** [comment]
@qfmy the QS8, QS16 actually stands for a fixed point datatype in arm compute library, in other words you are missing the fixed point position.
e.g.
```
  A.allocator()->init(TensorInfo(s_a,1,DataType::QS16, 1 /** fixed point position */));
   B.allocator()->init(TensorInfo(s_b,1,DataType::QS16, 1));
   D.allocator()->init(TensorInfo(s_d,1,DataType::QS16, 1));

We are adding assymetric quantized data types in the upcoming releases.

**Comment by qfmy** [comment]
Thanks a lot, @GeorgeARM ! So,  the fixed point position of the QS8 can be 0, but  the fixed point position of the QS16 must be equal or greater than 1 in the latest version. Is that right?

**Comment by GeorgeARM** [comment]
@qfmy [here](https://github.com/ARM-software/ComputeLibrary/blob/master/src/core/TensorInfo.cpp#L124) you can see what is allowed. So fixed point position should be greater than 1 for both, it just happens that the QS8 works I presume.

**Comment by qfmy** [comment]
@GeorgeARM I see.  Thanks a lot！
