### ISSUE TITLE
How can I do a 14x14x1 tensor activate(relu)?

### ISSUE THREAD

**Issue by dolmens** [ARM-software/ComputeLibrary#260]
I got an error: "_dims[i].end() <= _dims[i].start()".
It seems that activate(relu) only support 16x_x_ tensor.

**Comment by GeorgeARM** [comment]
Hello @dolmens,

Can you provide more in information? Can you post your test code? My assumption is that you allocate before you configure and your window get reduced and is empty.

**Comment by dolmens** [comment]
YES! Fixed. I allocated the tensor before my configuration! Thank you. Why this happened?

**Comment by GeorgeARM** [comment]
More information can be found here https://arm-software.github.io/ComputeLibrary/v17.10/architecture.xhtml#S4_6_1_padding_and_border
