### ISSUE TITLE
How do you do pooling with a pool_size other than 2 or 3?

### ISSUE THREAD

**Issue by dolmens** [ARM-software/ComputeLibrary#261]
I noticed that NEPoolingLayerKernel has an assertion of 
`ARM_COMPUTE_ERROR_ON(2 != pool_size && 3 != pool_size);`

**Comment by GeorgeARM** [comment]
@dolmens 
I think in the latest release we support all pooling sizes for floating data type.
https://github.com/ARM-software/ComputeLibrary/blob/master/src/core/NEON/kernels/NEPoolingLayerKernel.cpp#L196

**Comment by dolmens** [comment]
@GeorgeARM 
Ok, I will give it a try.

**Comment by GeorgeARM** [comment]
Closing issue. Reopen if needed.
