### ISSUE TITLE
Does the Graph API require OpenCL?

### ISSUE THREAD

**Issue by mohamedadaly** [ARM-software/ComputeLibrary#263]
I noticed this if directive in the Alexnet graph example

```c++
#ifndef ARM_COMPUTE_CL /* Needed by Utils.cpp to handle OpenCL exceptions properly */
#error "This example needs to be built with -DARM_COMPUTE_CL"
#endif /* ARM_COMPUTE_CL */
```

Does the graph api require OpenCL? Or can it work with Neon alone?

Thanks.

**Comment by AnthonyARM** [comment]
At the moment the Graph API is just a prototype, we still need to iron out some issues, so yes, for now you need to link against `OpenCL` (However if libOpenCL.so is not available at runtime on your platform it will still run using NEON only).
We're still actively working on it, and in the future you'll be able to compile the Graph API with only NEON or only CL, and your application should only have to link against the Graph API and not OpenCL.

**Comment by mohamedadaly** [comment]
Thanks Anthony!

**Comment by GeorgeARM** [comment]
Closing issue. Reopen if needed.
