### ISSUE TITLE
Compile for ARM-v8.2-a to evaluate FP16 performance on ARM NEON

### ISSUE THREAD

**Issue by atrah22** [ARM-software/ComputeLibrary#266]
Hello,
I couldn't compile for arm-v8.2-a 
Command: 
scons Werror=0 -j8 debug=0 neon=1 opencl=0 os=android arch=arm64-v8.2-a build=cross_compile examples=0 benchmark_tests=1 pmu=1

I get the error that Gcc 6.2.1 or higher is required for arm-v8.2-a.  I tried with multiple linaro gcc-linux-android and gcc-linux-gnu version but all went in vein.

I also cannot find any tutorial or post to compile a program for arm-v8.2-a.

**Comment by morgolock** [comment]
Hi @atrah22 

The following command must work well:
`PATH=$PATH:/work/local_tools/gcc-linaro-6.2.1-2016.11-x86_64_aarch64-linux-gnu/bin/ scons arch=arm64-v8.2-a neon=1 opencl=0 openvx=0 opencv=0 Werror=0 debug=0 validation_tests=1 benchmark_tests=1 debug=0 Werror=0 asserts=1 examples=0 standalone=1 cppthreads=0 openmp=0 -j8`

The toolchain version you must use is the one in the command above.

**Comment by atrah22** [comment]
Thankyou for the comment.
However, Shouldn't I put "os=android build=cross_compile" to compile for android platform? My host machine is linux and I want to compile for android platform.
I did compile with your command. However it shows error when run on android platform.

**Comment by morgolock** [comment]
Hi @atrah22 

The command in my previous reply was meant only for Linux targets. 

To build for android you should follow the instructions in the documentation: https://arm-software.github.io/ComputeLibrary/v17.10/index.xhtml#S3_3_android

What android device are you trying to run the FP16 benchmark tests?. The problem in building with the options 'os=android arch=arm-v8.2-a' is finding an android toolchain that supports FP16. All our work with FP16 has been done in Linux with GCC 6.2.1.
