### ISSUE TITLE
Fast corner extraction slower than OpenCV

### ISSUE THREAD

**Issue by y22ma** [ARM-software/ComputeLibrary#267]
Hey guys,

Recently compiled ComputeLibrary for iOS arm64 architecture, and did a fast corner keypoint extraction comparison between OpenCV and the ARM Compute routine.

Based on what I'm seeing, for an 8-level image pyramid with the largest resolution of 640x360, I'm seeing a 64ms +/- 50ms performance for the Compute Library, and 17ms +/- 2ms for OpenCV. Both libraries were compiled with O3 and ftree-vectorize flags in XCode, with the same fast corner parameters.

Any clue to the worse performance despite NEON acceleration?

**Comment by morgolock** [comment]
Hi @y22ma

Thanks. We are aware of the performance difference between the two implementations of this function. We will look into this.

**Comment by y22ma** [comment]
Much appreciated.

**Comment by y22ma** [comment]
Checking if there's an update on this? Any hint for me to look into myself?

**Comment by AnthonyARM** [comment]
No, currently our focus is on the machine learning functions, unfortunately we don't have the bandwidth to investigate computer vision performance issues.

**Comment by kanster** [comment]
> Hey guys,
> 
> Recently compiled ComputeLibrary for iOS arm64 architecture, and did a fast corner keypoint extraction comparison between OpenCV and the ARM Compute routine.
> 
> Based on what I'm seeing, for an 8-level image pyramid with the largest resolution of 640x360, I'm seeing a 64ms +/- 50ms performance for the Compute Library, and 17ms +/- 2ms for OpenCV. Both libraries were compiled with O3 and ftree-vectorize flags in XCode, with the same fast corner parameters.
> 
> Any clue to the worse performance despite NEON acceleration?

Hi Yan,

We have met the same issue and we are looking into it and try what was discussed on https://github.com/ARM-software/ComputeLibrary/issues/128

Just a following up, are you guys still using arm ComputeLibrary for frontend computations such as feature extraction in your work?

Best regards

**Comment by GeorgeARM** [comment]
Hello @kanster ,

We are in the process of deprecating our CV functionality as this is something that we don't actively support. Do you use it or is this of concern?

On the fast corners aspect I think the algorithm implemented by Compute Library vs OpenCV is different, that is the reason behind the performance gap.

Regards,
George

**Comment by kanster** [comment]
> Hello @kanster ,
> 
> We are in the process of deprecating our CV functionality as this is something that we don't actively support. Do you use it or is this of concern?
> 
> On the fast corners aspect I think the algorithm implemented by Compute Library vs OpenCV is different, that is the reason behind the performance gap.
> 
> Regards,
> George

Hi George,

We were trying to use ComputeLibrary to speed up low-level feature extraction methods to run our SLAM system on mobile devices. We were hoping that this library provided by ARM could provide better performance compared with our implementation using NEON. 

So, in my understanding, sooner or later, these functionalities will be deprecated from ComputeLibaray and ComputeLibrary will be focused on DL tasks optimization, is that correct?

Best regards
Kanzhi

**Comment by morgolock** [comment]
Hi @kanster 

Yes, that's right. CV functions in ACL will be deprecated in 20.11 and removed in 20.05.
