### ISSUE TITLE
Very slow map first time it is called on the output tensor

### ISSUE THREAD

**Issue by deepneuralnetwork** [ARM-software/ComputeLibrary#268]
I have stacked layers (consist of CLConvolutionLayer, CLActivationLayer, CLPoolingLayer). I fill the input tensor using like this: input.map(), memcpy(...), input.unmap(). It is extremely fast, about 0.003s. When I pass the input tensor through layers I want to read the network output and I do it like this: output.map(), memcpy(...), output.unmap() and it is extremely slow, about 0.45s. When I do that sequence of commands second time on output tensor, it is fast, about 0.003s. How can I make first mapping fast?

**Comment by GeorgeARM** [comment]
Hello @deepneuralnetwork,
My assumption is that this happens due to the CLConvolutionLayer.
In order to perform an efficient GEMM we reshape the input weights, thus this might need a bit more time for the first run, but it only happens in the first run. This new tensor will be used in every subsequent run. The only way to make this mapping fast is to provide weights that are already reshape to our requirements. You can use [this function](https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/CL/functions/CLConvolutionLayer.h#L51) to do so and you also have to make sure that the function is aware that the weights are reshaped by using the WeightsInfo parameter in the CLConvolutionLayer API [here](https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/CL/functions/CLConvolutionLayer.h#L100).
Hope this helps.

**Comment by deepneuralnetwork** [comment]
Can you please write me part of the code to reshape weights and pass it to CLConvolutionLayer?

**Comment by AnthonyARM** [comment]
You can have a look in the configure code of [CLConvolutionLayer](https://github.com/ARM-software/ComputeLibrary/blob/master/src/runtime/CL/functions/CLConvolutionLayer.cpp#L158) and just do the same yourself outside the function

**Comment by deepneuralnetwork** [comment]
I do it like this: 
        CLTensor _weights_reshaped;
        CLConvolutionLayerReshapeWeights _reshape_weights;

        const DataType dt = cl_input.info()->data_type();
        const int fixed_point_position = cl_input.info()->fixed_point_position();
        const bool _has_bias = (&cl_bias != nullptr);
        unsigned int mat_weights_cols = cl_weight.info()->dimension(3);
        unsigned int mat_weights_rows = cl_weight.info()->dimension(0) * cl_weight.info()->dimension(1) * cl_weight.info()->dimension(2) + (_has_bias ? 1 : 0);

        TensorShape shape_wr(mat_weights_cols, mat_weights_rows);
        TensorInfo  info_wr(shape_wr, 1, dt, fixed_point_position);
        _weights_reshaped.allocator()->init(info_wr);
        _weights_reshaped.allocator()->allocate();
        _reshape_weights.configure(&cl_weight, &cl_bias, &_weights_reshaped, false);

        conv->configure(&cl_input, &_weights_reshaped,
                              &cl_bias, &cl_output,
                              PadStrideInfo(1, 1,
                                            (unsigned int) conv->input_padding.top,
                                            (unsigned int) conv->input_padding.top), WeightsInfo(true, 3, 3, 16));


    _reshape_weights.run();
    conv->run();

and it passes, but it gives me wrong numbers for some reason. Do you know where can be a mistake?

**Comment by AnthonyARM** [comment]
You need to allocate after the configure

**Comment by deepneuralnetwork** [comment]
I did it, but nothing changed, cl_input, _weights_reshaped, cl_bias and cl_output, cl_weight and cl_bias are all allocated.

**Comment by deepneuralnetwork** [comment]
Still didn't find solution on this issue, is there anything else that could be wrong in this approach because of which I can't get correct results?

**Comment by deepneuralnetwork** [comment]
I reshaped weights and now is everything okey with inputs, but first problem still remains.

Here is more detailed information and minimal example.

When I run this:

    CLTensor tensor;
    tensor.allocator()->init(TensorInfo(TensorShape(3U, 3U, 16U, 1U), 1, DataType::F32));

    tensor.allocator()->allocate();
    high_resolution_clock::time_point t1_ = high_resolution_clock::now();
    tensor.map();
    high_resolution_clock::time_point t2_ = high_resolution_clock::now();
    tensor.unmap();

    high_resolution_clock::time_point t1__ = high_resolution_clock::now();
    tensor.map();
    high_resolution_clock::time_point t2__ = high_resolution_clock::now();
    tensor.unmap();

t1__ and t2__ are very small, both about 0.0001s.

But when I do this above commands:
layer1->run();
layer1->run();
layer1->run();

**Comment by AnthonyARM** [comment]
1) When run() returns it doesn't mean the kernel has finished to execute: you need to call CLScheduler::sync() for that.
2)  unmapping and cache maintenance is usually deferred to the first kernel execution which is why unmap() will be fast but the first kernel executing after that is slower.

**Comment by deepneuralnetwork** [comment]
Yes, the problem was in CLScheduler::sync(). When I call sync and wait for all layers to finish, I end up with very large execution time: ~0.5s. It seems that OpenCL ARM compute library for GPU is slower than NNPACK CPU implementation (~0.2s), I am using only convolution layers, max pooling layers and ReLUs. Do you have any advice how to speed things up?
