### ISSUE TITLE
Open CL SVM (shared virtual memory) support in ACL

### ISSUE THREAD

**Issue by msuryadeekshith** [ARM-software/ComputeLibrary#271]
Hello folks,

I'm using [CaffeonACL](https://github.com/OAID/CaffeOnACL) with Arm Compute Library (version 17.10). FYI,  I am using mobile GPU hardware which supports [SVM],
[1] https://community.arm.com/processors/b/blog/posts/exploring-how-cache-coherency-accelerates-heterogeneous-compute,

And also confirmed about OpenCL driver capabilities using clGetDeviceInfo OpenCL 2.0 API function passing CL_DEVICE_SVM_CAPABILITIES constant . The level of SVM support is returned as  coarse-gained SVM capability support which means its H/W I/O Coherency with coarse-grained SVM as per [1].

To experiment that, I have done the following settings,
  - useHostPtr set true in ComputeLibrary (CL2.hpp)
  - share variable set true in CaffeOnACL tensor_mem functions (acl_layer.cpp)
        => Note: the default settings are changed from false to true.

But Surprisingly, the output is wrong when I benchmark Alexnet for classification with the above changes. However, the output is proper when i use the default settings (no SVM support)  as well as when I by-pass all ACL layers.

Now, My query is whether the above settings will be good enough to enable SVM support
or 
Do I need to make any additional changes?

Thanks for your inputs,

Regards,
Surya Deekshith.

**Comment by GeorgeARM** [comment]
Hello @msuryadeekshith,

I am not quite sure if you can do it or how straightforward it is to do. We haven't added SVM support to ACL yet, but I think is something that we are going to add in one of the upcoming releases.
Hope this helps.

**Comment by GeorgeARM** [comment]
Closing issue. Support for SVM is added in 18.05. It will automatically use SVM allocations  if the CL device supports it
