### ISSUE TITLE
Unsure how to use QS16 Data Type

### ISSUE THREAD

**Issue by nwindt** [ARM-software/ComputeLibrary#272]
I want to accelerate a matrix multiply using QS16 values instead of f32. Can I fill this tensor of data type QS16  with float values? If not how do I fill and read fixed point values to the tensor, how should these fixed point values be represented?

**Comment by mpekatsoula** [comment]
Hi @nwindt,

You can find more information about Q number format [here](https://en.wikipedia.org/wiki/Q_(number_format)). 

You cannot directly assign float values to QS16. You have to first convert your float values to QS16, fill your tensors and then perform the matrix multiplication.

**Comment by nwindt** [comment]
Thank you @mpekatsoula
