### ISSUE TITLE
How can I benchmark this compute library? Integrated with framework such as caffe?

### ISSUE THREAD

**Issue by ysh329** [ARM-software/ComputeLibrary#273]
I referred CaffeOnACL  and Tutorial: Cartoonifying Images on Raspberry Pi with the Compute Library. CaffeOnACL integrates with ACL and tutorial using ACL directly.

I want to do some OpenCL benchmarks (classic network inference performance and GEMM performance) using ACL but I'm a little confused and not familiar about ACL. Is it necessary to integrate Caffe to benchmark classic networks?

**Comment by ysh329** [comment]
I found [ComputeLibrary/tests at master · ARM-software/ComputeLibrary](https://github.com/ARM-software/ComputeLibrary/tree/master/tests) and was building with `scons Werror=1 -j8 debug=1 neon=1 opencl=1 os=linux arch=arm64-v8a build=native embed_kernels=1 benchmark_tests=1 mali=1`.

**Comment by ysh329** [comment]
According to [Docs of Compute Library: Validation and benchmarks tests](https://arm-software.github.io/ComputeLibrary/v17.10/tests.xhtml), I tested all Conv. layer ACL supporting.

**Comment by AaronLiu92** [comment]
> According to [Docs of Compute Library: Validation and benchmarks tests](https://arm-software.github.io/ComputeLibrary/v17.10/tests.xhtml), I tested all Conv. layers ACL supporting.
Hello there. i'd like to ask about how to test GoogleNet by ACL Graph API. Can you help me with that? thanks

**Comment by ysh329** [comment]
Tests have googlenet, find it and test~~~

**Comment by AaronLiu92** [comment]
ok got it. I am kind of new here, do you have wechat so maybe we can have some technique exchanges in the future. thanks for ur help 👍
