### ISSUE TITLE
How can I benchmark GEMM perforamce

### ISSUE THREAD

**Issue by ysh329** [ARM-software/ComputeLibrary#275]
Hi. I'm new to ACL. and not familiars with C/C++ project structure. I want to benchmark GEMM performance for half type and float type. I read docs about [Compute Library: Validation and benchmarks tests](https://arm-software.github.io/ComputeLibrary/v17.10/tests.xhtml), which only have some pre-defined test cases and don't have GEMM test case. 

How can I benchmark GEMM performance using user-defined size? Thanks a lot!

**Comment by ysh329** [comment]
I ran all test cases and found result as below:

![_20171108111236](https://user-images.githubusercontent.com/7320657/32529901-1512942a-c476-11e7-9c96-6a873b81cb95.png)

How can I define size for these test case? 🙇

**Comment by ysh329** [comment]
I just want to run a general GEMM using ACL😭

**Comment by AnthonyARM** [comment]
You can change the datasets in the test framework [here](https://github.com/ARM-software/ComputeLibrary/blob/v17.10/tests/datasets/MatrixMultiplyGEMMDataset.h)

Hope this helps

**Comment by ysh329** [comment]
@AnthonyARM Thanks my big brother, I'll have a try! Closed.
