### ISSUE TITLE
Example (graph_lenet and graph_alexnet) execution Error: Failed to load binary data Not a directory

### ISSUE THREAD

**Issue by ysh329** [ARM-software/ComputeLibrary#277]
```shell
$ ./graph_lenet ./cat700x700.jpg 1

./graph_lenet

Instantiating CLConvolutionLayer!!!!!!!!!!!!!!!!!!!!!!!!!!!

ERROR in access_tensor utils/GraphUtils.cpp:301: Failed to load binary data Not a directory
!!!!!!!!!!!!!!!!!!!!!!!!!!!

Test FAILED
```

**Comment by GeorgeARM** [comment]
Hello @ysh329,
Do you have the model's trainable data?
AlexNet is really easy to deploy. Go [here](https://github.com/BVLC/caffe/tree/master/models/bvlc_alexnet) do download the caffemodel and the deploy file. Then use [this](https://github.com/ARM-software/ComputeLibrary/blob/master/scripts/caffe_data_extractor.py) script to dump the model data.
Then pass the folder that contains the model data to the graph_alexnet example and it should work.
More information on how to use the scripts can be found [here](https://arm-software.github.io/ComputeLibrary/v17.10/data_import.xhtml).
Hope this helps.

**Comment by ysh329** [comment]
@GeorgeARM Thanks, George 😻
