### ISSUE TITLE
How many vector register does Mali GPU have?

### ISSUE THREAD

**Issue by ysh329** [ARM-software/ComputeLibrary#278]
Maybe here is not an appropriate place to ask this questions about hardware. But 😢 I can't find a more appropriate place to ask. 

Does anyone know how many vector registers does mali T860 gpu have? I looked up mali gpu reference (ARM® Mali™ GPU OpenCL Version 3.3 Developer Guide), not mentioning the number of vector registers. 😢 

Thanks in advance.

**Comment by xingjinglu** [comment]
There are should be 1024 registers every core. As disclosed within follow blog:
https://community.arm.com/graphics/b/blog/posts/arm-mali-compute-architecture-fundamentals

**Comment by psyhtest** [comment]
I’m pleased to see that my blog post written 4 years ago is still being
considered useful. Thanks!

Interestingly, the new Bifrost architecture differs from Midgard in almost
every aspect :).

**Comment by ysh329** [comment]
Thanks!
