### ISSUE TITLE
how to use opencl 

### ISSUE THREAD

**Issue by xiaomage11** [ARM-software/ComputeLibrary#279]
I want to know how to use opencl to make cnn like using neonconvolution,please show an example as neon_convolition.cpp

**Comment by gunasekaran7** [comment]
You can look at "cl_convolution.cpp" in examples folder and  "AlexNetNetwork.h/LeNet5Network.h" files in "tests/network" folder for reference.

Note: Make sure you compile the library with opencl support when building as mentioned in the build instructions.

**Comment by xiaomage11** [comment]
@gunasekaran7  I saw the "cl_convolution.cpp",I want to use opencl to write lightenedcnn,before this time the lightenedcnn with neon_convolution is ok.and I change the interface to clconvolution.do not run pass.

**Comment by gunasekaran7** [comment]
have you enabled OpenCL support while compiling? and does the platform you are using supports OpenCL 1.2 FP?

**Comment by xiaomage11** [comment]
show my code:" *reinterpret_cast<float *>(weights1.buffer() + weights1.info()->offset_element_in_bytes(Coordinates(x, y, z, k))) = temp "  weights is defined cltensor, the program run down at this part, the reason is Segmentation fault,please tell me how to solve.thanks @gunasekaran7

**Comment by AnthonyARM** [comment]
Please post enough code so that we can reproduce

**Comment by xiaomage11** [comment]
//conv_1_1
    x = y = z = k = 0;
    std::ifstream conv_1_Wfile("conv1.txt");
    line = "";
    while(getline(conv_1_Wfile, line)){
        std::stringstream strstr(line);
        std::string word = "";
        while(getline(strstr, word, ',')){
            float temp = StringToFloat(word);
            *reinterpret_cast<float *>(weights1.buffer() + weights1.info()->offset_element_in_bytes(Coordinates(x, y, z, k))) = temp;
            ++ x;
            if(x == conv_1_weights_shape.x()) ++ y, x = 0;
            if(y == conv_1_weights_shape.y()) ++ z, y = 0;
            if(z == conv_1_weights_shape.z()) ++ k, z = 0;
            
        }
    }
    conv_1_Wfile.close();

**Comment by xiaomage11** [comment]
@AnthonyARM   I want to ask what is the different between using opencl to store number and neon?

**Comment by AnthonyARM** [comment]
@xiaomage11 : I'm not sure I understand the question. NEON processing is done on the CPU using the CPU's SIMD instructions, whereas OpenCL runs on the GPU. 
NEON buffers can only be used on the CPU side, whereas OpenCL buffers can be used on both the GPU side and the CPU side (It's is the applications responsibility to map / unmap the OpenCL buffers accordingly)
