### ISSUE TITLE
ACL how to use opencl 

### ISSUE THREAD

**Issue by xiaomage11** [ARM-software/ComputeLibrary#281]
I want to make lightened cnn with opencl .when i read weights into cltensor ,run error.I find the reason that data structure in gpu is different from neon cpu,so i want to know my own weights how to read into.please tell me thanks.Or give me an example as cnn,it can show how to read weights.

**Comment by AnthonyARM** [comment]
You can have a look at the documentation to see [how to fill/read tensors](https://arm-software.github.io/ComputeLibrary/v17.10/architecture.xhtml#S4_6_4_working_with_objects)

I would recommend using the Graph API to implement full networks: [here is an example](https://github.com/ARM-software/ComputeLibrary/blob/v17.10/examples/graph_alexnet.cpp)
However please note it's still experimental, and not all the nodes have been implemented yet.

**Comment by xiaomage11** [comment]
@AnthonyARM Is there any other way to load image data as well as weight and bias other than npy. I want to fill the tensor acooding to our own data format,is this possible?

**Comment by AnthonyARM** [comment]
You can use your own parser then use the `execute_window_loop` method described in the documentation to fill your tensors

**Comment by xiaomage11** [comment]
thanks for your answer. I will have a look about your suggestion.

**Comment by xiaomage11** [comment]
@AnthonyARM I find the way to solve this problem,thanks for you.
