### ISSUE TITLE
LRN only works for auto padding mode

### ISSUE THREAD

**Issue by joey2014** [ARM-software/ComputeLibrary#284]
To avoid memory copy between layers, the input and output tensor should be not auto padding. I tried to enable no padding mode, for most layers like conv, fc, pooling etc. , the mode works. But for LRN layer, it only work for auto padding mode. 

The test code provides test code for two modes, the input is 27x27x96(size is 279936). If auto padding enable, the input size is 331776 and the output size is 290304, this feature requires data alignment  for both input and output. If no padding mode is used, the input and output data size is 279936.

The test code shows LRN's output data is different with out_ref.bin when no padding mode is enable. 

steps to repro the issue:
1.  g++ lrn_test.cpp -std=c++11 -I. -Iinclude -o test -Lbuild -larm_compute -larm_compute_core
2.  ./test
3.  out_err.bin is for no padding and out_ok.bin for auto padding.
[lrn_padding.zip](https://github.com/ARM-software/ComputeLibrary/files/1477176/lrn_padding.zip)

**Comment by AnthonyARM** [comment]
@joey2014 I'm confused : why would padding prevent you from using the output of a layer as the input of another layer?

**Comment by joey2014** [comment]
@AnthonyARM For performance, auto padding can't guarantee this layer's input is same as the previous layer's output which makes memory copy or re-alignment is inevitable.  If there is way to make sure the layer's input size is same previous layer's output, auto padding also can avoid memory copy.

For example,
original Caffe layer input size-->output size
  conv     618348-->1161600  
  relu     1161600-->1161600
  pooling  1161600->279936
  lrn      279936->279936
zero copy from conv to lrn.

after autopadding
 conv       618348 --> 1161600
 relu        1161600 --> 1161600
 pooling  1182720 --> 279936
 lrn           331776 --> 290304
every layer need do memory re-alignment.

**Comment by AnthonyARM** [comment]
You get different sizes probably because you do:
```cpp
conv.configure(in, out);
in->allocate();
out->allocate();
relu.configure(in2, out2);
in2.allocate();
out2.allocate();
```
You should instead call all the configure that use a given buffer before allocating it:
```cpp
conv.configure(in,out);
in->allocate();
relu.configure(out, out2);
out->allocate();
out2->allocate();
```
Then you will see that `out` is initialised to the correct value and you don't need to copy data between layers. (Basically configure methods **extend** the padding to the minimum they require but they never shrink it.)

**Comment by GeorgeARM** [comment]
@joey2014 did this issue get solved with @AnthonyARM suggestion?

**Comment by GeorgeARM** [comment]
Closing issue. Assume that was a configuration problem. Reopen if it persists.
