### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by xiaomage11** [ARM-software/ComputeLibrary#285]
I run the code with opencl, Compile success，but run error,the problem show:
 terminate called after throwing an instance of 'std::runtime_error'
  what():  in create_kernel src/core/CL/CLKernelLibrary.cpp:604: Non uniform workgroup size is not supported!!
Aborted
what is the reason for this error? thanks

**Comment by AnthonyARM** [comment]
In order to use the library you need an OpenCL device that support either  `-cl-arm-non-uniform-work-group-size` or OpenCL 2.0

**Comment by xiaomage11** [comment]
@AnthonyARM  I am sure that my device can support opencl,I use opencl library to make lightened-cnn three days ago,it can run and  show the right result.

**Comment by AnthonyARM** [comment]
See for yourself: [CLKernelLibrary](https://github.com/ARM-software/ComputeLibrary/blob/v17.10/src/core/CL/CLKernelLibrary.cpp#L594)

**Comment by GeorgeARM** [comment]
Closing issue. Device does not have OpenCL 2.0 support or `-cl-arm-non-uniform-work-group-size` support.
