### ISSUE TITLE
OpenCL CNN

### ISSUE THREAD

**Issue by peter73421** [ARM-software/ComputeLibrary#288]
I think just missing it. I can fin cnn with NEON acceleration, is there example on CNN acclerated with OpenCL as well?

**Comment by AnthonyARM** [comment]
You have several options:
1) You can start from the NEON example and use the CL functions instead (They should have matching signatures)
2) You can use the Graph API: https://github.com/ARM-software/ComputeLibrary/blob/master/examples/graph_lenet.cpp
3) You can have a look at the tests: https://github.com/ARM-software/ComputeLibrary/blob/master/tests/networks/LeNet5Network.h

**Comment by GeorgeARM** [comment]
Closing issue. Reopen if needed.
