### ISSUE TITLE
Element-wise operations on Tensors

### ISSUE THREAD

**Issue by mo-morikawa** [ARM-software/ComputeLibrary#292]
Is it possible to perform element-wise operations on tensors, like with eltwise layers of ResNet?

**Comment by GeorgeARM** [comment]
Hello @mo-morikawa,

You can use the Addittion, Subtraction, PixelwiseMultiplication functions for example. These perform elementwise operations among tensors. Do you need a specific operation?

**Comment by GeorgeARM** [comment]
Closing issue. Reopen for clarification!
