### ISSUE TITLE
Runtime error in load program src/core/CL/CLKernelLibrary.cpp

### ISSUE THREAD

**Issue by iamant92** [ARM-software/ComputeLibrary#293]
can some tell me why CL Kernel Library not finding kernel file cl_kernels/convolution_layer.cl
it giving the error
`RuntimeError: in load_program src/core/CL/CLKernelLibrary.cpp:673: Kernel file ./cl_kernels/convolution_layer.cl does not exist.
`  
I was trying to test caffe on Odroid XU4 
os: ubuntu 16.04
Caffe build successfully.

**Comment by mpekatsoula** [comment]
Recompile the library with embed_kernels=1 or copy src/core/CL/cl_kernels/ to your working directory

**Comment by iamant92** [comment]
used this to complie.
`scons Werror=1 -j8 debug=0 asserts=1 neon=1 opencl=1 embed_kernels=1 os=linux arch=armv7a`
and file is already in the directory

**Comment by GeorgeARM** [comment]
Hello @iamant92,

We cannot debug it with the information you have provided.
We need to know what you are trying to run? What is the configuration of your model?
Which function does it try to configure when it fails?

**Comment by GeorgeARM** [comment]
Closing issue. Seems to be a configuration issue from your side. Reopen if needed.
