### ISSUE TITLE
Is there a way to downgrade version of ComputeLibrary?

### ISSUE THREAD

**Issue by wlgns0105** [ARM-software/ComputeLibrary#294]
I can't upgrade my g++ cross-compiler version to 4.9

so I want to download ComputeLibrary 17.04 version which requires g++ cross-compiler version 4.8

**Comment by AnthonyARM** [comment]
Have you tried to build ?
It might work with Werror=0. 
Otherwise you can use the v17.04 tag to download an older version: https://github.com/ARM-software/ComputeLibrary/tree/v17.04
You can also try to use the pre-built binaries and only build your application with 4.8?

**Comment by wlgns0105** [comment]
@AnthonyARM 
it didn't work with Werror=0
and i'm trying to download https://github.com/ARM-software/ComputeLibrary/tree/v17.04
Thanks for the help
