### ISSUE TITLE
Example for operation on existing data buffer

### ISSUE THREAD

**Issue by dattanchu** [ARM-software/ComputeLibrary#296]
I have a data buffer in memory (OpenCV Mat) that I want to run a Gaussian filter on. The example set currently doesn't give details on how to reuse existing buffer in memory. I plan to use ARM Compute Library side by side with OpenCV. Having to perform Tensor::allocator()->allocate() then copy over the data is slow.

**Comment by AnthonyARM** [comment]
In the next release we'll add the possibility to import existing allocations, however, correct me if I'm wrong, but I don't think OpenCV matrices usually use any padding ?
In which case you will be able to use OpenCV allocations for some computer vision algorithms (But the pixels near the borders will not get processed) and you will not be able to use it for machine learning algorithms (As it doesn't make sense to process only part of a matrix for machine learning)

**Comment by dattanchu** [comment]
OpenCV matrix does use padding to make the read of each row aligned. Its cv::Mat class doesn't have the concept of offset-from-begin though. Each header already points to where the data starts.

**Comment by AnthonyARM** [comment]
I guess you'll have to try and see if it works for you then, it's hard for us to work around this.

**Comment by dattanchu** [comment]
I will give it a try on my own. Will providing an implementation of arm_compute::core::ITensor that wraps an existing buffer (OpenCV's Mat being the prime example) still be on the roadmap for next release?

**Comment by AnthonyARM** [comment]
Yes, this will be part of the next release (At some point this month)

**Comment by GeorgeARM** [comment]
Support for importing existing memory to a Tensor was added in `v17.12`. It currently works for NEON.
A test can be found [here](https://github.com/ARM-software/ComputeLibrary/blob/master/tests/validation/NEON/UNIT/TensorAllocator.cpp#L42) and the respective API call [here](https://github.com/ARM-software/ComputeLibrary/blob/master/tests/validation/NEON/UNIT/TensorAllocator.cpp#L42).

**Comment by AnthonyARM** [comment]
Feature added: closing
