### ISSUE TITLE
src/runtime/IScheduler.cpp undeclared identifier sched_getcpu()

### ISSUE THREAD

**Issue by dattanchu** [ARM-software/ComputeLibrary#298]
When compiling ARM Compute Library under MacOS with Clang, I get the error

external/armcompute/src/runtime/IScheduler.cpp:46:15: error: use of undeclared identifier 'sched_getcpu'

I change line 46 to int cpu = 0; to bypass the issue. What should be the correct fix in this case?

**Comment by AnthonyARM** [comment]
It's odd, `sched_getcpu` is a Linux function from [sched.h](http://man7.org/linux/man-pages/man3/sched_getcpu.3.html) so you might have a problem with your clang setup ?
Does it also complain about not finding `sched.h` ?

**Comment by dattanchu** [comment]
sched_getcpu() is not available on MacOS as indicated in this SO's question.

https://stackoverflow.com/questions/33745364/sched-getcpu-equivalent-for-os-x

**Comment by AnthonyARM** [comment]
But, aren't you cross compiling ?
What are you trying to run the library on ? Your Mac ?

**Comment by dattanchu** [comment]
Ah my bad. My project uses Bazel so I have created a Bazel equivalent(-ish) of the project's SConsript.

Anyway, the root cause of the problem is sched_getcpu is not available in sched.h for Android 18. I can find some reference to it being available at Android 20. 

The fix for me was to tell Bazel to hot-patch and add 

extern int sched_getcpu(void);

on line 34 of IScheduler.cpp

**Comment by AnthonyARM** [comment]
Thanks for sharing your fix!

**Comment by AnthonyARM** [comment]
Just realised there was a similar issue in [this thread](https://github.com/ARM-software/ComputeLibrary/issues/242#issuecomment-338365588)
When you generate your standalone toolchain try to specify `--api 21`:

```
$NDK/build/tools/make_standalone_toolchain.py --arch arm64 --install-dir $MY_TOOLCHAINS/aarch64-linux-android-4.9 --stl gnustl --api 21
$NDK/build/tools/make_standalone_toolchain.py --arch arm --install-dir $MY_TOOLCHAINS/arm-linux-androideabi-4.9 --stl gnustl --api 21
```

We've updated the documentation so that it appears in the next release.
