### ISSUE TITLE
Question about IPC when the datatype is QS16

### ISSUE THREAD

**Issue by qfmy** [ARM-software/ComputeLibrary#299]
How many instructions can computelibrary do per cycle on cortex-a75 when the data type is QS16?  Thanks a lot!

**Comment by qfmy** [comment]
@AnthonyARM  @GeorgeARM  How many neon units does the library use on cortex-a75  when the datatype is QS16?

**Comment by AnthonyARM** [comment]
The library will create by default as many threads as there are cores reported on the system.
Please note QS8 and QS16 are going to be deprecated (No network seem to be using them).
We've added instead QASYMM8 support for quantised 8bit networks.

Feel free to reopen this ticket or create a new one if you've got more questions.

**Comment by qfmy** [comment]
Hi @AnthonyARM , I  am realy interested in low bit netwrok, can you talk something about QASYMM8, thanks a lot.
