### ISSUE TITLE
Can this library work on AllwinnerTech's or RochChip's Chip? like A64 and RK3288.

### ISSUE THREAD

**Issue by 9crk** [ARM-software/ComputeLibrary#3]
Can this library work on AllwinnerTech's or RochChip's Chip? like A64 and RK3288.

with this library, can I run the demo on RK3288 or some other ARM based chips?

what if they use a unknow GPU,like Mali400 / GC2000 or other ? do I need some more resources to get start my work?

**Comment by AnthonyARM** [comment]
Hi,
The NEON backend will work on any A class processor which has NEON.
The OpenCL backend will work on any Mali Midgard (6xx and above) or any Mali Bifrost (Gxx) GPU, but *not* Mali 400 as this architecture doesn't support OpenCL.
