### ISSUE TITLE
How to complie and debug ACL on the x86 computer ? 

### ISSUE THREAD

**Issue by WenguoLi** [ARM-software/ComputeLibrary#302]
How to complie and debug  ACL  On the x86 computer ? Are there  pure C-codes in the  ARM ComputeLibrary (ACL) ?

**Comment by AnthonyARM** [comment]
There is no pure c++ backend, but the OpenCL backend should work.

**Comment by GeorgeARM** [comment]
Closing issue. Reopen if needed. No pure C++ backend exists. OpenCL backend could be used in x86 but OpenCL 2.0 support will be needed.
