### ISSUE TITLE
gpu convolution problem

### ISSUE THREAD

**Issue by daming5432** [ARM-software/ComputeLibrary#304]
I'm new of the code of gpu convolution.Is this use the im2col+gemm? I find the im2col_gpu cost many time.How do I reduce the time or im2col, or use other better ways to achieve opencl gpu convolution.

**Comment by psyhtest** [comment]
@daming5432 It depends on your use case. The Compute Library supports direct convolution for 1x1, 3x3 and 5x5 convolutions. For example, the AlexNet example only uses gemm-based convolution for the 11x11 layer.

**Comment by GeorgeARM** [comment]
Closing issue. Reopen if needed. As @psyhtest  correctly mentioned you could try using `CLDirectConvolutionLayer` which is supported for kernels 1x1, 3x3 and 5x5.
