### ISSUE TITLE
[Q] different softmax axis with caffe

### ISSUE THREAD

**Issue by gpneil** [ARM-software/ComputeLibrary#305]
I found the behavior of NESoftmaxLayer function is different from caffe's implementation.
For example, if my input tensor is of shape [2x3x4] like the one below
[[[0.,   0.1, 0.01,  0.3]
  [0.01, 1.,  1.0,  -1.0]
  [0.2, -1.1, 0.2,   0.1]]

 [[-0.1,   0., 0.2, -0.01 ]
  [ 0.01, -1., 0.1,  0.   ]
  [ 0.1,   0., 0.3, -0.001]]]

The result of caffe is 
[[[ 0.30945832  0.26590106  0.20406148  0.47818008]
  [ 0.31256843  0.65401107  0.54917729  0.13031928]
  [ 0.37797323  0.08008786  0.24676125  0.39150071]]

 [[ 0.29960924  0.42231882  0.33222499  0.33122554]
  [ 0.33444721  0.15536241  0.30060959  0.3345544 ]
  [ 0.36594355  0.42231882  0.36716539  0.33422002]]]

But the result of Compute Library's softmax implementation is
[[[ 0.22396,  0.247514, 0.226211, 0.302315 ], 
  [ 0.148221, 0.398897, 0.398897, 0.0539849], 
  [ 0.314726, 0.0857728, 0.314726, 0.284776], 

 [[ 0.219819, 0.242937, 0.296724, 0.24052  ], 
  [ 0.289986, 0.105618, 0.317295, 0.287101 ], 
  [ 0.248128, 0.224516, 0.303065, 0.224291 ]]] 

I guess this difference is caused because of the choice of on which axis to perform the softmax operation.
In caffe, it uses axis 1 by default no matter what dimension the tensor is. In ComputeLibrary's language, this will be dimension 1 (the second dimension).
However, Compute Library performs softmax on the first axis.

If a tensor has more than 2 dimensions, then the results could be completely different as you already see.
Is there any way to specify on which axis to perform softmax in Compute Library?

Thanks,

**Comment by GeorgeARM** [comment]
Hello @gpneil ,

Yes as you correctly noticed we perform the softmax across the first dimension while caffe across the second (from the Compute Library view).
This is mainly done for performance reasons and unfortunately there is no way to perform softmax on a different axis at the moment.
Do you need to perform softmax across a different axis?

**Comment by GeorgeARM** [comment]
Closing. No reply. We have already a request for supporting Softmax across other dimensions
