### ISSUE TITLE
SCons error: Cannot compile NEON for x86

### ISSUE THREAD

**Issue by ysh329** [ARM-software/ComputeLibrary#307]
I downloaded source code using `git clone --recursive` command and installed a pre-built Scons from its official site. Then I finished the scons installation using `python setup.py install` command. However, when I tried to compile the ACL, it occurs errors as below: 
```shell
yuanshuai@firefly:~/code/ComputeLibrary$ scons Werror=1 -j1 debug=1 asserts=1 neon=0 opencl=1 embed_kernels=1 os=linux arch=arm64-v8a validation_tests=1 benchmark_tests=1 examples=1 mali=1
scons: Reading SConscript files ...
  File "/home/yuanshuai/code/ComputeLibrary/SConstruct", line 68

    print "Cannot compile NEON for x86"

                                      ^

SyntaxError: invalid syntax
```

Line 68 in Sconstruct:
```python
if env['neon'] and 'x86' in env['arch']:
    print "Cannot compile NEON for x86"
    Exit(1)
```

## Other info

```shell
$ scons -v
SCons by Steven Knight et al.:
        script: v3.0.0.rel_3.0.0:4395:8972f6a2f699, 2017/09/18 12:59:24, by bdbaddog on ubuntu-16
        engine: v3.0.0.rel_3.0.0:4395:8972f6a2f699, 2017/09/18 12:59:24, by bdbaddog on ubuntu-16
        engine path: ['/usr/local/lib/scons-3.0.0/SCons']
Copyright (c) 2001 - 2017 The SCons Foundation
$ python --version
Python 2.7.12
```

**Comment by ysh329** [comment]
Fixed. I downloaded SCONS code from [https://sourceforge.net/projects/scons/files/scons/](https://sourceforge.net/projects/scons/files/scons/) and `rm -rf` all files about SCONS. After that, I re-installed using this new code.

**Comment by terablade2001** [comment]
I have this kind of problem when I use Python 3.6.4; No problem exist when I use Python 2.7.11.

However I can bypass the problem of Python 3.6.4, by updating all the _print ""_ commands of the _**SConstruct**_ file with _print ("")_ commands (i.e. using parentheses).

Ps. _I use scon 3.0.1_.

**Comment by ysh329** [comment]
My system is Ubuntu
