### ISSUE TITLE
CLMinMaxLocation kernel's CLCoordinates2DArray o/p array order not matching with that of NEMinMaxLocation Coordinates2DArray o/p

### ISSUE THREAD

**Issue by ganashree-rm** [ARM-software/ComputeLibrary#312]
Hi,

On execution of CLMinMaxLocation kernel we find that the o/p CLCoordinates2DArray order of the values seem to be swapped and therefore it is not exactly as same as that of NEMinMaxLocation kernel's Coordinates2DArray. Could you provide us the reason for this mismatch in order of the location arrays in the two kernels.
We have attached the stand alone API's for both NEON and GPU targets and their respective o/p logs as well.

Thank You. 

[cl_minmaxloc_API.txt](https://github.com/ARM-software/ComputeLibrary/files/1574263/cl_minmaxloc_API.txt)
[neon_minmaxloc_API.txt](https://github.com/ARM-software/ComputeLibrary/files/1574264/neon_minmaxloc_API.txt)
[cl_minmaxloc_log.txt](https://github.com/ARM-software/ComputeLibrary/files/1574265/cl_minmaxloc_log.txt)
[neon_minmaxloc_log.txt](https://github.com/ARM-software/ComputeLibrary/files/1574266/neon_minmaxloc_log.txt)

**Comment by mpekatsoula** [comment]
Hi @ganashree-rm ,
The reason this happens is that the kernels are executed by multiple threads so the **order** of the output is not guaranteed to match between NEON and OpenCL.

**Comment by ganashree-rm** [comment]
Hi @mpekatsoula ,
Thank You for the update.
We have also observed that the mismatch in order is only seen if the input image format is unsigned 8 bit integer format. In case of a 16 bit signed integer format the order of the locations matches with NEON.

So is it fine in continuing with different order for GPU and NEON, even though overall contents are same and going ahead with our development? Could you please provide us your input.

**Comment by AnthonyARM** [comment]
Yes, that's correct: there is no guarantee on the ordering in which the values will be reported, however you should get the same values in both cases

**Comment by ganashree-rm** [comment]
@AnthonyARM 
Thank You for the info.
