### ISSUE TITLE
What's the difference between mobilenet and mobilenetV1

### ISSUE THREAD

**Issue by ysh329** [ARM-software/ComputeLibrary#313]
I ran `arm_compute_benchmark` and found there're two mobilenet as below:
```shell
Running [9] 'CL/SYSTEM_TEST/MobileNet@Batches=1'^[[m
Wall clock/Wall clock time:    MEDIAN=39194.0000 us, AVG=39194.0000 us, STDDEV=0.00 %, ^[[m
Running [10] 'CL/SYSTEM_TEST/MobileNet@Batches=4'^[[m
Wall clock/Wall clock time:    MEDIAN=150026.0000 us, AVG=150026.0000 us, STDDEV=0.00 %, ^[[m
Running [11] 'CL/SYSTEM_TEST/MobileNet@Batches=8'^[[m
Wall clock/Wall clock time:    MEDIAN=298261.0000 us, AVG=298261.0000 us, STDDEV=0.00 %, ^[[m
Running [12] 'CL/SYSTEM_TEST/MobileNetV1_224@Batches=1'^[[m
Wall clock/Wall clock time:    MEDIAN=176788.0000 us, AVG=176788.0000 us, STDDEV=0.00 %, ^[[m
Running [13] 'CL/SYSTEM_TEST/MobileNetV1_224@Batches=4'^[[m
Wall clock/Wall clock time:    MEDIAN=697498.0000 us, AVG=697498.0000 us, STDDEV=0.00 %, ^[[m
Running [14] 'CL/SYSTEM_TEST/MobileNetV1_224@Batches=8'^[[m
Wall clock/Wall clock time:    MEDIAN=1403295.0000 us, AVG=1403295.0000 us, STDDEV=0.00 %, ^[[m
Running [15] 'CL/SYSTEM_TEST/MobileNetV1_128@Batches=1'^[[m
Wall clock/Wall clock time:    MEDIAN=61432.0000 us, AVG=61432.0000 us, STDDEV=0.00 %, ^[[m
Running [16] 'CL/SYSTEM_TEST/MobileNetV1_128@Batches=4'^[[m
Wall clock/Wall clock time:    MEDIAN=238822.0000 us, AVG=238822.0000 us, STDDEV=0.00 %, ^[[m
Running [17] 'CL/SYSTEM_TEST/MobileNetV1_128@Batches=8'^[[m
Wall clock/Wall clock time:    MEDIAN=477354.0000 us, AVG=477354.0000 us, STDDEV=0.00 %, ^[[m
```

You can find the obvious performance difference between mobilenetV1 and mobilenet:
- mobileNet：0.0391 sec
- mobileNetV1：0.1767 sec

**Comment by GeorgeARM** [comment]
Hello @ysh329,
The one you care about is mobileNetV1, that is the configuration presented in the respective paper.
The other is a smaller example we used for validation purposes.
Hope this helps.

**Comment by ysh329** [comment]
@GeorgeARM Thanks, Geogre. I searched `mobileNetV1` and found tensorFlow support this:[models/mobilenet_v1.md at master · tensorflow/models](https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md). However, I read this link. it seems: in addition to the title of mobilenetv1, there is no mention of mobilenetV1 in the rest of the article([models/mobilenet_v1.md at master · tensorflow/models](https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md)). May you tell me this paper title name? 😆 Thanks in advance.

**Comment by ysh329** [comment]
```shell
$ ./graph_mobilenet 1                                                                                                                                                                            

./graph_mobilenet

Usage: ./graph_mobilenet 1 [path_to_data] [image] [labels]

No data folder provided: using random values

Time used: 0.220446
0Time used: 0.183237
1Time used: 0.000885963
2Time used: 0.176579
3Time used: 0.177057
4Time used: 0.000503063
5Time used: 0.177596
6Time used: 0.177103
7Time used: 0.0008111
8Time used: 0.176596
9Time used: 0.177247

Test passed
```

I have two questions:
1.  the 1st, 4th, 7th of 10 times are so fast, strange!
2.  MobileNet in `arm_compute_benchmark` is different from MobileNet in `./example/graph_mobilenet`?

The MobileNet execution time using `arm_compute_benchmark`:
- MobileNet@Batches=1 0.039194
- MobileNetV1_224@Batches=1 0.176788

**Comment by AnthonyARM** [comment]
This is a bug with the examples, could you please try to change [this line](https://github.com/ARM-software/ComputeLibrary/blob/v17.12/utils/GraphUtils.h#L258) to:
```cpp
return arm_compute::support::cpp14::make_unique<DummyAccessor>(0);
```
It should fix the issue. (This fix will be added to the next maintenance release)

**Comment by ysh329** [comment]
@AnthonyARM Thanks Anthony 😁 
```shell
$ ./graph_mobilenet 1

./graph_mobilenet

Usage: ./graph_mobilenet 1 [path_to_data] [image] [labels]

No data folder provided: using random values

Time used: 0.225077
0Time used: 0.190147
1Time used: 0.184613
2Time used: 0.186048
3Time used: 0.187841
4Time used: 0.18888
5Time used: 0.180582
6Time used: 0.179794
7Time used: 0.180263
8Time used: 0.188394
9Time used: 0.180103
ave:0.184666

Test passed
```

**Comment by ysh329** [comment]
I found some differences between `MobileNet`  and `MobileNetV1` in [this link](https://github.com/ysh329/diff/commit/add8164d4384e76908dac865628853416fbff97e). It seems that `MobileNetV1` is an experiment version of `MobileNet`?

**Comment by GeorgeARM** [comment]
Hello @ysh329,

As I mentioned above `MobileNetV1` is one of the MobileNet configurations from the respective paper. To be more specific its the biggest one `MobileNet_v1_1.0_224`. More details about the models can be found [here](https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md).
Now `MobileNet` is a cutdown experimental version we use for validation. `MobileNetV1` is the one you are interested in probably :)
Hope this helps.

**Comment by ysh329** [comment]
@GeorgeARM Thanks, George 🙇
