### ISSUE TITLE
How to change DataType in examples?

### ISSUE THREAD

**Issue by ysh329** [ARM-software/ComputeLibrary#316]
I want change FP32 to FP16 or INT8. How can I change. Thanks in advance. 🙇

**Comment by ysh329** [comment]
Change codes from
```cc
    graph << target_hint
          << Tensor(TensorInfo(TensorShape(224U, 224U, 3U, 1U), 1, DataType::F32),
           ...............
```
to
```cc
    graph << target_hint
          << Tensor(TensorInfo(TensorShape(224U, 224U, 3U, 1U), 1, DataType::F16),
           ...............
```

**Comment by iKess** [comment]
does this change work?
When running mobilenet with F16, it doesn't work but saying that there is no kernel supporting.

anyone can help me?

**Comment by gmiodice** [comment]
What command are you using to run the network?

**Comment by iKess** [comment]
Hi @gmiodice
I only changes F32 to F16 in the tensor defining code and run it by following the running example guideline.

(just ran the output executable with 0, 1, 2 option (CPU, GPU, GPU w/ tuner))

**Comment by iKess** [comment]
I attach the output.
![screenshot from 2018-06-22 18-51-17](https://user-images.githubusercontent.com/5152461/41770488-54b0cdc0-764d-11e8-9372-f2f705d4afe8.png)

**Comment by gmiodice** [comment]
Many thanks for attaching your output. In order to reproduce your issue could you also forward the following information?

arm_compute library version:
development platform:
OS of your development platform

Thanks,
Gian Marco

**Comment by iKess** [comment]
arm_compute library version: latest.
Development platform:
Chipset - Qualcomm MSM8996 Snapdragon 821
CPU - Quad-core (2x2.35 GHz Kryo & 2x1.6 GHz Kryo)
GPU - Adreno 530
OS of your development platform: Android 7.0 (Nougat)

thanks in advance :)

**Comment by gmiodice** [comment]
Many thanks @iKess for reporting these information. 

Unfortunately I do not have with me any Qualcomm platform to test on but I have tried on other platforms and it seems working properly. 
Looking at your error, HALF_MAX seems not recognized (HALF_MAX is part of the fp16 macros in OpenCL. https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/cl_khr_fp16.html). 

Is the fp16 acceleration supported by your platform?
To check this, you can edit helpers.h inside src/core/CL/cl_kernels/helpers.h. In particular you should remove lines 27 (https://github.com/ARM-software/ComputeLibrary/blob/master/src/core/CL/cl_kernels/helpers.h#L27) and 29 (https://github.com/ARM-software/ComputeLibrary/blob/master/src/core/CL/cl_kernels/helpers.h#L29).

Thanks
