### ISSUE TITLE
SqueezeNet in examples is 1.0 or 1.1?

### ISSUE THREAD

**Issue by ysh329** [ARM-software/ComputeLibrary#317]
Thanks in advance! 🙇

**Comment by ysh329** [comment]
fixed. 1.0

**Comment by pcub** [comment]
@ysh329  did graph_squeezenet example work?
Mine do not work. I followed similar procedure that grapch_alexnet can run.
What I did is: first converted sqeezenet_v1.0 caffe model to numpy array using caffe_data_extractor.py and run following:
./examples/graph_squeezenet 0 /home/*/cnn_test_data/compute_library_alexnet /home/*/cnn_test_data/go_kart.ppm /home/*/cnn_test_data/labels.txt

result is:
./examples/graph_squeezenet
!!!!!!!!!!!!!!!!!!!!!!!!!!!
ERROR io error: failed reading file No such file or directory
!!!!!!!!!!!!!!!!!!!!!!!!!!!

Test FAILED
**Note** do not confurse with /home/* 

any suggestion?
