### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by cwp007** [ARM-software/ComputeLibrary#318]
ubuntu14.04 64bit
after install the following tool:
gcc-linaro-arm-linux-gnueabihf-4.9-2014.07_linux
gcc-linaro-4.9-2016.02-x86_64_aarch64-linux-gnu
gcc-linaro-6.3.1-2017.02-i686_aarch64-linux-gnu
and install apt-get install g++-arm-linux-gnueabihf
then i try: scons Werror=1 -j8 debug=0 neon=1 opencl=0 os=linux arch=armv7a build=cross_compile
![bbda2ef4-2e9b-9edb-80a3-aa4a4ff127b2](https://user-images.githubusercontent.com/34837210/34340732-7067ca20-e9c4-11e7-97c0-9f1532ad9a65.png)
but i try: scons Werror=1 -j8 debug=0 asserts=1 neon=0 opencl=1 embed_kernels=1 os=linux arch=arm64-v8a
then succeed.
I don't know how to solve it.
Any one can help me?

**Comment by AnthonyARM** [comment]
Are you sure the right compiler gets picked up ?
What do you get when you run `aarch64-linux-gnu-g++ --version` ?

Here is what you should get:
```
aarch64-linux-gnu-g++ --version
aarch64-linux-gnu-g++ (Linaro GCC 4.9-2016.02) 4.9.4 20151028 (prerelease)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by cwp007** [comment]
yes, it is same to yours when i run aarch64-linux-gnu-g++ --version, and it is succeed to build the lib for arm64-v8a, i got failed when build the lib for armv7a, the error is the picture above. there may be some version problem about the compiler. i add some blank in half.hpp ，finally succeed.

**Comment by AnthonyARM** [comment]
Sorry, for 32bit when I run `arm-linux-gnueabihf-g++ --version` I get:
```
arm-linux-gnueabihf-g++ (crosstool-NG linaro-1.13.1-4.9-2014.07 - Linaro GCC 4.9-2014.07) 4.9.1 20140710 (prerelease)
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by cwp007** [comment]
thank you, it is true some version problem about the compiler. my compiler version is 4.8.4, thank you again

**Comment by AnthonyARM** [comment]
No update in a while: assuming this has been fixed.
