### ISSUE TITLE
Query on support for color spaces

### ISSUE THREAD

**Issue by rohit-unnimadhavan** [ARM-software/ComputeLibrary#319]
Hi,

What color spaces are supported by Compute Library classes NEColorConvert and CLColorConvert? Is there a way to configure different color spaces like BT.709, BT.601-525, BT.601-625 etc?

Thanks,
Rohit

**Comment by AnthonyARM** [comment]
Hi Rohit,
It is not configurable at the moment, we only support BT.709

**Comment by rohit-unnimadhavan** [comment]
Thank you!
