### ISSUE TITLE
Build failure on ppc64le

### ISSUE THREAD

**Issue by afaerber** [ARM-software/ComputeLibrary#32]
Reusing `arch=x86`, it builds okay for openSUSE Tumbleweed on ppc64 and s390x, but it fails for ppc64le, due to apparent redefinition of the `bool` type via `altivec.h` from `include/CL/cl_platform.h`.

[GCC bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58241)
[Khronos bug](https://www.khronos.org/bugzilla/show_bug.cgi?id=1449)
[Mesa bug](https://bugs.freedesktop.org/show_bug.cgi?id=68504)

The solution appears to be using `-std=gnu++11` instead of `-std=c++11` for this architecture. Relates to issue #19.

**Comment by AnthonyARM** [comment]
We've tried internally to replace `-std=c++11` by `-std=gnu++11` and it doesn't seem to create any problem, so we're happy to switch for all targets.
Would that be a suitable fix ? Or are we missing some potential issues here ?

**Comment by AnthonyARM** [comment]
We're now using gnu++11, re-open if it still doesn't build
