### ISSUE TITLE
why cl api test  hang？

### ISSUE THREAD

**Issue by wangshankun** [ARM-software/ComputeLibrary#320]
On Rockchip **RK3399** (A72 x 2 , A53 x 4, **Mali-T860**),
 I test cl_sgemm and arm_compute_benchmark

my compile config:
**scons -j6 arch=arm64-v8a build=native os=linux opencl=1 gles_compute=1 embed_kernels=1**

test log:
=================================================
**./build/examples/cl_sgemm**

Usage: 1) ./build/cl_sgemm input_matrix_1.npy input_matrix_2.npy [input_matrix_3.npy] [alpha = 1] [beta = 0]
       2) ./build/cl_sgemm M N K [alpha = 1.0f] [beta = 0.0f]

Too few or no input_matrices provided. Using M=7, N=3, K=5, alpha=1.0f and beta=0.0f

^C
=================================================
$ **./build/tests/arm_compute_benchmark** 
Seed = 2163321844
Iterations = 1
Threads = 1
Dataset mode = PRECOMMIT
Running [0] 'CL/SYSTEM_TEST/AlexNet@DataType=F16:Batches=1'

**Comment by AnthonyARM** [comment]
We've started seeing some hangs internally too, and we'll release a fix as soon as we know what's causing them. In the meantime I would recommend not enabling both `gles_compute=1` and `opencl=1` at the same time.

**Comment by wangshankun** [comment]
Tks, i've tested  at version v17.04 , v17.09, v17.12 , disable gles_compute, this issue still exist.
for me, gles_compute may not have influence.

**Comment by wangshankun** [comment]
Another issue, if **disable embed_kernels** and **enable opencl**, test ./build/cl_convolution will occur
_Kernel file ./cl_kernels/convolution3x3.cl does not exist. No such file or directory_
I need to export some path ?

**Comment by wangshankun** [comment]
i replace the opencl and displayer， this issue is not exist

**Comment by AnthonyARM** [comment]
You need to copy the folder `src/core/CL/cl_kernels` to your runtime directory.

Could you please explain what you did to fix it, I don't understand what you mean by displayer ?

**Comment by wangshankun** [comment]
I think  system libOpenCL.so can‘t work，look like cl_sgemm hang;
May my embedded  card no displayer  env  led  to  libOpenCL.so  abnormal

**Comment by AnthonyARM** [comment]
Seems to be a platform issue, no update in a while: closing
