### ISSUE TITLE
Handling of CLTensor buffer itself

### ISSUE THREAD

**Issue by zesiha** [ARM-software/ComputeLibrary#326]
Hi!

Nowadays, I am implementing an algorithm using this library.
Most of time consumption occurs in a process of memory copy in self test.
However the target algorithm requires a lot of variables to calculate mathematical formulas, and the variables use many times because the algorithm works iteratively.
In order to reduce redundant time consumption, I want to minimize the use of memory copy.

1. Is there any way to handle CLTensor buffer data itself without copy? (buffer unit may be 1 bytes, but I have to use F32.)
2. Is there any way to cast CLTensor buffer address to float pointer? (reinterpret_cast didn't work in my case. Platform : android)

Thanks.

**Comment by zesiha** [comment]
Sorry. I solved question 2.

I didn't use .map() and .unmap(). 
If those function are not call, then can not get the address of buffer.
reinterpret_cast<> is properly work.

Thanks.

**Comment by AnthonyARM** [comment]
I'm not sure I understand what you mean by "without copy" ?
Once the buffer is mapped you can access the data directly from the `buffer()` pointer, you don't need to copy the data.

**Comment by GeorgeARM** [comment]
Hello @zesiha,
Quick comment raise separate issue for different questions as content with title issue is not aligned.
1. Yes you can do tensor * scalar either using Linear activation function or using pixelwise multiplication.
2. CLGEMM is already optimized thus I would go using that directly. If you need to do a classical transpose we have a CLTranspose function that does a blocked transposition.

Closing this issue. Reopen if needed.
