### ISSUE TITLE
not found severals includes

### ISSUE THREAD

**Issue by tzhang2014** [ARM-software/ComputeLibrary#327]
Hi , when i make caffeOnACL will meet not found the follow includes: arm_compute/core/NEON/kernels/NEDepthConcatenateKernel.h  arm_compute/runtime/NEON/functions/NEDepthConcatenate.h arm_compute/core/CL/kernels/CLDepthConcatenateKernel.h arm_compute/runtime/CL/functions/CLDepthConcatenate.h

how can i solve it? THX

**Comment by AnthonyARM** [comment]
It's a problem with CaffeOnACL not with the Compute Library. It's probably just because it hasn't been updated yet to work with the latest version of the Compute Library.

**Comment by tzhang2014** [comment]
I modified some codes to make and test it  succeesully, I configure it step by step ,but meet a ERROR about opencL, My platform is TX2 , it is mean  I configure it success?

**Comment by psyhtest** [comment]
@tzhang2014 TX2 doesn's support OpenCL, as far as I know.

**Comment by tzhang2014** [comment]
@psyhtest  thank you , I can run the examples.

**Comment by GeorgeARM** [comment]
Closing issue as seems to have been resolved! Reopen if needed!

**Comment by psyhtest** [comment]
@tzhang2014 Could you please share your modifications here?
