### ISSUE TITLE
CLGEMM performance

### ISSUE THREAD

**Issue by zesiha** [ARM-software/ComputeLibrary#329]
Hi!

I have a question as below.

Maybe, CLGEMM does not seems to support to 'transpose' option.
Considering CLGEMM.cpp, x dimension of matrix a and y dimension of matrix b should be same.
Thus, I had to do prepare both target matrix (m x n) and transpose matrix of target (n x m).
The result of below two cases showed the different run time although they have same time complexity.
(1) (n x m) x (m x 1) = (n x 1), m < n
(2) (m x n) x (n x 1) = (m x 1), m < n

Time consumption of (2) was larger than it of (1).

Is there an efficient tip for transpose matrix vector multiplication (e.g. A' b)?

Thanks.

**Comment by gmiodice** [comment]
Hi,

currently CLGEMM does not support the option transpose for the input matrix A. To overcome this problem I'd suggest to use CLTranspose function before calling CLGEMM. If the values in the input matrix A are constant, I'd suggest to run CLTranspose only once:

i.e.

CLTranspose transpose;
CLGEMM gemm;

// configure
transpose.configure();
gemm.configure();

// Transpose only once
transpose.run();

for()
...
gemm.run();

Hope this can help.

**Comment by AnthonyARM** [comment]
No update in a month, closing ticket.
