### ISSUE TITLE
Obtaining libOpenCL.so

### ISSUE THREAD

**Issue by kindloaf** [ARM-software/ComputeLibrary#33]
Hi,
I'm trying to use the library on mali GPU. I'm wondering what's the best way to obtaining a real implementation of libOpenCL.so that is compatible to the openCL header files used in this library? I didn't find libOpenCL.so in /system on the device.

**Comment by llhe** [comment]
@kindloaf If you are using Android, you can use [OpenCL-Z](https://play.google.com/store/apps/details?id=com.robertwgh.opencl_z_android&hl=en) or [OpenCL-X benchmark](https://play.google.com/store/apps/details?id=com.maxtrium.opencldevicetest&hl=en) to detect OpenCL information.

**Comment by kindloaf** [comment]
@llhe Thanks! I will give it a try.

**Comment by kindloaf** [comment]
I'm also trying to compile the library with mali openCL SDK. Many people refer to the URL of
https://developer.arm.com/products/software/mali-sdks/opencl
But it doesn't work for me - got a 404. Any advice?

**Comment by kindloaf** [comment]
@llhe I used OpenCL-Z and found the path to the library. Thanks!

**Comment by AnthonyARM** [comment]
The OpenCL SDK has been discontinued (It was no longer maintained and had become completely out of date).
You have a bunch of tutorials available on the [ARM developer website](https://developer.arm.com/graphics/tutorials/opencl-tutorials)

**Comment by kindloaf** [comment]
Thanks @AnthonyARM . I will check it out.
