### ISSUE TITLE
Compile error:  ignoring attributes on template argument 

### ISSUE THREAD

**Issue by EllaFeng** [ARM-software/ComputeLibrary#330]
I try to compile this library with scons command,

>     scons Werror=1 -j8 debug=0 asserts=1 neon=0 opencl=1 embed_kernels=1 os=linux arch=arm64-v8a build=cross_compile

using aarch64-poky-linux-g++ --version

> aarch64-poky-linux-g++ (GCC) 6.2.0
> Copyright (C) 2016 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

But I got the following error like in OpenCL.h, not sure if this is related to my compiler.
In file included from ./arm_compute/core/CL/CLHelpers.h:27:0,
                 from src/core/CL/CLHelpers.cpp:24:
./arm_compute/core/CL/OpenCL.h:60:38: error: ignoring attributes on template argument ‘cl_int(cl_program, cl_uint, _cl_device_id* const*, const char*, void (*)(cl_program, void*), void*) {aka int(_cl_program*, unsigned int, _cl_device_id* const*, const char*, void (*)(_cl_program*, void*), void*)}’ [-Werror=ignored-attributes]
     std::function<decltype(func_name)> func_name##_ptr = nullptr
                                      ^
./arm_compute/core/CL/OpenCL.h:62:5: note: in expansion of macro ‘DECLARE_FUNCTION_PTR’
     DECLARE_FUNCTION_PTR(clBuildProgram);
     ^~~~~~~~~~~~~~~~~~~~
./arm_compute/core/CL/OpenCL.h:60:38: error: ignoring attributes on template argument ‘cl_int(cl_command_queue, cl_kernel, cl_uint, const size_t*, const size_t*, const size_t*, cl_uint, _cl_event* const*, _cl_event**) {aka int(_cl_command_queue*, _cl_kernel*, unsigned int, const long unsigned int*, const long unsigned int*, const long unsigned int*, unsigned int, _cl_event* const*, _cl_event**)}’ [-Werror=ignored-attributes]
     std::function<decltype(func_name)> func_name##_ptr = nullptr
                                      ^
./arm_compute/core/CL/OpenCL.h:63:5: note: in expansion of macro ‘DECLARE_FUNCTION_PTR’
     DECLARE_FUNCTION_PTR(clEnqueueNDRangeKernel);
     ^~~~~~~~~~~~~~~~~~~~
./arm_compute/core/CL/OpenCL.h:60:38: error: ignoring attributes on template argument ‘cl_int(cl_kernel, cl_uint, size_t, const void*) {aka int(_cl_kernel*, unsigned int, long unsigned int, const void*)}’ [-Werror=ignored-attributes]
     std::function<decltype(func_name)> func_name##_ptr = nullptr
                                      ^
./arm_compute/core/CL/OpenCL.h:64:5: note: in expansion of macro ‘DECLARE_FUNCTION_PTR’

**Comment by EllaFeng** [comment]
I changed a cross-compiler to 5.4.0, and it worked.
Will this marked as known issue?

**Comment by psyhtest** [comment]
I see these warnings all the time with GCC 6.3 and 7.2 (which is why I don’t build with `-Werror`). I tend to trust these newer GCCs to be right about suspecting that there is something wrong with the code. But what is it?

**Comment by AnthonyARM** [comment]
I'm happy for us to fix this warning if someone can explain to me what it's about :)

I did a quick research and didn't find much explanations out there about this warning.

**Comment by psyhtest** [comment]
Ha-ha, me too! (And I am a compiler guy :))

**Comment by EllaFeng** [comment]
greatly appreciate your attention.  Not sure whether this is bugs in GCC.

**Comment by GeorgeARM** [comment]
Does it fail when you build with `debug=1` ?

**Comment by EllaFeng** [comment]
Yes, also failed

**Comment by GeorgeARM** [comment]
I actually just tried linaro toolchains 6.2, 6.3 and 7.2 and didn't get any warnings.
Thus I checked our project's [Sconstruct](https://github.com/ARM-software/ComputeLibrary/blob/master/SConstruct#L172) and saw:
```
        if version_at_least(compiler_ver, '6.1'):
            env.Append(CXXFLAGS = ['-Wno-ignored-attributes'])
```
So we disable these.
Can you check if it goes to this path and if not why?

**Comment by GeorgeARM** [comment]
I think that these warnings have to do with the attributes on the CL API entrypoints. Because template parameters do not retain the parameter's attributes as they are not part of the name mangling.
Thus we cannot do much for this, just disable the warning. Can't think of something else.

**Comment by EllaFeng** [comment]
Thanks very much. I will disable these warnings as your suggestion.
