### ISSUE TITLE
NEDeconvolutionLayer shifted output

### ISSUE THREAD

**Issue by wr0112358** [ARM-software/ComputeLibrary#331]
I am evaluating NEDeconvolutionLayer for interoperability with nn.ConvTranspose2d function from pytorch. The outputs look very similar, but shifted by 2 rows up and 2 columns right regardless of upscale factor and input sizes.
Is this expected behaviour?

Please find attached the results stored in output Tensor and the expected output.
If necessary I can provide my test code.

output Tensor contains:
0 0 78 78 156 156 234 156 234 156 156
0 0 78 78 156 156 234 156 234 156 156
0 0 117 117 234 234 351 234 351 234 234
0 0 78 78 156 156 234 156 234 156 156
0 0 117 117 234 234 351 234 351 234 234
0 0 78 78 156 156 234 156 234 156 156
0 0 78 78 156 156 234 156 234 156 156
0 0 39 39 78 78 117 78 117 78 78
0 0 39 39 78 78 117 78 117 78 78
0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0

0 0 78 78 156 156 234 156 234 156 156
0 0 78 78 156 156 234 156 234 156 156
0 0 117 117 234 234 351 234 351 234 234
0 0 78 78 156 156 234 156 234 156 156
0 0 117 117 234 234 351 234 351 234 234
0 0 78 78 156 156 234 156 234 156 156
0 0 78 78 156 156 234 156 234 156 156
0 0 39 39 78 78 117 78 117 78 78
0 0 39 39 78 78 117 78 117 78 78
0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0

0 0 78 78 156 156 234 156 234 156 156
0 0 78 78 156 156 234 156 234 156 156
0 0 117 117 234 234 351 234 351 234 234
0 0 78 78 156 156 234 156 234 156 156
0 0 117 117 234 234 351 234 351 234 234
0 0 78 78 156 156 234 156 234 156 156
0 0 78 78 156 156 234 156 234 156 156
0 0 39 39 78 78 117 78 117 78 78
0 0 39 39 78 78 117 78 117 78 78
0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0

expected content:
(0 ,0 ,.,.) = 
   39   39   78   78  117   78  117   78   78   39   39
   39   39   78   78  117   78  117   78   78   39   39
   78   78  156  156  234  156  234  156  156   78   78
   78   78  156  156  234  156  234  156  156   78   78
  117  117  234  234  351  234  351  234  234  117  117
   78   78  156  156  234  156  234  156  156   78   78
  117  117  234  234  351  234  351  234  234  117  117
   78   78  156  156  234  156  234  156  156   78   78
   78   78  156  156  234  156  234  156  156   78   78
   39   39   78   78  117   78  117   78   78   39   39
   39   39   78   78  117   78  117   78   78   39   39

(0 ,1 ,.,.) = 
   39   39   78   78  117   78  117   78   78   39   39
   39   39   78   78  117   78  117   78   78   39   39
   78   78  156  156  234  156  234  156  156   78   78
   78   78  156  156  234  156  234  156  156   78   78
  117  117  234  234  351  234  351  234  234  117  117
   78   78  156  156  234  156  234  156  156   78   78
  117  117  234  234  351  234  351  234  234  117  117
   78   78  156  156  234  156  234  156  156   78   78
   78   78  156  156  234  156  234  156  156   78   78
   39   39   78   78  117   78  117   78   78   39   39
   39   39   78   78  117   78  117   78   78   39   39

(0 ,2 ,.,.) = 
   39   39   78   78  117   78  117   78   78   39   39
   39   39   78   78  117   78  117   78   78   39   39
   78   78  156  156  234  156  234  156  156   78   78
   78   78  156  156  234  156  234  156  156   78   78
  117  117  234  234  351  234  351  234  234  117  117
   78   78  156  156  234  156  234  156  156   78   78
  117  117  234  234  351  234  351  234  234  117  117
   78   78  156  156  234  156  234  156  156   78   78
   78   78  156  156  234  156  234  156  156   78   78
   39   39   78   78  117   78  117   78   78   39   39
   39   39   78   78  117   78  117   78   78   39   39
[torch.FloatTensor of size 1x3x11x11]

**Comment by mpekatsoula** [comment]
Hi @wr0112358 
We are aware of some problems with Deconvolution layer and they are going to be fixed in the next release.

**Comment by wr0112358** [comment]
Thank you for the quick answer. Will there also be a version using non-direct convolution to enable larger kernel sizes?

I am investigating use of ACL for one of the semantic segmentation networks and the Deconvolution layer is an important building block in most of them.

**Comment by AnthonyARM** [comment]
Fixed in 18.01, reopen if you're still seeing the issue.
