### ISSUE TITLE
Compile question!

### ISSUE THREAD

**Issue by zhangguotai** [ARM-software/ComputeLibrary#333]
By this two orders: scons Werror=1 -j8 debug=0 asserts=1 neon=1 opencl=0 embed_kernels=0 os=linux arch=armv7a and make,I have compiled ComputeLibrary and MXnetonACL successfully!
But compiling example ,I found bug as follow:
/mnt/hgfs/TCPS_PeopleCount/MXNetOnACL/lib/libmxnet.so: undefined reference to `arm_compute::CLKernelLibrary::get()'
/mnt/hgfs/TCPS_PeopleCount/MXNetOnACL/lib/libmxnet.so: undefined reference to `arm_compute::CLTensor::do_map(cl::CommandQueue&, bool)'
/mnt/hgfs/TCPS_PeopleCount/MXNetOnACL/lib/libmxnet.so: undefined reference to `arm_compute::CLActivationLayer::configure(arm_compute::ICLTensor*, arm_compute::ICLTensor*, arm_compute::ActivationLayerInfo)'
/mnt/hgfs/TCPS_PeopleCount/MXNetOnACL/lib/libmxnet.so: undefined reference to `arm_compute::CLScheduler::get()'
/mnt/hgfs/TCPS_PeopleCount/MXNetOnACL/lib/libmxnet.so: undefined reference to `arm_compute::CLBatchNormalizationLayer::CLBatchNormalizationLayer()'
I should how to solve??????

**Comment by GeorgeARM** [comment]
You don't compile for OpenCL. You should have `opencl=1 embed_kernels=1`

**Comment by zhangguotai** [comment]
But I don't want to compile opencl which is supported in my device

**Comment by zhangguotai** [comment]
But I don't want to compile opencl which is supported in my device

**Comment by AnthonyARM** [comment]
Don't use "CLBatchNormalizationLayer" in your libmxnet then.

**Comment by GeorgeARM** [comment]
Closing issue. Reopen if needed. OpenCL functions are used without having compiled with OpenCL support. For the given build command:
```scons Werror=1 -j8 debug=0 asserts=1 neon=1 opencl=0 embed_kernels=0 os=linux arch=armv7a```
only NEON functions can be used.
