### ISSUE TITLE
Will this library support other GPU devices in the future? 

### ISSUE THREAD

**Issue by EllaFeng** [ARM-software/ComputeLibrary#334]
I think for now, this library only supports Mali GPU
Do you guys have plan to support other kind of devices of other vendors?

**Comment by AnthonyARM** [comment]
Currently this library is maintained by Arm alone so we focus on Arm accelerators ( CPU, GPU, etc.), but this is an Open Source project so other people can easily contribute to it support for other devices.

**Comment by GeorgeARM** [comment]
Closing issue. Reopen if needed.
