### ISSUE TITLE
SGEMM kernel performance

### ISSUE THREAD

**Issue by frank2679** [ARM-software/ComputeLibrary#336]
I have the ACL_17.12. I read two versions of sgemm kernel in directory : "arm_compute/core/NEON/kernels/assembly/kernels/a64_sgemm_12x8/". 
One is "generic.hpp"; the other is "a53.hpp". Since I have an ARM core with two A53 and two A73 cores, I tested the two .hpp on A53, and found that a53.hpp is 30%(a53.hpp: 5.4 GFLOPS, generic.hpp: 4.1 GFLOPS) faster than generic.hpp. I 've read the two source code and found the difference between the two, but not understand why the difference can make such performance improvment for a53.hpp. 
Any answers or suggestions on this question? Thanks a lot.

**Comment by AnthonyARM** [comment]
You can have a look at [this paper](http://www.csc.lsu.edu/~whaley/theses/hasan_phd.pdf) section 5.1.2 for more details

**Comment by frank2679** [comment]
@AnthonyARM Thanks a lot. This paper helps resolve my problem.
