### ISSUE TITLE
 Error in running graph_alexnet on 1.2 OpenCL

### ISSUE THREAD

**Issue by szihs** [ARM-software/ComputeLibrary#337]
Hello ARM,

I am trying to evaulate ACL library.
I have 
  Device Version                                  OpenCL 1.2 
  Device OpenCL C Version                         OpenCL C 1.2 
  Device Type                                     GPU
  Device Profile                                  EMBEDDED_PROFILE

To run CL samples, I have changed 
 concat_str += " -cl-std=CL1.2 "; as device doesn't have non_uniform_workgroup_support or OpenCL2.0.
The ./cl_convolution, ./cl_events, ./cl_sgemm and other samples work welll.

However on running ./graph_alexnet and other samples at runtime I am getting below error:

BuildGroup_40:524:44: error: automatic variable qualified with an address space
    __constant VEC_DATA_TYPE(DATA_TYPE, 4) type_min4 = (VEC_DATA_TYPE(DATA_TYPE, 4))(MINVAL);
                                           ^

terminate called after throwing an instance of 'cl::Error'
  what():  clCreateKernel

Please let me know if there is a way to enable support for devices with OpenCL1.2 profile supported.

Regards,

**Comment by AnthonyARM** [comment]
Hi,
No it's not possible you need either the arm_non_uniform_workgroup_size extension or CL 2.0
As a hack you can try passing always NULL to clEnqueueNDRangeKernel for the local workgroup size and it might work for most cases however this is a hack so if it crashes with that configuration there isn't much we can do about it.

**Comment by szihs** [comment]
Hi Anthony,
Thanks for your reply. I changed to NULL as hack
It works however alexnet prediction of wrong. (Compared to neon)

Regards,
Harsh

**Comment by GeorgeARM** [comment]
Closing issue. Reopen if needed. Mismatches are due to unsupported non uniform workgroup size extension.

**Comment by ncbkhoi** [comment]
Hello ARM,
I have the same issue as Anthony. However, even if I added NULL to clEnqueueNDRangeKernel, graph_alexnet still throws the error, please see below:
BuildGroup_31:671:44: error: automatic variable qualified with an address space
__constant VEC_DATA_TYPE(DATA_TYPE, 4) type_min4 = (VEC_DATA_TYPE(DATA_TYPE, 4))(MINVAL);
^

terminate called after throwing an instance of 'cl::Error'
what(): clCreateKernel
I added to OpenCL.cpp. line 332.
Do you have any advices for me?

Best Regards,
Khoi
