### ISSUE TITLE
internal compiler error

### ISSUE THREAD

**Issue by zhaofenqiang** [ARM-software/ComputeLibrary#338]
Hi,
I have compiled the ComputeLibrary at Firefly RK3399 with command:
`scons Werror=1 -j4 debug=0 asserts=1 neon=1 opencl=1 embed_kernels=1 os=linux arch=arm64-v8a validation_tests=1 benchmark_tests=1`

and then I always get the error like this after about 30mins:

> aarch64-linux-gnu-g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
scons: *** [build/src/graph/operations/CLSimpleOperations.o] Error 4
scons: building terminated because of errors.

Anyone konw why? Thank you in advance.

**Comment by AnthonyARM** [comment]
Maybe the board runs out of memory try without the `-j4`

**Comment by zhaofenqiang** [comment]
Wow, that works, thank you very much~
