### ISSUE TITLE
converting tensorflow object detection models

### ISSUE THREAD

**Issue by triiipleee** [ARM-software/ComputeLibrary#339]
I want to convert my object detectors (e.g. MobileNet-SSD) to ComputeLibrary. Can someone provide an example for loading all extracted tensorflow/numpy layers? The example [graph_mobilenet.cpp](https://github.com/ARM-software/ComputeLibrary/blob/master/examples/graph_mobilenet.cpp) seems to show the classification structure, however, can it be extended for box prediction?

**Comment by AnthonyARM** [comment]
I'm not sure what you're asking for ? You can already have a look at the graph_* examples to see how to load npy files for the weights.
We haven't tried this particular network: could you please tell us what feature(s) you're missing ?
