### ISSUE TITLE
ndk-build compile error?

### ISSUE THREAD

**Issue by Igamegum** [ARM-software/ComputeLibrary#34]
I have an error when I compile example with .so,The error message show as below

In file included from jni/test.cpp:25:
In file included from jni/arm_compute/core/Types.h:27:
In file included from jni/arm_compute/core/Coordinates.h:27:
In file included from jni/arm_compute/core/Dimensions.h:27:
jni/arm_compute/core/Error.h:123:2: error: expected expression
[[noreturn]] void error(const char *function, const char *file, const in...
 ^
jni/arm_compute/core/Error.h:123:14: error: expected unqualified-id
[[noreturn]] void error(const char *function, const char *file, const in...
             ^
In file included from jni/test.cpp:25:
In file included from jni/arm_compute/core/Types.h:27:
In file included from jni/arm_compute/core/Coordinates.h:27:
jni/arm_compute/core/Dimensions.h:29:10: fatal error: 'algorithm' file not found
#include <algorithm>
         ^
3 errors generated.

**Comment by mpflanzer** [comment]
That looks like your compiler doesn't support C++11 or at least doesn't compile for it. Which version of the NDK are you using? And what is your build command?

**Comment by AnthonyARM** [comment]
You need to use the standalone toolchains not ndk-build.
Follow the instructions in the [documentation](https://arm-software.github.io/ComputeLibrary/v17.03.1/index.xhtml#S3_3_android) to generate the toolchain and build the library.
Alternatively you can download Android binaries from the [release page](https://github.com/ARM-software/ComputeLibrary/releases)

**Comment by AnthonyARM** [comment]
Re-open if you've got issues compiling using the standalone toolchain
