### ISSUE TITLE
Cannot complie CaffeOnACL missing NEDepthConcatenateKernel.h

### ISSUE THREAD

**Issue by panzhigang0703** [ARM-software/ComputeLibrary#341]
I have followed the instruction. also the pdf to compile CaffeOnACL.
Hpwever, it keeps failing during "sudo make all" steps.
fatal error:arm_compute/core/NEON/kernels/NEDepthConcatenateKernel.h: No such file or directory
complilation terminated.
Makefile:631

**Comment by psyhtest** [comment]
The CaffeOnACL haven’t been updated for a while. I have encountered the same problem with more recent versions of the Compute Library, but I believe it works with v17.09.
