### ISSUE TITLE
CL2.hpp - error: ‘CL_DEVICE_QUEUE_ON_HOST_PROPERTIES’ was not declared in this scope

### ISSUE THREAD

**Issue by soulslicer** [ARM-software/ComputeLibrary#344]
Hello all,

I have the following error when I attempt to compile my code on my CUDA 8.0 Machine. But on my CUDA 9.0 machine it works fine. Why is this the case? I have set the version flag to 200

**Comment by AnthonyARM** [comment]
What flag are you talking about ? You shouldn't need to change anything

**Comment by soulslicer** [comment]
```
> #define CL_HPP_ENABLE_EXCEPTIONS
>     #define CL_HPP_MINIMUM_OPENCL_VERSION 120 // Need to set to 120 on CUDA 8
>     #define CL_HPP_TARGET_OPENCL_VERSION 120 // Need to set to 120 on CUDA 8
>     #include <CL/cl2.hpp>
```

**Comment by AnthonyARM** [comment]
By default it's on `110` not `120` or `200`, it should work with `110` on all devices (We don't use any 1.2 or 2.0 entry points).

Anyway if it doesn't build for 1.2 or 2.0 then it looks like an issue with the Khronos header not the library: https://github.com/KhronosGroup/OpenCL-CLHPP

**Comment by soulslicer** [comment]
Yes okay, so its an issue with the Chronos header. How can I fix it?

**Comment by soulslicer** [comment]
Yes okay, so its an issue with the Chronos header. How can I fix it?

**Comment by soulslicer** [comment]
I set those defines to 110 and I still get the same ; error. Only if I leave it at 200 does it work

**Comment by GeorgeARM** [comment]
Closing. Reopen if needed.

**Comment by guodajun** [comment]
在代码中增加如下:
#define CL_HPP_ENABLE_EXCEPTIONS
#define CL_HPP_MINIMUM_OPENCL_VERSION 120 // Need to set to 120 on CUDA 8
#define CL_HPP_TARGET_OPENCL_VERSION 120 // Need to set to 120 on CUDA 8
 #include <CL/cl2.hpp>

并且在其它地方不要重复包含cl2.hpp头文件.
