### ISSUE TITLE
Query on freeing Pyramid structure

### ISSUE THREAD

**Issue by rohit-unnimadhavan** [ARM-software/ComputeLibrary#347]
Hi,

I could see that there is a free method in Tensors for freeing up the memory allocated to them. I couldn't find a similar function for Pyramid and CLPyramid. How are the allocated pyramids freed?

Thanks,
Rohit

**Comment by GeorgeARM** [comment]
Hello @rohit-unnimadhavan,

The pyramids are freed at object destruction. So when the `Pyramid` object goes out of scope.

**Comment by GeorgeARM** [comment]
Closing issue. Reopen if needed.
