### ISSUE TITLE
Tensor data alignment - Query

### ISSUE THREAD

**Issue by rayjs** [ARM-software/ComputeLibrary#350]
From the documentation it is suggested that data should be aligned.
But I am looking under TensorAllocator.cpp but could not find the alignment check. I understand the raw memory (Memory.h) is held as a uint8 buffer and using the dataformat ,tensorinfo, and the padding the correct indices (windows) are calculated. 

But I dont see where the alignment check is being performed. Can you please point me in the right direction and correct me if I am wrong?

Thank you

Documentation:

```Align data on 128-bit or 16-byte boundaries

Align data on 128-bit or 16-byte boundaries. This can improve the speed of loading and saving data. 
If you can, align data on 64-byte boundaries. This ensures data fits evenly into the cache on Mali GPUs.
```

**Comment by morgolock** [comment]
Hi @rayjs 

The library does not impose alignment restrictions, there is no code performing the checks you mention.

The information in the documentation is merely an advice on good practices.
