### ISSUE TITLE
NESobel3x3 doesn't have a run() function

### ISSUE THREAD

**Issue by transldw** [ARM-software/ComputeLibrary#351]
Hi All,

I'm using the latest release v18.01. I noticed that class NESobel3x3 doesn't have a run() function as NESobel5x5 does. 
So just wondering how to use NESobel3x3 in the code.

Thanks!

**Comment by GeorgeARM** [comment]
Hello @transldw ,

They inherit from different interfaces that's why. `NESobel3x3` inherits from `INESimpleFunction` which already overloads the run methods. So you can use it just like the same way you use any other function.

**Comment by transldw** [comment]
OK, got it!

Thanks, George.
