### ISSUE TITLE
HOG features and SVM prediction

### ISSUE THREAD

**Issue by triiipleee** [ARM-software/ComputeLibrary#352]
In the documentation, we can find functions like NEHOGDescriptor and NEHOGDetector (or the OpenCL equivalent functions) to compute HOG features. Furthermore, the NEHOGMultiDetection class allows to detect objects at multiple scales. Are there any examples that show their usage, especially in combination with SVMs? How to build a simple object detector? Any discussion would be helpful, thanks!

**Comment by steniu01** [comment]
Hi, you can use NEHOGDescritpor to extract the hog features and then use NEHOGDetector for single template detection, NEHOGMUltiDetection is used when you have multiple templates (it will do non max suppression at the end). 
ACL HOG don't support multiple scale levels but if you can easily extend it if you want.

Once you have gotten the templates from your svm trainer, then you can load the templates into the NEHOG object and then pass to the NEDetector. 

Here is an example how I load templates trained with dlib svm into the CLHOG. In the below example I used fhog features but it should be just similar if you use the traditional Dalal and Triggs HoG.  

template<typename fhog_filter_type>
void load_hog_weights_from_dlib(fhog_filter_type& filters, arm_compute::ICLHOG* hog)
{
    using namespace arm_compute;
    // Map buffer to access in host
    hog->map(arm_compute::CLScheduler::get().queue(), true/* blocking */);

    // More efficient way: create an iterator to iterate through each row (instead of each element) of the src tensor:
    // Iterate through the rows of the src tensor and copy data to them:
    float* ptr = hog->descriptor();

    for(int i = 0; i < filters[0].nr(); i++)
        for( int j =0; j < filters[0].nc(); ptr += filters.size(),j++)
            for (int o = 0; o < filters.size(); o++)
            {
                *(ptr + o) = filters[o](i, j);
            }

    // Unmap buffer to access in host
    hog->unmap(arm_compute::CLScheduler::get().queue());
}

**Comment by GoodKairos** [comment]
Hi, I have a question. Dlib calculates fhog but ACL calculates hog, how to load the fhog to ACL correctly? Thank you very much.
