### ISSUE TITLE
Which layer support element wise add?

### ISSUE THREAD

**Issue by zhaofenqiang** [ARM-software/ComputeLibrary#356]
I would like to build ResNet50 by Graph API.
But I found BranchMergeMethod only support DEPTH_CONCATENATE.
So is there any plan to support element wise add when concatenating just like the ResNet utilizing.
Or is there any layer or example can be used as reference for the time being.
Thanks!

**Comment by GeorgeARM** [comment]
Hello @zhaofenqiang,
Yes the idea is to add other merging methods. The graph API though is mostly experimental and mostly used for internal testing, so I can't comment when support for this will be added. But we are currently working on ResNet-50 example so it might be part of the next release.

**Comment by zhaofenqiang** [comment]
@GeorgeARM , OK, glad to here that, thank you.

**Comment by GeorgeARM** [comment]
Hello @zhaofenqiang,
ResNet-50 was added in 18.02 release. For the moment we created a residual layer for the graph so should be fine for now.
Closing this issue.
