### ISSUE TITLE
Compute Library based submission to ReQuEST: same prediction for any image

### ISSUE THREAD

**Issue by psyhtest** [ARM-software/ComputeLibrary#357]
We have published [dividiti's submission](https://github.com/dividiti/request-asplos18) to the 1st Reproducible Tournament on Pareto-efficient Image Classification ([ReQuEST @ ASPLOS'18](http://cknowledge.org/request-cfp-asplos2018.html)). It is based on the Arm Compute Library v18.01 ( specifically your [MobileNet graph example](https://github.com/ARM-software/ComputeLibrary/blob/master/examples/graph_mobilenet.cpp)), and our [Collective Knowledge](https://github.com/ctuning/ck) framework for reproducible and collaborative experimentation.

To complete the submission, we need to measure performance (e.g. images per second) and accuracy (top1 / top5 on the [ImageNet](http://www.image-net.org/) validation dataset). Unfortunately, we are having a bit of an issue with doing the latter. To wit, we always get the same answer no matter which image we try to classify.

For example, when classifying a single image, we get:
```
$ ck run program:mobilenets-armcl-opencl
...
--------------------------------
Process results in predictions
---------------------------------------
ILSVRC2012_val_00000001.JPEG - (65) n01751748 sea snake
0.86 - (144) n02051845 pelican
0.03 - (706) n03899768 patio, terrace
0.02 - (969) n07932039 eggnog
0.01 - (369) n02483708 siamang, Hylobates syndactylus, Symphala...
0.01 - (455) n02877765 bottlecap
---------------------------------------
Accuracy top 1: 0.000000 (0 of 1)
Accuracy top 5: 0.000000 (0 of 1)
--------------------------------
```
When classifying two images (two batches consisting of a single image each), we get:
```
$ ck run program:mobilenets-armcl-opencl --env.CK_BATCH_COUNT=2
...
--------------------------------
Process results in predictions
---------------------------------------
ILSVRC2012_val_00000001.JPEG - (65) n01751748 sea snake
0.86 - (144) n02051845 pelican
0.03 - (706) n03899768 patio, terrace
0.02 - (969) n07932039 eggnog
0.01 - (369) n02483708 siamang, Hylobates syndactylus, Symphala...
0.01 - (455) n02877765 bottlecap
---------------------------------------
---------------------------------------
ILSVRC2012_val_00000002.JPEG - (970) n09193705 alp
0.86 - (144) n02051845 pelican
0.03 - (706) n03899768 patio, terrace
0.02 - (969) n07932039 eggnog
0.01 - (369) n02483708 siamang, Hylobates syndactylus, Symphala...
0.01 - (455) n02877765 bottlecap
---------------------------------------
Accuracy top 1: 0.000000 (0 of 2)
Accuracy top 5: 0.000000 (0 of 2)
--------------------------------
```
I believe that with pseudo-random weights we also get the same prediction (but a different one from "pelican"). This suggests that the weights loading mechanism (which we suspected to be at fault for a while) has nothing to do with this problem.

We would appreciate if you could have a quick look at [our code](https://github.com/dividiti/request-asplos18/tree/master/program/mobilenets-armcl-opencl) to see if we are missing something obvious. Many thanks in advance!

/cc @chunosov @gfursin @fvella

**Comment by GeorgeARM** [comment]
Hello @psyhtest ,

Might be a problem with your input preprocessing step.
The 18.01 mobilenet example has some bugs that we have fixed for the upcoming release.
As a pre-processing step for the image just divide each pixel with 255.f  (don't subtract any mean) and set convert to BGR to false.

**Comment by Chunosov** [comment]
Seems it doesn't help.
I've event tried to ignore preprocessing at all and changed input images to be 
```
      RandomAccessor acc(PixelValue(0.0f), PixelValue(1.0f));
      bool ok = acc.access_tensor(tensor);
```
Predictions are changed but they are the same for two images.

**Comment by GeorgeARM** [comment]
@Chunosov @psyhtest has the issue been resolved?

**Comment by psyhtest** [comment]
@GeorgeARM Thank you so much for your help offline! The issue is now fully resolved with our submission publicly available [here](https://github.com/dividiti/ck-request-asplos18-mobilenets-armcl-opencl).

Now, please consider reviewing it :). It should only take 15-20 minutes.

**Comment by bubbles1990** [comment]
@psyhtest @GeorgeARM 
I have the same issue when trying to restore tf's mobilenet ([link](http://download.tensorflow.org/models/mobilenet_v1_1.0_224_2017_06_14.tar.gz)).
Can one of you please share the solution you came up with?
Thank you

**Comment by psyhtest** [comment]
@bubbles1990 Please take a look at our reproducible ReQuEST artifact [here](https://github.com/dividiti/ck-request-asplos18-mobilenets-armcl-opencl), and let me know if you have any questions.

**Comment by bubbles1990** [comment]
Thank you for the comment.
currently I'm working with the ComputeLibrary v18.02. I'm just trying to evaluate mobilenet (1.0, 224) from the tf slim zoo.  I was able to generate the appropriate .npy files for each layer using [tensorflow_data_extractor.py](https://github.com/ARM-software/ComputeLibrary/blob/master/scripts/tensorflow_data_extractor.py), and run the ./graph_mobilenet example.
I have a similar issue to what you had, where no matter what the image input, the output labels are identical (and obviously wrong...).
I've tried to find what did you do so that the mobilenet evaluation won't output the same result for different input images. So far I didn't find it...
There's a missing part (["offline help"](https://github.com/ARM-software/ComputeLibrary/issues/357#issuecomment-366713821)) in this issue thread that I'm trying to understand :)

**Comment by psyhtest** [comment]
@bubbles1990 The "offline help" part has been fully incorporated into the Collective Knowledge workflow above :).

**Comment by bubbles1990** [comment]
I'm sure it was. It's just that I can't tell what line(s) of code in your repo solved the discussed issue, and I will appreciate any hint on that.

**Comment by Chunosov** [comment]
@bubbles1990 Two key points here are:
1) Properly prepare weights files. But as you use ARM's script `tensorflow_data_extractor.py`, you probably already there. BTW which TF version you use with this script? We have not succeeded with it, as it tries to load complete graph from checkpoint files and those contains some reference to an operator which is not available.
2) Properly prepare image before loading it into graph. For that see our file `preprocess.py`

**Comment by bubbles1990** [comment]
Thank you for that @Chunosov ,
I'm using tf 1.4, but I had to apply this [modification](https://github.com/ARM-software/ComputeLibrary/issues/290#issuecomment-363995362).
So from your answer I'm getting that no significant change were made to the cpp file, right?
Thanks again.

**Comment by Chunosov** [comment]
Right. Graph in cpp is built correct.

**Comment by marcosvgmartins** [comment]
Hello @Chunosov. I'm having the exact same problem as @bubbles1990. Since I also successfully used `tensorflow_data_extractor.py` to prepare the weights files, I'm guessing that my problem is in "_properly preparing image before loading it into graph_".

I tried to take a look at the repositories mentioned by you and @psyhtest, but I couldn't find the `preprocess.py` script. Could you help me identifying what needs to be done, or where I can find your pre-processing script?

Thanks in advance.

**Comment by Chunosov** [comment]
@marcosvgmartins We moved the script to more common location as it is used by different programs. Please look it here: https://github.com/ctuning/ck-tensorflow/blob/master/script/cached-benchmark/preprocess.py 
Main preparation is done by `load_image` function, it decodes jpeg files, crops and scales them. Then we save just binary data into temporary files. All what a program have to do is load such a file into input tensor of network.
