### ISSUE TITLE
Anyway to run the graph examples without opencl?

### ISSUE THREAD

**Issue by nwindt** [ARM-software/ComputeLibrary#358]
I want to test the graph examples, however my DUT does not have a mali-gpu. Is there anyway to work around opencl?

**Comment by AnthonyARM** [comment]
Absolutely: you need to build with opencl=1 and neon=1 but at runtime if there is no OpenCL driver available on your platform it will automatically fall back to neon.

If both are available, you can use a hint to decide if you want to use OpenCL or NEON. (It's usually the first command line argument of every graph example)

**Comment by nwindt** [comment]
Awesome, thanks.
