### ISSUE TITLE
NEOpticalFlow wrong results

### ISSUE THREAD

**Issue by idanfr** [ARM-software/ComputeLibrary#359]
Hey, 
I've tried to use the NEOpticalFlow function, and compared it to OpenCV's implementations. I get different results and I don't find why. Maybe I don't use the function correct.
I'm using OpenCV types, like Mat and Point2f as base code.

Here is my code:

    arm_compute::Image curImage, prvImage;
    const arm_compute::TensorShape imgShape(imageWidth, imageHeight);
    curImage.allocator()->init(arm_compute::TensorInfo(imgShape, 1, arm_compute::DataType::U8));
    prvImage.allocator()->init(arm_compute::TensorInfo(imgShape, 1, arm_compute::DataType::U8));
    curImage.allocator()->allocate();
    prvImage.allocator()->allocate();
    unsigned char* pImg = (uchar*)img.ptr(0);
    unsigned char* pPrv = (uchar*)prevImg.ptr(0);
    arm_compute::Window win1, win2;
    win1.use_tensor_dimensions(curImage.info()->tensor_shape(),arm_compute::Window::DimY);
    win2.use_tensor_dimensions(curImage.info()->tensor_shape(),arm_compute::Window::DimY);

    //copy current image
    arm_compute::Iterator it1(&curImage, win1);
    execute_window_loop(win1, [&](const arm_compute::Coordinates & id) { memcpy(it1.ptr(), pImg + id.z() * (imageWidth * imageHeight) + id.y() * imageWidth, imageWidth);  }, it1);
    //copy previous image
    arm_compute::Iterator it2(&prvImage, win2);
    execute_window_loop(win2, [&](const arm_compute::Coordinates & id) { memcpy(it2.ptr(), pPrv + id.z() * (imageWidth * imageHeight) + id.y() * imageWidth, imageWidth);  }, it2);

    //Create Gaussian Pyramid
	arm_compute::PyramidInfo pyrInfo(2, arm_compute::SCALE_PYRAMID_HALF, imgShape, arm_compute::Format::U8);
	arm_compute::Pyramid new_pyramid, old_pyramid;
    arm_compute::NEGaussianPyramidHalf oldGaussianPyramid, newGaussianPyramid;
    old_pyramid.init(pyrInfo);
	new_pyramid.init(pyrInfo);
    old_pyramid.allocate();
    new_pyramid.allocate();

    oldGaussianPyramid.configure(&prvImage, &old_pyramid, arm_compute::BorderMode::CONSTANT, 0);
    oldGaussianPyramid.run();
    newGaussianPyramid.configure(&curImage, &new_pyramid, arm_compute::BorderMode::CONSTANT, 0);
    newGaussianPyramid.run();

    //copy cv::Points array 
    arm_compute::KeyPointArray old_points(prvPoints.size());
	arm_compute::KeyPointArray new_points(prvPoints.size());
	for (cv::Point2f& p : prvPoints) {
		arm_compute::KeyPoint keyPoint;
		keyPoint.x = p.x;
		keyPoint.y = p.y;
		keyPoint.tracking_status = 1;
		old_points.push_back(keyPoint);
	}

    //construct OpticalFlow object
    arm_compute::NEOpticalFlow NeonOF;
	//configure
	NeonOF.configure(&old_pyramid, &new_pyramid, &old_points, &old_points, &new_points, arm_compute::Termination::TERM_CRITERIA_BOTH, 0.03, 10,
					 21, false, arm_compute::BorderMode::CONSTANT, 0);
	//run
	NeonOF.run();

**Comment by AnthonyARM** [comment]
We've added tests for this function, they'll be part of the next release, we haven't found anything fundamentally wrong in our implementation (The only "fix" was to add a safeguard to make sure the function doesn't end up in an infinite loop for some termination criteria values) but hopefully the test will help you to understand how to use the function

**Comment by zanazakaryaie** [comment]
Hello

I used the first part of **idanfr** code to copy an image which is read by opencv. The image is 1280x720 BUT when I print out curImage.info()->dimension(1) after **execute_window_loop** I get 1 instead of 720! curImage.info()->dimension(0) gives 1280 correctly

Could you please help? I guess it's something related to DimY

**Comment by zanazakaryaie** [comment]
Hello

I was searching for a way to read images with OpenCV and then process it with ComputeLibrary. The code here helped me to copy cv::Mat to arm_compute::Image and then do my work. Now I need to copy the arm_compute::Image back to a cv::Mat so that I can display it with cv::imshow.

Could you please help?

**Comment by morgolock** [comment]
Hi @zanazakaryaie 

Please take a look at ACL's documentation: https://arm-software.github.io/ComputeLibrary/v19.02/architecture.xhtml#S4_6_4_working_with_objects

You need to use the `execute_window_loop function` function to copy back onto the cv::Mat.

Please the next time open a new issue and try not to comment on unrelated issues like this on discussing optical flow.

**Comment by morgolock** [comment]
Hi @idanfr 

Please take a look at the patch: https://review.mlplatform.org/#/c/ml/ComputeLibrary/+/1299/ which is an OpticalFlow example.

From the code you shared above, I think you should move:
`old_pyramid.allocate();`
`new_pyramid.allocate();`

below `NeonOF.configure()`

Another thing worth mentioning is that ACL's reference for vision functions is OpenVX and not OpenCV, there might be some minor differences between the results of these two libraries.
