### ISSUE TITLE
Load new images parallel with computation current image on GPU 

### ISSUE THREAD

**Issue by minhntu** [ARM-software/ComputeLibrary#36]
I want to load new images parallel with computation current image on GPU Mali T628 in OdroidXU4 to reduce an overhead time ( time spend on copying a new image to GPU for computation). Do you know how to do that? Whether It can do?

**Comment by steniu01** [comment]
@minhntu , Hi, in your system are there two blocks of memory for the GPU? While GPU access one block, you want CPU to update the other block? Or it is a single block memory, while GPU access one half , you want CPU update the other half?

**Comment by GeorgeARM** [comment]
Hello @minhntu,

Yes theoretically there is nothing stopping you doing that. Probably create another command queue for this purpose and map your input CLTensor, fill it and unmap, while the network runs. Note that you have to do some synchronization as the first layer of you network that requires your input should have finished before trying to fill your input and on the hand the input filling should have finished before rerunning you network.
