### ISSUE TITLE
Classification result is not good on LeNet5 implementation

### ISSUE THREAD

**Issue by pcub** [ARM-software/ComputeLibrary#360]
I am testing LeNet5 model on ACL. The library provides sample code for LeNet5 Model and python script for exporting lenet caffe model (i.e., weight and bias information *.npy). I followed the LeNet mnist tutorial [(http://caffe.berkeleyvision.org/gathered/examples/mnist.html)].
   However, the library does not provide the script to generate "input10.npy". Therefore I wrote python script for obtaining input images as numpy format:

> save_inputImage.py

```
import os, struct
import numpy as np
import random
import matplotlib.pyplot as plt
from array import array as pyarray
from numpy import append, array, int8, uint8, zeros
import sys

if (len(sys.argv)<3):
    print "usage example: python *.py 10 input10_10.npy"
    sys.exit(0)

i = int(sys.argv[1])
print "using: ", i,"-th images"
outputName = (sys.argv[2])

def readDataSet(digits, path = "."):

    fname_img = os.path.join(path, 't10k-images-idx3-ubyte')
    fname_lbl = os.path.join(path, 't10k-labels-idx1-ubyte')
    flbl = open(fname_lbl, 'rb')
    magic_nr, size = struct.unpack(">II", flbl.read(8))
    lbl = pyarray("b", flbl.read())
    flbl.close()

    fimg = open(fname_img, 'rb')
    magic_nr, size, rows, cols = struct.unpack(">IIII", fimg.read(16))
    img = pyarray("B", fimg.read())
    fimg.close()

    ind = [ k for k in xrange(size) if lbl[k] in digits ]
    N = len(ind)

    images = zeros((N, rows, cols), dtype=uint8)
    labels = zeros((N, 1), dtype=int8)

    images[i] = array(img[ind[i]*rows*cols : (ind[i]+1)*rows*cols]).reshape((rows, cols))
    labels[i] = lbl[ind[i]]
    return images, labels

outputs = zeros((10,28,28,1),dtype=float)

for x in range(10):
    images, labels = readDataSet([x], 'caffe/data/mnist')
    plt.imshow(images[i])
    plt.show()
    outputs[x,:,:,0] = 1.0 - images[i]/255.0
print "saving output imamges under: ", outputName
np.save(outputName,outputs)
```
    
this script generates input image(28x28) that contains digit from 0 to 9 into numpy format. Then I used this file into LeNet5 sample code that is provided by ACL.

> main.cpp
```
// input image in numpy array
    std::string input_file = "input10.npy";
    // Expected labels
    std::vector<unsigned int> expected_labels = {0,1,2,3,4,5,6,7,8,9};
    unsigned int numBatches = expected_labels.size();
    // run lenet5 model
    std::vector<unsigned int> classified_labels = compute_lenet5(numBatches, input_file);
    for(unsigned int i = 0; i < numBatches; ++i)
    {
        cout<<"expectedLabels: "<<expected_labels[i]<<"\t"<<"classifiedLabels: "<<classified_labels[i]<<endl;
    }
```
and classification result for example is as follows:
```
expectedLabels: 0	classifiedLabels: 5
expectedLabels: 1	classifiedLabels: 2
expectedLabels: 2	classifiedLabels: 7
expectedLabels: 3	classifiedLabels: 2
expectedLabels: 4	classifiedLabels: 2
expectedLabels: 5	classifiedLabels: 5
expectedLabels: 6	classifiedLabels: 3
expectedLabels: 7	classifiedLabels: 1
expectedLabels: 8	classifiedLabels: 1
expectedLabels: 9	classifiedLabels: 5
```

My question is why this model give kind of result?
Is my python script for generating input image is same with your script?

Thank you in advance.

**Comment by GeorgeARM** [comment]
Hello @pcub,

Are you sure that your preprocessing step is correct?
`outputs[x,:,:,0] = 1.0 - images[i]/255.0`
I would expect the output to be `images[i]/256.f`.

**Comment by pcub** [comment]
I changed the output:
`outputs[x,:,:,0] = images[i]/256.0`
however, result is:
expectedLabels: 0	classifiedLabels: 8
expectedLabels: 1	classifiedLabels: 0
expectedLabels: 2	classifiedLabels: 1
expectedLabels: 3	classifiedLabels: 1
expectedLabels: 4	classifiedLabels: 8
expectedLabels: 5	classifiedLabels: 4
expectedLabels: 6	classifiedLabels: 7
expectedLabels: 7	classifiedLabels: 6
expectedLabels: 8	classifiedLabels: 0
expectedLabels: 9	classifiedLabels: 1

**Comment by giorgio-arena** [comment]
Hi @pcub 

There is a problem with the way you store the output's shape. Once you have got all the necessary values in the layout that has been provided to you (in this case [batches, width, height, depth]) it must be converted to the layout that our library supports ([batches, depth, width, height]).

Also, you should explicitly state the data type of the output tensor.

The bottom part of your script will look something like this:
```
outputs = zeros((10, 28, 28, 1), dtype=float32)

for x in range(10):
    images, labels = readDataSet([x])
    outputs[x,:,:,0] = images[i]/256.0

transp_outs = np.transpose(outputs, (0, 3, 1, 2))
np.save(outputName, transp_outs)
```

I'd suggest you compile our library in debug mode (i.e. add debug=1 to the scons command) as there are asserts aimed to avoid errors like this, which would be skipped in release mode.

Hope this helps!

**Comment by pcub** [comment]
Hi @giorgio-arena 
Problem was in python script to save the input images. 
Now ACL LeNet5-model sample code works as expected.
Thank you.
