### ISSUE TITLE
graph_*_net fails in some images

### ISSUE THREAD

**Issue by pcub** [ARM-software/ComputeLibrary#362]
I followed similar procedure that graph_alexnet can run.
What I did is: first converted sqeezenet_v1.0 caffe model (https://github.com/DeepScale/SqueezeNet/tree/master/SqueezeNet_v1.0) to numpy array using caffe_data_extractor.py and run following command:

`./examples/graph_squeezenet 0 /home/*/cnn_test_data/compute_library_squeezenet /home/*/cnn_test_data/go_kart.ppm /home/*/cnn_test_data/labels.txt`

result is:
```
Segmentation fault (core dumped)

```
**Note** do not confuse with /home/*

when I change the input image as ComputeLibrary/data/images/128x128.ppm
graph_squeezenet works.
also in case of ComputeLibrary/data/images/1280x720.ppm
graph_squeezenet fails.
grapch_alexnet also fails when input image is 1280x720.ppm
it seems there is a bug in ppm related code in ACL.

**Comment by pcub** [comment]
when I change the imput image as ComputeLibrary/data/images/128x128.ppm
graph_squeezenet works.
also in case of ComputeLibrary/data/images/1280x720.ppm
graph_squeezenet fails.

what is the problem?

**Comment by GeorgeARM** [comment]
Hello @pcub,
The way the example is now accepts only inputs of 224x224 size.
You can alter it I presume to accept different image sizes but the last steps of the pipeline have to change.

**Comment by pcub** [comment]
My main point here is for example:
go_kart.ppm (input image) has dimension 227x227 and graph_alexnet works on this image.
however graph_squeezenet does not work on this image.

**Comment by GeorgeARM** [comment]
@pcub can you provide us with your build command?

**Comment by pcub** [comment]
scons -j4 Werror=1 debug=0 asserts=0 neon=1 opencl=1 os=linux arch=arm64-v8a examples=1

**Comment by GeorgeARM** [comment]
Well yes the `PPMLoader` seems to segfault but its not a bug in the loader.
As you can see [here](https://github.com/ARM-software/ComputeLibrary/blob/master/examples/graph_squeezenet.cpp#L98) the input tensor is marked as a 224x224 image thus if you give a bigger image in the loader it will go and fill the input tensor out of bounds. Thus if you want this to work with a bigger image you should change the width and height in the code line I mentioned.

**Comment by pcub** [comment]
It worked. Thank you
