### ISSUE TITLE
Graph does not support DeconvolutionLayer

### ISSUE THREAD

**Issue by ek9852** [ARM-software/ComputeLibrary#367]
There is no DeconvolutionLayer support in Graph

**Comment by AnthonyARM** [comment]
The Graph library is used only for tests purposes, which is why it currently only contains the nodes we've needed to implement the example networks.

**Comment by AnthonyARM** [comment]
We've added this request to our backlog, however it's not high priority so can't guarantee if / when it will be done.
If someone else in the community wants to pick it up, please let us know

**Comment by GeorgeARM** [comment]
Fixed on 18.08 release. Reopen if needed.
