### ISSUE TITLE
Need example for image segmentation networks

### ISSUE THREAD

**Issue by ek9852** [ARM-software/ComputeLibrary#368]
Need example support for image segmentation such as segnet, unet, etc. Not just classification.

**Comment by AnthonyARM** [comment]
We've added this request to our backlog, however it's not high priority so can't guarantee if / when it will be done.
If someone else in the community wants to pick it up, please let us know

**Comment by morgolock** [comment]
Hi @ek9852 

Apologies for the delayed reply.

We have added the request to our backlog and this might be scheduled to be done for any of the upcoming releases. In the meantime I would suggest you looking into Deeplab TFlite model, you can run this model through ArmNN+ACL.
