### ISSUE TITLE
convolution method chosen in 18.02

### ISSUE THREAD

**Issue by wl3b10s** [ARM-software/ComputeLibrary#372]
1.  the return value of NEConvolutionLayer::get_convolution_method seems that direct conv will never be chosen

2.  is there any doc for the winogard method conv? 

thanks.

**Comment by AnthonyARM** [comment]
1. That's because currently direct convolution is never faster than GEMM or Winograd

2. I'm not sure I understand the question ? The interface for NEWinogradLayer is the same one as the other Convolution layers.

**Comment by wl3b10s** [comment]
i mean: the method of gemm and directconv is easy to understand.

but the winogard calculation formula comes from what doc or thesis? i need some help for understanding the math formula. 

thanks.

**Comment by AnthonyARM** [comment]
This is based on [this paper](https://arxiv.org/pdf/1509.09308.pdf)

**Comment by wl3b10s** [comment]
thanks a lot @AnthonyARM
