### ISSUE TITLE
How to  Load input tensor using graph

### ISSUE THREAD

**Issue by szihs** [ARM-software/ComputeLibrary#373]
Hello,
How do I migrate nongraph CNN model to graph model.

Specifically how / when to copy the source data to input layer
From Neon_cnn.cpp, first init src tensor, then configure, then allocate and **then copy**
```
  // Initialize src tensor
        constexpr unsigned int width_src_image  = 32;
        constexpr unsigned int height_src_image = 32;
        constexpr unsigned int ifm_src_img      = 1;

        const TensorShape src_shape(width_src_image, height_src_image, ifm_src_img);
        src.allocator()->init(TensorInfo(src_shape, 1, DataType::F32));
```
```
      graph << target_hint
              << Tensor(TensorInfo(TensorShape(28U, 28U, 1U, batches), 1, DataType::F32), DummyAccessor())
```

How to do the same using graph API ?
Regards,
Harsh

**Comment by AnthonyARM** [comment]
Tensors initialisation / allocations are automatically handled by the Graph API, you just need to pass the shape, format and an accessor.

The accessor will get called whenever the Tensor needs filling.
If it's a tensor containing weights it will get called only once, if it's a graph input / output it will get called every time the graph gets executed.

You can have a look at the [PPMAccessor](https://github.com/ARM-software/ComputeLibrary/blob/v18.03/utils/GraphUtils.h#L116) (implementation [here](https://github.com/ARM-software/ComputeLibrary/blob/v18.03/utils/GraphUtils.cpp#L114))for an example of how to create a simple Accessor.

Please note, currently there is a known issue with graphs containing only a single node, so make sure your graph contains at least 2 layers when experimenting with the API.

**Comment by szihs** [comment]
Thanks Anthony.

Regards,
Harsh
