### ISSUE TITLE
CLDeconvolutionLayer with 4x4 weights

### ISSUE THREAD

**Issue by shaharf1** [ARM-software/ComputeLibrary#374]
Hi,
We tried to configure CLDeconvolutionLayer with a 4x4 weights on version 18.01.
We got this error:

_terminate called after throwing an instance of 'std::runtime_error'
  what():  in arm_compute::Kernel arm_compute::CLKernelLibrary::create_kernel(const std::string &, const StringSet &) const src/core/CL/CLKernelLibrary.cpp:688: Kernel direct_convolution4x4 not found in the CLKernelLibrary
Aborted_

Are you not supporting it?
When will you support it?

Thanks.

**Comment by mpekatsoula** [comment]
Hi @shaharf1,
Can you try with version 18.02? We now use CLConvolutionLayer and not CLDirectConvolution inside the DeconvolutionLayer.

**Comment by shaharf1** [comment]
Thanks I will try.

BTW,
I think your link to the 18.02 binary is not good:
https://github.com/ARM-software/ComputeLibrary/releases/download/v*18.01*
/arm_compute-v18.02-bin-android.tar.gz

**Comment by mpekatsoula** [comment]
Thanks, @shaharf1, the binary links will be fixed in the maintenance release.

**Comment by AnthonyARM** [comment]
FYI the correct links are here:
- [v18.02-linux](https://github.com/ARM-software/ComputeLibrary/releases/download/v18.02/arm_compute-v18.02-bin-linux.tar.gz)
- [v18.02-android](https://github.com/ARM-software/ComputeLibrary/releases/download/v18.02/arm_compute-v18.02-bin-android.tar.gz)

**Comment by GeorgeARM** [comment]
Closing. Should have been resolved in 18.03. Reopen if needed.
