### ISSUE TITLE
Output Mismatch

### ISSUE THREAD

**Issue by Subarukun** [ARM-software/ComputeLibrary#379]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

arm_compute_version=v18.01 Build options: {'cppthreads': '1', 'arch': 'armv7a', 'opencl': '0', 'neon': '1', 'build': 'native', 'debug': '0', 'openmp': '1', 'os': 'linux', 'Werror': '0'} Git hash=unknown

**Platform:**
raspberrypi 3
**Operating System:**
archlinux

**Problem description:**
I have created the standalone setup for 3 layers (conv->relu->maxpool). Input to convolution is always same and fixed. This 3 layers are run repeatedly in a while loop as shown in the wrapper file. I expect the output to be same for all the iterations as the input is always fixed   . However we see results mismatch with the expected outputs. This mismatch is observed randomly for conv/maxpoolLayer in between 1 to 10 iterations.

Could you please check if the same behaviour is observed on your side with the attached inputs and wrapper files and let us know your feedback.
[testsetup.zip](https://github.com/ARM-software/ComputeLibrary/files/1788936/testsetup.zip)

**Comment by Subarukun** [comment]
is there any update on this?

**Comment by GeorgeARM** [comment]
Hello @Subarukun,

Just saw your code. I think this is probably due to the padding. You seem to incorrectly fill and read the values.
Please look at the documentation [here](https://arm-software.github.io/ComputeLibrary/v18.03/architecture.xhtml#S4_6_4_working_with_objects)
Better used Window loops to fill and read you values.

**Comment by Subarukun** [comment]
Hi @GeorgeARM,
Since the  dimensions(input,weights,bias) for conv layer does not increase in the attached example code , I have used the copy_n instead of the window loop mentioned.So that is not the issue.

The given example code runs fine for some iterations. If padding is the issue then ideally every iteration must fail.There might be something wrong.Could you rerun and look into the issue.

**Comment by GeorgeARM** [comment]
Well your inputs might not have padding but your destination and relu output does have.
Of course it depends on how you produced the intermediate buffers that you compare with, and you are correct that it should fail if it was a padding problem and I am surprised it does not.
I compiled your code and run without any failures.
I also get this:
```
conv dst :1520768   dst Tensor size: 1562624 
relu dst :1520768   dst Tensor size: 1562624 
mp dst :373248   dst Tensor size: 373248 
```  
which justifies the fact that there is padding in the tensor. Do you get something similar or the size of your tensors are the same size with the reference? If there is padding why do you validate consecutive elements? I would expect to see failures in max pool output as there is no padding.

Finally, can you report what these values are for you and in which elements you get failures. Are they in consistent places? Could you try latest release as well?

**Comment by Subarukun** [comment]
Yes George I do get the same padding values as you have shown. With the latest release I donot see this issue for the given setup upto  50 iterations.
If you have the raspberrypi 3 with arch linux can you run the sample alexnet model and let us know your results with multiple runs . In our case we are seeing difference in outputs for the same image with opencv and imshow for alexnet model. Could be due to huge cpu load or low RAM . If you need I can give you our sample Alexnet setup where we are seeing this issue.

**Comment by GeorgeARM** [comment]
Hello @Subarukun,

I don't have raspberry pi 3 with arch linux setup but I did try your test on a similar platform and on our latest release. I left it run more than 100 iterations multiple times without any issues.
As I mentioned above the way you check your conv and relu output seems to be wrong. You check consecutive values of your result without accounting the padding (maybe I am missing something).

Difference in the output might be due to several reason. Have you tried to check it layer by layer to find which layer starts to go wrong? Can you also try our graph alexnet example as well and check the output? 
If you send us the Alexnet setup I can have a look, but try the above first.

Thanks

**Comment by Subarukun** [comment]
Hi George,

Thanks for trying it out and letting us know the results George.As I have mentioned in my previous comments, I don't have issue for the test setup that I have shared with you using latest release . It was meeting our tolerance level .

However, I am facing issues with Alexnet Model for multiple runs on raspberry pi 3. I can give you my failing setup of Alexnet Model but again, I do not think it is of no use to you, since you confirmed that you do not have raspberry pi platform.

If you still want try out the alexnet model standalone test setup, I could give you that.
####  It would be great if you could let us know what is the platform/simulator  that you are using to test these things. We could also use the same setup instead investing our resources on rpi3b.

Thanks,
G. Praveen.

**Comment by GeorgeARM** [comment]
Hello @Subarukun,

Please send over your failing setup so that we can have a better look.

**Comment by AnthonyARM** [comment]
We haven't looked at the attached files yet.
But out of curiosity: have you tried using `examples/graph_alexnet.cpp` instead ? 
It's a more up to date version.

**Comment by uu-praveeng** [comment]
Hi Anthony,

I have gone through the graph_alexnet.cpp and it appears to be very simpler without exposing internal details.

Anyways I see 2 approaches to tackle the issue:
1) If graph_alexnet accepts the video as input then ,recheck the same issue with graph_alexnet. 
     How ever it has been written to take a single image during the dosetup. We are planning for an 
     example that takes a video as input. It would be great if there is graph_alexnet example which accepts 
     the video input file.

2)  Inherently **if** the graph_alexnet uses same code as AlexNetNetwork.h then the issue(inconsistent outputs) would still persists . So looking into the issue with AlexNetNetwork.h would be a good idea.

I could share a demo video of the issue on raspberrypi if you want to have a look at nature of the issue.

Thanks.

**Comment by AnthonyARM** [comment]
`graph_alexnet` doesn't accept a video but it would be pretty easy to implement.
Basically if you look at how [Graph::run()](https://github.com/ARM-software/ComputeLibrary/blob/master/src/graph/Graph.cpp#L111) is implemented you'll see that the network is called inside a loop for as long as the input / output accessor return true.

So you could just provide your own accessor with something like:
```cpp
bool VideoAccessor::access_tensor(ITensor &tensor)
{
    if( video.eof()) return false;

    tensor.fill( video.next_frame() ):
   return true;
}
```
Then the network will run for every frame of the video with a single call to `graph.run()`

Hope this helps,

**Comment by AnthonyARM** [comment]
Also, George is right: You cannot just use `memcpy` to set the input, you need to copy row by row using `execute_window_loop` to take into account the padding.

Something like:
```cpp
// Create an iterator:
        Iterator output_it(&output, output_window);
        // Iterate through the rows of the output tensor and copy them to dst_data:
        // This is equivalent to:
        // for( unsigned int z = 0; z < batch; ++z)
        // {
        //   for( unsigned int y = 0; y < height; ++y)
        //   {
        //     memcpy( dst_data + z * (width*height) + y * width, input.buffer() + input.info()->offset_element_in_bytes(Coordinates(0,y,z)), width * sizeof(float));
        //   }
        // }
        // Except it works for an arbitrary number of dimensions
        execute_window_loop(output_window, [&](const Coordinates & id)
        {
            std::cout << "Copying one row starting from [" << id.x() << "," << id.y() << "," << id.z() << "]\n";
            // Copy one whole row:
            memcpy(dst_data + id.z() * (width * height) + id.y() * width, output_it.ptr(), width * sizeof(float));
        },
        output_it);
```

**Comment by GeorgeARM** [comment]
@Subarukun Did y

**Comment by uu-praveeng** [comment]
Hi George,

Sorry for the delayed response . 

I was able to create an example using the graph_alexnet which takes video as input and outputs the result. To do this I have implemented VideoAccessor as suggested . Opencv is used to extract frames from Video which happens in the VideoAccessor:accesstensor.

After running the example we observed that there was wrong classification randomly as shown in the below snapshot at frame:39


---------- Top 5 predictions ----------

0.2282 - [id = 889], n04536866 violin, fiddle
0.0839 - [id = 432], n02804610 bassoon
0.0757 - [id = 546], n03272010 electric guitar
0.0755 - [id = 486], n02992211 cello, violoncello
0.0747 - [id = 420], n02787622 banjo
frame :34
---------- Top 5 predictions ----------

0.2260 - [id = 889], n04536866 violin, fiddle
0.0816 - [id = 432], n02804610 bassoon
0.0751 - [id = 558], n03372029 flute, transverse flute
0.0741 - [id = 486], n02992211 cello, violoncello
0.0728 - [id = 420], n02787622 banjo
frame :35
---------- Top 5 predictions ----------

0.2257 - [id = 889], n04536866 violin, fiddle
0.0817 - [id = 432], n02804610 bassoon
0.0751 - [id = 558], n03372029 flute, transverse flute
0.0740 - [id = 486], n02992211 cello, violoncello
0.0728 - [id = 420], n02787622 banjo
frame :36
---------- Top 5 predictions ----------

0.2176 - [id = 889], n04536866 violin, fiddle
0.0831 - [id = 432], n02804610 bassoon
0.0752 - [id = 558], n03372029 flute, transverse flute
0.0744 - [id = 486], n02992211 cello, violoncello
0.0718 - [id = 420], n02787622 banjo
frame :37
---------- Top 5 predictions ----------

0.2269 - [id = 889], n04536866 violin, fiddle
0.0804 - [id = 432], n02804610 bassoon
0.0746 - [id = 558], n03372029 flute, transverse flute
0.0737 - [id = 486], n02992211 cello, violoncello
0.0735 - [id = 420], n02787622 banjo
frame :38
---------- Top 5 predictions ----------

### 1.0000 - [id = 955], n07754684 jackfruit, jak, jack
0.0000 - [id = 672], n03792972 mountain tent
0.0000 - [id = 658], n03775071 mitten
0.0000 - [id = 659], n03775546 mixing bowl
0.0000 - [id = 660], n03776460 mobile home, manufactured home
frame :39
---------- Top 5 predictions ----------

0.2262 - [id = 889], n04536866 violin, fiddle
0.0842 - [id = 432], n02804610 bassoon
0.0767 - [id = 546], n03272010 electric guitar
0.0754 - [id = 420], n02787622 banjo
0.0735 - [id = 486], n02992211 cello, violoncello
frame :40
---------- Top 5 predictions ----------

0.2257 - [id = 889], n04536866 violin, fiddle
0.0784 - [id = 432], n02804610 bassoon
0.0782 - [id = 420], n02787622 banjo
0.0781 - [id = 546], n03272010 electric guitar
0.0734 - [id = 486], n02992211 cello, violoncello
frame :41
---------- Top 5 predictions ----------

0.2282 - [id = 889], n04536866 violin, fiddle
0.0805 - [id = 558], n03372029 flute, transverse flute
0.0793 - [id = 432], n02804610 bassoon
0.0754 - [id = 486], n02992211 cello, violoncello
0.0730 - [id = 420], n02787622 banjo
frame :42
---------- Top 5 predictions ----------

0.2299 - [id = 889], n04536866 violin, fiddle
0.0803 - [id = 432], n02804610 bassoon
0.0757 - [id = 486], n02992211 cello, violoncello
0.0744 - [id = 558], n03372029 flute, transverse flute
0.0726 - [id = 546], n03272010 electric guitar

Please let me know if you need the testsetup.

Thanks,
G.Praveen

**Comment by GeorgeARM** [comment]
Hello @uu-praveeng ,

Can you provide us with your setup and some inputs?
This seems rather strange.

Thanks,
George

**Comment by uu-praveeng** [comment]
Did you have a chance to  look into this?

**Comment by AnthonyARM** [comment]
Yes, and we can't reproduce the problem.
Internally we've got tests running on huge image datasets (thousands of images) and they work fine, so it seems to be likely to be an issue with your OpenCV setup and your camera code.

**Comment by AnthonyARM** [comment]
As explained above: our unit tests pass, so it's likely to be an issue related to the data transfer between OpenCV and the Compute Library

**Comment by hdchenjian** [comment]
Hello @Subarukun , I may found output mismatch reason, I have meet same issue, code like this:

`class LoadInputData final : public arm_compute::graph::ITensorAccessor
{
public:
    LoadInputData(float *data) : _already_loaded(false), _data(data){}

    bool access_tensor(arm_compute::ITensor &tensor) override {
        if(!_already_loaded){
            if(tensor.info()->data_type() != arm_compute::DataType::F32){
                printf("Unsupported format\n");
                exit(-1);
            }
            arm_compute::Window window;
            window.use_tensor_dimensions(tensor.info()->tensor_shape());
            arm_compute::utils::map(tensor, true);
            arm_compute::Iterator it(&tensor, window);

            int i = 0;
            printf("LoadInputData %p\n", reinterpret_cast<float *>(it.ptr()));
            execute_window_loop(window, [&](const arm_compute::Coordinates & id) {
                    //if(i < 10) printf("LoadInputData %d %d %d %d %f\n", i, id.x(), id.y(), id.z(), _data[i]);                                                              
                    //*reinterpret_cast<float*>( tensor.buffer() + tensor.info()->offset_element_in_bytes(id)) = _data[i++];                                                 
                    *reinterpret_cast<float *>(it.ptr()) = _data[i++];
                },
                it);
            arm_compute::utils::unmap(tensor);
            printf("LoadInputData %d %f\n", i, _data[0]);
        }
        _already_loaded = !_already_loaded;
        return true;
        //return _already_loaded;                                                                                                                                            
    }

private:
    bool _already_loaded;
    float *_data;
};

float face_feature[512];
arm_compute::graph::frontend::Stream graph_face(0, "yolov3");
    graph_face << graph_target
              << fast_math_hint
              << arm_compute::graph::frontend::InputLayer(input_descriptor, arm_compute::support::cpp14::make_unique<LoadInputData>(face_image_input))
              << arm_compute::graph::frontend::ConvolutionLayer(
                  3U, 3U, 64U,
                  get_weights_accessor(data_path, "conv0_w.npy"),
                  std::unique_ptr<arm_compute::graph::ITensorAccessor>(nullptr),
                  arm_compute::PadStrideInfo(1, 1, 1, 1)).set_name("conv0");
    graph_face << arm_compute::graph::frontend::OutputLayer(arm_compute::support::cpp14::make_unique<ReadOutputData>(face_feature));
`
I test use a ConvolutionLayer, the first time run result is right, but second round is different, because access_tensor return bool value, you should always return true, not `_already_loaded = !_already_loaded`
