### ISSUE TITLE
Are there any design documents of the implementation and framework?

### ISSUE THREAD

**Issue by eric2016fly** [ARM-software/ComputeLibrary#38]
Are there any documents about the details of how the image processing algorithm is implemented using opencl and neon or about the framework architecture?
Do the community plan for this thing? I'm in big hungry for this.

Thanks

**Comment by AnthonyARM** [comment]
There are several places you can look for image processing algorithms: [OpenCV](http://docs.opencv.org/3.2.0/d7/dbd/group__imgproc.html) , [OpenVX](https://www.khronos.org/registry/OpenVX/specs/1.1/html/index.html), Eigen (For the CNN functions), Caffe / TensorFlow, etc.

**Comment by AnthonyARM** [comment]
You also have a few tutorials on the [ARM developer website](https://developer.arm.com/graphics/tutorials/opencl-tutorials)

**Comment by eric2016fly** [comment]
Thanks for the reply,however, For community are there any plans to fully explain how the parrallel kernels are designed and the optimization techniques used to implement all the algorithms which are alrealy implemented in the reposity? And also how the framework is designed?

**Comment by AnthonyARM** [comment]
Guides like those mentioned in my previous comment are really time consuming to produce and got very little success in the past.

We have plans to create some series of blog posts detailing specific features but we probably won't create an exhaustive documentation of all the algorithms implemented in the library (You can already find a lot of information on those in the OpenVX / OpenCV documentations)

If you're interested in specific algorithms, feel free to ask here and we'll try to give more details (And add those to the library's documentation too)

**Comment by mdigiorgio** [comment]
Closing this issue as the question has been answered. Reopen if needed.
