### ISSUE TITLE
Need help with Deconvolution Layer

### ISSUE THREAD

**Issue by shaharf1** [ARM-software/ComputeLibrary#380]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

arm_compute_version=v18.03 Build options: {'embed_kernels': '1', 'opencl': '1', 'pmu': '1', 'arch': 'arm64-v8a', 'standalone': '0', 'neon': '1', 'build_dir': 'android-arm64-v8a-neon-cl', 'debug': '0', 'validation_tests': '0', 'examples': '1', 'asserts': '0', 'mali': '1', 'benchmark_tests': '0', 'os': 'android', 'Werror': '1'} Git hash=e40997bbad105e298214e6d40cc87ab2b49f8efb

**Platform:**
Samsung Galaxy

**Operating System:**
Android

**Problem description:**

I am trying to implement the following simple deconvolution layer with Arm Compute Lib:

Input (4x2x2):
[[[[ 1.  1.  1.  1.]
   [ 1.  1.  1.  1.]]
  [[ 3.  3.  3.  3.]
   [ 3.  3.  3.  3.]]]]
   
kernel (4x4x2): 
[[[[ 1.  1.  1.  1.]
   [ 1.  1.  1.  1.]
   [ 1.  1.  1.  1.]
   [ 1.  1.  1.  1.]]]   
 [[[ 2.  2.  2.  2.]
   [ 2.  2.  2.  2.]
   [ 2.  2.  2.  2.]
   [ 2.  2.  2.  2.]]]]
     
caffe deconvolution output(stride=2, pad = 1): 
[[[[  1.   2.   2.   2.   2.   2.   2.   1.]
   [  2.   4.   4.   4.   4.   4.   4.   2.]
   [  2.   4.   4.   4.   4.   4.   4.   2.]
   [  1.   2.   2.   2.   2.   2.   2.   1.]]

  [[  6.  12.  12.  12.  12.  12.  12.   6.]
   [ 12.  24.  24.  24.  24.  24.  24.  12.]
   [ 12.  24.  24.  24.  24.  24.  24.  12.]
   [  6.  12.  12.  12.  12.  12.  12.   6.]]]]

Here is my code:

//Buffers 
float input_image[] = { 1,1,1,1,1,1,1,1, 3,3,3,3,3,3,3,3};
float deconv_weights[] = { 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1, 2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2};
float deconv_biases[] = {  0, 0};

//Tensor 
CLTensor data_T0_tensor;
CLTensor deconv_weights_tensor;
CLTensor deconv_biases_tensor;
CLTensor deconv_T0_tensor;

	
const TensorShape data_T0_tensor_shape((unsigned int)4, (unsigned int)2, (unsigned int)2);
data_T0_tensor.allocator()->init(TensorInfo(data_T0_tensor_shape, 1, DataType::F32));

const TensorShape deconv_weights_tensor_shape(4 , 4 ,(long unsigned int)1 , 2);
deconv_weights_tensor.allocator()->init(TensorInfo(deconv_weights_tensor_shape, (long unsigned int)1, DataType::F32));

const TensorShape deconv_biases_tensor_shape(2);
deconv_biases_tensor.allocator()->init(TensorInfo(deconv_biases_tensor_shape, 1, DataType::F32));

const TensorShape deconv_T0_tensor_shape(data_T0_tensor_shape.x()*2, data_T0_tensor_shape.y()*2, 2);
deconv_T0_tensor.allocator()->init(TensorInfo(deconv_T0_tensor_shape, 1, DataType::F32));

//layer config 
CLDeconvolutionLayer  * deconv_p = new CLDeconvolutionLayer();
deconv_p->configure(&data_T0_tensor,&deconv_weights_tensor, &deconv_biases_tensor, &deconv_T0_tensor, PadStrideInfo(2, 2, 1, 1), (long unsigned int)0, (long unsigned int)0 );

//alllocate tensors 
data_T0_tensor.allocator()->allocate();
deconv_weights_tensor.allocator()->allocate();
deconv_biases_tensor.allocator()->allocate();
deconv_T0_tensor.allocator()->allocate();

//Write Weights and Biases
copyDataToTensor((uint8_t *)deconv_weights , &deconv_weights_tensor);
copyDataToTensor((uint8_t *)deconv_biases , &deconv_biases_tensor);
copyDataToTensor((uint8_t *)input_image , &data_T0_tensor);

deconv_p->run();
		

The result I get is:

[[4.0000000   14.0000000   15.0000000   14.0000000   15.0000000   14.0000000   0.0000000   0.0000000   ]
[13.0000000   7.0000000   7.0000000   7.0000000   7.0000000   7.0000000   0.0000000   0.0000000   ]
[0.0000000   0.0000000   0.0000000   0.0000000   0.0000000   0.0000000   0.0000000   0.0000000   ]
[0.0000000   0.0000000   0.0000000   0.0000000   0.0000000   0.0000000   0.0000000   0.0000000   ]
]
[[8.0000000   28.0000000   30.0000000   28.0000000   30.0000000   28.0000000   0.0000000   0.0000000   ]
[26.0000000   14.0000000   14.0000000   14.0000000   14.0000000   14.0000000   0.0000000   0.0000000   ]
[0.0000000   0.0000000   0.0000000   0.0000000   0.0000000   0.0000000   0.0000000   0.0000000   ]
[0.0000000   0.0000000   0.0000000   0.0000000   0.0000000   0.0000000   0.0000000   0.0000000   ]
]
		
What am I doing wrong?
   
Thanks.

**Comment by mpekatsoula** [comment]
Hi @shaharf1 ,

Can you please try with PadStrideInfo(2, 2, 2, 2)? We follow a different implementation compared to caffe, thus the pad values are not the same. Let us know if this works.

**Comment by shaharf1** [comment]
Thanks.

This is what I get with PadStrideInfo(2, 2, 2, 2).  Still not what I expect.
I will read about your approach. I didn't know that it is different.

[[1.0000000   4.0000000   7.0000000   7.0000000   7.0000000   7.0000000   7.0000000   7.0000000   ]
[5.0000000   9.0000000   14.0000000   15.0000000   14.0000000   15.0000000   14.0000000   14.0000000   ]
[7.0000000   4.0000000   7.0000000   7.0000000   7.0000000   7.0000000   7.0000000   7.0000000   ]
[4.0000000   4.0000000   7.0000000   7.0000000   7.0000000   7.0000000   7.0000000   7.0000000   ]
]
[[2.0000000   8.0000000   14.0000000   14.0000000   14.0000000   14.0000000   14.0000000   14.0000000   ]
[10.0000000   18.0000000   28.0000000   30.0000000   28.0000000   30.0000000   28.0000000  
 28.0000000   ]
[14.0000000   8.0000000   14.0000000   14.0000000   14.0000000   14.0000000   14.0000000   14.0000000   ]
[8.0000000   8.0000000   14.0000000   14.0000000   
14.0000000   14.0000000   14.0000000   14.0000000   ]
]

**Comment by mpekatsoula** [comment]
Can you please provide us the copyDataToTensor() function in order to make sure that the tensors are correctly initialized? 

Thanks

**Comment by shaharf1** [comment]
I will be able to do it only on Sunday. sorry....

**Comment by shaharf1** [comment]
Anyway, I have been using this function in all other networks and never saw
a problem.

**Comment by mpekatsoula** [comment]
Hi @shaharf1 , 
I was able to test your code and your weights shape: 
`const TensorShape deconv_weights_tensor_shape(4 , 4 ,(long unsigned int)1 , 2);`
should be
`const TensorShape deconv_weights_tensor_shape(4 , 4 ,(long unsigned int)2 , 2);`

3rd dimension of weights should be equal to OFM.

In the above example, your weights should be 0 when dim Z equals to 1, something like this:

[[[[ 1. 1. 1. 1.]
[ 1. 1. 1. 1.]
[ 1. 1. 1. 1.]
[ 1. 1. 1. 1.]] 
[[[ 0. 0. 0. 0.]
[ 0. 0. 0. 0.]
[ 0. 0. 0. 0.]
[ 0. 0. 0. 0.]]]
[[[ 2. 2. 2. 2.]
[ 2. 2. 2. 2.]
[ 2. 2. 2. 2.]
[ 2. 2. 2. 2.]]
[[ 0. 0. 0. 0.]
[ 0. 0. 0. 0.]
[ 0. 0. 0. 0.]
[ 0. 0. 0. 0.]]]]

Let us know if you still have a problem

**Comment by shaharf1** [comment]
Thanks.

Actually my weights should be:

[[[[ 1. 1. 1. 1.]
[ 1. 1. 1. 1.]
[ 1. 1. 1. 1.]
[ 1. 1. 1. 1.]]
[[[ 0. 0. 0. 0.]
[ 0. 0. 0. 0.]
[ 0. 0. 0. 0.]
[ 0. 0. 0. 0.]]]
[[[ 0. 0. 0. 0.]
[ 0. 0. 0. 0.]
[ 0. 0. 0. 0.]
[ 0. 0. 0. 0.]]
[[ 2. 2. 2. 2.]
[ 2. 2. 2. 2.]
[ 2. 2. 2. 2.]
[ 2. 2. 2. 2.]]]]

And I understand now that it is not the same deconvolution operation as CAFFE deconvolution, 
so I will probably have to implement it myself.

**Comment by shaharf1** [comment]
Perhaps there is a way to reshape the weights for the general case.
I am thinking.....

**Comment by GeorgeARM** [comment]
Hello @shaharf1 ,

Are you sure that the shapes you provided us with are correct?
Can you give us the caffe example code that you are trying to port?

**Comment by shaharf1** [comment]
Hi,
Let me clarifiy...
The weights you gave me are good, but only for this specific case.
When I change the input values I still don't get a good result.

The caffe example is here:
[caffe.zip](https://github.com/ARM-software/ComputeLibrary/files/1806321/caffe.zip)

Thanks.

**Comment by mpekatsoula** [comment]
In your .prototxt file you have set the optional parameter group to 2. In your above example, this will separate input and output into 2 groups and perform deconvolution in each group. Unfortunately, this is not supported by Compute Library.

You could do this separation yourself, for example, create two  4x2x1 inputs, two 4x4x1x1 weight tensors and two 8x4x1 output tensors and perform two deconvolution operations.

**Comment by shaharf1** [comment]
Thanks.
I understand that, but even for the simpler case of one group and one output, the weights need some transoframtion.

For example:
Input:
[[[[ 1.  1.  1.  1.]
   [ 1.  1.  1.  1.]]]]
kernel: 
[[[[ 1.  2.  1.  1.]
   [ 1.  1.  1.  1.]
   [ 1.  1.  1.  1.]
   [ 1.  1.  1.  1.]]]]
output: 
[[[[ 1.  2.  2.  2.  2.  2.  2.  1.]
   [ 3.  4.  5.  4.  5.  4.  5.  2.]
   [ 2.  4.  4.  4.  4.  4.  4.  2.]
   [ 1.  2.  2.  2.  2.  2.  2.  1.]]]]


So, if I want to use your deconvolution, I need to generalize the transformation of the weights, 

Here is the CAFFE code.
[caffe.zip](https://github.com/ARM-software/ComputeLibrary/files/1807101/caffe.zip)


Shahar.

**Comment by shaharf1** [comment]
Actually, 
I can already tell that we need to transpose the weights matrix.
But it is still not enough....:)

**Comment by shaharf1** [comment]
Hi,
Let's leave the CAFFE deconvolution for now.

I read about your approach in http://deeplearning.net/software/theano/tutorial/conv_arithmetic.html#transposed-convolution-arithmetic.
I sill don't fully understand your calculation.

With pad=2 and stride=2,  
input data:
[[[[ 1.  1.  1.  1.]
   [ 1.  1.  1.  1.]]]]
kernel: 
[[[[ 1.  1.  1.  1.]
   [ 1.  1.  1.  1.]
   [ 1.  1.  1.  1.]
   [ 1.  1.  2.  1.]]]]

I would expect this output : 
[[[[ 1.  2.  2.  2.  2.  2.  2.  1.]
   [ 3.  4.  5.  4.  5.  4.  5.  2.]
   [ 2.  4.  4.  4.  4.  4.  4.  2.]
   [ 1.  2.  2.  2.  2.  2.  2.  1.]]]]

However, with your deconvolution I get 

[[2.0000000   3.0000000   3.0000000   3.0000000   3.0000000   3.0000000   3.0000000   2.0000000   ]
[4.0000000   5.0000000   6.0000000   5.0000000   6.0000000   5.0000000   6.0000000   3.0000000   ]
[3.0000000   5.0000000   5.0000000   5.0000000   5.0000000   5.0000000   5.0000000   3.0000000   ]
[2.0000000   3.0000000   3.0000000   3.0000000   3.0000000   3.0000000   3.0000000   2.0000000   ]
]

As you can see, there is a difference of '1' between the output I see and what I would expect.
Can you explain?

Thanks.

**Comment by mpekatsoula** [comment]
So, the idea is that the input is upsampled by inserting N = (stride - 1) zeroes in the input (ans also insert padding) and then we apply a normal convolution pass with stride = 1.

In your case, the input data with pad=2 and stride=2 will become:
[[[[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0. 0. 1. 0. 1. 0. 1. 0. 1. 0. 0.]
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0. 0. 1. 0. 1. 0. 1. 0. 1. 0. 0.]
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]]

and then a convolution pass is applied with your kernel. For example, the first element of the output is the convolution of:
[0. 0. 0. 0.
 0. 0. 0. 0.
 0. 0. 1. 0.
 0. 0. 0. 0.]
       *
[ 1. 1. 1. 1.]
[ 1. 1. 1. 1.]
[ 1. 1. 1. 1.]
[ 1. 1. 2. 1.]

which will give 1.

I don't know why you got 2 as the first element, are you sure you don't add any bias? I just run an example with the exact same input and got:
1 2 2 2 2 2 2 1 
3 4 5 4 5 4 5 2 
2 4 4 4 4 4 4 2 
1 2 2 2 2 2 2 1

**Comment by shaharf1** [comment]
I am checking. I still can't find anything wrong with my code.

I definitely see that the bias comes from the first input element.

For example,
With this input:
[[[[ 100. 1. 1. 1.]
       [ 1. 1. 1. 1.]]]]

I get this output:
[[200.0000000   201.0000000   201.0000000   102.0000000   102.0000000   102.0000000   102.0000000   101.0000000   ]
[202.0000000   203.0000000   204.0000000   104.0000000   105.0000000   104.0000000   105.0000000   102.0000000   ]
[201.0000000   203.0000000   203.0000000   104.0000000   104.0000000   104.0000000   104.0000000   102.0000000   ]
[101.0000000   102.0000000   102.0000000   102.0000000   102.0000000   102.0000000   102.0000000   101.0000000   ]
]

If you know about such an issue, please let me know.
Thanks.

**Comment by mpekatsoula** [comment]
Can you please share your code? I tried again with your new input and got:
100 101 101   2   2   2   2   1 
102 103 104   4   5   4   5   2 
101 103 103   4   4   4   4   2 
  1   2   2   2   2   2   2   1 

which looks correct.

Thanks

**Comment by shaharf1** [comment]
Here is my full code. Sorry if it is a little messy....


[acl_gpu_nfd_cnn.zip](https://github.com/ARM-software/ComputeLibrary/files/1807961/acl_gpu_nfd_cnn.zip)

Anyway, in my code I add a 0 bias.
And I see that when I remove the 0 bias, this problem disappears.
So perhaps I don't configure the bias correctly.

**Comment by shaharf1** [comment]
Can try adding a zero bias in your code and see what happens?

**Comment by mpekatsoula** [comment]
I ran your code and got correct results. You had an error in line 232:
`const TensorShape deconv_weights_tensor_shape(deconv_p_kernel_size, deconv_p_kernel_size,(long unsigned int)2 , deconv_p_num_outpus);`
this needs to be 
`const TensorShape deconv_weights_tensor_shape(deconv_p_kernel_size, deconv_p_kernel_size,(long unsigned int)1 , deconv_p_num_outpus);`
as it is the OFM.

Make sure you compile with asserts=1 as there was an error thrown there. This way you'll make sure that your code is correct :)

**Comment by shaharf1** [comment]
OK. 
Thanks a lot :)

**Comment by mpekatsoula** [comment]
Marking this as solved, reopen if needed.
