### ISSUE TITLE
getting current tensor shape in graph API

### ISSUE THREAD

**Issue by bubbles1990** [ARM-software/ComputeLibrary#382]
Hi,

I was wandering if it's possible to get current output tensor shape in the Graph API, for example:

        Graph graph{};
        graph << Tensor(TensorInfo(TensorShape(...)));
        graph << ConvolutionLayer(...);
        graph << ConvolutionLayer(...);
        // some more layers here
        graph << ConvolutionLayer(...);
        
        // here I want to know the shape of the current output tensor
        TensorShape output_shape = ???
        
        // then there might be some more layers
        graph << ConvolutionLayer(...);
        graph << ConvolutionLayer(...);

Thank you

**Comment by AnthonyARM** [comment]
1) If you're running in debug mode, the graph builder will output the full configuration of each layer created, so you can get the dimensions from there.
2) If, for debug purposes, you need to find the dimensions in the code, you could make your network end wherever you want the dimensions of the tensor and add a Tensor() node with an accessor.

**Comment by dcsgan** [comment]
Can you please explain in little detail 
graph << target_hint
              << convolution_hint
              << Tensor(TensorInfo(TensorShape(spatial_size, spatial_size, 3U, 1U), 1, DataType::F32),
                        get_input_accessor(image, std::move(preprocessor), false))
              << ConvolutionLayer(
                  3U, 3U, 32U * depth_scale,
                  get_weights_accessor(data_path, "Conv2d_0_weights.npy"),
                  std::unique_ptr<arm_compute::graph::ITensorAccessor>(nullptr),
                  PadStrideInfo(2, 2, 0, 1, 0, 1, DimensionRoundingType::FLOOR))
              << BatchNormalizationLayer(
                  get_weights_accessor(data_path, "Conv2d_0_BatchNorm_moving_mean.npy"),
                  get_weights_accessor(data_path, "Conv2d_0_BatchNorm_moving_variance.npy"),
                  get_weights_accessor(data_path, "Conv2d_0_BatchNorm_gamma.npy"),
                  get_weights_accessor(data_path, "Conv2d_0_BatchNorm_beta.npy"),
                  0.001f, ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::BOUNDED_RELU, 6.f));

if I want to get the tensor info after  BatchNormalizationLayer, what should i do ?
