### ISSUE TITLE
Tensor dimension mismatch in NPYLoader

### ISSUE THREAD

**Issue by ymbaek** [ARM-software/ComputeLibrary#384]
Hello.
I am dumping tensorflow trained data using NPYLoader. and I have some difficulty to understand Tensor dimension in ACL.

According to the document and example in ACL, the tensor dimension definition of ACL is [width, height, feature maps, batches]. However, same dimension numpy array cannot be loaded by NPYLoader cause of the dimension mismatch.

The tensor dimension def. of Tensorflow and Numpy is [H, W, ifm, ofm].
For example, If I have the tensor with the shape of row(H) 2 and col(W) 3, I can extract numpy array with the same shape of row(H) 2 and col(W) 3. However, I should make the ACL tensor with shape of col(W) 2, row(H) 3 to upload this into ACL. id.x() range is from 0 to 2 and id.y() range is from 0 to 3.

The document is wrong? and id.x() actually notice the index of HEIGHT?
Or should I transpose my numpy data to load in ACL?

Many Thanks.

**Comment by giorgio-arena** [comment]
Hi @ymbaek 

The NPYLoader assumes that the layout is NCHW (ofm, ifm, height, width) and therefore will read your layout in reverse. If you want to go that route, you should transpose your matrix to fit this layout.

E.g.
```
// example.py

import numpy as np

tensor = np.matrix([[1, 2, 3],
                    [4, 5, 6]], dtype='float32')

tensor_transp = np.transpose(tensor, (1, 0))

np.save('example_matrix.npy', tensor_transp)
```

```
// example.cpp

Tensor    src;
NPYLoader npy_loader;
        
src.allocator()->init(TensorInfo(TensorShape(3U, 2U), 1, DataType::F32));
src.allocator()->allocate();
        
npy_loader.open("example_matrix.npy");
npy_loader.fill_tensor(src);
        
src.print(std::cout);
```

```
// output
1 2 3 
4 5 6
```

Hope this helps!

**Comment by ymbaek** [comment]
Hello @giorgio-arena,
Thank you very much. It help me very materially!

Now, my ACL CNN out_act is perfectly matched with tensorflow tensor dummy.

Many thanks.
