### ISSUE TITLE
fail to run examples/gc_dc.cpp

### ISSUE THREAD

**Issue by huanyingjun** [ARM-software/ComputeLibrary#385]
Hi,
When I run examples/gc_dc.cpp on Android, I get below issue:
ERROR in update_shader_params src/core/GLES_COMPUTE/GCKernelLibrary.cpp:181: Arguments size (120) is not equal to shader params block size (128)

 Could you please help check this ?

**Comment by AnthonyARM** [comment]
Please, provide the information requested by the template, without it we cannot investigate the issue

**Comment by GeorgeARM** [comment]
Closing issue. Not enough information. Reopen if needed.
