### ISSUE TITLE
Has anybody tried running ACL on RK3288? 

### ISSUE THREAD

**Issue by wjtan99** [ARM-software/ComputeLibrary#386]
**ERROR: The DDK is not compatible with any GPU on the system
The DDK was built for ox750 r0p0 status range [1..1], but one of the GPU matched:
/dev/mali0 detected is 0x750 status 0
terminate called after throwing an instance of \cl:Error'
  what():  empty 
Abort (core dumped) 
**

**Platform:RK3288**

**Operating System: Ubuntu 16.04**

Does anybody have any idea?

**Comment by AnthonyARM** [comment]
Where did you get the libmali.so / libOpenCL.so from ? Looks like the driver doesn't match the GPU you've got on your platform

**Comment by Bo331429856** [comment]
@wjtan99, have you run ACL on RK3288? Can you share the performance of mobilenet for one forwarding with GPU?

**Comment by psyhtest** [comment]
@Bo331429856 Would you be interested in MobileNets performance on RK3399? I should be able to benchmark it within a week or so.

**Comment by wjtan99** [comment]
Benchmark of Mobilenet can be found here  https://github.com/merrymercy/tvm-mali.  I am more interested in RK3288 for its low cost. Earlier I asked about why it could not run.  Thank @AnthonyARM for giving good hint. Later we found it was a libmali.so issue.  We still have not made ACL fully work yet on RK3288.   If anybody does, please share with us.   Thanks

**Comment by AnthonyARM** [comment]
@wjtan99 Performance on RK3288 is unlikely to be great as the GPU on it is fairly old and the only publicly available drivers are quite old too.
The userspace drivers are available here: https://developer.arm.com/products/software/mali-drivers/user-space
And you will need to build the corresponding kernel modules for it: https://developer.arm.com/products/software/mali-drivers/midgard-kernel

Hope this helps
