### ISSUE TITLE
How to set multithreading ?

### ISSUE THREAD

**Issue by WenguoLi** [ARM-software/ComputeLibrary#387]
How to set multithreading when executing  a  NN graph ?

**Comment by AnthonyARM** [comment]
Currently the Graph API doesn't set the number of threads, so you need to do it like you would do it if it was a regular NEON test:
```cpp
#include "arm_compute/runtime/Scheduler.h"

...

Scheduler::get().set_num_threads(options.threads->value());
```

**Comment by WenguoLi** [comment]
@AnthonyARM Thanks

**Comment by GeorgeARM** [comment]
Closing issue. Reopen if needed
