### ISSUE TITLE
Plaforms on which ARM Compute Mali version can be tested?

### ISSUE THREAD

**Issue by mkamrao** [ARM-software/ComputeLibrary#388]
I would like to know, if you could suggest any ARM Mali based platforms/boards for verifying the applications using ARM Compute Library Mali version. I am looking for Android, Linux based plaforms/boards. 
Also, is there any dependency on OpenCL driver on the platform - if so, which version is recommended? Could you suggest platforms with inbuilt OpenCL support needed for ARM Compute Library.

Thanks 
Kamrao

**Comment by psyhtest** [comment]
@mkamrao I'd recommend [Firefly-RK3399](http://wiki.t-firefly.com/index.php/Firefly-RK3399/en). It's  stable, relatively cheap, has good community support and can be flashed with both Linux and Android. As of yesterday, I'm running the [Firefly-RK3399_xubuntu1604_201711301130](https://drive.google.com/drive/folders/1lbaR7XVyHT4SnXkJ2ybj5YXAzAjDBWfT) image which comes with OpenCL support!

You can find some public benchmarking results of Caffe [here](https://github.com/dividiti/ck-caffe-firefly-rk3399/).

HTH.

**Comment by psyhtest** [comment]
By the way, more benchmarking results [are coming soon](https://github.com/ctuning/ck-request-asplos18-mobilenets-tvm-arm/issues/5) from a [public TVM-based artifact](https://github.com/ctuning/ck-request-asplos18-mobilenets-tvm-arm) submitted to the [1st Reproducible Tournament on Pareto-efficient Image Classification](http://cknowledge.org/request-cfp-asplos2018.html) as ASPLOS'18.
