### ISSUE TITLE
clconvolution example issues

### ISSUE THREAD

**Issue by kananaskis** [ARM-software/ComputeLibrary#39]
hi all,
i try to run the example of clconvolution.cpp, but i meet something problem like bug.
if the climage format is u8, the result ppm image is fine.
but when the format is rgb888, it return a wrong result contain stripes .
any one meet the same problem? th.

**Comment by AnthonyARM** [comment]
Hi,
That's because CLConvolution only supports single channel U8 format (cf [Documentation](https://arm-software.github.io/ComputeLibrary/v17.04/classarm__compute_1_1_c_l_convolution3x3.xhtml#a26e1b4686b1f2d591d62d11585114a82) )

**Comment by kananaskis** [comment]
thanks @AnthonyARM ,  I wonder is the Data types supported: U8. or Format:U8？

**Comment by AnthonyARM** [comment]
A Format is just a Data Type + a number of channels.

> Unless specified otherwise in the kernel's or function's documentation the number of channels for tensors is expected to be 1 (For images, the number of channels is inferred from the Format).

[Documentation](https://arm-software.github.io/ComputeLibrary/v17.04/index.xhtml#S4_6_3_description_conventions)

Which means most of the time Format::U8 == DataType::U8

Does this make sense ?
