### ISSUE TITLE
dilated convolution support

### ISSUE THREAD

**Issue by Subarukun** [ARM-software/ComputeLibrary#390]
Hi,

Is there any plan to support dilated convolution layer on arm-neon. It would be really useful to run the waveNet kind of networks.

Thanks

**Comment by GeorgeARM** [comment]
Hello @Subarukun,

Yes we have this in our backlog don't though when it will be scheduled.

**Comment by GeorgeARM** [comment]
Closing issue. Dilated convolution was added in 18.05.
