### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by op21beyond** [ARM-software/ComputeLibrary#391]
Hi.

ACL seems to use large dynamic memory when compared with Tensorflow Lite.
In case of GoogLenet, Tensorflow Lite consumes 60MB. But for ACL graph.run(), it is 240MB. Why is it so? and can we expect this can be optimized soon?

Thanks

**Comment by GeorgeARM** [comment]
Hello @op21beyond,

Yes we are working on this. Hopefully in the next release there will be some improvements there.

**Comment by GeorgeARM** [comment]
Hello @op21beyond,

If you use the graph API you should get reduced memory.
ACL will consume a bit more memory in the beginning as it needs to reshape some matrices but after that the memory should drop. This can be optimized at graph level but our graph API is for testing purposes thus we haven't spend any time improving that even more.

Doing some runs GoogleNet for CL requires `Peak Memory :  87MB` and `Run Memory : 47MB` when I force `GEMM` to be the default convolution method. If I leave the graph to optimize the selection of the convolution methods the memory requirements increase to `Peak Memory :  117MB` and `Run Memory : 85MB` as Winograd based convolutiond require more memory for the transformations.

`Peak Memory` is the memory required to construct and prepare the network.
`Run Memory` is the memory consumed once the network is prepared.
