### ISSUE TITLE
GLES lenet5 does not work

### ISSUE THREAD

**Issue by pcub** [ARM-software/ComputeLibrary#393]
**Platform:**
aarch64
**Operating System:**

android

**Problem description:**
I am testing non-graph lenet5 example (i.e., LeNet5Network.h)
I compiled with -DARM_COMPUTE_GC flag with cmake.
when all datatype are CL* it works and if all datatype are GC* and GLES lenet5 gives following error:

terminate called after throwing an instance of 'std::runtime_error'
  what():  in GLuint arm_compute::GCProgram::compile_shader(const std::string &) src/core/GLES_COMPUTE/GCKernelLibrary.cpp:123: Error: Compiler log:
what is the problem?

**Comment by AnthonyARM** [comment]
Does it work when compiling with SCons ?

The Graph example is the most up to date version of the code, the non-graph version is a legacy test which will be removed soon.

**Comment by pcub** [comment]
I am not using gles anymore.
Is it possible to use mixed mode (i.e., neoncl_scale_median_gaussian) in graph version of examples?

**Comment by AnthonyARM** [comment]
Currently it *might* work if you change the target hint mid-stream, but in the next version it won't be supported anymore (That's not something we currently need for our testing and it added unnecessary complexity).

**Comment by GeorgeARM** [comment]
Closing issue. GLES backend is now supported in the graph. Lenet should work through graph examples
