### ISSUE TITLE
error: class 'numeric_limits' was previously declared as a struct 

### ISSUE THREAD

**Issue by zhaofenqiang** [ARM-software/ComputeLibrary#396]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v18.03 Build options: {'arch': 'armv7a', 'opencl': '1', 'neon': '1', 'debug': '0', 'os': 'linux', 'Werror': '1'} Git hash=3dd034f2356319ee1cff6bcad5c58ed8611ae26e

**Platform:**
Linux

**Operating System:**
Ubuntu 16.04

**Problem description:**
I have built ComputeLibrary for android using this command
```
CXX=clang++ CC=clang scons Werror=1 -j8 debug=0 asserts=1 neon=1 opencl=1 embed_kernels=1 os=android arch=armv7a
```
It's perfectly done without problem.

Then I needed to port ComputeLibrary onto [Paddle](https://github.com/PaddlePaddle/Paddle). I have included some ComputeLibrary's header file in this [file](https://github.com/zhaofenqiang/Paddle/blob/develop/paddle/gserver/layers/ACLOperator.hpp), as you can see,

> #include "arm_compute/runtime/NEON/functions/NEDepthConcatenateLayer.h"
#include "arm_compute/runtime/NEON/functions/NEConvolutionLayer.h"
#include "arm_compute/runtime/NEON/functions/NEDirectConvolutionLayer.h"
#include "arm_compute/runtime/NEON/functions/NEActivationLayer.h"
#include "arm_compute/runtime/NEON/functions/NENormalizationLayer.h"
#include "arm_compute/runtime/NEON/functions/NEPoolingLayer.h"
#include "arm_compute/runtime/NEON/functions/NESoftmaxLayer.h"
#include "arm_compute/runtime/NEON/functions/NEFullyConnectedLayer.h"
#include "arm_compute/runtime/NEON/functions/NELocallyConnectedLayer.h"
#include "arm_compute/runtime/NEON/functions/NEBatchNormalizationLayer.h"
#include "arm_compute/runtime/Tensor.h"
......

Then I used a [dockerfile](https://github.com/zhaofenqiang/Paddle/blob/develop/Dockerfile.android) to build Paddle for Android following this [guide](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/mobile/cross_compiling_for_android_en.md#cross-compiling-using-docker). After `docker run -it --rm -v $PWD:/paddle -e "ANDROID_ABI=armeabi-v7a" -e "ANDROID_API=21" paddle:dev-android`, I met this error:

> [ 52%] Building CXX object paddle/gserver/CMakeFiles/paddle_gserver.dir/activations/ActivationFunction.cpp.o
In file included from /paddle/paddle/gserver/activations/ActivationFunction.cpp:15:
In file included from /paddle/paddle/gserver/activations/ActivationFunction.h:17:
In file included from /paddle/paddle/gserver/layers/ACLOperator.hpp:3:
In file included from /paddle/ComputeLibrary/arm_compute/runtime/NEON/functions/NEDepthConcatenateLayer.h:29:
In file included from /paddle/ComputeLibrary/arm_compute/core/NEON/kernels/NEDepthConcatenateLayerKernel.h:28:
In file included from /paddle/ComputeLibrary/arm_compute/core/NEON/INEKernel.h:27:
In file included from /paddle/ComputeLibrary/arm_compute/core/CPP/ICPPKernel.h:28:
In file included from /paddle/ComputeLibrary/arm_compute/core/IKernel.h:27:
In file included from /paddle/ComputeLibrary/arm_compute/core/Types.h:33:
In file included from /paddle/ComputeLibrary/support/Half.h:36:
/paddle/ComputeLibrary/include/half/half.hpp:1081:10: error: class 'numeric_limits' was previously
      declared as a struct [-Werror,-Wmismatched-tags]
                friend class std::numeric_limits<half>;
                       ^
/opt/toolchains/arm-android-21/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../include/c++/4.9.x/limits:304:12: note: 
      previous use is here
    struct numeric_limits : public __numeric_limits_base
           ^

I was wondering if you guys know anything about this problem? Can you help me? Thank you very much.

**Comment by AnthonyARM** [comment]
Hi,
The error seems to be coming from `include/half/half.hpp` which is a third party header: http://half.sourceforge.net/
You might want to check on their website if there is any issue related to what  you've seen.
The problem might be coming from the Android STL library used (We recommend using gnustl),

**Comment by zhaofenqiang** [comment]
Thank you for your quick reply and valuable suggestions~

**Comment by Alicture** [comment]
@zhaofenqiang hi! Could you please tell me how to solve this problem?

**Comment by zhaofenqiang** [comment]
@Alicture ，hi, sorry, it's long time ago, I barely remember. Probably change the data type in the half library's header.
