### ISSUE TITLE
Group Convolution and batch processing

### ISSUE THREAD

**Issue by mkamrao** [ARM-software/ComputeLibrary#40]
Hello

I am trying to implement a neural n/w (similar to Alexnet) using the Convolution layer APIs for ARM Neon. Does the APIs in the Compute lib support Grouped Convolution and batch processing?
If so, can you clarify how to configure for grouped convolution and batch processing using the API.
Thank you.

Kamrao

**Comment by GeorgeARM** [comment]
Hello @mkamrao,

The library's Tensor object supports up to 6 dimensions, thus it does support batch processing (3D batch space) for the CNN layers.
If you define a TensorShape as:
```cpp
TensorShape shape(16 /* width */,16 /* height */,64 /* feature maps */,10 /* batches */);
```
you will have a tensor with 10 batches.
Grouped convolution is not yet supported in the current release but we are working on it.

Thanks
