### ISSUE TITLE
build library but always print "Cannot compile NEON for x86"

### ISSUE THREAD

**Issue by lebronze** [ARM-software/ComputeLibrary#405]
I followed the Compute Library  18.03 documents : " build for Android"  to configure everything in my computer, and i successfully configured everything.

Then i tried to build the library:
To cross-compile the library in debug mode, with NEON only support, for Android 32bit:
CXX=clang++ CC=clang scons Werror=1 -j8 debug=1 neon=1 opencl=0 os=android arch=armv7a

but error comes:  
    File "/home/qb/ComputeLibrary-master/SConstruct", line 74
    print "Cannot compile NEON for x86"
    SyntaxError: invalid syntax

I didn't use x86,  my commond is "arch=v7a"   !!
The i tried to make "neon=0", "arc=arm64-v8a".  However, the same mistake comes.

**Comment by AnthonyARM** [comment]
As you can see inside the [SConstruct file](https://github.com/ARM-software/ComputeLibrary/blob/master/SConstruct#L73) this error will only be printed if you're trying to compile with `neon=1` and `arch=x86_32` or `arch=x86_64`

Can you try to add a `print env['arch']` on line 72 to check which architecture is selected ?

**Comment by lebronze** [comment]
thank you very much!
 i tried print env['arch'], but error comes :

  File "/home/qubo/ComputeLibrary-master/SConstruct", line 72
    print env['arch']
           ^
SyntaxError: invalid syntax

is it possible that the version of python cause the mistake?

**Comment by AnthonyARM** [comment]
Possibly, I think SCons only works with python2, in `/usr/bin/scons` I've got:

```python
if sys.version_info >= (3,0,0):
    msg = "scons: *** SCons version %s does not run under Python version %s.\n\
Python 3 is not yet supported.\n"
    sys.stderr.write(msg % (__version__, sys.version.split()[0]))
    sys.exit(1)
```
So in theory it shouldn't run at all if all you've got on your system is python 3.

**Comment by lebronze** [comment]
Em, i check my computer and find the version of python in my computer is python 2.7.
I don't konw why this error: SyntaxError: invalid syntax  comes.

**Comment by lebronze** [comment]
oh， i solved this problem by  change:   print "Cannot compile NEON for x86"   into   print("Cannot compile NEON for x86")  in the file SConstruct.
It's about the usage of print in Python.

**Comment by AnthonyARM** [comment]
No, it's definitely something to do with the version of python you're using
In my case if I add
```python
import sys
print sys.version
```
Then I get:
```
scons: Reading SConscript files ...
2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609]
Cannot compile NEON for x86
```

**Comment by lebronze** [comment]
Thank you very much for answering again!
I tried as you suggested: 
`import sys
print sys.version`

And I get:
`scons: Reading SConscript files ...

2.7.6 (default, Oct 26 2016, 20:30:19) 

[GCC 4.8.4]

scons: done reading SConscript files.`

I still think this problem is about the version of Python and the usage of "print" in Python.
And i find two diferent ways of using the function print : 
`print(`` " **** " )`
and 
`print " **** "` in SConstruct.
 I think if we could unify the usage of print, maybe we can avoid this problem.

In addition, if i want to use ACL in my android project, what do i need to do?
I include "libarm_compute.so", "libarm_compute_core.so" , "libarm_compute_graph.so" and some headers in my project.
 I don‘t know do i need to include "opencl-1.2-stubs/libOpenCL.so" or something else in my project? When i want to use opencl but my cellphone only support opencl1.1.

**Comment by AnthonyARM** [comment]
Odd, I thought `print "..."` was the python2 way and `print(...)` the python3 way.

Regarding Android Studio: have you checked https://github.com/ARM-software/ComputeLibrary/issues/137 ?

It might be related to the API level you target for your app (If it's 23 or lower you should be able to link against OpenCL otherwise you rely on the manufacturer to have whitelisted the OpenCL library)
