### ISSUE TITLE
Box filter difference with NEON and ACL GPU code (ACL version 17.10)

### ISSUE THREAD

**Issue by vinithsrvv1** [ARM-software/ComputeLibrary#407]
Hi Sir, 

We are executing box filter kernel in arm compute library. WE are getting proper output in ARM NEON , but when executed in ARM GPU, we are getting the mismatch. Attaching the stand alone workspace and logs for reference. 

Version: 17.10 

Please let us know your inputs in resolving this issue
Thanks in advance. 

Thanks,
Vinith 
[acl_neonoutput.txt](https://github.com/ARM-software/ComputeLibrary/files/1886084/acl_neonoutput.txt)
[box_aclgpu_issue.txt](https://github.com/ARM-software/ComputeLibrary/files/1886085/box_aclgpu_issue.txt)

[cl_box.txt](https://github.com/ARM-software/ComputeLibrary/files/1886087/cl_box.txt)

**Comment by AnthonyARM** [comment]
I'm confused: everything in box_aclgpu_issue.txt looks fine: you selected "UNDEFINED" for the border mode, therefore the first & last row & column are removed, all the other values look good.

Where does acl_neonoutput.txt come from ? I'm not sure what these values are supposed to be ?

**Comment by vinithsrvv1** [comment]
Hi Sir, 

Thanks for the update . in file box_aclgpu_issue.txt,

Reference output: which is NEON output
108 132 100 142 133 167 125 116 91  102 101 146 171 177
124 150 129 151 134 136 99  81  72  74  58  90  126 163
125 142 121 144 140 133 91  60  64  78  93  123 143 159
139 136 135 159 159 149 99  89  81  100 122 123 150 136
108 110 136 163 187 171 139 110 108 119 148 138 136 127
121 115 151 167 180 165 142 148 124 124 129 133 146 146
144 148 164 160 177 161 157 144 139 135 140 134 120 149
123 135 125 132 131 155 139 142 108 126 133 142 131 145
95  107 95  102 98  139 133 152 132 161 145 111 83  100
94  110 84  83  66  110 112 147 123 133 118 113 108 118
112 115 79  69  84  99  137 160 147 111 101 117 127 143
111 124 106 92  92  77  126 130 125 74  102 148 165 150
95  91  92  94  105 87  141 139 142 101 114 128 130 126
108 115 136 144 137 121 133 120 110 93  127 134 130 111

Target output :GPU output
125 125 128 123 156 175 139 107 97  89  93  128 172 177
109 119 138 122 131 138 95  72  74  60  53  88  140 163
144 146 149 141 147 129 72  52  74  86  84  103 136 155
147 131 129 150 173 160 111 72  76  100 129 153 152 147
102 105 119 169 186 160 142 117 103 115 141 143 127 134
106 136 138 184 201 153 144 150 127 130 143 119 118 147
157 170 135 167 186 149 157 162 121 123 146 137 146 169
145 151 117 138 145 134 161 144 105 129 153 127 117 139
85  100 91  96  106 121 147 132 117 150 158 103 79  107
99  106 76  68  80  94  134 154 144 143 138 102 90  119
140 133 82  70  78  86  123 164 140 90  91  124 133 144
123 108 93  92  91  100 118 156 131 65  83  158 169 140
98  82  109 113 89  89  117 150 131 97  115 154 146 114
111 97  122 139 117 113 135 137 115 107 120 125 104 104

You may ignore acl_neonoutput.txt,. Please let me know if you need any clarification

**Comment by AnthonyARM** [comment]
Same here: on hikey it works
```
root@acl_hikey_dev:~/tmp/antbar01/release/build/linux-arm64-v8a-neon-cl-debug# LD_LIBRARY_PATH=. ./examples/cl_box 16 16 3

./examples/cl_box

width 16 height 16

******Input Image ******* 
103 198 105 115  81 255  74 236  41 205 186 171 242 251 227  70 
124 194  84 248  27 232 231 141 118  90  46  99  51 159 201 154 
102  50  13 183  49  88 163  90  37  93   5  23  88 233  94 212 
171 178 205 198 155 180  84  17  14 130 116  65  33  61 220 135 
112 233  62 161  65 225 252 103  62   1 126 151 234 220 107 150 
143  56  92  42 236 176  59 251  50 175  60  84 236  24 219  92 
  2  26 254  67 251 250 170  58 251  41 209 230   5  60 124 148 
117 216 190  97 137 249  92 187 168 153  15 149 177 235 241 179 
  5 239 247   0 233 161  58 229 202  11 203 208  72  71 100 189 
 31  35  30 168  28 123 100 197  20 115  90 197  94  75 121  99 
 59 112 100  36  17 158   9 220 170 212 172 242  27  16 175  59 
 51 205 227  80  72  71  21  92 187 111  34  25 186 155 125 245 
 11 225  26  28 127  35 248  41 248 164  27  19 181 202  78 232 
152  50  56 224 121  77  61  52 188  95  78 119 250 203 108   5 
172 134  33  43 170  26  85 162 190 112 181 115  59   4  92 211 
 54 148 179 175 226 240 228 158  79  50  21  73 253 130  78 169 


******Output Image ******* 
108 132 100 142 133 167 125 116  91 102 101 146 171 177 
124 150 129 151 134 136  99  81  72  74  58  90 126 163 
125 142 121 144 140 133  91  60  64  78  93 123 143 159 
139 136 135 159 159 149  99  89  81 100 122 123 150 136 
108 110 136 163 187 171 139 110 108 119 148 138 136 127 
121 115 151 167 180 165 142 148 124 124 129 133 146 146 
144 148 164 160 177 161 157 144 139 135 140 134 120 149 
123 135 125 132 131 155 139 142 108 126 133 142 131 145 
 95 107  95 102  98 139 133 152 132 161 145 111  83 100 
 94 110  84  83  66 110 112 147 123 133 118 113 108 118 
112 115  79  69  84  99 137 160 147 111 101 117 127 143 
111 124 106  92  92  77 126 130 125  74 102 148 165 150 
 95  91  92  94 105  87 141 139 142 101 114 128 130 126 
108 115 136 144 137 121 133 120 110  93 127 134 130 111 


Test passed
```
Which platform are you running on ? Looks like the OpenCL driver isn't working as expected

**Comment by vinithsrvv1** [comment]
Rebotted and reflashed the board. Issue is not observed. Closing this issue . Will update you if any clarification required
