### ISSUE TITLE
how to extract the data of hog descriptor in tensor?

### ISSUE THREAD

**Issue by chenkezhe** [ARM-software/ComputeLibrary#41]
Hello everyone,
     Now I have trouble with the NEHOGDescriptor function, the function runs ok, but I can't find the way to extract it's result data. Could you help me? Thanks.

best wishes!

**Comment by steniu01** [comment]
@chenkezhe  you just extract the data from the final output data. Depends on what format you want extract to, here is a code I used to extract the output tensor to dlib  dlib::array<dlib::array2d<float>> format. 

void hog_convert_tensor_to_array2d(arm_compute:ITensor* src,     dlib::array2d<dlib::matrix<float, n_channel,1>> dlib_hog)
{
    TensorInfo* info = src->info();
    size_t n_channel = info->num_channels();
    size_t width = info->dimension(0);
    size_t height = info->dimension(1);

    // Map tensor to access in host
    src->map(true /* blocking */);

    Window src_window;
    src_window.use_tensor_dimensions(src->info()->tensor_shape(), /* first_dimension =*/Window::DimX); 

    // Create an iterator:
    Iterator src_it(src, src_window);

    dlib_hog.set_size(height, width);

    // Iterate through the rows of the src tensor and copy data to them:
    execute_window_loop(src_window, [&](const Coordinates & id)
    {
        // Copy one whole channel
        float* ptr = reinterpret_cast<float*> (src_it.ptr());
      
      // here it iterate channel by channel. Ideally, it should do a blocking copy
        for (int i = 0; i < n_channel; i++)
        {
            dlib::assign_pixel(dlib_hog[id.y()][id.x()](i), *(ptr + i));
        }
    },
    src_it);
    // Unmap tensor to access in host
    src->unmap();
}
