### ISSUE TITLE
Magnitude kernel crash in GPU in ACL 17.10 - Request for inputs

### ISSUE THREAD

**Issue by vinithsrvv1** [ARM-software/ComputeLibrary#410]
Hi Sir, 

When executing Magnitude kernel for GPU in Armcompute library, it is resulting in crash in configuring the magnitude kernel. Attaching the logs, stand alone workspace for reference. 

Version: 17.10 

Please help us in resolving this issue.
[cl_magnitude_standalone_32x32 _log.txt](https://github.com/ARM-software/ComputeLibrary/files/1886255/cl_magnitude_standalone_32x32._log.txt)
[cl_magnitude_32x32_api.txt](https://github.com/ARM-software/ComputeLibrary/files/1886256/cl_magnitude_32x32_api.txt)

Thanks,
Vinith

**Comment by GeorgeARM** [comment]
Closing issue. No issues are reported from our test infrastructure. Try 18.05 and make sure your driver is fine.
