### ISSUE TITLE
Mean and SD GPU crash in Arm compute version 17.10 - Request for inputs 

### ISSUE THREAD

**Issue by vinithsrvv1** [ARM-software/ComputeLibrary#411]
Hi Sir,

When executing Mean and SD kernel for GPU in Armcompute library, it is resulting in crash in configuring the Mean and SD 
[cl_meanstddev_log.txt](https://github.com/ARM-software/ComputeLibrary/files/1886268/cl_meanstddev_log.txt)
[cl_meanstddev_api.txt](https://github.com/ARM-software/ComputeLibrary/files/1886269/cl_meanstddev_api.txt)

kernel. Attaching the logs, stand alone workspace for reference.

Version: 17.10

Please help us in resolving this issue.

Thanks,
Vinith

**Comment by GeorgeARM** [comment]
Closing issue. No issues are reported from our test infrastructure. Try 18.05 and make sure your driver is fine. Reopen in case of more information.

**Comment by manjunathahg** [comment]
Hi @GeorgeARM can you please reopen the issue as we are still seeing crash in 18.05.
Attaching stand alone work space and log.
[cl_meanstddev_api_18.05.txt](https://github.com/ARM-software/ComputeLibrary/files/2183249/cl_meanstddev_api_18.05.txt)
[meanstddev_log.txt](https://github.com/ARM-software/ComputeLibrary/files/2183250/meanstddev_log.txt)
Thank you

**Comment by AnthonyARM** [comment]
The problem comes from your OpenCL driver: `clCreateKernel` fails with this reason:
```
meanStdDevObj.configure
BC-src-code:408:49: error: Calling atom_add requires that the cl_khr_global_int32_base_atomics extension is enabled.
     atom_add(global_sum, tmp_sum.s0 + tmp_sum.s1);
                                                 ^
BC-src-code:408:5:{408:5-408:13}: error: no matching builtin function for call to 'atom_add'
     atom_add(global_sum, tmp_sum.s0 + tmp_sum.s1);
     ^~~~~~~~
BC-src-code:413:58: error: Calling atom_add requires that the cl_khr_global_int32_base_atomics extension is enabled.
     atom_add(global_sum_sq, tmp_sum_sq.s0 + tmp_sum_sq.s1);
                                                          ^
BC-src-code:413:5:{413:5-413:13}: error: no matching builtin function for call to 'atom_add'
     atom_add(global_sum_sq, tmp_sum_sq.s0 + tmp_sum_sq.s1);
     ^~~~~~~~
4 diagnostic(s) generated.

!!!!!!!!!!!!!!!!!!!!!!!!!!!

ERROR clCreateKernel(-45)
!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
But if you look at the top of the kernel's file, the extension **is** enabled: https://github.com/ARM-software/ComputeLibrary/blob/master/src/core/CL/cl_kernels/mean_stddev.cl#L26
```cpp
#pragma OPENCL EXTENSION cl_khr_int64_base_atomics : enable
#pragma OPENCL EXTENSION cl_khr_int64_extended_atomics : enable
```
The only thing that is missing on our side is an assert in `CLMeanStdDevKernel::configure" when the extension is not present. (It's already been added and will be part of the next release)
