### ISSUE TITLE
Phase kernel GPU crash in Arm compute version 17.10 - Request for inputs

### ISSUE THREAD

**Issue by vinithsrvv1** [ARM-software/ComputeLibrary#412]
Hi Sir,

When executing Phase kernel for GPU in Armcompute library, it is resulting in crash in configuring the Phase
[cl_phase_api.txt](https://github.com/ARM-software/ComputeLibrary/files/1886277/cl_phase_api.txt)
[cl_phase_32x32_logs.txt](https://github.com/ARM-software/ComputeLibrary/files/1886278/cl_phase_32x32_logs.txt)

 kernel. Attaching the logs, stand alone workspace for reference.

Version: 17.10

Please help us in resolving this issue.

Thanks,
Vinith

**Comment by GeorgeARM** [comment]
Closing issue. No issues are reported from our test infrastructure. Try 18.05 and make sure your driver is fine. Reopen in case of more information.
