### ISSUE TITLE
not find “libarm_compute.so”

### ISSUE THREAD

**Issue by lebronze** [ARM-software/ComputeLibrary#415]
I successfully build ACL and get libarm_compute.so,  libarm_compute_core.so.
Then i use Android Studio to include this two files in my project, and include correspondent header files.
But error comes in Android Studio :  not find “libarm_compute.so” . I check the path but it is correct.

So is there anyone knows how to use ACL in Android project?   Please help me, thanks.

**Comment by AnthonyARM** [comment]
We don't use Android Studio internally, but have you checked #137 ?

Also, are you sure you've compiled arm_compute for the correct architecture ?
