### ISSUE TITLE
Non Linear Filter ACL GPU output mismatch with ACL Neon(ACL 17.10) - Request for inputs

### ISSUE THREAD

**Issue by vinithsrvv1** [ARM-software/ComputeLibrary#416]
Hi Sir, 

When executing non linear filter kernel, we are getting GPU hang. NEON output is matching with reference implementation (OpenVx C model) . Attaching the logs , sample workspace for reference. 

Can you please help in resolving
[NonLinearFilter_gpu_op_not _matching_neon_for_min_and_max_kernels_border_constant_and_replicate_mode.txt](https://github.com/ARM-software/ComputeLibrary/files/1888760/NonLinearFilter_gpu_op_not._matching_neon_for_min_and_max_kernels_border_constant_and_replicate_mode.txt)
[cl_nonlinearfilter_test.txt](https://github.com/ARM-software/ComputeLibrary/files/1888761/cl_nonlinearfilter_test.txt)

 this issue? 

Thanks,
Vinith

**Comment by manjunathahg** [comment]
Hi team, 
any update on the above issue?

**Comment by AnthonyARM** [comment]
Once again, this looks like a problem with your platform, if I download the file you've provided and compile it as-is, I get the following output:
```
root@acl_hikey_3:~/tmp/antbar01/stock/build/linux-arm64-v8a-cl-debug# LD_LIBRARY_PATH=. ./examples/cl_nonlinear 16 16

./examples/cl_nonlinear

Max Kernel

******Input Image ******* 
103 198 105 115  81 255  74 236  41 205 186 171 242 251 227  70 
124 194  84 248  27 232 231 141 118  90  46  99  51 159 201 154 
102  50  13 183  49  88 163  90  37  93   5  23  88 233  94 212 
171 178 205 198 155 180  84  17  14 130 116  65  33  61 220 135 
112 233  62 161  65 225 252 103  62   1 126 151 234 220 107 150 
143  56  92  42 236 176  59 251  50 175  60  84 236  24 219  92 
  2  26 254  67 251 250 170  58 251  41 209 230   5  60 124 148 
117 216 190  97 137 249  92 187 168 153  15 149 177 235 241 179 
  5 239 247   0 233 161  58 229 202  11 203 208  72  71 100 189 
 31  35  30 168  28 123 100 197  20 115  90 197  94  75 121  99 
 59 112 100  36  17 158   9 220 170 212 172 242  27  16 175  59 
 51 205 227  80  72  71  21  92 187 111  34  25 186 155 125 245 
 11 225  26  28 127  35 248  41 248 164  27  19 181 202  78 232 
152  50  56 224 121  77  61  52 188  95  78 119 250 203 108   5 
172 134  33  43 170  26  85 162 190 112 181 115  59   4  92 211 
 54 148 179 175 226 240 228 158  79  50  21  73 253 130  78 169 


******Output Image ******* 
198 248 248 255 255 255 255 255 236 236 242 251 251 251 251 251 
205 248 248 255 255 255 255 255 236 236 242 251 251 251 251 251 
233 248 248 255 255 255 255 255 252 236 242 251 251 251 251 251 
233 248 248 248 252 252 252 252 252 251 236 236 236 236 236 233 
254 254 254 254 254 252 252 252 252 251 251 236 236 236 236 233 
254 254 254 254 254 252 252 252 252 251 251 236 241 241 241 241 
254 254 254 254 254 252 252 252 252 251 251 236 241 241 241 241 
254 254 254 254 254 251 251 251 251 251 251 236 241 241 241 241 
254 254 254 254 254 251 251 251 251 251 251 242 242 242 241 241 
247 247 247 249 249 249 249 249 229 242 242 242 242 245 245 245 
247 247 247 247 248 248 248 248 248 248 248 242 242 245 245 245 
227 227 227 227 248 248 248 248 248 248 250 250 250 250 250 245 
227 227 227 227 248 248 248 248 248 248 250 250 250 250 250 245 
227 227 227 240 248 248 248 248 248 248 253 253 253 253 253 245 
225 225 226 240 248 248 248 248 248 248 253 253 253 253 253 232 
179 224 226 240 240 240 240 240 228 190 253 253 253 253 253 211 


Test passed
```

**Comment by manjunathahg** [comment]
Hi @AnthonyARM , thanks for the reply. We got the correct output as mentioned above for Max kernel.
Same output is seen for Min and Median kernels (log attached). Can you please help here?
[cl_nonlinear_log.txt](https://github.com/ARM-software/ComputeLibrary/files/2148614/cl_nonlinear_log.txt)

**Comment by morgolock** [comment]
Hi @vinithsrvv1 

I ran the test with all the three different filters MIN, MAX and MEDIAN. In all cases CL matches NEON.

![nonlinear](https://user-images.githubusercontent.com/5577511/44157334-1ad74480-a0aa-11e8-9c03-ad9a70fbd174.png)


Closing the issue. Please try this again with 18.05 and reopen if you still see problems.
