### ISSUE TITLE
Scale image - AREA interpolation unsupported execution issue ACL - GPU 17.10 - request for inputs

### ISSUE THREAD

**Issue by vinithsrvv1** [ARM-software/ComputeLibrary#419]
Hi Sir,
When executing scale image for interpolation AREA type, when executing the kernel. " Kernel scale_area not found in the CLKernelLibrary" error is observed.  Attaching the standalone workspace and logs 
[scale_image_gpu_error_for_area_interpolation.txt](https://github.com/ARM-software/ComputeLibrary/files/1889216/scale_image_gpu_error_for_area_interpolation.txt)
[cl_scale_test.txt](https://github.com/ARM-software/ComputeLibrary/files/1889217/cl_scale_test.txt)

Can you please help in resolving this ?

Version : 17.10 

Can you let us know whether this issue is resolved with latest ARM compute library versions ?

Thanks,
Vinith

**Comment by AnthonyARM** [comment]
No it's not, and currently we have no plans to add support for area interpolation.

**Comment by morgolock** [comment]
Closing issue. I created a ticket internally to be sure we look at this when planning the sprints.
