### ISSUE TITLE
MinMaxloc kernel for S16 output mismatch between GPU and NEON - ACL v 17.10  - request for inputs 

### ISSUE THREAD

**Issue by vinithsrvv1** [ARM-software/ComputeLibrary#420]
Hi Sir, 

When executing MinMax loc kernel for GPU, output is getting mismatched compated to NEON. NEON is matching with C-Model reference (OpenVx) . This is observed for S16 formats. U8 works fine in GPU with out of order . 

Version : 17.10 

Attaching the sample workspace, logs for reference .

Can you please help us in resolving the same?

Thanks,
Vinith 
[minmax_loc_log.txt](https://github.com/ARM-software/ComputeLibrary/files/1889810/minmax_loc_log.txt)
[neon_minmaxloc_s16_16x16_api.txt](https://github.com/ARM-software/ComputeLibrary/files/1889811/neon_minmaxloc_s16_16x16_api.txt)
[cl_minmax_loc_s16_16x16_api.txt](https://github.com/ARM-software/ComputeLibrary/files/1889812/cl_minmax_loc_s16_16x16_api.txt)

**Comment by AnthonyARM** [comment]
HI,
You can't do:
```cpp
    memcpy(src.buffer(), buffer, 16 * 16 * sizeof(int16_t));   
```
because the library uses padded images, instead you need to copy one row at the time as explained [in the documentation](https://arm-software.github.io/ComputeLibrary/v18.03/architecture.xhtml#S4_6_4_working_with_objects)

Hope this helps,

**Comment by vinithsrvv1** [comment]
Thanks for the update. But for U8 types, it works fine. So this should had been observed there also na ? Why it is not happening when format is U8 ? Can you please explain ?

**Comment by manjunathahg** [comment]
Hi @AnthonyARM, thank you for the response.
The issue is still seen even after modifying the read/write accesses.
Can you please let us know your inputs? Attaching standalone code and logs.
[cl_minmax_8x8_log.txt](https://github.com/ARM-software/ComputeLibrary/files/2149975/cl_minmax_8x8_log.txt)
[cl_minmax_loc_u8xu8_api.txt](https://github.com/ARM-software/ComputeLibrary/files/2149983/cl_minmax_loc_u8xu8_api.txt)

Thanks in advance

**Comment by morgolock** [comment]
Hi @vinithsrvv1 

I downloaded your test and just removed one call to map() which was not necessary

![maaaap](https://user-images.githubusercontent.com/5577511/44100779-b0e43cc6-9fdd-11e8-8afc-029cfbadaf4a.png)

The output looks good to me:
![minmax](https://user-images.githubusercontent.com/5577511/44100796-bbc5e702-9fdd-11e8-975f-00a65597efb2.png)

Could you please try this with ACL 18.05. Reopen if you still see the problem.

**Comment by manjunathahg** [comment]
Hi @morgolock the output matches with NEON output with CL 18.05.
Thank you for the support.
