### ISSUE TITLE
Half scale gaussian kernel GPU output mismatch - 5x5 kernel ACL version 17.10 - request for inputs

### ISSUE THREAD

**Issue by vinithsrvv1** [ARM-software/ComputeLibrary#422]
Hi Sir,

When executing Half scale gaussian kernel in ACL GPU, output mismatches with NEON output. NEON  is matching with reference  OpenVx implementation . Attaching the logs, sample workspace for reference .

Can you please help in resolving this issue?

Thanks,
Vinith 
[cl_halfscale_gaussian_api.txt](https://github.com/ARM-software/ComputeLibrary/files/1889997/cl_halfscale_gaussian_api.txt)
[neon_halfscalegaussian_output.txt](https://github.com/ARM-software/ComputeLibrary/files/1889998/neon_halfscalegaussian_output.txt)
[Uploading cl_halfscale_gaussian_log.txt…]()

**Comment by morgolock** [comment]
Hi @vinithsrvv1 

One problem I've noticed in the test is that tmp2 is never allocated. I'll compare the output of CL with NEON and let you know if I can reproduce the issue.

**Comment by morgolock** [comment]
Hi @vinithsrvv1 

I removed tmp2 altogether, I'm not sure what the purpose of this variable was but it had no effect at all in the test. 

I can't see anything wrong with the CL output, as shown below there are no mismatches between Neon and CL.
![gaussian](https://user-images.githubusercontent.com/5577511/44143589-324ccf14-a07c-11e8-8984-e243619b72c9.png)

Please clean up your test (remove tmp2) and try this again with the latest version of ACL 18.05. Closing the issue, if you still experience the problem reopen.
