### ISSUE TITLE
Gaussian pyramid ACL NEON and GPU output issue (Version 17.10) request for inputs

### ISSUE THREAD

**Issue by vinithsrvv1-path** [ARM-software/ComputeLibrary#426]
Hi Sir ,

When executing Gaussian pyramid for NEON and GPU, for the upper levels, only partial output is visible. Say for example 
IP = 64x64 
L1 = 32x32 

in L1, only middle 16x32 is filled with values, others are with zeros. Can you please help us in resolving this issue.? 

ACL Version : 17.10 

Attaching the stand alone workspaces and logs for both NEON and GPU targets for reference.

Thanks,
Vinith 
[acl_neon_gaussianImgPyramid_output_is not_proper.txt](https://github.com/ARM-software/ComputeLibrary/files/1897489/acl_neon_gaussianImgPyramid_output_is.not_proper.txt)
[acl_gpu_gaussianImgPyramid_op.txt](https://github.com/ARM-software/ComputeLibrary/files/1897490/acl_gpu_gaussianImgPyramid_op.txt)
[cl_gaussImgPyr_test.txt](https://github.com/ARM-software/ComputeLibrary/files/1897491/cl_gaussImgPyr_test.txt)
[neon_gaussImgPyr_test.txt](https://github.com/ARM-software/ComputeLibrary/files/1897492/neon_gaussImgPyr_test.txt)

**Comment by manjunathahg** [comment]
Hi team
Any update on the above issue?

**Comment by AnthonyARM** [comment]
You need to allocate the pyramid *after* you've configured the function that uses it.
