### ISSUE TITLE
Where can I find inceptionv4_model for inceptionv4 example?

### ISSUE THREAD

**Issue by chunyen627** [ARM-software/ComputeLibrary#428]
I have found inception-v4.caffemodel on other websites, but the extracted files are not comparable to the files in the examples. I hope I can get a model for use. Thank you

**Comment by GeorgeARM** [comment]
Hello @chunyen627,

The model we use is from [here](https://github.com/tensorflow/models/tree/master/research/slim#pre-trained-models)

**Comment by chunyen627** [comment]
I got the .ckpt file but still can't find the .meta file

**Comment by GeorgeARM** [comment]
You don't get a meta file.
You need the pb and the ckpt file. You should load the pb and push the ckpt inside the pb.
You will get a pb file with everything inside.
More info [here](https://github.com/tensorflow/models/tree/master/research/slim#freezing-the-exported-graph)
