### ISSUE TITLE
Crash in Android Studio when using Tensor

### ISSUE THREAD

**Issue by AnshanTJU** [ARM-software/ComputeLibrary#430]
Output of 'strings libarm_compute.so | grep arm_compute_version :
arm_compute_version=v18.03 Build options: {'opencl': '0', 'neon': '1', 'examples': '1', 'asserts': '0', 'debug': '0', 'Werror': '1', 'build': 'native'} Git hash=6cd8accb92a0f9e59e44d7e51440bd814a9bb192

I want to use ACL in android studio. It is made by:
CXX=clang++ CC=clang scons Werror=1 -j8 debug=1 neon=1 opencl=0 os=android arch=armv7a
I link "libarm_compute_core-static.a libarm_compute_graph-static.a libarm_compute-static.a" in CMakeLists.txt when building the dynamic library. 
When I add this line "Tensor weights_1;" in the JNI file. The app crashed with：
04-16 18:26:20.660 25548-25548/com.tencent.squeezencnn A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 25548 (ent.squeezencnn)
I delete the line ""Tensor weights_1; " and the app is right.
The libOpenCL.so is also loaded using System.loadLibrary.
Could you please tell me Why?

**Comment by AnthonyARM** [comment]
1) Could you try linking the libraries in this order: `graph / runtime / core`
Also the graph API relies on some static variables auto-registrating themselves so you need to link the library with: ` -Wl,--whole-archive -larm_compute_graph-static -Wl,--no-whole-archive -larm_compute-static -larm_compute_core-static`
2) Could you try to build the library with `asserts=1` to see if you're hitting any asserts that are disabled in release mode.

**Comment by AnshanTJU** [comment]
Hi, I add the asserts=1 to rebuild the ACL library, and it happens again:
04-16 20:04:52.100 19326-19326/com.tencent.squeezencnn A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 19326 (ent.squeezencnn)
The libraries are linked in the order: libarm_compute_graph-static.a libarm_compute-static.a libarm_compute_core-static.a
The variables are set using:
 add_definitions(-Wl,--whole-archive)
However, it report:
clang50++: warning: -Wl,--whole-archive: 'linker' input unused [-Wunused-command-line-argument]

**Comment by morgolock** [comment]
Hi @AnshanTJU 

Could you please show us the code trying to use the Tensor?

**Comment by mpekatsoula** [comment]
Closing, reopen if needed
