### ISSUE TITLE
Table lookup Armcompute GPU kernel gives IOVA fault (ACL version 17.10)- request for inputs

### ISSUE THREAD

**Issue by vinithsrvv1** [ARM-software/ComputeLibrary#433]
Hi Sir ,

When Table look up kernel is executed for Armcompute version 17.10. We are getting IOVA fault. We are not sure whether it is the driver issue . Can you please comment on the same? 

Attaching the sample test app and logs for your reference for reproducing the issue.

Thanks,
Vinith
[table_lookup_standalone_test_failed_log.txt](https://github.com/ARM-software/ComputeLibrary/files/1928155/table_lookup_standalone_test_failed_log.txt)
[cl_tablelookup_test.txt](https://github.com/ARM-software/ComputeLibrary/files/1928156/cl_tablelookup_test.txt)

**Comment by morgolock** [comment]
Hi @vinithsrvv1 

In the test code attached to this issue, there are no calls to  `dest.allocator()->allocate();` before `tableLookup.run();`. If you add that the segfault will be fixed.

**Comment by manjunathahg** [comment]
Hi @morgolock, thanks for the reply.
Issue got fixed after accommodating the above change.
Thank you.
