### ISSUE TITLE
NEDeconvolutionLayer kernelsize

### ISSUE THREAD

**Issue by wr0112358** [ARM-software/ComputeLibrary#436]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v18.03 Build options: {'arch': 'arm64-v8a', 'opencl': '1', 'neon': '1', 'asserts': '1', 'debug': '1', 'os': 'android', 'Werror': '1'} Git hash=c3f34a43ffb5d52ee4a4e9f7b1bf4c6c002aeebb
**Platform:**
hikey960
**Operating System:**
android

**Problem description:**
I am currently implementing LinkNet architecture(https://arxiv.org/pdf/1707.03718.pdf) for semantic segmentation for ACL. I have encountered some problems using NEDeconvolutionLayer:
1. This architecture uses "Deconvolution" with kernelsizes of 3x3 and stride=2. I am unable to get the same results as an equivalently parametrised tensorflow implementation. Changing kernelsize to 4x4 for stride=2 works as expected. Is there a list of kernelsizes that are known to work?
2. The reference implementation of linknet uses padding=1 for the Deconvolutionlayer. Since padding in ACL's Deconvolution behaves differently I am having trouble to find the correct parameters:
To get the same results as a tensorflow operation nn.conv2d_transpose with padding=VALID and no additional zero-padding, I set padding=kernelsize-1 in ACL. If I add zero-padding in tensorflow and the required amount of padding to this parameter I get the following error in function deconvolution_output_dimensions: ARM_COMPUTE_ERROR_ON(padx_deconv < 0)
Is padding supported in ACL's DeconvolutionLayer?
3. Aside from these 2 problems the differing number of input and output features leads to the problems described in PR404.

**Comment by ved27** [comment]
Hi ,

For the First point:
for 3x3 kernel , Try with inner_border_right = -1 (although inner_border_right is of type unsigned int)and increment padx by 1
And the weights format should be WxHxIn_channelxOut_channel with flipping around WxH plane

**Comment by mpekatsoula** [comment]
Closing, reopen if needed.
