### ISSUE TITLE
Illegal instruction when running neon_convolution example

### ISSUE THREAD

**Issue by zanazakaryaie** [ARM-software/ComputeLibrary#437]
**Output of 'strings libarm_compute.so | grep arm_compute_version':** arm_compute_version=v18.03 Build options: {'opencl': '0', 'neon': '1', 'examples': '1', 'asserts': '0', 'debug': '0', 'Werror': '1', 'build': 'native'} Git hash=02c62c8030e7aca592b294396556a93c6bfb9f7a

**Platform:** Raspberry Pi 2

**Operating System:** Raspbian OS

**Problem description:** I've successfully installed computeLibrary on Raspberry Pi2 BUT when I run the neon_convolution example, I get "Illegal instruction". This happens in conv3x3.run() function. Could you please help?

**Comment by AnthonyARM** [comment]
You need an OS which is compiled for armv7 (Raspbian is compiled for armv6) [See this other thread for more details](https://github.com/ARM-software/ComputeLibrary/issues/12#issuecomment-291119511)

**Comment by zanazakaryaie** [comment]
Thanks for replying

I read somewhere that armv6 does not support Neon and hence computeLibrary is unavailable.

But I have successfully built OpenCV with Neon flag on Raspbian OS. I've also included <arm_neon.h> and used Neon C intrinsics for some of my codes.

Could you please provide the clear reason for armv6 incompatibility?

**Comment by AnthonyARM** [comment]
As explained in the other thread, the only architectures supported are armv7 and later, for armv6 NEON is optional, so by tweaking the compiler flags you might manage to get it working on armv6.
But the recommended way is to use an armv7 distribution (You've got several available for Raspberry Pi)
