### ISSUE TITLE
where to download libopencl.so

### ISSUE THREAD

**Issue by kuang93** [ARM-software/ComputeLibrary#438]
**Platform:** Odroid

**Operating System:** ubuntu14.04

**Problem description:** Hi, recently I want to compile Compute Library on odroid-xu4, ubuntu14.04, but I can't find libopencl.so on my odroid. Where can I find this file? thanks

**Comment by AnthonyARM** [comment]
We don't have this particular platform in the office, but from a quick Google search it looks like you might need to install the Ubuntu 16.04 image on this platform: [source](http://mechanicalforex.com/2016/10/using-the-gpu-and-cpu-for-opencl-programs-in-an-odroid-xu4.html)

**Comment by AnthonyARM** [comment]
And [here](https://wiki.odroid.com/odroid-xu4/os_images/linux/ubuntu_4.14/ubuntu_4.14) is the link to the Ubuntu images

**Comment by kuang93** [comment]
thank you, I've change my odroid's operating system to ubuntu16.04 mate, and the OpenCL version is 1.2. I use : 

    ln -s /usr/lib/arm-linux-gnueabihf/mali-egl/libOpenCL.so libOpenCL.so 

to put a symlink in my ComputeLibrary/build directory, and then run (this commad line is come from [here](https://community.arm.com/graphics/f/discussions/9625/compute-library-run-opencl-examples/31609#31609) ):
    scons Werror=1 -j8 debug=0 neon=1 opencl=1 os=linux arch=armv7a build=native embed_kernels=1 
got error:
```
build/src/graph/Graph.os: In function `cl::CommandQueue::makeDefault()':
Graph.cpp:(.text._ZN2cl12CommandQueue11makeDefaultEv[_ZN2cl12CommandQueue11makeDefaultEv]+0xc6): undefined reference to `clCreateCommandQueue'
build/src/graph/Graph.os: In function `cl::Device::makeDefault()':
Graph.cpp:(.text._ZN2cl6Device11makeDefaultEv[_ZN2cl6Device11makeDefaultEv]+0x94): undefined reference to `clGetContextInfo'
Graph.cpp:(.text._ZN2cl6Device11makeDefaultEv[_ZN2cl6Device11makeDefaultEv]+0xc8): undefined reference to `clGetContextInfo'
build/src/graph/Graph.os: In function `cl::Context::makeDefault()':
Graph.cpp:(.text._ZN2cl7Context11makeDefaultEv[_ZN2cl7Context11makeDefaultEv]+0x7e): undefined reference to `clCreateContextFromType'
collect2: error: ld returned 1 exit status
build/examples/neoncl_scale_median_gaussian.o: In function `cl::CommandQueue::makeDefault()':
neoncl_scale_median_gaussian.cpp:(.text._ZN2cl12CommandQueue11makeDefaultEv[_ZN2cl12CommandQueue11makeDefaultEv]+0xf0): undefined reference to `clCreateCommandQueue'
build/examples/neoncl_scale_median_gaussian.o: In function `cl::Device::makeDefault()':
neoncl_scale_median_gaussian.cpp:(.text._ZN2cl6Device11makeDefaultEv[_ZN2cl6Device11makeDefaultEv]+0xaa): undefined reference to `clGetContextInfo'
neoncl_scale_median_gaussian.cpp:(.text._ZN2cl6Device11makeDefaultEv[_ZN2cl6Device11makeDefaultEv]+0xde): undefined reference to `clGetContextInfo'
build/examples/neoncl_scale_median_gaussian.o: In function `cl::Context::makeDefault()':
neoncl_scale_median_gaussian.cpp:(.text._ZN2cl7Context11makeDefaultEv[_ZN2cl7Context11makeDefaultEv]+0x92): undefined reference to `clCreateContextFromType'
collect2: error: ld returned 1 exit status
```
do you have any advice about this?
thank you very much

**Comment by kuang93** [comment]
I finally handle it by " sudo apt-get install mali-fbdev ".

**Comment by AnthonyARM** [comment]
FYI: You don't need to pull any library from your platform to build the library & tests. The library comes with a stub version of libOpenCL which is used to resolve the OpenCL symbols at compile time. (You obviously need to make sure the stub doesn't get picked up when you then try to run your application on the target)
