### ISSUE TITLE
simply build the examples error with test_helpers

### ISSUE THREAD

**Issue by MattZhz** [ARM-software/ComputeLibrary#44]
MattZhz@ubuntu:~/libraries/ComputeLibrary-master/build$ aarch64-linux-android-g++ examples/cl_convolution.cpp -I. -Iinclude -std=c++11 -larm_compute-static -L. -o cl_convolution_aarch64 -static-libstdc++ -pie -lOpenCL
/tmp/cc5TU2e0.o: In function `main':
cl_convolution.cpp:(.text+0x660): undefined reference to `test_helpers::run_example(int, char const**, void (&)(int, char const**))'
/tmp/cc5TU2e0.o: In function `test_helpers::PPMLoader::open(std::string const&)':
cl_convolution.cpp:(.text._ZN12test_helpers9PPMLoader4openERKSs[_ZN12test_helpers9PPMLoader4openERKSs]+0x88): undefined reference to `test_helpers::parse_ppm_header(std::basic_ifstream<char, std::char_traits<char> >&)'

directory showed by tree -L 2
├── arm_compute
│   ├── core
│   └── runtime
├── cl_convolution
├── cl_events
├── examples
│   ├── cl_convolution.cpp
│   ├── cl_convolution.o
│   ├── cl_events.cpp
│   ├── cl_events.o
│   ├── neoncl_scale_median_gaussian.cpp
│   ├── neon_convolution.cpp
│   ├── neon_copy_objects.cpp
│   ├── neon_scale.cpp
│   └── test_helpers
├── include
│   └── CL
├── libarm_compute_core.so
├── libarm_compute_core-static.a
├── libarm_compute.so
├── libarm_compute-static.a
├── libOpenCL.so
├── src
│   ├── core
│   └── runtime
└── test_helpers
    ├── Utils.cpp
    ├── Utils.h
    └── Utils.o

Please help see if there is anything wrong.

Thanks,
MattZhz

**Comment by mpflanzer** [comment]
You also need to compile and link `test_helpers/Utils.cpp` in addition to each of the examples. Can't test it right now but this should work:

```
$ aarch64-linux-android-g++ examples/cl_convolution.cpp test_helpers/Utils.cpp -I. -Iinclude -std=c++11 -larm_compute-static -L. -o cl_convolution_aarch64 -static-libstdc++ -pie -lOpenCL
```

**Comment by AnthonyARM** [comment]
Re-open if you still have issues compiling the examples
