### ISSUE TITLE
Example of image dilation

### ISSUE THREAD

**Issue by zanazakaryaie** [ARM-software/ComputeLibrary#441]
Could you please provide an example of image dilation using the ComputeLibrary?

**Comment by AnthonyARM** [comment]
You can just use the existing [neon_convolution](https://github.com/ARM-software/ComputeLibrary/blob/master/examples/neon_convolution.cpp) example and replace the Convolution operator by a [NEDilate](https://arm-software.github.io/ComputeLibrary/v18.03/classarm__compute_1_1_n_e_dilate.xhtml) operator.
You can also have a look at the [DilateFixture](https://github.com/ARM-software/ComputeLibrary/blob/master/tests/validation/fixtures/DilateFixture.h#L67) in the unit tests

**Comment by zanazakaryaie** [comment]
Thanks for reply

I tested your suggestion by replacing the convolution operator by a NEDilate operator but It gives me "no matching function" error. 

Looking at NEDilate documentation, the function has no argument for morphology kernel:

void configure ( ITensor * input, ITensor * output, BorderMode border_mode, uint8_t constant_border_value = 0)

Could you please help?

**Comment by zanazakaryaie** [comment]
In the neon_convolution example, the third argument in **configure** gets the kernel as a 1D array. It works fine but this doesn't hold for NEDilate

**Comment by AnthonyARM** [comment]
Sorry, I only meant this as a hint about how to get most of the boiler plate code done. Yes, you still need to adapt the configure() call to match the function's arguments (But it should be pretty straight forward based on the documentation)

The dilate function follows the OpenVX specifications ([which doesn't have a morphology kernel](https://www.khronos.org/registry/OpenVX/specs/1.0/html/dc/d73/group__group__vision__function__dilate__image.html))

**Comment by morgolock** [comment]
Hi @zanazakaryaie 

For the call into configure you just need to do this:
`dilate.configure(&src, &dst, BorderMode::CONSTANT );`

I'll close the issue, please reopen if you still have problems.
