### ISSUE TITLE
Can I use OpenGL_ES on Raspberry Pi?

### ISSUE THREAD

**Issue by zanazakaryaie** [ARM-software/ComputeLibrary#442]
Hello

I know that the GPU of raspberry pi does not support OpneCL. But I have seen in different forums that it supports OpenGLS-ES. Is it true? If yes, will it use the GPU to accelerate the performance if I build ComputeLibrary with OpenGL-ES flag on? 
I want to use both Neon and OpenGL-ES

**Comment by AnthonyARM** [comment]
You need support for Compute Shaders, i.e OpenGLES 3.1 (Not just regular OpenGLES) and if your GPU doesn't support OpenCL then it almost certainly won't support 3.1 (As it's very similar in terms of HW features needed).

**Comment by AnthonyARM** [comment]
While the driver reports OpenCL 1.1, it might support some functions from OpenCL 1.2, so it's worth trying.
We configure the Khronos header to target OpenCL 1.2 (See [here](https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/core/CL/OpenCL.h#L34)), but we're not using a lot of functions from 1.2 so it might mostly work with 1.1
