### ISSUE TITLE
Making heterogeneous accelerator graph has problem. OpenCL->NEON works fine, but NEON -> OpenCL returns segment fault.

### ISSUE THREAD

**Issue by jongwooc** [ARM-software/ComputeLibrary#443]
Hi,
I am trying to make faster graph network by using both NEON and OpenCL, just like NEONCL example.

For example, 

in AlexNet example,

        graph 
<< target_hint_CL
                      << ConvolutionMethodHint::GEMM
        

              << Tensor(TensorInfo(TensorShape(227U, 227U, 3U, 1U), 1, DataType::F32),
                        get_input_accessor(image, std::move(preprocessor)))
              // Layer 1
              << ConvolutionLayer(
                  11U, 11U, 96U,
                  get_weights_accessor(data_path, "/cnn_data/alexnet_model/conv1_w.npy"),
                  get_weights_accessor(data_path, "/cnn_data/alexnet_model/conv1_b.npy"),
                  PadStrideInfo(4, 4, 0, 0))
              << ActivationLayer(ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::RELU))
              << NormalizationLayer(NormalizationLayerInfo(NormType::CROSS_MAP, 5, 0.0001f, 0.75f))
              << PoolingLayer(PoolingLayerInfo(PoolingType::MAX, 3, PadStrideInfo(2, 2, 0, 0)))

              // Layer 2
<<target_hint_NEON

Something like this. 
When I start with OpenCL, then change into NEON, things are working fine.
1layer configure 1
 OPENCL 
 Instantiate GEMM based convolution layer
2layer configure 2
 OPENCL 
3layer configure 3
 OPENCL 
4layer configure 4
 OPENCL 
5layer configure 5
 NEON 
 Instantiate GEMM based convolution layer
 Instantiate GEMM based convolution layer
 CL > NEON map 
6layer configure 6
 NEON 
7layer configure 7
 NEON 
8layer configure 8
 NEON 
9layer configure 9
 NEON 
 Instantiate GEMM based convolution layer
10layer configure 10
 NEON 
11layer configure 11
 NEON 
 Instantiate GEMM based convolution layer
 Instantiate GEMM based convolution layer
12layer configure 12
 NEON 
13layer configure 13
 NEON 
 Instantiate GEMM based convolution layer
 Instantiate GEMM based convolution layer
14layer configure 14
 NEON 
15layer configure 15
 NEON 
16layer configure 16
 NEON 
 Instantiate Fully Connected layer
17layer configure 17
 NEON 
18layer configure 18
 NEON 
 Instantiate Fully Connected layer
19layer configure 19
 NEON 
20layer configure 20
 NEON 
 Instantiate Fully Connected layer
21layer configure 21
 NEON 
graph run()
 CL conv 
graph run()
graph run()
graph run()
graph run()
graph run()
NEON conv
NEON conv
graph run()
graph run()
graph run()
graph run()
NEON conv
graph run()
graph run()
NEON conv
NEON conv
graph run()
graph run()
NEON conv
NEON conv
graph run()
graph run()
graph run()
 NEON Fully 
graph run()
graph run()
 NEON Fully 
graph run()
graph run()
 NEON Fully 
graph run()
total : 527153

Test passed

However, whenever I try to change NEON into OpenCL, the graph generates segment fault.
1layer configure 1
 OPENCL 
 Instantiate GEMM based convolution layer
2layer configure 2
 OPENCL 
3layer configure 3
 OPENCL 
4layer configure 4
 OPENCL 
5layer configure 5
 NEON 
 Instantiate GEMM based convolution layer
 Instantiate GEMM based convolution layer
 CL > NEON map 
6layer configure 6
 NEON 
7layer configure 7
 NEON 
8layer configure 8
 OPENCL 
9layer configure 9
 OPENCL 
 Instantiate GEMM based convolution layer
 NEON >CL Unmap map 
10layer configure 10
 OPENCL 
11layer configure 11
 OPENCL 
 Instantiate GEMM based convolution layer
 Instantiate GEMM based convolution layer
12layer configure 12
 OPENCL 
13layer configure 13
 OPENCL 
 Instantiate GEMM based convolution layer
 Instantiate GEMM based convolution layer
14layer configure 14
 OPENCL 
15layer configure 15
 OPENCL 
16layer configure 16
 OPENCL 
 Instantiate Fully Connected layer
17layer configure 17
 OPENCL 
18layer configure 18
 OPENCL 
 Instantiate Fully Connected layer
19layer configure 19
 OPENCL 
20layer configure 20
 OPENCL 
 Instantiate Fully Connected layer
21layer configure 21
 OPENCL 
graph run()
 CL conv 
graph run()
graph run()
graph run()
graph run()
graph run()
NEON conv
NEON conv
graph run()
graph run()
graph run()
Segmentation fault 

As the log shows, I checked CL:: map and unmap, So, I wonder what would be the problem of going back to OpenCL accelerator. 

thank you.

Device : Samsung Galaxy S9

ACL version L 18.03

**Comment by AnthonyARM** [comment]
Hi,
I'm afraid we don't currently support mixed pipelines, it might work in some cases, but the API is not intended to be used like this.

**Comment by jongwooc** [comment]
I see. Thank you for reply.

**Comment by gmiodice** [comment]
Hi @jamesking1,

you should not have any problem using two different graphs (one for CL and one for NEON). The important thing is to keep the target (NEON or CL) on a given graph.

Hope this can help you.

**Comment by GeorgeARM** [comment]
Closing. Not heterogeneous in the same pipeline is currently supported at graph level.
