### ISSUE TITLE
How to convert arm_compute::Image to opencv Mat?

### ISSUE THREAD

**Issue by zanazakaryaie** [ARM-software/ComputeLibrary#444]
Hello

I have converted cv::Mat to arm_compute::Image. Now I want to do the reverse operation. How should I do this?

**Comment by i7clock** [comment]
Thats what I did:

preserve the ptr as long as you need the mat then free() it!

There might be a better way though

`ptr = (unsigned char*)malloc(mat.cols*mat.rows*sizeof(unsigned char));`
`std::memcpy(ptr, matACL.buffer(), sizeof *matACL.buffer());`
`result = cv::Mat(mat.rows, mat.cols, CV_8UC1, ptr);`

**Comment by cnhzcy14** [comment]
Hi @morgolock 
Is there any way to import or map the cv::Mat data or any image raw data with known pointer and data structure (something like pixel stride) to ACL tensor without copy?

Thanks!

**Comment by AnthonyARM** [comment]
Have a look at this [other thread](https://github.com/ARM-software/ComputeLibrary/issues/474#issuecomment-400582790) hopefully this will answer your questions.

**Comment by cnhzcy14** [comment]
Thanks @morgolock, that's really helpfull!

**Comment by cnhzcy14** [comment]
Thanks @AnthonyARM, that's really helpfull!

**Comment by i7clock** [comment]
I know this is closed but for the sake of completeness I have implemented a function which extracts the relevant date from an ACL image and writes it to an OpenCV Mat. It is not very nice yet but I think it can be improved easily. You can find it [here](https://github.com/ARM-software/ComputeLibrary/issues/474#issuecomment-428521549)
