### ISSUE TITLE
fast_math not enabled for Winograd Convolution Method

### ISSUE THREAD

**Issue by samashu007** [ARM-software/ComputeLibrary#446]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v18.03 Build options: {'arch': 'armv7a', 'opencl': '0', 'neon': '1', 'examples': '1', 'asserts': '0', 'debug': '0', 'os': 'linux', 'Werror': '1'} Git hash=02c62c8030e7aca592b294396556a93c6bfb9f7a

**Platform:**
Raspberry Pi
**Operating System:**
Ubuntu Mate 16.04.2

**Problem description:**

How do I enable the fast_math for Winograd Convolution Method. The NEWinogradLayer.cpp and .h files built are different from the NEWinogradConvolutionLayer.cpp and .h given in the github repository. 
Since fast_math is not enabled, Winograd Implementation of convolution takes more time than expected for small kernel sizes and small images.
Ho to enable it?

**Comment by samashu007** [comment]
Any suggestions? Please?

**Comment by gmiodice** [comment]
Hi @samashu007,

are you trying to use our graph examples (i.e. graph_alexnet.cpp,..) or a standalone example?

**Comment by samashu007** [comment]
It got enabled. I modified the header files and set the flag to TRUE.

**Comment by gmiodice** [comment]
Happy to know you solved the issue. Anyway about Winograd, the fast_math flag has been added in the library just in the latest ACL 18.05 release (I have seen you are using the 18.03 release). Feel free to open another ticket if you need any help.
