### ISSUE TITLE
How to reshape a tensor?

### ISSUE THREAD

**Issue by Weyne168** [ARM-software/ComputeLibrary#45]
hi, I configured a dnn with computeLibrary.
I found that the full connected layer only accept a two dims tensor.
so, I need to reshape the three(four) dims tensors to be a two dims tensor.

Is there an exiting reshape methods in this library?

**Comment by GeorgeARM** [comment]
Hello @Weyne168,
The fully connected layer restricts only the weights to be two dimensional.
If the input to your fully connected layer comes from a convolution layer the function itself will handle the reshaping.
You can have a look in the codebase [here](https://github.com/ARM-software/ComputeLibrary/blob/master/src/runtime/NEON/functions/NEFullyConnectedLayer.cpp). You will see that it handles the case where your input comes from a fully connected layer separately from the case where your input comes from a convolution layer.
Hope this helps!

**Comment by GeorgeARM** [comment]
Closing! Reopen if required!
