### ISSUE TITLE
Support for multiple output nodes in the ACL graph

### ISSUE THREAD

**Issue by gplhegde** [ARM-software/ComputeLibrary#450]
Hi, Does ACL graph/stream support networks with multiple output nodes? For example, SSD detector requires features to be pull in from more than one convolution layer outputs. If this supported, how to construct such a graph? Any example would be of great help.
Thanks

**Comment by gplhegde** [comment]
Here is the sample net that I want to try to construct using ACL Stream. 

Caffe network :
https://gist.github.com/gplhegde/cd3abbae169060265bbaa5616e32f7df
Visualization:
http://ethereon.github.io/netscope/#/gist/cd3abbae169060265bbaa5616e32f7df

**Comment by GeorgeARM** [comment]
Hello @gplhegde,
Multiple outputs should work at our graph level. We have implemented YOLOv3 (will be part of our next release) which has three output nodes.
So I am closing this. Reopen if needed.
