### ISSUE TITLE
static instance of BackendRegistrar cannot work

### ISSUE THREAD

**Issue by MaeThird** [ARM-software/ComputeLibrary#451]
I compiled the ComputeLibrary source into static libs to use in my project.But I found the that before 18-05 version static operations are create by the macro **REGISTER_SIMPLE_OPERATION** in file **NESimpleOperations.cpp** and when the produce run **there is no instances registered in memory at all**. 
Same issue occurred in version 18-05 in which case the static instance is created in the file **NEDeviceBackend.cpp** witch this code
` static detail::BackendRegistrar<NEDeviceBackend> NEDeviceBackend_registrar(Target::NEON);` and when the produce run there is no instance in memory.
In both cases , I put the creation of these instances in function and **call it by hand** to solve the problem.

**Comment by GeorgeARM** [comment]
Hello @MaeThird,

Can you use `--whole-archive` option when statically linking? We use a static registration mechanism thus you need this option to avoid stripping those.

**Comment by MaeThird** [comment]
Hi @GeorgeARM  In my case if I pass  `-Wl,--whole-archive `to the linker there will be a lot of multiple definitions caused by libc.a and libm.a. This has nothing to do with ComputeLibrary.
One more question,in ComputeLibrary the basic DataLayout format is NCHW which by experience the index 0 is 'N',index 1 is 'C'...but the code in `get_data_layout_dimension_index` shows 
     * [N C H W]
     * [3 2 1 0]
     * [N H W C]
that the indices are reversed.
As the data layout is basic for the correct result,can u explain it more ? Thank u.

**Comment by GeorgeARM** [comment]
@MaeThird you can do `--whole-archive` when linking with ComputeLibrary and then revert to `--no-whole-archive` for the rest. Should work.
Concerning DataLayout your assumptions are correct, the basic layout is NCHW for ComputeLibrary and indices are reversed from the faster changing dimensions to the slower one.

**Comment by MaeThird** [comment]
Hi @GeorgeARM , 
if an ActivationLayer was created after a BatchNormalizationLayer there would be a check-failed in some case. Just like this:
 ```
 BatchNormalizationLayer bn_0(some parameters);
 ActivationLayer ac_0(ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::LEAKY_RELU));
```
the default constructor of ActivationLayerInfo is `ActivationLayerInfo(ActivationFunction f, float a = 0.0f, float b = 0.0f): _act(f), _a(a), _b(b), _enabled(true){}`.What care is the default value of `_enabled`. After node fusion processing the ac_0 layer was merged to bn_0 and the following check is failed in Line 53 of  `validate_arguments` within  **NEBatchNormalizationLayerKernel.cpp**. 
Is LEAKY_RELU supported in this mode ? the formulation of LEAKY_RELU looks like others.

**Comment by GeorgeARM** [comment]
Hello @MaeThird ,
seems that we don't support fusion for NEON when activation is `LEAKY_RELU`, I am not aware why but should be trivial to add. If you use the graph API and you have this issue disable the fusion by commenting out the mutator [here](https://github.com/ARM-software/ComputeLibrary/blob/master/src/graph/Utils.cpp#L84).
Will note and fix that in next release.
