### ISSUE TITLE
input possition offset in pooling and convolution layers

### ISSUE THREAD

**Issue by justPe** [ARM-software/ComputeLibrary#457]
hi,
I need configure kernels for pooling and convolution layers (all layers with stride) so that, start from where kernel compute output is offset by some possitions. And i want do it with only one input tensor, I don't want copy whole tensor multiple times.

example:
i have input tensor of size 100x100 and i need apply  e.g. pooling size: 2x2, stride: 2x2 layer for coordinates [0,0], [1,0], [0,1] [1,1] follow:

1  input[0,0] - > output[50x50]
2  input[1,0] - > output[49x50]
3  input[0,1] - > output[50x49]
4  input[1,1] - > output[49x49]

I found method Tensor::set_valid_region() but is possible to apply multiple times on same tensor with different layers and configurations? Because this tensor is in one layer as output and in second layer is input. Is possible call Tensor::set_valid_region() before configure with specifically region on every case and then again before IFunction::run() ?? Will this work when kernels are compute with multiple threads ? 

thanks

**Comment by gmiodice** [comment]
Hi @justPe,

thanks for your question. I am afraid this feature is not available if you use the graph API. Setting manually the valid region of your input tensor, you should be able to set the starting point for your pooling layer but you won't be able to have different shapes for your output tensors.

Hope this can help you.
