### ISSUE TITLE
function arm_compute::get_cpu_configuration(arm_compute::CPUInfo&): error: undefined reference to 'getauxval'

### ISSUE THREAD

**Issue by putiancaijunyu** [ARM-software/ComputeLibrary#458]
**Output of 'strings libarm_compute-static.a | grep arm_compute_version':*arm_compute-v18.05-bin-androi*
D:\Jingle_Workspace\Open_source\arm_compute-v18.05-bin-android\arm_compute-v18.05-bin-android\lib\android-armv7a-neon-cl-gles/libarm_compute-static.a(CPUUtils.o):src/runtime/CPUUtils.cpp:function arm_compute::get_cpu_configuration(arm_compute::CPUInfo&): error: undefined reference to 'getauxval'
clang60++.exe: error: linker command failed with exit code 1 (use -v to see invocation)

**Platform:**
NDK version：android-ndk-r17-windows-x86_64
arm_abi: armeabi-v7a
include lib: android-armv7a-neon-cl-gles

**Operating System:**
NDK

I try to compile the sample code "neon_convolution_arm" to test the support of my platforms.
The build command is "arm-linux-androideabi-clang++ examples/neon_convolution.cpp utils/Utils.cpp -I. -Iinclude -std=c++11 -larm_compute-static -larm_compute_core-static -L D:\Jingle_Workspace\Open_source\arm_compute-v18.05-bin-android\arm_compute-v18.05-bin-android\lib\android-armv7a-neon-cl-gles -o neon_convolution_arm -static-libstdc++ -pie"
But failed. It's show me that "error: undefined reference to 'getauxval".
But if I compile the arm64-v8a use "android-arm64-v8a-neon-cl-gles" lib, it will build ok.

**Comment by AnthonyARM** [comment]
We'll investigate, in the meantime please stick to the recommended NDK version if you can ( r16b + gnustl)

**Comment by putiancaijunyu** [comment]
Thanks, I will try with r16b.
