### ISSUE TITLE
ERROR building the compute library

### ISSUE THREAD

**Issue by jackdonghai** [ARM-software/ComputeLibrary#46]
Executed the following command :
scons Werror=1 -j8 debug=0 asserts=1 neon=0 opencl=1 embed_kernels=1 os=android arch=arm64-v8a

Error:
scons: Reading SConscript files ...
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
ERROR: Compiler not found
scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: build
scons: `.' is up to date.
scons: done building targets.

**Comment by mpflanzer** [comment]
Can you please update to the latest version of the library? https://github.com/ARM-software/ComputeLibrary/releases/tag/v17.04

The issue might be fixed already. If not at least the error message should be more helpful. Letting aside the git error it looks like the compiler cannot be found. Do you have `aarch64-linux-android-g++` in your `PATH` environment?

**Comment by jackdonghai** [comment]
Thanks, I'll try .

**Comment by jackdonghai** [comment]
The issue  is solved .
@mpflanzer Thanks!
1,   ERROR: Compiler not found : 
export PATH=$PATH:$MY_TOOLCHAINS/aarch64-linux-android-4.9/bin:$MY_TOOLCHAINS/arm-linux-androideabi-4.9/bin
2,  'git [...] -- [...]'.
git_hash = subprocess.check_output(["git", "rev-parse","HEAD"]))  ->
git_hash = subprocess.check_output(["git", "rev-parse","--HEAD"]))

**Comment by sejal-gupta** [comment]
I am getting the following error . Can someone please help me with this error.
@jackdonghai Could u please help me with this. Where did u set the path of the compiler.

scons: Reading SConscript files ...
ERROR: Compiler 'aarch64-linux-gnu-g++' not found

**Comment by AnthonyARM** [comment]
@sejal-gupta You just need to do:
```bash
 export PATH=$PATH:</path/to/compiler>/aarch64-linux-android-4.9/bin
```
Replace **</path/to/compiler>** with the real path to your compiler.

Then in the same terminal:
```
scons ...
```
