### ISSUE TITLE
Compile neon error on rk3399

### ISSUE THREAD

**Issue by xtanitfy** [ARM-software/ComputeLibrary#463]
The error message as follow:
```
/tmp/cc9XYDtO.s: Assembler messages:
/tmp/cc9XYDtO.s:1733: IT blocks containing 32-bit Thumb instructions are deprecated in ARMv8
gemm_fp32.cpp:(.text._ZN8arm_gemm15GemmInterleavedINS_9sgemm_8x6EffE16execute_internalILb0EEEvjji[_ZN8arm_gemm15GemmInterleavedINS_9sgemm_8x6EffE16execute_internalILb0EEEvjji]+0x9a0): undefined reference to `arm_gemm::a32_sgemm_8x6_a53(float const*, float const*, float*, int, int, int)'
gemm_fp32.cpp:(.text._ZN8arm_gemm15GemmInterleavedINS_9sgemm_8x6EffE16execute_internalILb0EEEvjji[_ZN8arm_gemm15GemmInterleavedINS_9sgemm_8x6EffE16execute_internalILb0EEEvjji]+0x14ec): undefined reference to `arm_gemm::a32_sgemm_8x6_a55r1(float const*, float const*, float*, int, int, int)'
build/src/core/NEON/kernels/arm_gemm/gemm_fp32.os: In function `arm_gemm::GemmInterleaved<arm_gemm::sgemm_8x6, float, float>::execute(unsigned int, unsigned int, int)':
gemm_fp32.cpp:(.text._ZN8arm_gemm15GemmInterleavedINS_9sgemm_8x6EffE7executeEjji[_ZN8arm_gemm15GemmInterleavedINS_9sgemm_8x6EffE7executeEjji]+0x420): undefined reference to `arm_gemm::a32_sgemm_8x6(float const*, float const*, float*, int, int, int)'
gemm_fp32.cpp:(.text._ZN8arm_gemm15GemmInterleavedINS_9sgemm_8x6EffE7executeEjji[_ZN8arm_gemm15GemmInterleavedINS_9sgemm_8x6EffE7executeEjji]+0xb00): undefined reference to `arm_gemm::a32_sgemm_8x6_a55r1(float const*, float const*, float*, int, int, int)'
gemm_fp32.cpp:(.text._ZN8arm_gemm15GemmInterleavedINS_9sgemm_8x6EffE7executeEjji[_ZN8arm_gemm15GemmInterleavedINS_9sgemm_8x6EffE7executeEjji]+0xb04): undefined reference to `arm_gemm::a32_sgemm_8x6_a53(float const*, float const*, float*, int, int, int)'
collect2: error: ld returned 1 exit status
scons: *** [build/libarm_compute_core.so] Error 1
^Cscons: *** [build/src/runtime/CPUUtils.os] Build interrupted.
```

**Comment by xtanitfy** [comment]
1.I use the compile cmd as follow:
#scons Werror=0 -j8 debug=0 neon=1 opencl=0 os=linux arch=arm64-v8a build=native openmp=1
2.add a flag:
  env.Append(CXXFLAGS = ['-Wno-deprecated-declarations','-Wall','-DARCH_ARM',
         '-Wextra','-Wno-unused-parameter','-pedantic','-Wdisabled-optimization','-Wformat=2',
         '-Winit-self','-Wstrict-overflow=2','-Wswitch-default',
         '-fpermissive','-std=gnu++11','-Wno-vla','-Woverloaded-virtual',
         '-Wctor-dtor-privacy','-Wsign-promo','-Weffc++','-Wno-format-nonliteral','-Wno-overlength-strings','-Wno-strict-overflow','-Wno-implicit-fallthrough','-mfloat-abi=hard', '-mfpu=neon'])
 ('-mfloat-abi=hard', '-mfpu=neon') is added by me.

**Comment by AnthonyARM** [comment]
Why did you add these flags? That's what's breaking your build.
It should work just fine on this platform with the default flags.

**Comment by xtanitfy** [comment]
If i use the follow default compile command ：
scons Werror=1 -j8 debug=0 neon=1 opencl=0 os=linux arch=arm64-v8a build=native

then another error will occur：
/usr/lib/gcc/arm-linux-gnueabihf/5/include/arm_neon.h:31:2: error: #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h
 #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h

So I add the flag of “-mfloat-abi=softfp -mfpu=neon”

**Comment by gmiodice** [comment]
Hi @xtanitfy,

looking at your command it seems you are building the library natively. Can you try to build the library with the following command?

scons Werror=1 debug=0 neon=1 opencl=0 build=native -j8

It is similar to your command but it does not set explicitly the OS and the arch.

By the way, is your OS built for Aarch32 or Aarch64?

Thanks

**Comment by AnthonyARM** [comment]
Can you try to do `uname -p` to check your OS is indeed aarch64 ?

**Comment by xtanitfy** [comment]
Yes.The resault is 'aarch64'.

**Comment by xtanitfy** [comment]
The problem is solved after I run:
scons Werror=1 debug=0 neon=1 opencl=0 build=native -j8

It seemds like it  selected 'arch=armv7-a' automatically.

Thank you  very much !

**Comment by gmiodice** [comment]
Perfect @xtanitfy and thanks for reporting. I close the ticket but feel free to open another one if you need any further help

**Comment by xtanitfy** [comment]
OK,thanks!

**Comment by xtanitfy** [comment]
I have tested ‘squeezenet_v1_1’ .I find the time is 200ms every frame but ncnn is 75ms every frame . 
 I think I must have gone wrong insomewhere.

**Comment by xtanitfy** [comment]
I changed the version and everything is well. The time is 60ms every frame on 'squeezenet_v1_1'.
