### ISSUE TITLE
Channel-wise softmax in NCHW format support

### ISSUE THREAD

**Issue by BhaskarsarmaP** [ARM-software/ComputeLibrary#464]
Hi,
As per this raised issue #401

In CUDNN and MKLDNN, they are doing the channel wise softmax when the inputs and outputs are of the form NCHW.
For my Query, Our Input has 3 channels  , Height and width 32 and 32 respectively.They are implemeting like exp(1st)/(exp(1st)+exp(1025th)+exp(2049th)) elements. But I was unable to reproduce the same in our  ARM Compute Library. Here we are getting exp(1st)/(sum of exp(all 3072)) elements.
Is there a way to execute the softmax layer similar to mkldnn and cudnn in  ARM COMPUTE LIBRARY

**Comment by GeorgeARM** [comment]
We have marked this work as a feature request and will prioritize accordingly. For now you can do the above by performing  a permute->softmax->permute which is not the most efficient solution.

**Comment by nhkrishna** [comment]
Hi @GeorgeARM 

Can you please elaborate how permute->softmax->permute will perform softmax classifier in channelwise ?

**Comment by nhkrishna** [comment]
Thanks for your reply @GeorgeARM 
I will try it and get back to you.

**Comment by ManubARM** [comment]
Have you tried @nhkrishna in the end?

**Comment by nhkrishna** [comment]
Yes i have tried using permute->softmax->permute. It works as required.
