### ISSUE TITLE
Problem on average pooling

### ISSUE THREAD

**Issue by duseok** [ARM-software/ComputeLibrary#467]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

- arm_compute_version=v18.05
 Build options: {'embed_kernels': '1', 'arch': 'arm64-v8a', 'opencl': '1', 'neon': '1', 'asserts': '1', 'debug': '0', 'os': 'android', 'Werror': '1'} Git hash=b3a371bc429d2ba45e56baaf239d8200c2662a74 / **Galaxy S9+**

- arm_compute_version=v18.05
 Build options: {'embed_kernels': '1', 'opencl': '1', 'neon': '1', 'asserts': '0', 'debug': '0', 'Werror': '1'} Git hash=b3a371bc429d2ba45e56baaf239d8200c2662a74 / **Odroid XU4**

**Platform:** Galaxy S9+(Android), Odroid XU4(Linux)

**Operating System:** Android 8.0.0, Linux

**Problem description:**
While I was using ACL core and runtime functions, I have found that CLPoolingLayer does not work properly with setting of 3x3 kernel and global pooling. 

I have checked CLPoolingLayer with 2x2, 4x4, 5x5 and 7x7 kernels setting, and those are working properly.

So, I have tested 5x5 kernel with padding and 3x3 kernel without padding on same layer. 5x5 kernel returned right answer, but 3x3 kernel returned wrong answer.

Please check CLPoolingLayer with 3x3 setting.

Thank you.
P.S. NEPoolingLayer is working properly with 3x3 setting.

**Comment by AnthonyARM** [comment]
Please provide a repro case showing how you've initialised the tensors, and which arguments you pass to the `CLPoolingLayer`

None of the existing tests seem to be failing (You can see the combinations we test [here](https://github.com/ARM-software/ComputeLibrary/blob/master/tests/validation/CL/PoolingLayer.cpp)) but it might be that we've got a gap in our validation.

**Comment by GeorgeARM** [comment]
Hello @duseok,

Can you apply the following diff:
```
diff --git a/tests/datasets/ShapeDatasets.h b/tests/datasets/ShapeDatasets.h
index a5620ff..a5af534 100644
--- a/tests/datasets/ShapeDatasets.h
+++ b/tests/datasets/ShapeDatasets.h
@@ -550,7 +550,8 @@ public:
                      TensorShape{ 27U, 27U, 1U, 3U },
                      // Batch size 4
                      TensorShape{ 31U, 31U, 3U, 4U },
-                     TensorShape{ 34U, 34U, 2U, 4U }
+                     TensorShape{ 34U, 34U, 2U, 4U },
+            TensorShape{ 3U, 3U, 1000U }
     })
     {
     }
```
and try to run the GlobalPooling tests with the following command
`./arm_compute_validation --filter=CL/GlobalPoolingLayer/*`

Check if this will report any errors

**Comment by duseok** [comment]
I checked the validation. And I found that there was a bug in my code when calculating the padding of last layer's output feature.

Thanks for your help.
