### ISSUE TITLE
'std::length_error' what(): basic_string::_S_create

### ISSUE THREAD

**Issue by aivanis** [ARM-software/ComputeLibrary#468]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
`{'embed_kernels': '1', 'opencl': '0', 'pmu': '1', 'arch': 'armv7a', 'standalone': '0', 'neon': '1', 'build_dir': 'linux-armv7a-neon', 'debug': '0', 'validation_tests': '0', 'examples': '1', 'asserts': '0', 'mali': '1', 'benchmark_tests': '0', 'compiler_cache': 'ccache', 'os': 'linux', 'Werror': '1'} `

**Platform:**
Asus Tinker Board

**Operating System:**
Linux tinkerboard 4.4.71+ #1 SMP Wed Nov 15 14:31:48 CST 2017 armv7l GNU/Linux

**Problem description:**
I downloaded precompiled libraries v18.05 and I am using the following command to build the neon_convolution example:
`g++ examples/neon_convolution.cpp utils/Utils.cpp -I. -Iinclude -std=c++11 -mfpu=neon -Llib/linux-armv7a-neon -larm_compute -larm_compute_core -o neon_convolution`
and then this command to run it:
`LD_LIBRARY_PATH=lib/linux-armv7a-neon ./neon_convolution`

The output I get is:
`./neon_convolution`

`Usage: ./build/neon_convolution [input_image.ppm]`

`No input_image provided, creating a dummy 640x480 image`
`terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_S_create`
`Aborted`

As I found out the error is being caused by line 100:
`conv3x3.run();`

Can you help me resolve this?

**Comment by AnthonyARM** [comment]
What version of g++ are you using?
The binaries are built with g++ 4.9
So either cross compile the example using the same Linaro cross compiler or if you want to build on the board, just rebuild the library. (Should be pretty straight forward: there aren't any external dependencies to build)

**Comment by aivanis** [comment]
g++ version is 
`g++ (Debian 6.3.0-18+deb9u1) 6.3.0 20170516`
Thank you for help. Rebuilding the library on the device solved the problem.
