### ISSUE TITLE
Mean And Variance API question

### ISSUE THREAD

**Issue by abhajaswal** [ARM-software/ComputeLibrary#470]
Actaully I want to know , Is there any kernel in ACL  where i could calculate mean and variance of the input buffer.?
I am trying to find the documentation for same, but since i am new to ACL unable to get required 
API.

Comput library version : 18.02

Using Neon and open CL on arm.

**Comment by AnthonyARM** [comment]
You've got [NEMeanStdDev](https://arm-software.github.io/ComputeLibrary/v18.03/classarm__compute_1_1_n_e_mean_std_dev.xhtml#a08ebd3b5f0e06c72c512d799cd9fccd2) and [CLMeanStdDev](https://arm-software.github.io/ComputeLibrary/v18.03/classarm__compute_1_1_c_l_mean_std_dev.xhtml)
And you can have a look at the [validation tests](https://github.com/ARM-software/ComputeLibrary/blob/master/tests/validation/fixtures/MeanStdDevFixture.h#L56) to see how to use them.

Hope this helps,

PS: Please switch to 18.05 if possible.

**Comment by abhajaswal** [comment]
Thanks for your info
