### ISSUE TITLE
Whether I can implement SVM with this Lib

### ISSUE THREAD

**Issue by cmyf123** [ARM-software/ComputeLibrary#472]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

**Platform:** raspberry pi3b

**Operating System:** debian 9

**Problem description:** Can I write SVM using ComputeLibrary? If yes, what interfaces should I used?

**Comment by AnthonyARM** [comment]
What do you mean by SVM ? Shared Virtual Memory or Support Vector Machine ?

**Comment by gmiodice** [comment]
Hi @cmyf123,

if you would like to write a Support Vector Machine function using the compute library I would suggest to have a look at our implementation for HOG. In that case SVM is only implemented for being used with HOG but it could be potentially extended to be used for other scopes as well.

// HOG detector function
https://github.com/ARM-software/ComputeLibrary/blob/master/src/runtime/NEON/functions/NEHOGDetector.cpp

https://github.com/ARM-software/ComputeLibrary/blob/master/src/core/NEON/kernels/NEHOGDetectorKernel.cpp

**Comment by mpekatsoula** [comment]
Closing, reopen if needed.
