### ISSUE TITLE
Canny Edge returns unusable data from imported opencv image

### ISSUE THREAD

**Issue by i7clock** [ARM-software/ComputeLibrary#474]
arm_compute_version=v18.03 Build options: {'opencl': '0', 'neon': '1', 'examples': '1', 'asserts': '0', 'debug': '0', 'Werror': '1', 'build': 'native'} Git hash=c3f34a43ffb5d52ee4a4e9f7b1bf4c6c002aeebb

**Platform:** armv7

**Operating System:** Linux

**Problem description:** I have implemented the canny edge neon like it is done in the NECannyEdge.cpp file to better understand what is happening. I copy the data of the result into an opencv Mat and preserve the pointer to it like that.
`ptr = (unsigned char*)malloc(mat.cols*mat.rows*sizeof(unsigned char));`
`std::memcpy(ptr, matACL.buffer(), sizeof *matACL.buffer());`
`result = cv::Mat(mat.rows, mat.cols, CV_8UC1, ptr);`

The image sometimes showes a correct canny edge result but most of the time it shows random maybe unfinished data.

I checked if it might be a race condition but the implementation should be single threaded and I can't figure out where the problem is. Does anyone have an idea?

Greetings, i7clock

**Comment by i7clock** [comment]
![screen shot 2018-06-26 at 11 53 32](https://user-images.githubusercontent.com/7429753/41904000-9dd3eeaa-7937-11e8-827f-6bae31ba5186.png)

Example of data returned by the canny edge...

**Comment by AnthonyARM** [comment]
ACL buffers are padded, therefore you cannot use memcpy to copy data in one block, you have to copy one row at the time (See comment in [this thread](https://github.com/ARM-software/ComputeLibrary/issues/379#issuecomment-379207850)

Also `sizeof(*matACL.buffer())` is going to be `sizeof(uint8_t)` i.e 1, not the size of your actual buffer.
The allocation size can be accessed by doing `matACL.info()->total_size()`

Hope this helps,

**Comment by i7clock** [comment]
Hi Anthony,
thanks for your reply! I see so I have tried the following:
I don't know what batch is so I put 0
```
for(unsigned int z = 0 ; z < 0 ; ++z)
{
    for (unsigned int y = 0; y < leftEye.rows; ++y)
    {
        memcpy(ptr + z * (mat.cols * mat.rows) + y * mat.cols, matACL.buffer() +
        matACL.info()->offset_element_in_bytes(Coordinates(0, y, z)), mat.cols * 
        sizeof(unsigned char));
    }
}
```
and this:

```
Window output_window;
output_window.use_tensor_dimensions(shape, Window::DimY);
Iterator output_it(&matACL, output_window);
execute_window_loop(output_window,
[&](const Coordinates & id)
{
    memcpy(ptr + id.z() * (mat.cols * mat.rows) + id.y() * mat.cols, output_it.ptr(), mat.cols * sizeof(unsigned char));
}, output_it);
```

And I initialized ptr like that:
`ptr = (unsigned char*)malloc(mat.cols*mat.rows*sizeof(unsigned char));`

But unfortunately I get similar results...
`matACL` was initialized with data from an opencv mat, which worked in other kernels perfectly! I used thresholding, histogram equalization and so on.

What am I missing here? Thanks in advance

**Comment by AnthonyARM** [comment]
Can you try loading from a PPM image to start with (Will eliminate the potential issues of importing data from OpenCV)
And can you post the entire test code please. (I assume it's fairly small ?)

**Comment by i7clock** [comment]
Unfortunately I cannot post the entire code because I am porting a project from opencv to ACL.
I have imported the data from opencv like this:
```
arm_compute::Image matACL;
matACL.allocator()->init(arm_compute::TensorInfo(mat.cols, mat.rows, arm_compute::Format::U8));
matACL.allocator()->allocate();
matACL.allocator()->import_memory(arm_compute::Memory(mat.data));
```

With this I was able to use opencv and ACL for preprocessing on the same data which was very convenient.

**Comment by AnthonyARM** [comment]
1) Padding requirements are set by the function during the `configure()` stage, therefore you need to do:
```cpp
arm_compute::Image matACL;
matACL.allocator()->init(arm_compute::TensorInfo(mat.cols, mat.rows, arm_compute::Format::U8)); // Initialise tensor's dimensions
myFunction.configure(matACL); // Padding requirements filled by the function
matACL.allocator()->allocate(); //Only allocate after all the configure calls using this image
```
2) `allocate()` will allocate some memory for the tensor, whereas `import_memory` will just use the pointer provided as memory for the tensor, therefore you should only use one or the other.

3) It's the user's responsibility to make sure that the pointer provided to `import_memory` has the correct padding. Which in your case is wrong as `mat.data` doesn't have any padding.

4) For computer vision functions (This will not work for machine learning functions), you can run on a buffer without padding, but in this case the processing window will be shrunk (i.e the border pixels won't be processed), but if your objective is to avoid any copy between OpenCV and ACL then that might be a valid solution for you.
In order to shrink the execution window you need to allocate your tensor **before** the call to configure:
```cpp
arm_compute::Image matACL;
matACL.allocator()->init(arm_compute::TensorInfo(mat.cols, mat.rows, arm_compute::Format::U8)); // Initialise tensor's dimensions
matACL.allocator()->import_memory(arm_compute::Memory(mat.data)); //Allocate the image without any padding.
myFunction.configure(matACL); // Tensor already allocated, so can't increase the padding: will shrink the execution window instead.
```

Looking at your output image: are you sure you haven't swapped the width and height ?

**Comment by i7clock** [comment]
Thank you very much for your explanation! 
I am pretty sure that I haven't swapped width and height, but I tried it the other way anyway, which gives me the same result unfortunately.

I am doing what you described in 4. but maybe you are right and the whole thing doesn't work for canny.

My question then: How do I copy data from an opencv mat into a ACL Tensor? What Information does the Tensor need additionally which is provided in a PPM Image for example?

Appreciate your help!!

**Comment by AnthonyARM** [comment]
It's really odd because the output image of Canny Edge should be a binary map (Only black or white pixels), the fact that you've got grey pixels in there suggests something is still wrong with the copy.
Could you try to use [save_to_ppm()](https://github.com/ARM-software/ComputeLibrary/blob/v18.05/utils/Utils.h#L682) ?

**Comment by i7clock** [comment]
I exported to ppm and all the images are black...

**Comment by i7clock** [comment]
![lefteye ppm](https://user-images.githubusercontent.com/7429753/41970171-29813a98-7a0a-11e8-93f6-e0dbbbcc6b48.png)

**Comment by i7clock** [comment]
The examples work for me too. I guess its the import of the data. 

I have data coming from a camera in a raw unsigned char pointer, which means I only have color (grayscale) and position. how would I initialize a tensor with that?

**Comment by AnthonyARM** [comment]
The code above should work:
```cpp
arm_compute::Image matACL;
matACL.allocator()->init(arm_compute::TensorInfo(mat.cols, mat.rows, arm_compute::Format::U8)); // Initialise tensor's dimensions
matACL.allocator()->import_memory(arm_compute::Memory(mat.data)); //Allocate the image without any padding.
```
I guess you could try to save that Image to ppm to check it's valid.

Also make sure the library is compiled with either `asserts=1` or `debug=1` for now to enable parameters validation.

**Comment by i7clock** [comment]
I saved this to ppm and it is valid. I compiled with `asserts=0` and `debug=0` for better performance.

**Comment by cnhzcy14** [comment]
Hi @i7clock, I'm looking for a method to import cv::Mat to arm_compute::Image. I used the following code:
 `matACL.allocator()->import_memory(arm_compute::Memory(mat.data));`
However the compiler report error at here. Is your mat a cv::Mat? 
Thanks!

**Comment by i7clock** [comment]
Hi @cnhzcy14 ,
I used v18.03 and it worked for me ... I now switched to 18.05 and I also get a compile error. Maybe @AnthonyARM could help?

Yes I was using a cv::Mat!

Best wishes.

**Comment by AnthonyARM** [comment]
What's the error ?

**Comment by i7clock** [comment]
I saw that you changed the Memory Interface and added IMemoryRegion. You have to implement the Interface @cnhzcy14. Here is a sample of what I thought might work:

you find the interface here
`#include <arm_compute/runtime/IMemoryRegion.h>`

```
class cvMat2ACLMemory : public arm_compute::IMemoryRegion
{
public:
	cvMat2ACLMemory(std::shared_ptr<uint8_t> memory)
		: arm_compute::IMemoryRegion(sizeof(memory))
		, _memory(nullptr)
		, _memory_owned(std::move(memory)) 
	{
		
	}
	cvMat2ACLMemory(uint8_t *memory)
		: arm_compute::IMemoryRegion(sizeof(memory))
		, _memory(memory)
		, _memory_owned(nullptr) 
	{
		
	}
	void *buffer() override
	{
		return _memory;
	}
	void *buffer() const override
	{
		return _memory;
	}
	void **handle() override
	{
		return (void**)&_memory;
	}
private:
	uint8_t *_memory;
	std::shared_ptr<uint8_t> _memory_owned;
};
```

And then pass like the following:

`imgACL.allocator()->import_memory(arm_compute::Memory(new cvMat2ACLMemory(imgCV->data)));`

where `imgACL` is the arm compute library Image or Tensor and `imgCV` is the OpenCV Mat

I hope this works for you! Greetings

**Comment by cnhzcy14** [comment]
Yes it works! Thank you very much @i7clock !
Here is the error @AnthonyARM : 
`error: no matching function for call to ‘arm_compute::Memory::Memory(uchar*&)’ src.allocator()->import_memory(arm_compute::Memory(greyMat.data));`
I think the feature of importing external data is quite useful.

**Comment by i7clock** [comment]
I asked this on [stackoverflow](https://stackoverflow.com/questions/52703756/arm-compute-library-canny-edge-returns-unusable-data-from-imported-opencv-imag)

**Comment by i7clock** [comment]
So I will close tis because I've resolved the issue for now:

Function to convert an ACL Image to OpenCV Mat:

`	void ACLImageToMat(arm_compute::Image &aCLImage, cv::Mat &cVImage, std::unique_ptr<unsigned char[]> &cVImageDataPtr)
	{
		size_t width  = aCLImage.info()->valid_region().shape.x();
		size_t height = aCLImage.info()->valid_region().shape.y();
		
		cVImageDataPtr = std::make_unique < unsigned char[]>(width*height);
		auto ptr_src = aCLImage.buffer();
		
		
		arm_compute::Window input_window;
		input_window.use_tensor_dimensions(aCLImage.info()->tensor_shape());
		arm_compute::Iterator input_it(&aCLImage, input_window);
		int counter = 0;
		arm_compute::execute_window_loop(input_window,
			[&](const arm_compute::Coordinates & id)
			{
				*reinterpret_cast<unsigned char *>(cVImageDataPtr.get() + counter++) = ptr_src[aCLImage.info()->offset_element_in_bytes(id)];
			},
			input_it);

		
		cVImage = cv::Mat(cVImage.rows, cVImage.cols, CV_8UC1, cVImageDataPtr.get());
	}`

Another important thing for canny was to have an EXTRA OUTPUT image, which is allocated AFTER configuring the canny edge detector.

**Comment by julled** [comment]
For current acl (19.02) there is a easy way to import and export images. See #662 for the code.
