### ISSUE TITLE
Memory requirement For GEMM/ DIRECT convolution for Datatype F32

### ISSUE THREAD

**Issue by abhajaswal** [ARM-software/ComputeLibrary#476]
Compute library version - 18.05
Platform : arm7a
Operating System: linux

Can you please let me know the exact Memory requirement  for convolution layer?
Using following example :
If i Use CLConvolutionLayer of size 272x208x3 input tensor shape and output tensor shape 272 x 208x 32,  kernel size 9x9 ,padstrideinfo(1,1,4,4) 

I observe that the memory required if i use this  single convolution layer in tensorflow is lesser than that 
ACL convolution layer for GEMM as well as direct.

I want to estimate memory requirement for a network using ACL on my board due to memory limitation of GPU and CPU.
My application crashes for a higher resolution image of 714x442 (wxh) for single convolution for above configurations due to less GPU memory.

NEON equivalent ACL API's for convolution shows around 900 MB for 714x442 (wxh) for the same convolution layer configuration. This quite high memory requirement

Please share me some information regarding the memory requirements of ACL GPU/ Neon layers if possible.

Awaiting your reply

**Comment by abhajaswal** [comment]
Please provide some insight!!

**Comment by AnthonyARM** [comment]
It's not straight forward to answer, you can see the size of the input tensor once they've been allocated by doing `tensor->info()->total_size()` but then you also need to take into account the memory used by the temporary tensors inside the function.
The easiest way I would say is to check the amount of memory used by the process in the system.
Also for better memory re-use you should use the Graph layer as it will re-use memory for the temporary buffers in different layers.

**Comment by GeorgeARM** [comment]
Hello @abhajaswal,

In general, NEDirectConvolutionLayer should have much lower memory requirements that the NEGEMMConvolutionLayer.
Your problem though might relate to #479 if you see a huge amount of memory requirements for NEGEMMConvolutionLayer.
Eitherway, as @AnthonyARM mentioned you can use the graph API to implement your pipeline, which will reuse any memory when possible among different layers.
If you want more insight on how this can be done manually have a look [here](https://arm-software.github.io/ComputeLibrary/v18.05/architecture.xhtml#S4_7_memory_manager)

**Comment by abhajaswal** [comment]
Thanks a lot for your reply.currently graph interface does not support the detection window, prior box and permute and  concatenate layer interfaces.. so for the ssd network I will  to use direct api..
