### ISSUE TITLE
Needed Support to obtain Max Pooling Layer Indices and Unpooling Layer

### ISSUE THREAD

**Issue by BhaskarsarmaP** [ARM-software/ComputeLibrary#477]
using Latest ARM Compute Library 18.05
ARM_NEON (ARM Cortex v7)
Working on Raspberry Pi3 -- Arch Linux
I couldn't find any method to obtain Max Pooling Layer Indices. Could you provide me a method to obtain Max Pooling Layer Indices ?
Is there any Implementation of Unpooling Layer in ARM Compute Library?

**Comment by AnthonyARM** [comment]
Hi @BhaskarsarmaP ,
Could you please provide us with more information about these layers and examples of networks that are using them ?
Thanks

**Comment by nevenpiculjan** [comment]
I also need unpooling layer. Segmentation neural networks are using them, for example SegNet: http://mi.eng.cam.ac.uk/projects/segnet/ or UNet: https://arxiv.org/pdf/1505.04597.pdf. What is your estimation when that layer could be implemented?

**Comment by AnthonyARM** [comment]
Thanks for the information, we'll try to fit it in the November release if we can.

**Comment by morgolock** [comment]
Hi @BhaskarsarmaP 

Please take a look at the patch https://review.mlplatform.org/c/ml/ComputeLibrary/+/3289 implementing basic support for MaxUnpooling in the Neon backend.

Hope this helps.
