### ISSUE TITLE
ERROR in debug mode : /NEGEMMConvolutionLayer.cpp:575: Output shape does not match the expected one

### ISSUE THREAD

**Issue by ved27** [ARM-software/ComputeLibrary#478]
Hi,

version  : Computelibrary 18.05 
Platform : arm7a
Operating System: linux

I use ACL-NEON to implement tensorflow based NN.

The NEConvolutionlayer (internally calls NEGEMMConvolutionLayer) ran successfully after compiling with debug mode OFF.
When I tried running the code compiled with debug mode ON,  
***ERROR in debug mode : /NEGEMMConvolutionLayer.cpp:575: Output shape does not match the expected one***
was the error it threw during runtime

Point to note: (DEBUG is ON) 
 I did not initialize the output tensor as it would be auto initialized in the NEGEMMConvolutionLayer::configure() . But, NEConvolutionlayer  calls NEGEMMConvolutionLayer::validate() before configuring. 
So, the following line in NEGEMMConvolutionLayer::validate():
   **ARM_COMPUTE_RETURN_ERROR_ON_MSG((output->dimension(idx_width) != conv_w) || (output->dimension(idx_height) != conv_h), "Output shape does not match the expected one"); 
threw the error since it checks the output dimension even before auto initializing .** 
The above same Debug macro check is there in the NEGEMMConvolutionLayer::configure() also .

So, is it a bug that the macro is called in validate()  ? Kindly let me know if I'm right.
Also please let me know if I can opt for auto initialization of output tensor in the code compiled with debug  ON .

Awaiting your reply,

**Comment by ved27** [comment]
Hi,

Did anyone get a chance to look into this ?


Thank you

**Comment by gmiodice** [comment]
Hi @ved27,

could you please report the configuration you are running with NEGEMMConvolutionLayer?

Thanks

**Comment by ved27** [comment]
Hi,

 scons Werror=1 -j8 debug=1 asserts=0 neon=1 opencl=1 openmp=1 cppthreads=1 embed_kernels=1 os=linux arch=armv7a

I did 
conv1.configure(&src, &conv1_weight, nullptr, &dst_conv1,  PadStrideInfo(1, 1, 4, 4))    where conv1 is NEConvolutionLayer

And I did not initialize dst_conv1 as mentioned above. as it would be auto initialized in configure of NEGEMMConvolutionlayer

**Comment by gmiodice** [comment]
Hi,

from the above configuration it seems you have:

stride_x = 1
stride_y = 1
pad_x = 4
pad_y = 4

so I assume your kernel size is 9x9. Is it correct?

**Comment by ved27** [comment]
Hi,

Yes . Kernel size is 9x9 in this case.

**Comment by gmiodice** [comment]
Hi @ved27,

many thanks for providing all these information. Could you also provide the shapes for your input tensor and weights as well?

**Comment by gmiodice** [comment]
Perfect @ved27 ,

I check your test case and I let you know as soon as possible.

Many thanks

**Comment by gmiodice** [comment]
Hi @ved27,

the problem seems related to the wrong initialization of the output. Could you try to initialize manually the output before configuring the function? The output should have the same shape of the input but with different number of channels:

i.e. TensorInfo(TensorShape(272, 208, 32), 1, DataType::F32)

I flag this issue as "bug"

Thanks

**Comment by ved27** [comment]
Hi @gmiodice

Yea, It works in the case of  manually initializing the output before the configure() is called. 


Thank you ,

So, probably in
NEGEMMConvolutionLayer::validate():
**ARM_COMPUTE_RETURN_ERROR_ON_MSG((output->dimension(idx_width) != conv_w) || (output->dimension(idx_height) != conv_h), "Output shape does not match the expected one");
**
above line can be removed as the same assertion is there in NEGEMMConvolutionLayer::configure(). so that auto initialization does not throw error in DEBUG.


Thank you @gmiodice ,

**Comment by mpekatsoula** [comment]
Closing, reopen if needed
