### ISSUE TITLE
How to release the graph correctly?

### ISSUE THREAD

**Issue by MaeThird** [ARM-software/ComputeLibrary#479]
Hi,I'm back.
Is there a gracefully way to release the graph memory? Actually in my tests the model is just no more than 20M,with all the optimization opened ,the running memory is above 250M! It's horrible because my board has only 512M memory.

**Comment by AnthonyARM** [comment]
Hi,
- Is this NEON or CL ? (If NEON, how many threads ?)
- Are you using the Graph API or just using the functions ?

**Comment by MaeThird** [comment]
@AnthonyARM  NEON with 4 threads. GraphAPI used.

**Comment by AnthonyARM** [comment]
And I assume you're using 18.05, right ?

There is a bug in [allocate_workspace](https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/NEON/AssemblyHelper.h#L139), there is no need to multiply by `num_threads` here as the number of threads is already taken into consideration when calculating `workspace_size` in [get_working_size()](https://github.com/ARM-software/ComputeLibrary/blob/master/src/core/NEON/kernels/arm_gemm/gemm_interleaved.hpp#L483)

**Comment by MaeThird** [comment]
@AnthonyARM  Yes,I'm using 18.05. I'll try it later.Thank u.
