### ISSUE TITLE
benchmark numbers

### ISSUE THREAD

**Issue by mkamrao** [ARM-software/ComputeLibrary#48]
Hello

I am implementing a neural network (similar to Alexnet) on a ARM Neon based platform using the ARM Compute library.
I wanted to compare the performance numbers with the expected numbers - 
Do you have any performance bench mark numbers (or execution times) for different layers of neural n/w(Convolution layer, Fully connected etc.).

Thanks
kamrao

**Comment by mkamrao** [comment]
Hello

Do you have any information/suggestions on this. Thanks.

kamrao

**Comment by GeorgeARM** [comment]
Hello @mkamrao,

I am closing this issue as in the latest v17.09 release a custom-made testing and validation suite has been added to Compute Library. Benchmarking suite includes tests for all the layer of well known networks and some full network runs as well. We will keep enriching this suite as we go.

Reopen if needed.
