### ISSUE TITLE
Performance difference between A73 and A53.

### ISSUE THREAD

**Issue by drneerajgoel** [ARM-software/ComputeLibrary#481]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**  v18.5

**Platform:**  Octa core A73-A53

**Operating System:** Linero (kernel 4.14.0-rc7)

**Problem description:** 

I am running graph examples given in compute library (like graph_resnet50) on Octa core (A73-A53). I see some surprising performance figures. If I use four cores of A73 (using taskset), I get much higher performance for running resnet50, then using all 8 cores. To maximize the performance of 8 cores, I create 8 threads instead of default 4, but  it does not result in any gain over using 4 big cores. 

On investigations, I found that some code in arm compute is specifically written for A53. For example:
(a) A53 always uses GEMM as convolution method, while A73 (being specified as generic core) uses Winograd.
(b) A53 uses a64_sgemm_asimd_12x8_a53 as the kernel function, while A73 (being generic) uses generic kernel a64_sgemm_asimd_12x8

Since both of above examples effect the performance of Convolution layer, which is most compute intensive layer in CNN, overall impact on performance is a lot.

My question is:
(i) Are these optimizations not required for A73 or for that matter any other core? In other words, why some specific functions are used only for A53?
(ii) Can there be some other reason, of low performance of using all 8 cores.

Regards,
Neeraj

**Comment by AnthonyARM** [comment]
1) The design of the A53 is significantly different from the other CPUs that it needs its own version.
2) The main reason is the scheduler, not the actual kernels. The current scheduler is just provided as an example of how to parallelise kernels execution, it is very basic: it takes the workload and divides it by the number of threads, which means your small cores end up having as much to process as the big cores and obviously become the bottleneck. 
Finally, there is a risk of a thread migrating from one type of core to a different type half way through execution which means you might end up for example executing the generic kernel on an A53 which would make things even worse.

**Comment by martinl** [comment]
would it be possible to run 2 processes in parallel, one on A73 with 4 threads and second on A53 with 4 threads

**Comment by AnthonyARM** [comment]
Yes, you can do that using `taskset 0f` on one process and `taskset f0` on the other
