### ISSUE TITLE
Output mismatch in CLDeconvolutionLayer with reference to Tensorflow data

### ISSUE THREAD

**Issue by ved27** [ARM-software/ComputeLibrary#483]
Hi,

version : Computelibrary 18.05
Platform : arm7a
Operating System: linux

I use ACL- CL to implement tensorflow based NN.

Input size : 48 x 32 x 128 (W H C)
weights : 3 x 3 x 128 x 64 (W H IFM OFM )  and weights across W x H are rotated 
stride : 2
PadStrideInfo; (2,2,1,1) ; Inner border right = 1 , inner border top = 1
(Given tensor flow padding = "SAME" )
Output size : 96 x 64 x 64 (W H C) 

The above padstrideinfo gives me the correct output dimensions , but the data mismatched 
 and misplaced at regular intervals of pixels.

Kindly help me with this,

**Comment by gmiodice** [comment]
Hi @ved27 ,

what do you mean for "weights across W x H are rotated"? Does it mean the "height" is the fast changing dimension?

Thanks

**Comment by gmiodice** [comment]
Many thanks @ved27 for your quick reply. In order to reproduce the issue, could you report the piece of code you are testing this function with?

**Comment by ved27** [comment]
Hi @gmiodice ,

Sorry for delayed response as I went offline 
I'm unable to share the code on public domain , 

but I request you to kindly refer to the following details  in addition to the info mentioned in the earlier comment: 

PadStrideInfo; (2,2,1,1) ; Inner border right = 1 , inner border top = 1
(Given tensor flow padding = "SAME" )
I'm unable to match the output with reference data 

But now, I tweaked padstride info to the following 
PadStrideInfo; (2,2,2,1) ; Inner border right = -1 , inner border top = 1 , to keep the output dimensions same .
Output data is matching with the dumped data from Tensorflow.

But  "Inner border right" is of type **unsigned int** . 

Kindly look into this,

**Comment by gmiodice** [comment]
Hi @ved27,

I was checking at your output size but are you sure the dimensions are correct?
Input size : 48 x 32 x 128 (W H C)
Output size : 96 x 64 x 64 (W H C) ??

Maybe is:
Input size : 96 x 64 x 64 (W H C)
Output size : 48 x 32 x 128 (W H C)
?

**Comment by ved27** [comment]
Hi @gmiodice ,

Yes. Please not that this is Deconvolution with stride 2 . So the input dimensions are going to be doubled


Thank you,

**Comment by ved27** [comment]
Hi @gmiodice

Sorry for delayed response as I am away
I shall check this and let you know,

Meanwhile can you please let me know your choice of values for 

1 ) padstrideinfo 
2 ) inner border right ,
3) inner border top
 to be applied on the previously mentioned input to get the mentioned output

Thank you,

**Comment by mpekatsoula** [comment]
Please check the answers on this issue: https://github.com/ARM-software/ComputeLibrary/issues/523
Closing, reopen if needed
