### ISSUE TITLE
Performance/support of 8 bit operations

### ISSUE THREAD

**Issue by drneerajgoel** [ARM-software/ComputeLibrary#485]
**Output of 'strings libarm_compute.so | grep arm_compute_version':** v18.5

**Platform:** Octa core A73-A53

**Operating System:**: Linero/Linux

**Problem description:**

My observations:

-  I see the performance of floating point benchmark (graph_mobilenet) and 8-bit fixed point benchmark (graph_mobilenet_qasymm8) is almost similar. 

- I also see the primary function to compute convolution (a64_gemm_u8_4x4) uses 32 bit number. Thus, operation should be atleast 4 times faster than corresponding 32 bit fixed point. And multiple time faster than floating point. 

- I see the notice on main page: "Deprecation notice: QS8 and QS16 data types will be removed in the next release"

Based on these observations, I have the following questions:

1. Why performance of fixed point and floating point application is similar?
2. Given the model size, and performance, fixed point DNN are more suitable for mobile/embedded computing. Will they not be supported in compute library?
3. For fixed point arithmetic, NEON can provide good speed up. Still why it is not used.

Please let me know, if I am missing anything.

Thanks and regards,
Neeraj

**Comment by gmiodice** [comment]
Hi @drneerajgoel,

how many times do you run the benchmarks? Do you take the average of the execution times or the minimum one? 

Regarding the deprecation of QS8 and QS16, the main reason behind that is that, as far as we know, these are not used by any of the major ML frameworks. This deprecation concerns only 8 bit and 16 bit fixed point but we will keep QASYMM8 (Asymmetric 8bit integer with scale / offset).
Feel free to add a comment here: https://github.com/ARM-software/ComputeLibrary/issues/435 to share your concern about this aspect.

Thanks,

**Comment by drneerajgoel** [comment]
Thanks @gmiodice  for your clarification on QASYMM8. 

To average out - I called graph.run() 50 times in a loop.

**Comment by mpekatsoula** [comment]
Hi @drneerajgoel 

Are you observing the same results with v18.08?

**Comment by mpekatsoula** [comment]
Closing, reopen if needed.
