### ISSUE TITLE
NESoftmaxLayer not support S32 type

### ISSUE THREAD

**Issue by jclvsfl** [ARM-software/ComputeLibrary#487]
NESoftmaxLayer Data types supported: QASYMM8/QS8/QS16/F16/F32. If S32 type is support, that is great for me! 

**Output of 'strings libarm_compute.so | grep arm_compute_version':**

**Platform:**  ARM , HI3559A

**Operating System:** Linux 64 Bit

**Problem description:**

**Comment by AnthonyARM** [comment]
Hi,
What's your use case ? In which case do you need S32 Softmax ? 
That seems a bit odd given that none of the other functions support this data type.

**Comment by jclvsfl** [comment]
Hi,
The softmax function cost too much time  when use cpu resource,  There is no other way to Improve the overall performance of my SSD model 。So i want to use the ACL NESoftmaxLayer to repace the fuction like it:

#define QUANT_BASE 4096 
static int ssd_softmax(int* ps32Src, int s32ArraySize, int* ps32Dst)
{
    /***** define parameters ****/
    int s32Max = 0;
    int s32Sum = 0;
    int i = 0;
    for (i = 0; i < s32ArraySize; ++i)
    {
        if (s32Max < ps32Src[i])
        {
            s32Max = ps32Src[i];
        }
    }
    for (i = 0; i < s32ArraySize; ++i)
    {
        ps32Dst[i] = (int)(QUANT_BASE* exp((float)(ps32Src[i] - s32Max) /QUANT_BASE));
        s32Sum += ps32Dst[i];
    }
    for (i = 0; i < s32ArraySize; ++i)
    {
        ps32Dst[i] = (HI_S32)(((float)ps32Dst[i] / (float)s32Sum) * QUANT_BASE);
    }
    return 0;
}

**Comment by morgolock** [comment]
Hi @jclvsfl 

Would it be possible to change your function to take float instead of int?

**Comment by GeorgeARM** [comment]
Hello @jclvsfl,

Don't know why you want S32 instead of float, at it seems you have to do more operations with the suggested code above.
In general we support QASYMM8 for quantized  inputs if you are interested.
Eitherway I am closing this issue. Reopen if needed with an actual use case so that we can schedule this work.
