### ISSUE TITLE
Issue in the case of merging  graph_*.cpp / cl_*.cpp in one file

### ISSUE THREAD

**Issue by ved27** [ARM-software/ComputeLibrary#488]
Hi,

Compute library version : 18.05
platform : arm7.
linux

scons Werror=1 -j8 debug=0 asserts=0 neon=1 opencl=1 openmp=1 cppthreads=1 embed_kernels=1 os=linux arch=armv7a

I am trying to implement the modified mobilenet using examples provided in examples/graph_*.cpp and
example/cl_*.cpp

initially I wrote own cl_mobilenet.cpp , built it and is run very fine.

I changed cl_mobilenet.cpp to graph_mobilenet.cpp and built successfully. 
But   it threw sig fault while accessing the tensors in code.

i.e,
code has tensors allocated but throws nullptr when the file is graph_mobilenet.cpp
when the name of file is changed to cl_mobilenet.cpp , it works correctly

Kindly help me with this,

**Comment by GeorgeARM** [comment]
Hello @ved27,
Can you provide more information? I don't think I understand your problem.

**Comment by ved27** [comment]
Hi @GeorgeARM 

I mean that , I changed the cl_xxx.cpp in the examples to graph_xxx.cpp and compiled.
The file has tensors allocated .
The issue is when accessing the memory, the same tensor throws nullptr in graph_*.cpp , where as it works fine in cl_*.cpp

could you please mention the issue  apparently ?

Thank you,

**Comment by AnthonyARM** [comment]
It's because Graph examples are backend independent, if you instantiate CLTensors in your example then it's CL specific, that's why it doesn't work.
If you want to use CL in your example then you need to add `#define ARM_COMPUTE_CL` at the top, I think it should fix the issue.

**Comment by ved27** [comment]
Thank you @AnthonyARM
