### ISSUE TITLE
result mismatch between CLConvolutionLayer and NEconvolutionLayer

### ISSUE THREAD

**Issue by yoyo-zhao** [ARM-software/ComputeLibrary#490]
hi, 
I have been working on accelerating a CNN network with Mali GPU. To validate the result, I build a one-layer conv network with CLConvolutionLayer and input tensor 40x40x3/output tensor 40x40x24/conv kernel 3x3/stride 1/padding 1. It is strange that the elements positioned in output tensor COL 39 and 40 as well as ROW 39 and 40 are all set to 0, while the other elements are correct.
When I change the layer to NEConvolutionLayer, the results are all correct.

arm_compute_version=v18.05 
Build options: {'embed_kernels': '1', 'arch': 'arm64-v8a', 'opencl': '1', 'neon': '1', 'asserts': '1', 'debug': '0', 'os': 'linux', 'Werror': '1'}
Git hash=b3a371bc429d2ba45e56baaf239d8200c2662a74
Platform: Mediatek - MT2712
OS: linux

```c++
// init data tensor
CLTensor* data  = new CLTensor();
const TensorShape input_shape(40, 40, 3);
data->allocator() -> init(TensorInfo(input_shape, 1, DataType::F32));
data->allocator() -> allocate();
data->map(true);
for (int i = 0; i < input_shape.total_size(); i ++) {
    (reinterpret_cast<float *>(data->buffer()))[i] = 1.0;
}
data->unmap();

// init weight tensor
CLTensor* ConvNd_1_weight = new CLTensor();
const TensorShape ConvNd_1_weights_shape(3,3,3,24);
ConvNd_1_weight->allocator()->init(TensorInfo(ConvNd_1_weights_shape,1,DataType::F32));
ConvNd_1_weight->allocator()->allocate();
ConvNd_1_weight->map(true);
for (int i = 0; i < ConvNd_1_weights_shape.total_size(); i ++) {
    (reinterpret_cast<float *>(ConvNd_1_weight->buffer()))[i] = 1.0;
}
ConvNd_1_weight->unmap();

// init output tensor
CLTensor* ConvNd_1 = new CLTensor();
const TensorShape ConvNd_1_shape(40,40,24);
ConvNd_1->allocator()->init(TensorInfo(ConvNd_1_shape,1,DataType::F32));
ConvNd_1->allocator()->allocate();

// init conv layer
CLConvolutionLayer* ConvNd_1_conv = new CLConvolutionLayer();
ConvNd_1_conv->configure(data,ConvNd_1_weight,nullptr,ConvNd_1,PadStrideInfo(1,1,1,1));

// run
CLScheduler::get().sync();
ConvNd_1_conv->run();
CLScheduler::get().sync();
```

results.txt
[result.txt](https://github.com/ARM-software/ComputeLibrary/files/2204205/result.txt)

Did I get something wrong?

**Comment by gmiodice** [comment]
Hi @yoyo-zhao,

would it be possible to see the piece of code you use to print the output values?

Thanks

**Comment by yoyo-zhao** [comment]
hi @gmiodice ,

```c++
        ConvNd_1->map(block);
        ofstream fc1_txt;
        fc1_txt.open("result.txt");
        float *output = reinterpret_cast<float*>(ConvNd_1->buffer());
        for(int i = 0;i<24*40*40;i++){
            fc1_txt<<output[i]<<"\n";
        }
        ConvNd_1->unmap();
        fc1_txt.close();
```

thanks for your reply

**Comment by gmiodice** [comment]
Hi @yoyo-zhao,

I think the problem is related to how you read the values from your output tensor because you are not taking into account the paddings.

can you try to read the output values in the following manner?

```cpp
            printf("\n******Input Image 2 ******* \n");
            ConvNd_1->map(true);
            ConvNd_1->print(std::cout);
            ConvNd_1->unmap();
```

**Comment by yoyo-zhao** [comment]
Hi @gmiodice 
Sure, i just had a try. But nothing different.

**Comment by gmiodice** [comment]
I noticed you are allocating the tensors before configuring CLConvolutionLayer. Could you try to move allocate() after the configuration of the function?

```cpp
// init data tensor
CLTensor* data  = new CLTensor();
const TensorShape input_shape(40, 40, 3);
data->allocator() -> init(TensorInfo(input_shape, 1, DataType::F32));

// init weight tensor
CLTensor* ConvNd_1_weight = new CLTensor();
const TensorShape ConvNd_1_weights_shape(3,3,3,24);
ConvNd_1_weight->allocator()->init(TensorInfo(ConvNd_1_weights_shape,1,DataType::F32));

// init output tensor
CLTensor* ConvNd_1 = new CLTensor();
const TensorShape ConvNd_1_shape(40,40,24);
ConvNd_1->allocator()->init(TensorInfo(ConvNd_1_shape,1,DataType::F32));

// init conv layer
CLConvolutionLayer* ConvNd_1_conv = new CLConvolutionLayer();
ConvNd_1_conv->configure(data,ConvNd_1_weight,nullptr,ConvNd_1,PadStrideInfo(1,1,1,1));

data->allocator() -> allocate();
data->map(true);
for (int i = 0; i < input_shape.total_size(); i ++) {
    (reinterpret_cast<float *>(data->buffer()))[i] = 1.0;
}
data->unmap();

ConvNd_1_weight->allocator()->allocate();
ConvNd_1_weight->map(true);
for (int i = 0; i < ConvNd_1_weights_shape.total_size(); i ++) {
    (reinterpret_cast<float *>(ConvNd_1_weight->buffer()))[i] = 1.0;
}
ConvNd_1_weight->unmap();

ConvNd_1->allocator()->allocate();

// run
CLScheduler::get().sync();
ConvNd_1_conv->run();
CLScheduler::get().sync();
```

**Comment by yoyo-zhao** [comment]
hi @gmiodice 
Thanks for your patience. As you suggested, allocate() should be after configure(). And I found that data->info() was modified after configuration. While its shape remained 40x40x3, the memory layout was resized to 42x42x3 with padding space included. So i had to fill in the input tensor carefully skipping the padding space. Now I can get the expected output tensor using the following code. However, it seems not convenient and maybe low performance. How can I do the job gracefully and efficiently ?

```c++
// fill in input tensor
data->allocator() -> allocate();
data->map(true);
const size_t first_element_offset = data->info()->offset_first_element_in_bytes() / sizeof(float);
const size_t stride_x = data->info()->strides_in_bytes().x() / sizeof(float);
const size_t stride_y = data->info()->strides_in_bytes().y() / sizeof(float);
const size_t stride_z = data->info()->strides_in_bytes().z() / sizeof(float);
for (int i = 0; i < 3; i ++) {
    float* offset = reinterpret_cast<float *>(data->buffer()) + stride_z * i + first_element_offset;
    for (int j = 0; j < 40; j ++) {
        for (int k = 0; k < 40; k ++) {
            offset[k] = 1.0;
        }
        offset += stride_y;
    }
}
data->unmap();
```

**Comment by gmiodice** [comment]
Hi @yoyo-zhao,

happy to know you managed to find the issue. Try to have a look at [here](https://arm-software.github.io/ComputeLibrary/v17.09/architecture.xhtml#S4_6_4_working_with_objects). At that page you can find how to fill a tensor efficiently. For your specific case, I would suggest to copy your input data per row so this means you can use a memset or memcpy for each row

Hope this can help you

**Comment by yoyo-zhao** [comment]
@gmiodice 
Ok. Thank you ~

**Comment by GeorgeARM** [comment]
Resolved. Reopen if needed.

**Comment by blueardour** [comment]
Hi, i met a similar problem.
 However, I didn't observe data->info() change after configration.

`
static void print(ITensorInfo *info)
{
  size_t i; 
  std::cout << "--> ";
  for(i=0; i<info->num_dimensions(); i++) std::cout << info->dimension(i) << ", ";
  std::cout << std::endl;
}`

I use the print funtion to get the data->info().   Is the behavour changed after last time?

**Comment by blueardour** [comment]
// for( unsigned int z = 0; z < batch; ++z)
    // {
    //   for( unsigned int y = 0; y < height; ++y)
    //   {
    //     for( unsigned int x = 0; x < width; ++x)
    //     {
    //       *reinterpret_cast<float*>( input.buffer() + input.info()->offset_element_in_bytes(Coordinates(x,y,z))) = src_data[ z * (width*height) + y * width + x];
    //     }
    //   }
    // }

**Comment by morgolock** [comment]
Hi @blueardour 

I think the way you copy the values into the tensor is wrong, so it's difficult to speculate about results.

![copyinput](https://user-images.githubusercontent.com/5577511/56728043-d11b1f80-6749-11e9-94b5-ba7455e8d92c.png)

Please take a look at  https://arm-software.github.io/ComputeLibrary/v19.02/architecture.xhtml#S4_6_images_tensors for an example on how to copy data into a CLTensor using `execute_window_loop`

**Comment by blueardour** [comment]
Hi, @morgolock 

Thank you for the tip. I successfully get the same result after following your advice.  Great thanks to you~~~
