### ISSUE TITLE
compile failed in fedora28+gcc8.1

### ISSUE THREAD

**Issue by jiulongshan** [ARM-software/ComputeLibrary#491]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

**Platform:**

**Operating System:**
fedora28

**Problem description:**
After download the latest version computerlib v18.05, which the OS is fedora28 and compile tools is default gcc-c++.  So simpily issue description is fedora28+default GCC8.1, can not compile computer library success.
error messages is:
![image](https://user-images.githubusercontent.com/31117595/42858052-44118234-8a7f-11e8-80df-fb9235ed845c.png)

Question:
Can you make this done? compile computer library in fedora28+gcc8.1.

**Comment by jiulongshan** [comment]
Could arm will release patch for this issue before release version? @gmiodice

**Comment by morgolock** [comment]
Hi @jiulongshan 

We haven't built the library with GCC8. I would suggest you follow the build recommendations in the documentation https://arm-software.github.io/ComputeLibrary/v18.05/index.xhtml#S3_2_linux

For Linux you need one or more of these toolchain versions (depending on target platform):

- gcc-linaro-arm-linux-gnueabihf-4.9-2014.07_linux
- gcc-linaro-4.9-2016.02-x86_64_aarch64-linux-gnu
- gcc-linaro-6.3.1-2017.02-i686_aarch64-linux-gnu

You can get the toolchains from: http://releases.linaro.org/components/toolchain/binaries/
