### ISSUE TITLE
Does ACL Graph support custom layer?

### ISSUE THREAD

**Issue by kobe2000** [ARM-software/ComputeLibrary#492]
Hi
I noticed there's no Shuffle Channel Layer in ACL Graph. How can I implement a costom layer?

**Comment by AnthonyARM** [comment]
Hi,
The Graph layer of the Compute Library is only here for test purposes, it's not meant to be used for applications development.
You've got other options for that, such as for example ArmNN

**Comment by GeorgeARM** [comment]
Channel Shuffle layer will be part of the next release.

**Comment by waynexhsieh** [comment]
Hi
I noticed there's no ROI Align Layer in ACL Graph. How can I implement a costom layer?

**Comment by mpekatsoula** [comment]
Hi @waynexhsieh 
As Anthony mentioned, the Graph layer of the Compute Library is only here for test purposes. If you want to implement a new layer, you can have a look at an existing kernel/function. We are in the process of updating our documentation where we'll explain how to create custom kernels/functions, hopefully in the next release.
