### ISSUE TITLE
Benchmark results for Inception v3 on ARM Mali

### ISSUE THREAD

**Issue by uu-kameshm** [ARM-software/ComputeLibrary#493]
Hi

Do you have any performance results of speed (execution time/FPS) for Inception v3 Deep Learning network on ARM Mali GPU using the ARM Compute Library. Do mention the GPU configuration too, if you have the results. 

Thanks in advance
Kamesh

**Comment by uu-kameshm** [comment]
Hi 

It would help to know the numbers for "ARM Mali T880 MP12" GPU or for a similar ARM Mali based GPU platform.

Thank you
Kamesh

**Comment by morgolock** [comment]
Hi @uu-kameshm 

We do not have anything for that architecture.

In the past we have shared some information about ACL's performance, check out the following links:
https://developer.arm.com/ip-products/processors/machine-learning/compute-library
https://www.youtube.com/watch?v=xwESWqdJt_Y 

Hope this helps.
