### ISSUE TITLE
Scale Layer Need Info

### ISSUE THREAD

**Issue by uu-praveeng** [ARM-software/ComputeLibrary#494]
Hi,

There is no scale layer supported in src/runtime/Neon/functions. But the I have seen accessing the scale layer in the graph examples . 

Could you let me know how could I implement the scale layer with out using graph api's.

Thank you

**Comment by GeorgeARM** [comment]
Hello @uu-praveeng,

When you say scale layer you mean the Caffe scale layer?

**Comment by uu-praveeng** [comment]
Scale layer used in the Neural Networks (alpha*input +beta)

Thank you

**Comment by uu-praveeng** [comment]
Hi George,

It would be very helpful for us if you could give me some example implementation for scale layer using  Broadcast api's that you have mentioned. 

Thank you

**Comment by GeorgeARM** [comment]
Hey @uu-praveeng,
You can jut use a pixelwise multiplication and an arithmetic addition. They should take care of the broadcasting automatically. That what we do in the graph [here](https://github.com/ARM-software/ComputeLibrary/blob/master/src/graph/GraphBuilder.cpp#L424).

**Comment by uu-praveeng** [comment]
Thanks George.
