### ISSUE TITLE
Example or clues to replace feature detect & tracking function of OpenCV

### ISSUE THREAD

**Issue by cclo-astri** [ARM-software/ComputeLibrary#495]
Hi all,

I am newbie of ACL. 

I am now using an ARM + Mali platform for some SLAM demo application development. With the help of OpenCV, I used `cv::goodFeaturesToTrack()` and `cv::calcopticalflowpyrlk()` and now I have a very preliminary level of tracking pipeline. 

After some test, the performance of this combination is not good enough. So I enabled OpenCL support in OpenCV library but the performance worse than without OpenCL. Finally I found the OpenCL version of `cv::calcopticalflowpyrlk()` is the root cause (I do not know why the OpenCL version is slower than the generic CPU implementation).

The question is, I would like to use ACL to replace the above 2 functions in OpenCV. I could find some components which is part of `cv::goodFeaturesToTrack()` and `cv::calcopticalflowpyrlk()` such as `CLHarrisCorners`, `CLOpticalFlow`, etc. But I have no clue to integrate them to form a complete SLAM tracking pipeline.

Beside of the above replacement, as my demo application need to further use OpenCV for pre & post processing (image un-distortion, loop closure detection, key-frame management, etc), I need to able to let ACL accept OpenCV's `Mat` class and convert the output of ACL to OpenCV's `Mat` class.

Please help. 

Thanks.

**Comment by GeorgeARM** [comment]
Hello @cclo-astri,

Do you still need help with the above?

**Comment by cclo-astri** [comment]
Hi @GeorgeARM 

Sorry for late reply. 

I have finished to implement `cv::goodFeaturesToTrack()` and `cv::calcopticalflowpyrlk()` by using `CLHarrisCorners` (replace `cv::goodFeaturesToTrack()`), and `CLGaussianPyramidHalf + CLOpticalFlow` (replace `cv::calcopticalflowpyrlk()`).

But the performance still not good enough when compared to OpenCV CPU mode (it means the 2 OpenCV functions runs on CPU only). So I temporarily gave up the development.

Thanks.

**Comment by vswdigitall** [comment]
> Hi @GeorgeARM
> 
> Sorry for late reply.
> 
> I have finished to implement `cv::goodFeaturesToTrack()` and `cv::calcopticalflowpyrlk()` by using `CLHarrisCorners` (replace `cv::goodFeaturesToTrack()`), and `CLGaussianPyramidHalf + CLOpticalFlow` (replace `cv::calcopticalflowpyrlk()`).
> 
> But the performance still not good enough when compared to OpenCV CPU mode (it means the 2 OpenCV functions runs on CPU only). So I temporarily gave up the development.
> 
> Thanks.



> Hi @GeorgeARM
> 
> Sorry for late reply.
> 
> I have finished to implement `cv::goodFeaturesToTrack()` and `cv::calcopticalflowpyrlk()` by using `CLHarrisCorners` (replace `cv::goodFeaturesToTrack()`), and `CLGaussianPyramidHalf + CLOpticalFlow` (replace `cv::calcopticalflowpyrlk()`).
> 
> But the performance still not good enough when compared to OpenCV CPU mode (it means the 2 OpenCV functions runs on CPU only). So I temporarily gave up the development.
> 
> Thanks.

Hi cclo-asti, can you provide ACL optflow example?

**Comment by cclo-astri** [comment]
@vswdigitall 

Hi,

I uploaded my latest version of test code (although it is so called "latest", it is written a year go). 

This code mixed with OpenCV's `cv::goodFeaturesToTrack()` and `cv::calcopticalflowpyrlk()` for me to do some fast switch testing between the performance of OpenCV's and ACL's.

Please check. Thanks.

[test_acl_opt_flow.zip](https://github.com/ARM-software/ComputeLibrary/files/3052391/test_acl_opt_flow.zip)

**Comment by vswdigitall** [comment]
Of course i did it. And it is the fact - output array descriptors are empty. Why? May be developers can help?
