### ISSUE TITLE
How do I convert bytebuffer image to Image(Tensor) class in JNI?

### ISSUE THREAD

**Issue by Kang3498** [ARM-software/ComputeLibrary#497]
**Platform: Arm64-v8a

**Operating System: Android

**Problem description:** 

I want to pass my bytebuffer that is filled by RGBA8888 to my jni with neon class.

Here's my code.
```cpp
Image src;
 void *dBuf = env->GetDirectBufferAddress(buf);
 src.allocator()->init(TensorInfo(w, h, Format::RGBA8888));
 src.allocator()->allocate();
 src.allocator()->import_memory(Memory(dBuf));
```
And I got this error.
```
error: no matching conversion for functional-style cast from 'void *' to 'arm_compute::Memory'
    src.allocator()->import_memory(Memory(dBuf));
```

I have no idea how to convert my rgb bytebuffer to Image(Tensor) class.
Anyone give me some hint please.

**Comment by GeorgeARM** [comment]
Hello @Kang3498 ,

Have a look [here ](https://github.com/ARM-software/ComputeLibrary/issues/474#issuecomment-404464968)
We will try to simplify the interface to pass just a raw pointer instead of having to implement an interface.
