### ISSUE TITLE
ComputeLibrary for ARM Cortex A57 CPU

### ISSUE THREAD

**Issue by gija92** [ARM-software/ComputeLibrary#498]
**OpenCL for ARM Cortex A57 with Compute Library**

**Platform: Renesas**

**Operating System: Linux Ubuntu 16.04. Yocto-distribution**

**Problem description:**

Hello,

I built the ComputeLibrary (v18.05.) on Linux to provide OpenCL for ARM Cortex A57 CPUs. After building with 
```ruby
scons Werror=1 -j8 debug=0 asserts=1 neon=0 opencl=1 embed_kernels=1 os=linux arch=arm64-v8a
```

I executed the examples where cl_convolution passed but graph_lelnet got me following error

```ruby
BuildGroup_1:120[14317.852974] audit: type=1701 audit(1532346165.586:14): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=7002 comm="graph_lenet" exe="/home/root/ComputeLibrary-master/build/examples/graph_lenet" sig=6
3:44: error: automatic variable qualified with an address space
    __constant VEC_DATA_TYPE(DATA_TYPE, 4) type_min4 = (VEC_DATA_TYPE(DATA_TYPE, 4))(MINVAL);
                                           ^

terminate called after throwing an instance of 'cl::Error'
  what():  clCreateKernel
Aborted (core dumped)
```

I think that maybe the solution of this error could provide that the CPU is OpenCL compatible, so that running the command 'clinfo' for example show me the ARM Cortex A57 as OpenCL device.

Can someone help me to provide OpenCL functionality for the CPU with ComputeLibrary?
Thanks a lot, :)

Best regards

**Comment by gmiodice** [comment]
Hi @gija92,

what OpenCL version are you using on the CPU? regarding your question, have you tried to use the NEON acceleration instead of the OpenCL one? 
Although OpenCL can be available on the CPU (through POCL for instance), the implementation is highly optimized just for Arm Mali GPUs architectures so I do not expect great benefit on using OpenCL on A57.

If you build the library with NEON enabled

```
scons Werror=1 -j8 debug=0 asserts=1 neon=1 opencl=0 os=linux arch=arm64-v8a
```
you could benefit of highly optimized assembly routines for the main ML functions and the performance should be much better than using OpenCL.

Hope this can help.

Thanks

**Comment by gija92** [comment]
Hi @gmiodice 

thanks for that advice I tried activating NEON but the build stops cause of errors. Actually I need the CPU as an OpenCL device (OpenCL 1.2).
 
So you're suggesting to use POCL?

**Comment by AnthonyARM** [comment]
@gija92 ,

Could you please explain why you need the CPU as an OpenCL device ? 
As Gian Marco explained, while it might be functional, it's very likely that the performance will be poor compare to the pure NEON backend.

**Comment by gija92** [comment]
@AnthonyARM 
I have a program which I have to execute "on" the CPU and it's based on OpenCL. It measures the performance of CPU so it's okay if the perfomance will be poor I just have to get the Cortex A57 defined as an OpenCL device. ^^

**Comment by AnthonyARM** [comment]
That's not what the Compute Library does though: the Compute Library will use the CPU through OpenCL but in no case will it create a NEON OpenCL device. (i.e the Compute Library is a client OpenCL application like yours, it's not an implementation of the OpenCL standard).
So in your case all you need is to find a NEON based OpenCL implementation (You won't need the compute library at all).

**Comment by gija92** [comment]
@AnthonyARM 

ok I understand thanks for the information. Do you have any suggestions concerning the NEON based OpenCL implementation? Maybe POCL?

**Comment by AnthonyARM** [comment]
Yes, POCL should do the job.

**Comment by gija92** [comment]
@AnthonyARM 

Ok thanks for your answer. I will try this way :)
