### ISSUE TITLE
Strange border exists after CLGaussianPyramidHalf

### ISSUE THREAD

**Issue by cclo-astri** [ARM-software/ComputeLibrary#499]
**Output of 'strings libarm_compute.so | grep arm_compute_version':** 
arm_compute_version=v18.05 Build options: {'embed_kernels': '1', 'opencl': '1','pmu': '1', 'arch': 'arm64-v8a', 'standalone': '0', 'neon': '0', 'build_dir': 'android-arm64-v8a-cl', 'debug': '0', 'validation_tests': '0', 'examples': '1', 'asserts': '0', 'mali': '1', 'benchmark_tests': '0', 'compiler_cache': 'ccache', 'os': 'android', 'Werror': '1'} Git hash=12ad439c2511cca35b36cabcd6b342feccf6f02b

**Platform:** 
Rockchip RK3399

**Operating System:** 
Android 6.0

**Problem description:**

I am now trying replace the `cv::calcopticalflowpyrlk()` by ACL implementation.

Then I and found if I need to use ACL's `CLOpticalFlow`, I need to first prepare an image pyramid. I am now using `CLGaussianPyramidHalf` to achieve this. After some coding, I dump the output images in pyramid, and I found all levels (except level 0, the first one), 3 black borders exists (on the left / right / bottom side of image). And the image seems cropped.

I already set the Border mode to `BorderMode::UNDEFINED`. I doubt such border will further affect the tracking result when I use `CLOpticalFlow`.

Please help.  Thanks.

**Comment by morgolock** [comment]
Hi @cclo-astri 

Reading your message I get the impression that you would expect the output of `CLGaussianPyramidHalf` to have no padding at all when you set border mode to `BorderMode::UNDEFINED`

Is this so?

**Comment by cclo-astri** [comment]
Hi @morgolock 

Yes, that's what I mean. Sorry for my poor English.

Thanks.

**Comment by morgolock** [comment]
Hi @cclo-astri 

Can you please share the code to generate the pyramid? 

The padding added by `CLGaussianPyramidHalf` shouldn't be a problem when calling other ACL functions, but if you want to copy the output images to your own buffer you have to take into account the padding. Take a look at [https://arm-software.github.io/ComputeLibrary/v18.05/architecture.xhtml#S4_6_4_working_with_objects](url) for more detailed information on how to move the data to/from ACL's tensors to your own buffers.

**Comment by cclo-astri** [comment]
Hi @morgolock 

Here is the code snippet:

    PyramidInfo pyramid_info;
    pyramid_info.init(3, SCALE_PYRAMID_HALF, TensorShape(480, 640), Format::U8);
    CLGaussianPyramidHalf prevPyrDown;

    CLPyramid prevEqlPyr;
    prevEqlPyr.init(pyramid_info);
    prevEqlPyr.allocate();
    prevPyrDown.configure(&prevEqlTensor, &prevEqlPyr, BorderMode::UNDEFINED, 255);
    prevPyrDown.run();
    CLScheduler::get().sync();

And I use the following codes to dump the output:

    CLTensor *output = prevPyramid.get_pyramid_level(1);
    output->map();

    Window output_window;
    output_window.use_tensor_dimensions(output->info()->tensor_shape());
    Iterator output_it(output, output_window);
    Mat outputImg(output->info()->tensor_shape().y(), output->info()->tensor_shape().x(), iGreyImage.type());

    execute_window_loop(output_window, [&](const Coordinates & id)
    {
        outputImg.at<unsigned char>(id.y(), id.x()) = *reinterpret_cast<unsigned char *>(output_it.ptr());
    },
    output_it);
    output->unmap();
    imwrite("./prevPyr1.png", outputImg);

Thank you.

**Comment by morgolock** [comment]
Hi @cclo-astri 

Could you please try moving `prevEqlPyr.allocate();` after `prevPyrDown.configure(&prevEqlTensor, &prevEqlPyr, BorderMode::UNDEFINED, 255);` ?

As explained in the documentation

> It's important to call allocate after the function is configured: if the image / tensor is already allocated then the function will shrink its execution window instead of increasing the padding. (See below for more details).

Let me know if this solves the problem

**Comment by cclo-astri** [comment]
Hi @morgolock 

Yes this modification solves the problem.

Thanks so much.
