### ISSUE TITLE
DepthwiseConvolutionLayer kernel size

### ISSUE THREAD

**Issue by bubbles1990** [ARM-software/ComputeLibrary#501]
Hi,

it seems the the only allowed kernel size for `DepthwiseConvolutionLayer` is 3x3. Is it possible to use different kernel sizes?

Thank you.

**Comment by giorgio-arena** [comment]
Hi, @bubbles1990 

CL/NEDepthwiseConvolutionLayer functions support any kernel sizes.

The 3x3 case is an highly optimised one and it has its own function (CL/NEDepthwiseConvolutionLayer3x3)

Maybe you are trying to call the incorrect function?

**Comment by bubbles1990** [comment]
Hi, thank you.
I should have mentioned that I'm using the graph API. Any kernel size other than 3x3 raises an error.
`graph << DepthwiseConvolutionLayer(kernel_height, kernel_width, ...)`

**Comment by giorgio-arena** [comment]
Hi,

You should pass a hint to your graph, stating what depthwise convolution method to use. For instance, in our mobilenet example, `<< DepthwiseConvolutionMethod::OPTIMIZED_3x3` is passed to the graph.

Anyway, keep in mind that the graph API is only here for test purposes, it's not meant to be used for applications development.
You've got other options for that, such as for example ArmNN.

Hope that helps

**Comment by bubbles1990** [comment]
Thank you.
