### ISSUE TITLE
Cannot include headers from other directories

### ISSUE THREAD

**Issue by arnav2** [ARM-software/ComputeLibrary#503]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
msys32\mingw32\bin\strings.exe: 'libarm_compute.so': No such file
**Platform:**

**Operating System:**
Windows 10

I am getting a No such file or directory when trying to include header files from other path. 
**Problem description:**
I am trying to cross compile in windows. 
COMMAND: 
scons.bat Werror=1 -j8 debug=0 asserts=1 neon=0 opencl=1 embed_kernels=1 os=linux arch=arm64-v8a
LOG : 
scons: Reading SConscript files ...
scons: done reading SConscript files.

scons: warning: you do not seem to have the pywin32 extensions installed;
        parallel (-j) builds may not work reliably with open Python files.
File "C:\Python27\Scripts\scons.py", line 201, in <module>
scons: Building targets ...
scons: `opencl' is up to date.
scons: `build\src\core\arm_compute_version.embed' is up to date.
scons: `build\src\core\CL\cl_kernels\absdiff.clembed' is up to date.
aarch64-linux-gnu-g++ -o build\src\core\Utils.o -c -Wno-deprecated-declarations -Wall -DARCH_ARM -Wextra -Wno-unused-parameter -pedantic -Wdisabled-optimization -Wformat=2 -Winit-self -Wstrict-overflow=2 -Wswitch-default -fpermissive -std=gnu++11 -Wno-vla -Woverloaded-virtual -Wctor-dtor-privacy -Wsign-promo -Weffc++ -Wno-format-nonliteral -Wno-overlength-strings -Wno-strict-overflow -Wno-implicit-fallthrough -Wlogical-op -Wnoexcept -Wstrict-null-sentinel -march=armv8-a -Wno-ignored-attributes -Werror -O3 -ftree-vectorize -fstack-protector-strong -D_GLIBCXX_USE_NANOSLEEP -DARM_COMPUTE_CPP_SCHEDULER=1 -DARM_COMPUTE_AARCH64_V8A -DNO_DOT_IN_TOOLCHAIN -DEMBEDDED_KERNELS -DARM_COMPUTE_ASSERTS_ENABLED -Iinclude -I. -Ibuild\build\src\core\CL -Ibuild\src\core\CL -Ibuild\build\src\core -Ibuild\src\core src\core\Utils.cpp
aarch64-linux-gnu-g++ -o build\src\core\CPP\kernels\CPPCornerCandidatesKernel.o -c -Wno-deprecated-declarations -Wall -DARCH_ARM -Wextra -Wno-unused-parameter -pedantic -Wdisabled-optimization -Wformat=2 -Winit-self -Wstrict-overflow=2 -Wswitch-default -fpermissive -std=gnu++11 -Wno-vla -Woverloaded-virtual -Wctor-dtor-privacy -Wsign-promo -Weffc++ -Wno-format-nonliteral -Wno-overlength-strings -Wno-strict-overflow -Wno-implicit-fallthrough -Wlogical-op -Wnoexcept -Wstrict-null-sentinel -march=armv8-a -Wno-ignored-attributes -Werror -O3 -ftree-vectorize -fstack-protector-strong -D_GLIBCXX_USE_NANOSLEEP -DARM_COMPUTE_CPP_SCHEDULER=1 -DARM_COMPUTE_AARCH64_V8A -DNO_DOT_IN_TOOLCHAIN -DEMBEDDED_KERNELS -DARM_COMPUTE_ASSERTS_ENABLED -Iinclude -I. -Ibuild\build\src\core\CL -Ibuild\src\core\CL -Ibuild\build\src\core -Ibuild\src\core src\core\CPP\kernels\CPPCornerCandidatesKernel.cpp
aarch64-linux-gnu-g++ -o build\src\core\CPP\kernels\CPPDetectionWindowNonMaximaSuppressionKernel.o -c -Wno-deprecated-declarations -Wall -DARCH_ARM -Wextra -Wno-unused-parameter -pedantic -Wdisabled-optimization -Wformat=2 -Winit-self -Wstrict-overflow=2 -Wswitch-default -fpermissive -std=gnu++11 -Wno-vla -Woverloaded-virtual -Wctor-dtor-privacy -Wsign-promo -Weffc++ -Wno-format-nonliteral -Wno-overlength-strings -Wno-strict-overflow -Wno-implicit-fallthrough -Wlogical-op -Wnoexcept -Wstrict-null-sentinel -march=armv8-a -Wno-ignored-attributes -Werror -O3 -ftree-vectorize -fstack-protector-strong -D_GLIBCXX_USE_NANOSLEEP -DARM_COMPUTE_CPP_SCHEDULER=1 -DARM_COMPUTE_AARCH64_V8A -DNO_DOT_IN_TOOLCHAIN -DEMBEDDED_KERNELS -DARM_COMPUTE_ASSERTS_ENABLED -Iinclude -I. -Ibuild\build\src\core\CL -Ibuild\src\core\CL -Ibuild\build\src\core -Ibuild\src\core src\core\CPP\kernels\CPPDetectionWindowNonMaximaSuppressionKernel.cpp
aarch64-linux-gnu-g++ -o build\src\core\CPP\kernels\CPPPermuteKernel.o -c -Wno-deprecated-declarations -Wall -DARCH_ARM -Wextra -Wno-unused-parameter -pedantic -Wdisabled-optimization -Wformat=2 -Winit-self -Wstrict-overflow=2 -Wswitch-default -fpermissive -std=gnu++11 -Wno-vla -Woverloaded-virtual -Wctor-dtor-privacy -Wsign-promo -Weffc++ -Wno-format-nonliteral -Wno-overlength-strings -Wno-strict-overflow -Wno-implicit-fallthrough -Wlogical-op -Wnoexcept -Wstrict-null-sentinel -march=armv8-a -Wno-ignored-attributes -Werror -O3 -ftree-vectorize -fstack-protector-strong -D_GLIBCXX_USE_NANOSLEEP -DARM_COMPUTE_CPP_SCHEDULER=1 -DARM_COMPUTE_AARCH64_V8A -DNO_DOT_IN_TOOLCHAIN -DEMBEDDED_KERNELS -DARM_COMPUTE_ASSERTS_ENABLED -Iinclude -I. -Ibuild\build\src\core\CL -Ibuild\src\core\CL -Ibuild\build\src\core -Ibuild\src\core src\core\CPP\kernels\CPPPermuteKernel.cpp
aarch64-linux-gnu-g++ -o build\src\core\CPP\kernels\CPPSortEuclideanDistanceKernel.o -c -Wno-deprecated-declarations -Wall -DARCH_ARM -Wextra -Wno-unused-parameter -pedantic -Wdisabled-optimization -Wformat=2 -Winit-self -Wstrict-overflow=2 -Wswitch-default -fpermissive -std=gnu++11 -Wno-vla -Woverloaded-virtual -Wctor-dtor-privacy -Wsign-promo -Weffc++ -Wno-format-nonliteral -Wno-overlength-strings -Wno-strict-overflow -Wno-implicit-fallthrough -Wlogical-op -Wnoexcept -Wstrict-null-sentinel -march=armv8-a -Wno-ignored-attributes -Werror -O3 -ftree-vectorize -fstack-protector-strong -D_GLIBCXX_USE_NANOSLEEP -DARM_COMPUTE_CPP_SCHEDULER=1 -DARM_COMPUTE_AARCH64_V8A -DNO_DOT_IN_TOOLCHAIN -DEMBEDDED_KERNELS -DARM_COMPUTE_ASSERTS_ENABLED -Iinclude -I. -Ibuild\build\src\core\CL -Ibuild\src\core\CL -Ibuild\build\src\core -Ibuild\src\core src\core\CPP\kernels\CPPSortEuclideanDistanceKernel.cpp
aarch64-linux-gnu-g++ -o build\src\core\CPP\kernels\CPPUpsampleKernel.o -c -Wno-deprecated-declarations -Wall -DARCH_ARM -Wextra -Wno-unused-parameter -pedantic -Wdisabled-optimization -Wformat=2 -Winit-self -Wstrict-overflow=2 -Wswitch-default -fpermissive -std=gnu++11 -Wno-vla -Woverloaded-virtual -Wctor-dtor-privacy -Wsign-promo -Weffc++ -Wno-format-nonliteral -Wno-overlength-strings -Wno-strict-overflow -Wno-implicit-fallthrough -Wlogical-op -Wnoexcept -Wstrict-null-sentinel -march=armv8-a -Wno-ignored-attributes -Werror -O3 -ftree-vectorize -fstack-protector-strong -D_GLIBCXX_USE_NANOSLEEP -DARM_COMPUTE_CPP_SCHEDULER=1 -DARM_COMPUTE_AARCH64_V8A -DNO_DOT_IN_TOOLCHAIN -DEMBEDDED_KERNELS -DARM_COMPUTE_ASSERTS_ENABLED -Iinclude -I. -Ibuild\build\src\core\CL -Ibuild\src\core\CL -Ibuild\build\src\core -Ibuild\src\core src\core\CPP\kernels\CPPUpsampleKernel.cpp
aarch64-linux-gnu-g++ -o build\src\core\utils\io\FileHandler.o -c -Wno-deprecated-declarations -Wall -DARCH_ARM -Wextra -Wno-unused-parameter -pedantic -Wdisabled-optimization -Wformat=2 -Winit-self -Wstrict-overflow=2 -Wswitch-default -fpermissive -std=gnu++11 -Wno-vla -Woverloaded-virtual -Wctor-dtor-privacy -Wsign-promo -Weffc++ -Wno-format-nonliteral -Wno-overlength-strings -Wno-strict-overflow -Wno-implicit-fallthrough -Wlogical-op -Wnoexcept -Wstrict-null-sentinel -march=armv8-a -Wno-ignored-attributes -Werror -O3 -ftree-vectorize -fstack-protector-strong -D_GLIBCXX_USE_NANOSLEEP -DARM_COMPUTE_CPP_SCHEDULER=1 -DARM_COMPUTE_AARCH64_V8A -DNO_DOT_IN_TOOLCHAIN -DEMBEDDED_KERNELS -DARM_COMPUTE_ASSERTS_ENABLED -Iinclude -I. -Ibuild\build\src\core\CL -Ibuild\src\core\CL -Ibuild\build\src\core -Ibuild\src\core src\core\utils\io\FileHandler.cpp
aarch64-linux-gnu-g++ -o build\src\core\utils\logging\FilePrinter.o -c -Wno-deprecated-declarations -Wall -DARCH_ARM -Wextra -Wno-unused-parameter -pedantic -Wdisabled-optimization -Wformat=2 -Winit-self -Wstrict-overflow=2 -Wswitch-default -fpermissive -std=gnu++11 -Wno-vla -Woverloaded-virtual -Wctor-dtor-privacy -Wsign-promo -Weffc++ -Wno-format-nonliteral -Wno-overlength-strings -Wno-strict-overflow -Wno-implicit-fallthrough -Wlogical-op -Wnoexcept -Wstrict-null-sentinel -march=armv8-a -Wno-ignored-attributes -Werror -O3 -ftree-vectorize -fstack-protector-strong -D_GLIBCXX_USE_NANOSLEEP -DARM_COMPUTE_CPP_SCHEDULER=1 -DARM_COMPUTE_AARCH64_V8A -DNO_DOT_IN_TOOLCHAIN -DEMBEDDED_KERNELS -DARM_COMPUTE_ASSERTS_ENABLED -Iinclude -I. -Ibuild\build\src\core\CL -Ibuild\src\core\CL -Ibuild\build\src\core -Ibuild\src\core src\core\utils\logging\FilePrinter.cpp
src\core\Utils.cpp:43:37: fatal error: arm_compute_version.embed: No such file or directory
 #include "arm_compute_version.embed"
                                     ^
compilation terminated.
scons: *** [build\src\core\Utils.o] Error 1
scons: building terminated because of errors.

**Comment by arnav2** [comment]
Also if I put the complete path it works just fine. So it has to be a build issue. I cannot figure out the reason. Maybe because I am a novice in the field. If someone can help me that would be amazing. Thanks.

**Comment by morgolock** [comment]
Hi @arnav2 

Are you building directly from windows? if you do this the build system gets confused with the windows naming convention for paths.

I would recommend you follow the suggestions in the documentation [https://arm-software.github.io/ComputeLibrary/v18.05/index.xhtml#S3_5_windows_host](url)

**Comment by arnav2** [comment]
Hello Pablo,

Thanks for the reply. But I need to build it for windows. I did install
cygwin and I am using that but it still gives me the same error. Could you
please help me out with that.

Regards,
Arnav goel.

**Comment by morgolock** [comment]
Hi @arnav2 

Have you tried `Windows Subsystem for Linux` ? This is the best option when building from Windows.

[https://docs.microsoft.com/en-gb/windows/wsl/install-win10](url)

Would this work for you? Other solutions on windows are problematic because the tools required to build the library are not as robust as their counterpart on the unix based operating systems.

**Comment by arnav2** [comment]
I haven't yet but definitely seems worth looking at. Thanks for the info.
Really appreciated the help.

Regards,
Arnav goel.
