### ISSUE TITLE
Question about copying CLTensor and CLArray

### ISSUE THREAD

**Issue by cclo-astri** [ARM-software/ComputeLibrary#506]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v18.05 Build options: {'embed_kernels': '1', 'opencl': '1','pmu': '1', 'arch': 'arm64-v8a', 'standalone': '0', 'neon': '0', 'build_dir': 'android-arm64-v8a-cl', 'debug': '0', 'validation_tests': '0', 'examples': '1', 'asserts': '0', 'mali': '1', 'benchmark_tests': '0', 'compiler_cache': 'ccache', 'os': 'android', 'Werror': '1'} Git hash=12ad439c2511cca35b36cabcd6b342feccf6f02b

**Platform:**
Rockchip RK3399

**Operating System:**
Android 6.0

**Problem description:**

I am testing ACL capability to track feature points with a bunch of images. During tracking, I need to save the detected feature points of previous image (from `CLHarrisCorners`) and perform tracking with the detected feature points of current image (by `CLOpticalFlow`).

This is the code snippet that I use for copying the `CLKeyPointArray` 

            CLKeyPointArray prevPts(::numOfPoints), detectedPts(::numOfPoints);

            prevPts.map(); detectedPts.map();
            prevPts.clear();
            for (int p = 0; p < ::numOfPoints; p++)
            {
                arm_compute::KeyPoint keypt;
                keypt.x = detectedPts.at(p).x;
                keypt.y = detectedPts.at(p).y;
                keypt.strength = detectedPts.at(p).strength;
                keypt.tracking_status = detectedPts.at(p).tracking_status;
                prevPts.push_back(keypt);
            }
            prevPts.unmap(); detectedPts.unmap();

As required by `CLOpticalFlow`, it is better that I could also save the previous image (`CLTensor`), and the generated image pyramid (`CLPyramid`) together.

I wonder there exist any method (`Iterator` ? `memcpy` ? `copy_from` ?) that could copy `CLKeyPointArray`, `CLTensor` and `CLPyramid` from one variable to another just like assigning a value to variable in C++, rather than copying the elements one by one ... 

Please help. Thanks.

**Comment by morgolock** [comment]
Hi @cclo-astri 

The  copy constructor in `CLKeyPointArray` has been deleted explicitly so the only way to copy the elements is to iterate as you do in the code above. It should be safe however to directly copy individual keypoints without going through all the work of assigning individual fields. You could do: `arm_compute::KeyPoint keypt = detectedPts.at(p)`

The recommend approach for moving data from/to tensors is to use `execute_window_loop` as described in the documentation: [https://arm-software.github.io/ComputeLibrary/v18.05/architecture.xhtml#S4_6_4_working_with_objects](url)

There is a method void copy_from(const ITensor &src) which you can use as well
[https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/core/ITensor.h#L68](url)

To copy the Pyramid you would need to iterate over each level and call the copy_from() method mentioned above.

**Comment by vswdigitall** [comment]
Hi All,

I can't access CLKeyPointArray items for CLOpticalFloat function.

Example:

CLKeyPointArray arr{ 1000 };
map( arr, true ); // or without map
KeyPoint pt{};
arr.push_back( pt ); // The program has unexpectedly finished
arr.at( 0 ) = pt; // The program has unexpectedly finished
cout << arr.at( 0 ).x; // The program has unexpectedly finished

KeyPoint pt{ arr.at( 0 )  }; // ok but:
cout << pt.x; // The program has unexpectedly finished
unmap( arr ); // or without unmap
How to operate with CLArray?

Please help.

**Comment by vswdigitall** [comment]
Should use:

CLArray.map/unmap instead utils::map/unmap:
```
for(;;)
{
prevPts.map( true );
arm_compute::KeyPoint pt{};
 pt.x = 10;
prevPts.push_back( pt );
prevPts.at( 0 ) = pt;
std::cout << prevPts.at( 0 ).x << " " << prevPts.num_values() << " " << prevPts.max_num_values() << "\n";
prevPts.unmap();
}
```
It works in simple loop. But in execute_window_loop fails:

```
pts = arm_compute::CLKeyPointArray{ image.total() };

void copyToArray( const arm_compute::CLImage & clImage, arm_compute::CLKeyPointArray & pts )
    {
        const uint32_t width{ clImage.info()->tensor_shape()[ 0 ] };
        pts.map( true );
        pts.clear();
        arm_compute::utils::map( clImage, true );
        arm_compute::Window window;
        window.use_tensor_dimensions( clImage.info()->tensor_shape() );
        arm_compute::Iterator in( & clImage, window );
        arm_compute::execute_window_loop( window, [ & ]( const arm_compute::Coordinates & id )
        {
            uint8_t value{ * reinterpret_cast< uint8_t * >( in.ptr() ) };
            if( value > 200 )
            {
                //                    outImage.at< uint8_t >( id.y(), id.x() ) = 255;
                arm_compute::KeyPoint pt{};
                pt.x = id.x();
                pt.y = id.y();
                pt.tracking_status = 1;

                pts.push_back( pt ); // The program has unexpectedly finished

            }
        }, in );
        arm_compute::utils::unmap( clImage );
        pts.unmap();
    }
```

How to push_back CLArray  inside execute_window_loop?

**Comment by vswdigitall** [comment]
My mistake, instead: 
`void copyToArray( **const** arm_compute::CLImage & clImage, arm_compute::CLKeyPointArray & pts )`
use
`void copyToArray( **const** arm_compute::CLImage & clImage, arm_compute::CLKeyPointArray & pts )
`

Closed.
