### ISSUE TITLE
tensorflow_data_extractor.py

### ISSUE THREAD

**Issue by clydeliuyan** [ARM-software/ComputeLibrary#509]
Dear:

PC: ubuntu 16.04 + AMD CPU/GPU
Python 3.6.4 |Anaconda, Inc.|
tensorflow:'1.7.0'
model: mobilenet_v1_1.0_224

1. download MobileNet_v1_1.0_224.tgz from tf/slim. https://github.com/tensorflow/models/tree/master/research/slim

2.  python3.6 tensorflow_data_extractor.py  -m mobilenet_v1_1.0_224.ckpt.data-00000-of-00001 -n mobilenet_v1_1.0_224.ckpt.meta

log:
DataLossError (see above for traceback): Unable to open table file ./mobilenet_v1_1.0_224.ckpt.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?

More case:
python3.6 tensorflow_data_extractor.py -m mobilenet_v1_1.0_224 -n mobilenet_v1_1.0_224.ckpt.meta
->
NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for mobilenet_v1_1.0_224

My issue: Which model(checkpoint) file useful in decompressing files?
---
  -m MODELFILE  Path to Tensorflow checkpoint binary file. For Tensorflow
                version >= 0.11, only include model name; for Tensorflow
                version < 0.11, include model name with ".ckpt" extension

Thanks
Yan Liu

**Comment by NAKsir-melody** [comment]
come here, I made already!
https://github.com/NAKsir-melody/tfslim_ckpt_to_savefile

**Comment by clydeliuyan** [comment]
Thanks for your help,I found the cause,
python tensorflow_data_extractor.py -m ~/mobilenet_v1_1.0_224/mobilenet_v1_1.0_224.ckpt -n ~/mobilenet_v1_1.0_224/mobilenet_v1_1.0_224.ckpt.meta

the .ckpt suffix is necessary.
My TF version is 1.7 > 0.11,the "-m" help maybe have some mistake.

Thanks
Yan Liu
