### ISSUE TITLE
How do I implement a LRN layer in ACL supporting multiple channels?

### ISSUE THREAD

**Issue by yangyanzhan** [ARM-software/ComputeLibrary#51]
I've found out that NENormalizationLayer requires its input tensor having exactly one channel. How could I extend NENormalizationLayer so that its input tensor could have more than one channels? Does ACL team has any plan to support this feature in the future?

**Comment by AnthonyARM** [comment]
In the ARM Compute library the "number of channels" describes interleaved data only.
If your data is planar (which is usually the case for CNN functions) then you need to use the 3rd dimension ( [feature_map](https://arm-software.github.io/ComputeLibrary/v17.04/index.xhtml#S4_6_2_tensors) of the tensor to store several channels inside a single tensor:

3 channels [ 2, 2 ] tensor: 
```
R G B R G B <paddng>
R G B R G B <padding>
```
1 channel [ 2, 2, 3] tensor:
```
R R <padding>
R R <padding>
<padding>
G G <padding>
G G <padding>
<padding>
B B <padding>
B B <padding>
```

Does it make sense ?

**Comment by yangyanzhan** [comment]
Thank you, Anthony. I have made a try and it works perfectly now.
