### ISSUE TITLE
FC (or batch matmul) between splited tensors in graph API.

### ISSUE THREAD

**Issue by neverdoubt** [ARM-software/ComputeLibrary#511]
I'm implementing a sort of dot-product attention.
I need to use existing node as a weight for FC as follows.

I did something like this.
```
                           -> Aa  ----- -> input
A - Splitnode ->                                         -> FCnode
                            -> Ab  ------> weight
```

a part of code..

NodeID GraphBuilder::add_attention_node(...)
{
...
NodeID S =  GraphBuilder::add_split_node(g, params, input, 2U, 0U);
NodeID OUT = g.add_node<FullyConnectedLayerNode>(out_len);
    g.add_connection(S, 0, OUT, 0);
    g.add_connection(S, 1, OUT, 1);
set_node_params(g, OUT, params);
return OUT;
}
It worked s i expected in NEON.
but not working (output wrong result) in open CL.

Maybe do i need to set output tensordescriptor for {S,1}?
if yes, can you give me an example for that?

Thanks in advance.

**Comment by neverdoubt** [comment]
I play with tensordescriptor, but no help.

I guess using tensor or existing node as a weight if FC layer is problem.
Maybe it  is not designed to do that.

Strange thing is in openCL it produces wrong FC result and in NEON it produces correct FC result, but it crashes(just return) at the end of Graph.run().
(i designed to call graph.run() 5 times. CL runs 5 times with wrong results, NEON runs only 1 and crash with a correct result.)

**Comment by GeorgeARM** [comment]
Hello @neverdoubt,

I don't think this is going to work as the FC layer expects a Const node for the weights. If A changes between runs then it should produce wrong result. Now the crash I think it comes from the internal memory manager that handles the intermediate buffers.

**Comment by GeorgeARM** [comment]
Graph API is experimental thus won't add support for more nodes/operators unless needed for integration testing.
