### ISSUE TITLE
Yocto Recipe

### ISSUE THREAD

**Issue by ghost** [ARM-software/ComputeLibrary#512]
Hello,

is there availbale ComputeLibrary via Yocto (yocto recipe)?

Thank you!

**Comment by morgolock** [comment]
Hi @peter73421 

No, we haven't worked with Yocto. We just release the prebuilt binaries on github. You can try with the latest binary release https://github.com/ARM-software/ComputeLibrary/releases/download/v18.05/arm_compute-v18.05-bin-linux.tar.gz which should work on any linux platform.

**Comment by AnthonyARM** [comment]
@peter73421 : I've tried to create a Yocto recipe, but I'm afraid I know very little about how Yocto works.

I think it should be enough to build the library in release mode however I haven't tested it.
[acl_18.05.bb.txt](https://github.com/ARM-software/ComputeLibrary/files/2260617/acl_18.05.bb.txt)
(Rename to acl_18.05.bb)

I've flagged this issue with "Help Wanted" and hopefully someone with more Yocto knowledge can help polish/fix the recipe.

**Comment by dhruvkakadiya** [comment]
Looks like that recipe is available under [openembedded](https://layers.openembedded.org/layerindex/recipe/87607/) which is not directly sourcing code from this repo and also NXP has that available under [CodeAurora](https://source.codeaurora.org/external/imx/meta-fsl-bsp-release/diff/imx/meta-sdk/recipes-support/arm-compute-library/arm-compute-library_git.bb?h=sumo-4.14.98-2.0.0_ga&id=52560982809ba6c1df043539e1c7ad026ffbe499) which is directly sourcing code from this repo so NXP one looks more promising.
