### ISSUE TITLE
Padding in tensors

### ISSUE THREAD

**Issue by ved27** [ARM-software/ComputeLibrary#513]
Hi,

I run the examples in Computelibrary-18.05/examples
I have a query regarding the internal padding that happens in tensors

Can I  know  function in which this padding happens in tensors exactly ?

Awaiting a speedy reply,

Thank you much,

**Comment by morgolock** [comment]
Hi @ved27 

Please take a look at this link which explains why the library uses padding for some algorithms:
[https://arm-software.github.io/ComputeLibrary/v18.05/architecture.xhtml#S4_6_1_padding_and_border](url)

There is no official list of the functions that require padding but you can easily get this information by running the following command: `rgrep FillBorder arm_compute/runtime/`. Any function in the library using padding will call into either `CLFillBorder` or `NEFillBorder`.

 https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/CL/functions/CLFillBorder.h
https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/NEON/functions/NEFillBorder.h

**Comment by NatalCoder** [comment]
I think there's a problem with ACL's FillBorder kernel. In CLFillBorderKernel.cpp, when the call returns from CLKernelLibrary::create_kernel, it gets assigned to the CL::Kernel _kernel object. I  am getting a Page Fault error in Mali GPU at this point. Have you run the validation tests with border_size other than 0? In case of 0, it doesn't even create a fill border kernel in the first place. Could you please share the results of validation tests with border_size 1 and 2?
Thanks in advance!

**Comment by NatalCoder** [comment]
@morgolock

**Comment by AnthonyARM** [comment]
Replied on #519
