### ISSUE TITLE
big gap in performance between graph APIs and CL functions

### ISSUE THREAD

**Issue by yoyo-zhao** [ARM-software/ComputeLibrary#514]
hi,
I have been working on accelerating a CNN network with Mali GPU. I noticed that two versions of mobilenetV1 were implemented in ACL, "examples/graph_mobilenet.cpp" and "tests/networks/MobileNetV1Network.h". When testing them on an MTK platform using mali gpu, "graph_mobilenet" finished in 120ms while "MobileNetV1Network" (as part of tests/benchmark/CL/SYSTEM) cost 224ms. 
Why there's such big gap in performance between calling graph APIs and CL functions?

arm_compute_version=v18.05
Build options: {'embed_kernels': '1', 'arch': 'arm64-v8a', 'opencl': '1', 'neon': '1', 'asserts': '1', 'debug': '0', 'os': 'linux', 'Werror': '1'}
Git hash=b3a371bc429d2ba45e56baaf239d8200c2662a74
Platform: Mediatek - MT2712
OS: linux

**Comment by AnthonyARM** [comment]
Hi,
The test in SYSTEM is a legacy test (It will be removed in the next release), it was created when we didn't have a Graph API in order for people to have an idea of what the performance would be like when running the entire network.
Nowadays we've got Graph support which contains several optimisations (Like heuristics to select the right algorithms, some layer fusion, etc.) so the Graph example is what should be used to measure performance.

Hope this helps,

**Comment by yoyo-zhao** [comment]
Thanks, it helps. Further question is that is it possible to insert a concat layer or add layer for constructing a residual block (which is common in Resnet and Mobilenet V2) with Graph APIs since they are used in kind of streaming manner?

**Comment by GeorgeARM** [comment]
Hello @yoyo-zhao,

Yes there is. Look at the [resnet_50 ](https://github.com/ARM-software/ComputeLibrary/blob/master/examples/graph_resnet50.cpp#L232)example to check how its done.
