### ISSUE TITLE
Questions on available functions

### ISSUE THREAD

**Issue by SRimbaudNviso** [ARM-software/ComputeLibrary#516]
Hi,

I'm working on raspberry Pi with NEON and I was looking for some functions.

- We have warpAffine function, is there something to estimate an affine transformation between two images (like getAffineTransform and estiamteRigidTransform with OpenCV).

- It's possible to compute image histogramm with NEHistrogram, is there a function to equalize an histogram like equalizeHist with OpenCV (or CLAHE on OpenCV)

- Image Blur can be done with the Gaussian kernel. This kernel is available with 5x5 and 3x3 sizes, I need some custom size (like 8x8, 9x9 or even 3x6). The convolution kernel exists only for 5x5 7x7 and 9x9 is there a way to convolve with other non squared kernels ? (I'm looking for something flexible, like GaussianBlur in OpenCV)

Thanks

**Comment by morgolock** [comment]
Hi @SRimbaudNviso 

- ACL has no equivalent to OpenCV's  `getAffineTransform()` and `estiamteRigidTransform()`. ACL's focus is on optimizing ML algorithms for ARM Systems; these functions you mention are not likely to bring massive performance gains.
- We have `NEEqualizeHistogram' in ACL: https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/NEON/functions/NEEqualizeHistogram.h . It's based on the OpenVX 1.2 specification.
- The function `NEConvolutionRectangle` allows non square sizes for the convolution matrix but the sizes must be  3, 5, 7 or 9. You can take a look at the header: https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/NEON/functions/NEConvolution.h#L115 . Presently there is no function in ACL allowing arbitrary matrix sizes for the convolution.

**Comment by SRimbaudNviso** [comment]
Ok, thanks for you answers. 

One last question, is there some camera calibration functions in ACL ? There is an optical flow kernel, is there a way to perform operation like solvePnP available on OpenCV ?

**Comment by morgolock** [comment]
Hi @SRimbaudNviso 

No, there no camera calibration functionality in ACL. This is really something not in the scope of the library which I mentioned in my previous post: optimise Vision & ML algorithms for ARM systems.
