### ISSUE TITLE
FillBorder Kernel issue

### ISSUE THREAD

**Issue by NatalCoder** [ARM-software/ComputeLibrary#519]
I think there's a problem with ACL's FillBorder kernel. In CLFillBorderKernel.cpp, when the call returns from CLKernelLibrary::create_kernel, it gets assigned to the CL::Kernel _kernel object. I am getting a Page Fault error in Mali GPU at this point. Have you run the validation tests with border_size other than 0? In case of 0, it doesn't even create a fill border kernel in the first place. Could you please share the results of validation tests with border_size 1 and 2? Surprisingly, there is no page fault happenning with other kernels like CLPooling..etc
Thanks in advance!

**Comment by AnthonyARM** [comment]
Yes, the validation tests for computer vision functions use all border modes, like for example [Convolution tests](https://github.com/ARM-software/ComputeLibrary/blob/master/tests/validation/CL/Convolution.cpp#L90)

What are you trying to run ? Is it an example ? Our validation tests ?

**Comment by NatalCoder** [comment]
@AnthonyARM
I wrote a wrapper around ACL to test it. When I ran PAD operation with ACL, it gives me page fault. Rest of the kernels I tested were working fine. I checked the code and I think the error is with accessing _kernel variable

**Comment by AnthonyARM** [comment]
We haven't noticed anything wrong with it, so please provide a sample code that highlight the problem.
