### ISSUE TITLE
Using ACL in Anroid Studio (cmake/ndk) 

### ISSUE THREAD

**Issue by ydmo** [ARM-software/ComputeLibrary#52]
I import libarm_compute.so to my project, but there is app can't run~
please help. thanks a lot

**gradle:**
apply plugin: 'com.android.application'

android {
    signingConfigs {
        yuda {
            keyAlias 'yuda'
            keyPassword '000000'
            storeFile file('/home/user/Android/keys/Key.jks')
            storePassword '000000'
        }
    }
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.example.user.demo_acl"
        minSdkVersion 22
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        externalNativeBuild {
            cmake {
                cppFlags "-std=c++11 -frtti -fexceptions"
                abiFilters 'arm64-v8a'
            }
        }
        sourceSets {
            main {
                jniLibs.srcDirs = ['libs']
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.yuda
        }
    }
    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.1.0'
    testCompile 'junit:junit:4.12'
}

**CMakeLists.txt:**

cmake_minimum_required(VERSION 3.4.1)

set(CMAKE_VERBOSE_MAKEFILE on)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=gnu++11")

set(pathToProject /home/user/Documents/MyApplication/app)

include_directories(${pathToProject}/src/main/cpp/include)

#compute:
add_library(lib_armcompute SHARED IMPORTED)
set_target_properties(lib_armcompute PROPERTIES IMPORTED_LOCATION ${pathToProject}/libs/${ANDROID_ABI}/libarm_compute.so)

#opencv:
add_library(lib_opencv SHARED IMPORTED )
set_target_properties(lib_opencv PROPERTIES IMPORTED_LOCATION ${pathToProject}/libs/${ANDROID_ABI}/libopencv_java3.so)

#opencl:
add_library(lib_opencl SHARED IMPORTED)
set_target_properties(lib_opencl PROPERTIES IMPORTED_LOCATION ${pathToProject}/libs/${ANDROID_ABI}/libOpenCL.so)

add_library(
             native-lib
             SHARED
             src/main/cpp/native-lib.cpp )
find_library( log-lib log )
target_link_libraries( # Specifies the target library.
                       native-lib
                       # Links the target library to the log library
                       # included in the NDK.
                       ${log-lib}
                       lib_opencv
                       # lib_opencl
                       lib_armcompute
                       )

**log:**
04-19 15:22:21.109 14420-14420/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.example.user.demo_acl, PID: 14420
                                                   java.lang.UnsatisfiedLinkError: dlopen failed: library "../../../../libs/arm64-v8a/libarm_compute.so" not found
                                                       at java.lang.Runtime.loadLibrary0(Runtime.java:994)
                                                       at java.lang.System.loadLibrary(System.java:1533)
                                                       at com.example.user.demo_acl.MainActivity.<clinit>(MainActivity.java:14)
                                                       at java.lang.Class.newInstance(Native Method)
                                                       at android.app.Instrumentation.newActivity(Instrumentation.java:1083)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2682)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                       at android.os.Looper.loop(Looper.java:156)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6524)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by mpflanzer** [comment]
The problem might be that the _soname_ is not set in the build of `libarm_compute.so` that your are using. (It is disabled by default as not all versions of `scons` support it.) You can check if the `SONAME` field is specified by doing `objdump -p build/libarm_compute.so | grep SONAME`.

If it is not set you have to tell CMake that the library that doesn't the `SONAME`.

```
add_library(arm_compute SHARED IMPORTED)
set_target_properties(arm_compute PROPERTIES
    IMPORTED_NO_SONAME 1
    IMPORTED_LOCATION "${pathToProject}/libs/${ANDROID_ABI}/libarm_compute.so"
)
```

If you have at least version 2.4 of scons you can pass the flag `set_soname=1` at compile time. Then there should be no need to specify `IMPORTED_NO_SONAME 1` when importing the library.

**Comment by ydmo** [comment]
@mpflanzer 
it works!!!!
Thanks a lot~~ ^_^~

**Comment by mobicham** [comment]
@ydmo How were you able to use the include headers? Simply copying the arm_compute folder (+ the other include folders/support) doesn't work in Android because it can only recognize the relative path (changing "arm_compute/core/.." to "../core/" for example). But doing this for all headers is a bit too much, so I was wondering how you were able to make it work

**Comment by jefby** [comment]
> IMPORTED_NO_SONAME

if i use Android.mk, do you know how to set soname for dynamic library??

**Comment by BowNV** [comment]
@mobicham   

I have the same problem with you:  How were you able to use the include headers? 

Have you resolved it? if so, please show me the steps, thanks a lot! 

thanks
bo

**Comment by tdh8316** [comment]
> The problem might be that the _soname_ is not set in the build of `libarm_compute.so` that your are using. (It is disabled by default as not all versions of `scons` support it.) You can check if the `SONAME` field is specified by doing `objdump -p build/libarm_compute.so | grep SONAME`.
> 
> If it is not set you have to tell CMake that the library that doesn't the `SONAME`.
> 
> ```
> add_library(arm_compute SHARED IMPORTED)
> set_target_properties(arm_compute PROPERTIES
>     IMPORTED_NO_SONAME 1
>     IMPORTED_LOCATION "${pathToProject}/libs/${ANDROID_ABI}/libarm_compute.so"
> )
> ```
> 
> If you have at least version 2.4 of scons you can pass the flag `set_soname=1` at compile time. Then there should be no need to specify `IMPORTED_NO_SONAME 1` when importing the library.

Okay, 8 years later, I finally found this answer, which once again saved me!
I spent a couple of hours trying to fix this error, which is resolved by simply adding the `IMPORTED_NO_SONAME 1` property.
