### ISSUE TITLE
undefined reference to arm_compute::CLConvolutionLayer::CLConvolutionLayer

### ISSUE THREAD

**Issue by nevenpiculjan** [ARM-software/ComputeLibrary#520]
I tried to build the library and use binaries, but in both cases I got the following error on Android:

undefined reference to `arm_compute::CLConvolutionLayer::CLConvolutionLayer(std::__ndk1::shared_ptr<arm_compute::IMemoryManager>)'.

I am using shared .so libraries.

It seems CLConvolutionLayer is missing from the library. I tried to use CLTensor and CLBatchNormalizationLayer and they work fine.

**Comment by morgolock** [comment]
Hi @nevenpiculjan 

Could you please share the command you use to build the library as well as other details like toolchain version and host platform?

**Comment by nevenpiculjan** [comment]
Hi @morgolock 

This is how I built the toolchain: $NDK/build/tools/make_standalone_toolchain.py --arch arm64 --install-dir $MY_TOOLCHAINS/aarch64-linux-android-ndk --stl gnustl --api 21

I used this command to build the library:
CXX=clang++ CC=clang scons Werror=1 -j8 debug=0 asserts=1 neon=0 opencl=1 embed_kernels=1 os=android arch=arm64-v8a

NDK version is: 17.1.4828580

Android version on Samsung Galaxy S7 is 8.0.0.

**Comment by AnthonyARM** [comment]
18.05 has been tested with r16b. (18.08 will work with r17b)

We haven't tried to build 18.05 with r17b, but the first thing you need to change is switch to `--stl libc++` instead of gnustl and you might have to fix one or two warnings / missing includes after that.

**Comment by nevenpiculjan** [comment]
When I use --stl libc++ instead of gnustl, I get SIGABRT. When will 18.08 be released?

**Comment by morgolock** [comment]
Hi @nevenpiculjan 

The update will be released soon.

In the meantime could you please try the ndk 16b and let us know if that solves the problem.

**Comment by nevenpiculjan** [comment]
With gnustl and ndk 16b I got the same error as with ndk 17b and gnustl. Combination of --stl libc++ and ndk 16b worked. Thank you.
