### ISSUE TITLE
OpenCL version needed for ACL Mali

### ISSUE THREAD

**Issue by uu-kameshm** [ARM-software/ComputeLibrary#521]
Hi

Could you please suggest which OpenCL version is required on the hardware platform to be able to run ARM Compute Library Mali GPU version?

Also, could you please let me know if ACL was used/tested using the ARM Mali GPUs available on the ARM Juno board . 

Thank you
Kamesh

**Comment by morgolock** [comment]
Hi @uu-kameshm 

1. The minimum required OpenCL version is 1.2 and the GPU/Driver must also support the non uniform workgroup size extension.
2. We haven't run our tests on Juno boards but we have done it on other boards with the same GPU, so I would say it should work fine.
