### ISSUE TITLE
Need clarification on fill_border.cl

### ISSUE THREAD

**Issue by NatalCoder** [ARM-software/ComputeLibrary#526]
Hi,
In fill_border.cl kernel, I was looking at the following snippet..

 */
__kernel void fill_image_borders_constant(
    TENSOR3D_DECLARATION(buf),
    uint      width,
    uint      height,
    int2      start_pos,
    DATA_TYPE constant_value)
{
    Image buf = CONVERT_TENSOR3D_TO_IMAGE_STRUCT_NO_STEP(buf);

    // Update pointer to point to the starting point of the valid region
    buf.ptr += start_pos.y * buf.stride_y + start_pos.x * buf.stride_x;

    const int total_width = BORDER_SIZE_LEFT + width + BORDER_SIZE_RIGHT;
    const int gid0        = get_global_id(0);
    const int gidH        = gid0 - total_width;
    const int gidW        = gid0 - BORDER_SIZE_LEFT;

    if(gidH >= 0)
    {
        // Handle left border
        for(int i = -BORDER_SIZE_LEFT; i < 0; ++i)
        {
            *(__global DATA_TYPE *)offset(&buf, i, gidH) = constant_value;
        }
        // Handle right border
        for(int i = 0; i < BORDER_SIZE_RIGHT; ++i)
        {
            *(__global DATA_TYPE *)offset(&buf, width + i, gidH) = constant_value;
        }
    }
    else
    {
        // Handle top border
        for(int i = -BORDER_SIZE_TOP; i < 0; ++i)
        {
            *(__global DATA_TYPE *)offset(&buf, gidW, i) = constant_value;
        }
        // Handle bottom border
        for(int i = 0; i < BORDER_SIZE_BOTTOM; ++i)
        {
            *(__global DATA_TYPE *)offset(&buf, gidW, height + i) = constant_value;
        }
    }
}

As we can see, it only handles two borders at a time.. either top and bottom or left or right.. why is it like that? Shouldn't a fill border kernel handle all the 4 borders at a time?

**Comment by mdigiorgio** [comment]
Hi @NatalCoder 

The kernel itself does handle all 4 borders at a time. It just distinguish between threads, depending on the global ID the thread fills either top and bottom, or left and right. Does that answer your question?

**Comment by NatalCoder** [comment]
Thanks for the clarification. I was implementing Pad operation using this kernel and in my output, it is filling only the left and right borders. Top and bottom are not filled.

**Comment by mdigiorgio** [comment]
Could you share the values you pass to the `configure()` method of the fill border kernel?

**Comment by NatalCoder** [comment]
ICLTensor *tensor,
1 1 2 2
1 1 2 2
3 3 4 4
3 3 4 4

BorderSize border_size,
1
 BorderMode border_mode, 
CONSTANT
const PixelValue &constant_border_value
O

output after the run:
0 1 2 0
0 1 2 0
0 3 4 0
0 3 4 0

**Comment by mdigiorgio** [comment]
Hi @NatalCoder 

FillBorder only writes values in the padding and you should set the padding yourself in the tensor info before configuring the FillBorder kernel. If you print the tensor, padding isn't visible. In fact, I tried to reproduce your use case and I don't get the output you mention above. I don't think you can use that kernel to do what you want.

If it can be of any help, we are planning to add a Pad operator in the 18.11 release.

**Comment by NatalCoder** [comment]
Hi @mdigiorgio 
So, currently there is no kernel to fill a constant value in the tensor itself?
I forgot to mention, I commented out the line which limits the border_size to zero if there is no padding just to check whether the kernel will be able to fill values in the tensor. (CLFillBoderdrKernel's configure).
Had it not filled anything, I would not have suspected thing, but the kernel filled a couple of borders and ignored the other two.

**Comment by mdigiorgio** [comment]
No, I'm afraid at the moment we don't have what you need. But, as I said, we''l probably have a Pad operator in 18.11 if that can help.

That check is there exactly to make sure that the input tensor does have space for padding, which is what FillBorder will fill.

**Comment by NatalCoder** [comment]
Hmm.. Thanks for the clarification. Can I just ask you one more question before we close this issue?
How do I modify the tensor buffer? I tried pointing a new buffer's pointer to tensor->buffer() and also tried memcpy. In all the cases, the tensor remains the same and there is no segmentation fault.

**Comment by mdigiorgio** [comment]
No problem at all.

In order to modify the values of a tensor you can refer to the following examples:
- https://github.com/ARM-software/ComputeLibrary/blob/master/examples/gc_dc.cpp
- https://github.com/ARM-software/ComputeLibrary/blob/master/examples/neon_copy_objects.cpp

The first uses the GLES backend. Since you are using CL you'll need to do perform `map()` and `unmap()` of the tensor you want to access/modify. The examples show how to use windows, iterators and coordinates to modify the contents of a tensor. You can play around with the coordinates to read/write values from/to where you want.

**Comment by NatalCoder** [comment]
Yes.  I'm using map and unmap.
Thanks a lot for your support.

**Comment by mdigiorgio** [comment]
No problem. We've actually found a bit of a hacky way to do what you ask. In order to do that you need to move the valid region back one step in all directions and then use fill border. So your example could work like this:

```
auto tshape = TensorShape(2, 2);
A.allocator()->init(TensorInfo(tshape,  1, DataType::F32));
A.info()->extend_padding(PaddingSize{1});
A.info()->set_valid_region(ValidRegion(Coordinates(-1,-1), TensorShape(4,4)));
CLFillBorderKernel k;
k.configure( &A, BorderSize{1}, BorderMode::CONSTANT, 0);
A.allocator()->allocate();
```

Then you could copy the contents of  `A` to a tensor with shape 4x4. Hope this helps.

**Comment by NatalCoder** [comment]
looks good, but it does not change the dimensions of the tensor A, in which case a direct use of CLCopy kernel would fail I think. Please correct me if I'm wrong.

**Comment by NatalCoder** [comment]
@mdigiorgio 
Have you tried the above mentioned approach? If so, could you please share the results? 
Because at my end, I am getting a page fault.
```
mali 11800000.mali:: Unhandled Page fault in AS0 at VA 0x00000000B5790FF8
[638417.394958] Reason: Memory is not mapped on the GPU
[638417.394958] raw fault status: 0x100003C3
[638417.394958] decoded fault status: SLAVE FAULT
[638417.394958] exception type 0xC3: TRANSLATION_FAULT
[638417.394958] access type 0x3: WRITE
[638417.394958] source id 0x1000
[638417.394958] pid: 10335
[638417.429522] mali 11800000.mali:: t6xx: GPU fault 0x4002 from job slot 1
```

**Comment by NatalCoder** [comment]
`C++ exception with description "clEnqueueMapBuffer" thrown in the test body.`

**Comment by mdigiorgio** [comment]
Hi @NatalCoder 

I had to modify the code a bit by moving the call to `set_valid_region()` after running the kernel through `k.run()`. I get the following result with no page faults or exceptions (I've only tried the 2x2 case though):

Input
65 65 
65 65 

Output
 0  0  0  0 
 0 65 65  0 
 0 65 65  0 
 0  0  0  0 

But again, this is a hacky solution. Padding and valid regions are not meant to be used that way. So, if you plan to use it, do it with caution and when the pad operator will be available you can switch to it.

Hope it helps.
