### ISSUE TITLE
_kernel.setArg failing in a new sample cl kernel.

### ISSUE THREAD

**Issue by kuladeep2706** [ARM-software/ComputeLibrary#528]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

**Platform:**
arm64-v8a 

**Operating System:**
Android Oreo

**Problem description:**
Hello,
I was trying to implement a sample cl kernel in Compute library and _kernel.setArg is failing without any error.

I tried this way.
In CLSampleKernel.cpp,
```cpp
    _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name, build_opts));
    unsigned int idx = 0;
    _kernel.setArg<cl_uint>(idx++, static_cast<int32_t>(_input->info()->dimension(0)));
```
In sample_kernel.cl,
```cpp
#include "helpers.h"
__kernel void sample_kernel(uint a)
{
} 
```
_input->info()->dimension(0) -> this value is filled & proper.

Added all the other required changes in Compute Library. 

Any pointers in what I might be missing are appreciated.
Thanks in advance!

**Comment by AnthonyARM** [comment]
Can you try with the library built with `assert=1` or `debug=1`, it should give you more information about why it fails

**Comment by AnthonyARM** [comment]
Can you try with `static_cast<cl_uint>`, might just be a type mismatch

**Comment by AnthonyARM** [comment]
Also, in your test code, make sure you're catching `cl::Error` and displaying them properly: usually the `what()` will only return the name of the entry point (clSetKernelArg in your case), and you need to query separately `err()` to get the actual error.

**Comment by kuladeep2706** [comment]
1. I tried typecasting to cl_uint & still it's not a success. 
2. I tried catching cl::Error using the above example, the error is not caught.

**Comment by kuladeep2706** [comment]
Is there a limit on number of arguments for kernel?

**Comment by GeorgeARM** [comment]
Hello @kuladeep2706,
It depends. You can get the max size in bytes of the arguments that you can pass by checking `CL_DEVICE_MAX_PARAMETER_SIZE` using `clGetDeviceInfo`.

**Comment by mpekatsoula** [comment]
Closing, reopen if needed.
