### ISSUE TITLE
Need clarification on Memory Manager

### ISSUE THREAD

**Issue by cancro7** [ARM-software/ComputeLibrary#529]
Hi,

I am trying to use ACL18.05 in a project. 
I don't understand how to use the memory manager, 
in particular how can I manage lifetime for input tensors of a DepthConcatenationLayer?

Thanks for your help,
Antonio

**Comment by GeorgeARM** [comment]
Hello @cancro7,

What are you trying to achieve? Can you elaborate a bit? You could use our experimental Graph API to create an ML pipeline or [armnn](https://github.com/ARM-software/armnn)

**Comment by cancro7** [comment]
Hi @GeorgeARM,

thanks for the fast reply.
I am using the _runtime abstraction_ of the library since I want to have more fine-grain control on the code.
The Neural Net I want to describe has a graph similar to the following:
![issue_example](https://user-images.githubusercontent.com/17797308/44734704-d5276c80-aaea-11e8-86d6-dd524529be47.png)
As far as I understand I have to declare 2 memory managers:
- One for the memory requirements of a layer
- One for the input/output of each layer.

In my case I have that during the execution of a concatenation 3 tensors (2 input tensors and 1 output tensor ) should be active as memory regions.
Is it right to:
- Use 3 memory groups for the I/O memory manager
- Set to 3 the number of pools of the I/O memory manager

Thanks for your time,
Antonio

**Comment by GeorgeARM** [comment]
Hello @cancro7,

I would go for an initial implementation using the Graph API to have a quick prototype. Graph API should optimize your memory and also do some optimizations were possible (e.g. zero copy on DepthConcatenation etc).

But if you already have the pipeline working using functions directly and you want to add memory management then:

> As far as I understand I have to declare 2 memory managers:
    One for the memory requirements of a layer
    One for the input/output of each layer.

Yes you are correct.

You need one memory manager that will take care of the auxilary memory requirements of all the functions. This is controlled by the functions so you don't have to do something. Just create one and pass it to the functions that require one. In the end just finalize it with a single pool and it should be fine.

Once this is done you can add the support for the memory manager that controls the transition tensors. This is a bit more difficult to do as you have to explicitly define the lifetime of the tensors. You will need another memory manager and a single memory group (not 3).
You have to register the memory_group to the tensors that you want to be managed  and call `manage()`/`allocate()` in the correct order to define the `start`/`end` lifetime of the tensor.
We call `manage()` before configuring a function using the given tensor for the first time and `allocate` after the last function configure that uses this tensor. Beware not to put any tensor that contain trainable parameters (weights, biases) to the memory manager. These shouldn't be managed by the manager as their data are persistent. In the end finalize the memory manager with a single pool and it should be fine.

**Comment by cancro7** [comment]
Very helpful, I will try and let you know.

Just for curiosity, in the neon_cnn example there is a comment about the number of pool (lines 224,225)

> // Number of pools that the manager will create. This specifies how many models we can run in 
   // parallel.
  // Setting to 2 as we need one for the input and one for the output at any given time
  mm_transitions->set_num_pools(2);                                        

 is it incorrect?

Thanks,
Antonio

**Comment by GeorgeARM** [comment]
@cancro7 
Yes seems that documentation is outdated in this case. Will update it in the next release. Sorry for any inconvenience.

**Comment by cancro7** [comment]
Thanks a lot, it seems to work. Now I am testing it deeply, thus in case I will reopen the issue.

**Comment by mpekatsoula** [comment]
Closing, reopen if needed.
