### ISSUE TITLE
NDK-Build Error

### ISSUE THREAD

**Issue by Igamegum** [ARM-software/ComputeLibrary#53]
when I use ndk-build in jni programming，I have got some error  when I want to make a DLL;

THE erroe message show  as below 
[armeabi-v7a] Compile++ thumb: gesture_opencv <= Interface.cpp
jni/mtcnn/Interface.cpp: In function 'void Func()':
jni/mtcnn/Interface.cpp:103:50: error: expected primary-expression before '(' token
     src.allocator()->init(arm_compute::TensorInfo(src_shape, 1, DataType::F32) );
                                                  ^
jni/mtcnn/Interface.cpp:103:65: error: reference to 'DataType' is ambiguous
     src.allocator()->init(arm_compute::TensorInfo(src_shape, 1, DataType::F32) );
                                                                 ^
In file included from jni/include/arm_compute/core/IKernel.h:27:0,
                 from jni/include/arm_compute/core/CPP/ICPPKernel.h:27,
                 from jni/include/arm_compute/core/NEON/INEKernel.h:27,
                 from jni/include/arm_compute/runtime/NEON/INESimpleFunction.h:27,
                 from jni/include/arm_compute/runtime/NEON/functions/NEAbsoluteDifference.h:27,
                 from jni/include/arm_compute/runtime/NEON/NEFunctions.h:28,
                 from jni/mtcnn/Interface.cpp:8:
jni/include/arm_compute/core/Types.h:59:12: note: candidates are: enum class arm_compute::DataType
 enum class DataType
            ^
In file included from jni/include/opencv2/core.hpp:56:0,
                 from jni/include/opencv2/opencv.hpp:46,
                 from jni/mtcnn/Interface.cpp:3:
jni/include/opencv2/core/traits.hpp:106:30: note:                 template<class _Tp> class cv::DataType
 template<typename _Tp> class DataType
                              ^
make: *** [obj/local/armeabi-v7a/objs/gesture_opencv/mtcnn/Interface.o] Error 1

My Code Show as Below 
void Func()
{

    Tensor src;
    constexpr unsigned int width_src_image = 32;
    constexpr unsigned int height_src_image = 32;
    constexpr unsigned int ifm_src_img = 3;
    const TensorShape src_shape(width_src_image, height_src_image, ifm_src_img);
    src.allocator()->init(arm_compute::TensorInfo(src_shape, 1, DataType::F32) );
}

My Application.mk show as below 
APP_PLATFORM := android-14
APP_ABI :=  armeabi-v7a arm64-v8a 
APP_STL :=gnustl_static
NDK_TOOLCHAIN_VERSION :=4.9
APP_CPPFLAGS += -std=c++11 

What Should I do?

**Comment by mpflanzer** [comment]
```
jni/mtcnn/Interface.cpp:103:65: error: reference to 'DataType' is ambiguous
src.allocator()->init(arm_compute::TensorInfo(src_shape, 1, DataType::F32) );
^
```
At least one problem is that both OpenCV and ARM Compute defined the `DataType` type. Since you seem to include both types and probably make them available via `using` directives the compiler doesn't know which to use. Specifying the namespace explicitly should solve at least this problem.
```
src.allocator()->init(arm_compute::TensorInfo(src_shape, 1, arm_compute::DataType::F32));
```

To provide more help we would need to see the whole content of `Interpolation.cpp` (including the include statements).

**Comment by Igamegum** [comment]
@mpflanzer  yes,you are right ,thank you
