### ISSUE TITLE
Where to download “cnn_data“?

### ISSUE THREAD

**Issue by Frankzhangnxp** [ARM-software/ComputeLibrary#530]
**Output of 'strings libarm_compute.so | grep arm_compute_version':** v18.05 

**Platform:** arm64-v8a NXP i.MX8QMMEK

**Operating System:** Linux imx8qmmek 4.14.62-imx_4.14.y+gef7acf9 built by Yocto

**Problem description:**
Hi All,

    We are running the validation code in ARM compute library. For LeNet and AlexNet testing cases, a cnn_data directory is used, but we can't find whre it is. Could you please tell me where I can download it or how to generate it from Caffe or TF models. Many thanks in advance！

Best Regards,
Frank

**Comment by AnthonyARM** [comment]
Hi Frank,
We don't provide the weights because the files are too large, you need to generate them from the Caffe / TF models.
There are some instructions about how to do that in the [documentation](https://arm-software.github.io/ComputeLibrary/v18.05/data_import.xhtml)

**Comment by Frankzhangnxp** [comment]
Hi Anthony,

     Thank you for your reply. Yes, I have got these weight and bias npy files by the script. But how to generate cat.npy used in the Alexnet validation code? Thank you!

Best Regards,
Frank

**Comment by Frankzhangnxp** [comment]
Hi Anthony,

     Thanks for your reply, Yes, we have We have downloaded the caffe model from http://dl.caffe.berkeleyvision.org/bvlc_alexnet.caffemodel. and used that script to generate the weight and bias npy file. Also we generate a "cat.npy" with NCHW layout . Then the validation "'NEON/SYSTEM_TESTS/AlexNet" can run, but the result is not expected. We got 669, but the expected labels result is 281. I don't know what the label 669 mean. Could you please tell me how to get the meaning to each label number of this caffe model? Thank you.

Best Regards,
Frank

**Comment by mdigiorgio** [comment]
Closing this issue. Reopen if needed.
