### ISSUE TITLE
Depthwise convolution without pointwise in compute library

### ISSUE THREAD

**Issue by sgurminder** [ARM-software/ComputeLibrary#531]
**Output of 'strings libarm_compute.so | grep arm_compute_version':** v.18.05

**Platform:**  

**Operating System:**  Tizen

**Problem description:**
Hello,
I am implementing slim model ssdlite_mobilenet_v2_coco_2018_05_09 (Caffe) in compute library.  It uses Depthwise Convolutions without pointwise convolutions. 
i.e Number of channels before  = Number of channels after.
We took code from get_dwsc_node() from graph_mobilenet.cpp and removed the "pointwise" convolution part. 
 I get rank of tensor mismatch error. Mismatch of shape in *.npy and tensor_shape
for e.g npy expects  3 3 1 32  and tensor_shape is 3 3 32. 

I need help to use  Depthwise convolution without pointwise as there are no weights for pointwise.

Thanks for Help
Gurminder

**Comment by GeorgeARM** [comment]
Hello @sgurminder,

Try to reshape your numpy arrays from (3,3,1,32) to (3,3,32). Should be trivial to do.
Check if it works this way.

**Comment by mpekatsoula** [comment]
Closing, reopen if needed.
