### ISSUE TITLE
library "libGLES_mali.so" not found when running arm_compute_benchmark

### ISSUE THREAD

**Issue by htjacky** [ARM-software/ComputeLibrary#533]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

arm_compute_version=v18.05 Build options: {'embed_kernels': '1', 'os': 'android', 'opencl': '1', 'neon': '1', 'validation_tests': '0', 'benchmark_tests': '0', 'extra_cxx_flags': '-fPIC', 'arch': 'arm64-v8a'} Git hash=e2542c9f35ca427286822cd0c9296f49914f78b0

**Platform:**
Android

**Operating System:**
Ubuntu 14.04

Hi,

I'm trying to run arm_compute_benchmark on an Android phone with mali GPU supported, follow the steps provided in https://arm-software.github.io/ComputeLibrary/latest/tests.xhtml#writing_tests.

But get following error:

WARNING: linker: /data/local/tmp/arm_compute_benchmark: unsupported flags DT_FLAGS_1=0x8000000
Can't load libGLES_mali.so: dlopen failed: library "libGLES_mali.so" not found
Can't load libmali.so: dlopen failed: library "libmali.so" not found
Couldn't find any OpenCL library.
terminating with uncaught exception of type cl::Error: empty
Aborted 

I tried following solutions:

1. Move /vendor/lib64/egl/libGLES_mali.so to current folder(/data/local/tmp/), create a symbol link for libmali.so;

2. Rebuild Compute library and arm NN without openCL;

But it still doesn't work, shows the same error message.

By the way, the UnitTest of ARM NN works fine, without error.

I think both of them(arm_compute_benchmark and ARM NN unit test) depended with  libGLES_mali.so, but the result shows different.

**Comment by htjacky** [comment]
It works only if I change following line in OpenCL.cpp:
static const std::vector<std::string> libraries{ "libOpenCL.so", "libGLES_mali.so", "libmali.so" };
to a complete path such as:
static const std::vector<std::string> libraries{ "/data/local/tmp/libGLES_mali.so"};

**Comment by mdigiorgio** [comment]
Hi @htjacky 

The reason why the change you made in OpenCL.cpp works is that you have given the absolute path to the library. In order to make it work without that change, you need to specify your libraries locations using:

```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<path_to_libraries>
```

In your case:


```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/vendor/lib64/egl/
```

**Comment by htjacky** [comment]
Hi @mdigiorgio

It's fixed with your suggestion, thanks so much!

**Comment by mdigiorgio** [comment]
Glad to hear that, you are very welcome.

**Comment by Samzizo** [comment]
Hello, 
Can u plz tell me where exactly past this:
- export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/vendor/lib64/egl/
I just started a course in android, I tried to past it in Terminal but it still every time show me the same error u had??!!
I am using mac big Sur
