### ISSUE TITLE
Need clarification on Windows and Padding Requirements

### ISSUE THREAD

**Issue by cancro7** [ARM-software/ComputeLibrary#536]
Hi,

Currently I am using the 18.05 Compute Library for a project.
I would ask if you can give me an overview of the **windows** in particular when they are used
to compute the _padding requirements of the input tensors_ of a layer/kernel.
For example I was not able to understand why you use this windows in the _validate_and_configure_windows_ of the NEGEMMMatrixMultiplyKernel . (lines 1571,1572,1573, 1574 of src/core/NEON/kernels/NEGEMMMatrixMultiplyKernel.cpp).

`window_changed = \
    update_window_and_padding(win,
                                                     AccessWindowRectangle(input0, 0, 0, 4, 1, 1.f, 0.25f),
                                                      AccessWindowStatic(input1, 0, 0, input1->tensor_shape().x(), ceil_to_multiple(input1->tensor_shape().y(), 4)),
                                                   output_access);`

I am asking this because I am implementing new kernels and I am not able to set padding correctly.

Thanks for your time.
Regards,
Antonio

**Comment by cancro7** [comment]
Hello @GeorgeARM,

Thanks for your reply.

I am trying to generalize the interleave4x4 and transpose1_W and the  _manual loop unrolling_  used in the inner code of the GEMM. 
Lets consider the following parameters:
- interleaveZxZ: Z is the new value for the interleaving of the matrix A.
- transpose1_W: W is the parameter for the blocked transposition of the matrix B.
- K is the value of the _manual loop unrolling_

Given these parameters the new access patterns to the matrices will be:
- Z*K  values accessed in the matrix A at a time.
- W*K values accessed in the matrix B at a time.

Ask me if it is not clear.

Just for my learning process could you give me a general overview of the windows?
As far as I understand they are a good way to create an abstraction for access pattern for both SIMD operations and multithreading, thus they seems very interesting to me.

Thanks for your help.
Regards, 
Antonio

**Comment by GeorgeARM** [comment]
Hello @cancro7,

We are in the process of updating our documentation with explanations for all the concepts needed to create custom kernels/functions. This will be part of the next release hopefully.
Concerning your questions, yes your assumptions are correct, its an abstraction on access patterns to ease vectorization and multi-threading.
