### ISSUE TITLE
How to use OpenCL datatypes like image2d_t in Compute Library code?

### ISSUE THREAD

**Issue by ssj4gogeta** [ARM-software/ComputeLibrary#539]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

**Platform:**
arm64-v8a

**Operating System:**
Android O

**Problem description:**
How can I use OpenCL datatypes like image2d_t in Compute Library code?

**Comment by GeorgeARM** [comment]
Hello,
At the moment we have no API for using other cl types apart from cl_buffer. Is there a specific reason for wanting to used `image2d_t`?

**Comment by ssj4gogeta** [comment]
I am able to use these data types. Hence closing.
