### ISSUE TITLE
CL memory management of a CNN implemented with GEMM Convolutions

### ISSUE THREAD

**Issue by ved27** [ARM-software/ComputeLibrary#542]
Hi,

In the case of allocating im2col buffer , each convolution layer of a CNN allocates **separate im2col buffer** , which is costly in terms of memory if the network has many convolutions .  

This can be handled by having one global im2col buffer of maximum size to run a CNN .  
Is the same type of optimized memory cost mechanism followed in CL of Compute Library- 18.05  ? If so, please provide a reference

Awaiting a speedy reply,
Thank you much

**Comment by GeorgeARM** [comment]
Hello @ved27,
If you use our graph API which utilizes our memory manager this is what's is going to happen. In other words a single buffer will be allocated for the im2col for all the CNN layers.

**Comment by ved27** [comment]
Hi, @GeorgeARM 

I also set the usage of memory manager to **false** in graphconfig . So even when the memory manager is false , the graph api uses a single buffer ?

**Comment by GeorgeARM** [comment]
Hello @ved27,
There are two managers present in the graph API:
The transition manager that reuses transition (connecting) tensors among the layers and the function memory manager which reuses memory required internally by all the the functions.

**Comment by ved27** [comment]
Yea , figured it out as the comments of mem-manager were altered in my code.
Thank you much
