### ISSUE TITLE
Memory usage between GEMM convolution and Winograd convlution

### ISSUE THREAD

**Issue by ved27** [ARM-software/ComputeLibrary#543]
Hi,

Compute Library - 18.05

Can I please know the memory usage comparison between a CLGEMMConvolution layer and CLWinograd layer ? 
I know how CLGEMMConv layer works using Im2col  but unaware of winograd layer and its internal buffer allocation . I wish to know the memory usage of winograd layer, if it really uses less memory than the case of Im2col in GEMMConvolution  ?

Awaiting for a response,
Thank you much

**Comment by ved27** [comment]
Is there any estimate of additional buffer usage in winograd layer ?

**Comment by ved27** [comment]
Hi,

Any info available ? Kindly share, if available

Thank you,

**Comment by AnthonyARM** [comment]
No we don't any data I'm afraid, you should be able to measure it by yourself though.

**Comment by gmiodice** [comment]
Hi @ved27,

I think you can find some information in my recent presentation at the embedded vision summit 2018 (https://www.embedded-vision.com/platinum-members/arm/embedded-vision-training/videos/pages/may-2018-embedded-vision-summit-iodice#comment-form). At minute 30, I evaluate the memory footprint for both GEMMConvolutionLayer and WinogradConvolutionLayer for the case 3x3 with 2x2 output tile. You should be able to extend the formula to other cases such as the 3x3 convolution with 4x4 output tile or the 5x5 convolution with 4x4 output tile.

i.e. 3x3 with 4x4 output tile
Input transform memory: 36*(W/4)*(H/4)*Cin
Output transform memory: 36*(W/4)*(H/4)*Cout

Hope this can help you.

**Comment by GeorgeARM** [comment]
Hello @ved27,

As per @gmiodice comment you can work out the space requirements of each convolution implementation.
Closing this issue. Reopen if needed.
