### ISSUE TITLE
cannot build example on bare metal and general questions

### ISSUE THREAD

**Issue by Yang-YiFan** [ARM-software/ComputeLibrary#546]
**compute library version:** 18.08

**Platform:** armv7a

**Compiles on:** Linux

**Problem description:**

Hi,
I try to build the neon convolution example on bare metal using Xilinx SDK 2017.1. The compiler I'm using is arm-none-eabi-g++ 6.2.1 (also tried 6.3.1). And it always pops up error like 
```
undefined reference to std::thread
undefined reference to std::condition_variable
```
which looks like arm-none-eabi-g++ doesn't support c++11 and pthread. I add `-std=c++11` and `-lpthread`. But it doesn't help. I was wondering is there by any chance I could build the example in bare metal? Or can I build a one without those multithread features without compromising the convolution performance?
Thanks,
Yifan

**Comment by AnthonyARM** [comment]
I'm confused, why does "Operating System" says Linux ? Or is that the host ?
What scons command line did you use ?

**Comment by Yang-YiFan** [comment]
@AnthonyARM  By linux I mean I use a linux operating system to compile the neon convolution example to a ELF file to run on the armv7a CPU. The compiler is `arm-none-eabi-g++`. I want the example to run on bare metal mode without a operating system on ARM CPU. 
No, I didn't use scons to build. I compile `Utils.cpp` and `neon_convolution.cpp` to .o file. And then I use `arm-none-eabi-g++`'s linker to link `Utils.o`, `neon_convolution.o`, `libarm_compute-static.a`, `libarm_compute_core-static.a` and `libarm_compute_graph-static.a` (in dir `/lib/linux-armv7a-neon`) to generate the final .elf file. Every time I tried to link the error pops out (in my last post).
When I switch to compiler `arm-linux-gnueabihf-g++` to compile and link, it built .elf successfully. This compiler is target for linux system on ARM (it's not bare metal). So I think at least my flow is correct. It's just the issue with `arm-none-eabi-g++` compiler for bare metal.
Thanks,
Yifan

**Comment by mpekatsoula** [comment]
Hi @Yang-YiFan 

Didn't you use scons to build the library for bare metal? Where did you get the static libraries from?
You should first compile the library with scons, ie: `scons Werror=0 -j8 debug=1  os=bare_metal` and then try and link with the example you want. 
You can find more information in the documentation here: https://arm-software.github.io/ComputeLibrary/v18.08/index.xhtml#S3_4_bare_metal

Keep in mind that we've only tested bare metal with arm-eabi ans not arm-none-eabi.

**Comment by Yang-YiFan** [comment]
Hi @mpekatsoula ,
I get it now. I just use the static library provided in the v18.08 release. I will recompile it. I still have 2 questions.
1. if I compile with bare metal, does it support multi-threading?
2. I have already build the neon convolution example using `arm-linux-gnueabihf-g++`. I was wondering does the neon convolution kernel automatically handles the multi-threading stuff or I have write it in the example src file?
Thanks,
Yifan

**Comment by mpekatsoula** [comment]
@Yang-YiFan 

1. Unfortunately bare metal builds do not support multi-threading.
2. All the functions support multi-threading and run on all the available CPU cores. You don't have to make any changes.

**Comment by Yang-YiFan** [comment]
@mpekatsoula 
2. To be more specific, I'm using `neon_convolution.cpp` and `neon_cnn.cpp` examples. Do you mean I don't need to add any code and the examples can automatically run on all of the available cores?
3. Add 2more question, is there a efficient way to copy data from a C array to `arm_conpute::Tensor`? I have looked into the `neon_copy_objects.cpp`, but it still needs to iterate over different rows which is not efficient for a small feature map.
4. It seems like I can't copy tensor b to tensor a by just calling `a=b`. The compiler indicates that this method is deleted. So how exactly can I copy a tensor to another?
Thanks,
Yifan

**Comment by mpekatsoula** [comment]
@Yang-YiFan 
2. Yes that's correct, the library will take care of the multi threading.
3. Because you don't know how much padding the tensor will require the correct way to copy data is like in the neon_copy_objects example.
4. You can use the CLCopy/NECopy functions in order to copy two tensors.

**Comment by mpekatsoula** [comment]
Closing this, reopen if needed.
