### ISSUE TITLE
Live demonstrator for classification network

### ISSUE THREAD

**Issue by ddenaro** [ARM-software/ComputeLibrary#548]
Hi,
This is not an issue but a request for clarification.
I would like to use the Graph Interface to build a simple network topology used for image classification.
I am wondering if exists a memory accessor useful to feed the InputLayer.
The examples show how to feed the InputLayer with jpeg,ppm, numpy and random data but in case of a live demonstrator I plan to use a camera.
Do I have to write my own feeder ?
Thanks
Davide

**Comment by GeorgeARM** [comment]
Helllo @ddenaro,

Yes, you have to write your own `Accessor` to feed data from a camera into the graph.

**Comment by ddenaro** [comment]
Ok
thanks
