### ISSUE TITLE
About ACL opencl initialization code

### ISSUE THREAD

**Issue by 18810579179** [ARM-software/ComputeLibrary#549]
Hi:

Thank your for your wonderful work.

Now I can just build and link your provided application(`examples/graph_inception_v3.cpp`) against your library on my Mali G72 GPU for arm_compute-v18.08-bin-android，and get the performance. In your `examples/graph_inception_v3.cpp` file, I can just see the graph  execution process in the code:
```
    void do_run() override
    {
        graph.run();
    }
```

But, I wonder where the opencl initialization code is, such as create context/program/kernel/memory object and so on.

expect your reply soon. 
Best wishes

**Comment by mpekatsoula** [comment]
Hi @18810579179 
You can have a look at [CLKernelLibrary.cpp](https://github.com/ARM-software/ComputeLibrary/blob/master/src/core/CL/CLKernelLibrary.cpp) and [CLScheduler.cpp](https://github.com/ARM-software/ComputeLibrary/blob/master/src/runtime/CL/CLScheduler.cpp) to see how we manage kernels, issue execution etc. 
Also, have a look at the [documentation](https://arm-software.github.io/ComputeLibrary/v18.08/index.xhtml#S1_file_organisation) for more information.
