### ISSUE TITLE
How can I increase the dimention of a ITensor?

### ISSUE THREAD

**Issue by bulletcross** [ARM-software/ComputeLibrary#550]
Given a shape of a ITensor for example [3, 4, 5], how can I increase the dimension to [3, 1, 4, 5]. Here I introduced a dimension at axis 1.

**Comment by mpekatsoula** [comment]
Hi @bulletcross 
Once you allocate memory for a Tensor you cannot change its dimensions.

**Comment by GeorgeARM** [comment]
Hello @bulletcross ,

You can change the shape of your tensor by using the `CLReshapeLayer` or `NEReshapeLayer`, depending on the backend that you need. Reshape layer needs the produce of the dimensions of the input and the output to be the same, so it will work in you case.
