### ISSUE TITLE
CLTuner Example

### ISSUE THREAD

**Issue by hemantbits** [ARM-software/ComputeLibrary#555]
Please can you provide an example on how to use CLTuner? There is no example for this. cl_sgemm.cpp initializes CLTuner but doesn't use it.

**Comment by mpekatsoula** [comment]
Hi @hemantbits 
The test is correct. You should just pass pass a CLTuner object to CLScheduler before configuring any function. If you want to store the results in a csv file you should call:
` tuner.save_to_file(filename);`. 

You can find more information in the [documentation](https://arm-software.github.io/ComputeLibrary/v18.08/index.xhtml#S3_9_cl_tuner).
