### ISSUE TITLE
Not all permutations are supported

### ISSUE THREAD

**Issue by vishal-keshav** [ARM-software/ComputeLibrary#556]
According to CLPermuteKernel, there are only three permutations available namely [2,0,1], [1,2,0] and [3,2,0,1].

Is there any support for other Tensor permutations (mostly 4 dimensional). How shall I proceed to implement/use other permutations?

**Comment by mpekatsoula** [comment]
Hi @bulletcross 
That's correct, we only support 3 permutations so far. May I ask which permutation you need? You can have a look at how the [CLPermuteKernel.cpp](https://github.com/ARM-software/ComputeLibrary/blob/52ba29e936b8e711e8acdfe819e36f884d4f3fe1/src/core/CL/kernels/CLPermuteKernel.cpp) is implemented and you can try to add a new one.

**Comment by GeorgeARM** [comment]
Hello @bulletcross,
Can you prioritize the permutations needed? We will try to schedule them, but yes we plan to support all possible ones in the future.

**Comment by gupta-shubham** [comment]
Hello, @bulletcross  @mpekatsoula , I have created a generic permute kernel which can handle any permutation upto 4d tensors.
Logic goes like this : 
1. let PV = permutation required , eg PV={2,0,1,3} which needs to be applied on NCHW format. 
2. using global ids get current values of W , H , C and N for input and assigned to input_index_array[0 to 3]
3. now to find the new position of these parameters(W,H,C and N) using the permutation vector like 
out_index[0] = input_index_array[PV[0]] and so on...
4. store in output by out.ptr+offset(out_index[0]..., out_index[3]) = input.ptr

I have verified the logic with the test cases generated by me.
So, can u tell is it the good approach to solve for this issue?

**Comment by bulletcross** [comment]
Thanks. Method posted by @gupta-shubham works. I am wondering why a generic permutation kernel was not implemented and instead implementation was done for three different permutation kernels.

**Comment by GeorgeARM** [comment]
Hello @bulletcross @gupta-shubham,
Yes logic is correct and should work, don't know why we didn't implement it directly this, I would have thought due to optimization purposes but seems the kernels are not optimal. Will try to include this in next release.
Thanks for all your suggestions.

**Comment by bulletcross** [comment]
@GeorgeARM Thanks for confirming.

**Comment by gupta-shubham** [comment]
@GeorgeARM  Since the logic has been approved, I would like to add that code to ACL src-code.

**Comment by GeorgeARM** [comment]
Sure @gupta-shubham, more than happy for that.
Create a pull request and will review it.

**Comment by gupta-shubham** [comment]
Okay I will create a pull request in a day or two.

**Comment by vishal-keshav** [comment]
This issue has been resolved. Hence, closing this issue.
