### ISSUE TITLE
Implementation of Crop 2D layer Required.

### ISSUE THREAD

**Issue by BhaskarsarmaP** [ARM-software/ComputeLibrary#557]
Hi,

Is there any support for 2D Crop Layer ?. It is good to have support for 2D crop layer, because this layer used in FCN. (or) Is there any way to use existing kernels to support 2D cropping?.

Thanks,
Bhaskar

**Comment by mpekatsoula** [comment]
Hi @BhaskarsarmaP 
By Crop you mean [Caffe's Crop](http://caffe.berkeleyvision.org/tutorial/layers/crop.html)? You can do this using the Slice and Concat operators. Slice operator will be part of the next release.

**Comment by BhaskarsarmaP** [comment]
Thank you,
Waiting for next release.
