### ISSUE TITLE
wrong syntax of inline functions in OpenCL

### ISSUE THREAD

**Issue by justPe** [ARM-software/ComputeLibrary#559]
Hi,
i tried to run examples of library on i.mx8 board with Vivante OpenCL gpu. I came accros some problem with inline functions defined in src/core/CL/cl_kernels/helpers.h. 

They have syntax as follows :

Vector inline update_vector_workitem_ptr()
Image inline update_image_workitem_ptr()
__global inline const uchar *vector_offset()
...

but keyword "inline" of declaration by  C99  should be as follows:
inline <function_declaration>

then declarations of methods should look like as follows:

inline Vector  update_vector_workitem_ptr()
inline  Image update_image_workitem_ptr()
inline  __global const uchar *vector_offset()
...

It's possible to change the declarations so they are closer to the standard because some OpenCL compilers don't understand the syntax ?

thanks

**Comment by mpekatsoula** [comment]
Hi @justPe 
Have you tried to change the inline definitions in src/core/CL/cl_kernels/helpers.h and compile? Does it work? Can you also share the error you get from the compiler?

Thanks

**Comment by justPe** [comment]
Yes when i change definition of inline function, compilation works.
for example when function looks like as follow:

Vector inline update_vector_workitem_ptr()

i get error:

(213:0) : error : syntax error at 'inline'

**Comment by mpekatsoula** [comment]
Could you create a pull request with your changes? 
Also, where you able to run any OpenCL example on this platform?

**Comment by justPe** [comment]
ok i did. i hope it's ok.
yes some examples work but some don't.. e.g. in kernel file im2col.cl i have problem with select() method. 
i get error: function: 'select' hasn't the corresponding declaration 
and test from  
arm_compute_validation --filter-id=1514
gets sigsegv.
when i find problem i try to make pull request if it would be possible :)

**Comment by GeorgeARM** [comment]
This is fixed [here](https://git.mlplatform.org/ml/ComputeLibrary.git/commit/?h=refs/heads/master&id=af7f740229e9f08f6ce26c513b372775160537b3). Closing.
