### ISSUE TITLE
How could I create a demo for GEMM.

### ISSUE THREAD

**Issue by xlxulin1** [ARM-software/ComputeLibrary#56]
I have created a sample for GEMM. but I can't get the rigth output. Below is my code, is there any problems?
    int rowNum = 3;
    int colNum = 2;
    int k = 4;

    NEGEMM armGemm;
    Tensor         matrixA, matrixB, matrixOut;

    // tensor shape for channel.
    const TensorShape shapeA(k, rowNum);
    const TensorShape shapeB(colNum, k);
    const TensorShape shapeOut(colNum, rowNum);

    matrixA.allocator()->init(TensorInfo(shapeA, DataType::F32));  
    matrixB.allocator()->init(TensorInfo(shapeB, DataType::F32));
    matrixOut.allocator()->init(TensorInfo(shapeOut, DataType::F32));

   matrixA.allocator()->allocate();
    matrixB.allocator()->allocate();
    matrixOut.allocator()->allocate();

float tmpV = 0;
 for(unsigned int h = 0; h < rowNum; h++)
        {
            for(unsigned int w = 0; w < k; w++)
            {
                
		tmpV = *reinterpret_cast<float*>( matrixA.buffer() + matrixA.info()->offset_element_in_bytes(Coordinates(w,h,0))) = A[w + h * k] ; 
                printf("%f,", tmpV);
            }
            printf("\n");
        }

     tmpV = 0;
        for(unsigned int h = 0; h < k; h++)
        {
            for(unsigned int w = 0; w < colNum; w++)
            {
		tmpV = *reinterpret_cast<float*>( matrixB.buffer() + matrixB.info()->offset_element_in_bytes(Coordinates(w,h,0))) = B[w + h * colNum] ; 
                printf("%f,", tmpV);
            }
            printf("\n");
        }

    armGemm.configure(&matrixA, &matrixB, NULL, &matrixOut, 1, 0);
    printf("----------------\n");
    armGemm.run();

    for(unsigned int h = 0; h < rowNum; h++)
        {
            for(unsigned int w = 0; w < colNum; w++)
            {
                tmpV = *reinterpret_cast<float*>( matrixOut.buffer() + matrixOut.info()->offset_element_in_bytes(Coordinates(w,h,0)));
                printf("%f,", tmpV);
            }
        }
        printf("\n");

the output is always 0.

**Comment by xlxulin1** [comment]
A is 0123    4567 89 10 11  
b is 01   23   45  67

**Comment by gmiodice** [comment]
Hello @xlxulin1,

the problem seems related to the allocation of the tensors. In your code the allocation of the tensors is called before the configure() method. The configure method updates the padding bytes requirements for each tensor used so it is necessary to allocate the memory only after that. Following you can find a sample code.

Hope this can help you.
Gian Marco

`
    (i.e. Allocation after the configure method)
    
    int rowNum = 3;
    int colNum = 2;
    int k = 4;
    const TensorShape shapeA((unsigned int)k, (unsigned int)rowNum);
    const TensorShape shapeB((unsigned int)colNum, (unsigned int)k);
    const TensorShape shapeOut((unsigned int)colNum, (unsigned int)rowNum);

    matrixA.allocator()->init(TensorInfo(shapeA, 1, DataType::F32));
    matrixB.allocator()->init(TensorInfo(shapeB, 1, DataType::F32));
    matrixOut.allocator()->init(TensorInfo(shapeOut, 1, DataType::F32));

    // Configure the functions to call
    armGEMM.configure(&matrixA, &matrixB, nullptr, &matrixOut, 1.0f, 0.0f);

    // Memory allocation

    // Now that the padding requirements are known we can allocate the images:
    matrixA.allocator()->allocate();
    matrixB.allocator()->allocate();
    matrixOut.allocator()->allocate();

    float tmpV = 0;
    for(int h = 0; h < rowNum; h++)
    {
        for(int w = 0; w < k; w++)
        {
            tmpV = *reinterpret_cast<float*>( matrixA.buffer() + matrixA.info()->offset_element_in_bytes(Coordinates(w,h,0))) = (float)(w + h * k);
            printf("%f,", tmpV);
        }
        printf("\n");
    }

    tmpV = 0;
    for(int h = 0; h < k; h++)
    {
        for(int w = 0; w < colNum; w++)
        {
            tmpV = *reinterpret_cast<float*>( matrixB.buffer() + matrixB.info()->offset_element_in_bytes(Coordinates(w,h,0))) = (float)(w + h * colNum);
            printf("%f,", tmpV);
        }
        printf("\n");
    }

    // Execute the functions:
    armGEMM.run();

    for(int h = 0; h < rowNum; h++)
    {
        for(int w = 0; w < colNum; w++)
        {
            tmpV = *reinterpret_cast<float*>( matrixOut.buffer() + matrixOut.info()->offset_element_in_bytes(Coordinates(w,h,0)));
            printf("%f,", tmpV);
        }
    }
    printf("\n");`

**Comment by xlxulin1** [comment]
hi @gmiodice 

Thanks, it works.

**Comment by victorygogogo** [comment]
if one matrix need to transpose ,can NEGEMM work well  ?
