### ISSUE TITLE
Tutorial for replacing cv::cvtColor function to CLColorConvert or NEColorConvert

### ISSUE THREAD

**Issue by shirbarzel** [ARM-software/ComputeLibrary#560]
I would be happy to receive a Tutorial that has a detailed explanation and maybe an example of how I can make this replacement in order to optimize my system

**Platform:** RKX3399

**Operating System:** Linux ubuntu

**Problem description:**

Tutorial for replacing cv::cvtColor function to CLColorConvert or NEColorConvert

I want to convert yuyv to bgr
replacing : cv::cvtColor(input, output,cv::COLOR_YUV2BGR_YUYV);
Thanks

**Comment by mpekatsoula** [comment]
Hi @shirbarzel 

Using NE/CLColorConvert is the same as using any other function. You can have a look at the [examples](https://github.com/ARM-software/ComputeLibrary/tree/master/examples) and try to understand how it's done. You can find the list of available conversions [here](https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/NEON/functions/NEColorConvert.h).
