### ISSUE TITLE
GPU to CPU memcpy is consuming huge time

### ISSUE THREAD

**Issue by uu-praveeng** [ARM-software/ComputeLibrary#563]
Hi,

I have implemented the alexnet using the armcompute-cl apis. 
Alexnet execution is faster  , but the time taken to transfer softmax output to CPU is pretty huge(if entire network takes 10 ms GPU to CPU transfer takes 100ms).

This doesnt seem to be justified ,Is there anyway we could reduce this overhead?

Thank you,
G. Praveen.

**Comment by GeorgeARM** [comment]
Hello @uu-praveeng,
We need more information about how your pipeline looks like. Are you sure you wait for your opencl queue to finish before you collect the timings of the network run?

**Comment by uu-praveeng** [comment]
Thank you George. I was missing the sync. Now the numbers appear reasonable.
