### ISSUE TITLE
graph_mobilenet QASYMM8  speed test  abnormal

### ISSUE THREAD

**Issue by WenguoLi** [ARM-software/ComputeLibrary#565]
add test time code:  https://github.com/ARM-software/ComputeLibrary/blob/master/examples/graph_mobilenet.cpp#L116

```
    void do_run() override
    {
        struct timeval start, end;

        // Run graph
        for (int i = 0; i < 10; ++i) {
          graph.run();
        } 
        
     	gettimeofday(&start, NULL);              
        // Run graph
        for (int i = 0; i < 50; ++i) {
          graph.run();
        }        
        gettimeofday(&end, NULL); 
        
        int timeuse = 1000000 * ( end.tv_sec - start.tv_sec ) + end.tv_usec -start.tv_usec;
	printf("\ntime: %f ms\n", timeuse/50000.0);
    }
```
after built ...
adb push graph_mobilenet  data/local/tmp
adb shell 
cd data/local/tmp

```
./graph_mobilenet --threads=4

Threads : 4
Target : NEON
Data type : F32
Data layout : NHWC
Tuner enabled? : false
Tuner file : 
Fast math enabled? : false


time: 123.174700 ms
```
But 

```
./graph_mobilenet --threads=4 --type=QASYMM8 

Threads : 4
Target : NEON
Data type : QASYMM8
Data layout : NHWC
Tuner enabled? : false
Tuner file : 
Fast math enabled? : true

time: 1960.270360 ms
```

Compared with F32 MobileNet, QASYMM8 MobileNet model should take less time, right ?

Please help! 

Thanks

**Comment by GeorgeARM** [comment]
Hello @WenguoLi,

Yes performance of the QASYMM8 is not optimized for mobilenet in 18.08 for NEON. We have improved performance a lot and will part of the next release.
Hope this helps.

**Comment by WenguoLi** [comment]
Thanks, @GeorgeARM.

**Comment by GeorgeARM** [comment]
Closing this issue @WenguoLi. Reopen if the issue persists on the next release. Thank you for your questions and useful help.
