### ISSUE TITLE
Time benchmarking of examples? 

### ISSUE THREAD

**Issue by ghimiredhikura** [ARM-software/ComputeLibrary#566]
Hello, 

How can I test the runtime of each examples? As I can see every example will invoke `int run_example(int argc, char **argv, std::unique_ptr<Example> example)`  from `utils/Utils.cpp`, can I just calculate the graph run time in this function. Or am I missing something? 

One more thing, do I must need to run graph with actual weights and test image to calculate time? 

As run time also can be calculated just like this:
```
./build/examples/graph_mobilenet
```
I am not sure it will be actual run time or now. 

Any help will be greatly appreciated. 
Thanks.

**Comment by GeorgeARM** [comment]
Hello @ghimiredhikura,

In your scons command you can set `benchmark_tests=1`, this should create binaries for each example with the prefix `benchmark_`. Then you can use the benchmarking framework infrastructure to benchmark each example.

e.g.
```
benchmark_graph_alexnet --iterations=10 --example_args="--target=cl,--type=f32" --instruments="wall_clock_timer_ms"
```

You can check all the common graph parameters [here](https://github.com/ARM-software/ComputeLibrary/blob/master/utils/CommonGraphOptions.h#L37) and you can check the instruments that you can use [here](https://github.com/ARM-software/ComputeLibrary/blob/master/tests/framework/instruments/Instruments.cpp#L39).

**Comment by ghimiredhikura** [comment]
Thanks @GeorgeARM. Great. 
Just check - for vgg16 model using single thread, f32 and neon in RPI3B+(armv8a) I got graph run time just 92 ms. Do you think it is correct?

**Comment by GeorgeARM** [comment]
Hello @ghimiredhikura,
Can you post the command you executed?

**Comment by WenguoLi** [comment]
Hi, GeorgeARM ,

I set benchmark_tests=1 in my scons command : 

 scons arch=arm64-v8a neon=1 opencl=1 embed_kernels=1 extra_cxx_flags="-fPIC" \
  benchmark_tests=1 validation_tests=0 os=android -j16

But I didn't find those binaries for each example with the prefix benchmark_,  e.g benchmark_graph_alexnet.

Did I make a mistake somewhere?

Thanks!

**Comment by GeorgeARM** [comment]
Hello @WenguoLi,
seems we haven't exposed it in the public repo, so I suppose the only way is to do it manually.  Just do not forget to sync at the end of the pipeline in case of CL execution. So yes you can benchmark in the run_example function.

**Comment by WenguoLi** [comment]
Thanks @GeorgeARM

**Comment by ghimiredhikura** [comment]
@WenguoLi, same here. 
@GeorgeARM, waiting for the new release. Closing the issue.

**Comment by AnthonyARM** [comment]
If you build `master` from the dev repo: https://review.mlplatform.org/#/admin/projects/ml/ComputeLibrary if you build with `benchmark_examples=1` you will get two sets of binaries: `./build/examples/graph_*` and `build/tests/benchmark_graph_*`. The latter one is the instrumented one.
