### ISSUE TITLE
How to enable NEON F16 support ?

### ISSUE THREAD

**Issue by WenguoLi** [ARM-software/ComputeLibrary#569]
Hi, 

I see that most kernels have supported NEON F16, how to enable NEON F16 support  in example/graph_mobilenet ?  

BRs

**Comment by GeorgeARM** [comment]
Hello @WenguoLi, 

to enable fp16 you have to compile for `arch=arm64-v8.2-a` architecture, meaning that you have to have also the hardwate that has native fp16 support.

**Comment by GeorgeARM** [comment]
Closing this issue. FP16 compilation for neon requires toolchain and hw support. Can be achieved by setting `arch=arm64-v8.2-a` . Reopen if needed.
