### ISSUE TITLE
Question about Optimizing neural networks for mobile and embedded devices with TensorFlow

### ISSUE THREAD

**Issue by Jeong-Heon** [ARM-software/ComputeLibrary#570]
Hi, I am a student interested in deep running on arm processors.

I have a question about the following guide: 
https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides/optimizing-neural-networks-for-mobile-and-embedded-devices-with-tensorflow/benchmark-the-optimized-models 

> Model type              | Processor               | Model size | 1-batch inference
> 32-bit floating point | Arm Cortex A73      | 97 MB        | 1794ms
> 8-bit integer             | Arm Cortex A73      | 25 MB       | 935ms
> 32-bit floating point | 4x Arm Cortex A73  | 97 MB       | 567ms
> 8-bit integer             | 4x Arm Cortex A73 | 25 MB        | 522ms

According to the table above, the quantization efficiency in a single core is high and the efficiency in a 4x arm core is low.

Why does multi-core's quantization efficiency drop?

**Comment by GeorgeARM** [comment]
Hello @Jeong-Heon,

I am not aware of what the attached document uses, but we have an int8 mobilenet benchmark in ACL and it seems that performance scales with the number of threads as expected. At least that what I see from a quick run that I had now. You can benchmark it yourself and find out.

**Comment by Jeong-Heon** [comment]
@GeorgeARM Thank you for your reply. 

The point of my question is that the inference performance of a single core is 1794 ms and the inference performance of 8-bit quantization is 935 ms. This seems to be about twice as fast.
However, when four cores are used, the inference performance is 567 ms and the inference performance of the 8-bit quantization is 522 ms, which is about 40 ms difference.
When using 4-core 8-bit quantization, the speed I expected was 234 ms (2 times faster than 567 ms).

Can you explain in more detail?

**Comment by GeorgeARM** [comment]
As I mentioned above @Jeong-Heon  I am not aware of what backend is being used in the page you posted. I don't think it uses ACL directly so I cannot comment on that. But yes performance should scale closely to what you mentioned, and that's what I see in ACL from the test runs I did.

**Comment by Jeong-Heon** [comment]
@GeorgeARM 
Oh, I mistook it as an ACL backend, only looking at the word 'optimization'. I will benchmark for the results I expected. Thank you.

**Comment by GeorgeARM** [comment]
Closing this reopen if needed, or raise a separate ticket if your findings do not match your expectations.
