### ISSUE TITLE
Feature Request: "install_dir" option to scons

### ISSUE THREAD

**Issue by ayounes-nviso** [ARM-software/ComputeLibrary#571]
scons install_dir=<install_dir>

This would install the 3 static libraries to:
   <install_dir>/lib
and the relevant headers to:
   <install_dir>/include

Thanks,
Abdel.

**Comment by AnthonyARM** [comment]
Hi Abdel,

Just to confirm, if you were to pass `install_dir=out` you would expect to get the following:

```bash
antbar01@antbar01:/acl/build/linux-arm64-v8a-neon-asserts/out$ tree
.
├── bin
│   ├── arm_compute_benchmark
│   ├── arm_compute_validation
│   ├── graph_alexnet
│   ├── ...
│   ├── neon_cartoon_effect
│   └── ...
├── include
│   └── arm_compute (all headers)
└── lib
    ├── libarm_compute_core.so
    ├── libarm_compute_core-static.a
    ├── libarm_compute_graph.so
    ├── libarm_compute_graph-static.a
    ├── libarm_compute.so
    └── libarm_compute-static.a
```

**Comment by ayounes-nviso** [comment]
Hi Anthony,

Yes, exactly what I would expect.

Of course I would also expect that this install option is consistent with the various compile options and just install what is needed (for example I might not want to compile nor install all the binaries or the shared libraries).

Thanks!

**Comment by AnthonyARM** [comment]
It will only install whatever gets built by the other options. (i.e if you've got examples=0 then none of the graph_* neon_* cl_* binaries will be installed, etc.)

Was that what you meant ?

**Comment by ayounes-nviso** [comment]
yes, exactly.

**Comment by GeorgeARM** [comment]
Closing as this is fixed [here](https://git.mlplatform.org/ml/ComputeLibrary.git/commit/?h=refs/heads/master&id=01bbd5fd0af0847ac847c78c7064b3c9810a924a)
