### ISSUE TITLE
Feature Request: build out of source

### ISSUE THREAD

**Issue by ayounes-nviso** [ARM-software/ComputeLibrary#573]
Hello,

It is currently not possible to build armcl out of the source directory. Out of source building is very important when your builds for various platforms are automated. As a work-around we can copy the source tree for each build target but this is far from optimal.

When passing "scons build_dir=/some/path" will put the object file in "build/some/path" subdirectory of the source folder.

Moreover, scons will also create a "..dblite" file at the root of the source directory; this database should be created in the build folder instead.

Thanks in advance and best regards,
Abdel

**Comment by AnthonyARM** [comment]
Hi,
The `..dblite` file depends on the version of SCons you're using: from a quick check around the office it looks like if you've got SCons 2.3.x or 2.4.x then you'll have a global `..dblite` file however with SCons 3.0.x you'll get `build/my-platform-build` and `build/my-platform-build.dblite` (i.e one dblite file per platform build instead of one global one).

Anyway, we've been building on our Jenkins server multiple flavours of the library in parallel and this has never caused any problem. So, I'm not 100% sure what this file is used for by SCons, but I assume it's to keep track which files have been changed, so my guess would be that it will only make a performance difference if you do some incremental builds (In which case it will probably unnecessarily rebuild some files, but I'm pretty sure it will not corrupt the build).

Hope this helps,

**Comment by ayounes-nviso** [comment]
Hi Anthony,

You are correct, we are using scons 2.x and the ..dblite seems harmless indeed. As this is fixed in scons 3.x then you can ignore the second part of the feature request :-)

Thanks,
Abdel

**Comment by AnthonyARM** [comment]
Hi Abdel,

Could you please try the patch below and tell me if it does what you want (Basically, if the build_dir is an absolute path then the build system won't try to put it in the `build` folder)

```diff
diff --git a/SConstruct b/SConstruct
index ede4f7d1d5..3417234d4d 100644
--- a/SConstruct
+++ b/SConstruct
@@ -59,16 +59,23 @@ vars.AddVariables(
 )
 
 env = Environment(platform="posix", variables=vars, ENV = os.environ)
-env.Append(LIBPATH = ["#build/%s" % env['build_dir']])
+build_path = env['build_dir']
+# If build_dir is a relative path then add a #build/ prefix:
+if not env['build_dir'].startswith('/'):
+    SConsignFile('build/%s/.scons' % build_path)
+    build_path = "#build/%s" % build_path
+else:
+    SConsignFile('%s/.scons' % build_path)
+
+env.Append(LIBPATH = [build_path])
 Export('env')
 Export('vars')
 
-SConsignFile('build/.%s' % env['build_dir'])
 
 Help(vars.GenerateHelpText(env))
 
 if env['build'] == "embed_only":
-    SConscript('./SConscript', variant_dir='#build/%s' % env['build_dir'], duplicate=0)
+    SConscript('./SConscript', variant_dir=build_path, duplicate=0)
     Return()
 
 if env['neon'] and 'x86' in env['arch']:
@@ -246,16 +253,16 @@ env.Append(CXXFLAGS = env['extra_cxx_flags'])
 Export('version_at_least')
 
 if env['opencl']:
-    SConscript("./opencl-1.2-stubs/SConscript", variant_dir="build/%s/opencl-1.2-stubs" % env['build_dir'], duplicate=0)
+    SConscript("./opencl-1.2-stubs/SConscript", variant_dir="%s/opencl-1.2-stubs" % build_path, duplicate=0)
 
 if env['gles_compute'] and env['os'] != 'android':
     env.Append(CPPPATH = ['#/include/linux'])
-    SConscript("./opengles-3.1-stubs/SConscript", variant_dir="build/%s/opengles-3.1-stubs" % env['build_dir'], duplicate=0)
+    SConscript("./opengles-3.1-stubs/SConscript", variant_dir="%s/opengles-3.1-stubs" % build_path, duplicate=0)
 
-SConscript('./SConscript', variant_dir='#build/%s' % env['build_dir'], duplicate=0)
+SConscript('./SConscript', variant_dir=build_path, duplicate=0)
 
 if env['examples'] and env['os'] != 'bare_metal':
-    SConscript('./examples/SConscript', variant_dir='#build/%s/examples' % env['build_dir'], duplicate=0)
+    SConscript('./examples/SConscript', variant_dir='%s/examples' % build_path, duplicate=0)
 
 if env['os'] != 'bare_metal':
-    SConscript('./tests/SConscript', variant_dir='#build/%s/tests' % env['build_dir'], duplicate=0)
+    SConscript('./tests/SConscript', variant_dir='%s/tests' % build_path, duplicate=0)
diff --git a/tests/SConscript b/tests/SConscript
index 38e4d47c5f..e060b67713 100644
--- a/tests/SConscript
+++ b/tests/SConscript
@@ -71,7 +71,6 @@ else:
 
 test_env.Append(CPPPATH = ["#3rdparty/include"])
 test_env.Append(LIBPATH = ["#3rdparty/%s/%s" % (env['os'], env['arch'])])
-test_env.Append(LIBPATH = ["#build/%s" % env['build_dir']])
 
 common_files = Glob('*.cpp')
 common_objects = [test_env.StaticObject(f) for f in common_files]
```

**Comment by ayounes-nviso** [comment]
This patch works like a charm.

Thanks for the prompt answer and patch!

**Comment by AnthonyARM** [comment]
Thanks for confirming, we'll review and merge this patch.

**Comment by GeorgeARM** [comment]
Closing as this was [merged](https://git.mlplatform.org/ml/ComputeLibrary.git/commit/?h=refs/heads/master&id=e8a55dfb02f998ebdfe6ec2a06cd976206c0065f). Reopen if needed
