### ISSUE TITLE
How to perform tensor addition or subtract?

### ISSUE THREAD

**Issue by yanlei08** [ARM-software/ComputeLibrary#576]
How to perform tensor addition or subtract? It seems like there is no element-wise layer.
Anyone has ideas? Thanks very much!

**Comment by GeorgeARM** [comment]
Hello @yanlei08,
These are all the function that we have in [NEON](https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/NEON/NEFunctions.h#L27). As you can see there are `ArithmeticAddittion` and `ArithmeticSubtraction` layer that you can use.

**Comment by yanlei08** [comment]
Hello @GeorgeARM,
I got it. Thank you for your reply.
