### ISSUE TITLE
why mobilenet graph example qasymm8 mode run much slower than float mode?

### ISSUE THREAD

**Issue by liwei46** [ARM-software/ComputeLibrary#578]
Hi all,

We are trying to test the speed of qasymm8  using ACL version 18.08 with surprising results. We are using the example mobilenet V1, testing on one single image, hardware is Rasperry PI. 
(as we do not have actual weights forqasymm8, summy weight data is used.  )
1) float mode: take 490 ms;
2) qasymm8 mode: take  3423 ms. 
(screen attached below)

Is the results normal?

Regards,
liwei

![acl-qasymm8](https://user-images.githubusercontent.com/18522264/47707383-9f2b7380-dc66-11e8-8cd9-9328186ee802.png)

**Comment by GeorgeARM** [comment]
Hello @liwei46,
This was an issue in the latest release as the optimized kernels are not dispatched for Int8.
We have fixed that and the performance in the upcoming release should be fixed.

**Comment by GeorgeARM** [comment]
Closing as you can test up to date performance [here](https://review.mlplatform.org/#/admin/projects/ml/ComputeLibrary). Reopen if needed
