### ISSUE TITLE
CMake best practices with ComputeLibrary

### ISSUE THREAD

**Issue by Wheest** [ARM-software/ComputeLibrary#579]
Hello there,

Let's say I have successfully built ARM-CL, and it is in `~/tools/arm/ComputeLibrary/build`.

Now, I have a project in some other directory.  It uses the CMake build system.  I want to be able to leverage ARM-CL, use the the tools provided by it etc.

Using CMake, as we need to link our code to the library, and include the ARM-CL headers.  Our project structure is thus:

```
.
├── _build
├── CMakeLists.txt
└── src
    ├── CMakeLists.txt
    └── gemm_armcl.cpp
```

CMake folk: how would you link ARM-CL?
- Download and build ARM-CL in the project directory.
- Use some sort of `FindARMCL.cmake` script
- Globally install ARM-CL by adding symbolic links in some common location?

[This StackOverflow](https://stackoverflow.com/a/41909627/6267719) post seems like a way to do it, though when it comes to ARM-CL I'm not entirely sure what and where to link.

**Comment by Wheest** [comment]
Have been working away with the ComputeLibrary, and did eventually get an okay workflow going with it.  Has been a good learning experience.

I have made a minimum working example from my project, which you can find in [this Github repo](https://github.com/Wheest/armcl_cmake_mwe).  Hopefully this will be useful for other people starting out like me.  

Any suggestions for improvements would be appreciated, since right now I have the library built from source, and the path to the build directory as an environment variable ([see MWE](https://github.com/Wheest/armcl_cmake_mwe)).

**Comment by AnthonyARM** [comment]
Thanks for sharing your example, closing this issue for now.
