### ISSUE TITLE
Does it support fourier transform?

### ISSUE THREAD

**Issue by zanazakaryaie** [ARM-software/ComputeLibrary#581]
Hello

I'm looking for a faster alternative to OpenCV's dft function. 

Does ComputeLibrary include a Neon-based Fourier transform?

**Comment by GeorgeARM** [comment]
Hello @zanazakaryaie,

Unfortunately, we don't have a NEON- based DFT in ComputeLibrary.
Is this something you are interested in? If yes we can mark it as feature request which we can try and schedule when we can or you can contribute one yourself as ACL is open for contributions [here ](https://review.mlplatform.org/#/projects/ml/ComputeLibrary,dashboards/ComputeLibrary:master).

**Comment by zanazakaryaie** [comment]
Hello GeorgeARM
Thanks for your reply

Actually, I was looking for a way to accelerate object trackers (e.g. KCF, MOSSE, etc.) on ARM CPUs and I found that DFT is the main time-consuming part of such algorithms. I tried to use FFTW library which has mentioned to benefit from Neon coprocessor but it was 3-4 times slower than OpenCV's DFT! 

Since I've seen similar requests for a faster DFT ([link1](https://stackoverflow.com/questions/10436673/fftw-vs-opencv-cvdft), [link2](https://dsp.stackexchange.com/questions/24375/fastest-implementation-of-fft-in-c), [link3](https://groups.google.com/forum/#!topic/arrayfire-users/6y5Ec0l-ENk), [link4](http://answers.opencv.org/question/75780/android-opencl-dft-vs-cpp-version-is-very-slow/)), I think it would be very nice if you add a Neon-based DFT in upcoming versions of ACL.

**Comment by mpekatsoula** [comment]
HI @zanazakaryaie 

Are you interested in complex to complex or real to complex transform?

**Comment by morgolock** [comment]
Hi @zanazakaryaie 

In 19.05 we introduced DFT
https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/NEON/functions/NEFFT1D.h
https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/NEON/functions/NEFFT2D.h

This is used in the convolution layer for specific shapes.

Please reopen the ticket if you need additional support.
