### ISSUE TITLE
Run example graph_mobilenet with QASYMM8 data type and CL target

### ISSUE THREAD

**Issue by sqlin** [ARM-software/ComputeLibrary#583]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v18.08 Build options: {'embed_kernels': '1', 'gles_compute': '1', 'arch': 'arm64-v8a', 'opencl': '1', 'neon': '1', 'asserts': '1', 'debug': '0', 'os': 'linux', 'Werror': '1'} Git hash=52ba29e936b8e711e8acdfe819e36f884d4f3fe1

**Platform:**

**Operating System:**

Hi,
I try to run example graph_mobilenet with QASYMM8 data type, but it would report error as follows:
$ **graph_mobilenet --type=QASYMM8 --target=CL**

**ERROR in validate_all_nodes src/graph/detail/ExecutionHelpers.cpp:50: in validate_arguments src/core/CL/kernels/CLDirectConvolutionOutputStageKernel.cpp:51: ITensor data type QASYMM8 not supported by this kernel No such process**

And running graph_mobilenet with dafault data type goes well:
$**graph_mobilenet --target=CL**
Could you help to support this issue? Thanks.

**Comment by gmiodice** [comment]
Hi @sqlin ,

what platform are you using?

thanks,
Gian Marco

**Comment by sqlin** [comment]
Hi Gian,

I run it on MTK6763 platform, and the GPU is ARM T720.

Thanks,
Shiqin

**Comment by ManubARM** [comment]
Hi @sqlin ,
We have found the problem, thanks for opening the issue

Manuel

**Comment by mpekatsoula** [comment]
Closing. This should be fixed in the [19.02](https://github.com/ARM-software/ComputeLibrary/releases/tag/v19.02) release.
