### ISSUE TITLE
Feature Request: 'tests' option to build tests programs

### ISSUE THREAD

**Issue by ayounes-nviso** [ARM-software/ComputeLibrary#584]
**Platform:**
ALL

**Operating System:**
ALL

**Problem description:**

This is a feature request: add a 'tests' option to build tests programs.

Except for os=bare_metal tests programs are always built, which is time consuming in a CI environment and is not needed when not developing ArmCL.

**Comment by AnthonyARM** [comment]
Hi @ayounes-nviso,

I'm not sure what you're talking about: by default `validation_tests=0` `benchmark_tests=0` (As you can see [here](https://github.com/ARM-software/ComputeLibrary/blob/master/tests/SConscript#L32) )
Only `examples=1` is enabled by [default](https://github.com/ARM-software/ComputeLibrary/blob/master/SConstruct#L46) but you can easily disable them by using `examples=0`

**Comment by ayounes-nviso** [comment]
Hi Anthony,

I see, for some reason those variables are set to 'True' by default...

Good, thanks for the pointer and sorry about the noise!
