### ISSUE TITLE
compile fails with 'Werror=1 opencl=1' in gcc 8 by '-Wcatch-value'

### ISSUE THREAD

**Issue by FanShupei** [ARM-software/ComputeLibrary#585]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

**Platform**: x86_64

**Operating System**: fedora 29

**Problem description:**
When compiling Arm ComputeLibrary 18.08 with Fedora's default gcc 8, it triggers a lot of warnings

```
include/CL/cl2.hpp: In constructor ‘cl::Context::Context(cl_device_type, cl_context_properties*, void (*)(const char*, const void*, cl::size_type, void*), void*, cl_int*)’:
include/CL/cl2.hpp:2745:26: warning: catching polymorphic type ‘class cl::Error’ by value [-Wcatch-value=]
                 } catch (Error) {}
                          ^~~~~
```

Since `cl2.hpp` is included by many files, the warning floods the screen. 

**Fix:**

Simply change `cl2.hpp:2745' from
```
    } catch (Error) {}
```
to
```
    } catch (Error&) {}
```
resolve the issus.

I know gcc 8 is not now officially supported by Arm ComputeLibrary, but this should be easy to fix.

**Comment by GeorgeARM** [comment]
Fixed on master. Closing. Reopen if needed.
