### ISSUE TITLE
Crash in clEnqueueNDRangeKernel on Odroid XU-4 with Ubuntu 18.04

### ISSUE THREAD

**Issue by tablyazimov** [ARM-software/ComputeLibrary#587]
**Output of 'strings libarm_compute.so | grep arm_compute_version': arm_compute_version=v18.08 Build options: {'embed_kernels': '1', 'opencl': '1', 'neon': '0', 'build': 'cross_compile', 'debug': '0', 'arch': 'armv7a', 'Werror': '0'} Git hash=unknown**

**Platform: Odroid XU-4**

**Operating System: Ubuntu 18.04**

Problem description:
I have crash every time in configure methods of the CL layers (CLConvolutionLayer for example) if I initialize the TensorInfo for CLTensor objects with the init(const TensorShape &tensor_shape, Format format) method or with the TensorInfo(const TensorShape &tensor_shape, Format format) constructor.

I found workaround to use init_auto_padding(const TensorShape &tensor_shape, Format format) for the initialization, but wondering why the init() does not work.

The crash takes place after the call to the clEnqueueNDRangeKernel() OpenCL function, which returns CL_INVALID_GLOBAL_WORK_SIZE status. I explored this a little bit under debugger and found, the global_work_size parameter of this function receives an array with one dimension set to 0, when I use TensorInfo::init(). When TensorInfo::init_auto_padding() is used that dimension is set to 3 in my example program.

**Comment by AnthonyARM** [comment]
Please provide your test code that highlights the issue

**Comment by giuseros** [comment]
Hi @tablyazimov , 
In addition to test code, it would also be important to know which OpenCL version you are using. 

Thanks,
G.

**Comment by tablyazimov** [comment]
This is the code example which I constructed:

#include "arm_compute/core/Types.h"
#include "arm_compute/runtime/CL/CLFunctions.h"
#include "arm_compute/runtime/CL/CLScheduler.h"

static void initializeTensor(arm_compute::CLTensor& tensor, const arm_compute::TensorShape& ts) {
  arm_compute::TensorInfo ti(ts, arm_compute::Format::F32);
  //arm_compute::TensorInfo ti;// - with the next line also cause crash
  //ti.init(ts, arm_compute::Format::F32);
  //ti.init_auto_padding(ts, arm_compute::Format::F32);// - but with this everything works
  tensor.allocator()->init(ti);
  tensor.allocator()->allocate();
}

static void fillTensor(arm_compute::CLTensor& tensor, float scalar) {
  tensor.map();
  arm_compute::Window window;
  window.use_tensor_dimensions(tensor.info()->tensor_shape());
  arm_compute::Iterator iter(&tensor, window);
  arm_compute::execute_window_loop(window, [&scalar, &iter](const arm_compute::Coordinates&) {
    memcpy(iter.ptr(), &scalar, sizeof(float));
  }, iter);

  tensor.unmap();
}

int main(int argc, char* argv[]) {
  arm_compute::CLScheduler::get().default_init();

  arm_compute::TensorShape in_shape(8, 4, 3);
  arm_compute::CLTensor in;
  initializeTensor(in, in_shape);
  fillTensor(in, 5);

  arm_compute::TensorShape out_shape(4, 2, 3);
  arm_compute::CLTensor out;
  initializeTensor(out, out_shape);

  arm_compute::TensorShape weights_shape(3, 3, 3, 3);
  arm_compute::CLTensor weights;
  initializeTensor(weights, weights_shape);
  fillTensor(weights, 1);

  arm_compute::PadStrideInfo pad_stride_info(2, 2, 1, 1);
  arm_compute::CLConvolutionLayer conv_layer;
  conv_layer.configure(&in, &weights, nullptr, &out, pad_stride_info);// Crash here
  conv_layer.run();
  arm_compute::CLScheduler::get().sync();
  return 0;
}

**Comment by AnthonyARM** [comment]
You need to call `allocate()` after you've configured the function otherwise your tensor is allocated without any padding.
See the documentation: https://arm-software.github.io/ComputeLibrary/v18.08/architecture.xhtml#padding

Also compiling with `debug=1` would probably fire an assert when you try to configure your function.

**Comment by tablyazimov** [comment]
Thank you, AnthonyARM! It seems everything works, when I do allocation after the layer configuration.

**Comment by tablyazimov** [comment]
Dear giuseros,

Unfortunately, I am not quite sure how to obtain the OpenCL library version. The only thing I have found on the device is the location of the library:
/usr/lib/arm-linux-gnueabihf/libOpenCL.so -> /usr/lib/arm-linux-gnueabihf/mali-egl/libmali.so

**Comment by giuseros** [comment]
Hi @tablyazimov ,
I see you resolved, anyway the OpenCL version can be obtained through the `CLKernelLibrary::get_device_version()`  function.

**Comment by tablyazimov** [comment]
Hi @giuseros ,
Thank you very much!
