### ISSUE TITLE
Build error in SnapDragon 410c board

### ISSUE THREAD

**Issue by cloverpop** [ARM-software/ComputeLibrary#588]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

**Platform:**
SnapDragon 410c ( 4 x Cortex-A53), ComputeLibrary 18.08

**Operating System:**
Debian OS

**Problem description:**
Build error with the "scons Werror=1 debug=0 asserts=0 neon=1 opencl=0 examples=1 build=native -j2"
Werror=0 can bypass this error.

src/core/NEON/kernels/NENormalizationLayerKernel.cpp:136:62: required from here
src/core/NEON/kernels/NENormalizationLayerKernel.cpp:198:15: error: variable ‘min_top’ set but not used [-Werror=unused-but-set-variable]
const int min_top = 0;
^~~~~~~
src/core/NEON/kernels/NENormalizationLayerKernel.cpp: In instantiation of ‘void arm_compute::NENormalizationLayerKernel::normalize_float(con
st arm_compute::Window&) [with arm_compute::DataType dt = (arm_compute::DataType)11; unsigned int dim = 2; bool do_2D_norm = false]’:
src/core/NEON/kernels/NENormalizationLayerKernel.cpp:141:58: required from here
src/core/NEON/kernels/NENormalizationLayerKernel.cpp:198:15: error: variable ‘min_top’ set but not used [-Werror=unused-but-set-variable]
cc1plus: all warnings being treated as errors
scons: *** [build/src/core/NEON/kernels/NENormalizationLayerKernel.o] Error 1
scons: building terminated because of errors.

**Comment by GeorgeARM** [comment]
Hello @cloverpop,
This has been resolved and will be fixed in upcoming release.
You can have a look on master [here](https://git.mlplatform.org/ml/ComputeLibrary.git/).
