### ISSUE TITLE
CLBatchToSpaceLayer  doesn't support cropping

### ISSUE THREAD

**Issue by olegarch** [ARM-software/ComputeLibrary#589]
batch to space layer in tensorflow performs cropping step, but ARM CL implementation doesn't have such functionality.
Is the right approach to use CLSlice for cropping after CLBatchToSpace to mimic TF operation?
Does it incurs overhead of multiple copies of data?

**Comment by mpekatsoula** [comment]
Hi @olegarch 

Yes that's correct BatchToSpace does not support cropping. Did you try with CLSlice?

**Comment by olegarch** [comment]
> Hi @olegarch
> 
> Yes that's correct BatchToSpace does not support cropping. Did you try with CLSlice?

Actually we modified BatchToSpace to support cropping. It allows easier parsing for TF models in ARM NN.

**Comment by mpekatsoula** [comment]
Great, if you want you can consider pushing your changes to our development branch:
https://review.mlplatform.org/q/project:ml%252FComputeLibrary

Marking this as solved.
