### ISSUE TITLE
unable to run neon_convolution on raspberrypi-3

### ISSUE THREAD

**Issue by Subarukun** [ARM-software/ComputeLibrary#59]
Hi,

I am unable to run the neon_convolution example on raspberry pi 3. Below are the commands for building the library and application that I have used 

Library:
arm-linux-gnueabihf-g++ -c -fpic -D_GLIBCXX_USE_NANOSLEEP -Wno-deprecated-declarations -Wall -DARCH_ARM -Wextra -Wno-unused-parameter -pedantic -Wdisabled-optimization -Wformat=2 -Winit-self -Wmissing-include-dirs -Wstrict-overflow=2 -Wswitch-default -fpermissive -std=c++11 -Wno-vla -Woverloaded-virtual -Wctor-dtor-privacy -Wsign-promo -Weffc++ -Wno-format-nonliteral -Wno-overlength-strings -Wno-strict-overflow -Wlogical-op -Wnoexcept -Wstrict-null-sentinel -march=armv7-a -Werror -O3 -ftree-vectorize -mfpu=neon-vfpv4 -gdwarf-2 -Ibuild -I. -Iinclude   src/core/NEON/kernels/*.cpp src/runtime/NEON/*.cpp src/runtime/NEON/functions/*.cpp src/core/*.cpp src/core/CPP/*.cpp src/runtime/*.cpp src/core/CPP/kernels/*.cpp src/runtime/CPP/CPPScheduler.cpp
arm-linux-gnueabihf-g++ -shared -o libarm.so *.o -lpthread -lrt

App: 
arm-linux-gnueabihf-g++  -march=armv7-a examples/neon_convolution.cpp test_helpers/Utils.cpp -I. -Iinclude -std=c++11 -L. -larm -o neon_convolution -Wl,-rpath,.

When I run the application I am getting the below error:
"./neon_convolution

Usage: ./build/neon_convolution [input_image.ppm]

No input_image provided, creating a dummy 640x480 image
**Illegal instruction**"

But if I disable the multithreading(NO_MULTI_THREADING) and built the library then its running fine and I am not getting any illegal instruction error . Could you let me know what is the issue.

Thanks.

**Comment by gmiodice** [comment]
Hi @Subarukun,

what OS are you using on the Raspberry Pi 3?

Thanks,
Gian Marco

**Comment by Subarukun** [comment]
Hi gmiodice,

uname -a 
Linux raspberrypi-hY0LTbHYN0 4.4.13-v7+ #894 SMP Mon Jun 13 13:13:27 BST 2016 armv7l GNU/Linux

lsb_release -a
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 8.0 (jessie)
Release:        8.0
Codename:       jessie

Thanks.

**Comment by AnthonyARM** [comment]
Rasbian is compiled for armv6, please use an armv7 OS.
See [this other thread](https://github.com/ARM-software/ComputeLibrary/issues/12#issuecomment-291119511) for more details
