### ISSUE TITLE
Performance when using on BananaPi M2U with R40 CPU is much slower than RPi

### ISSUE THREAD

**Issue by solarprism** [ARM-software/ComputeLibrary#590]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

arm_compute_version=v18.11 Build options: {'arch': 'armv7a', 'opencl': '0', 'neon': '1', 'benchmark_tests': '1', 'build': 'native', 'debug': '0', 'os': 'linux', 'Werror': '1'} Git hash=unknown
**Platform:**

**Operating System:**
Ubuntu 16.04
Linux bpi-iot-ros-ai 3.10.107-BPI-M2U-Kernel #1 SMP Thu Aug 24 08:01:24 CST 2017 armv7l armv7l armv7l GNU/Linux

**Problem description:**
Performance when using on BananaPi M2U with R40 CPU is much slower than RPi
![image](https://user-images.githubusercontent.com/13034858/49274775-5e688980-f4b4-11e8-8231-de556833daa5.png)
Also when i change target to GC, it still NEON
![image](https://user-images.githubusercontent.com/13034858/49274901-b43d3180-f4b4-11e8-870f-9943a844ea52.png)
Can we have anyway to know if it really use NEON or not ?
I saw different debug output from here : https://developer.arm.com/technologies/machine-learning-on-arm/developer-material/how-to-guides/profiling-alexnet-on-raspberry-pi-and-hikey-960-with-the-compute-library/run-the-graph-alexnet-application-on-pi

`[GRAPH][08-02-2018 06:39:53][INFO] Instantiating NESoftmaxLayer Data Type: F32 Input shape: 1000 Output shape: 1000 `

Instead of NESoftmaxLayer, it will be SoftmaxLayer Target: NEON Data Type: F32.
Is this correct output for this example ?
Thank you

**Comment by AnthonyARM** [comment]
Hi,
The AllWinner R40 SoC is based on the Mali 400 GPU which doesn't support GLES Compute (That's probably why it falls back to NEON), on the CPU side it's got a quad Cortex-A7 so if you're comparing the performance to RPi3 (Quad Cortex-A53) then I think it's normal for the performance to be less good.

Regarding whether or not NEON is being used: there is no C++ fallback in the Compute Library therefore it is guaranteed to be using NEON.

**Comment by solarprism** [comment]
Thank you for your reply,
I got it that the performance is normal. I run some other tests by other people before and it showed result better that RPi3 but maybe these tests are not good design.
I saw Mali 400 support OpenGL ES 2.0 but Compute Library require 3.1 right ? I didnot see it in document but guess from opengles-3.1 folder in Git.

**Comment by AnthonyARM** [comment]
That's correct, Compute Shaders were introduced in OpenGLES 3.1

Regarding the performance: it's hard to tell, I don't think we've got any Cortex-A7 based platform in our test farm.
The Cortex-A53 is quite powerful a powerful 64bit CPU, but it might be tricky to program for as it's different from most other recent A class processors.
Also, if you run the 32bit version of the library on A53 I would expect the performance to be much worse than the 64bit one (Because we only have 64bit versions of hand written assembly so it would fallback to the generic path).

**Comment by solarprism** [comment]
![image](https://user-images.githubusercontent.com/13034858/49283114-d1312f00-f4cb-11e8-8b1e-4ea2d2a2f0b3.png)
I tested on another BananaPi, but the first generation M1, with A20 CPU, which show double the BogoMIPS values compared to R40 and result as above.
Thank you for your information, i will close this.
