### ISSUE TITLE
Writing Image based kernels from Buffer based kernels

### ISSUE THREAD

**Issue by ssj4gogeta** [ARM-software/ComputeLibrary#592]
Architecture: arm64-v8a
Operating system: Android 9 Pie
Hello,
If we have a buffer based kernel [like current kernels] & I want to write an image based kernel [which use cl::Image instead of cl::Buffer] based on the same, how would I go about doing that? What are the differences in memory layout & what potential problems I might face? Any pointers are appreciated.
Thanks in Advance.

**Comment by giuseros** [comment]
Hi @ssj4gogeta ,

** If you want to copy the buffer to the image,** 
You can use [clCreateImage](https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/clCreateImage.html), but there are some memory alignment restrictions.
 
- A first restriction is the following:
> A 2D image can be created from a buffer by specifying a buffer object in the image_desc->mem_object passed to clCreateImage for image_desc->image_type = CL_MEM_OBJECT_IMAGE2D. If image_desc->mem_object is created with CL_MEM_USE_HOST_PTR, the host_ptr specified to clCreateBuffer must be aligned to the minimum of the CL_DEVICE_IMAGE_BASE_ADDRESS_ALIGNMENT value for all devices in the context associated with image_desc->mem_object and that support images."

- While a second restriction is about the size of the image (still refer to the link above). 

**If you want to use a cl:Image from scratch**

It might be simpler in terms of restrictions, but quite cumbersome in terms of code rewriting: 
- cl::Buffer is used directly in the interface ICLKernel.h. This means you would need to write a new interface to support cl::Image. 
- All the arg setters for the kernels only support buffers. You would need to write new ones to support images.
- All the window slicing logic should support images and not buffers. 

All in all, it is not a straightforward change. 

I hope this helps,
Giuseppe

**Comment by ssj4gogeta** [comment]
Hello @giuseros,
Got it, thanks.
