### ISSUE TITLE
Feature request: configure the cross compiler to use and not hard code it

### ISSUE THREAD

**Issue by crayroud-nviso** [ARM-software/ComputeLibrary#594]
**Platform:**

ALL

**Operating System:**

ALL

**Problem description:**

This is a feature request: configure the cross compiler to use and not hard code it

The compiler prefix is defined from the target architecture and the OS, but the compiler that we want to use may not be aarch64-linux-gnu-g++ for example.

**Comment by AnthonyARM** [comment]
Yes, fair enough. We'll have a look.
Just to be clear: you want to use the same prefix for all of CC / CXX / LD / AS / AR / RANLIB
https://github.com/ARM-software/ComputeLibrary/blob/master/SConstruct#L203

**Comment by crayroud-nviso** [comment]
Yes exactly, we want to have the same prefix for all.

**Comment by AnthonyARM** [comment]
Patch under review: https://review.mlplatform.org/#/c/ml/ComputeLibrary/+/354/

**Comment by AnthonyARM** [comment]
Patch reviewed & merged
