### ISSUE TITLE
Feature request: add the possibility to set the sysroot path

### ISSUE THREAD

**Issue by crayroud-nviso** [ARM-software/ComputeLibrary#595]
**Pl
atform:**

ALL

**Operating System:**

ALL

**Problem description:**

This is a feature request: add the possibility to set the sysroot path

For some targets we need to set the sysroot --sysroot flag

**Comment by AnthonyARM** [comment]
Can't you do it through `extra_cxx_flags` and `extra_link_flags` ? https://github.com/ARM-software/ComputeLibrary/blob/master/SConstruct#L58

**Comment by crayroud-nviso** [comment]
You are right, sorry
