### ISSUE TITLE
graph_* examples's --help  shows --target={NEON,CL,GC,}, where GC doesn't exist, it is "gles"

### ISSUE THREAD

**Issue by santo4ul** [ARM-software/ComputeLibrary#597]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
```
san@san-Thinkpad-T440S:~/san/ComputeLibrary/build$ strings libarm_compute.so | grep arm_compute_version
arm_compute_version=v18.11 Build options: {'embed_kernels': '1', 'gles_compute': '1', 'arch': 'arm64-v8a', 'opencl': '1', 'neon': '1', 'benchmark_tests': '1', 'validation_tests': '1', 'asserts': '1', 'debug': '0', 'os': 'android', 'Werror': '1'} Git hash=3d2d44ef55ab6b08afda8be48301ce3c55c7bc67

```

**Platform:** RK3399

**Operating System:** Android

**Problem description:** "graph_googlenet --help" command shows --target={NEON,CL,GC,} , where the GC seems to be a typo.

Hi, I was trying to run the graph using GLES and was trying "--target=GC" as per --help information. Based on details provided in #593, it should --target=gles and not --target=GC. This seems to be a typo in the example applications.

This is misleading the user and as a result all --target=GC commands are falling back to NEON.

Thanks,
San

**Comment by GeorgeARM** [comment]
Hello @santo4ul,

Yes you are correct, its confusing. Will fix.

**Comment by GeorgeARM** [comment]
Fixed and patch can be found [here](https://review.mlplatform.org/#/c/ml/ComputeLibrary/+/374/)
