### ISSUE TITLE
Question: CL Vs GLES on a Mali Midgrad T864MP4

### ISSUE THREAD

**Issue by santo4ul** [ARM-software/ComputeLibrary#598]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
```
san@san-Thinkpad-T440S:~/san/ComputeLibrary/build$ strings libarm_compute.so | grep arm_compute_version
arm_compute_version=v18.11 Build options: {'embed_kernels': '1', 'gles_compute': '1', 'arch': 'arm64-v8a', 'opencl': '1', 'neon': '1', 'benchmark_tests': '1', 'validation_tests': '1', 'asserts': '1', 'debug': '0', 'os': 'android', 'Werror': '1'} Git hash=3d2d44ef55ab6b08afda8be48301ce3c55c7bc67

```

**Platform:** RK3399

**Operating System:** Android

**Problem description:** Question: CL Vs GLES on a Mali Midgrad T864MP4

Hi,

We are evaluating CL vs GLES for our graph on a Mali Midgrad (T864MP4) GPU. Our platform supports OpenGL ES 3.2 (which shader compute), that is required for GLES. 

As I understand (I'm no GPU/Graphics expert, btw), the Midgrad GPU architecture uses Shader Cores, which handles both the vertex and the fragment processing. It also includes a Tile based renderiung. 

I'm using DS-5 Streamline (Ultimate Edition), to see which of the GPU cores are being used for CL and GLES. 

To my surprise, the streamline shows same load (or almost simillar) for both CL and GLES.

Streamline output for `./graph_googlenet  --target=CL`
![image](https://user-images.githubusercontent.com/1419919/49629677-aa658200-fa10-11e8-924d-483fe4dad743.png)

Streamline output for `./graph_googlenet  --target=gles --layout=NCHW`
![image](https://user-images.githubusercontent.com/1419919/49629759-18aa4480-fa11-11e8-8f4e-03fd8dbc349e.png)

The GPU activity (in terms of load) in both of the above streamline output is the same. Meaning, the way the GPU is being used is almost the same, with only 'GPU Vertex-Tiling-Compute" activity showing-up for both CL and GLES. However, there could be some difference in performance between CL and GLES. I was expecting something to show up on "GPU Fragment" Activity for GLES. 

**Questions:**
1) Is this the expected behaviour on the GPU activity for both CL and GLES on a Midgrad GPU? 
2) Am I missing any important Streamline Counter that differentiates the load usage of CL vs GLES?
3) The "GPU Fragment" Activity always show 0% usage. Is this the expected behaviour? 

Thanks. Appreciate any pointers, inputs, that helps us in evaluating CL Vs GLES on our platform.

**Comment by santo4ul** [comment]
Could someone throw some light, please? 

@giuseros any thoughts?

Thanks,
San

**Comment by AnthonyARM** [comment]
Hi San,

`GPU Vertex-Tiling-Compute` and `GPU Fragment` are just hardware counter names, they don't actually mean they're run on different cores.

The HW counters only show that the GPU utilisation might be similar between the two APIs.
I would recommend highlighting a range on your counters to see what the average utilisation is, as sometimes it might be very different but isn't visible at the zoomed out level.

Assuming both APIs reach a similar GPU utilisation level, you need then to take into account how optimised the code is: OpenGLES and OpenCL are very different APIs, and it's not always possible to implement all the optimisations in both languages, therefore OpenGLES might reach the same level of hardware utilisation as OpenCL but because its code is less optimised it will take longer to process the whole workload.

Hope this helps,

**Comment by santo4ul** [comment]
Thanks @AnthonyARM for your inputs. 

_`GPU Vertex-Tiling-Compute and GPU Fragment are just hardware counter names, they don't actually mean they're run on different cores.`_
Do you mean that these two  counters are doing the same job? If yes, I'm wondering why gatord is exposing two counters for the same Activity. If not,  could you please let me know the difference between  `GPU Vertex-Tiling-Compute` and `GPU Fragment` counters? When will something show-up on the `GPU Fragment` activity counter?

By zooming-in the streamline output I coud see the difference in actual GPU utilization. 

_`therefore OpenGLES might reach the same level of hardware utilisation as OpenCL but because its code is less optimised it will take longer to process the whole workload.`_
Agree, that makes sense. 

Thanks,
San

**Comment by AnthonyARM** [comment]
I think these counters are only meant to describe the nature of the job currently running on the core.

You can refer to [Mali Midgard Family Performance Counters](https://community.arm.com/graphics/b/blog/posts/mali-midgard-family-performance-counters#jive_content_id_31_Shader_Core_Activity) for more details

**Comment by santo4ul** [comment]
Thanks @AnthonyARM, for your inputs.
