### ISSUE TITLE
How to bypass specific test case in arm_compute_benchmark.

### ISSUE THREAD

**Issue by fcyella** [ARM-software/ComputeLibrary#600]
Hi 
Here is the env I am working with. 

ARM Compute Library, v18.11
Platform, arm64-v8a
Linux OS. 

I got some info form the documents of Compute Library,  and have one question about the benchmark tests. Can I drop one or several cases of benchmark?  
For example,  the filter-id=3644 case failed and the process was killed but I need to know the left cases' result.

**Comment by AnthonyARM** [comment]
Hi,
You can use `filter-id` to specify a range: `--filter-id="3645,..." will run only the tests starting from ID 3645

Hope this helps

**Comment by fcyella** [comment]
Thanks very much
