### ISSUE TITLE
How to build run-time on the arm compute library

### ISSUE THREAD

**Issue by babatn1** [ARM-software/ComputeLibrary#601]
Hi everybody; 
 I want to build arm compute library the run-time part.  Dose anyone show me steps to make it?
Many thanks

**Comment by AnthonyARM** [comment]
Hi @babatn1 

You've got examples of command lines in the documentation [here](https://arm-software.github.io/ComputeLibrary/v18.11/index.xhtml#S3_how_to_build)

Are you trying to build for Linux or Android ?

**Comment by babatn1** [comment]
Hi @AnthonyARM ;
Thank for your help; 
 I trying to build for linux; Did you research or make any project with it?

**Comment by babatn1** [comment]
@AnthonyARM ;
 
how to see the result when i build successful with this command ?
scons Werror=1 -j8 debug=0 asserts=1 neon=0 opencl=1 embed_kernels=1 os=linux arch=arm64-v8a
Thank you so much!

**Comment by giuseros** [comment]
Hello @babatn1 ,
Can't you  run the examples? They are in the example folder of your build directory.

**Comment by babatn1** [comment]
Dear @giuseros ;

When I build successful follow this command 
scons Werror=1 -j8 debug=0 asserts=1 neon=0 opencl=0 gles_compute=1 embed_kernels=1 os=linux arch=arm64-v8a 
It had a folder build  as into the picture
![2](https://user-images.githubusercontent.com/39723389/50086952-8b56b500-01b3-11e9-8d1e-05e9f69c87ca.PNG)
So, Where are the examples? (Because when I clone ComputeLibrary from github.com it is a examples folder as the picture)
![3](https://user-images.githubusercontent.com/39723389/50087286-657de000-01b4-11e9-92e4-9ba537f6aeaf.PNG) 
When I do follow your guide then it is not ok.

**Comment by AnthonyARM** [comment]
Inside the `build` folder you should have an `examples` folder.

**Comment by babatn1** [comment]
Hi @AnthonyARM ; 

Yes. I have the examples folder inside build folder. it has as the picture 
![4](https://user-images.githubusercontent.com/39723389/50088537-2487ca80-01b8-11e9-9345-ad632c6ef6b4.PNG)
So. when I run follow this command  
aarch64-linux-gnu-g++ examples/cl_convolution.cpp utils/Utils.cpp -I. -Iinclude -std=c++11 -L. -larm_compute -larm_compute_core -o cl_convolution -DARM_COMPUTE_CL
It is still errors as the picture
![5](https://user-images.githubusercontent.com/39723389/50088819-f3f46080-01b8-11e9-8f25-ee46b452b185.PNG)

**Comment by AnthonyARM** [comment]
You already have the built examples in your `build` folder, you don't need to re-build them (The section to compile the examples by hand only applies to people who downloaded the pre-built binaries).
You just need to do:
```
cd build
LD_LIBRARY_PATH=. examples/cl_convolution
```

**Comment by babatn1** [comment]
Dear @AnthonyARM  and @giuseros 
Thank for your help

**Comment by GeorgeARM** [comment]
Hello @babatn1,
Usage of onnc is a different topic, thus closing this issue.
