### ISSUE TITLE
int8 gemm is slow

### ISSUE THREAD

**Issue by yeshunping** [ARM-software/ComputeLibrary#602]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v18.11 Build options: {'cppthreads': '0', 'arch': 'arm64-v8a', 'opencl': '0', 'neon': '1', 'examples': '0', 'asserts': '0', 'debug': '0', 'os': 'linux', 'Werror': '1'} Git hash=3d2d44ef55ab6b08afda8be48301ce3c55c7bc67

**Platform:**
arm64 A57

**Operating System:**
linux

**Problem description:**
I found that NEGEMMLowpMatrixMultiplyCore function has some bug, which will cause gemm is slow for int8.

code snippet is like below:
```cpp
// use three tensor for gemm
  arm_compute::Tensor a { }, b { }, c { };

  a.allocator()->init(TensorInfo(TensorShape(k, m), 1, DataType::S8));
  b.allocator()->init(TensorInfo(TensorShape(n, k), 1, DataType::S8));
  c.allocator()->init(TensorInfo(TensorShape(n, m), 1, DataType::S32));

//  import memory from existing buffer.
  a.allocator()->import_memory((void*)xxx, m*k);
  b.allocator()->import_memory((void*)yyy, n*k);
  c.allocator()->import_memory(zzz, m*n);

  arm_compute::NEGEMMLowpMatrixMultiplyCore gemm_core;
  arm_compute::GEMMInfo info(false, false, true);  // _reshape_b_only_on_first_run is true here.
  gemm_core.configure(&a, &b, nullptr, &c, info);
  gemm_core.run();
```

From CPU profiling result, We can see that NEGEMMInterleavedWrapper::run will always call NEGEMMInterleavedPrepareBWrapperKernelTemplate::transform , even is _reshape_b_only_on_first_run is true.

I tried to fix this bug, in function 
NEGEMMAssemblyDispatch::configure
i skiped calling create_function_or_arm_gemm again if _function != nullptr 
using some data for benchmark , performance is much better, but for some other data, program will crash, can someone fix this performance bug ?

**Comment by yeshunping** [comment]
Here B is the model weights, i think InterleavedPrepareBWrapperKernel should apply to it only once, but actually it's called every time gemm_core is called for different a, as a result, performance of gemm is not good enough. NEGEMMInterleavedPrepareBWrapperKernelTemplate::transform use 4X time of kernel function a64_gemm_s8_4x4

**Comment by yeshunping** [comment]
<img width="860" alt="2018-12-13 17 43 07" src="https://user-images.githubusercontent.com/1329442/49929980-a6e56580-fefe-11e8-88a9-af15a7590730.png">

**Comment by AnthonyARM** [comment]
Could you please try again with the development branch ? https://review.mlplatform.org/#/admin/projects/ml/ComputeLibrary

if you call `gemm_core.prepare()` before calling `gemm_core.run()` then B reshaping will happen in the `prepare()`. Anyway, even if you don't call `prepare()` separately, only the first `run()` should be slow so could you please share the code where you call `run()` several times ?

**Comment by yeshunping** [comment]
ok , I will try be development branch.

I am sure that  in function gemm_core.run() , prepare of some kernel will be called again, since in xxx configure function, create_function_or_arm_gemm will be called, so some important object will be created many times even B is the same & _reshape_b_only_on_first_run is true

**Comment by AnthonyARM** [comment]
prepare will be called but there should always be a `_is_prepared` variable that is checked inside the prepare() functions

**Comment by yeshunping** [comment]
Hi , i have tried development branch, but the performance is poor than before.
BM_ApplyAffineTransform                8795253992 ns 8742167920 ns          1
BM_ApplyAffineTransform_Armlib         10836666346 ns 10794933280 ns          1

If i use v18.11 ,  BM_ApplyAffineTransform_Armlib will be about 3-4s, much better than development branch.

**Comment by AnthonyARM** [comment]
Please share your code if you want us to have a look

**Comment by yeshunping** [comment]
Hi Anthony, i will write some single source file for u to reproduce, but it need some time.

for you answer 
```
_is_prepared variable that is checked inside the prepare() functions
```
I have found a bug here
```
void NEGEMMLowpMatrixMultiplyCore::configure(const ITensor *a, const ITensor *b, const ITensor *c, ITensor *output, const GEMMInfo &gemm_info)
{
    ARM_COMPUTE_ERROR_ON_NULLPTR(a, b, output);
    ARM_COMPUTE_UNUSED(c);
    ARM_COMPUTE_ERROR_THROW_ON(NEGEMMLowpMatrixMultiplyCore::validate(a->info(), b->info(), c != nullptr ? c->info() : nullptr, output->info(), gemm_info));

    // Clear state
    _mtx_a_reshape_kernel = nullptr;
    _mtx_b_reshape_kernel = nullptr;

    // Set internal variables
    _a_offset                         = a->info()->quantization_info().offset;
    _b_offset                         = b->info()->quantization_info().offset;
    _run_vector_matrix_multiplication = a->info()->dimension(1) < 2;
    _reshape_b_only_on_first_run      = gemm_info.reshape_b_only_on_first_run();
    _is_prepared                      = false;
```

_is_prepared if reset to be false when  NEGEMMLowpMatrixMultiplyCore::configure is called for new matrix A (matrix B is the same).

**Comment by yeshunping** [comment]
```cpp
#include <time.h>
#include <stdlib.h>
#include <stdio.h>

#include "third_party/arm_compute/arm_compute/graph.h"
#include "third_party/arm_compute/arm_compute/runtime/Tensor.h"
#include "third_party/arm_compute/arm_compute/runtime/NEON/functions/NEGEMMLowpMatrixMultiplyCore.h"

using namespace arm_compute;

int main(int argc, char** argv) {
  arm_compute::Tensor a1 { }, b { }, c1 { };
  size_t M1 = 20;
  size_t K = 3000;
  size_t N = 1000;

  a1.allocator()->init(TensorInfo(TensorShape(K, M1), 1, DataType::S8));
  b.allocator()->init(TensorInfo(TensorShape(N, K), 1, DataType::S8));
  c1.allocator()->init(TensorInfo(TensorShape(N, M1), 1, DataType::S32));

  // Import memory
  uint8_t* dataA1 = new uint8_t[M1*K];
  uint8_t* dataB = new uint8_t[N*K];
  int32_t* dataC1 = new int32_t[N*M1];

  a1.allocator()->import_memory(dataA1, M1*K);
  b.allocator()->import_memory(dataB, N*K);
  c1.allocator()->import_memory(dataC1, N*M1);

  for (int i = 0; i < M1; ++i) {
    for (int j = 0; j < K; ++j) {
      dataA1[i*K+j] = i;
    }
  }

  // Fill random value.
  for (int i = 0; i < K; ++i) {
    for (int j = 0; j < N; ++j) {
      dataB[i*N+j] = M1+i;
    }
  }

  // Call gemm
  arm_compute::NEGEMMLowpMatrixMultiplyCore gemm_core;
  size_t M2 = 30;
  uint8_t* dataA2 = new uint8_t[M2*K];
  int32_t* dataC2 = new int32_t[N*M2];

  for (int i = 0; i < M2; ++i) {
    for (int j = 0; j < K; ++j) {
      dataA2[i*K+j] = i;
    }
  }

  // Call gemm
  for (int i = 0; i < 10000000; ++i) {
    arm_compute::GEMMInfo info1(false, false, true);
    gemm_core.configure(&a1, &b, nullptr, &c1, info1);
    gemm_core.run();

    arm_compute::Tensor a2 { }, c2 { };
    a2.allocator()->init(TensorInfo(TensorShape(K, M2), 1, DataType::S8));
    c2.allocator()->init(TensorInfo(TensorShape(N, M2), 1, DataType::S32));

    a2.allocator()->import_memory(dataA2, M2*K);
    c2.allocator()->import_memory(dataC2, N*M2);

    arm_compute::GEMMInfo info2(false, false, true);
    gemm_core.configure(&a2, &b, nullptr, &c2, info2);
    gemm_core.run();
  }

  return 0;
}
```

I use google CPU profiler , tool link:
https://github.com/gperftools/gperftools

the benchmark result:
[new6.pdf](https://github.com/ARM-software/ComputeLibrary/files/2675959/new6.pdf)

As the CPU profiler show, NEGEMMInterleavedPrepareBWrapperKernelTemplate::transform takes up more than 59% of CPU .

**Comment by yeshunping** [comment]
part of profiler image in png format:

<img width="1027" alt="2018-12-13 20 36 11" src="https://user-images.githubusercontent.com/1329442/49939539-1ae03780-ff18-11e8-9acb-9f7e59dd9c04.png">

**Comment by yeshunping** [comment]
so what should i do if tensor B is model weights, and A is feature input coming streaming (give speech recognition for example). can use give me some code snippets for this case ?

Thanks a lot.

**Comment by AnthonyARM** [comment]
Basically, after you've called `configure()` you cannot change the tensor's dimension anymore, but you can change its content:
```
// use three tensor for gemm
  arm_compute::Tensor a { }, b { }, c { };

  a.allocator()->init(TensorInfo(TensorShape(k, m), 1, DataType::S8));
  b.allocator()->init(TensorInfo(TensorShape(n, k), 1, DataType::S8));
  c.allocator()->init(TensorInfo(TensorShape(n, m), 1, DataType::S32));

//  import memory from existing buffer.
  a.allocator()->import_memory((void*)xxx, m*k);
  b.allocator()->import_memory((void*)yyy, n*k);
  c.allocator()->import_memory(zzz, m*n);

  arm_compute::NEGEMMLowpMatrixMultiplyCore gemm_core;
  arm_compute::GEMMInfo info(false, false, true);  // _reshape_b_only_on_first_run is true here.
  gemm_core.configure(&a, &b, nullptr, &c, info);
  gemm_core.run();
  a.allocator()->import_memory((void*)www, m*k);
  gemm_core.run();
  a.allocator()->import_memory((void*)vvv, m*k);
  gemm_core.run();
```
Or instead of `import_memory` you could just write to the tensor using execute_window_loop as shown in the example: https://arm-software.github.io/ComputeLibrary/v18.11/architecture.xhtml#S4_6_4_working_with_objects

**Comment by AnthonyARM** [comment]
Note: You cannot change the content of `b` though, this only works for `a`

**Comment by yeshunping** [comment]
hi Anthony, thanks very much !
I will try to update a using import_memory then run benchmark program again.

**Comment by yeshunping** [comment]
performance is ok now. 
thanks very much.
