### ISSUE TITLE
Can this library be compiled and used on the x86p platform?

### ISSUE THREAD

**Issue by jianghuxinyi** [ARM-software/ComputeLibrary#604]

**Comment by AnthonyARM** [comment]
Yes, you can compile for `arch=x86_32` or `arch=x86_64` however you must have `opencl=1 neon=0` and the performance is unlikely to be good.

**Comment by jianghuxinyi** [comment]
> 是的，你可以编译`arch=x86_32`或者`arch=x86_64`你必须编译，`opencl=1 neon=0`并且性能不太可能是好的。

thanks
