### ISSUE TITLE
Support for U32 output for NEGEMMLowpAssemblyMatrixMultiplyCore undocumented

### ISSUE THREAD

**Issue by geoffreyblake** [ARM-software/ComputeLibrary#605]
**v18.11**

Documentation for NEGEMMLowpAssemblyMatrixMultiplyCore is incomplete for accepted integer formats for the A, B, and C tensors.  The documentation states that the C tensor must be S32, but the code will also accept U32.  This is currently not documented. 

If the sign of the output mismatches the input tensor signs, experiments have also noticed that performance degrades due to improper selection of optimized kernels.

We have not checked ourselves, but it may be a worthwhile exercise to double check the documentation regarding input/output types supported for the rest of the NEGEMMLowp* family of objects .

**Comment by ManubARM** [comment]
Hi @geoffreyblake ,
thanks for indicating us the problems in the documentation, we are going to fix them for the next release.

About the performance issue we need more information: environment, board, operating system

Thanks,
Manuel

**Comment by mpekatsoula** [comment]
Closing. This should be fixed in the [19.02](https://github.com/ARM-software/ComputeLibrary/releases/tag/v19.02) release.
