### ISSUE TITLE
Is matrix B already reshaped supported now?

### ISSUE THREAD

**Issue by chwma** [ARM-software/ComputeLibrary#609]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v18.11 Build options: {'cppthreads': '0', 'arch': 'arm64-v8a', 'opencl': '0', 'neon': '1', 'examples': '0', 'asserts': '0', 'debug': '0', 'os': 'linux', 'Werror': '1'} Git hash=3d2d44ef55ab6b08afda8be48301ce3c55c7bc67
**Platform:**
arm64 A57
**Operating System:**
linux

**Problem description:**
In function "NEGEMMLowpMatrixMultiplyCore::validate", some code like this: 
ARM_COMPUTE_RETURN_ERROR_ON_MSG(gemm_info.is_b_reshaped(), "Matrix B already reshaped is not supported");

I want to verify if the current version supports reshaped matrix tensor b.
Thank you very much.

For example:
  arm_compute::NEGEMMLowpMatrixMultiplyCore gemm_core;
  arm_compute::GEMMInfo info(false, **true**, true); // here second param is true
  gemm_core.configure(&a, &b, nullptr, &c, info);
  gemm_core.run();

**Comment by AnthonyARM** [comment]
We're not planning on support B already reshaped because the reshaped shape depends on which algorithm is selected and this is out of the user's hands.

**Comment by GeorgeARM** [comment]
Not planning to support already reshaped matrix as it depends on the algorithm heuristics.
Closing for now.
