### ISSUE TITLE
Header files in "support" directory

### ISSUE THREAD

**Issue by yannispapadakis** [ARM-software/ComputeLibrary#613]
**Output of 'strings libarm_compute.so | grep arm_compute_version': v0.0**

**Platform: Nvidia Tegra TX2**

**Operating System: Ubuntu 16.04**

**Problem description:** I am using the interface provided at the arm_compute/runtime/NEON/functions directory. When I install arm-cl at my build directory, I copy the arm_compute directory, but it seems that I need to copy the "support" and "include/half" directories (which are not in "arm_compute" directory) so that my code links correctly. 

The files that are not available in case that these directories are not included at the build directory are Half.h and ToolchainSupport.h included in Types.h and half.hpp included by support/Half.h. 

The goal is to install only the arm_compute directory in my build, without having to copy other directories.

**Comment by GeorgeARM** [comment]
Hello @yannispapadakis,

We could make `support ` part of the `arm_compute/core` folder which makes sense in the end but unfortunately I would argue that we can't do the same for the `include` folder which contains third party libraries.

You could just build ComputeLibrary  and then use the  `-I` and `-L`  linker options to link against it by pointing to the ACL paths.

**Comment by mpekatsoula** [comment]
Marking this as solved
