### ISSUE TITLE
Is it possible to add a new example?

### ISSUE THREAD

**Issue by d-b-h** [ARM-software/ComputeLibrary#615]
I would like to create an example for a new method of convolution. I added it to ComputeLibrary/examples and did a clean build, However, when I try to run the executable on my aarch64 armv8 device, it shows file not found. Is there any other step required to add an example? Or another way to cross-compile a c++ code?

**Comment by GeorgeARM** [comment]
Hello @d-b-h,
can you share the name of your new example?
Maybe you need to explicitly add it in https://github.com/ARM-software/ComputeLibrary/blob/master/examples/SConscript to pick it up.

**Comment by d-b-h** [comment]
I have named it as neon_testTwo.cpp. The executable is present in build/examples, but when i push it to my phone, the result of ./neon_testTwo is "not found"

**Comment by GeorgeARM** [comment]
can you post your build command please?

**Comment by d-b-h** [comment]
scons arch=arm64-v8a neon=1 opencl=1 embed_kernels=1 extra_cxx_flags="-fPIC" -j8 internal_only=0

**Comment by GeorgeARM** [comment]
Hello @d-b-h ,

Can you please provide with the platform that you are running on? Where did you run the neon_convolution examples? This is rather strange

**Comment by d-b-h** [comment]
I am running it on a 64-bit armv8-a processor. (Snapdragon 636).

**Comment by mpekatsoula** [comment]
Let's recap:
You cross compile the examples targeting linux and you copy the examples to your device which runs linux 64bit correct? Do you also copy the libraries to the remote device?
Do you compile the examples using examples=1 in the scons command (this should be the default option)? This should automatically pick any neon_* file in the examples folder
So if you add a new neon_test.cpp and build with scons, the neon_test binary that is generated is not working (not found) but the others are?

**Comment by d-b-h** [comment]
Yes,
**host machine** - x86_64
**target device** - aarch64 armv8-A processor (my android phone)

I have built Compute Library targeting linux. I have copied the libraries and all example executables  onto my device. All run successfully. I have also successfully run MNIST test inference with linux as target.

I have created a neon_test.cpp following a similar structure to neon_convolution.cpp. I have done a clean build with this cpp file in my ComputeLibrary/examples folder. Executable is generated as neon_test in ComputeLibrary/build/examples. When I try running this on my device, it says "no such file".

I tried cross compiling with g++ cross compiler, and obtained the executable in ComputeLibrary/build. The same error occurs. I am using adb shell to run on my phone.

**Comment by mpekatsoula** [comment]
You target linux but you try to run on android, this cannot work. So, when you do a clean build your neon_test is giving you an error but if you copy neon_convolution it executes correctly? Are you sure you copy the correct file?

You need to build for android using **os=android** in your scons command, else this won't work.

**Comment by d-b-h** [comment]
I have copied the correct file. However, one thing to note is that the already present example neon_convolution(result of clean build) runs on my phone. But the error appears when the executable is a result of the g++  cross compile.

**Comment by d-b-h** [comment]
I am not getting how to install the clang android cross compiler. When I put **os=android** it says 

ERROR: Compiler ' aarch64-linux-android-clang++' not found

**Comment by d-b-h** [comment]
Alright! I compiles with for android using the following command:

scons arch=arm64-v8a neon=1 opencl=1 embed_kernels=1 extra_cxx_flags="-fPIC" -j8 internal_only=0 platform=android

The same thing is happening

![error](https://user-images.githubusercontent.com/29578828/51069755-1b750680-165b-11e9-932e-45d61de2ebf2.png)

**Comment by d-b-h** [comment]
I have build the arm-nn sdk, from this repo: https://github.com/ARM-software/armnn/blob/branches/armnn_18_11/BuildGuideCrossCompilation.md, not the NDK.

Why are the other examples running without issue? And what do I do to add the ndk to the PATH? How do I install that compiler? I was not able to find anything.

**Comment by AnthonyARM** [comment]
It's all explained in the documentation: https://arm-software.github.io/ComputeLibrary/v18.11/index.xhtml#S3_3_android
