### ISSUE TITLE
Extracting weights for ACL from tensorflow pre-trained MobilenetV2 SSDlite frozen graph

### ISSUE THREAD

**Issue by krgor** [ARM-software/ComputeLibrary#617]
Hi,

ACL version: v 18.11
Platform: Android-7.1

Currently I am trying to implement the Mobilenet V2 SSDlite detection model on ACL 18.11. I am using graph APIs to create a graph.

I am using the frozen graph from tensorflow from [here](http://download.tensorflow.org/models/object_detection/ssdlite_mobilenet_v2_coco_2018_05_09.tar.gz). 
I modified the tensorflow_data_extractor.py provided in ACL to extract the weights from the frozen graph.

The modified script is attached.
[tensorflow_data_extractor_ssdlite.py.zip](https://github.com/ARM-software/ComputeLibrary/files/2751860/tensorflow_data_extractor_ssdlite.py.zip)

However the graph's output doesn't seem to be expected and seems to be having issue with weight extrating.

Let me know if you need more details on the problem.

Can you please review the script and help me to extract the weights correctly from the tensorflow frozen model?

Thanks,
KGor

**Comment by ManubARM** [comment]
Could you try with our script in the development repo?
git clone https://review.mlplatform.org/ml/ComputeLibrary

The script is called in the directory `scripts` and you can call it in this way:
`python tf_frozen_model_extractor.py -m ssdlite_mobilenet_v2_coco_2018_05_09/frozen_inference_graph.pb -d output`

I am assuming the directory `ssdlite_mobilenet_v2_coco_2018_05_09` is in scripts too.

Thanks,
Manuel

**Comment by krgor** [comment]
@ManubARM 
Thanks a lot for sharing the script. It's working :). I am closing the ticket.
Regards,
KGor
