### ISSUE TITLE
Build fail with 'TypeError : cannot use a string pattern on a bytes-like object'

### ISSUE THREAD

**Issue by ggardet** [ARM-software/ComputeLibrary#619]
**Platform:** any (aarch64, armv7, x86_64)

**Operating System:** openSUSE

**Problem description:**
While trying to build with openCL, on openSUSE Tumbleweed (rolling release) or Leap 15.0+ (stables), I get:
```
[   50s] scons: *** [build/src/core/CL/cl_kernels/absdiff.clembed] TypeError : cannot use a string pattern on a bytes-like object
```
Previous openSUSE Leap versions are fine.

**Comment by AnthonyARM** [comment]
What compiler version are you using ? Could you try one of the ones that have been tested ?

https://arm-software.github.io/ComputeLibrary/v18.11/index.xhtml#S3_2_linux

**Comment by ggardet** [comment]
> What compiler version are you using ?

It breaks with GCC8/scons 3.0.2 and GCC7/scons 7.0.1.

**Comment by ggardet** [comment]
This is Python 3.6.5. 
I should have included the full backtrace, sorry. Here it is:
```
[   50s] scons: *** [build/src/core/CL/cl_kernels/absdiff.clembed] TypeError : cannot use a string pattern on a bytes-like object
[   50s] Traceback (most recent call last):
[   50s]   File "/usr/lib/python3.6/site-packages/SCons/Action.py", line 1202, in execute
[   50s]     result = self.execfunction(target=target, source=rsources, env=env)
[   50s]   File "/home/abuild/rpmbuild/BUILD/ComputeLibrary-18.11/SConscript", line 89, in resolve_includes
[   50s]     found = pattern.search(line)
[   50s] TypeError: cannot use a string pattern on a bytes-like object
[   51s] scons: building terminated because of errors.
```

**Comment by AnthonyARM** [comment]
We'll have a look, in the meantime can you try to force SCons to use python2 ? (By editing /usr/bin/scons by example and changing the first line to /usr/bin/python2)

**Comment by ManubARM** [comment]
Hi @ggardet, have you solved the problem?

**Comment by tenspd137** [comment]
Hi - I have the exact same issue.  Anyone figured this out?

**Comment by tenspd137** [comment]
If you try to force python2 the error becomes:

scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: `arm_compute' is up to date.
scons: `support' is up to date.
scons: *** [opencl-1.2-stubs/opencl_stubs.c] ValueError : unsupported pickle protocol: 4
scons: building terminated because of errors.

**Comment by tenspd137** [comment]
Basically what appears to be happening is that byte objects are being used all over the place instead of strings.  For example, if you go to line 89 and change it to:
found =	pattern.search(line.decode("utf-8"))

it will move on, but you will get a similar error on line 114.

I don't really understand scons all that much, but why is it reading the files into the python interpreter to build them?  Are they being manipulated on the fly?

**Comment by ManubARM** [comment]
Could you provide the exact scons command? 
Then also output of the following commands
`scons --version`
`gcc --version`
`g++ --version`
`uname -a`

Best,
Manuel

**Comment by tenspd137** [comment]
rockpro64 ~ # gcc --version
gcc (Gentoo 8.2.0-r6 p1.7) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

rockpro64 ~ # g++ --version
g++ (Gentoo 8.2.0-r6 p1.7) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

rockpro64 ~ # uname -a
Linux rockpro64 4.20.0-rc6-106496-g6b3dd2a83c96-dirty #3 SMP PREEMPT Mon Jan 21 15:49:16 MST 2019 aarch64 GNU/Linux

**Comment by ManubARM** [comment]
I am guessing you are compiling on the board. Have you tried cross-compiling on local machine and then upload the files on the board?

Thanks,
Manuel

**Comment by tenspd137** [comment]
No - I'll give that a try as soon as I get a chance.

**Comment by ManubARM** [comment]
Yes we have a reference environment and it is the one we use, you can find everything here:
https://arm-software.github.io/ComputeLibrary/v18.11/index.xhtml

We usually crosscompile and upload the files on a board. Step by step:
```
$ scons --version
SCons by Steven Knight et al.:
	script: v2.4.1.rel_2.4.1:3453:73fefd3ea0b0, 2015/11/09 03:25:05, by bdba
```

This is the scons command we use:
```
os=linux arch=arm64-v8a Werror=1 mode=release neon=1 opencl=1 examples=1 validation_tests=1 benchmark_tests=1 -j32`
```
Which uses the following compiler: aarch64-linux-gnu-g++ . So:
```
$ aarch64-linux-gnu-g++ --version
aarch64-linux-gnu-g++ (Linaro GCC 6.3-2017.05) 6.3.1 20170404
```
Also you might not want to change your environment python and scons version, in this sense you can setup a virtual machine with this OS:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
```

Let us know if you keep having problems
Thanks

**Comment by peteryang1** [comment]
Hi, @ggardet  @AnthonyARM @tenspd137 @ManubARM 
I faced the same problem, I'm building the library on windows, I changed the CXX and C compiler to 
```Python
env['CC'] = "~/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe"
env['CXX'] = "~/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe"
```
then I faced the error 
```Python
Traceback (most recent call last):
  File "d:\software\anaconda\envs\onnx\lib\site-packages\scons\SCons\Action.py", line 1202, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "D:\code\armnn-devenv\ComputeLibrary\SConscript", line 89, in resolve_includes
    found = pattern.search(line)
TypeError: cannot use a string pattern on a bytes-like object
```
then I changed to python2.7, I got
```Python
File "D:\software\anaconda\envs\python2\Scripts\scons", line 204, in <module>
scons: Building targets ...
scons: `arm_compute' is up to date.
scons: `support' is up to date.
scons: *** [opencl-1.2-stubs\opencl_stubs.c] ValueError : unsupported pickle protocol: 4
scons: building terminated because of errors.
```
Is it possible to build library on windows?

**Comment by AnthonyARM** [comment]
```
scons: *** [opencl-1.2-stubs\opencl_stubs.c] ValueError : unsupported pickle protocol: 4
```
This is likely due to some residual Python 3 files, make sure your folder is clean from any `pyc` files, etc.

We don't support building natively on Windows but it should be pretty straight forward using [Bash on Windows](https://arm-software.github.io/ComputeLibrary/v19.02/index.xhtml#S3_5_windows_host) or a Virtual Machine.

**Comment by AnthonyARM** [comment]
Regarding
```
TypeError: cannot use a string pattern on a bytes-like object
```
Could you try this patch and let us know if it fixes the issue:
```
diff --git a/SConscript b/SConscript
index e57dd2390..9b5653d97 100644
--- a/SConscript
+++ b/SConscript
@@ -70,7 +70,7 @@ def resolve_includes(target, source, env):
for i in range(len(source)):
src = source[i]
dst = target[i]
- contents = src.get_contents().splitlines()
+ contents = src.get_contents().decode('utf-8').splitlines()
entry = FileEntry(target_name=dst, file_contents=contents)
files.append((os.path.basename(src.get_path()),entry))
```

**Comment by peteryang1** [comment]
Thanks @AnthonyARM for your help.

I'm building ArmNN on windows using the clang in windows ndk, there's some problem in linking the armnn to armcompute reference. So I want to build the library using clang.exe in windows ndk.

I cleared the cache and used python2 to build the library, after builded some sources, I got an error below:
```CMAKE
scons: *** [build\opencl-1.2-stubs\opencl_stubs.os] The system cannot find the file specified
scons: *** [build\src\core\AccessWindowAutoPadding.o] The system cannot find the file specified
scons: *** [build\src\core\AccessWindowStatic.o] The system cannot find the file specified
scons: *** [build\src\core\AccessWindowTranspose.o] The system cannot find the file specified
scons: *** [build\src\core\Error.o] The system cannot find the file specified
scons: *** [build\src\core\GPUTarget.o] The system cannot find the file specified
scons: *** [build\src\core\HOGInfo.o] The system cannot find the file specified
scons: *** [build\src\core\Helpers.o] The system cannot find the file specified
scons: *** [build\src\core\IAccessWindow.o] The system cannot find the file specified
scons: *** [build\src\core\IDistribution.o] The system cannot find the file specified
scons: *** [build\src\core\IDistribution1D.o] The system cannot find the file specified
scons: *** [build\src\core\IKernel.o] The system cannot find the file specified
scons: *** [build\src\core\ITensor.o] The system cannot find the file specified
scons: *** [build\src\core\MultiImageInfo.o] The system cannot find the file specified
scons: *** [build\src\core\PyramidInfo.o] The system cannot find the file specified
scons: building terminated because of errors.
```
Is there a chance I link the armnn in windows to the compute library?

**Comment by blueardour** [comment]
it seems to the be encode/decode issue. I sovled the problem by take python2 rather than python3。 Explicitly decode the string might also work. 

import chardet 
encode_type = chardet.detect(html)  
html = html.decode(encode_type['encoding'])

**Comment by ggardet** [comment]
> Regarding
> 
> ```
> TypeError: cannot use a string pattern on a bytes-like object
> ```
> Could you try this patch and let us know if it fixes the issue:
> 
> ```diff
> diff --git a/SConscript b/SConscript
> index e57dd2390..9b5653d97 100644
> --- a/SConscript
> +++ b/SConscript
> @@ -70,7 +70,7 @@ def resolve_includes(target, source, env):
> for i in range(len(source)):
> src = source[i]
> dst = target[i]
> - contents = src.get_contents().splitlines()
> + contents = src.get_contents().decode('utf-8').splitlines()
> entry = FileEntry(target_name=dst, file_contents=contents)
> files.append((os.path.basename(src.get_path()),entry))
> ```

It does fix the problem! Thanks. 
@AnthonyARM Do you want I do a PR or will you take care of it?

**Comment by AnthonyARM** [comment]
Thanks @ggardet but Michalis picked it up already: it should be merged shortly https://review.mlplatform.org/#/c/ml/ComputeLibrary/+/978/

**Comment by morgolock** [comment]
Closing. The patch has been merged to main branch and will be included in the next release.
