### ISSUE TITLE
Documentation error "XML Parsing Error: not well-formed"

### ISSUE THREAD

**Issue by Wheest** [ARM-software/ComputeLibrary#624]
When navigating the latest version of the docs, I am encountering an error page, with the main error being "XML Parsing Error: not well-formed", specifically when trying to access the page related to `PoolingType`.  

This error is reproduced when I search for `PoolingType` in the Doxygen search bar and select the link to the `PoolingType` page, or if I select a link to the PoolingType page from other pages, such as on [PoolingLayerInfo Class Reference](https://arm-software.github.io/ComputeLibrary/latest/classarm__compute_1_1_pooling_layer_info.xhtml).

Alas I'm not yet familiar enough with Doxygen to diagnose the problem and put in a PR.  Issue reproduces on other version of the docs, >=v18.02.  Have not tried with locally generated docs, just those available on `arm-software.github.io`

**Comment by ManubARM** [comment]
Thanks for creating the issue. We verified the problem also for other datatype and we are now investigating it and we will be back as soon as we solve it.
In the meantime, please look directly into the code

Thanks,
Manuel

**Comment by ManubARM** [comment]
Update 1: The problem seems to be on Firefox, Chrome correctly visualize the page

**Comment by Wheest** [comment]
Can confirm that Chromium, and Konqueror also correctly visualise the page

**Comment by mpekatsoula** [comment]
Closing. This should be fixed in the [19.02](https://github.com/ARM-software/ComputeLibrary/releases/tag/v19.02) release.
