### ISSUE TITLE
run arm_compute_benchmark

### ISSUE THREAD

**Issue by peter197321** [ARM-software/ComputeLibrary#626]
By running ./arm_compute_benchmark

```
~/ComputeLibrary/build/tests# ./arm_compute_benchmark
./arm_compute_benchmark: error while loading shared libraries: libarm_compute_graph.so: cannot open shared object file: No such file or directory

```

how to correctly call it?

**Comment by mpekatsoula** [comment]
Hi @peter197321 

What is your build command?

From a first look it seems like you don't have the shared libraries in your LD_LIBRARY_PATH

**Comment by giuseros** [comment]
Did you exported LD_LIBRARY_PATH?

It should be on the line of:
$ export LD_LIBRARY_PATH = /path/to/libarm_compute_graph.so

Also, make sure you are building for the correct architecture.

**Comment by peter197321** [comment]
I just got exported 

`LD_LIBRARY_PATH=/home/root/ComputeLibrary/build/ ./tests/arm_compute_benchmark
`
works now. 

What's meant "building for correct architecture"?

**Comment by mpekatsoula** [comment]
When you build, you can specify the target architecture i.e armv7a or arm64-v8a depending on your target. 

Marking this as solved

**Comment by peter197321** [comment]
i got it. thanks
