### ISSUE TITLE
Non uniform workgroup size is not supported!!

### ISSUE THREAD

**Issue by peter197321** [ARM-software/ComputeLibrary#627]
By running benchmark  I got

```
Running [0] 'CL/AlexNetActivationLayer@Shape=55x55x96:Info=RELU:DataType=F16:Batches=1'
ERROR: in create_kernel src/core/CL/CLKernelLibrary.cpp:936: Non uniform workgroup size is not supported!!
```
How to fix it?

**Comment by AnthonyARM** [comment]
You need either an OpenCL 1.2 driver with the non uniform workgroup size extension or an OpenCL 2.0 driver (This extension is part of the core spec for 2.0)
Hope this helps
