### ISSUE TITLE
Failed to get display: 0x3000

### ISSUE THREAD

**Issue by peter197321** [ARM-software/ComputeLibrary#628]
Hello,

I encounter this problem, is there a way to work-around this?
I understand I do not have ARM Mali GPU but can be ACL accomadted to non-ARM GPU? 

Thanks.

```
~/ComputeLibrary/build# LD_LIBRARY_PATH=/home/root/ComputeLibrary/build/ ./tests/arm_compute_benchmark
 [CORE][09-02-2019 11:23:05][INFO]  Can't find valid Mali GPU. Target is set to default.
EGL: Warning: No default display support on wayland
terminate called after throwing an instance of 'std::runtime_error'
  what():  in setup_context src/runtime/GLES_COMPUTE/GCScheduler.cpp:88: Failed to get display: 0x3000.
Aborted (core dumped)

```

**Comment by AnthonyARM** [comment]
Hi,

ACL should work on any implementation supporting OpenGLES Compute Shaders.
Looks like in your case your driver doesn't support `EGL_DEFAULT_DISPLAY` so you might need to change this part of the code set up to make it create a display that your implementation understands: https://github.com/ARM-software/ComputeLibrary/blob/master/src/runtime/GLES_COMPUTE/GCScheduler.cpp#L86

Hope this helps
