### ISSUE TITLE
No NEON instructions appear in disassembly

### ISSUE THREAD

**Issue by mablem8** [ARM-software/ComputeLibrary#631]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
* arm_compute_version=v18.11
* Build options:
  * embed_kernels: 0
  * install_dir: $HOME/sw/ComputeLibrary-aarch64/install
  * gles_compute: 0
  * arch: arm64-v8a
  * opencl: 1
  * neon: 1
  * build_dir: $HOME/sw/ComputeLibrary-aarch64/build
  * benchmark_tests: 1
  * validation_tests: 1
  * build: cross_compile
  * asserts: 0
  * debug: 0
  * openmp: 0
  * extra_cxx_flags: '-std=c++14 -fPIC -march=armv8-a+fp+simd -mtune=cortex-a53 -mcpu=cortex-a53+fp+simd'
  * os: linux
  * cppthreads: 1

**Platform:** Cross-compiling on x86_64 for Cortex-A53 

**Operating System:** Cross-compiling on Ubuntu 18.04 for PetaLinux

**Problem description:** Clarify the meaning of NEON support. The disassembly of the `libarm_compute*.so` libraries does not include any NEON instructions. Vector registers are used, e.g. `fmla v8.4s, v7.4s, v0.4s`, but no NEON instructions appear (e.g. `vadd`, `vmul`). The source files make reference to NEON instructions, but no assembly using these instructions is present. Disassembly generated using e.g. `aarch64-linux-gnu-objdump -dR libarm_compute_core.so > libarm_compute_core.txt`. Should NEON instructions be present?

**Comment by AnthonyARM** [comment]
That's because NEON instructions for `arm64-v8a` are not prefixed with `v` anymore: http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.den0024a/ch07s03.html

**Comment by mablem8** [comment]
Great! In that case they are present, e.g. `grep -iP "add\tv" libarm_compute_core.txt`.
