### ISSUE TITLE
unable to run sdot instruction on 845 and apple A12

### ISSUE THREAD

**Issue by xyoungli** [ARM-software/ComputeLibrary#638]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

**Platform:**
qualcomm 845
**Operating System:**
android 8.1.0

**Problem description:**
i built the int8 gemm kernel in a55r1.cpp,  but when running on android(adb shell), i got "illegal instruction";
then i checked the system register ID_AA64ISAR0_EL1 by "MRS %[id], ID_AA64ISAR0_EL1", and still get "illegal insruction".

**Comment by AnthonyARM** [comment]
What makes you think that the HW supports it ?
I can't find any information regarding these CPUs which suggests they do.

**Comment by xyoungli** [comment]
i thought A75 has enable this feature, thanks
