### ISSUE TITLE
OpenCL linking fails on x86_64 with 19.02

### ISSUE THREAD

**Issue by andrew-wja** [ARM-software/ComputeLibrary#642]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

arm_compute_version=v19.02 Build options: {'embed_kernels': '1', 'gles_compute': '0', 'pmu': '0', 'os': 'linux', 'opencl': '1', 'neon': '0', 'set_soname': '0', 'benchmark_tests': '0', 'validation_tests': '0', 'mali': '0', 'build': 'native', 'asserts': '0', 'cppthreads': '1', 'debug': '0', 'openmp': '0', 'extra_cxx_flags': '-fPIC', 'arch': 'x86_64', 'Werror': '0', 'examples': '0'} Git hash=514be65ad8d3340f53fd9591035352ed285811ba

**Platform:**

OpenCL w/ Intel OpenCL SDK

**Operating System:**

GNU/Linux x86_64

**Problem description:**

When linking an application that uses the CLConvolutionLayer, the linking fails with some methods not found. The link line, and output, follows.

`g++ test.cpp -fPIC -DARM_COMPUTE_CL -I /usr/include/arm_compute/ -lOpenCL -ldl -Wl,--allow-shlib-undefined /usr/lib/arm_compute/CL*.o -l:libarm_compute-static.a -l:libarm_compute_core-static.a -o test`

The error message is

`
<artificial>:(.text+0x7dbe): undefined reference to 'arm_compute::CLDirectConvolutionLayer::CLDirectConvolutionLayer()'
/usr/bin/ld: <artificial>:(.text+0x7e79): undefined reference to 'arm_compute::CLConvolutionLayer::configure(arm_compute::ICLTensor*, arm_compute::ICLTensor const*, arm_compute::ICLTensor const*, arm_compute::ICLTensor*, arm_compute::PadStrideInfo const&, arm_compute::WeightsInfo const&, arm_compute::Size2D const&, arm_compute::ActivationLayerInfo const&, bool, unsigned int)'
`

I get exactly one of these errors for each CLConvolutionLayer that I try to instantiate. Clearly, I am missing something in the linking step, but I cannot find any docs on how to link with OpenCL on x86 beyond looking in the SConstruct files in the examples.

Any pointers would be much appreciated!

**Comment by andrew-wja** [comment]
I have found that if I change from static linking of the `arm_compute` and `arm_compute_core` objects to dynamic linking, it seems to work! So it looks like these methods are missing in the static objects, but not the shared objects. The following link line works for me:

`g++ test.cpp -fPIC -DARM_COMPUTE_CL -I /usr/include/arm_compute/ -lOpenCL -ldl -Wl,--allow-shlib-undefined /usr/lib/arm_compute/CL*.o -l:libarm_compute.so -l:libarm_compute_core.so -o test`

**Comment by AnthonyARM** [comment]
Your original command line looks wrong:
- why do you have `/usr/lib/arm_compute/CL*.o` ?
- `-l:libarm_compute-static.a -l:libarm_compute_core-static.a` looks wrong too

All you need should be:
```
g++ test.cpp -fPIC -DARM_COMPUTE_CL -I /usr/include/arm_compute/ -lOpenCL -ldl -Wl,--allow-shlib-undefined -larm_compute-static -larm_compute_core-static -o test
```

**Comment by andrew-wja** [comment]
Hi Anthony,

I agree that it looks incorrect to manually link the CL shared objects, but if I remove the `/usr/lib/arm_compute/CL*.o' I get thousands of linker errors from the CL methods not being found:

`
<artificial>:(.text+0x6e06): undefined reference to 'arm_compute::CLTensor::map(bool)'
/usr/bin/ld: <artificial>:(.text+0x6e0e): undefined reference to 'arm_compute::ICLTensor::buffer() const'
/usr/bin/ld: <artificial>:(.text+0x6ea3): undefined reference to 'arm_compute::CLTensor::unmap()'
/usr/bin/ld: <artificial>:(.text+0x6ea8): undefined reference to 'arm_compute::CLScheduler::get()'
/usr/bin/ld: <artificial>:(.text+0x6ecd): undefined reference to 'arm_compute::CLScheduler::get()'
/usr/bin/ld: <artificial>:(.text+0x6ef4): undefined reference to 'arm_compute::CLTensor::map(bool)'
/usr/bin/ld: <artificial>:(.text+0x6f00): undefined reference to 'arm_compute::ICLTensor::buffer() const'
/usr/bin/ld: <artificial>:(.text+0x6f18): undefined reference to 'arm_compute::CLTensor::unmap()'
/usr/bin/ld: <artificial>:(.text+0x6f1d): undefined reference to 'arm_compute::CLScheduler::get()'
`

`-l:file` is the LD explicit link syntax. It's a way of making sure that there isn't some failure in the object resolution. It tells LD to look on the linker path for files named exactly as specified, rather than using the usual rules (so e.g. -l:libtest.so is equivalent to -ltest)

**Comment by AnthonyARM** [comment]
Could you please share your test.cpp ? This still looks wrong.

**Comment by AnthonyARM** [comment]
If I cut down the code of `examples/cl_convolution.cpp`
```cpp
#include "arm_compute/core/Types.h"
#include "arm_compute/runtime/CL/CLFunctions.h"
#include "arm_compute/runtime/CL/CLScheduler.h"

using namespace arm_compute;

/** Gaussian 3x3 matrix
 */
const int16_t gaussian3x3[] =
{
    1, 2, 1,
    2, 4, 2,
    1, 2, 1
};

/** Gaussian 5x5 matrix
 */
const int16_t gaussian5x5[] =
{
    1, 4, 6, 4, 1,
    4, 16, 24, 16, 4,
    6, 24, 36, 24, 6,
    4, 16, 24, 16, 4,
    1, 4, 6, 4, 1
};

int main(int argc, char **argv)
{
    CLScheduler::get().default_init();
    CLImage          src{}, tmp{}, dst{};
    CLConvolution3x3 conv3x3{};
    CLConvolution5x5 conv5x5{};

    src.allocator()->init(TensorInfo(640, 480, Format::U8));

    // Configure the temporary and destination images
    tmp.allocator()->init(*src.info());
    dst.allocator()->init(*src.info());

    // Apply a Gaussian 3x3 filter to the source image followed by a Gaussian 5x5:
    conv3x3.configure(&src, &tmp, gaussian3x3, 0 /* Let arm_compute calculate the scale */, BorderMode::UNDEFINED);
    conv5x5.configure(&tmp, &dst, gaussian5x5, 0 /* Let arm_compute calculate the scale */, BorderMode::UNDEFINED);

    // Allocate all the images
    src.allocator()->allocate();
    tmp.allocator()->allocate();
    dst.allocator()->allocate();

    // Execute the functions:
    conv3x3.run();
    conv5x5.run();

    // Make sure all the OpenCL jobs are done executing:
    CLScheduler::get().sync();
}
```
The library needs to be compiled with `-fPIC`:
```diff
diff --git a/SConstruct b/SConstruct
index 7d396fabc..8337724bc 100644
--- a/SConstruct
+++ b/SConstruct
@@ -201,9 +201,11 @@ elif 'arm64-v8.2-a' in env['arch']:
     if 'clang++' in cpp_compiler:
         env.Append(CXXFLAGS = ['-no-integrated-as'])
 elif env['arch'] == 'x86_32':
+    env.Append(CXXFLAGS = ['-fPIC'])
     env.Append(CCFLAGS = ['-m32'])
     env.Append(LINKFLAGS = ['-m32'])
 elif env['arch'] == 'x86_64':
+    env.Append(CXXFLAGS = ['-fPIC'])
     env.Append(CCFLAGS = ['-m64'])
     env.Append(LINKFLAGS = ['-m64'])
 ```

Then I can statically link the example:
```
g++ convolution.cpp -o convolution -I. -Iinclude -Lbuild/linux-x86_64-cl/out/lib/ -larm_compute-static -larm_compute_core-static -fPIC -ldl
```

**Comment by andrew-wja** [comment]
Github doesn't support attaching .cpp files so here is the source of my test.cpp

`#include <cstddef>
#include <vector>
#include <numeric>
#include <iostream>
#include <chrono>

#include "arm_compute/core/Types.h"
#include "arm_compute/runtime/Tensor.h"

#include "arm_compute/runtime/CL/CLFunctions.h"
#include "arm_compute/runtime/CL/CLScheduler.h"

int main(int argc, char **argv) {

  constexpr unsigned ofms = 100;
  constexpr unsigned ifms = 3;
  constexpr unsigned ifm_h = 224;
  constexpr unsigned ifm_w = 224;
  constexpr unsigned stride_h = 1;
  constexpr unsigned stride_w = 1;
  constexpr unsigned ofm_h = 224;
  constexpr unsigned ofm_w = 224;
  constexpr unsigned k = 3;

  float *input_cpu = new float[ifms * ifm_h * ifm_w]();
  float *kernel_cpu = new float[ofms * ifms * k * k]();
  float *output_cpu = new float[ofms * ifm_h * ifm_w]();

  arm_compute::CLScheduler::get().default_init();

  arm_compute::CLTensor armcl_input;
  arm_compute::CLTensor armcl_kernel;
  arm_compute::CLTensor armcl_output;

  armcl_input.allocator()->init(arm_compute::TensorInfo(arm_compute::TensorShape(ifm_w, ifm_h, ifms), 1, arm_compute::DataType::F32));
  armcl_kernel.allocator()->init(arm_compute::TensorInfo(arm_compute::TensorShape(k, k, ifms, ofms), 1, arm_compute::DataType::F32));
  armcl_output.allocator()->init(arm_compute::TensorInfo(arm_compute::TensorShape(ofm_w, ofm_h, ofms), 1, arm_compute::DataType::F32));

  armcl_input.allocator()->allocate();
  //armcl_input.allocator()->import_memory(((void*) (input_cpu)), (ifms * ifm_h * ifm_w));
  armcl_kernel.allocator()->allocate();
  //armcl_kernel.allocator()->import_memory(((void*) (kernel_cpu)), (ofms * ifms * k * k));
  armcl_output.allocator()->allocate();
  //armcl_output.allocator()->import_memory(((void*) (output_cpu)), (ofms * ofm_h * ofm_w));

  arm_compute::IFunction *conv = new arm_compute::CLDirectConvolutionLayer;

  reinterpret_cast<arm_compute::CLConvolutionLayer*>(conv)->configure(&armcl_input, &armcl_kernel, nullptr, &armcl_output, arm_compute::PadStrideInfo((signed) stride_w, (signed) stride_h, (signed) k/2, (signed) k/2));

  //~ constexpr unsigned split_dimension = 0;
  //~ arm_compute::CLScheduler::get().schedule(reinterpret_cast<arm_compute::ICLKernel*>(conv), split_dimension);

  armcl_input.map(true);
  std::copy_n(input_cpu, ifms * ifm_h * ifm_w, armcl_input.buffer());
  armcl_input.unmap();
  arm_compute::CLScheduler::get().sync();

  armcl_kernel.map(true);
  std::copy_n(kernel_cpu, ofms * ifms * k * k, armcl_kernel.buffer());
  armcl_kernel.unmap();
  arm_compute::CLScheduler::get().sync();

  auto t1 = std::chrono::high_resolution_clock::now();

  conv->run();
  arm_compute::CLScheduler::get().sync();

  auto t2 = std::chrono::high_resolution_clock::now();

  auto millis = std::chrono::duration_cast<std::chrono::milliseconds>(t2-t1).count();

  armcl_output.map(true);
  std::copy_n(armcl_output.buffer(), ofms * ofm_h * ofm_w, output_cpu);
  armcl_output.unmap();
  arm_compute::CLScheduler::get().sync();

  armcl_input.allocator()->free();
  armcl_kernel.allocator()->free();
  armcl_output.allocator()->free();

  std::cout << "Convolution took " << millis << "ms " << std::endl;

  return 0;

}
`

**Comment by AnthonyARM** [comment]
Have you tried what I said in my last comment?

**Comment by andrew-wja** [comment]
Hi Anthony,

Apologies, I forgot to update the issue after trying out your suggestion. The linker errors are gone now, but no matter what platform I try to execute the test program on, I get this error message:


```
terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1
Aborted (core dumped)
```

This happens on an Intel Xeon CPU with the Intel OpenCL SDK, and on a Radeon GPU with the AMD OpenCL driver installed (see below the output of clinfo). I can run other OpenCL code, such as the demos that ship with mesa, just fine.

```
$ clinfo  -a
Number of platforms                               1
  Platform Name                                   Clover
  Platform Vendor                                 Mesa
  Platform Version                                OpenCL 1.1 Mesa 18.3.4
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             MESA

  Platform Name                                   Clover
Number of devices                                 2
  Device Name                                     Radeon RX 580 Series (POLARIS10, DRM 3.27.0, 5.0.0-arch1-1-ARCH, LLVM 7.0.1)
  Device Vendor                                   AMD
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.1 Mesa 18.3.4
  Driver Version                                  18.3.4
  Device OpenCL C Version                         OpenCL C 1.1 
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               36
  Max clock frequency                             1411MHz
  Device Partition                                (n/a)
    Max number of sub-devices                     0
    Supported partition types                     None
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             256x256x256
  Max work group size                             256
  Preferred work group size multiple              64
  Preferred / native vector sizes                 
    char                                                16 / 16      
    short                                                8 / 8       
    int                                                  4 / 4       
    long                                                 2 / 2       
    half                                                 8 / 8        (cl_khr_fp16)
    float                                                4 / 4       
    double                                               2 / 2        (cl_khr_fp64)
  Half-precision Floating-point support           (cl_khr_fp16)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Address bits                                    64, Little-Endian
  Global memory size                              8589934592 (8GiB)
  Error Correction support                        No
  Max memory allocation                           6871947673 (6.4GiB)
  Unified memory for Host and Device              No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       32768 bits (4096 bytes)
  Preferred alignment for atomics                 
  Global Memory cache type                        None
  Global Memory cache size                        0
  Global Memory cache line size                   0 bytes
  Image support                                   No
    Max number of samplers per kernel             32
    Max size for 1D images from buffer            2147483647 pixels
    Max 1D or 2D image array size                 2048 images
    Max 2D image size                             32768x32768 pixels
    Max 3D image size                             4096x4096x4096 pixels
    Max number of read image args                 32
    Max number of write image args                32
  Local memory type                               Local
  Local memory size                               32768 (32KiB)
  Max number of constant args                     16
  Max constant buffer size                        2147483647 (2GiB)
  Max size of kernel argument                     1024
  Queue properties                                
    Out-of-order execution                        No
    Profiling                                     Yes
  Queue properties (on host)                      
    Out-of-order execution                        No
    Profiling                                     Yes
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      0ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
  printf() buffer size                            0
  Built-in kernels                                (n/a)
  Device Extensions                               cl_khr_byte_addressable_store cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_fp64 cl_khr_fp16

  Device Name                                     Radeon RX 580 Series (POLARIS10, DRM 3.27.0, 5.0.0-arch1-1-ARCH, LLVM 7.0.1)
  Device Vendor                                   AMD
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.1 Mesa 18.3.4
  Driver Version                                  18.3.4
  Device OpenCL C Version                         OpenCL C 1.1 
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               36
  Max clock frequency                             1411MHz
  Device Partition                                (n/a)
    Max number of sub-devices                     0
    Supported partition types                     None
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             256x256x256
  Max work group size                             256
  Preferred work group size multiple              64
  Preferred / native vector sizes                 
    char                                                16 / 16      
    short                                                8 / 8       
    int                                                  4 / 4       
    long                                                 2 / 2       
    half                                                 8 / 8        (cl_khr_fp16)
    float                                                4 / 4       
    double                                               2 / 2        (cl_khr_fp64)
  Half-precision Floating-point support           (cl_khr_fp16)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Address bits                                    64, Little-Endian
  Global memory size                              8589934592 (8GiB)
  Error Correction support                        No
  Max memory allocation                           6871947673 (6.4GiB)
  Unified memory for Host and Device              No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       32768 bits (4096 bytes)
  Preferred alignment for atomics                 
  Global Memory cache type                        None
  Global Memory cache size                        0
  Global Memory cache line size                   0 bytes
  Image support                                   No
    Max number of samplers per kernel             32
    Max size for 1D images from buffer            2147483647 pixels
    Max 1D or 2D image array size                 2048 images
    Max 2D image size                             32768x32768 pixels
    Max 3D image size                             4096x4096x4096 pixels
    Max number of read image args                 32
    Max number of write image args                32
  Local memory type                               Local
  Local memory size                               32768 (32KiB)
  Max number of constant args                     16
  Max constant buffer size                        2147483647 (2GiB)
  Max size of kernel argument                     1024
  Queue properties                                
    Out-of-order execution                        No
    Profiling                                     Yes
  Queue properties (on host)                      
    Out-of-order execution                        No
    Profiling                                     Yes
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      0ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
  printf() buffer size                            0
  Built-in kernels                                (n/a)
  Device Extensions                               cl_khr_byte_addressable_store cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_fp64 cl_khr_fp16

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Clover
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [MESA]
  clCreateContext(NULL, ...) [default]            Success [MESA]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
    Platform Name                                 Clover
    Device Name                                   Radeon RX 580 Series (POLARIS10, DRM 3.27.0, 5.0.0-arch1-1-ARCH, LLVM 7.0.1)
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (2)
    Platform Name                                 Clover
    Device Name                                   Radeon RX 580 Series (POLARIS10, DRM 3.27.0, 5.0.0-arch1-1-ARCH, LLVM 7.0.1)
    Device Name                                   Radeon RX 580 Series (POLARIS10, DRM 3.27.0, 5.0.0-arch1-1-ARCH, LLVM 7.0.1)
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (2)
    Platform Name                                 Clover
    Device Name                                   Radeon RX 580 Series (POLARIS10, DRM 3.27.0, 5.0.0-arch1-1-ARCH, LLVM 7.0.1)
    Device Name                                   Radeon RX 580 Series (POLARIS10, DRM 3.27.0, 5.0.0-arch1-1-ARCH, LLVM 7.0.1)

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.12
  ICD loader Profile                              OpenCL 2.2
```

**Comment by andrew-wja** [comment]
Just to confirm, I see the same output with the test program you posted above using the 2D convolution primitive.

I checked my build options for the library, and they include `extra_cxx_flags="-fPIC"` as the docs say.

**Comment by AnthonyARM** [comment]
Could you please try to rebuild with either `debug=1` or `asserts=1` ?
Looks like an exception is thrown but without these enabled it will be hard to find out what the issue is.

**Comment by AnthonyARM** [comment]
To run the Compute Library you need either 
- OpenCL 2.0
- OpenCL 1.1 + [cl_arm_non_uniform_work_group_size](https://www.khronos.org/registry/OpenCL/extensions/arm/cl_arm_non_uniform_work_group_size.txt)
cl_arm_non_uniform_work_group_size is basically a backport of an OpenCL 2.0 feature which allows the global workgroup size to not be a multiple of the local workgroup size.

**Comment by andrew-wja** [comment]
Hi Anthony,

I rebuilt the library with debug=1 and asserts=1, but the error message is identical:

```
terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1
Aborted (core dumped)
```

I didn't realize that we require a specific extension for OpenCL 1.1.

Do you know of a specific x86 OpenCL implementation that supports OpenCL 2.0 or has the arm non-uniform workgroup size extension? Is there a version accompanying the Compute Library for x86 development?

**Comment by mpekatsoula** [comment]
You can easily find [online](https://en.wikipedia.org/wiki/OpenCL#OpenCL_2.0_support) which x86 OpenCL implementations support OpenCL 2.0.

The patch for x86_64 build is now available in our development branch [here](https://review.mlplatform.org/#/admin/projects/ml/ComputeLibrary).
