### ISSUE TITLE
Setting for cpu_has_dotprod = false

### ISSUE THREAD

**Issue by peter197321** [ARM-software/ComputeLibrary#643]
How to enable cpu_has_dotprod for ARM CPU? 
The ./arm_compute_benchmark benchmark has indicated me there is no this feature ebnabled.

**Comment by AnthonyARM** [comment]
Hi @peter197321 ,

That's probably because either your CPU doesn't support it or you're using an old Linux kernel.
What device / platform are you running on ?

**Comment by peter197321** [comment]
I have NXP i.MX8 4xA53 and 2xA72
root~# uname -a
Linux 4.14.78-imx_4.14.78_1.0.0_ga+g66620c3 #1 SMP PREEMPT Fri Feb 1 09:09:25 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux

How to check if cpu_has_dotprod is available or what that cpu_has_dotprod is (hw support, some sort of library) ?

**Comment by AnthonyARM** [comment]
You need a cpu that supports the Arm v8.2 dot product instruction (i.e Cortex-A55 / Cortex-A75 and above)
Cortex-A72 and Cortex-A53 CPUs implement v8.0 and therefore don't have the dot product instruction
