### ISSUE TITLE
Issue on run the OpenCL precommit benchmark tests

### ISSUE THREAD

**Issue by peter197321** [ARM-software/ComputeLibrary#644]
I hope I am executing the benchmark test as per required documentation 

`# LD_LIBRARY_PATH=. ./tests/arm_compute_benchmark --mode=precommit --filter='^CL.*' --instruments="opencl_timer_ms" --iterations=10
`
I have 

```
INFO: Could not load PPM image: /images/640x480.ppm
INFO: Could not load PPM image: /images/800x600.ppm
```
How to include it correctly for benchmark test?

**Comment by mpekatsoula** [comment]
You should also point to the data folder that contains the images as described [here](https://arm-software.github.io/ComputeLibrary/v19.02/tests.xhtml#tests_running_tests)
