### ISSUE TITLE
Performance improvements with lws_hint() instead of default_ndrange()

### ISSUE THREAD

**Issue by jyoungyun** [ARM-software/ComputeLibrary#645]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
```
arm_compute_version=v19.02 Build options: {'arch': 'armv7a', 'opencl': '1', 'neon': '1', 'build_dir': 'armv7a-linux.release', 'examples': '0', 'os': 'linux', 'Werror': '0'} Git hash=d2de75135e3741b0613a651668d85a177762ebc4
```
**Platform:**
armv7l
**Operating System:**
Linux odroid

**Problem description:**
This issue is related to `default_ndrange()` in ACL.

When we use acl kernel, we always add the acl kernel to the command queue using `enqueue` function. If we don't add the last paramter of this function, it calls `default_ndrange()` function to set `lws_hint` value by default. However, the function takes a long(?) time to access the device directly using `clGetDeviceInfo` function to get device name. The `ICLKernel` has already stored the `lws_hint` value in the configure step through the `default_ndrange()` function. So I think if we set the `lws_hint` in ICLKernel to the last parameter of `enqueue` function, I expect to be able to reduce the time.

So, I tested two cases:
1. before : original
2. after : Use `lws_hint()` instead of `default_ndrange()`

Some models have improved the performance even though the actual time taken is very small. And by checking the data by operator, I can clearly see the improvements.

* RESHAPE
  * [SqueezeNet](https://storage.googleapis.com/download.tensorflow.org/models/tflite/model_zoo/upload_20180427/squeezenet_2018_04_27.tgz): 0.268ms -> 0.125ms (2.144 times faster)
  * [ResNet v2 101](https://storage.googleapis.com/download.tensorflow.org/models/tflite/model_zoo/upload_20180427/resnet_v2_101_2018_04_27.tgz) : 0.230ms -> 0.127ms (1.811 times faster)
  * [Inception V3](https://storage.googleapis.com/download.tensorflow.org/models/tflite/model_zoo/upload_20180427/inception_v3_2018_04_27.tgz) : 0.290ms -> 0.146ms (1.986 times faster)
* MUL
  * [DenseNet](https://storage.googleapis.com/download.tensorflow.org/models/tflite/model_zoo/upload_20180427/densenet_2018_04_27.tgz) : 9.747ms -> 6.570ms (1.484 times faster)
  * [ResNet v2 101](https://storage.googleapis.com/download.tensorflow.org/models/tflite/model_zoo/upload_20180427/resnet_v2_101_2018_04_27.tgz) : 5.407ms -> 3.485ms (1.552 times faster)
* SQUEEZE
  * [Mobilenet v1.0 224](http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_1.0_224.tgz) : 0.134ms -> 0.054ms (2.481 times faster)
  * [Mobilenet v1.0 224 quant](http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_1.0_224_quant.tgz) : 0.090ms -> 0.050ms (1.8 times faster)
* FULLY_CONNECTED
  * [Inception ResNet V2](https://storage.googleapis.com/download.tensorflow.org/models/tflite/model_zoo/upload_20180427/inception_resnet_v2_2018_04_27.tgz) : 0.405ms -> 0.238ms (1.702 times faster)
  * [Inception V4](https://storage.googleapis.com/download.tensorflow.org/models/tflite/model_zoo/upload_20180427/inception_v4_2018_04_27.tgz) : 0.380ms -> 0.228ms (1.667 times faster)
* Modified kernel
  * CLPermuteKernel
  * CLReductionOperationKernel
  * CLPixelWiseMultiplicationKernel
  * CLWeightsReshapeKernel
  * CLWinogradFilterTransformKernel
  * CLGEMMReshapeRHSMatrixKernel
  * CLReshapeLayerKernel

So I suggest to apply `lws_hint()` in the case of the above kernels.

**Comment by gmiodice** [comment]
Hi @jyoungyun ,

and many thanks for using ACL :)

In order to reproduce your numbers, could you please tell us the following information?

1. Did you use our graph example to perform this evaluation? 
2. How many iterations did you run your test?
3. What unit of measure are you using for the performance? seconds? ms? ..

Thanks,

**Comment by jyoungyun** [comment]
> 2. How many iterations did you run your test?
I executed each model 10 times.

> 3. What unit of measure are you using for the performance? seconds? ms? ..
The unit is millisecond(ms).

> 1. Did you use our graph example to perform this evaluation?
I'm going to run acl graph example on my environment. And I will share the result here.

**Comment by jyoungyun** [comment]
Here is the performance data of graph examples:

|  | original | modified | diff (org - mod) | comments 
| :--: | :--: | :--: | :--: | :--:
| alexnet | 127.796 | 125.002 | 2.794
| googlenet | 164.336 | 167.167 | -2.831 | Why is it slower than before?
| inception_resnet_v1 | 2850.142 | 2841.753 | 8.389
| inception_resnet_v2 | 2197.747 | 2194.819 | 2.928
| inception_v3 | 824.588 | 830.697 | -6.109 | be slowed
| inception_v4 | 2135.351 | 2132.787 | 2.564
| lenet | 4.572 | 4.611 | -0.039 | be slower
| mobilenet | 119.32 | 120.197 | -0.877 | be slowed
| mobilenet_v2 | 81.123 | 81.009 | 0.114
| resnet12 | 1440.322 | 1443.245 | -2.923 | be slowed
| resnet50 | 515.835 | 515.037 | 0.798
| resnet_v2_50 | 512.074 | 509.323 | 2.751
| resnext50 | 1148.577 | 1138.395 | 10.182
| shufflenet | 63.495 | 63.241 | 0.254
| squeezenet | 105.817 | 106.063 | -0.246 | be slowed
| squeezenet_v1_1 | 62.471 | 62.667 | -0.196 | be slowed
| srcnn955 | 1248.653 | 1203.98 | 44.673
| ssd_mobilenet | 268.2 | 265.639 | 2.561
| vgg_vdsr | 1800.885 | 1792.76 | 8.125
| yolov3 | 6838.142 | 6783.185 | 54.957

Modified kernels:
```
src/core/CL/kernels/CLGEMMReshapeRHSMatrixKernel.cpp
src/core/CL/kernels/CLWinogradFilterTransformKernel.cpp
src/core/CL/kernels/CLConvertFullyConnectedWeightsKernel.cpp
src/core/CL/kernels/CLReshapeLayerKernel.cpp
src/core/CL/kernels/CLPixelWiseMultiplicationKernel.cpp
src/core/CL/kernels/CLPriorBoxLayerKernel.cpp
src/core/CL/kernels/CLUpsampleLayerKernel.cpp
```

I don't understand why some model is slower than before. But most models seems to have some benefits.

**Comment by jyoungyun** [comment]
What do you think about adding `lws_hint()` directly from the `enqueue()` function for some kernels that showed the effect? 

Like below..:
```
--- a/src/core/CL/kernels/CLGEMMReshapeRHSMatrixKernel.cpp
+++ b/src/core/CL/kernels/CLGEMMReshapeRHSMatrixKernel.cpp
@@ -166,7 +166,7 @@ void CLGEMMReshapeRHSMatrixKernel::run(const Window &window, cl::CommandQueue &q
         unsigned int idx = 0;
         add_3D_tensor_argument(idx, _input, slice);
         add_3D_tensor_argument(idx, _output, slice);
-        enqueue(queue, *this, slice);
+        enqueue(queue, *this, slice, lws_hint());
     }
     while(window.slide_window_slice_3D(slice));
```

**Comment by jyoungyun** [comment]
I wanna make a patch in [ml/ComputeLibrary gerrit](https://review.mlplatform.org/#/q/project:ml/ComputeLibrary). Is there anyone guide me?

**Comment by morgolock** [comment]
Hi @jyoungyun 

Would you please share the output of `git remote -v` ?

**Comment by morgolock** [comment]
Hi @jyoungyun

We have merged a patch with your suggestion: https://review.mlplatform.org/#/c/ml/ComputeLibrary/+/1803/

Thanks
