### ISSUE TITLE
How to print the value of CLTensor

### ISSUE THREAD

**Issue by ByeongHeonYOO** [ARM-software/ComputeLibrary#646]
I want to check whether the cl_sgemm is properly working. 
So, I tried dst.print(std::cout) but it prints some error message 'ERROR in print src/core/ITensor.cpp:77: this->buffer() == nullptr No such file or directory'.

I didn't edit original code but just add one instruction to print the value in CLTensor.
How can i print it?
Thank you in advance.

**Comment by AnthonyARM** [comment]
Hi,

This means you're trying to print a tensor that hasn't been allocated or isn't mapped.
As you're using OpenCL, I assume it's the latter: you need to call [CLTensor::map()](https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/CL/CLTensor.h#L55) before you print the content of the tensor.

Hope this helps

**Comment by ByeongHeonYOO** [comment]
Hi, i used map & unmap as you advised and print function works!

Thank you!

**Comment by ByeongHeonYOO** [comment]
> Hi,
> 
> This means you're trying to print a tensor that hasn't been allocated or isn't mapped.
> As you're using OpenCL, I assume it's the latter: you need to call [CLTensor::map()](https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/CL/CLTensor.h#L55) before you print the content of the tensor.
> 
> Hope this helps
