### ISSUE TITLE
How can i use gemm in integer data type?

### ISSUE THREAD

**Issue by ByeongHeonYOO** [ARM-software/ComputeLibrary#648]
**Problem description:**
Hi, I need to execute gemm in integer data type(S32, not float32 or float16) using cl and neon.
To do that, i added the data type in each kernel.cpp(neon, cl) but it print error message.
The error messages are here.
- OpenCL
"ERROR in create_kernel src/core/CL/CLKernelLibrary.cpp:971: Kernel gemm_mm_interleaved_transposed_s32 not found in the CLKernelLibrary No such file or directory"
- Neon
"ERROR in run src/core/NEON/kernels/NEGEMMMatrixMultiplyKernel.cpp:1054: Data type not supported"

Actually, in Neon case, i tried to find matrixmultiply function about S32 type but i coudln't find.
If there is any example, please let me know.
Thank you in advance.

**Comment by morgolock** [comment]
Hi @ByeongHeonYOO 

The CLGEMM and NEGEMM functions support only the data types float and half (float 16 bits). You could check out the documentation to know what data types each function supports: 
https://arm-software.github.io/ComputeLibrary/v19.02/classarm__compute_1_1_c_l_g_e_m_m.xhtml#a34e7b882208ff6720bad2e4f2c7565c5

I'd suggest your convert your input to from S32 to F32 before calling GEMM in ACL? Would this be a good workaround for you?

Hope this helps.

**Comment by VadasCorePrj** [comment]
Hi @morgolock 

Thank you for answering my question.

It helps me!
Thank you again.
