### ISSUE TITLE
Too high performances??? Am i doing it right?

### ISSUE THREAD

**Issue by GAnto85** [ARM-software/ComputeLibrary#649]
Hi all!! i'm using one of the examples (neon_cnn) to test the performances of NEON. I've been using  F32 Datatype and these are the results i get. To me, they seem way too good, what do you think about it?
![image](https://user-images.githubusercontent.com/39409379/54551367-40b12880-49ae-11e9-99c0-e3c1ff94fa11.png)

**Comment by ManubARM** [comment]
Hi @GAnto85,
Performances are platform specifics, so it is very difficult for us to confirm or not without knowing where you run the code. 

Anyway I think the best way for you would be to compare the outputs with a reference implementation that you trust.

Best,
Manuel

**Comment by GAnto85** [comment]
Thanks for you reply!
