### ISSUE TITLE
how to support multi channel input?

### ISSUE THREAD

**Issue by kananaskis** [ARM-software/ComputeLibrary#65]
for example, does NEremap support BGRA8888 input? tx
[remap](https://arm-software.github.io/ComputeLibrary/v17.03.1/classarm__compute_1_1_n_e_remap.xhtml#a7570555ae5933bef168425e55a1a11a9)

**Comment by AnthonyARM** [comment]
No, you have to do a channel extract then do a remap per channel.
Most computer vision algorithms are performed on grayscale images, that's why most of the functions only support U8.

**Comment by kananaskis** [comment]
@AnthonyARM thank you! so i have to transform RGBA  into Tensor with 4 feature_maps to do remap.

**Comment by GeorgeARM** [comment]
Assuming question has been addressed. Closing issue. Reopen if required!
