### ISSUE TITLE
How to print a Tensor?!

### ISSUE THREAD

**Issue by GAnto85** [ARM-software/ComputeLibrary#650]
Hi all, i need to print a convolution output Tensor , to check the results. I'm new with C++ but i hav e enough experience with C. I can't print it at all. Any suggestions? Thank you!

**Comment by mpekatsoula** [comment]
Hi @GAnto85 

You can use the [print method](https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/core/ITensor.h#L85) in order to print the Tensor's data. 

For example:
`dst.print(std::cout);`

**Comment by GAnto85** [comment]
Hi, Thank you for your answer. I've been trying to use that one but it says: 
![image](https://user-images.githubusercontent.com/39409379/54598061-02f8e200-4a38-11e9-8caf-e1e20eb842a1.png)

**Comment by GAnto85** [comment]
#include "arm_compute/runtime/NEON/NEFunctions.h"
#include "arm_compute/runtime/NEON/functions/NEDirectConvolutionLayer.h"
#include "arm_compute/core/Types.h"
#include "arm_compute/core/ITensor.h"
#include "arm_compute/runtime/Allocator.h"
#include "arm_compute/runtime/BlobLifetimeManager.h"
#include "arm_compute/runtime/MemoryManagerOnDemand.h"
#include "arm_compute/runtime/PoolManager.h"
#include "utils/Utils.h"
#include <chrono>


using namespace arm_compute;
using namespace utils;
using namespace std::chrono;
using namespace std;


class ARMCONVNEON : public Example
{
public:
    bool do_setup(int argc, char **argv) override
    {
        //ARM_COMPUTE_UNUSED(argc);
        //ARM_COMPUTE_UNUSED(argv);
        
        // Create memory manager components
        // We need 2 memory managers: 1 for handling the tensors within the functions (mm_layers) and 1 for handling the input and output tensors of the functions (mm_transitions))
        auto lifetime_mgr0  = std::make_shared<BlobLifetimeManager>();                           // Create lifetime manager
        auto lifetime_mgr1  = std::make_shared<BlobLifetimeManager>();                           // Create lifetime manager
        auto pool_mgr0      = std::make_shared<PoolManager>();                                   // Create pool manager
        auto pool_mgr1      = std::make_shared<PoolManager>();                                   // Create pool manager
        auto mm_layers      = std::make_shared<MemoryManagerOnDemand>(lifetime_mgr0, pool_mgr0); // Create the memory manager
        auto mm_transitions = std::make_shared<MemoryManagerOnDemand>(lifetime_mgr1, pool_mgr1); // Create the memory manager
        
        
        // The weights and biases tensors should be initialized with the values inferred with the training
        // Set memory manager where allowed to manage internal memory requirements
        conv   = arm_compute::support::cpp14::make_unique<NEConvolutionLayer>(mm_layers);
        //conv   = arm_compute::support::cpp14::make_unique<NEDirectConvolutionLayer>(mm_layers);
        

        if(argc < 8){
        
          cout<< "argc: "<< argc << " .Not enough parameters have been inserted"<< std::endl;

        }

        /* [Initialize tensors] */
        // Initialize src tensor
         unsigned int width_src_image  = atoi(argv[1]);//32;
         unsigned int height_src_image = atoi(argv[2]);//32;
         unsigned int ifm_src_img      = atoi(argv[3]);//96;

        const TensorShape src_shape(width_src_image, height_src_image, ifm_src_img);
        src.allocator()->init(TensorInfo(src_shape, 1, DataType::QASYMM8));
        
        
        // Initialize tensors of conv
         unsigned int kernel_x_conv = atoi(argv[5]);//3;
         unsigned int kernel_y_conv = atoi(argv[6]);//3;
         unsigned int ofm_conv      = atoi(argv[4]);//96;

         unsigned int stride_x = atoi(argv[7]);
         unsigned int stride_y = atoi(argv[7]);
         unsigned int pad_x = atoi(argv[8]);
         unsigned int pad_y = atoi(argv[8]);
        
        std::cout << "convolution " <<kernel_x_conv<<"x"<<kernel_y_conv<<"\n";
        std::cout << "input image: "<<height_src_image<<"x"<<width_src_image<<"\n"; 
        std::cout <<  ifm_src_img << " input features \n";
        std::cout <<  ofm_conv << " output features \n";
        std::cout <<  "stride " << stride_x << "\n";
        std::cout <<  "padding " << pad_x << "\n";
        
        const TensorShape weights_shape_conv(kernel_x_conv, kernel_y_conv, src_shape.z(), ofm_conv);
        const TensorShape biases_shape_conv(weights_shape_conv[3]);
        const TensorShape out_shape_conv(src_shape.x(), src_shape.y(), weights_shape_conv[3]);
        
        
        weights.allocator()->init(TensorInfo(weights_shape_conv, 1, DataType::QASYMM8));
        biases.allocator()->init(TensorInfo(biases_shape_conv, 1, DataType::QASYMM8));
        out_conv.allocator()->init(TensorInfo(out_shape_conv, 1, DataType::QASYMM8));

        //out_conv.print(std::cout);
        
        /* -----------------------End: [Initialize tensors] */


        /* [Configure functions] */
        
        // in: kxk convolution, o output features maps (OFM)
        conv->configure(&src, &weights, &biases, &out_conv, PadStrideInfo( stride_x ,  stride_y , pad_x , pad_y));
        
        
        /* -----------------------End: [Configure functions] */
        
        
        /*[ Add tensors to memory manager ]*/

        // We need 1 memory group for handling the input and output
        // We call explicitly allocate after manage() in order to avoid overlapping lifetimes    
        
        
        memory_group = arm_compute::support::cpp14::make_unique<MemoryGroup>(mm_transitions);
        
        memory_group->manage(&out_conv);
        out_conv.allocator()->allocate();
        
       /* -----------------------End: [ Add tensors to memory manager ] */
       
        /* [Allocate tensors] */

        // Now that the padding requirements are known we can allocate all tensors
        src.allocator()->allocate();
        weights.allocator()->allocate();
        biases.allocator()->allocate();
        
        /* -----------------------End: [Allocate tensors] */
        
        // Populate the layers manager. (Validity checks, memory allocations etc)
        mm_layers->populate(allocator, 1 /* num_pools */);

        // Populate the transitions manager. (Validity checks, memory allocations etc)
        mm_transitions->populate(allocator, 2 /* num_pools */);   
        
           
        return true;
    }
    void do_run() override
    {
        // Acquire memory for the memory groups
        memory_group->acquire();

        high_resolution_clock::time_point t1 = high_resolution_clock::now();

        conv->run();
              
        high_resolution_clock::time_point t2 = high_resolution_clock::now();
        auto duration = duration_cast<microseconds>( t2 - t1 ).count();
        std::cout << "Convolution time:" << duration << " us" << std::endl;

        
        out_conv.print(std::cout);

        // Release memory
        memory_group->release();

    }
    
    
private:
    // The src tensor should contain the input image
    Tensor src{};

    // Intermediate tensors used
    Tensor weights{};
    Tensor biases{};
    Tensor out_conv{};


    // NEON allocator
    Allocator allocator{};

    // Memory groups
    std::unique_ptr<MemoryGroup> memory_group{};


    // Layers
    std::unique_ptr<NEConvolutionLayer>    conv{};
   // std::unique_ptr<NEDirectConvolutionLayer>    conv{};

};



int main(int argc, char **argv)
{
    return utils::run_example<ARMCONVNEON>(argc, argv);
}

**Comment by mpekatsoula** [comment]
How did you compile the library? You need to enable asserts when building with asserts=1 in order to use the print method.

**Comment by GAnto85** [comment]
Ah...ok then that must be the problem!! I'm pretty sure i didn't do that !! I will recompile the library and let you know. Thank you for your help!

**Comment by morgolock** [comment]
Hi @GAnto85 

You must compile ACL with debug=1 otherwise you'll get the linker error you mentioned.

The print() method in the link below will do your job: 

https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/core/ITensor.h#L85

Closing this, if you experience problems please reopen.
