### ISSUE TITLE
Where can I find the examples for HoG

### ISSUE THREAD

**Issue by hejinIzhanghao** [ARM-software/ComputeLibrary#651]
**Nvidia TX2:**

**Ubuntu:**

**Problem description:**
Hello there, 
#129 & #128 have issused the HoG examples.

Anybody can provide it？

**Comment by morgolock** [comment]
Hi @hejinIzhanghao 

Currently we have no HOG examples in ACL.

I'd suggest you take a look at the fixtures in the validation tests.

https://github.com/ARM-software/ComputeLibrary/blob/master/tests/validation/fixtures/HOGDescriptorFixture.h
https://github.com/ARM-software/ComputeLibrary/blob/master/tests/validation/fixtures/HOGDetectorFixture.h
https://github.com/ARM-software/ComputeLibrary/blob/master/tests/validation/fixtures/HOGMultiDetectionFixture.h

This might help you to gain a better understanding on how to use these functions and configure them properly.

Hope this helps.
