### ISSUE TITLE
Grouped Convolution for NEON 

### ISSUE THREAD

**Issue by pranathibl** [ARM-software/ComputeLibrary#652]
Hi,

I have observed that ACL is supporting grouped convolution for ARM Mali target and not supported for ARM Neon. 

Are there any known issues restricting the support of grouped convolution on ARM Neon?
When can I expect ACL to support grouped convolution for ARM Neon?

Thank you.

**Comment by pranathibl** [comment]
Is there any update on this?

**Comment by GeorgeARM** [comment]
Hello @pranathibl,
Currently we support native grouped convolution for NCHW for the CL backend. There is nothing restricting us for supporting it on Neon as well, but we have it lower in our priority list as this can be achieved by using subtensors and dispatch multiple convolutions instead. Is this something that you think needs to be natively supported for NEON soon?

**Comment by pranathibl** [comment]
Hi @GeorgeARM ,

Yes, We want it to be natively supported for Neon as well. reason is, In one of our networks number of groups for convolution are 96, which will be difficult to implement using sub-tensors. 

Let us know the timeline if you are implementing it.

Thanks

**Comment by pranathibl** [comment]
any update on this?

**Comment by morgolock** [comment]
We have plans to add support for https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0a847acf8d9f3d2343328c3dbe6d447c50 in the Neon backend. Is this what you are asking for?

I cannot provide any potential dates but this is something in our backlog and will be done in the short/medium term.

**Comment by jcanore** [comment]
Is there any progress in supporting grouped convolutions in the Neon backend? Thanks.

**Comment by morgolock** [comment]
Hi @jcanore 

This has dropped down in our backlog so I don't think we'll do it in the short term.
