### ISSUE TITLE
Integration of new Layers for graph execution!!

### ISSUE THREAD

**Issue by GAnto85** [ARM-software/ComputeLibrary#653]
Hello everybody!
I was looking into the graph mode in order to run a few nets and execute inference. It works fine. 
Now i am curious if i can integrate my own convolution function that allows me to use a convolution accelerator implemented in the programmable logic. I already have my API to use the accelerator. I was wondering if i can add it when the graph is built: 

```cpp
 graph << common_params.target
              << common_params.fast_math_hint
              << InputLayer(input_descriptor, get_input_accessor(common_params, 
                    std::move(preprocessor)))
              // Layer 1
              << ConvolutionLayer(
                  11U, 11U, 96U,
                  get_weights_accessor(data_path, "/cnn_data/alexnet_model/conv1_w.npy", 
                  weights_layout),
                  get_weights_accessor(data_path, "/cnn_data/alexnet_model/conv1_b.npy"),
                  PadStrideInfo(4, 4, 0, 0))
              .set_name("conv1")
              << ActivationLayer(ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::RELU)).set_name("relu1")
              << NormalizationLayer(NormalizationLayerInfo(NormType::CROSS_MAP, 5, 0.0001f, 0.75f)).set_name("norm1")
              << PoolingLayer(PoolingLayerInfo(PoolingType::MAX, 3, PadStrideInfo(2, 2, 0, 0))).set_name("pool1")
              // Layer 2
              << ConvolutionLayer(
                  5U, 5U, 256U,
                  get_weights_accessor(data_path, "/cnn_data/alexnet_model/conv2_w.npy", weights_layou......
```

Furthermore, i don't understand how the output of each layer is given to the input of the next layer. And at last i don't see a direct connection with the kernels... i mean i see a function graph.run();  this function executes `_manager.execute_graph(_g);  `

`void GraphManager::execute_graph(Graph &graph)` runs the graph with `detail::call_all_tasks(it->second);`
`void call_all_tasks(ExecutionWorkload &workload) `executes the tasks by doing:
         
    for(auto &task : workload.tasks)
    {
        task();
    }

I don't see the connection with the convolution kernels.

**Comment by morgolock** [comment]
Hi @GAnto85 

I'd suggest you try adding a new 'custom' node to the graph API that calls your own convolution layer function.

The data flow through the different layers should be handled automatically by the existing code in the graph API; you should only add code to implement a new node type, please take a look at the NEFunctionFactory, it'll be a good starting point to give you a general idea of the kind of work you'll have to do: https://github.com/ARM-software/ComputeLibrary/blob/master/src/graph/backends/NEON/NEFunctionFactory.cpp#L189

You'll also need to modify the following files:
https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/graph/Types.h
https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/graph/GraphBuilder.h
https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/graph/backends/FunctionHelpers.h

Hope this helps.

**Comment by GAnto85** [comment]
Thank you so much! I'm gonna work on it. I will let you know how it goes!

**Comment by GeorgeARM** [comment]
Hello @GAnto85,

You could extend the methods of the Convolution [here](https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/graph/Types.h#L103) and add one of your own.
Then in the Neon backend [here](https://github.com/ARM-software/ComputeLibrary/blob/master/src/graph/backends/NEON/NEFunctionFactory.cpp#L109) you can extend the function generator and return your own wrapped function instead. The function interface that you need to implement is [this](https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/IFunction.h).
 Memory synchronization or anything similar between your accelerator should be handled by you.

Finally, the graph interface is just made for integration testing on our side. A more elaborate/productized graph interface using our SW stack is [ArmNN](https://github.com/ARM-software/armnn). 

Hope this helps.

**Comment by GAnto85** [comment]
Thanks for the help!

**Comment by GAnto85** [comment]
Hi everybody. The accelerator can only read in a limited range of the DDR due to addressing issues. I have my own function to create a pointer to that region. I'm not sure how to work with tensors in the library. If i directly load them in that area through the pointer then i don't know how to follow the graph. I don't know how to explain my problem.

**Comment by GeorgeARM** [comment]
Hello @GAnto85,

I understand your problem, unfortunately I don't see a very straightforward way for you to do it without involving a copy, but I suppose this is OK for now. When you overload the function `run()` method you can copy the given input to a region that you want and then feed that to the acclerator.

```
class CLConvolutionLayerAcc : public IFunction
{
public:
    void configure(const ICLTensor *input, const ICLTensor *weights, const ICLTensor *biases, ICLTensor *output, const PadStrideInfo &conv_info, ...);

    // Inherited methods overridden:
    void run() override;
    void prepare() override;

private:
   const ICLTensor *_input;
   const ICLTensor *_weights;
   const ICLTensor *_biases;
   const ICLTensor *_output;
};
```
In `configure()` you can set your private variables to track the tensors like we do in most of our functions.
Then in `prepare()` you can copy your weights and biases to the region that your accelerator sees, this has to be done only once as they are persistent during execution (that's why we have a prepare stage).
During the `run()` you copy the input to the memory region that you want then you run your accelerated function and the copy back the output from your region to the ACL output tensor.

That is the least invasive solution I can think of. Otherwise you need to overload the interface that manages the tensors' memory between layers to do the allocations in the region that you want, this will help you avoid the copies for the input and output.
Hope this helps.

**Comment by GAnto85** [comment]
Thank you so much, this is gonna help a lot! I'm gonna try both solutions.

**Comment by GAnto85** [comment]
Maybe i'm missing something but i can't find the overloading of the method configure() or prepare() for a ConvolutionLayer , for example in the file graph_alexnet.cpp. Also, i cannot find a way to send the parameters of the layer as : 

<< ConvolutionLayer(
                  11U, 11U, 96U,
                  get_weights_accessor(data_path, "/cnn_data/alexnet_model/conv1_w.npy", weights_layout),
                  get_weights_accessor(data_path, "/cnn_data/alexnet_model/conv1_b.npy"),
                  PadStrideInfo(4, 4, 0, 0))

to the new class created above (child of IFunction). I need to pass some of these parameters like 11U, 11U, 96U, and PadStrideInfo(4, 4, 0, 0) to the accelerator API function that will be called in the method run() of CLConvolutionLayerAcc (class above).

**Comment by GAnto85** [comment]
Hello!! I have an issue which i can't figure out. I added the accelerator method (NEURAghe) in NEConvolutionLayer.cpp.
![image](https://user-images.githubusercontent.com/39409379/55279215-5b708f00-5316-11e9-8330-f2f8794c21ff.png)
For some reason i can't compile it. This is the error i get.
![image](https://user-images.githubusercontent.com/39409379/55279238-865ae300-5316-11e9-9f92-a091321ecfcd.png)
Any idea in order to overcome it? Thanks

**Comment by GAnto85** [comment]
Hello , i've got problems with validating the new Class!! 
![image](https://user-images.githubusercontent.com/39409379/55316060-e31ce180-546d-11e9-9ceb-34380e1122ed.png)
![image](https://user-images.githubusercontent.com/39409379/55316080-ee700d00-546d-11e9-8b09-568f54cb65c8.png)

**Comment by GAnto85** [comment]
Hello, i have a bad_alloc problem. This is really hard to explain but i'll try. When i initialize the accelerator i execute a function init_soc() , which creates the pointers to the SoC addresses and DDR  by using the mmap function. In particular if i don't comment these lines , i'll get a bad_alloc error:
![image](https://user-images.githubusercontent.com/39409379/55480927-9417ad80-5621-11e9-92c1-5dd2b393616f.png)
where addr_linux is:
![image](https://user-images.githubusercontent.com/39409379/55480961-a8f44100-5621-11e9-939b-b1fd5dbb6c8f.png)
This initalization works well if i'm using the accelerator alone, but merging with with compute library is complicated. If i reduce the parameter DDR_SIZE the error is gone but i can't reduce it that much. Maybe at some point the compute library is trying to access to a memory region already allocated by the accelerator initialization and this ends up in a bad_alloc? 
Do you know anything i can do to overcome this problem? Maybe modificating any memory allocation function?

**Comment by morgolock** [comment]
Hi @GAnto85 

Could you please provide a callstack of the code throwing the `bad_alloc` exception as well as the size trying to allocate and the total amount of memory available on the system?

**Comment by GAnto85** [comment]
Hello, i fixed the problem somehow... 
Now i found out something weird... i am running alexnet and there are some 3x3 convolutions such as: 
a) 256 input features - 384 output features
b) 384 input features - 384 output features
c) 384 input features - 256 output features

I realized that the compute library is splitting these convolutions like this : 
a) 256 input features - 384 output features     //UNCHANGED
b.1) 192 input features - 192 output features
b.2) 192 input features - 192 output features
c.1) 192 input features - 128 output features
c.2) 192 input features - 128 output features

How can be possible? Every output feature needs the contribution of every input feature to be completed. If we split both input and output features in two parts, none of the output features can be finished. 
Can anybody help me please?

**Comment by GAnto85** [comment]
Another question... i just realized that the files .npy contain floating point weights.
![image](https://user-images.githubusercontent.com/39409379/55618983-14f8b580-5798-11e9-9910-d70b80c690e2.png)
But the Tensors contain 8bit weights and biases. Is there a quantization somewhere in the graph flow?

**Comment by morgolock** [comment]
Hi @GAnto85 

I would expect a quantized model to store the weights as unsigned char. 

What particular npy file have you printed? If you print the npy for a quantized model you should see something like this:

![qasymweights](https://user-images.githubusercontent.com/5577511/55621126-8d5d7780-5794-11e9-971b-79aadfe9bbe7.png)

These values would be used to fill the QASYMM8 tensors.

**Comment by GAnto85** [comment]
Hi! i printed these files using np.load 
![image](https://user-images.githubusercontent.com/39409379/55621344-88e98c80-579d-11e9-8091-4d0277d2c321.png)
they are floating points, but when i read the tensors where they have been put in , i read uint_8 !!

**Comment by morgolock** [comment]
Hi @GAnto85 

Where did you get those model files? It seems they are the weights for float and not qasymm8.

**Comment by GAnto85** [comment]
From some website suggested by my coordinator . The model works just fine , the inference is executed perfectly and the input image is always recognized. I just don't realize how these weights get converted from floating point to qasymm8 ! I'm taking a look at the dataflow and i don't see any conversion. I've checked the NumpyBinLoader and NPYLoader classes but i don't see anything particularly weird.

**Comment by GAnto85** [comment]
Anybody knows why the library splits the convolution layers in two parts?

**Comment by morgolock** [comment]
Hi @GAnto85 

> Hello, i fixed the problem somehow...
> Now i found out something weird... i am running alexnet and there are some 3x3 convolutions such as:
> a) 256 input features - 384 output features
> b) 384 input features - 384 output features
> c) 384 input features - 256 output features
> 
> I realized that the compute library is splitting these convolutions like this :
> a) 256 input features - 384 output features //UNCHANGED
> b.1) 192 input features - 192 output features
> b.2) 192 input features - 192 output features
> c.1) 192 input features - 128 output features
> c.2) 192 input features - 128 output features
> 
> How can be possible? Every output feature needs the contribution of every input feature to be completed. If we split both input and output features in two parts, none of the output features can be finished.
> Can anybody help me please?

I assume you are running ACL's alexnet graph example, is this correct? if so could you please share the command to run the example.

**Comment by GAnto85** [comment]
Hello! I'm running it typing this command on the terminal: 

agarufi@neuro-pulpemu:~/cnnlib$ sudo LD_LIBRARY_PATH=. ./ARMCONVNEON --fast-math  --image=images/school_bus.ppm --layout=NCHW --data=.  --labels=labels.txt  --threads=1 --type=F32 ARM_COMPUTE_LOG_GRAPH_INFO

**Comment by GAnto85** [comment]
Hello, is possible to use the function "void fill_tensor(T &tensor)" in utils/Utils.h to load a random .npy file in a tensor? 
Our accelerator requires, for each layer 3x3, a particular structure made of 32 elements: 27 weights, 1 bias and 4 zeros. The total number of elements will be : num of input channels * num of output features * 3 * 3 / 3. So i don't need to load a weight and a bias file, but just one file weights and biases are interleaved in a certain way. 
If i try loading a file with such structure into a tensor, i get this error: 
![image](https://user-images.githubusercontent.com/39409379/55789477-b6df1180-5aba-11e9-9e70-b528ca498cd3.png)
Is it because every tensor is already 'pre-configured' to contain a certain number of elements? Any suggestion to overcome this issue?

**Comment by AnthonyARM** [comment]
I'm confused: are you feeding the tensor to your accelerator or to ACL's NEON backend ?

**Comment by GAnto85** [comment]
It's very confusing i know =\  I am trying to fill the tensor with the data from the .npy file. Then in prepare() i copy the tensor into another structure located in region where my accelerator can access.

**Comment by morgolock** [comment]
Closed by inactivity, please reopen if this is still relevant.
