### ISSUE TITLE
NEGaussian Right/Left Border removed

### ISSUE THREAD

**Issue by julled** [ARM-software/ComputeLibrary#654]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v19.02 Build options: {'arch': 'armv7a', 'opencl': '0', 'neon': '1', 'examples': '1', 'asserts': '0', 'debug': '0', 'os': 'linux', 'Werror': '1'} Git hash=29f6788cee8881c5523a042a0ac9b0131d993768
**Platform:**
rpi 3 
**Operating System:**
raspbian  

**Problem description:**
When using NE gaussian blur functions, 8 pixels from the right and left border of ppm-loader  #loaded images get removed. In the attached image i used a 5x5 kernel. The same error appears when using a 3x3 kernel. The top and bottom of the image looks okey so far. 
Can someone reproduce this? I used opencv as reference where this error doesnt happen.
![Selection_161](https://user-images.githubusercontent.com/8696195/54884664-0515d300-4e74-11e9-90da-97e19d383a38.png)

**Comment by morgolock** [comment]
Hi @julled 

Could you please share the code you use to test this? It would be also helpful if you shared more details on the input (shapes,etc)

**Comment by julled** [comment]
Test-Img:
https://ufile.io/i781d
Code:
`
#include "arm_compute/runtime/NEON/NEFunctions.h"
#include "arm_compute/core/Types.h"
#include "utils/ImageLoader.h"

using namespace arm_compute;
using namespace utils;

int main(int argc, char **argv)
{

    Image src{};
    PPMLoader ppm;

    if(argc < 2)
    {
        src.allocator()->init(TensorInfo(640, 480, Format::U8));
    }
    else
    {
        ppm.open(argv[1]);
        ppm.init_image(src, Format::U8);
    }
    src.allocator()->allocate();

    if(ppm.is_open())
    {
        ppm.fill_image(src);
    }
 
    NEGaussian5x5 blur{};
    Image blurredImg{};
	blurredImg.allocator()->init(*(src.info()));

    blur.configure(&src, &blurredImg, BorderMode::CONSTANT);
	blurredImg.allocator()->allocate();
	blur.run();

	// Save the result to file:
    std::cout << "Save... "<< "\n";
    save_to_ppm(blurredImg,"out.ppm"); // save_to_ppm maps and unmaps the image to store as PPM
    std::cout << "Save Finished! "<< "\n";

    return 0;
}
`

**Comment by morgolock** [comment]
Hi @julled 

Could you please try moving:


`src.allocator()->allocate();`
`if(ppm.is_open())`
`{`
`ppm.fill_image(src);`
`}`

after `blur.configure(&src, &blurredImg, BorderMode::CONSTANT)`

**Comment by morgolock** [comment]
Hi @julled 

Gaussian5x5 needs padding to operate on the full input image, if you call allocate() after configure() this extra padding is added automatically by the library. If you don't do that, the library will reduce the area on which the kernel is executed to ensure not writing outside the bounds of the input image.

Quoted from the library documentation:
> It's important to call allocate after the function is configured: if the image / tensor is already allocated then the function will shrink its execution window instead of increasing the padding. (See below for more details).

https://arm-software.github.io/ComputeLibrary/v19.02/architecture.xhtml#S4_6_images_tensors
