### ISSUE TITLE
Arm Compute lib graph model - Convolution Layer with Dilation

### ISSUE THREAD

**Issue by gilboash** [ARM-software/ComputeLibrary#655]
**Platform:**
ARM57 (NEON)
**Operating System:**
Linux

**Problem description:**

im trying to pipe a proprietry model using arm compute library, looking at the examples in the examples folder, couldn't find how to set dilation in ConvolutionLayer() routine

here is an example i saw:
ConvolutionLayer(
             7U, 7U, 64U,
             get_weights_accessor(data_path, "/cnn_data/resnet50_model/conv1_weights.npy"),
             std::unique_ptr<arm_compute::graph::ITensorAccessor>(nullptr),
             PadStrideInfo(2, 2, 3, 3))
            .set_name("conv1/convolution")

where to set dilation?

**Comment by morgolock** [comment]
Hi @gilboash 

At present there is no way to specify the dilation in the graph API. However, you could make the necessary changes in https://github.com/ARM-software/ComputeLibrary/blob/master/src/graph/backends/NEON/NEFunctionFactory.cpp#L117 to allow this when the method is ConvolutionMethod::GEMM. Please be aware that the other convolution methods do not support dilation.

Hope this helps.

**Comment by gilboash** [comment]
i see the NEConvolutionLayer also supports dilation. isnt that the case?

**Comment by morgolock** [comment]
Hi @gilboash 

Yes, but that's in the runtime library and not in the graph API.

You can see it here in the function interface:
https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/NEON/functions/NEConvolutionLayer.h#L93

You need to make some changes in the graph API to allow passing the dilation information into the neon function.

**Comment by RavikumarLav** [comment]
hi @gilboash 
I am just trying to test examples given in repository.
where we can find the weights data " conv1_weights.npy" in the repo.
I am not able to see "/cnn_data/resnet50_model/conv1_weights.npy" path so ib am getting error as file not found
Please suggest where to get this file
