### ISSUE TITLE
Is there a pre-tested list for Arm Computing library version and NDK version?

### ISSUE THREAD

**Issue by blueardour** [ARM-software/ComputeLibrary#656]
hi, guys:

it seems that both the arm computing library and NDK are updating in a fast rhythm. Currenty NDK version is r19c and the ACL version is v19.02.  Some errors when binding the two version software.

When I compile the ACL on Ubuntu18.04 with NDK r19c, CXX=clang++ CC=clang scons Werror=1 -j8 debug=1 neon=1 opencl=1 os=android arch=arm64-v8a reported the following error:

scons: *** [build/src/core/CL/cl_kernels/absdiff.clembed] TypeError : cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "/usr/lib/scons/SCons/Action.py", line 1197, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "/workspace/git/ComputeLibrary/SConscript", line 89, in resolve_includes
    found = pattern.search(line)
TypeError: cannot use a string pattern on a bytes-like object
scons: building terminated because of errors.

**Comment by blueardour** [comment]
hi, I've fixed the error I met. It's a python issue. After changed to the python2, the error was gone.

**Comment by GeorgeARM** [comment]
Hello @blueardour,
Glad you resolved the issue. Our [documentation](https://arm-software.github.io/ComputeLibrary/v19.02/index.xhtml#S3_3_android) mentions the NDKs we tested. But newer ones I suppose they should work. If you notice any issues feel free to open an issue here.
Hope this helps.
