### ISSUE TITLE
Custom Kernel FP16 version values are overflowing.

### ISSUE THREAD

**Issue by ssj4gogeta** [ARM-software/ComputeLibrary#658]
**Platform:**
arm64-v8a

**Operating System:**
Android 9 Pie

**Problem description:**
Hello,

I have added a custom kernel in Compute Library and if datatype is F32 it is working fine. But when I give the execution datatype as F16, some values are overflowing and the values are coming as inf. Is there an in-built way in Compute Library to handle such cases? Or any documentation that helps in handling? Any pointers are highly appreciated.

Thank you.

**Comment by morgolock** [comment]
Hi @ssj4gogeta 

I assume you are speaking of a new CL kernel, right?

When doing arithmetic some values will inevitably overflow for very big input shapes and low precision data types; but this also depends on other things like the actual input values you feed your kernel.

At the level of primitive datatypes there is nothing in ACL which would prevent operations like + or * to overflow when writing new code. Your code should handle this, some kernels in ACL clamp values for example.

Hope this helps.

**Comment by ssj4gogeta** [comment]
Hello @morgolock,

Thank you for the information. Can we do something like quantizing so that this overflow wouldn't happen rather than clamping to avoid loss in accuracy?

Thank you.

**Comment by morgolock** [comment]
Hi @ssj4gogeta 
I don't see how quantizing could help with overflow. Quantization is basically a very compact way to represent tensors and arithmetic will still overflow.

What range of values are you feeding to your kernel?

**Comment by ssj4gogeta** [comment]
The values are exceeding (2^16 - 1) inside the calculation. These values are coming as inf in the tensor. So, that is causing the issue.

**Comment by morgolock** [comment]
Hi @ssj4gogeta 

I meant: what are the input values before any computation, what's the range of values for the input?

**Comment by morgolock** [comment]
Closed by inactivity, if reopening please provide more information.
