### ISSUE TITLE
v19.02 - missing build/tests/benchmark_graph* apps? 

### ISSUE THREAD

**Issue by ghimiredhikura** [ARM-software/ComputeLibrary#659]
Hello, 

In new release version I can't get build/tests/benchmark_graph* apps. 
```
Platform: RPI3B+, aarch64. 
ARMCL_Version: v19.02
Build_command: scons arch=arm64-v8a benchmark=1 benchmark_tests=1 opencl=0 neon=1 cppthreads=1 Werror=0 -j2
```
Output in build/test folder
![image](https://user-images.githubusercontent.com/24696403/55269556-1b8ab700-52d8-11e9-967b-d3bd2d974df2.png)

However in the previous version ( dev version with commit id:  
aa3fc130acb84f7262fa47d9b5107f0afcf105e0) building library with exactly same build command I can get benchamrking apps for each examples as follows: 

![image](https://user-images.githubusercontent.com/24696403/55269590-abc8fc00-52d8-11e9-9a29-13669bf9a4ad.png)

So in new version how can I run benchmark? 

Thanks.

**Comment by AnthonyARM** [comment]
benchmark_graph_* are a bit of hack, therefore they're only available as part of our [development master](https://review.mlplatform.org/#/admin/projects/ml/ComputeLibrary), we remove them before the release.
