### ISSUE TITLE
Understanding Tunerfile for CL

### ISSUE THREAD

**Issue by krgor** [ARM-software/ComputeLibrary#660]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
ACL Version: 19.02

**Platform:**

**Operating System:**
Android 7.1.1

I am trying to run various graph model with ACL (using Graph APIs). I am also using the tunerfile to optimize the performance.

What I observed is, if I don't provide a tunefile ACL creates a new tunerfile when I run it for the first time. This way I created 3-4 tunerfiles. Surprisingly with each of the tunerfile the time taken for one run() is different but remains constant with that tuner file. Then I compared the contents of tunerfile. It shows operation name and then 3 numbers like below,

depthwise_convolution_3x3_f32_150_150_32_150_150;1;6;2

Questions:
1. Why each time when new tunerfile is created has a different content (even after providing the same environment, cpu, gpu, graph etc)?
2. What does these 3 numbers provided in tuner file after the operation name mean?

Thanks & Regards,
KGor

**Comment by gmiodice** [comment]
Hi @krgor ,

and thanks for using ACL :)

ACL graph should not generate a tuner file if not explicitly configured before running.

The way to create a new tuner file is through --tuner-file option

i.e. graph_mobilenet --target=cl --enable-tuner --tuner-file=acl_tuner.csv

If --tuner-file were not provided, you should not have any new tuning file.

Regarding the question concerning the "result of tuner is not always the same", I might have two answers.

1. If the test condition were not stable (same GPU frequency for the whole duration of the test), you could have different results for the tuning and this could not be optimal as well
2. Few functions could have similar performance using different tuning parameters

In the end, regarding the question: What are the three values reported in the tuning file, the answer is: is the optimal LWS (Local Workgroup Size) to use for that specific OpenCL kernel

Hope this can help.
Regards,
Gian Marco

**Comment by krgor** [comment]
@gmiodice 
Thanks for your reply.

Maybe I didn't provided detailed information. When I mentioned "I don't provide tunerfile", I meant that I am providing --tuner-file=<file_path> option but the file is not present. So it will generate a new file. 

I am currently setting all the CPUs and GPU to a maximum and fixed frequencies. Maybe some other OS operations might be running in parallel and can cause environment a bit unstable. Do you have any suggestion to have more reliable setup while ACL is performing tuning?

Thanks,
KGor

**Comment by morgolock** [comment]
HI @krgor 

I'd suggest monitoring system load during tuning to see if there are other resource-hungry processes running at the same time the tuning. 

Double check power-saving is disabled or fixed, this might affect the frequency at runtime according to the current policy and influence the tuning process.

Hope this helps.
