### ISSUE TITLE
Import unpadded image into padded Image(cv::mat Import)

### ISSUE THREAD

**Issue by julled** [ARM-software/ComputeLibrary#662]
Output of 'strings libarm_compute.so | grep arm_compute_version':
arm_compute_version=v19.02 Build options: {'arch': 'armv7a', 'opencl': '0', 'neon': '1', 'examples': '1', 'asserts': '0', 'debug': '0', 'os': 'linux', 'Werror': '1'} Git hash=29f6788cee8881c5523a042a0ac9b0131d993768
Platform:
rpi 3
Operating System:
raspbian

**Problem description:**
I want to import a unpadded iamge into a padded acl image tensor, which got automatic padding configuration from a NEGaussian. Is there a possible way define something like linestride/step size for copyless import like opencv got in one of the cv::mat constructors(https://docs.opencv.org/3.4/d3/d63/classcv_1_1Mat.html#a51615ebf17a64c968df0bf49b4de6a3a) to avoid copying? I currently solved this problem by copying the cv mat (cv::copyMakeBorder) into a padded mat and import from there, but i want to avoid the copy.

For completion and future users here the code to import and export opencv mat to acl images:
```
//OpenCv => ACL
cv::Mat ocvImg = cv::imread(path2img,cv::IMREAD_GRAYSCALE);
cv::Mat ocvImgPadded;

// aclImg got configured with padding by acl runtime function (e.g. kernel-algorithms like gauss)
// can be skipped if image is not configured with padding 
cv::copyMakeBorder(ocvImg,ocvImgPadded,aclImg.info()->padding().top,aclImg.info()->padding().bottom,aclImg.info()->padding().left,aclImg.info()->padding().right,cv::BORDER_REPLICATE); 
aclImg.allocator()->import_memory(ocvImgPadded.data,ocvImgPadded.elemSize()*ocvImgPadded.rows*ocvImgPadded.cols);
```
```
//ACL => OpenCv 
size_t width  = aclImg->info()->dimension(0);
size_t height = aclImg->info()->dimension(1);
auto ptr_src = aclImg->buffer();
cv::Mat ocvImg(int(height), int(width), CV_8UC1, ptr_src, width+aclImg->info()->padding().right+aclImg->info()->padding().left);
```

**Comment by morgolock** [comment]
Hi @julled 

Import memory knows nothing about strides or padding, it's just a mechanism to make the tensor use memory which has been allocated at an earlier stage. 

In this case particular case, your ACL function requires padding for the border modes BORDER_REPLICATE and BORDER_CONSTANT, which in turn imposes the requirement of importing enough memory for the padding too.

Unless border mode is set to UNDEFINED in the ACL function (which would remove padding needs) I don't think there is a way get rid of the call to cv::copyMakeBorder(). If you change your border mode in ACL to UNDEFINED I think you could probably get rid of the call to cv::copyMakeBorder() and import directly ocvImg. Is this something that would work for you?

Hope this helps.

**Comment by julled** [comment]
okey thx this helps.
