### ISSUE TITLE
Variable size input

### ISSUE THREAD

**Issue by benv2k6** [ARM-software/ComputeLibrary#663]
Is it possible to make the inputs to have variable size in the run time api? Or must we reconfigure (init(),allocate() ) on every change of input shape?

I want to have an efficient way of init/allocate once, and then running the net many times with  different input sizes. (not configuring every cycle with different sizes)

**Comment by morgolock** [comment]
Hi @benv2k6 

If the input changes you have to call to configure() and allocate() as explained in the documentation: https://arm-software.github.io/ComputeLibrary/v19.02/architecture.xhtml#S4_1

It is not possible to call only once to configure() and allocate() if input's size changes.

**Comment by benv2k6** [comment]
Got it. Thanks for the quick reply
