### ISSUE TITLE
what's the relation between ACL and HCL

### ISSUE THREAD

**Issue by ysh329** [ARM-software/ComputeLibrary#664]
Hi, what's the relation between ACL and HCL, community version and commercial version? Thanks in advance.

**Comment by morgolock** [comment]
Hi @ysh329 

In order to help please tell me:
What is HCL ? what does it mean?

**Comment by ysh329** [comment]
@morgolock Excuse,_(:з」∠)_
![image](https://user-images.githubusercontent.com/7320657/55720688-ff9fb780-5a33-11e9-8ceb-0e568a8034f5.png)

HCL seems a quant. library like NNPack maybe, but i'm not sure.

**Comment by morgolock** [comment]
Hi @ysh329 

From your screenshot's diagram, I think HCL is just a placeholder (abstract concept) for any library with heterogeneous computing capabilities like ACL or OpenCV. I'm not sure though, I've never heard of HCL as a product.

**Comment by ysh329** [comment]
@morgolock THanks your reply.
