### ISSUE TITLE
Build Android Error: Could not find GCC/binutils

### ISSUE THREAD

**Issue by ysh329** [ARM-software/ComputeLibrary#666]
Hi, I wanna to cross compile an android version of ACL but failed with messages below:

```shell
# Below ACL root directory, scons installed, OS: Ubuntu14.04 docker
root@3b3374bcd1b5:/Users/ysh329/code/ComputeLibrary# $NDK/build/tools/make_standalone_toolchain.py \
  --arch arm64 \
  --install-dir $MY_TOOLCHAINS/aarch64-linux-android-ndk-r17b \
  --stl libc++ \
  --api 21
Could not find GCC/binutils: /Users/ysh329/code/android-ndk-r17b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64
```

Besides, I found docs about Build for Android as below(copy from docs):
> ## Building for Android
> For Android, the library was successfully built and tested using Google's standalone toolchains:
> - clang++ from NDK r17b for armv7a
> - clang++ from NDK r17b for arm64-v8a
> - clang++ from NDK r18-beta1 for arm64-v8.2-a with FP16 support
> Here is a guide to create your Android standalone toolchains from the NDK
> Download the NDK r17b from here: https://developer.android.com/ndk/downloads/index.html
> Make sure you have Python 2 installed on your machine.
> Generate the 32 and/or 64 toolchains by running the following commands:
>```shell
> $NDK/build/tools/make_standalone_toolchain.py --arch arm64 --install-dir $MY_TOOLCHAINS/aarch64-linux-android-ndk-r17b --stl libc++ --api 21
> $NDK/build/tools/make_standalone_toolchain.py --arch arm --install-dir $MY_TOOLCHAINS/arm-linux-android-ndk-r17b --stl libc++ --api 21
> ```

I wanna ask *what's the `$MY_TOOLCHAINS`* in command above? Is it from NDK?

Thanks in advance.

**Comment by morgolock** [comment]
Hi @ysh329 

`$MY_TOOLCHAINS` is an environment variable pointing to a folder on your system where you wish to install the standalone toolchains generated by the python script. You could replace it by just the absolute/relative path to a local folder.

Hope this helps.

**Comment by ysh329** [comment]
Thanks your reply, @morgolock 
However, I tried to `export` environment variable `MY_TOOLCHAINS` but failed, either.

```shell
root@3b3374bcd1b5:/Users/ysh329/code/ComputeLibrary# export MY_TOOLCHAINS=/Users/ysh329/tools/toolchains
root@3b3374bcd1b5:/Users/ysh329/code/ComputeLibrary# mkdir $MY_TOOLCHAINS/aarch64-linux-android-ndk-r17b
mkdir: cannot create directory '/Users/ysh329/tools/toolchains/aarch64-linux-android-ndk-r17b': File exists
root@3b3374bcd1b5:/Users/ysh329/code/ComputeLibrary# ls $MY_TOOLCHAINS/aarch64-linux-android-ndk-r17b
root@3b3374bcd1b5:/Users/ysh329/code/ComputeLibrary# $NDK/build/tools/make_standalone_toolchain.py \
  --arch arm64 \
  --install-dir $MY_TOOLCHAINS/aarch64-linux-android-ndk-r17b \
  --stl libc++ \
  --api 21
Could not find GCC/binutils: /Users/ysh329/code/snpe-repo/download/android-ndk-r17b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64
```

**Comment by morgolock** [comment]
Hi @ysh329 

Could you try something simple like:
`build/tools/make_standalone_toolchain.py --arch arm64 --install-dir ~/test_toolchain --stl libc++ --api 21`

The command above should work and create a new standalone toolchain in the folder `test_toolchain` in your home folder. If this doesn't work you NDK installation is broken and I'd suggest reinstalling the NDK.

**Comment by ysh329** [comment]
@morgolock Hi, I didn't find `make_standalone_toolchain` script

**Comment by morgolock** [comment]
Hi @ysh329 

The script is part of the NDK, please take a look at https://developer.android.com/ndk/guides/standalone_toolchain
