### ISSUE TITLE
npy Weights

### ISSUE THREAD

**Issue by GAnto85** [ARM-software/ComputeLibrary#667]
Hello! 
What is the best method to get trained weights for a net? I've seen ACL only accepts numpy files. Is there any automated way to get them?
I am interested at tiny yolo and U-Net.

**Comment by morgolock** [comment]
Hi @GAnto85 
Please take a look at the scripts folder distributed with `Arm Compute Library`, there you'll find two scripts to import the weights from trained models in caffe and tensorflow. For more details refer to the library documentation: https://arm-software.github.io/ComputeLibrary/v19.02/data_import.xhtml

Hope this helps.

**Comment by GAnto85** [comment]
Thank you ! I'm mostly interested in ONNX , do you know about any tool for compute library in order to read them? At the moment i'm taking a look at ARM NN , it seems to accept onnx files for the parsing.

**Comment by morgolock** [comment]
Hi @GAnto85 

Currently ACL does not support importing ONNX models. A workaround could be to import the ONNX model into tensorflow and then use one of the scripts I mentioned in my previous reply to get the npy files. (this is just an idea, I'm not sure it will work though)

ArmNN does support ONNX models.

Hope this helps.
