### ISSUE TITLE
CLScale for ResizeBilinear

### ISSUE THREAD

**Issue by ilous12** [ARM-software/ComputeLibrary#668]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
19.02
**Platform:**
android
**Operating System:**
android

**Problem description:**
I'm using acl and Tensorflow Lite for deeplabv3+ model.
I have a strange issue You will see below.

Tensorflow Lite scale output
![tflite](https://user-images.githubusercontent.com/3174693/55926676-33a1f500-5c4d-11e9-9d12-0427cb7ecafb.png)

compute library scale output
![armnn32](https://user-images.githubusercontent.com/3174693/55926698-44526b00-5c4d-11e9-925d-bb45b1e4143d.png)

When I scaled up from 1x9x9x21 to 1x257x257x21 by CLScale, output got a wrong area(blue area)
![armnn32](https://user-images.githubusercontent.com/3174693/55926764-9d220380-5c4d-11e9-9891-8f84095d132e.png)

 And It looks a little small.
![diff](https://user-images.githubusercontent.com/3174693/55926951-45d06300-5c4e-11e9-8fba-d4d04cd5c9b8.png)

my.hpp
`arm_compute::CLScale m_ResizeBilinearLayer;`

my.cpp
```
m_ResizeBilinearLayer.configure(&input, &output, arm_compute::InterpolationPolicy::BILINEAR,
                                    arm_compute::BorderMode::REPLICATE, arm_compute::PixelValue(0.f),
                                    arm_compute::SamplingPolicy::CENTER);
```

I notice that there is border. I changed border_size = 0, But not effected.
Please let me know if you have any tips. 

Thanks.

**Comment by AnthonyARM** [comment]
Could you please post more of your code ?
Are you sure you're not allocating the tensors *before* calling configure ? (In which case your image will be unpadded and therefore the border won't be processed)

**Comment by morgolock** [comment]
Hi @ilous12 

Do you see the same issue issue with NEScale ?

**Comment by ilous12** [comment]
Hi @AnthonyARM 
You will found belows
[code](https://github.com/ARM-software/armnn/blob/branches/armnn_19_02/src/backends/cl/workloads/ClResizeBilinearFloatWorkload.cpp)

@morgolock 
NeScale was same.

**Comment by morgolock** [comment]
Hi @ilous12 

The scale functions in ACL were implemented using OpenVX's scale as reference for validating the results: https://www.khronos.org/registry/OpenVX/specs/1.2/html/d1/d26/group__group__vision__function__scale__image.html

Probably the Tensorflow's function uses a slightly different reference for https://www.tensorflow.org/api_docs/python/tf/image/resize_bilinear

We need to look into this and compare for potential differences in both references causing these mismatches you observe.

**Comment by morgolock** [comment]
Hi @ilous12 

Could you please try using  arm_compute::SamplingPolicy::TOP_LEFT when you call ACL's function configure?

**Comment by morgolock** [comment]
Closing by inactivity, please reopen if you still need support.
