### ISSUE TITLE
how to run an example on the arm-compute-library built for bare metal on windows?

### ISSUE THREAD

**Issue by irkingmaker** [ARM-software/ComputeLibrary#669]
**Platform:** armv7a

**Operating System:**
windows 10

**Problem description:**

**Comment by morgolock** [comment]
Hi @irkingmaker 

Examples are disabled for the bare_metal target because they require many system calls only present in operating systems.

Please take a look at the documentation for more details: https://arm-software.github.io/ComputeLibrary/v19.02/index.xhtml#S3_4_bare_metal

**Comment by irkingmaker** [comment]
Thanks for the help.
Presently i am trying to build link independent binary of the arm_compute library using scons and arm-none-eabi-g++(version 8). The scons command is used for armv7, cortex-a9. I am facing the following issues-
1.(.text._ZN11arm_compute16NEConvolution3x3D2Ev[_ZN11arm_compute16NEConvolution3x3D5Ev]+0x30): undefined reference to `vtable for arm_compute::INESimpleFunction'
2.
(.text._ZN11arm_compute19NEConvolutionSquareILj5EED0Ev[_ZN11arm_compute19NEConvolutionSquareILj5EED5Ev]+0x1c): undefined reference to `arm_compute::TensorAllocator::~TensorAllocator()

**Comment by morgolock** [comment]
Hi @irkingmaker 

This suggests that the linker can't find the symbols mentioned above in your comment, these missing symbols are part for the runtime library (  https://arm-software.github.io/ComputeLibrary/v19.02/architecture.xhtml#S4_1 ).

Could you please share the commands for building the library and your code using it?

**Comment by irkingmaker** [comment]
Please find the attachments for the scons script(SConstruct.txt), linker description(CoreML.ld.txt) and the compilation issues i am facing. The compilation issues are present in error.txt. I have edited the code of neon_cnn example a little and saved it as TestCtrl_RunArmCompute.cpp.
[Sconstruct.txt](https://github.com/ARM-software/ComputeLibrary/files/3111054/Sconstruct.txt)
[coreML.ld.txt](https://github.com/ARM-software/ComputeLibrary/files/3111058/coreML.ld.txt)
[error.txt](https://github.com/ARM-software/ComputeLibrary/files/3111061/error.txt)

**Comment by morgolock** [comment]
Hi @irkingmaker 

I'd try to fix the first linker error:

![linkerror](https://user-images.githubusercontent.com/5577511/56672156-d62a9100-66ad-11e9-9202-310df469d28e.png)

From your build command:
`arm-none-eabi-g++ -o CoreML_Binary.elf -Wl,-no-undefined --verbose -mcpu=cortex-a9 -mfloat-abi=hard -Bstatic -Ttext=0x7DA0000 -e_main_cust -ffunction-sections -fdata-sections -Xlinker --gc-sections --specs=nosys.specs "-LLibs-Wl,--start-group -lgcc -lc -lg -lm -lstdc++ -larm_compute_core-static -larm_compute-static -Wl,--end-group" -Wl,-TcoreML.ld begina.o Misc.o TestCtrl_RunArmCompute.o`

It seems both `TestCtrl_RunArmCompute.o` and `Misc.o` were built with different setting from the ones you use for `CoreML_Binary`

Hope this helps.

**Comment by irkingmaker** [comment]
I was previously using version 7 arm-none-eabi compiler. But after using version 8, the first linker error is solved. I am still facing issues with the other errors.
[New Text Document (2).txt](https://github.com/ARM-software/ComputeLibrary/files/3116690/New.Text.Document.2.txt)

**Comment by irkingmaker** [comment]
The undefined reference errors were because of inappropriate order of linking of the libraries. In scons, i was not able to change the order of linkage of the libraries. Hence, by using make, I was able to build the library.
Now, while i am going through the example code of neon_cnn.cpp. I am not able to figure out how to initialize the layers with custom weights generated from a trained model?

**Comment by morgolock** [comment]
Hi @irkingmaker 

Good to know you fixed the linker errors, unfortunately for some toolchains the order in which you list the dependencies matters. 

In order to help you, please provide more context for your question. Why are you not able to initialise the layers? What's actually the problem?

**Comment by irkingmaker** [comment]
I am not able to understand how are weights inferred from a model loaded into layers in arm compute library. For example, in neon_convolution in conv3x3.configure-it is loading gaussian3x3 weights defined in the same file. How do we load weights from a different file ?

**Comment by morgolock** [comment]
Hi @irkingmaker 

The example you mention, `examples/neon_convolution.cpp`, does not load weights. It's just a 2D convolution where you can specify the transformation.

I'd suggest you take a look at `examples/neon_cnn.cpp`, although in this example the weights are not loaded from a file. You should copy the values from your weights file to the weights tensor after the call to `allocate()`.

**Comment by irkingmaker** [comment]
How do we copy the values from my weights file to weights tensor?

**Comment by morgolock** [comment]
Hi @irkingmaker 

Please take a look at the code examples showing how to copy data from/to ACL's tensors:
https://arm-software.github.io/ComputeLibrary/v19.02/architecture.xhtml#S4_6_4_working_with_objects

This assumes you have already loaded your weights from a file into a buffer.

**Comment by irkingmaker** [comment]
How do i load the weights from .npy or .csv file ? i am not able to find the documentation or example to load the weights from .npy or .csv file to a convolution layer(or any other function)?
-I have got the .npy files from the python script provided by ACL for conversion of a pretrained model into .npy files.

**Comment by morgolock** [comment]
Hi @irkingmaker 

You should use `libnpy` to read the data from a file into a buffer and then copy that to an ACL tensor. 

Take a look at libnpy https://github.com/llohse/libnpy and ACL NPYLoader: https://github.com/ARM-software/ComputeLibrary/blob/master/utils/Utils.h#L318

**Comment by morgolock** [comment]
Closed by inactivity, reopen it or open a new issue if in need of support.
