### ISSUE TITLE
Bug in CLBatchToSpaceLayerKernel.cpp?

### ISSUE THREAD

**Issue by lwu025** [ARM-software/ComputeLibrary#670]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

**Platform:**aarch64

**Operating System:**linux

**Problem description:**
Hi, I'm looking at the implementation of BatchToSpaceLayer and found that there is probably a bug in your code.

In: ComputeLibrary/src/core/CL/kernels/CLBatchToSpaceLayerKernel.cpp 
At Line 70
I believe that the "block_shape_x"  should be "block_shape_y" if you did not assume that the block_shape is square.

**Comment by morgolock** [comment]
Hi @lwu025 

Thanks for reporting this, it does look like a bug. I'll take a closer look at the code and the validation tests.

**Comment by morgolock** [comment]
Hi @lwu025 

I've created a patch to fix this and added test cases to exercise the path where blockx!=blocky : https://review.mlplatform.org/#/c/ml/ComputeLibrary/+/1017/

**Comment by morgolock** [comment]
The patch has been merged to the main development branch. Thanks for reporting this.
