### ISSUE TITLE
FlattenLayer giving incorrect results for 3D output

### ISSUE THREAD

**Issue by pranathibl** [ARM-software/ComputeLibrary#672]
Hi,

I am trying to give a 3D input [w,h,c] to flatten layer and I configured the output tensor shape as [1, 1, w*h*c]. I am getting incorrect results.

Does flatten layer accept output tensor of 3D shape? It is not throwing any error either.

Thanks,
Pranathi

**Comment by gmiodice** [comment]
Hi @pranathibl ,

the output shape for flatten layer should only be [whc]. However, from the source we should also able to throw an error in case of wrong output shape. Could you share the code are you using for a better understanding?

Thanks,

**Comment by morgolock** [comment]
Closed by inactivity. Reopen if help is needed.
