### ISSUE TITLE
NEActivationLayer gives nan values as output

### ISSUE THREAD

**Issue by pranathibl** [ARM-software/ComputeLibrary#674]
Hi,

NEActivationLayer with activation function 'LOGISTIC' is giving NaN values for the following input.
[sigmoid_tap.txt](https://github.com/ARM-software/ComputeLibrary/files/3146582/sigmoid_tap.txt)

can you please let me know why is this happening?

Thanks,
Pranathi

**Comment by morgolock** [comment]
Hi @pranathibl 

Could you please share the code calling to configure() and run() ?

**Comment by pranathibl** [comment]
Hi @morgolock 

Find the attachment for source code.
[SigmoidLayer.cpp.zip](https://github.com/ARM-software/ComputeLibrary/files/3200921/SigmoidLayer.cpp.zip)

Thanks.

**Comment by morgolock** [comment]
Hi @pranathibl 

I've just tried your test with an input file of 1500 x 0.1f and the ouput is 1500 x 0.524979f. I cannot see any nan in the output.

Would you please attach the file containing the input values you feed to the test?

**Comment by morgolock** [comment]
Hi @pranathibl 

I've managed to reproduce the nan output using the input values in `sigmoid_tap.txt`, however I wanted to ask you if this is a real use case for you and you will be expecting to call the ActivationFunction with values like `-110.563`. 

We only validate LOGISTIC with input values in the range [-40.f, 40.f], so yes, if you feed smaller/bigger values you might experience some problems.

Are the values from `sigmoid_tap.txt` coming from a real use case or network?
