### ISSUE TITLE
clconvolution benchmarking

### ISSUE THREAD

**Issue by uu-praveeng** [ARM-software/ComputeLibrary#675]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v19.02 Build options: {'embed_kernels': '1', 'arch': 'arm64-v8a', 'opencl': '1', 'neon': '0', 'debug': '0', 'os': 'linux'}
**Platform:**
HiKey 960 (ARM Mali G71 MP8)
**Operating System:**
Description:	Ubuntu 16.04.6 LTS

I have created a test setup having only the Convolution layer which has below dimensions 
input : 12x12x1920
filter : 3x3x1920x960, pad(1,1),stride(1,1)
output: 12x12x960

When I benchmarked the convolution it is  taking almost 100 ms . Which appears to be too huge on a GPU. I have attached the test setup for your reference. 
[ClConv.cpp.tar.gz](https://github.com/ARM-software/ComputeLibrary/files/3147689/ClConv.cpp.tar.gz)

Could you confirm whether this is the expected profile numbers/behaviour on Hikey-960.

Thank you,
Praveen.

**Comment by morgolock** [comment]
Hi @uu-praveeng 


Where does this workload come from? From what network? 

What's your baseline? What are your time expectations for this workload?

**Comment by morgolock** [comment]
Closing by inactivity, if reopening please provide the additional information I mentioned in my previous comment.
