### ISSUE TITLE
hgemm_24x8 calls get_cpu_model in its constructor

### ISSUE THREAD

**Issue by alankelly** [ARM-software/ComputeLibrary#676]
arm_compute_version=v0.0-unreleased Build options: {} Git hash=dc5d34319a673f6cbcd346a0c7046fb7fd0106ec

Platform: Cortex A55/A75 Snapdragon 845

Operating System: Android

Class hgemm_24x8 in file a64_hgemm_24x8.hpp calls get_cpu_model in its constructor. This accounts for approximately one third of then runtime of a hgemm kernel and profiling shows that a lot of time is spent in various libc functions due to this. Commenting these lines reduces runtime by a third.

Is it possible to cache the result of this function call or to call this function at a higher level? Currently hgemm is slower than sgemm, while we would expect it to be at least twice as fast.

Thanks!

**Comment by morgolock** [comment]
Hi @alankelly 

The constructor takes a pointer to a CPUModel class as shown in:
https://github.com/ARM-software/ComputeLibrary/blob/master/src/core/NEON/kernels/arm_gemm/kernels/a64_hgemm_24x8.hpp#L69

And then calls into get_cpu_model() which has already been initialised during the Scheduler instantiation: https://github.com/ARM-software/ComputeLibrary/blob/master/src/core/CPP/CPPTypes.cpp#L70

The method get_cpu_model() of CPUInfo should not call any libc code, this is done at an earlier stage in in the scheduler's constructor as can be seen in: https://github.com/ARM-software/ComputeLibrary/blob/master/src/runtime/IScheduler.cpp#L34

You should not see any libc calls in hgemm_24x8's constructor.

Hope this helps.

**Comment by morgolock** [comment]
Please reopen if need further explanation.

**Comment by alankelly** [comment]
Hi @morgolock 
Apologies for the delay in responding. Thanks for getting back to me. I'll run the streamline profiles again with and without these lines commented to confirm that the problem doesn't come from here.
Thanks
