### ISSUE TITLE
Error Running Cross-Compiled Executable: version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by noah-curran** [ARM-software/ComputeLibrary#678]
I am cross-compiling from Ubuntu 18.04 to Rasbian 9.6 and receive the following error when I attempt to run the example graph_alexnet executable:

`./build/examples/graph_alexnet: /lib/arm-linux-gnueabihf/libm.so.6: version 'GLIBC_2.27' not found (required by ./build/examples/graph_alexnet)`

Typing `ldd --version` into both environments, I get 2.27 for Ubuntu and 2.24 for Rasbian, so this is clearly where the issue lies. What do I need to do to compile correctly to avoid this error? This is my compile command I've used: `scons neon=1 opencl=0 -j4`.

This is my first time cross-compiling, so I apologize if there is something obvious I am missing.

**Comment by morgolock** [comment]
Hi @noah-curran 

It seems you're building the example with a newer toolchain than the one installed on your target system (Rasbian). What version of gcc do you use to cross-compile ACL examples?

You would have to either rebuild the examples with the same toolchain version installed in Rasbian or upgrade the OS to support a newer version of gcc.

I think if you cross-compile using gcc 4.9 the example would run fine. Please take a look at the documentation for more details on the toolchains we have tested :
https://arm-software.github.io/ComputeLibrary/v19.02/index.xhtml#S3_2_linux

**Comment by noah-curran** [comment]
I am currently using gcc 7.4, so that is likely the issue. Following your advice, I've tried installing 4.9 by using `sudo apt-get install g++-4.9-arm-linux-gnueabihf`, but I am not having luck with that. I was able to get `sudo apt-get intall gcc-4.8`, but not `udo apt-get install g++-4.8-arm-linux-gnueabihf`. Perhaps it is because I am running Ubuntu 18.04 rather than 16.04. Are you aware of a workaround for this?

**Comment by morgolock** [comment]
Hi @noah-curran 

You could just download the toolchain from https://releases.linaro.org/components/toolchain/binaries/4.9-2016.02/

Then when building make sure you point $PATH to the place where you have installed the toolchain.
`PATH=$PATH:/home/noah-curran/toolchains/gcc-linaro-4.9-2016.02-x86_64_aarch64-linux-gnu/bin scons neon=1 opencl=0 -j4`

**Comment by noah-curran** [comment]
That did the trick! Thanks for your help. I'll close this issue.
