### ISSUE TITLE
ARM_GEMM can produce incorrect results due to uninitialized memory

### ISSUE THREAD

**Issue by alex-xnor** [ARM-software/ComputeLibrary#679]
ARM compute version: 19.02

Platform: NVIDIA TX3

Operating system: Ubuntu 16.04.6 LTS

Problem description:

ARM_GEMM can produce incorrect results for matrix multiplications due to uninitialized memory. At least one instance is at

https://github.com/ARM-software/ComputeLibrary/blob/29f6788cee8881c5523a042a0ac9b0131d993768/src/core/NEON/kernels/arm_gemm/transforms/a64_interleave_8way_32bit.hpp#L38

where `zerobuff` is named as if it's a buffer full of zeroes, but is actually a buffer full of uninitialized memory. I have witnessed this cause problems in practice but I am at present unable to provide a minimal example demonstrating the erroneous behavior. I can confirm that initializing this `zerobuff` to all zeroes does fix the issue I was experiencing, but I would not be surprised if this same issue existed elsewhere inside of ARM Compute Library in code paths I happen to not be hitting.

**Comment by alex-xnor** [comment]
Also worth noting, that #582 found a different bug on the exact same line even. It may be worthwhile to review some of the logic in these functions with some extra care since now two bugs have been found in the same place, so there may be more lurking that have not yet been discovered.

**Comment by GeorgeARM** [comment]
Hello @alex-xnor ,

Thanks for reporting that. Will fix the issue. We have a lot of unit and integration tests that cover all our kernels but we haven't had any validation issues so far. We will review our kernels and our static code analysis space and try to avoid such issues in the future.

**Comment by morgolock** [comment]
Hi @alex-xnor 

A fix has been merged to the main dev branch. This is the link to the patch and code review https://review.mlplatform.org/#/c/ml/ComputeLibrary/+/1211/

Thanks @GeorgeARM 

Closing this as it's been resolved.
