### ISSUE TITLE
ACL LSTM API Usage

### ISSUE THREAD

**Issue by nhkrishna** [ARM-software/ComputeLibrary#680]
Hi,

I am trying to create a basic LSTM layer by using this [article](https://colah.github.io/posts/2015-08-Understanding-LSTMs/) as a reference. 
I have few queries regarding usage of the NELSTM layer API as below:

1. Above mentioned article explaining LSTM cell with four gate layers as follow- **forget gate (ft), input gate (it), input candidate gate (Ct) and output gate (Ot)**. Here each gate has its own input weight files(**4**) and recurrent weight files(**4**). But ACL LSTM layer API has **three** input weight files saying **forget, cell, output** weight files. In this case what cell weight file refers to?
     - If i consider ARM  **input_to_cell_weights** as accumulated weight files of **it** and **Ct** then size of input to cell weight will be 2D tensor with [input_sizex2,  num_units] but LSTMLayer.h file describes size cell weight as [input_size,  num_units]. Could you please describe what exactly input cell weight file refers to?

2. What is scratch buffer in 13th argument?. I am not using Coupled Input and Forget Gate (CIFG) in my implementation, so can I use NULL instead of passing any buffer.

Thanks,
Hari

**Comment by nhkrishna** [comment]
Hi @morgolock,

Is there any update on this?

Thanks,
Hari

**Comment by GeorgeARM** [comment]
The API that we follow is the AnroidNN API specification. More details can be found here:
https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0ad0377e8c305e596fb7f64ff896671fc5

Hope this helps. If your questions persist then we will be happy to help you

**Comment by nhkrishna** [comment]
Thanks for your response @GeorgeARM .
I will follow your reference and get back to you.

**Comment by nhkrishna** [comment]
Hi @GeorgeARM ,

I had gone through the ACL LSTM API to solve sequence classification problem with no peep hole optimization and no CIFG.  I am facing few issues in using the API for this problem.

Below example describes expected input, output and weight file dimensions to the LSTM layer used in the sequence classification problem in general:
1. **input_size** : _number of features that are observed at the each time step_ x _sequence length_ -- 3x200
2. **output_size** : _number of LSTM units_ -- 100
3. **input_to_*_weights** : _number of features that are observed at the each time step_ x _number of LSTM units_ -- 3x100(Note:* represents input/forget/cell/output gate)
4. **recurrent_to_*_weights** : _number of LSTM units_ x _number of LSTM units_ -- 100x100 
5. ***_gate_bias** -  _number of LSTM units_ -- 100
6. *_**_state_in** -  _number of LSTM units_ x batch_size_ -- 100x1
7. *_**_state_out** -  _number of LSTM units_ x batch_size_ -- 100x1

It is unclear how to configure the dimensions for the **input_size** , **batch_size** and **input_to_*_weights** in LSTM configure API specified in the NELSTMLayer.h file. Below are the cases with various input_size dimensions. 

- **Case1** - 
Could the input size be **number of features that are observed at the each time step x sequence length [3x200]** ? If Yes, then we weights sizes during configuration will over-shooted as shown below which may not result in the correct output.

ACL tensor shape of **input_to_*_weights** is specified as **[input_size, num_units] [3x200,100]**  then its size become  **[number of features that are observed at the each time step x sequence length x number of LSTM units] [3x200x100]** which is not true from the above mentioned example dimensions

-  **Case2** - 
Could the input size be **number of features that are observed at the each time step(3)**?If Yes, then we weights sizes during configuration will be same as in point 3 .

ACL tensor shape of **input_to_*_weights** is specified as **[input_size, num_units] [3,100]**  then its size become  **[number of features that are observed at the each time step x number of LSTM units] [3x100]** which is true from the above example dimensions 

**With the case 2, we could see that we are not handling the sequence length attribute of LSTM**. 

Could you let us know the appropriate usage of LSTM API with the given dimensions . You could disable peephole optimization and CIFG for this.

Any help would be highly appreciated.

I have [attached](https://drive.google.com/open?id=13FOn5FiKbQtzSYzdoVI4GFVLmJkHuavK) standalone LSTM setup that I am working on for your reference.

Thanks,
Hari

**Comment by nhkrishna** [comment]
Is there any update on this?

**Comment by nhkrishna** [comment]
Finally i'm able use the ACL LSTM API. The fact is that ACL LSTM API supports only for sequence length=1. I'm explicitly running the LSTM API for sequence length time by copying the previous time step outputs to the current time step. 
Is there any reason for not supporting sequence length parameter as like [CUDNN API](https://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#cudnnRNNForwardInference) supports?

**Comment by GeorgeARM** [comment]
Hello @nhkrishna,

Yes its something that we are planning to do. We follow the AndroidNN spec, as you can see there are such [operators](https://developer.android.com/ndk/reference/group/neural-networks.html#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0aaf30e491ad0b1fc7602cbde695b2c859). We are planning to add them in future releases.

**Comment by nhkrishna** [comment]
Hi @GeorgeARM,

I have seen [operators](https://developer.android.com/ndk/reference/group/neural-networks.html#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0aaf30e491ad0b1fc7602cbde695b2c859) in AndroidNN spec. It has support for [sequence length](https://developer.android.com/ndk/reference/group/neural-networks.html#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0aaf30e491ad0b1fc7602cbde695b2c859) and [Bi-Directional LSTMs](https://developer.android.com/ndk/reference/group/neural-networks.html#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0a492a71cb7aa50b9a1a834a3cb269d778).

Can i expect these features to be supported in next release?

Thanks,
Hari

**Comment by GeorgeARM** [comment]
Hello @nhkrishna,

Yes these are part of AndroidNN spec but they low at the moment in priority. Is this something of interest for you? Do you have network that utilize those?

Thanks,
George

**Comment by nhkrishna** [comment]
Hi @GeorgeARM,

Thanks for your response.
I am using LSTM Networks with the combination of  input-->LSTM layer-->FC-->Softmax layers to process the vector sequence data. Also we can use LSTM layers along with convolution layers to process image sequence data.
Currently ACL supports single time step data prediction. So we are running the ACL API for sequence length times. Its good have the support for **sequence length** as an API argument so that API will capable of supporting other variants of LSTM such as **Bi directional LSTMs**.

Thanks,
Hari
