### ISSUE TITLE
mobilenet QASYMM8 example

### ISSUE THREAD

**Issue by peter197321** [ARM-software/ComputeLibrary#681]
Where the example which is linked inhere [mobilenet QASYMM8 example](https://github.com/ARM-software/ComputeLibrary/issues/378#issuecomment-370752717) can be found?

**Comment by morgolock** [comment]
Hi @peter197321 
This is the file you're looking for:
https://github.com/ARM-software/ComputeLibrary/blob/master/examples/graph_mobilenet.cpp

Please also take a look at the documentation on how to run these examples:
https://arm-software.github.io/ComputeLibrary/v19.02/data_import.xhtml#validate_examples
