### ISSUE TITLE
Trying to use depthwise convolution yields insufficient padding

### ISSUE THREAD

**Issue by paulgheorghecristian** [ARM-software/ComputeLibrary#687]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
18.02
**Platform:**
Raspbery PI 3b+
**Operating System:**
Raspbian GNU/Linux 9.8 (stretch)

**Problem description:**
When I try to convert TF Lite's depthwise conv into CL depthwise conv, I get the insufficient padding error. This is because of  NEDirectConvolutionLayerOutputStageKernel member in NEDepthwiseConvolutionLayer. Is there anyway around this padding error? Or how should I perform the padding?
The error is:
what():  in validate_and_configure_window src/core/NEON/kernels/NEDirectConvolutionLayerOutputStageKernel.cpp:149: Insufficient Padding!

Thank you!

**Comment by morgolock** [comment]
Hi @paulgheorghecristian 

Could you please share the code setting up the functions as well as the shapes of the tensors?

**Comment by paulgheorghecristian** [comment]
Hello and thank you again for responding. This is my code and my tensors:

`    arm_compute::Scheduler::get().set_num_threads(4);

    arm_compute::Tensor input_arm;
    arm_compute::Tensor weights_arm;
    arm_compute::Tensor bias_arm;
    arm_compute::Tensor output_arm;
    arm_compute::Allocator allocator{};

    arm_compute::NEDepthwiseConvolutionLayer3x3 conv_arm{};

    arm_compute::TensorInfo output_info(arm_compute::TensorShape(
            output->dims->data[3],
            output->dims->data[2],
            output->dims->data[1],
            output->dims->data[0]), 1, arm_compute::DataType::F32);

    output_info.set_data_layout(arm_compute::DataLayout::NHWC);

    arm_compute::TensorInfo input_info(arm_compute::TensorShape(
									input->dims->data[3],
									input->dims->data[2],
									input->dims->data[1],
									input->dims->data[0]), 1, arm_compute::DataType::F32);

    input_info.set_data_layout(arm_compute::DataLayout::NHWC);
    arm_compute::TensorInfo weights_info(arm_compute::TensorShape(filter->dims->data[3],
                                                   filter->dims->data[1],
                                                   filter->dims->data[2]), 1, arm_compute::DataType::F32);

    arm_compute::TensorInfo bias_info(arm_compute::TensorShape(filter->dims->data[3]),
                                                              1, arm_compute::DataType::F32);

    output_arm.allocator()->init(arm_compute::TensorInfo(output_info));
    input_arm.allocator()->init(arm_compute::TensorInfo(input_info));
    weights_arm.allocator()->init(arm_compute::TensorInfo(weights_info));
    bias_arm.allocator()->init(arm_compute::TensorInfo(bias_info));


    input_arm.allocator()->import_memory((void *)GetTensorData<float>(input), input_info.total_size());
    weights_arm.allocator()->import_memory((void *)GetTensorData<float>(filter), weights_info.total_size());
    bias_arm.allocator()->import_memory((void *)GetTensorData<float>(bias), bias_info.total_size());
    output_arm.allocator()->import_memory((void *)GetTensorData<float>(output), output_info.total_size());

    conv_arm.configure(&input_arm, &weights_arm, &bias_arm, &output_arm, arm_compute::PadStrideInfo(params->stride_width,
                                                            params->stride_height,
                                                            data->padding.width, data->padding.height, arm_compute::DimensionRoundingType::CEIL), 
                                                            1,arm_compute::ActivationLayerInfo(arm_compute::ActivationLayerInfo::ActivationFunction::LU_BOUNDED_RELU,
                                                            output_activation_max, output_activation_min));

    input_info.set_num_channels(4);
    weights_info.set_num_channels(3);
    output_info.set_num_channels(4);
    bias_info.set_num_channels(1);

    conv_arm.run();
`
Tensors:

input: 32 112 112 1 (NHWC)
output: 32 112 112 1 (NHWC)
weights: 32 3 3 (HWC)
bias: 32

**Comment by morgolock** [comment]
Hi @paulgheorghecristian 

Please update to the latest release 19.05

The api for importing memory has changed slightly: https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/TensorAllocator.h#L107

**Comment by GeorgeARM** [comment]
Hello @paulgheorghecristian,

Functions can add padding to tensors to enable better vectorization. What happens here is that you use the `import_memory` API to import external memory. This will lock up your tensors and won't allow functions to extend the padding requirements on tensors which leads to the error that you face.
If you try the latest ACL you won't have any issues as I think we removed the padding requirements for `NEDepthwiseConvolutionLayer3x3`.
In general though, try to import memory after configuring all you functions and before running. Then you can check if your tensors require padding (you can see that through the TensorInfo::padding() interface) and act accordingly, meaning you might need to allocate larger memory on your side.

**Comment by paulgheorghecristian** [comment]
Thank you for your help, I will try your suggestion!

**Comment by GeorgeARM** [comment]
I suppose [this](https://github.com/tensorflow/tensorflow/pull/28737/files#diff-00fd549df24185f894b50fadce0bd1cd) might help you
