### ISSUE TITLE
GEMM beta=0 special case is not honored

### ISSUE THREAD

**Issue by alex-xnor** [ARM-software/ComputeLibrary#690]
ARM compute version: 19.02

Platform: NVIDIA TX3

Operating system: Ubuntu 16.04.6 LTS

Problem description:

The reference implementation of GEMM includes a special case for BETA=0 (these are lines 276&ndash;294 of `sgemm.f` from reference BLAS 3.8.0):

```fortran
*
*     And if  alpha.eq.zero.
*
      IF (ALPHA.EQ.ZERO) THEN
          IF (BETA.EQ.ZERO) THEN
              DO 20 J = 1,N
                  DO 10 I = 1,M
                      C(I,J) = ZERO
   10             CONTINUE
   20         CONTINUE
          ELSE
              DO 40 J = 1,N
                  DO 30 I = 1,M
                      C(I,J) = BETA*C(I,J)
   30             CONTINUE
   40         CONTINUE
          END IF
          RETURN
      END IF
```

Namely, if BETA is zero, the output matrix is zeroed rather than scaling the existing output matrix, which could yield a different result if e.g. the output matrix contained infinities or NaNs.

Other implementations of BLAS also contain this same special case, e.g. OpenBLAS (with a little bit of indirection: [1](https://github.com/xianyi/OpenBLAS/blob/ca8d8835f535515c2bdadf4e8198a3932e060993/interface/gemm.c#L454), [2](https://github.com/xianyi/OpenBLAS/blob/ca8d8835f535515c2bdadf4e8198a3932e060993/driver/level3/level3_thread.c#L291-L299), [3](https://github.com/xianyi/OpenBLAS/blob/ca8d8835f535515c2bdadf4e8198a3932e060993/kernel/generic/gemm_beta.c#L52)) has some explicit code to handle this too. So, I think it is fair to say that this is something that GEMM is specified to handle in this way.

ARM Compute Library, so far as I can tell, does not have this special case. At least with these parameters:

    trans_a=false
    trans_b=false
    m=1
    n=1024
    k=256
    nbatch=1
    nmulti=1
    alpha=1
    lda=256
    a_batch_stride=1
    a_multi_stride=256
    ldb=1024
    b_multi_stride=1024
    beta=0
    ldc=1024
    c_batch_stride=1
    c_multi_stride=1024

(Which in my environment, seems to choose the implementation in `src/core/NEON/kernels/arm_gemm/gemv_native_transposed.hpp` dispatching to `src/core/NEON/kernels/arm_gemm/kernels/a64_sgemv_trans/generic.cpp`)

If C starts out being full of NaNs, then after the GEMM operation, it will still be full of NaNs. But if I zero out C first, then I get the right answer. This is inconsistent with the reference BLAS and with other implementations of BLAS.

**Comment by morgolock** [comment]
Hi @alex-xnor 

You could take a look at our C++ reference for GEMM here: https://github.com/ARM-software/ComputeLibrary/blob/master/tests/validation/reference/GEMM.cpp


D = [alpha * A * B + beta * C]

If A, B or C are filled with nans then I would expect undefined behavior.

Can't you just initialise C to all 0s before calling NEGEMM? Why are you calling GEMM with C is filled with nans?

**Comment by alex-xnor** [comment]
I can initialize C to all-zeroes before calling NEGEMM, and that's my workaround. If NEGEMM just works differently from BLAS GEMM, that's fine, it was just unexpected. It looks like nobody is actually claiming compatibility with BLAS, so maybe it is unreasonable for me to port these expectations over. But, as a user, I expected NEGEMM to have this beta=0 special case, because it's part of the BLAS GEMM reference implementation, and they're both called "GEMM" so I would expect them to act the same.

**Comment by alex-xnor** [comment]
And the reason it's filled with NaNs is because C was straight from a memory allocator that didn't zero out the memory, and the data that happened to be in there contained some NaNs and infinities among other garbage. In our code we assume that it's safe to call GEMM with beta=0 and C pointed to such a buffer; my workaround for now is to explicitly zero it out for NEGEMM only.

**Comment by morgolock** [comment]
Hi @alex-xnor 

In your particular case when beta is 0, would it not make sense to just pass nullptr as C when calling negemm_function.configure() ?

**Comment by morgolock** [comment]
Hi @alex-xnor 
Passing C = nullptr to the configure() method might be faster than filling C with 0s.
Closing this issue, please reopen if you need help.
