### ISSUE TITLE
[Question] Community for asking developers

### ISSUE THREAD

**Issue by vswdigitall** [ARM-software/ComputeLibrary#691]
Hi ACL,

Arm Compute Library is excellent software!
But where i can ask developers for support?

Best regards, Viktor.

**Comment by gmiodice** [comment]
Hi Viktor,

many thanks for your message and...using Arm Compute Library! 

For developers support, we have two main channels:

1. **GitHub**: mainly used for issues
2. **Public mailing list** (https://lists.linaro.org/mailman/listinfo/acl-dev) for generic discussions/requests

Hope this can help.

Regards,
Gian Marco
