### ISSUE TITLE
[Question] Dynamically create roi of CLImage for optFlow

### ISSUE THREAD

**Issue by vswdigitall** [ARM-software/ComputeLibrary#692]
Hi ACL,

ACL 19.02, built for CL, aarch64, FriendlyArm nanopi NEO4.

Now i am using optFlow for whole frame(330x180) for winsize=31, 5 iters. And it is not fast (20-60ms).

How i can dynamically create roi of input images(prevImage, image and pyramids) for speed up optFlow?
And commonly how to create/free CLImage on runtime?

Best regards, Viktor.

**Comment by morgolock** [comment]
Hi @vswdigitall 

I think you could try CLSlice to get the region of interest from the input image and send only that to the rest of the processing pipeline: gaussian pyramid and optical flow.

Please take a look at https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/CL/functions/CLSlice.h 

Hope this helps.

**Comment by vswdigitall** [comment]
Thanks. Will try.

**Comment by vswdigitall** [comment]
How i can set Coordinates?

Have tried starts = Coordinates{ 0, 0 } and ends = Coordinates{ 150, 100 }. I assume that roi is { 0, 0, 150, 100 }.
I am right?

And how to dynamically change size of output Tensor?
Now the result is same as input Tensor after slice.run().

**Comment by morgolock** [comment]
Hi @vswdigitall

Your slices start and end look good.

To resize the slice you'll need to use CLScale, if the sizes of the input/output change at runtime you'll need to call cl_scale_function.configure(new size) each time any of the sizes change.

**Comment by vswdigitall** [comment]
Thanks. Will try.
