### ISSUE TITLE
[Question] HOG/SVM for OpenCV C-SVC model (non-linear) with kernel RBF

### ISSUE THREAD

**Issue by vswdigitall** [ARM-software/ComputeLibrary#693]
Hi ACL,

ACL 19.02, built for CL, aarch64, FriendlyArm nanopi NEO4.

I have learned model with OpenCV HOG/SVM. There are 2500 support vectors and decision functions. I am using RBF(non-linear) kernel, 2 classes.

How i can use model with ACL HOG/SVM?

Best regards, Viktor.

**Comment by morgolock** [comment]
Hi @vswdigitall 

We have no HOG examples in ACL.

For a general idea on how to use HOG in ACL I'd suggest you take a look at the fixtures in the validation tests.

https://github.com/ARM-software/ComputeLibrary/blob/master/tests/validation/fixtures/HOGDescriptorFixture.h
https://github.com/ARM-software/ComputeLibrary/blob/master/tests/validation/fixtures/HOGDetectorFixture.h
https://github.com/ARM-software/ComputeLibrary/blob/master/tests/validation/fixtures/HOGMultiDetectionFixture.h

This might help you to understand how to use these functions and configure them properly.

Hope this helps.

**Comment by vswdigitall** [comment]
Thanks. Will try.
