### ISSUE TITLE
[Question] Zero copy and CropRezie

### ISSUE THREAD

**Issue by redglass1984** [ARM-software/ComputeLibrary#695]
ACL 19.05, built for neon, aarch64

1. Why we don't have 0 copy function for input tensors?
In my case,  I got picture from camera, but if I want to process it with ACL, I need to allocate new buffer and copy the image into it. It cost much time, is there any plan that ACL can import image without copy.

2. Fro NECropResize function, why not support U8?
Source images always U8, but CropResize function only supported from U16. how to process with U8 image?

Thanks!

**Comment by redglass1984** [comment]
Seems NEScale support U8, but it will constrain to U16 when calling CropResize.

**Comment by morgolock** [comment]
Hi @redglass1984 

Most kernels in the library require padding and the amount of padding needed depends on the arguments used to configure a particular function. In theory you could import memory but you must provide a buffer big enough to account for the padding. This might sound easy for one function, but in practice it can be difficult determine exactly for nested functions.

What ACL's function you use to process the pic from the camera? For more details about importing memory please take a look at: https://github.com/ARM-software/ComputeLibrary/blob/master/tests/validation/NEON/UNIT/TensorAllocator.cpp#L53

**Comment by redglass1984** [comment]
Thanks @morgolock 
I will read the memory import code.

Do you have any idea on me 2nd problem? Why CropResize not support U8?

**Comment by redglass1984** [comment]
@morgolock 

We always need to do Crop & Resize on the original image to get a small one.
So we relay on CropResize function to import the data into ACL.
pseudocode as below:

1. tensor -> import ( src image)
2. crop ( roi)
3. resize (size)
4. forword (nn)

**Comment by morgolock** [comment]
Hi @redglass1984 

CropResize does not support U8. It should not be too difficult to make the changes to support U8, I encourage you to try to do it. Let us know if you need help.

**Comment by redglass1984** [comment]
@morgolock 

Ok， Thanks， If you don't plan to make this function support U8. I can only try to make it by myself.

THanks~

**Comment by morgolock** [comment]
Hi @redglass1984 

We have it in our backlog but there is no specific dates as to when this could happen. I'd encourage you to implement this and submit a patch for review on gerrit.
