### ISSUE TITLE
Performance improvement with NHWC data layout

### ISSUE THREAD

**Issue by pranathibl** [ARM-software/ComputeLibrary#696]
Hi,

I have observed a lot of performance boostup for various networks with NHWC data layout from NCHW layout.
Can i know why is it so? what is improving the performance?

and, I have seen CLScheduler sync() is used in cl_convolution.cpp example but not in graph example. What is the significance of sync()? is it okay if sync is not used? 

Thanks,
Pranathi.

**Comment by gmiodice** [comment]
Hi @pranathibl,
many thanks for your message. If you are using the latest Compute Library 19.05, we have introduced various optimizations for both OpenCL and NEON.
I recently wrote a blog post to report the work done for the last release. Please see the link below:
https://community.arm.com/developer/tools-software/graphics/b/blog/posts/arm-compute-library-19-05-is-coming

The 11th of June I will also host a free webinar to talk more about the new features and optimizations available in ACL. 
https://pages.arm.com/webinar-performance-analysis-for-embedded-deep-learning.html?_ga=2.233533470.1495490620.1559559599-196818026.1547118445

Regarding the sync(), this method should be only used at the end of the OpenCL pipeline. 
i.e.

conv(GPU) -> conv(GPU) -> conv(GPU) -> conv(GPU) ->sync()

if your pipeline has a mixture of CPU and GPU functions, you should call the sync() before running the CPU implementation

i.e. 
conv(GPU) -> **sync()** -> conv(CPU) -> conv(GPU) -> **sync()** -> conv(CPU) 

It is a point of syncronization between CPU and GPU and used to update the L2 cache.

Hope this can help.

**Comment by pranathibl** [comment]
Hi @gmiodice ,

I am using Compute Library 19.02 and i am observing performance improvement with NHWC layout for OpenCL. 
can i know what is improving the performance?

Thanks,
Pranathi.

**Comment by gmiodice** [comment]
Hi @pranathibl ,

could you give us some information about the platform used? With this I should be able to check what optimizations we introduced in ACL.

Thanks,

**Comment by pranathibl** [comment]
Hi @gmiodice ,

I am using Hikey960 with Mali G71 GPU.

**Comment by gmiodice** [comment]
Hi @pranathibl,

in 19.02 we have introduced two important optimizations for OpenCL:

1. A new GEMM implementation (CLGEMMReshaped) which, on average, should be 14% faster than the previous one. This new GEMM is configurable at runtime in terms of block size and coalescing
2. A new OpenCL tuner which increases the search space to look for the optimal LWS to use by each OpenCL kernel.

Let me know if you need any further information.

Thanks,
Gian Marco
