### ISSUE TITLE
is it possible to accelerate init/configure time?

### ISSUE THREAD

**Issue by l1a0t1n9** [ARM-software/ComputeLibrary#697]
Recently, I have integrated the library into another inference framework and found that a lot of time was spent on graph initialization and op configuration . Is it possible to speed up this step.

**Comment by gmiodice** [comment]
Hi @l1a0t1n9,

and thanks for your message.
It is possible and we are going to work on that soon. What backend are you using? NEON or OpenCL?

Thanks

**Comment by l1a0t1n9** [comment]
i have test cl and gl

**Comment by GeorgeARM** [comment]
Hello @l1a0t1n9,

Just out of curiosity.
Is the configure time that you are having performance concerns for or that usually the first execution of the graph is a bit slower or both? These are two completely different problems.

**Comment by l1a0t1n9** [comment]
In my case, it's a segment model with a MobileNet backbone.The configure time  typically takes 2-3 seconds while the runtime is only need 30ms.  
In general, we could configure it once and then call run func multiple time, in this case, the configure time is not a big deal. But in particular, it is too expensive if the model executes only once at a time.

**Comment by GeorgeARM** [comment]
Hello @l1a0t1n9,

Well this happens only during configuration and in the first run as you have online compilation of the kernels (in CL and GLES) and transformations on the weights. We have identified the issue and we will start working on this, but for now we expect that the same model will run multiple times thus this cost will get amortized. I will mark this as a feature request. If you have any more issues or more questions feel free to comment.

**Comment by morgolock** [comment]
Hi @l1a0t1n9 

Please take a look at this thread: https://github.com/ARM-software/ComputeLibrary/issues/568#issuecomment-433075269

The idea is to configure() all the functions, save the kernels to a cache file and then load them when your app restarts.

**Comment by l1a0t1n9** [comment]
This is exactly the feature I wanted, does this feature already support cl and gl?

**Comment by l1a0t1n9** [comment]
@morgolock

**Comment by l1a0t1n9** [comment]
Ps,  Can I understand in this way,  most configure time was spent on compiling shader?

**Comment by morgolock** [comment]
Hi @l1a0t1n9 

> Ps, Can I understand in this way, most configure time was spent on compiling shader?

Yes, for the 1st run specially, compilation of the kernels for the GPU backends is costly. The idea is to do it once, save the kernels to disc and the next time the app starts just loads the prebuilt kernels from the disc.
