### ISSUE TITLE
Mismatch of conv layer output

### ISSUE THREAD

**Issue by szihs** [ARM-software/ComputeLibrary#698]
**Output of 'strings libarm_compute.so | grep arm_compute_version':** arm_compute_version=v19.05 Build options: {'arch': 'armv7a', 'opencl': '1', 'neon': '1', 'debug': '1', 'os': 'linux', 'Werror': '1'} Git hash=4ba87dbdc3b22220eba4a792c1f5c87e7a88c7af

**Platform:** :  Samsung ARM Chromebook XE303C12 + Crouton 

**Operating System:** Ubuntu 18.04.1 LTS

**Problem description:**
I am trying a simple convolution layer and the output of tensorflow and the ACL doesn't seem to match.

Please find the attached code describing problem.
https://gist.github.com/szihs/bb6eefebea8ffe1cdcb05089edde0244

`src_tensor -> conv0 -> out_tensor`
`1x6x3x2  -> 4x3x2x4  -> 1x6x3x4`
Relevant TF code in python notebook
https://drive.google.com/file/d/1Z31ZaflNk35wNlhayPXdbGcH9W5SOnsu/view?usp=sharing

I have spent lot of time, but cannot find the problem why the output doesn't match.
Would you please be able to have a look?

Thank you

**Comment by gmiodice** [comment]
Hi @szihs ,

thanks for reporting this issue. 

We are investigating the mismatch and we should already have a patch to fix it.

Could you try:
https://review.mlplatform.org/#/c/ml/ComputeLibrary/+/1312/

and tell us if this patch fixes your problem?

Thanks,
Gian Marco

**Comment by szihs** [comment]
Hello Marco,
Thanks for your reply.
I studied little more, and found that TF has default NHWC format.

So based on my sample, i think 
```
src_tensor -> conv0 -> out_tensor
1x6x3x2 -> 4x3x2x4 -> 1x6x3x4
```
would lead to change in sample code. I updated `v3` for the https://gist.github.com/szihs/bb6eefebea8ffe1cdcb05089edde0244/revisions?diff=unified

Step 1)  Previously I had src_shape w=6, h=3, but assuming NCHW it should be reversed. 
Please confirm that it is correct change.  Updated  test.cpp

Step 2) As i understand, Weights in TF needs to be transposed to make it OIHW format. Is it correct understanding ? Below is the way i save the weights. 
`np.save('w.npy', np.ascontiguousarray(w.transpose(3, 2, 0, 1)))`
And then i am uploading with the below shape
weights_shape_conv0(kernel_x_conv0, kernel_y_conv0, src_shape.z(), ofm_conv0);
_( Already done in first revision)_ 

Step 3).  I also changed the np::SaveArrayAsNumpy shape[] in reverse order. 
Please check if it is correct.  Updated in v3 of test.cpp

Step 4)  When comparing, i change the output in TF code to NCHW format to compare the ACL output
`output = np.transpose(output, (0, 3, 1, 2))`

With these changes I can see the output matches.
Please let me know if the steps are correct.

Thank you
Regards.
