### ISSUE TITLE
share data of opencv mat with arm_compute::Tensor 

### ISSUE THREAD

**Issue by waveajay** [ARM-software/ComputeLibrary#699]
How do we share data of opencv mat with arm_compute::Tensor

**Comment by waveajay** [comment]
I know how to copy data using execute window ,but it is taking much time.Then I used
' import_memory (Memory(img.data)) '//where img is a opencv mat
but it is giving an error:no matching function for call to 'arm_compute::Memory::Memory(uchar*&)'

**Comment by morgolock** [comment]
Hi @waveajay 

What version of the library are you using? 19.05?

Please take a quick look at our unit test for importing memory: https://github.com/ARM-software/ComputeLibrary/blob/master/tests/validation/NEON/UNIT/TensorAllocator.cpp#L106

The test shows how to import memory when using NEActivationLayer.
