### ISSUE TITLE
TensorAccessor was not declared in scope

### ISSUE THREAD

**Issue by waveajay** [ARM-software/ComputeLibrary#701]
I tried creating an object of TensorAccessor for accessing elements of tensor but i am getting error TensorAccessor was not declared in the scope(i am using arm_compute name space )
code
TensorAccessor <uint8> acessor(&output)//where output is a Tensor

**Comment by morgolock** [comment]
Hi @waveajay 

Try `#include arm_compute/core/WindowIterator.h`

Hope this helps

**Comment by waveajay** [comment]
Thanks it worked
