### ISSUE TITLE
How access elements of tensor if tensor have channels

### ISSUE THREAD

**Issue by waveajay** [ARM-software/ComputeLibrary#702]
//output is a tensor and it has 3 channels
TensorAccessor\<float>accessor(output);
float *ptr=accessor.get_ptr(0,0,0);
//above code and below code is giving same memory location
float *ptr=accessor.get_ptr(0,0,1);

**Comment by morgolock** [comment]
Hi @waveajay 

Would you please share the Tensor shape and layout?

The pointer to (0,0,0) should be different from (0,0,1) as long as your tensor is rank 3 or more.

**Comment by waveajay** [comment]
//code of creating tensor
//width=19,height=19,num_cha=14
Tensor output;Tensorshape Spae(width,height);
output.allocator()->init(TensorInfo(Spae,num_cha,arm_compute::DataType::F32));
output.allocator->allocate();

**Comment by morgolock** [comment]
Hi @waveajay 

Please take a look at the following code in the validation test:
https://github.com/ARM-software/ComputeLibrary/blob/master/tests/validation/fixtures/DirectConvolutionLayerFixture.h#L69
https://github.com/ARM-software/ComputeLibrary/blob/master/tests/validation/NEON/UNIT/TensorAllocator.cpp#L96

We specify the tensor's channels in the TensorShape plus DataLayout.

For example:
`TensorInfo info(TensorShape(24U, 16U, 3U), 1, DataType::F32);`

If you do not specify the layout, NCHW is assumed and the tensor initialised with this TensorInfo will have 3 channels.

**Comment by nhkrishna** [comment]
Hi,

Could you elaborate more on second argument for the TensorInfo constructor?

When i go through [documentation ](https://arm-software.github.io/ComputeLibrary/v19.05/classarm__compute_1_1_tensor_info.xhtml#a734bdd7d65d40aa012ebeb172fda955a), it was saying as below

num_channels | It indicates the number of channels for each tensor element
-- | --

But we we are already specifying the num_channels in the Tenshape(Width, Height, Channels). Then why again num_channels required(second argument). Its little bit confusing for me and if i use 1 inplace of second argument (num_channels) then it works fine with out any issue.

Thanks,
Hari
