### ISSUE TITLE
Performance over releases

### ISSUE THREAD

**Issue by peter197321** [ARM-software/ComputeLibrary#703]
I have just tried some examples (alexnet, squeezenet) with various ACL releases 18.11, 19.02 and 19.05 and measured

squeezenet-19.05 is 209.534
squeezenet-19.02 is 248.903
squeezenet-19.02 is 96.8055
and for 
alexnet-19.05 is 377.191
alexnet-19.02 is 384.229
alexnet-18.11 is 51.0926

can you help to explain the 18.11 seems have better perfroamnce?

Thank you for your help.

**Comment by morgolock** [comment]
Hi @peter197321 

19.05 should be faster than 18.11. Could you please tell use more about your benchmarking environment? What device have you used to assess performance? What command did you use to run the examples and build the library?

**Comment by peter197321** [comment]
ACL lib building
scons Werror=0 -j24 neon=1 opencl=1 embed_kernels=1 os=linux arch=arm64-v8a build=cross_compile

same platform for measurement (OS, HW)
Yocto/Linux - THUD, 4.19.35, CPU: 4xA53

app
./graph_alexnet --target=NEON --type=F32 --threads=1

**Comment by morgolock** [comment]
Hi @peter197321 

For alexnet I get 134.5936 ms on a device with A53, this is top of the master development branch.

![benchmarkexamplesalex](https://user-images.githubusercontent.com/5577511/59608730-e8ed9f00-910d-11e9-9b0a-fd2e152ea778.png)

Regarding the command in your previous post, how do you measure the time? that command does not output any time figures.

**Comment by yasirmahmoodqureshi** [comment]
Hi @morgolock ,
How did you create the benchmark_graph_alexnet binary, as I don't get it even when I have set benchmark=1 while compiling ?

**Comment by morgolock** [comment]
Hi @yasirmahmoodqureshi 

You have to clone public master branch:
`git clone "ssh://your_user@review.mlplatform.org:29418/ml/ComputeLibrary`
and build with `benchmark_examples=1`

Benchmark examples are not released on github, it's just an internal tool we use to investigate the performance of different networks.

**Comment by peter197321** [comment]
I have starndard release version of ACL and have prepared bench application for myself (not aware of bench example on internal development repo)

The measuremnt is done as follows

```
gettimeofday(&timer_start, NULL);
        for(int i=0; i<BENCH_ITERS; ++i)
	    example->do_run();
gettimeofday(&timer_end, NULL);

....

perfTime = (timer_end.tv_sec - timer_start.tv_sec) * 1000.0;
perfTime += (timer_end.tv_usec - timer_start.tv_usec) / 1000.0;
```

The `example->do_run();` actually wraps a call of particular graph

```
// Run graph
    graph.run();
```

**Comment by yasirmahmoodqureshi** [comment]
Hi @morgolock 

Thanks for sharing this. I am able to run the benchmark examples now.
Just to clarify, the reported "Wall clock/Wall clock time" for a graph benchmark example (like benchmark_grapgh_alexnet) is for the actual execution of the graph and does not include the graph setup time, right ?

**Comment by yasirmahmoodqureshi** [comment]
Hi @peter197321,

But if you wrap the time measurements around  example->do_run(); call, you are also including the graph setup time (reading and setting up the weights, tensors, etc.). The graph setup is expensive in terms of time, so the actual execution time of is not really obvious, especially if you have just one execution.

**Comment by morgolock** [comment]
Hi @yasirmahmoodqureshi 

That is correct. The configuration of the graph is done in do_setup() and this is not measured by the framework.

https://github.com/ARM-software/ComputeLibrary/blob/master/tests/framework/Framework.cpp#L316

The test only measures the time it takes to run the graph.

**Comment by morgolock** [comment]
> But if you wrap the time measurements around example->do_run(); call, you are also including the graph setup time (reading and setting up the weights, tensors, etc.).

That is not the case, see my previous comment.

**Comment by peter197321** [comment]
In the case of OpenCL target does the measurement of mine around

```
// Run graph
    graph.run();

```
include `clCreateKernel(), clBuildProgram(), clCreateBuffer()` etc.. and yours it excludes...

**Comment by morgolock** [comment]
Hi @peter197321 

The time for configuring the functions does not affect the measurement. This occurs in:
https://github.com/ARM-software/ComputeLibrary/blob/master/examples/graph_alexnet.cpp#L42 and the test framework does not measure that.
