### ISSUE TITLE
ARM CPU FP16 Targets

### ISSUE THREAD

**Issue by uu-praveeng** [ARM-software/ComputeLibrary#704]
Hi,
	
Could you let us know hardware we could acquire and test the ARM CPU FP16 support provided by ACL. These are the links [link1](https://en.wikipedia.org/wiki/Comparison_of_ARMv8-A_cores) [link2](https://en.wikipedia.org/wiki/ARM_Cortex-A55) about processors that are based on the armv8.2-a. Do we need to acquire the mobiles that use snapdragon or Kirin SoCs which use these processor to test the FP16 support on ARM CPU?
	
What is your preferred hardware/device to test the ARM CPU FP16 support for AACL ?

ACL on ARM Mali front, Mali G71 does support FP16 . Am I right?

Thank you,
Praveen.

**Comment by morgolock** [comment]
Hi @uu-praveeng 

We validated our FP16 neon code on the Cortex-A55 fast model. Any device with an ARMv8.2-A CPU will support FP16.

**Comment by uu-praveeng** [comment]
Could you elaborate more on the Cortex-A55 fast model. Do you have hardware which has this cpu or is the CPU simulated and tested using DS-5 like simulator.

Reason I am asking this query is to know about hardware devices which use this armv8.2-a architectures. Any extra details would really help us in accelerating our work.

**Comment by morgolock** [comment]
Hi @uu-praveeng 

The fast model runs on an x86 machine and emulates the A55 hardware. We used the fast model with Linux to develop, debug and validate the FP16 Neon code in ACL. 

Please take a look at the page:
https://community.arm.com/developer/tools-software/tools/b/tools-software-ides-blog/posts/using-arm-models-for-software-development-and-performance-analysis-for-the-cortex-a75-and-cortex-a55

https://developer.arm.com/tools-and-software/simulation-models/fast-models?_ga=2.265692235.594063064.1560429485-833326948.1485870095&_gac=1.162329166.1560429485.Cj0KCQjw6IfoBRCiARIsAF6q06sJzDPBIsg_G9PpEWQT19iGrbzEn55n27jUd8RRa5MY1c_dcvlc1j4aAgZIEALw_wcB
