### ISSUE TITLE
 machine code in dot_toolchain_support.h

### ISSUE THREAD

**Issue by chenjiaoAngel** [ARM-software/ComputeLibrary#705]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

**Platform:**

**Operating System:**

hi, what is the machine code of "sdot v10.2s, %[v1].8b, v0.8b     \n"  in dot_toolchain_support.h
this dot_toolchain_support.h only  support "sdot v10.4s, %[v1].16b, v0.4b[0]     \n"

**Problem description:**

**Comment by morgolock** [comment]
Hi @chenjiaoAngel 

The macro _DECLARE_UDOT in
https://github.com/ARM-software/ComputeLibrary/blob/master/src/core/NEON/kernels/arm_gemm/kernels/a64_gemm_u8_12x8/dot_toolchain_support.h

is just a workaround to generate the opcode for the dot product instruction when the toolchain does not support it. If you compile for arch=armv8.2-a and your compiler does not know about the sdot instruction, ACL will use this macro generate the machine code for sdot.



Quoting the reference manual about the dot product instruction.

> ARMv8.2-DotProd provides SIMD instructions that perform the dot product of the four 8-bit subelements of the 32-bit elements of one vector with the four 8-bit subelements of a second vector. It provides two forms of the instructions, each with signed and unsigned versions

For more details please take a look at the reference manual: https://developer.arm.com/docs/ddi0487/latest/arm-architecture-reference-manual-armv8-for-armv8-a-architecture-profile?_ga=2.40959778.1213988665.1560783811-833326948.1485870095&_gac=1.217587044.1560429485.Cj0KCQjw6IfoBRCiARIsAF6q06sJzDPBIsg_G9PpEWQT19iGrbzEn55n27jUd8RRa5MY1c_dcvlc1j4aAgZIEALw_wcB

**Comment by chenjiaoAngel** [comment]
Thanks very much
