### ISSUE TITLE
Transfer data in neon tensor to CLTensor

### ISSUE THREAD

**Issue by waveajay** [ARM-software/ComputeLibrary#706]
How to  transfer NeonTensor data to CLTensor?

**Comment by morgolock** [comment]
Hi @waveajay 

Please take a look at the example below demonstrating how to feed CL data to Neon functions:
https://github.com/ARM-software/ComputeLibrary/blob/master/examples/neoncl_scale_median_gaussian.cpp

Hope this helps.

**Comment by GeorgeARM** [comment]
Hello @waveajay ,
In case you have both backends present I suppose you can use everywhere CLTensors. You can pass them to Neon functions but be careful before calling _run()_ on them you have to _map()_ them to ensure data synchronization. Moreover when you run the CL functions you have to _unmap()_ the tensors.

Hope this helps.
