### ISSUE TITLE
ACLGL convolution accuracy

### ISSUE THREAD

**Issue by l1a0t1n9** [ARM-software/ComputeLibrary#709]
Hi～，
I'm comparing the result of the CPU F32’s conv and gl fp16‘s conv and found some kind of mismatch. The accuracy between them is vary large， and the deference of each output elem is about 10-2.

**Comment by GeorgeARM** [comment]
Hello @l1a0t1n9,

Is this difference visible when running with real weights/inputs or random values? Well fp16 accuracy is completely different than fp32. We do all our internal calculation natively in fp16 thus no accumulations happen in higher precision. So you have to make sure that your internal calculations are in a range that fp16 arithmetic can handle.

Hope this helps.
