### ISSUE TITLE
Reagrading Graaph Interfacre and direct CL interface for ACL

### ISSUE THREAD

**Issue by abhajaswal** [ARM-software/ComputeLibrary#714]
Compute library- 19.05
arm7a
Platform : linux

I have deveopled a Classification model using tensorflow.
And Created a Graph application for the same.

Now i want to create an end to end application decoded data , melspec  and classification of frame data which is done by ACL.

I want to understand better apporach to use ACL !!

Currently i call do_setup my application one time , which contains graph pipeline  creation part and does weights loading and configurations for tensors.

and I call do_run() multiple times , everytime i load  data into input accesor and call  graph->run 
and then call arm_compute::CLScheduler::get().sync();

I want to understand wether its advisable to use graph interface or cl interface as explained in cl_convolution.cpp example

**Comment by abhajaswal** [comment]
Compute library- 19.05
arm7a
Platform : linux

I have deveopled a Classification model using tensorflow.
And Created a Graph application for the same.

Now i want to create an end to end application where i decode data , use  melspec and and provide input frame data for classification which  is done by ACL.

I want to understand better apporach to use ACL !!

Currently i call do_setup my application one time , which contains graph pipeline creation part and does weights loading and configurations for tensors.
Then I call do_run() multiple times , everytime i load data into input accesor and call graph->run
and then call arm_compute::CLScheduler::get().sync();

I want to understand wether its advisable to use graph interface or cl interface as explained in cl_convolution.cpp example for final product

**Comment by morgolock** [comment]
> Compute library- 19.05
> arm7a
> Platform : linux
> 
> I have deveopled a Classification model using tensorflow.
> And Created a Graph application for the same.
> 
> Now i want to create an end to end application where i decode data , use melspec and and provide input frame data for classification which is done by ACL.
> 
> I want to understand better apporach to use ACL !!
> 
> Currently i call do_setup my application one time , which contains graph pipeline creation part and does weights loading and configurations for tensors.
> Then I call do_run() multiple times , everytime i load data into input accesor and call graph->run
> and then call arm_compute::CLScheduler::get().sync();
> 
> I want to understand wether its advisable to use graph interface or cl interface as explained in cl_convolution.cpp example for final product

Hi @abhajaswal

The general idea is that you call setup() once and then run() as many times as you need. 

The choice between the functions and graph api is going to depend on your needs and requirements. The functions will provide some more flexibility but it's going to be more verbose, whereas the graph api is a higher level abstraction that requires less code to implement the models. It's entirely up to you to choose the one that works better for your problem. Whatever is your choice they will produce the same results.

That said please be aware that the graph api in ACL is provided as a way to quickly prototype models and experiment with the library, it was developed mainly to address internal testing needs in our team.

**Comment by morgolock** [comment]
> Compute library- 19.05
> arm7a
> Platform : linux
> 
> I have deveopled a Classification model using tensorflow.
> And Created a Graph application for the same.
> 
> Now i want to create an end to end application decoded data , melspec and classification of frame data which is done by ACL.
> 
> I want to understand better apporach to use ACL !!
> 
> Currently i call do_setup my application one time , which contains graph pipeline creation part and does weights loading and configurations for tensors.
> 
> and I call do_run() multiple times , everytime i load data into input accesor and call graph->run
> and then call arm_compute::CLScheduler::get().sync();
> 
> I want to understand wether its advisable to use graph interface or cl interface as explained in cl_convolution.cpp example

Hi @abhajaswal 

As explained in my previous message, the choice between function/graph api is yours. In both cases you'll have to update the data of the input tensor and rerun the function/graph.

Configure/Setup is only done once.

Hope this helps.

**Comment by abhajaswal** [comment]
@morgolock  thanks for your feedback, Reason why asked this is , Are there any bugs in  graph pipeline which may hamper my work.
My output layer in graph  has top 3 predictions i,e   I set :

OutputLayer(get_output_accessor(common_params, 3));


As I observed , when i run graph->run in a loop like this ->

        for(int i = 0 ; i< 1000 ; i++)
        {
          
          TIMER_START();
        // Run graph
          graph.run();
          if(common_params.target != arm_compute::graph::Target::NEON)
          {
             arm_compute::CLScheduler::get().sync();
          }
          TIMER_STOP(" run \n"); printf(" iter : %d \n " , i ) ; fflush(stdout) ;
        }

Every Alternate run iteration is not printing the correct top 3 predictions. Is there any bug with output accessor?

**Comment by abhajaswal** [comment]
By Every Alternate run iteration is not printing the correct output I mean, Its not printing the top predictions at all.

**Comment by abhajaswal** [comment]
Can you please check the GraphManager.cpp 

void GraphManager::execute_graph(Graph &graph)
{
    // Check if graph is finalized
    auto it = _workloads.find(graph.id());
    ARM_COMPUTE_ERROR_ON_MSG(it == std::end(_workloads), "Graph is not registered!");

    while(true)
    {
        // Call input accessors
        if(!detail::call_all_input_node_accessors(it->second))
        {
            return;
        }

        // Run graph
        detail::call_all_tasks(it->second);

        // Call output accessors
        if(!detail::call_all_output_node_accessors(it->second))
        {
            return;
        }
    }
}

In Every input accesor code :

bool NumPyBinLoader::access_tensor(ITensor &tensor)
{
    if(!_already_loaded)
    {
        utils::NPYLoader loader;
        loader.open(_filename, _file_layout);
        loader.fill_tensor(tensor);
    }

    _already_loaded = !_already_loaded;
    return _already_loaded;
}

_already_loaded = false by default, This then makes it true, in 2nd iteration it becomes true, and the while loop of exceute graph exits.

This mechanism was not present in 18.05 , there we dint get such issue.
Pleasec confirm

**Comment by abhajaswal** [comment]
ALso I want to know whether there will be any performance variance if i use graph interface or direct CL interface?

**Comment by morgolock** [comment]
Hi @abhajaswal 

Performance should be fairly similar among the two approaches, the graph ends up calling to the functions to execute all the workloads. There might be a negligible performance drop with the graph because it's just doing more than the functions and this represents more code.

**Comment by hdchenjian** [comment]
@abhajaswal please check this https://github.com/ARM-software/ComputeLibrary/issues/379#issuecomment-513515092
