### ISSUE TITLE
how to use gemm_uint16

### ISSUE THREAD

**Issue by HaoLiuHust** [ARM-software/ComputeLibrary#715]
I want to use gemm_uint16 to accelerate my matrix multiply, but I did not found the example

**Comment by morgolock** [comment]
Hi @HaoLiuHust 

The GEMM functions in both backends only support the data types FP32 and FP16.

Please take a look at this files:

https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/NEON/functions/NEGEMM.h#L68

https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/core/NEON/kernels/NEGEMMMatrixMultiplyKernel.h#L61

**Comment by HaoLiuHust** [comment]
thanks, get that. Is it possible to use FP16 on armv7, such as armA7 chip?

**Comment by morgolock** [comment]
Hi @HaoLiuHust 

Not with arm-v7a, you need at least armv8.2a.

https://developer.arm.com/architectures/instruction-sets/floating-point
