### ISSUE TITLE
How to complier this lib for arm-hisiv500 toolchain?

### ISSUE THREAD

**Issue by luyahan** [ARM-software/ComputeLibrary#716]
How to complier this lib for arm-hisiv500 toolchain?

**Comment by morgolock** [comment]
Hi @luyahan 

Could you please provide more information about the toolchain? A link could be useful.

**Comment by luyahan** [comment]
Hi @morgolock ,thank you
This is a download link for  arm-hisi300 toolchain .The tolchain is for hisi soc.
https://1drv.ms/u/s!AsT7rTrgGAFnniZ_X8o-myrPGvk0

**Comment by morgolock** [comment]
Hi @luyahan 

You could easily do it pointing the PATH to the place where your toolchain binaries are and using the toolchain_prefix option as shown below:

`PATH=/home/luyahan/work-acl/ComputeLibrary/arm-hisiv300-linux/bin/:$PATH scons os=linux arch=armv7a neon=1 gles_compute=0 opencl=1 examples=1 validation_tests=0 benchmark_examples=0 benchmark_tests=0 debug=1 examples=1 -j16 toolchain_prefix=arm-hisiv300-linux-uclibcgnueabi-`
