### ISSUE TITLE
Usage of free()

### ISSUE THREAD

**Issue by pranathibl** [ARM-software/ComputeLibrary#717]
Hi,

As per the documentation, it is mentioned that allocator::free() is used to free the allocated tensor. but i did not see any example using allocator::free().

will there be any memory leaks if we skip using free()?

Thanks,
Pranathi

**Comment by morgolock** [comment]
Hi @pranathibil

Please take a look at the prepare() method in CLWinogradConvolutionLayer: https://github.com/ARM-software/ComputeLibrary/blob/master/src/runtime/CL/functions/CLWinogradConvolutionLayer.cpp

You will find more runtime functions using it, just search `rgrep free src/runtime`

Hope this helps
