### ISSUE TITLE
More RAM needed in 32-bit than 64-bit Arm CPU

### ISSUE THREAD

**Issue by ValentinoPeluso** [ARM-software/ComputeLibrary#718]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
aarch64:arm_compute_version=v19.05 Build options: {'arch': 'arm64-v8a', 'debug': '0', 'asserts': '0', 'neon': '1', 'opencl': '0', 'embed_kernels': '1', 'extra_cxx_flags': '-fPIC', 'internal_only': '0', 'os': 'linux', 'toolchain_prefix': 'gcc-linaro-6.5.0-2018.12-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-'} Git hash=b'4ba87dbdc3b22220eba4a792c1f5c87e7a88c7af'
arm: arm_compute_version=v19.05 Build options: {'arch': 'armv7a', 'debug': '0', 'asserts': '0', 'neon': '1', 'opencl': '0', 'embed_kernels': '1', 'extra_cxx_flags': '-fPIC', 'internal_only': '0', 'os': 'linux', 'toolchain_prefix': 'gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-'} Git hash=b'4ba87dbdc3b22220eba4a792c1f5c87e7a88c7af'

**Platform:**
aarch64: Odroid C2
arm: Odroid XU4

**Operating System:**
Ubuntu 16.04 by HardKernel

**Problem description:**
Hi, 
I am trying to execute the graph_vgg16 and graph_vgg19 examples on two different architectures: Odroid C2 (64-bit) and Odroid XU4 (32-bit). Both systems have 2GB of RAM. 
On 64-bit architecture, everything works fine. Instead, on 32-bit architecture the job gets killed as it gets out of memory. Moreover, I noticed that every example uses more RAM in 32-bit CPUs than 64-bit CPUs. Is this an expected behavior?

**Comment by morgolock** [comment]
Hi @ValentinoPeluso 

Yes, it's a common problem on 32 bit systems with 2GB or less.

Have you tried forcing MemoryPolicy::MINIMIZE?
Just move `arm_compute::MEMInfo::set_policy(arm_compute::MemoryPolicy::MINIMIZE);` out of the if in the vgg16 example.

Other processes running at the same time will also compete for memory so make sure you don't have any memory hungry processes running in the background.

Most optimization efforts in the library are directed towards improving 64 bit arch performance, simply the 32 bit is not as optimised as the 64 bit code.

**Comment by ValentinoPeluso** [comment]
Even with this policy the memory usage is very high (~3x w.r.t. 64-bit). I also free few tens of RAM (only the OS is running) and the examples can run but RAM is almost fully used.

However, is it possible to change the Memory Policy in ARM NN? How can I do it?

**Comment by morgolock** [comment]
Hi @ValentinoPeluso 

I'm not sure how you can change the memory policy in Arm NN. It might be a good if you ask them directly: https://github.com/ARM-software/armnn/issues

**Comment by GeorgeARM** [comment]
@ValentinoPeluso 

Hope you are doing well.
Do you still use the MemInfo API? We are looking at deprecating it thus would be interested to know if this is still  in use.

**Comment by ValentinoPeluso** [comment]
@GeorgeARM not using anymore. But I am still interested on memory management in ACL. The new version supports new APIs for memory management? Is it possible to integrate custom policies?
