### ISSUE TITLE
how does execute_window_loop() work?

### ISSUE THREAD

**Issue by xlxulin1** [ARM-software/ComputeLibrary#72]
execute_window_loop( .. id)
{
    ..
    work(id);
    ..
}

I think this function works look like muti-thread, opencl, cuda or something.
each work(id) excutes parallel. Am I right?
can someone explain it?
thanks very much.

**Comment by AnthonyARM** [comment]
No, this is just a fancy `for` loop for an arbitrary number of dimensions.
i.e instead of doing:
```
for( id.y = y_start; id.y < y_end; id.y += y_step )
   for( id.x = x_start; id.x < x_end; id.x += x_step)
{
 // Do something
}
```
You just do:
```
Window w;
w.set( 0 , Window::Dimension( x_start, x_end, x_step);
w.set( 1 , Window::Dimension( y_start, y_end, y_step);
execute_window_loop( w, [&] ( Coordinates &id )
{
 // Do something
}
```
The difference being `execute_window_loop` can handle an arbitrary number of dimensions.
It can also be combined with iterators which will be incremented for every iteration.

Hope this helps

**Comment by xlxulin1** [comment]
hello, @AnthonyARM 
Thanks for the explanation. 
I was wondering the performace. It performs much faster than normal for/while loop.
It's about 4x or 5x faster than normal way.

**Comment by xlxulin1** [comment]
hello, @AnthonyARM 
I found that it's not execute_window_loop cased the performance speed up. I think it's the memory, but I am not sure yet.

**Comment by GeorgeARM** [comment]
Assuming question has been addressed. Closing issue. Reopen if required!
