### ISSUE TITLE
Notification error in multithreadded CPPScheduler::Thread

### ISSUE THREAD

**Issue by Beshkent** [ARM-software/ComputeLibrary#720]
**Output of `strings libarm_compute.so | grep arm_compute_version`:** `arm_compute_version=v19.02 Build options: {'arch': 'armv7a', 'opencl': '1', 'neon': '1', 'build_dir': 'armv7a-linux.release', 'examples': '0', 'os': 'linux', 'Werror': '0'} Git hash=09523c4c3178e66a46e85987aac50a284fbfad38`

**Platform:** `arm7l`

**Operating System:** `Linux`

**Problem description:**
If some operations (two `NEConvolutionLayer` in my case) are run concurrently, sometimes execution hangs. I investigated and experimented a bit and it seems to me:
1. May be there must be notification In `CPPScheduler::Thread::worker_thread()` like:
```diff
if(_workloads == nullptr)
        {
+           _job_complete = true;
+           lock.unlock();
+            _cv.notify_one();
            return;
        }
```
2. I'm sure in this section:
It has a lot of `wait` and they wait for **two different** conditions: **`return _wait_for_work`** and **`return _job_complete;`**. Since there is **just one** `std::condition_variable _cv` when its
`notify_one` is called it may notify an incorrect `wait`. For example, the one after `_job_complete = true;` may notify an `wait`, that is waiting for **`_wait_for_work`** to be true. So, I think there must be **two** `std::condition_variable`:
```diff
void CPPScheduler::Thread::start(std::vector<IScheduler::Workload> *workloads, ThreadFeeder &feeder, const ThreadInfo &info)
{
    _workloads = workloads;
    _feeder    = &feeder;
    _info      = info;
    {
        std::lock_guard<std::mutex> lock(_m);
        _wait_for_work = true;
        _job_complete  = false;
    }
-    _cv.notify_one();
+    _cv_w.notify_one();
}

void CPPScheduler::Thread::wait()
{
    {
        std::unique_lock<std::mutex> lock(_m);
-        _cv.wait(lock, [&] { return _job_complete; });
+        _cv_c.wait(lock, [&] { return _job_complete; });
    }

    if(_current_exception)
    {
        std::rethrow_exception(_current_exception);
    }
}

void CPPScheduler::Thread::worker_thread()
{
    while(true)
    {
        std::unique_lock<std::mutex> lock(_m);
-        _cv.wait(lock, [&] { return _wait_for_work; });
+        _cv_w.wait(lock, [&] { return _wait_for_work; });
        _wait_for_work = false;

        _current_exception = nullptr;

        // Time to exit
        if(_workloads == nullptr)
        {
+           //I'm not sure if it is really needed
+            _job_complete = true;
+           lock.unlock();
+          _cv_c.notify_one();
            return;
        }

#ifndef ARM_COMPUTE_EXCEPTIONS_DISABLED
        try
        {
#endif /* ARM_COMPUTE_EXCEPTIONS_ENABLED */
            process_workloads(*_workloads, *_feeder, _info);

#ifndef ARM_COMPUTE_EXCEPTIONS_DISABLED
        }
        catch(...)
        {
            _current_exception = std::current_exception();
        }
#endif /* ARM_COMPUTE_EXCEPTIONS_DISABLED */
        _job_complete = true;
        lock.unlock();
-        _cv.notify_one();
+        _cv_c.notify_one();
    }
}
```

**Comment by morgolock** [comment]
Hi @Beshkent 

The schedulers were not designed to be thread safe, if you call CPPScheduler::schedule() from a different thread while there are still workloads running you will get undefined results.

The CPPScheduler creates as many worker threads as the number of cores detected in the system and then each thread will run a kernel on a subset of the input data. Even if you fix the scheduler with the synchronisation code as above you won't get optimal performance because the workloads will have to compete for the threads time (too few threads and too many workloads).

We are working to remove the singletons from ACL which would help in this case. Instantiating multiple schedulers, one per thread, would solve the issue.

**Comment by Beshkent** [comment]
>The schedulers were not designed to be thread safe...

@morgolock,thank you for your answer

---
>We are working to remove the singletons from ACL...

👍. Feel free to close the issue or keep it open until you finish that work

**Comment by morgolock** [comment]
Hi @Beshkent 

> > The CPPScheduler creates as many worker threads as the number of cores detected in the system...
> 
> This is the same for `NEON` also, right?

Yes, the CPPScheduler is used to execute the NEON kernels concurrently. There is also an OpenMP scheduler which can be enabled at compilation time with openmp=1 cppthreads=0.
