### ISSUE TITLE
Add svm coefficients in Multihog  

### ISSUE THREAD

**Issue by waveajay** [ARM-software/ComputeLibrary#721]
How we can add svm coefficients in mutihog?
can we copy clhog object to multihog

**Comment by morgolock** [comment]
Hi @waveajay 

Is this still relevant to you?

We do not have an example using MultiHog but you can take a look at the validation fixtures in our test framework for a general idea on how to use the API.

https://github.com/ARM-software/ComputeLibrary/blob/master/tests/validation/fixtures/HOGMultiDetectionFixture.h#L119
https://github.com/ARM-software/ComputeLibrary/blob/master/tests/validation/fixtures/HOGDetectorFixture.h#L82
https://github.com/ARM-software/ComputeLibrary/blob/master/tests/validation/fixtures/HOGDescriptorFixture.h#L78


Hope this helps.
