### ISSUE TITLE
Backprpagation convolution

### ISSUE THREAD

**Issue by shubh809** [ARM-software/ComputeLibrary#722]
### 

I was searching for  api which can perform the backpropagation for convolution layer but did not found any api related to these .
Do armCL provide any such api?

**Comment by shubh809** [comment]
I was searching for  api which can perform the backpropagation for convolution layer but did not found any api related to these .
Do armCL provide any such api?

**Comment by morgolock** [comment]
Hi @shubh809 

ACL is used for inference. Back-propagation is a technique used for training models. Please take a look at other high level frameworks like TensorFlow for more information about this.
