### ISSUE TITLE
float array to SimpleTensor or ICLTensor

### ISSUE THREAD

**Issue by shubh809** [ARM-software/ComputeLibrary#724]
**Problem description:**
How should I convert float array to ICLTensor or SimpleTensor so that tensor can be used in APIs like CLGemm?

**Comment by morgolock** [comment]
Hi @shubh809 

Please take a look at the documentation explaning how to move data to/from ACL's tensors: https://arm-software.github.io/ComputeLibrary/v19.05/architecture.xhtml#S4_6_4_working_with_objects

In ACL it's a good practice to use the helper function `execute_window_loop()` for this purpose.

**Comment by shubh809** [comment]
Thanks
