### ISSUE TITLE
Failed to compile cl_sgemm.cpp using provided library with cmake

### ISSUE THREAD

**Issue by peyer** [ARM-software/ComputeLibrary#725]
Cross-Compile
Source platform: ubuntu 16.04
Destination platform: RK3399 + android
ANDROID_NDK: r17c
ANDROID_ABI="arm64-v8a"
CMAKE_ANDROID_STL_TYPE=gnustl_static

I used CMakeLists and android.toolchain.cmake to configure my test project,  the cmake built option like below.
$ANDROID_SDK/cmake/3.6.4111459/bin/cmake .. \
-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
-DCMAKE_BUILD_TYPE=Release \
-DANDROID_ABI="arm64-v8a" \
-DCMAKE_ANDROID_STL_TYPE=gnustl_static \
-DANDROID_NATIVE_API_LEVEL=android-21  \

and the CMakeLists.txt like below

cmake_minimum_required(VERSION 3.6)
project(arm_ocl_samples)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")

add_definitions(-DARM_COMPUTE_CL)
add_executable(acl_cl_sgemm_arm64 /xxx/cl_sgemm_v1811.cpp
                                    /xxx/Utils.cpp )

set(ACL_ANDROUD_ARM64_OCL_DIR xxxl)
set(ACL_ANDROUD_ARM64_LIBs  ${ACL_ANDROUD_ARM64_OCL_DIR}/libarm_compute_core.so 
                            ${ACL_ANDROUD_ARM64_OCL_DIR}/libarm_compute_graph.so
                            ${ACL_ANDROUD_ARM64_OCL_DIR}/libarm_compute.so
                            ${ACL_ANDROUD_ARM64_OCL_DIR}/libOpenCL.so)
                            
message(${ACL_ANDROUD_ARM64_LIBs})

target_link_libraries(acl_cl_sgemm_arm64
                        ${ACL_ANDROUD_ARM64_LIBs}
                        android
                        dl
                        log
                        m
                        )

However, the clang++ compiler return an error:cl_sgemm.cpp:188: undefined reference to arm_compute::CLGEMM::CLGEMM()
How can I solve it?

**Comment by morgolock** [comment]
Hi @peyer 

>However, the clang++ compiler return an error:cl_sgemm.cpp:188: undefined reference to arm_compute::CLGEMM::CLGEMM()

This looks like a linker error, could you please share the command you used to build the library?
If you compile the library with opencl=1 and point the makefile to ACL's shared libraries there should be no linker errors.

**Comment by peyer** [comment]
Hi, @morgolock 
I just used your provided library(v18.11, Android) and unzip the android-arm64-v8a-cl directory under lib content to get ACL's shared libraries.
I used cmake to configure my project like below
cmake_minimum_required(VERSION 3.6)
project(arm_ocl_samples)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")

add_definitions(-DARM_COMPUTE_CL)
add_executable(acl_cl_sgemm_arm64 /xxx/cl_sgemm_v1811.cpp
/xxx/Utils.cpp )

set(ACL_ANDROUD_ARM64_OCL_DIR xxx)
set(ACL_ANDROUD_ARM64_LIBs ${ACL_ANDROUD_ARM64_OCL_DIR}/libarm_compute_core.so
${ACL_ANDROUD_ARM64_OCL_DIR}/libarm_compute_graph.so
${ACL_ANDROUD_ARM64_OCL_DIR}/libarm_compute.so
${ACL_ANDROUD_ARM64_OCL_DIR}/libOpenCL.so)

message(${ACL_ANDROUD_ARM64_LIBs})

target_link_libraries(acl_cl_sgemm_arm64
${ACL_ANDROUD_ARM64_LIBs}
android
dl
log
m
)

Should the CLGEMM class be compiled into libarm_compute.so ? And how could I check your provided library whether include all the symbols of CLGEMM class ?

**Comment by peyer** [comment]
@morgolock Could you provide CMakeLists.txt to compile entire project ?

**Comment by morgolock** [comment]
Hi @peyer 

Please see below my CMakeLists file to cross-compiler the example cl_sgemm for Linux aarch64.

You should be able to adapt this file to compile for android.

Hope this helps.

```
cmake_minimum_required (VERSION 2.6)
project (cl_sgemm)
add_definitions(-DARM_COMPUTE_CL)
include_directories(../ ../include)
add_executable(clgemm cl_sgemm.cpp ../utils/Utils.cpp )
TARGET_LINK_LIBRARIES(clgemm /work/Clean/ComputeLibrary/build/libarm_compute_core.so /work/Clean/ComputeLibrary/build/libarm_compute.so)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
set(tools /work/Clean/jenkins/toolchains/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu)
set(CMAKE_C_COMPILER ${tools}/bin/aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER ${tools}/bin/aarch64-linux-gnu-g++)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
```
