### ISSUE TITLE
error: unknown target CPU 'armv8-a'

### ISSUE THREAD

**Issue by peyer** [ARM-software/ComputeLibrary#726]
Cross-Compile
Source platform: ubuntu 16.04
Destination platform: RK3399 + android

I just download your project and used command below to compile entire project.
scons Werror=1 -j4 debug=0 asserts=1 neon=1 opencl=1 embed_kernels=1 os=android arch=arm64-v8a toolchain_prefix=xxx
However, the clang++ compiler return an error below
error: unknown target CPU 'armv8-a'
How can I solve it ?

**Comment by morgolock** [comment]
Hi @peyer 

What toolchain version are you working with? Please take a look at this link describing how to build ACL for android: https://arm-software.github.io/ComputeLibrary/v19.05/index.xhtml#S3_3_android

It seems your toolchain doesn't support armv8a.

**Comment by peyer** [comment]
@morgolock Sorry about reply you so late! I selected clang++ under ${NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin to compile project.

**Comment by morgolock** [comment]
Hi @peyer 

What NDK version are you running?

Have you created the standalone toolchain as explained in the documentation with the command `$NDK/build/tools/make_standalone_toolchain.py --arch arm64 --install-dir $MY_TOOLCHAINS/aarch64-linux-android-ndk-r17b --stl libc++ --api 21`?
