### ISSUE TITLE
How to install Arm Cross compiler toolchain on centos? 

### ISSUE THREAD

**Issue by shubh809** [ARM-software/ComputeLibrary#729]

**Comment by morgolock** [comment]
Hi @shubh809 
Please take a look at the documentation explaining how to build the library:
https://arm-software.github.io/ComputeLibrary/v19.05/index.xhtml#S3_2_linux

You can download the toolchain here: https://releases.linaro.org/components/toolchain/binaries/4.9-2016.02/

Hope this helps.
