### ISSUE TITLE
How to enable logging when running examples 

### ISSUE THREAD

**Issue by chunseoklee** [ARM-software/ComputeLibrary#731]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v19.02 Build options: {'arch': 'armv7a', 'opencl': '1', 'neon': '1', 'build_dir': 'armv7a-linux.release', 'examples': '0', 'os': 'linux', 'Werror': '0'} Git hash=cc7a0e1ec88138ff223f03a45cc459555df1babe

**Platform:**
Odroid XU4
**Operating System:**
ubuntu mate 16.04

**Problem description:**

I try to print log during example(graph_mobilenet_v2) execution.
First, I have built exmaple with :

```
scons -j8 neon=1 opencl=1 examples=1 embed_kernels=1 os=linux arch=armv7a Werror=1 debug=0 asserts=1 logging=1
```

But, no log shown during execution.

I also have add std::cout print into the runtime code like : 
```
@@ -39,6 +41,7 @@ OffsetMemoryPool::OffsetMemoryPool(IAllocator *allocator, BlobInfo blob_info)
 {
     ARM_COMPUTE_ERROR_ON(!allocator);
     _blob = _allocator->make_region(blob_info.size, blob_info.alignment);
+    std::cout << "OffsetMemPool Constructor" << std::endl;
 }
```

It does not work either. 

Please help me.

**Comment by morgolock** [comment]
Hi @chunseoklee 

To enable logging and output to std::cout please try recompiling with debug=1

**Comment by chunseoklee** [comment]
THANK YOU FOR HELP
