### ISSUE TITLE
How to get npy files for evaluating example/graph_inception_v3

### ISSUE THREAD

**Issue by chunseoklee** [ARM-software/ComputeLibrary#734]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v19.02 Build options: {'arch': 'armv7a', 'opencl': '1', 'neon': '1', 'build_dir': 'armv7a-linux.release', 'examples': '0', 'os': 'linux', 'Werror': '0'} Git hash=cc7a0e1ec88138ff223f03a45cc459555df1babe
**Platform:**
odroid-xu4
**Operating System:**
ubuntu mate 16.04

**Problem description:**

I'd like to evaluate graph_inception_v3 with real image file. 
But I have no idea how to get npy files. 
I found scripts/tensorflow_data_extractor.py script. But which specific models should I use for this script ? 

Thank you.

**Comment by morgolock** [comment]
Hi @chunseoklee 

Please take a look at the documentation on how to do this: https://arm-software.github.io/ComputeLibrary/v19.05/data_import.xhtml#tensorflow_frozen_result

**Comment by chunseoklee** [comment]
@morgolock Thank you for answer. But the doc does not have the link of inception model. There are so many inception v3 models. Which model should I use ? I have tested with http://download.tensorflow.org/models/inception_v3_2016_08_28.tar.gz, but exit with 
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!

ERROR in fill_tensor ./utils/Utils.h:450: Tensor dimensions mismatch 
!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by morgolock** [comment]
Hi @chunseoklee 

You can find the link to the model in the graph example https://github.com/ARM-software/ComputeLibrary/blob/master/examples/graph_inception_v3.cpp#L855
