### ISSUE TITLE
How to launch own kernel?

### ISSUE THREAD

**Issue by shubh809** [ARM-software/ComputeLibrary#735]
Is there any example of how should I use ARMCL APIs for launching my own kernel from scretch?

**Comment by morgolock** [comment]
Hi @shubh809 

Please take a look at the code below, you have to call kernel->configure(..) and the kernel->run(..).

Remember to always call tensor->allocate(..) after kernel->configure(..)

Any of the functions in the library basically do the same thing, they allocate tensors if required for intermediate results and then call the kernel's configure(..) and run(..) methods. The multi-threading is done in the CPPScheduler ( https://github.com/ARM-software/ComputeLibrary/blob/master/src/runtime/CPP/CPPScheduler.cpp#L281) by splitting the workload in a number of windows that normally matches the number of cpu cores detected on the system.

```
#include "arm_compute/runtime/Tensor.h"
#include "arm_compute/core/NEON/kernels/NEActivationLayerKernel.h"
#include "arm_compute/runtime/NEON/NEScheduler.h"
#include "tests/Utils.h"

#include <iostream>
#include <thread>

int main(int argc, char** argv)
{
    using namespace std;
    using namespace arm_compute;
    using namespace test;
    Tensor ne_src = test::create_tensor<Tensor>(TensorShape(8, 16), DataType::F32, 1);
    Tensor ne_dst = test::create_tensor<Tensor>(TensorShape(8, 16), DataType::F32, 1);
    NEActivationLayerKernel ne_act_layer_kernel;
    ne_act_layer_kernel.configure(&ne_src, &ne_dst, ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::LINEAR, 0.4f));
    ne_src.allocator()->allocate();
    ne_dst.allocator()->allocate();
    ThreadInfo th;
    th.cpu_info = &NEScheduler::get().cpu_info();

    Window window;
    window.use_tensor_dimensions(ne_src.info()->tensor_shape());

    {
        Iterator ne_it(&ne_src, window);
        execute_window_loop(window, [&](const Coordinates & )
        {
            // Copy one whole row:
            const auto val = static_cast <float> (rand()) / static_cast <float> (RAND_MAX);
            *reinterpret_cast<float *>(ne_it.ptr()) = val;
        },
        ne_it);
    }

    ne_act_layer_kernel.run(ne_act_layer_kernel.window(),th );

    {
         Iterator ne_it(&ne_dst, window);
         std::cout << "Output : " << std::endl;
         execute_window_loop(window, [&](const Coordinates & )  { std::cout << (*reinterpret_cast<float *>(ne_it.ptr())) << " ";},ne_it);
         std::cout << std::endl;
    }
```

**Comment by shubh809** [comment]
Let me be more specific, suppose we a this simple program in opencl
#include <CL/cl2.hpp> // OpenCL 2 C++ Bindings
#include <iostream>
#include <vector>
#include <algorithm>
#include<#include "arm_compute/runtime/CL/CLTensor.h">

/*
 * Returns a Platfrom supporting OpenCL 2 or an empty one
 */
cl::Platform findCL2Platform()
{
  std::vector<cl::Platform> platforms;
  cl::Platform::get(&platforms);

  for (auto &p : platforms) {
    std::string version = p.getInfo<CL_PLATFORM_VERSION>();
    if (version.find("OpenCL 2.") != std::string::npos) {
      return p;
    }
  }
  return cl::Platform();
}

/*
 * OpenCL Program Source
 */
const std::string rot13Kernel = R"====(
kernel void rot13(global char* in, global char* out)
{
  int num = get_global_id(0);
  char c = in[num];
  if ('a' <= c && c <= 'z') {
    out[num] = ((c - 'a') + 13) % 26 + 'a';
  } else if ('A' <= c && c <= 'Z') {
    out[num] = ((c - 'A') + 13) % 26 + 'A';
  } else {
    out[num] = c;
  }
}
)====";

int main(int argc, const char* argv[])
{
  if (argc != 1) {
      std::cerr << "Usage: " << argv[0] << "\n";
      std::cerr << "Reads a line from standard input and "
        "prints the rot13'ed text to the standard output.\n";
      return EXIT_FAILURE;
  }

  cl::Platform platform = findCL2Platform();

  if (0 == platform()) {
    std::cerr << "No OpenCL 2 platform found.\n";
    return EXIT_FAILURE;
  }


  cl::Platform defaultPlatform = cl::Platform::setDefault(platform);
  if (defaultPlatform != platform) {
    std::cerr << "Error setting default platform\n";
    return EXIT_FAILURE;
  }

  // Make OpenCL Program
  cl::Program program(rot13Kernel);

  try {
    // Compile
    program.build("-cl-std=CL2.0");
  }
  catch (cl::BuildError e) {
    // Catch Compile failture and print diagnostics
    std::cerr << "Erro building program helloworld.cl: " << e.what() << "\n";
    for (auto &pair : e.getBuildLog()) {
      std::cerr << pair.second << std::endl;
    }

    return EXIT_FAILURE;
  }


  // 
  // Get Input
  //
  std::string input;
  std::getline(std::cin, input); // only reads on line (not till EOF)
  if (std::cin.fail()) {
    std::cerr << "\nInput error\n";
    return EXIT_FAILURE;
  }

  size_t strlength = input.length();

  //
  // Setup Buffers
  //
  cl::Buffer inputBuffer(std::begin(input), std::end(input), true/*read only*/);

  cl::Buffer outputBuffer = cl::Buffer(
      CL_MEM_WRITE_ONLY | CL_MEM_HOST_READ_ONLY, 
      input.length() * sizeof(char));

  //
  // Make and run Kernel
  //
  auto kernel = cl::KernelFunctor<cl::Buffer, cl::Buffer>(program, "rot13");

  kernel(cl::EnqueueArgs(cl::NDRange(input.length())),
      inputBuffer, outputBuffer);


  //
  // Readback result
  //
  std::string output(input); // output is the same size as input
  cl::copy(outputBuffer, std::begin(output), std::end(output));

  std::cout << output << std::endl;

  return EXIT_SUCCESS;
}

Now is there any way of importing this code into armcl , basically what I want to use ICLTensor as input to kernel . Is there any elegant way to do this?

**Comment by morgolock** [comment]
Hi @shubh809 

I think the best option for this would be adding a new custom operator to the library, please take a look at the documentation for more details:  https://arm-software.github.io/ComputeLibrary/v19.05/add_operator.xhtml#S4_1_2_add_kernel
