### ISSUE TITLE
How to specify opencl version at build time?

### ISSUE THREAD

**Issue by shubh809** [ARM-software/ComputeLibrary#736]
Is there a way to specify version of opencl to be used at build time using scons or any other way ? 
Basically, the libOpenCL.so created after building the source code is not providing me functions like clCreateCommandQueueWithProperties (opencl version 2.0). So i guess the build version of source code is below 2.0.

**Comment by morgolock** [comment]
Hi @shubh809 

No, there is no way to choose the CL version at compilation time.

At least you need:
OpenCL 1.1 + cl_arm_non_uniform_work_group_size

The file libOpenCL.so created when building the library contains just placeholders for the CL functions, this is provided just to be able to build the library without having to get the actual file from the device. You can easily modify the stubs to add additional functions, you can find the code in https://github.com/ARM-software/ComputeLibrary/blob/master/opencl-1.2-stubs/opencl_stubs.c
