### ISSUE TITLE
create ICLTensor

### ISSUE THREAD

**Issue by shubh809** [ARM-software/ComputeLibrary#737]
Is there any way I can create an ICLTensor with specified size rather than shape? The created ICLTensor will be passed into Armcl APIs which will store output in it, will shape of output tensor will automatically inferred ?

**Comment by morgolock** [comment]
Hi @shubh809 

You could just use a 1D tensor shape with the size you need.
```
src.allocator()->init(TensorInfo(1024, Format::U8));
function.configure(src,dst):
src.allocator()->allocate();
dst.allocator()->allocate();
```

The function will auto initialise the shape of the output tensor if required.
