### ISSUE TITLE
Read and Write CLTensor

### ISSUE THREAD

**Issue by shubh809** [ARM-software/ComputeLibrary#739]
I want to execute a simple program of arm cl in which I have to first fill the CLTensor and then after execution of an API using given CLTensor as input I have to read the output. 
I have written a program below is there something I am missing in this?

#include "arm_compute/core/Types.h"
#include "arm_compute/runtime/CL/CLTensor.h"
#include "arm_compute/runtime/CL/CLTensorAllocator.h"
#include "arm_compute/runtime/CL/functions/CLGEMM.h"
#include "arm_compute/runtime/CL/functions/CLTranspose.h"
#include "arm_compute/runtime/CL/functions/CLConvolutionLayer.h"
#include "tests/SimpleTensor.h"
//#include "tests/CLAccessor.h"
#include "arm_compute/core/TensorShape.h"
#include "arm_compute/runtime/CL/CLTuner.h"
#include <iostream>
#include "utils/Utils.h"
using namespace std;
using namespace arm_compute;

template <typename U,typename T>
void fill_tensor(U &&tensor, const std::vector<T> &v)
{
        std::memcpy(tensor.buffer(), v.data(), sizeof(T) * v.size());
}

int main()
{
arm_compute::CLTuner tuner{};
 arm_compute::CLScheduler::get().default_init(&tuner);

arm_compute::CLGEMM gemm;
arm_compute::CLTranspose cl_transpose;

arm_compute::CLTensor src = test::create_tensor<CLTensor>(TensorShape(4, 3),DataType::F32);
arm_compute::CLTensor weight = test::create_tensor<CLTensor>(TensorShape(3,4), DataType::F32);
arm_compute::CLTensor out = test::create_tensor<CLTensor>(TensorShape(4, 4), DataType::F32);

 src.allocator()->allocate();
 weight.allocator()->allocate();
 out.allocator()->allocate();

 cl_transpose.configure(&src, &weight);

src.map();
 fill_tensor(src, std::vector<float> { -26, -19, 87, 86,
                                                          -81, -27, 58, 63,
                                                          -44, -15, 55, 36
                                                        });

  for(int i=0;i<12;i++) printf("%f ",src.buffer()[i]);
   printf("fill the tensor \n");

src.unmap();
cl_transpose.run();
//how to read data of weight?
src.allocator()->free();
weight.allocator()->free();
out.allocator()->free();

}
 

Although src.buffer() is giving zero for all index. If I fill buffer will it automatically fill the device memory ?

**Comment by morgolock** [comment]
Hi @shubh809 

You should move the calls to allocate() after configure()

To read the data from the tensor you could use execute_window_loop()
```
Window window;
window.use_tensor_dimensions(tensor.info()->tensor_shape());
Iterator it(&tensor, window);
execute_window_loop(window, [&](const Coordinates & )
{
         std::cout << (*reinterpret_cast<float *>(it.ptr())) << " ";
 },it);

std::cout << std::endl;
```

For more information about execute_window_loop please refer to the documentation: https://arm-software.github.io/ComputeLibrary/v19.05/architecture.xhtml#S4_6_4_working_with_objects

**Comment by shubh809** [comment]
can't I use buffer to fill the tensor as in this example?
https://github.com/ARM-software/ComputeLibrary/blob/514be65ad8d3340f53fd9591035352ed285811ba/tests/validation/CL/GenerateProposalsLayer.cpp
I have followed similar approach in above example but it buffer is not reflecting assigned values.

**Comment by morgolock** [comment]
Hi @shubh809 

Have you moved allocate() calls below configure()? You must always call allocate after configure.

The way to move data to/from ACL's tensors is as shown in the code above. Accessing the buffer as you do directly will read padding values, the tensor values in the buffer won't be stored contiguously because some function require padding for the computation.

**Comment by shubh809** [comment]
Hi morgolock,
I have done all the changes you have suggested, but the output tensor (c) is still filled with zero. Although when I am printing input tensor they have desired value. Please find below code:

#include "arm_compute/core/Types.h"
#include "arm_compute/runtime/CL/CLFunctions.h"
#include "arm_compute/runtime/CL/CLScheduler.h"
#include "arm_compute/runtime/CL/CLTuner.h"
#include "utils/Utils.h"

namespace armcl = arm_compute;
namespace armcl_utils = arm_compute::utils;

int main(int argc, char *argv[])
{
  int n = 3;
  int m = 2;
  int p = 4;

  std::vector<float> src_a = {2, 1,
                          6, 4,
                          2, 3};
  std::vector<float> src_b = {5, 2, 1, 6,
                          3, 7, 4, 1};
  std::vector<float> c_targets = {13, 11, 6, 13,
                                  42, 40, 22, 40,
                                  19, 25, 14, 15};

  armcl::CLTuner tuner{};
  armcl::CLScheduler::get().default_init(&tuner);

  armcl::CLTensor a{}, b{}, c{};
  float alpha = 1;
  float beta = 0;

  const armcl::TensorShape shape_a(m, n);
  const armcl::TensorShape shape_b(p, m);
 const armcl::TensorShape shape_c(p, n);

  a.allocator()->init(armcl::TensorInfo(shape_a, 1, armcl::DataType::F32));
  b.allocator()->init(armcl::TensorInfo(shape_b, 1, armcl::DataType::F32));
  c.allocator()->init(armcl::TensorInfo(shape_c, 1, armcl::DataType::F32));


  armcl::CLGEMM sgemm{};
  sgemm.configure(&a, &b, nullptr, &c, alpha, beta);

  a.allocator()->allocate();
  b.allocator()->allocate();
  c.allocator()->allocate();


  armcl::Window input_window;
a.map();
  input_window.use_tensor_dimensions(a.info()->tensor_shape());
  armcl::Iterator input_it(&a, input_window);

  std::cout << " Dimensions of the input's iterator:\n";
  std::cout << " X = [start=" << input_window.x().start() << ", end=" << input_window.x().end() << ", step=" << input_window.x().step() << "]\n";
  std::cout << " Y = [start=" << input_window.y().start() << ", end=" << input_window.y().end() << ", step=" << input_window.y().step() << "]\n";


 
  execute_window_loop(input_window, [&](const armcl::Coordinates & id)
                      {
                        std::cout << "Setting item [" << id.x() << "," << id.y() << "]\n";
                        *reinterpret_cast<float *>(input_it.ptr()) = src_a[id.y() * m + id.x()]; //
                      },
                      input_it);
a.unmap();
 

b.map();
  input_window.use_tensor_dimensions(b.info()->tensor_shape());
  armcl::Iterator input_it_b(&b, input_window);

  std::cout << " Dimensions of the input's iterator:\n";
  std::cout << " X = [start=" << input_window.x().start() << ", end=" << input_window.x().end() << ", step=" << input_window.x().step() << "]\n";
  std::cout << " Y = [start=" << input_window.y().start() << ", end=" << input_window.y().end() << ", step=" << input_window.y().step() << "]\n";


  // // Iterate through the elements of src_data and copy them one by one to the input tensor:
  execute_window_loop(input_window, [&](const armcl::Coordinates & id)
                      {
                        std::cout << "Setting item [" << id.x() << "," << id.y() << "]\n";
                        *reinterpret_cast<float *>(input_it.ptr()) = src_a[id.y() * m + id.x()]; //
                      },
                      input_it_b);
b.unmap();

  sgemm.run();

c.map();
 armcl::Window window;
window.use_tensor_dimensions(c.info()->tensor_shape());
armcl::Iterator it(&c, window);
execute_window_loop(window, [&](const armcl::Coordinates & )
{
         std::cout << (*reinterpret_cast<float *>(it.ptr())) << " ";
 },it);
std::cout << std::endl;
c.print(std::cout);
c.unmap();
  return 0;
}

I am missing something?
