### ISSUE TITLE
build examples failing

### ISSUE THREAD

**Issue by JJPiglet** [ARM-software/ComputeLibrary#74]
I succeed building the library natively for NEON, but when I try to compile an example, something wrong with the compile process, the error information is as follows:
g++:error: unrecognized comman line option '-mfpu=neon'

I would appreciate it if you can help me to solve this problem!

**Comment by morgolock** [comment]
Would you please share the command line you use to compile the example?

The first thing to check is if you are using the right compiler for the examples, is it the same you've used to compile the library?

**Comment by JJPiglet** [comment]
The compiler is gcc 4.9.1, which is also the compiler I used to compile the library. The command line to compile the example is:"g++ examples/neon_convolution.cpp test_helpers/Utils.cpp -I. -Iinclude -std=c++11 -mfpu=neon -larm_compute -o neon_convolution"

**Comment by morgolock** [comment]
From your command line I think you are compiling natively, is this correct? What system are you using to build the example?

The instructions in the documentation to build the examples are just for 32 bits platforms, the build system will compile for armv7a if you don't specify the target platform with the 'arch' options. If you are building for a 64 bit platform make sure you use arch=arm64-v8a.

**Comment by JJPiglet** [comment]
Yes, I'm compiling natively on an 64bit ARM platform. The OS is YHKylin, a kind of Linux system, which is not widely used. The command line I used to compile the example follows the ARM Computer Library documentation, while the documentation doesn't distinguish 64 bit platform from 32 bit one. So you mean it is only for 32 bit ones? And I should use command line with arch-arm64-v8a, which means the command line should be "g++ examples/neon_convolution.cpp test_helpers/Utils.cpp -I. -Iinclude -std=c++11 -mfpu=neon -larm_compute arch=arm64-v8a -o neon_convolution", is that right? And I tried it a moment ago, the same error happened.

**Comment by AnthonyARM** [comment]
There is no `-mfpu=neon` for armv8, if you remove this it should work.
When we wrote this part of the documentation we only supported armv7 and we forgot to update it when we added 64bit support, we'll fix this in one of the maintenance release.

**Comment by GeorgeARM** [comment]
Documentation fixed in v17.05.

**Comment by JJPiglet** [comment]
Sorry for forgetting to reply, I solved the problem following you guidance several days ago. Thank you very much~
