### ISSUE TITLE
Is there a way to  simultaneously run same neon function with different input 

### ISSUE THREAD

**Issue by waveajay** [ARM-software/ComputeLibrary#742]
I need to run same neon function with different input simultaneously

**Comment by morgolock** [comment]
Hi @waveajay 

It's very easy to do it, please take a look at this: https://github.com/ARM-software/ComputeLibrary/issues/728

Just replace the CL function by a Neon function and remove any calls to map()/unmap().

**Comment by waveajay** [comment]
Hi @morgolock I did that but program is getting  stuck

**Comment by morgolock** [comment]
Hi @waveajay 

Sorry, the CPU scheduler is not thread safe and using it from multiple threads might have undefined behaviour.

We are working on a fix for this problem.

**Comment by waveajay** [comment]
i am working on a face detector and i need calculate hog features in different scales.In order to increase the speed   I thought  calculate hog at 2 scales using multi threading.Is there any way to achieve that?

**Comment by morgolock** [comment]
Hi @waveajay 

The CPPScheduler will use as many threads as cores have been detected on your system and try to keep the cores busy with the computation. Assuming the computation of hog 1 uses all cpu cores, the computation of hog 2 will need to wait for cpu time and you won't see any big performance improvements in this case.
