### ISSUE TITLE
NEDeconvolutionLayer  with asymmetric padding

### ISSUE THREAD

**Issue by pranathibl** [ARM-software/ComputeLibrary#743]
Hi,

I was trying to use NEDeconvolutionLayer with asymmetric padding [T B L R]=[1 2 1 2]. I am getting a output mismatch.

Could you tell me if API supports asymmetric padding. 
what does inner_border_right, inner_border_top mean? aren't they the padding values which we pass in PadStrideInfo()?

Thanks,
Pranathi.

**Comment by morgolock** [comment]
Hi @pranathibl 

Thanks for reporting the problem, we are currently working on a fix for this.

**Comment by morgolock** [comment]
Hi @pranathibl 
Please take a look at this patch adding support for asymmetric padding:
https://review.mlplatform.org/#/c/ml/ComputeLibrary/+/1797/

**Comment by morgolock** [comment]
Hi @pranathibl 

Closing this issue as the patch has been merged now. Reopen if you still need support.
