### ISSUE TITLE
Issue while using "import_memory" when prebuilt arm-compte-linu binaries are used,

### ISSUE THREAD

**Issue by pranathibl** [ARM-software/ComputeLibrary#744]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

arm_compute_version=v19.05 Build options: {'pmu': '1', 'opencl': '1', 'embed_kernels': '1', 'arch': 'arm64-v8a', 'standalone': '0', 'neon': '1', 'build_dir': 'linux-arm64-v8a-neon-cl', 'debug': '0', 'extra_link_flags': '', 'validation_tests': '0', 'examples': '1', 'asserts': '0', 'mali': '1', 'benchmark_tests': '0', 'compiler_cache': 'ccache', 'extra_cxx_flags': '', 'os': 'linux', 'Werror': '1'} Git hash=4ba87dbdc3b22220eba4a792c1f5c87e7a88c7af

Trying to use prebuilt arm linux binaries provided by github.
We are using binaries under "linux-arm64-v8a-neon-cl" folder,
**Platform:**
armv8

**Operating System:**
Linux

We are trying to run convolution layer on Hikey 960 board.
when we try to run convolution layer using prebuilt ARM Compute library, We were running into issues.

I have attached the convolution layer and the Makefile.
[NeConv.txt](https://github.com/ARM-software/ComputeLibrary/files/3525530/NeConv.txt)
[Makefile.txt](https://github.com/ARM-software/ComputeLibrary/files/3525534/Makefile.txt)

**Reproduction steps**
make neconv
./neconvolution

  ***** Error in `./ne_convolution': free(): invalid pointer: 0x00000000319ceef8 ***
Aborted**

When we try running the same convolution layer with our own built Compute Library, It was working

scons Werror=0 -j8 debug=0 neon=1 opencl=0 os=linux arch=arm64-v8a 

openmp=1 cppthreads=1 examples=0 asserts=0 build=cross_compile 

So we couldn't figure what could be the issue with the prebuilt binaries of ARM Compute,

I tried using "18.05" version and the same issue exists there also.

Thanks,

**Comment by pranathibl** [comment]
We also tried using import_memory function with larger size, But the issue still exists in the prebuilt ARM Compute library.

**Comment by OphirCarmi** [comment]
I have the same problem

**Comment by uu-praveeng** [comment]
any update on this?

**Comment by pranathibl** [comment]
Hi,

We have used the shared wrapper for V 19.08 pre-built library(linux-arm64-v8a-neon)and we are facing the crash at import_memory on Hikey960.

Could you let us know what we are missing here?
Could you also share the info about the prebuilt library used, hardware board and make command used.

Thank you.

**Comment by morgolock** [comment]
Hi @pranathibl

I've just reproduced the crash using the prebuilt library, something is wrong and we'll have to look at it.

In the meantime you could do as described below which works fine:

I ran the import memory code I shared above using the branch `branches/arm_compute_19_08` or `master` on `git clone "ssh://morgolock@review.mlplatform.org:29418/ml/ComputeLibrary"`

The build command for the library being:
`PATH=$PATH:/work/Clean/jenkins/toolchains/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu/bin scons os=linux arch=arm64-v8a neon=1 gles_compute=0 opencl=0 validation_tests=1 benchmark_tests=0 benchmark_examples=0 validate_examples=0 debug=1 opencl=1 -j9`

The comand for the example:
`/work/Clean/jenkins/toolchains/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-g++ -ggdb3 NeConv.cpp -I. -std=c++11 -I. -I/work/Clean/ComputeLibrary/include -larm_compute -larm_compute_core  -lOpenCL -L/work/Clean/ComputeLibrary/build -L/work/Clean/ComputeLibrary/build/opencl-1.2-stubs -o conv`

```
root@acl_hikey_dev:~/tmp/pabtel01/graph# LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. ./conv
Before src.info()->total_size() :1105920
Before out_conv0.info()->total_size() :552960
After src.info()->total_size() :1105920
4 48 576 
After out_conv0.info()->total_size() :552960
Convolution Layer :11203.799805 ms
Convolution Layer :111.406998 ms
Convolution Layer :117.292000 ms
Convolution Layer :132.123993 ms
Convolution Layer :130.362000 ms
Convolution Layer :127.113998 ms
Convolution Layer :116.114998 ms
Convolution Layer :120.000000 ms
Convolution Layer :145.537994 ms
Convolution Layer :143.386002 ms
Convolution Layer :134.266998 ms
Convolution Layer :152.445007 ms
Convolution Layer :132.294998 ms
Convolution Layer :143.395996 ms
Convolution Layer :146.070007 ms
Convolution Layer :126.022003 ms
Convolution Layer :166.479996 ms
Convolution Layer :160.628998 ms
Convolution Layer :200.509003 ms
Convolution Layer :132.427994 ms
```

Hope this helps.

**Comment by uu-praveeng** [comment]
Hi ,

Is this issue fixed in the latest release? or do we have to continue with build and use approach.

Thank you,
Praveen.

**Comment by morgolock** [comment]
Hi @uu-praveeng 

You need to use the workaround.

Hope this helps.

**Comment by morgolock** [comment]
Hi @uu-praveeng 

This is a toolchain issue, you are likely to be building the test with a different toolchain than the one used for the prebuilt binaries.


There is no segfault if you build your test with
` $JENKINS_TOOLCHAINS/gcc-linaro-4.9-2016.02-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-g++ -std=c++11 -ggdb3 test.cpp -o test -I./ -I./include -larm_compute_core -larm_compute  -L./lib/linux-arm64-v8a-neon-debug/` and link with the prebuilt binaries: v20.02.1-linux

If you build with other toolchains please use the workaround mentioned above.

Hope this helps.

**Comment by GeorgeARM** [comment]
Hello @uu-praveeng,
Could you please also post the gcc version that you use.

**Comment by uu-praveeng** [comment]
Hi George,

We tried to use the native compiler present in the hikey 960. You can see the same in Makefile. Below is the native compiler version :

COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/6/lto-wrapper
Target: aarch64-linux-gnu
gcc version 6.5.0 20181026 (Ubuntu/Linaro 6.5.0-2ubuntu1~16.04).

Is this fix part of ACL v20.02.1 ?
If not,  if I build my application using  gcc-linaro-4.9-2016.02-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-g++, older ACL libraries will it still work?

Thank you,
Praveen.

**Comment by morgolock** [comment]
Hi @uu-praveeng 

This is still present in 20.02.1, please use the toolchain gcc-linaro-4.9-2016.02-x86_64_aarch64-linux-gnu to build the test. This workaround should solve the problem. We'll look into fixing this in the next release.

Hope this helps.

**Comment by GeorgeARM** [comment]
Hello @uu-praveeng,

The problem you are experiencing looks like a compiler compatibility issue. Truth be told gcc 4.9 is old and not supported any more. We will be bumping up the gcc version used to generate our prebuilt binaries to a later one possibly gcc 6 or 7 in the next release. 

Hope this helps,
George

**Comment by uu-praveeng** [comment]
Hi George,

I guess the conclusion is we have to use the same toolchain which is used for ACL prebuilt libraries present in GitHub to build the application .

But it is not possible always, because the  custom ARM boards will have native custom gcc toolchains, so the ACL prebuilt library in github may not be compatible and user needs to build his own ACL library. 

Let us know if we could find any solution related to this. Probably a cross compiled prebuilt library which works on standard boards like raspi, hikey

Thank you,
Praveen.
