### ISSUE TITLE
Does ACL support heterogenous computing Support?

### ISSUE THREAD

**Issue by abhajaswal** [ARM-software/ComputeLibrary#745]
Version -  19.05
**Platform:** arm
**Operating System:**  linux

Curenntly in Graph interface we set target on which ACL to run as NEON or CL !!

Is it possible to control target at which the compute library should run at Runtime?
If i have both CPU and GPU resource available.. 
Then is it possible to run few layers on CPU and few on GPU? or run time decide which part of the code to run on GPU and which one on CPU depending on resources available on system!!

**Comment by morgolock** [comment]
Hi @abhajaswal 

The graph api lets you choose a target at runtime but all the layers will be executed using the same target you've chosen.

If you want to run some layers on the GPU and others on the CPU I would suggest you take a look at the following example using the functions api:  https://github.com/ARM-software/ComputeLibrary/blob/master/examples/neoncl_scale_median_gaussian.cpp

With the functions, you could create a pipeline where you can choose exactly where each layer is going to run.

**Comment by abhajaswal** [comment]
In case i run target as CL

Is there a previlage to enable openCL to run on both CPU & GPU?
using CL_DEVICE_TYPE_{GPU/CPU} options?

What is the default DEVICE_TYPE SET?

**Comment by morgolock** [comment]
Hi @abhajaswal 

The code in ACL uses `CL_DEVICE_TYPE_DEFAULT` to get the list of devices and then it selects the first device in the list.

The code implementing this can be seen here:
https://github.com/ARM-software/ComputeLibrary/blob/master/src/runtime/CL/CLHelpers.cpp#L97

You could experiment with this making changes in that function, bear in mind that all OpenCL code in ACL has been specially optimised for ARM GPUs.

Hope this helps.
