### ISSUE TITLE
How to add jpeg image support to graph_yolov3.cpp under examples?

### ISSUE THREAD

**Issue by chetansarmak** [ARM-software/ComputeLibrary#747]
**Platform:Raspberry pi 3 B

**Operating System:Ubuntu mate

I am trying to test detection on jpeg images which I am not able to do.The support is only for the .ppm format ,what should be done to extend the support for jpeg?

TIA

**Comment by morgolock** [comment]
Hi @chetansarmak 

There is support for jpeg, you can pass the input image with the option `--image=./filename.jpeg`

**Comment by morgolock** [comment]
Closing by inactivity, reopen if you need support.
