### ISSUE TITLE
GNU ARM embedded toolchain compile error

### ISSUE THREAD

**Issue by vivek-path** [ARM-software/ComputeLibrary#75]
in sconscript I use

            prefix = "arm-none-eabi-"

I hit the following build error:

src/core/Error.cpp: In function 'void arm_compute::error(const char*, const char*, int, const char*, ...)':
src/core/Error.cpp:35:18: error: 'snprintf' is not a member of 'std'
     int offset = std::snprintf(out, sizeof(out), "in %s %s:%d: ", function, file, line);
                  ^
src/core/Error.cpp:36:60: error: 'vsnprintf' was not declared in this scope
     vsnprintf(out + offset, sizeof(out) - offset, msg, args);

**Comment by AnthonyARM** [comment]
This is a problem with your toolchain's libc implementation, unfortunately we can't fix it at the library's level. Please report the issue against the toolchain
