### ISSUE TITLE
can  MALI-T720 GPU use ACL  to run CNN ?

### ISSUE THREAD

**Issue by YouZengLi** [ARM-software/ComputeLibrary#750]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

**Platform:** 

**Operating System:**

**Problem description:**

we prepare to run cnn in mali T720 GPU ,but we notice that the device( mali T720 GPU  ) only support OpenCL1.1, can i get more message to

**Comment by morgolock** [comment]
Hi @YouZengLi 
To run the Gpu backend in ACL at least you need:
OpenCL 1.1 + cl_arm_non_uniform_work_group_size

Hope this helps.
