### ISSUE TITLE
Can l2normalize support be added to graph?

### ISSUE THREAD

**Issue by abhajaswal** [ARM-software/ComputeLibrary#751]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

**Platform:**

**Operating System:**

**Problem description:**

**Comment by morgolock** [comment]
Hi @abhajaswal 
Yes, it should be straight-forward because ACL's backends already implement L2NormalizeLayer.

Please take a look at the graph api code where the workloads are created
https://github.com/ARM-software/ComputeLibrary/blob/master/src/graph/backends/NEON/NEFunctionFactory.cpp#Lhttps://github.com/ARM-software/ComputeLibrary/blob/master/src/graph/GraphBuilder.cpp162

You should make changes to this code to instantiate a workload using NEL2NormalizeLayer.

Hope this helps.

**Comment by abhajaswal** [comment]
Thanks for the information .
I have created new Node for l2normalize in 
./arm_compute/graph/backends/FunctionHelpers.h

template <typename L2NormalizeFunction, typename TargetInfo>
std::unique_ptr<IFunction> create_l2normalize_layer(L2NormalizeLayerNode &node)
{
//  ARM_COMPUTE_UNUSED(ctx);

    validate_node<TargetInfo>(node, 1 /* expected inputs */, 1 /* expected outputs */);

    // Extract IO and info
    typename TargetInfo::TensorType *input     = get_backing_tensor<TargetInfo>(node.input(0));
    typename TargetInfo::TensorType *output    = get_backing_tensor<TargetInfo>(node.output(0));
    const unsigned int      axis = node.axis();
    const float      epi = node.epsilon();
    ARM_COMPUTE_ERROR_ON(input == nullptr);
    ARM_COMPUTE_ERROR_ON(output == nullptr);

    // Create and configure function
    auto func = support::cpp14::make_unique<L2NormalizeFunction>();
    func->configure(input, output, axis,epi);
    return std::move(func);
}

and created respective changes in src/graph/backends/CL/CLFunctionsFactory.cpp & NEON/NEFunctionsFactory.cpp 
case Nodetype::L2NormalizeLayer: 
return detail::create_l2normalize_layer<CLL2NormalizeLayer, CLTargetInfo>(*polymorphic_downcast<L2NormalizeLayerNode *>(node));

and 
       case NodeType::L2NormalizeLayer:
            return detail::create_l2normalize_layer<NEL2NormalizeLayer, NETargetInfo>(*polymorphic_downcast<L2NormalizeLayerNode *>(node));


COmpilation happened correctly.
I will check once this Layer  i run complete network

**Comment by abhajaswal** [comment]
I hope there wont be any other change required apart from above!!! Kindly guide if anything left out

**Comment by abhajaswal** [comment]
Also in case i just need a sub operation x = a-b
where a is variable tensor and b is always constant
For this also i need  to make a new graph node for backend support of CLArithmeticSubtraction or NEArithmeticSubtraction?

As the EltwiseLayer take substream type as arguments but i am not sure that this is valid for my network!!
I am unable to find the method by which i can load b which is 1x16 constant weight and a previous layer to make it as input to Eltwise Layer.

**Comment by abhajaswal** [comment]
Thanks @morgolock I was able to run the L2NormLayer graph Node with the suggestion

**Comment by abhajaswal** [comment]
But For adding the contant Node for Elementwise Layer i will need your suggestion.
Currently i have used a workaround to use batch norm instead of this.
