### ISSUE TITLE
How we can  mobilenet v2 example

### ISSUE THREAD

**Issue by waveajay** [ARM-software/ComputeLibrary#752]
How to run mobile net v2 example 
From where do we get numpy files?

**Comment by morgolock** [comment]
Hi @waveajay 

Please take a look at ACL's documentation explaining how to export a pre-trained model's parameters as numpy files:

https://arm-software.github.io/ComputeLibrary/v19.08/data_import.xhtml

**Comment by waveajay** [comment]
Thank you, but from where I can download python script tf_frozen_model_extractor.py

**Comment by morgolock** [comment]
Hi @waveajay 

`git clone "https://review.mlplatform.org/ml/ComputeLibrary"`

In the `scripts` folder.

**Comment by waveajay** [comment]
Hi @morgolock,
Thank you for your replay, but the link you shared is not working. It is showing not found

**Comment by morgolock** [comment]
Hi @waveajay 

Please try this command from the terminal: `git clone "https://review.mlplatform.org/ml/ComputeLibrary" && ls ComputeLibrary/scripts -al`

**Comment by waveajay** [comment]
Thank you
