### ISSUE TITLE
graph_alexnet results

### ISSUE THREAD

**Issue by jinz2014** [ARM-software/ComputeLibrary#758]
I built the compute library successfully using scons. scons uses regular GNU compiler (g++) to build on the first-generation X-gene server. 

arm_compute_version=v19.08 Build options: {'arch': 'arm64-v8a', 'opencl': '1', 'neon': '1', 'build': 'native', 'debug': '0', 'os': 'linux', 'Werror': '1'} Git hash=975dfe175e3d7c62c27598b1c0e8e77ed90df463

When I run the graph_alexnet example, it gives the same incorrect results regardless of the input images.  May I use regular g++ to build the library ? If not, which compiler should I use to build the library on the server CPU ?  Thanks for your instructions. 

Threads : 1
Target : CL
Data type : F32
Data layout : NHWC
Tuner enabled? : false
Cache enabled? : true
Tuner mode : Normal
Tuner file :
Fast math enabled? : false
Image file : school_bus.ppm
Labels file : labels.txt

---------- Top 5 predictions ----------

0.0010 - [id = 672], n03792972 mountain tent
0.0010 - [id = 657], n03773504 missile
0.0010 - [id = 658], n03775071 mitten
0.0010 - [id = 659], n03775546 mixing bowl
0.0010 - [id = 660], n03776460 mobile home, manufactured home

Test passed

**Comment by morgolock** [comment]
Hi @jinz2014 

Please take a look at ACL's documentation: https://arm-software.github.io/ComputeLibrary/v19.08/index.xhtml#S3_2_linux

For linux we recommend at least:

-  gcc-linaro-4.9-2016.02-x86_64_arm-linux-gnueabihf
-  gcc-linaro-4.9-2016.02-x86_64_aarch64-linux-gnu

As for the example's results, could you please share the command you've used to run it as well as the file school_bus.ppm?

**Comment by jinz2014** [comment]
Are these compilers targeting a specific type of ARM CPUs ?  The doc says it is Cortex CPU.   
gcc-linaro-4.9-2016.02-x86_64_arm-linux-gnueabihf
gcc-linaro-4.9-2016.02-x86_64_aarch64-linux-gnu

For server CPUs, should I install them as well ?  


The command is shown below:

arm64:~/ComputeLibraryTutorial/alexnet$ ls
cnn_data  compute_library_alexnet.zip  go_kart.ppm  gold_fish.ppm  gondola.ppm  labels.txt  README  school_bus.ppm
arm64:~/ComputeLibraryTutorial/alexnet$  ~/ComputeLibrary/build/examples/graph_alexnet --target=NEON --threads=1 --image=school_bus.ppm --labels=labels.txt

/home/cc/ComputeLibrary/build/examples/graph_alexnet

Threads : 1
Target : NEON
Data type : F32
Data layout : NHWC
Tuner enabled? : false
Cache enabled? : false
Tuner mode : Normal
Tuner file :
Fast math enabled? : false
Image file : school_bus.ppm
Labels file : labels.txt

---------- Top 5 predictions ----------

0.0010 - [id = 672], n03792972 mountain tent
0.0010 - [id = 657], n03773504 missile
0.0010 - [id = 658], n03775071 mitten
0.0010 - [id = 659], n03775546 mixing bowl
0.0010 - [id = 660], n03776460 mobile home, manufactured home

Test passed

**Comment by morgolock** [comment]
Hi @jinz2014 

Yes these compilers are for two different cpu architectures:

Both compilers build binaries for Linux OS.

gcc-linaro-4.9-2016.02-x86_64_arm-linux-gnueabihf is used to build the library for armv7a.

and gcc-linaro-4.9-2016.02-x86_64_aarch64-linux-gnu is used to build for armv8a (aarch64)

Your server is likely to be at least armv8a, could you please share the output of the command: `lscpu && cat /proc/cpuinfo` ?

As for the wrong results, I think the problem might be in the fact you're not telling the test where the model's weights are located, you have to use the `--data='/path/to/weights/'` option for that. Please take a look at the documentation on how to do that: https://arm-software.github.io/ComputeLibrary/v19.08/data_import.xhtml#validate_examples

**Comment by jinz2014** [comment]
Thanks for your solution.

There are eight processors.   Could you please let me know how I can increase the BogoMIPS ?  I am not able to get the frequency of the processor.  How can I boost the CPU frequency as a root user ?

processor       : 0
BogoMIPS        : 100.00
Features        : fp asimd evtstrm
CPU implementer : 0x50
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0x000
CPU revision    : 1

**Comment by morgolock** [comment]
Hi @jinz2014 

From the output you've shared, it looks like there is only one CPU and it's aarch64.

If you're root you can play with disabling power management and changing the cpu frequency to increase performance.

**Comment by jinz2014** [comment]
Okay. I have a question about `label.txt`. Your document mentions the extraction of data from a trained model, but I am not clear how the label  is created, and if it is different for each model.

Thanks

**Comment by morgolock** [comment]
Hi @jinz2014 

The graph example should not crash. Could you please share the command you use to run vgg16?

Quoting the documentation:
> where: validation file is a plain document containing a list of images along with their expected label value. e.g:
val_00000001.JPEG 65
val_00000002.JPEG 970
val_00000003.JPEG 230
val_00000004.JPEG 809
val_00000005.JPEG 516

**Comment by meitiever** [comment]
Run the alexnet example: 
./build/examples/graph_alexnet \
--data=../assets_alexnet \
--target=NEON \
--threads=2 \
--image=../assets_alexnet/go_kart.ppm \
--labels=../assets_alexnet/labels.txt

I got this output:
./build/examples/graph_alexnet

Threads : 2
Target : NEON
Data type : F32
Data layout : NHWC
Tuner enabled? : false
Cache enabled? : false
Tuner mode : Normal
Tuner file :
Fast math enabled? : false
Data path : /home/pi/Documents/assets_alexnet
Image file : /home/pi/Documents/assets_alexnet/go_kart.ppm
Labels file : /home/pi/Documents/assets_alexnet/labels.txt

---------- Top 5 predictions ----------

1.0000 - [id = 672], n03792972 mountain tent
1.0000 - [id = 657], n03773504 missile
1.0000 - [id = 658], n03775071 mitten
1.0000 - [id = 659], n03775546 mixing bowl
1.0000 - [id = 660], n03776460 mobile home, manufactured home

Test passed

any idea? and i tested this example on two device and the output is the same.
