### ISSUE TITLE
question about cl_kernel header file

### ISSUE THREAD

**Issue by hxxfff** [ARM-software/ComputeLibrary#759]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

**Platform:**

**Operating System:**

**Problem description:**
question about cl_kernel header file: 
when call clCreateProgramWithSource, how are the cl headers in  "ComputeLibrary\src\core\CL\cl_kernels" loaded?
For example,  in example "neoncl_scale_median_gaussian.cpp",  "scale.cl" is loaded, there is " #include "helpers.h" in , but  when is the "helpers.h" loaded to the program? I can't find it.

**Comment by morgolock** [comment]
Hi @hxxfff 

Please take a look at the CLKernelLibrary class, the kernels are embedded in the library's binary:

https://github.com/ARM-software/ComputeLibrary/blob/master/src/core/CL/CLKernelLibrary.cpp

Hope this helps.

**Comment by hxxfff** [comment]
Hi, 

If EMBEDDED_KERNELS is defined, the headers is included in the generated *.clembed kernels. 
but , if EMBEDDED_KERNELS is not defined, the header would not be included.
thanks,

**Comment by morgolock** [comment]
Hi @hxxfff 

Yes, if the library is compiled with the option embed_kernels=false, then it'll try to load the opencl kernels source code from the file system. Take a look at the source code: https://github.com/ARM-software/ComputeLibrary/blob/master/src/core/CL/CLKernelLibrary.cpp#L1160

When embed_kernels=true, the opencl code is inserted in the shared library binary.
