### ISSUE TITLE
Building examples fail with scons on target platform

### ISSUE THREAD

**Issue by mike-a-collins** [ARM-software/ComputeLibrary#76]
I am natively compiling the library on an Asus Tinker Board and when running the following command scons Werror=1 -j8 debug=0 neon=0 opencl=1 os=linux arch=armv7a build=native

It fails at the following step:
g++ -o build/cl_convolution build/examples/cl_convolution.o build/test_helpers/Utils.o -Lbuild -L. -Lbuild -L. -larm_compute -lOpenCL

with the following:
build/examples/cl_convolution.o: In function `main_cl_convolution(int, char const**)':
cl_convolution.cpp:(.text+0x186): undefined reference to `clRetainContext'
cl_convolution.cpp:(.text+0x23a): undefined reference to `clReleaseContext'
cl_convolution.cpp:(.text+0x264): undefined reference to `clReleaseContext'
cl_convolution.cpp:(.text+0x2c4): undefined reference to `clRetainContext'
cl_convolution.cpp:(.text+0x32c): undefined reference to `clRetainCommandQueue'
cl_convolution.cpp:(.text+0x340): undefined reference to `clReleaseContext'
cl_convolution.cpp:(.text+0x364): undefined reference to `clReleaseCommandQueue'
cl_convolution.cpp:(.text+0x3a0): undefined reference to `clReleaseContext'
cl_convolution.cpp:(.text+0x500): undefined reference to `clFinish'
...
build/libarm_compute.so: undefined reference to `clBuildProgram'
build/libarm_compute.so: undefined reference to `clEnqueueNDRangeKernel'
build/libarm_compute.so: undefined reference to `clSetKernelArg'
build/libarm_compute.so: undefined reference to `clEnqueueUnmapMemObject'
build/libarm_compute.so: undefined reference to `clEnqueueWriteBuffer'
build/libarm_compute.so: undefined reference to `clEnqueueReadBuffer'
build/libarm_compute.so: undefined reference to `clGetProgramBuildInfo'
build/libarm_compute.so: undefined reference to `clRetainProgram'
build/libarm_compute.so: undefined reference to `clEnqueueMapBuffer'
build/libarm_compute.so: undefined reference to `clCreateProgramWithBinary'
build/libarm_compute.so: undefined reference to `clReleaseProgram'
build/libarm_compute.so: undefined reference to `clFlush'
build/libarm_compute.so: undefined reference to `clGetProgramInfo'
build/libarm_compute.so: undefined reference to `clCreateKernel'
build/libarm_compute.so: undefined reference to `clRetainKernel'
build/libarm_compute.so: undefined reference to `clCreateBuffer'
build/libarm_compute.so: undefined reference to `clCreateProgramWithSource'
collect2: error: ld returned 1 exit status
scons: *** [build/cl_convolution] Error 1
scons: building terminated because of errors.

I have looked at my ldconfig cache and it has the following libraries listed for OpenCL:
libOpenCL.so.1 (libc6,hard-float) => /usr/lib/libOpenCL.so.1
libOpenCL.so (libc6,hard-float) => /usr/lib/libOpenCL.so

Can't for the life of me figure out what's the problem.  I am running a yocto build with the rockchip-mali package installed. And it states that it provides the libOpenCL.so library:
Package: rockchip-mali
Architecture: armhf
Version: git-r0
Priority: optional
Section: libs
Maintainer: Jacob Chen <jacob2.chen@rock-chips.com>
Provides: libEGL.so, libGLESv1_CM.so, libGLESv2.so, libOpenCL.so, libegl, libgbm, libgbm.so, libgles1, libgles2, libglesv1-cm1, libglesv2-2, libwayland-egl.so
Depends: libc6 (>= 2.24), libdrm2 (>= rk)
Conflicts: libegl, libgbm, libgles1, libgles2, libglesv1-cm1, libglesv2-2
Replaces: libegl, libgbm, libgles1, libgles2, libglesv1-cm1, libglesv2-2
Filename: ./rockchip-mali_git-r0_armhf.deb
Size: 1627388
MD5sum: 3d71c26f2b899008669eb0fa2e1449d9
SHA1: 5c50841341a6c23ea992ee1330ad51bb7fe24ce6
SHA256: c5c3abde43695043715de31b0ce094e3c6e041d14f4944faadfaecb2d5df443f
SHA512: cb4fe966ca3339816a7583ab30f249e02eefd208463bc56f4804c58200c8dda30e918fd30d8993effac4e747da0a10fd9b2ef3b7a87e7dab4a40767732120c33
Description: rockchip-mali version git-r0
 GLES libraries for Rockchip SoCs for a family of Mali GPU
Description-md5: b88be0e208b88029b2e95e85d348bb80
OE: rockchip-mali
PackageArch: cortexa17hf-neon-vfpv4

Any assistance would be greatly appreciated!

**Comment by mike-a-collins** [comment]
Ok, so I figured out that I had the wrong version of libmali.so with the strings command, i.e. no cl stuff in the library, and I copied over the right one and everything compiled fine.  I moved libarm_compute_core.so and libarm_compute.so to /usr/lib and I get the following when running cl_convolution:
Usage: ./build/cl_convolution [input_image.ppm]

No input_image provided, creating a dummy 640x480 image
!!!!!!!!!!!!!!!!!!!!!!!!!!!

ERROR in load_program src/core/CL/CLKernelLibrary.cpp:553: Kernel file ./cl_kernels/convolution3x3.cl does not exist. No such file or directory
!!!!!!!!!!!!!!!!!!!!!!!!!!!

Test FAILED

I couldn't find a cl_kernels directory on github, so I don't know if this is supposed to be generated by the program or not.  Seems as if loading the kernel isn't working, any hints on where I should look next?

Thanks

**Comment by mike-a-collins** [comment]
Well, I feel like an idiot.  Just got done RTFM and stumbled upon the following:
embed_kernels: For OpenCL only: set embed_kernels=1 if you want the OpenCL kernels to be built in the library's binaries instead of being read from separate ".cl" files. If embed_kernels is set to 0 then the application can set the path to the folder containing the OpenCL kernel files by calling CLKernelLibrary::init(). By default the path is set to "./cl_kernels".

Rebuilding with embed_kernels=1 resolved all my issues!!!

**Comment by AnthonyARM** [comment]
Glad you managed to solve your problems
FYI: the cl_kernels are in `src/core/CL/cl_kernels`
