### ISSUE TITLE
scale_event is never released,  ComputeLibrary\examples\cl_events.cpp

### ISSUE THREAD

**Issue by hxxfff** [ARM-software/ComputeLibrary#760]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

**Platform:**

**Operating System:**

**Problem description:**
scale_event in the code below is never released

    void do_run() override
    {
        // Enqueue and flush the scale OpenCL kernel:
        scale.run();
        // Create a synchronisation event between scale and median:
        cl::Event scale_event = CLScheduler::get().enqueue_sync_event();
        // Enqueue and flush the median OpenCL kernel:
        median.run();
        // Enqueue and flush the Gaussian OpenCL kernel:
        gauss.run();

        //Make sure all the OpenCL jobs are done executing:
        scale_event.wait();        // Block until Scale is done executing (Median3x3 and Gaussian5x5 might still be running)
        CLScheduler::get().sync(); // Block until Gaussian5x5 is done executing
    }

**Comment by morgolock** [comment]
Hi @hxxfff 
Have you made any changes to the test https://github.com/ARM-software/ComputeLibrary/blob/master/examples/cl_events.cpp ?

I could not reproduce the problem on my device:

```
root@acl_hikey_dev:~/tmp/pabtel01/graph# LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. ./cl_events 

./cl_events

Usage: ./build/cl_events [input_image.ppm]

No input_image provided, creating a dummy 640x480 image

Test passed
```

What device do you use to run the test?

**Comment by hxxfff** [comment]
No, I have not test it. scale_event should be released, in my opinion. 




    


On 10/24/2019 20:42, Pablo Marquez wrote: Hi @hxxfff
Have you made any changes to the test https://github.com/ARM-software/ComputeLibrary/blob/master/examples/cl_events.cpp ?
I could not reproduce the problem on my device:
root@acl_hikey_dev:~/tmp/pabtel01/graph# LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. ./cl_events  

./cl_events

Usage: ./build/cl_events [input_image.ppm]

No input_image provided, creating a dummy 640x480 image

Test passed

What device do you use to run the test?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ARM-software/ComputeLibrary/issues/760?email_source=notifications\u0026email_token=ABYU4QENRWST2ZIEIVL6NJDQQGJZNA5CNFSM4I7YHBO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECE4FWQ#issuecomment-545899226",
"url": "https://github.com/ARM-software/ComputeLibrary/issues/760?email_source=notifications\u0026email_token=ABYU4QENRWST2ZIEIVL6NJDQQGJZNA5CNFSM4I7YHBO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECE4FWQ#issuecomment-545899226",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by morgolock** [comment]
Hi @hxxfff 

What device are you running the test? Have you tried running other tests?

**Comment by hxxfff** [comment]
Can you find the call of clReleaseEvent(scale_event）in the code? 




    


On 11/06/2019 23:29, Pablo Marquez wrote: Hi @hxxfff
What device are you running the test? Have you tried running other tests?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ARM-software/ComputeLibrary/issues/760?email_source=notifications\u0026email_token=ABYU4QAIKQNACILYHQR5E3DQSLPGXA5CNFSM4I7YHBO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDG5XAQ#issuecomment-550361986",
"url": "https://github.com/ARM-software/ComputeLibrary/issues/760?email_source=notifications\u0026email_token=ABYU4QAIKQNACILYHQR5E3DQSLPGXA5CNFSM4I7YHBO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDG5XAQ#issuecomment-550361986",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by morgolock** [comment]
Hi @hxxfff 

Where are you running the example? On a phone? what device? What OS?

**Comment by hxxfff** [comment]
I haven’t run it. 




    


On 11/07/2019 18:23, Pablo Marquez wrote: Hi @hxxfff
Where are you running the example? On a phone? what device? What OS?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ARM-software/ComputeLibrary/issues/760?email_source=notifications\u0026email_token=ABYU4QEJTM2YHGPCWUDTHW3QSPUB5A5CNFSM4I7YHBO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDL5WLI#issuecomment-551017261",
"url": "https://github.com/ARM-software/ComputeLibrary/issues/760?email_source=notifications\u0026email_token=ABYU4QEJTM2YHGPCWUDTHW3QSPUB5A5CNFSM4I7YHBO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDL5WLI#issuecomment-551017261",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by morgolock** [comment]
Hi @hxxfff 

No, there is no need to call `clReleaseEvent()`

The CLScheduler is just adding a marker in the command queue: https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/CL/CLScheduler.h#L163

See https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/clEnqueueMarker.html
