### ISSUE TITLE
Need more info to create ACL Tensor

### ISSUE THREAD

**Issue by nhkrishna** [ARM-software/ComputeLibrary#761]
Hi,

Could you elaborate more on second argument for the TensorInfo constructor?

When i go through [documentation ](https://arm-software.github.io/ComputeLibrary/v19.05/classarm__compute_1_1_tensor_info.xhtml#a734bdd7d65d40aa012ebeb172fda955a), it was saying as below

num_channels | It indicates the number of channels for each tensor element
-- | --

But we we are already specifying the num_channels in the Tenshape(Width, Height, Channels). Then why again num_channels required(second argument). Its little bit confusing for me and if i use 1 inplace of second argument (num_channels) then it works fine with out any issue.

Thanks,
Hari

_Originally posted by @nhkrishna in https://github.com/ARM-software/ComputeLibrary/issues/702#issuecomment-542608639_

**Comment by morgolock** [comment]
Hi @nhkrishna 

You're right, it's redundant and unsafe to have both a tensor_shape and num_channels in the constructor. All we need to specify the number of channels is a tensor_shape and a data_layout.

What function does not work if you do not use 1u for the 2nd argument?

**Comment by nhkrishna** [comment]
Hi @morgolock ,

By default i'm using 1 in place of second argument. I haven't tried using other than one.

**Comment by morgolock** [comment]
Hi @nhkrishna 

Using 1u is fine, we'll be addressing this api problem.

Closing the issue, if you require help please reopen it.
