### ISSUE TITLE
int8 gemm full example

### ISSUE THREAD

**Issue by jinz2014** [ARM-software/ComputeLibrary#763]
If it is not available, could you please provide an example that shows the entire process of int8 GEMM ?  This includes quantization, calling the ARM Compute Library function, and dequantization ? 

Thanks

**Comment by morgolock** [comment]
Hi @jinz2014 

We have an example for sgemm: https://github.com/ARM-software/ComputeLibrary/blob/master/examples/neon_sgemm.cpp

You could easily modify this example to use the function https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/NEON/functions/NEGEMMLowpMatrixMultiplyCore.h

If you need to quantize/dequantize before/after calling NEGEMMLowpMatrixMultiplyCore, you could use:
https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/NEON/functions/NEDequantizationLayer.h
https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/NEON/functions/NEQuantizationLayer.h

Hope this helps.

**Comment by RuABraun** [comment]
I want to use the library for SGEMM and have a question, how could one initialize a tensor such as `src0` in the example (I'm guessing `src0`, `src1` and `src2` correspond to A, B, C in SGEMM btw) from an existing float array?

**Comment by gmiodice** [comment]
Hi @RuABraun ,

many thanks for using ACL! :) A good starting point for initializing a tensor can be found at this link https://arm-software.github.io/ComputeLibrary/v19.08/architecture.xhtml#S4_6_4_working_with_objects .

Let us know if you need any further information.

Hope this can help
