### ISSUE TITLE
changing the Input _accessor for graph 

### ISSUE THREAD

**Issue by anathema43** [ARM-software/ComputeLibrary#764]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
=v19.08 Build options: {'': '', 'arch': 'armv7a', 'opencl': '1', 'neon': '1', 'debug': '1', 'os': 'linux', 'Werror': '1'} Git hash=975dfe175e3d7c62c27598b1c0e8e77ed90df463

**Platform:**Raspberry pi B+

**Operating System:** Ubuntu Mate 18.0.4

  creating an  simple input_accessor for graph that's takes input from a buffer

**Problem description:**
1) I modified the graph_alexnet to run my small graph, i was wondering how can  i make the get_input accessor take input as a buffer and not image or numpy?
2) In neon_cnn example how can put the weight and biases value to the tensors

**Comment by GeorgeARM** [comment]
Hello @anathema43,

You could replace the input accessor with a custom made one that takes some buffer and fills the tensor. Should be quite easy to do. You just need to implement the `ITensorAccessor` interface. You can use the same if you have your weights and biases loaded into buffers already.
Hope this helps.
