### ISSUE TITLE
how to use multiple CPU cores when using multi-threading

### ISSUE THREAD

**Issue by ZhuXingJune** [ARM-software/ComputeLibrary#765]
I want to use multiple Arm CPU cores to calculate convolution layers in parallle, but it didn't work when I use "NEScheduler::get().set_num_threads()".
When I use four threads, time of running a convolution layer is more than using one thread.
Is a thread corresponding to a CPU core?
What should I do if I want to use multiple threads in multiple cores?

The same happens when I run "examples/graph_shufflenet.cpp", and using "--threads=2" is slower than "--threads=1".
What does "--threads" mean?

I will be very grateful for your answer.

**Comment by morgolock** [comment]
Hi @ZhuXingJune 

Would you please tell us what commands you use for:

1. building the library
2. running the graph example

It would also help to know what device are you running the example and how you measure the performance?

I ran a quick test an I do not see the issue you mentioned:
```
root@acl_hikey_8:~/tmp/pabtel01# LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. ./benchmark_graph_shufflenet --example_args=--TARGET=NEON,--threads=1 --instruments=WALL_CLOCK_TIMER_MS --iterations=15
Version = arm_compute_version=v0.0-unreleased Build options: {'opencl': '0', 'standalone': '0', 'os': 'linux', 'test_filter': 'ConvolutionLayer.cpp', 'gles_compute': '0', 'neon': '1', 'debug': '0', 'validation_tests': '1', 'examples': '1', 'asserts': '1', 'benchmark_tests': '0', 'validate_examples': '0', 'arch': 'arm64-v8a', 'Werror': '1', 'benchmark_examples': '1'} Git hash=1dce3101ef8d77c8cf0af7dfd4af6595a0136b91
CommandLine = ./benchmark_graph_shufflenet --example_args=--TARGET=NEON,--threads=1 --instruments=WALL_CLOCK_TIMER_MS --iterations=15 
Iterations = 15
Running [0] 'Examples/benchmark_graph_shufflenet'
Threads : 1
Target : NEON
Data type : F32
Data layout : NHWC
Tuner enabled? : false
Cache enabled? : false
Tuner mode : Normal
Tuner file : 
Fast math enabled? : false

Model: Shufflenet_1_g4
  Wall clock/Wall clock time:    AVG=678.9606 ms, STDDEV=0.06 %, MIN=678.2670 ms, MAX=679.7530 ms, MEDIAN=678.9270 ms
Executed 1 test(s) (1 passed, 0 expected failures, 0 failed, 0 crashed, 0 disabled) in 10 second(s)
root@acl_hikey_8:~/tmp/pabtel01# LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. ./benchmark_graph_shufflenet --example_args=--TARGET=NEON,--threads=4 --instruments=WALL_CLOCK_TIMER_MS --iterations=15
Version = arm_compute_version=v0.0-unreleased Build options: {'opencl': '0', 'standalone': '0', 'os': 'linux', 'test_filter': 'ConvolutionLayer.cpp', 'gles_compute': '0', 'neon': '1', 'debug': '0', 'validation_tests': '1', 'examples': '1', 'asserts': '1', 'benchmark_tests': '0', 'validate_examples': '0', 'arch': 'arm64-v8a', 'Werror': '1', 'benchmark_examples': '1'} Git hash=1dce3101ef8d77c8cf0af7dfd4af6595a0136b91
CommandLine = ./benchmark_graph_shufflenet --example_args=--TARGET=NEON,--threads=4 --instruments=WALL_CLOCK_TIMER_MS --iterations=15 
Iterations = 15
Running [0] 'Examples/benchmark_graph_shufflenet'
Threads : 4
Target : NEON
Data type : F32
Data layout : NHWC
Tuner enabled? : false
Cache enabled? : false
Tuner mode : Normal
Tuner file : 
Fast math enabled? : false

Model: Shufflenet_1_g4
  Wall clock/Wall clock time:    AVG=243.7581 ms, STDDEV=2.46 %, MIN=234.5440 ms, MAX=253.4880 ms, MEDIAN=245.2870 ms
Executed 1 test(s) (1 passed, 0 expected failures, 0 failed, 0 crashed, 0 disabled) in 3 second(s)
```

**Comment by ZhuXingJune** [comment]
Hi @morgolock 

1. building the library:
    scons Werror=1 debug=0 asserts=0 neon=1 opencl=0 examples=1 cppthreads=1 build=native -j4

2. running the graph example:
   g++ examples/graph_mobilenet.cpp utils/Utils.cpp utils/GraphUtils.cpp utils/CommonGraphOptions.cpp -I. -Iinclude -std=c++11 -Lbuild -L. -larm_compute_graph -larm_compute -larm_compute_core -Wl,--allow-shlib-undefined -o examples/graph_mobilenet

  ./examples/graph_shufflenet

3. I test on Raspberry Pi Armv7.

4. I test the time:
        start = clock();
        graph.run();
        end = clock();
        cpu_time_used = ((double) (end - start)) / CLOCKS_PER_SEC;

**Comment by morgolock** [comment]
Hi @ZhuXingJune 

Please try building the library with benchmark_examples=1, this will create the benchmark_graph_shufflenet which then you can use to measure performance with any of the instruments

```
--instruments={NONE,WALL_CLOCK_TIMER,WALL_CLOCK_TIMER_MS,WALL_CLOCK_TIMER_S,SCHEDULER_TIMER,SCHEDULER_TIMER_MS,SCHEDULER_TIMER_S,WALL_CLOCK_TIMESTAMPS,WALL_CLOCK_TIMESTAMPS_MS,WALL_CLOCK_TIMESTAMPS_S,SCHEDULER_TIMESTAMPS,SCHEDULER_TIMESTAMPS_MS,SCHEDULER_TIMESTAMPS_S,ALL,}[,{...}[,...]] - Set the profiling instruments to use
```

I've noticed you ran the test on armv7a while I did on armv8a, I think you should see the same results as in armv8a.

**Comment by ZhuXingJune** [comment]
Hi @morgolock 

I built the library using:
"scons Werror=1 debug=0 asserts=0 neon=1 opencl=0 benchmark_examples=1 cppthreads=1 build=native -j4",
but I didn't find where "benchmark_graph_shufflenet" is.

By the way, I use the latest version of ACL (v19.08).

**Comment by dujiangsu** [comment]
I met this problem too, no matter I compile the library with cppthreads=1 or openmp=1. I tested it on both arm64-v8a server and armv7a. However, the more threads I set, the less performance I got.

**Comment by dujiangsu** [comment]
Btw, the %CPU will never exceed 100%.

**Comment by morgolock** [comment]
Hi @ZhuXingJune 

The benchmark examples are only available when you clone from the public repository: `git clone "https://review.mlplatform.org/ml/ComputeLibrary"`

Please try building them and running the test on your device.
