### ISSUE TITLE
Failed to build ComputeLibrary for arm64

### ISSUE THREAD

**Issue by jishminor** [ARM-software/ComputeLibrary#767]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
Source pulled from master branch as of commit id: 1dce3101ef8d77c8cf0af7dfd4af6595a0136b9

**Platform:**
x86
GCC Version: 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.9)

**Operating System:**
Ubuntu 16.04 Docker container

**Problem description:**
When building the compute library using the following command, with debug=1, as seen in the following Docker RUN command:
```
RUN git clone "https://review.mlplatform.org/ml/ComputeLibrary" && \
    cd ComputeLibrary/ && \
    scons -s arch=arm64-v8a Werror=0 debug=1 asserts=0 neon=1 opencl=0 os=linux extra_cxx_flags="-fPIC" -j $(getconf _NPROCESSORS_ONLN) 
```
I receive the following error:
```
/tmp/ccpRYpZl.s: Assembler messages:
/tmp/ccpRYpZl.s: Error: unaligned opcodes detected in executable segment
scons: *** [build/src/core/NEON/kernels/arm_gemm/gemm_fp16.o] Error 1
```
With the debug flag set to 0 I do not receive this error message.

I will also note that the arm32v7 build works fine with the same flags passed to scons

**Comment by morgolock** [comment]
Hi @jishminor 

It looks like a toolchain problem, could you please try to upgrade to gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu  and try building the library with that compiler?

**Comment by jishminor** [comment]
I attempted a build using Ubuntu 18.04 as a base image, which uses gcc version: gcc version 7.4.0 (Ubuntu/Linaro 7.4.0-1ubuntu1~18.04.1)`. This fixed the problem. I'll did not yet test with 6.3.1, but i'll take your word that that toolchain version would also work fine. Thanks
