### ISSUE TITLE
Return error "free(): invalid pointer" when executing NELSTMLayer::validate

### ISSUE THREAD

**Issue by alanhsu5678** [ARM-software/ComputeLibrary#768]
Dear ARM support,

*Platform:
armv7a
gcc version 6.4.0

*Operating System:
Linux Kernel 4.1.0

*Problem description:
I have trouble when I verify LSTM layer using CpuAcc backend which uses NELSTMLayer in ACL.
The final logs were shown as the follows:
*** Error in `./Test': free(): invalid pointer: 0x00092acc ***
Aborted

My build command for compute library is:
scons extra_cxx_flags="-fPIC" Werror=1 debug=0 asserts=0 neon=1 opencl=0 os=linux arch=armv7a standalone=1 examples=1 validation_tests=1 -j8

Try to readelf via the following command:
$arm-ca9-linux-gnueabihf-readelf -A arm_compute_validation
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "7-A"
  Tag_CPU_arch: v7
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: VFPv3
  Tag_Advanced_SIMD_arch: NEONv1
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_rounding: Needed
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_align_preserved: 8-byte, except leaf SP
  Tag_ABI_enum_size: int
  Tag_ABI_HardFP_use: Deprecated
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6

The boot messages in kernel about my environment:
[    0.000000] Linux version 4.1.0 (alanhsu@test) (gcc version 6.4.0 (Buildroot 2017.11.2) ) #1 SMP Wed Oct 23 13:33:44 CST 2019
[    0.000000] CPU: ARMv7 Processor [414fc091] revision 1 (ARMv7), cr=10c5387d

The kernel configs about NEON:
CONFIG_NEON=y
CONFIG_KERNEL_MODE_NEON=y

I am not sure if I need to configure more on my kernel.
Please help me about this issue.

Thanks!

B.R.
Alan

**Comment by alanhsu5678** [comment]
Hi morgolock,

Please refer to the attached zip file for the source code.
[Test.zip](https://github.com/ARM-software/ComputeLibrary/files/3766812/Test.zip)

Thank you.

B.R.
Alan

**Comment by morgolock** [comment]
Hi @alanhsu5678 

Built and run okay for armv8a as shown below:

```
pabtel01@e108458-lin:/work/ann/armnn-tflite/armnn/build$ PATH=/work/Clean/jenkins/toolchains/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu/bin:$PATH aarch64-linux-gnu-g++ Test.cpp -std=c++14 -I../include/ -I../src/armnnUtils -I/work/ann/armnn-devenv/boost_arm64_install/include/ -I../src/armnn -pthread  -larmnn -L../../install_aarch64_armnn/usr/local/lib/ -o LSTMTest
/work/Clean/jenkins/toolchains/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu/bin/../lib/gcc/aarch64-linux-gnu/6.3.1/../../../../aarch64-linux-gnu/bin/ld: warning: libOpenCL.so, needed by ../../install_aarch64_armnn/usr/local/lib//libarmnn.so, not found (try using -rpath or -rpath-link)
```

```
root@acl_hikey_dev:~/tmp/pabtel01# LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. ./LSTMTest 
====>Configure the LSTM descriptor
====>Set Tensor info
====>Set LSTM input parameters
====>Create Layers
====>Connect up layers
====>Create ArmNN runtime
ArmNN v20190800

====>Optimise ArmNN network
====>Load graph into runtime
```

I'll try to reproduce with armv7a

**Comment by alanhsu5678** [comment]
Hi @morgolock ,

Thanks for the check :)

B.R.
Alan

**Comment by alanhsu5678** [comment]
Quickly dumped the cpuinfo and checked neon feature appears on my device:
=====================================================
/ # cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 1 (v7l)
BogoMIPS        : 99.22
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpd32
...
=====================================================

Just F.Y.I.

B.R.
Alan

**Comment by alanhsu5678** [comment]
Hi @morgolock ,

If validation stage is skipped, the test program can be finished without errors on armv7a platform.

B.R.
Alan

**Comment by alanhsu5678** [comment]
Hi @morgolock ,

Would you mind updating the result for armv7a?

Thanks!

Alan

**Comment by morgolock** [comment]
Hi @alanhsu5678 

I built armnn and acl v20.11 and ran the test without problems. Please see below.


```
root@acl_hikey_dev:~/tmp/pabtel01/v7a# file LSTMTest 
LSTMTest: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.32, BuildID[sha1]=0866f41a08b2aa20190b9b16b3bbe1ece586be93, not stripped
root@acl_hikey_dev:~/tmp/pabtel01/v7a# LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. ./LSTMTest 
====>Configure the LSTM descriptor
====>Set Tensor info
====>Set LSTM input parameters
====>Create Layers
====>Connect up layers
====>Create ArmNN runtime
Info: ArmNN v22.0.0

Info: Initialization time: 13.50 ms

====>Optimise ArmNN network
====>Load graph into runtime
Info: Shutdown time: 2.97 ms

root@acl_hikey_dev:~/tmp/pabtel01/v7a# 
```

Closing this issue, please reopen if you still need help.
