### ISSUE TITLE
Using QASYMM8 for running graph examples

### ISSUE THREAD

**Issue by pr20** [ARM-software/ComputeLibrary#769]
Why are most examples using the graph API not able to run with data type QASYMM8 or F16? I want to run a CNN using graph API using integer format instead of floating point. Are there any restrictions to use QASYMM8?

**Comment by pr20** [comment]
Hi ,
Thank you for replying. I am trying to build a yolov2 tiny model using the graph API using direct convolutional layers. I wish to run it with integer format rather than floating point to speed up the program. Since QASSYM8 is the only integer format that the graph api supports , I tried to make the model run with that data-type, but it is giving the following error.
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!
ERROR in data_size_from_type ./arm_compute/core/../core/../core/Utils.h:131: Invalid data type 
!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
Even when I set --type=F16 , I get the following error
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!
ERROR in configure src/core/NEON/kernels/NEDirectConvolutionLayerOutputStageKernel.cpp:575: Unsupported combination of types among the inputs. 
!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
Even for GEMM convolutional layers ,I get 
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!
ERROR in configure src/core/NEON/kernels/NEIm2ColKernel.cpp:408: Data type not supported 
!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
I had a look at the libraries and the source files, but I do not understand why I can't run models like alexnet using QASSYM8 or any other integer type. I do not see on what conditions the data type can be selected too. So why can't we run some models using qassym support?Also will the weights used for a model using qassym support be different from the one using floating point?

**Comment by morgolock** [comment]
Hi @pr20 

Could you please share more information about the model you are trying to implement with the graph api?. From the output you shared in your post it looks like some functions/kernels in ACL are missing support for the dataypes you need.

Some of the examples like alexnet cannot run with qasymm8 or fp16 because of the reasons mentioned above. Other models can however be executed with qasymm8: graph_mobilenet.cpp and graph_mobilenet_v2.cpp

Hope this helps.

**Comment by pr20** [comment]
Hi
Thanks for replying. I had actually found that batch normalization layers and that most activation functions can not be used with qasymm8. So I had to some changes to my network, where I changed leaky relu to relu and remove the batch normalization layers.
About the F16 datatype, I actually did some changes to the kernel files. For example, in most kernels the switch operations had the f16 case mentioned in side the f16 vector arithmetic definition, and so even when the datatype was f16 it never recognized it.
```
#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
        case DataType::F16:
           //code....
            break;
#endif /* __ARM_FEATURE_FP16_VECTOR_ARITHMETIC */
```
So i put the definitions inside the case, so that it gets detected and it did but I am getting segmentation faults or floating point exceptions. Any idea why this is happening?
```
        case DataType::F16:
#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
           //code....
#endif /* __ARM_FEATURE_FP16_VECTOR_ARITHMETIC */
            break;
```

**Comment by morgolock** [comment]
Hi @pr20 

> About the F16 datatype, I actually did some changes to the kernel files. For example, in most kernels the switch operations had the f16 case mentioned in side the f16 vector arithmetic definition, and so even when the datatype was f16 it never recognized it.
> 
> ```
> #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
>         case DataType::F16:
>            //code....
>             break;
> #endif /* __ARM_FEATURE_FP16_VECTOR_ARITHMETIC */
> ```
> 
> So i put the definitions inside the case, so that it gets detected and it did but I am getting segmentation faults or floating point exceptions. Any idea why this is happening?
> 
> ```
>         case DataType::F16:
> #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
>            //code....
> #endif /* __ARM_FEATURE_FP16_VECTOR_ARITHMETIC */
>             break;
> ```

This is not going to work because there is no support for F16 in armv7a, you need at least armv8.2a.
 
> Also what is the difference between qasymm8 and u8?
> running on raspberry pi 3 b - arch7a

Some computer vision functions work with u8 whereas some ML functions work with qasymm8 which is a compact way to represent floats.

Hope this helps.
