### ISSUE TITLE
Wired NEPoolingLayer Problem

### ISSUE THREAD

**Issue by dujiangsu** [ARM-software/ComputeLibrary#771]
-
Hi, I met a wired bug when I use NEPooling Layer when I use 18.05 and 18.11.

This is my Conv Code: 
`NEConvolutionLayer * conv = new NEConvolutionLayer();
conv->configure(input, weights, nullptr, output, PadStrideInfo(stride, stride, padding, padding), WeightsInfo(), Size2D(1U, 1U), ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::RELU));`

This is my Pooling Code:
`NEPoolingLayer * MaxPoolLayer(Tensor * input, Tensor * output, int poolsize, int stride)
{
NEPoolingLayer * pool = new NEPoolingLayer();
pool->configure(input, output, PoolingLayerInfo(PoolingType::MAX, poolsize, PadStrideInfo(2, 2, 1, 1)));
output->allocator()->allocate();
return pool; 
};`

The Tensor (224,224,3) is initialized from a PPM pic, If I use the Tensor as conv's input and pool's input, both operate well. 

However, if I use the output(112,112,24) of the conv as pool's input, the output tensor(56,56,24) of the pool is full of  0.  If I set PadStrideInfo(2,2,0,0), the output tensor (55,55,24) is correct. Very strange. 

Is the wrong result related to data layout(NHWC) ?  Does the version I used provide support for NHWC data format?

**Comment by morgolock** [comment]
Hi @dujiangsu 

Please update to use ACL 19.08 and let us now if this solves the problem.

Hope this helps.

**Comment by GeorgeARM** [comment]
@dujiangsu does this error persists with the new ACL version?
Thank you in advance.

**Comment by morgolock** [comment]
Closed by inactivity, please reopen if you still require assistance.
