### ISSUE TITLE
Installing ACL version 18.05 files missing

### ISSUE THREAD

**Issue by waveajay** [ARM-software/ComputeLibrary#772]
ACL v 18.05  binaries Linux doesn't contain sconscript ,sconstruct etc so I am not able to install it.I need to install 18.05

**Comment by morgolock** [comment]
Hi @waveajay 

The binaries normally do not contain the source code. You'll need need to clone the public repo: `git clone "https://review.mlplatform.org/ml/ComputeLibrary"`

**Comment by waveajay** [comment]
Thank you
