### ISSUE TITLE
Regarding graph_yolov3 example execution, require /cnn_data/yolov3_model/ files

### ISSUE THREAD

**Issue by Prem-compute** [ARM-software/ComputeLibrary#773]
Hello,

Am trying to run graph_yolov3 example, as the dependent files are missing in arm compute repository, could not execute.

Please do help, where can i find files, that are under  "/cnn_data/yolov3_model".
And as well as pointers to run graph_yolov3 example.

Thanks,
Prem.

**Comment by morgolock** [comment]
Hi @Prem-compute 

ACL does not provide the weights for any of the graph examples, please refer to the documentation explaining how to export the parameters from a pre-trained model: https://arm-software.github.io/ComputeLibrary/v19.08/data_import.xhtml

You should download the model and extract the parameters as numpy files, the graph examples can read the weights from these files.

Hope this helps.

**Comment by mpekatsoula** [comment]
Hi @Prem-compute ,
As @morgolock said, we do not provide the weights required to run the model. You'll have to download the weights and after you extract them you can run yolov3 as:
./yolov3 --data='/path/to/weights/'
