### ISSUE TITLE
SGEMM does not calculate output when input is all 0?

### ISSUE THREAD

**Issue by RuABraun** [ARM-software/ComputeLibrary#774]
v19.08
arm64-v8a

Working on using `NEGEMM`, while trying to figure out why the output was not correct I realized while monitoring input/output pairs that it seems NEGEMM::run() only does anything when the input is nonzero? That means that whenever the input is zero it just kept outputting the last output with nonzero input. This is obviously not the sort of behaviour one wants.

Is there a flag or something of that sort which would change the behaviour to always calculate the output?

**Comment by morgolock** [comment]
Hi @RuABraun 

Would you please share the source code to reproduce the problem?

**Comment by RuABraun** [comment]
Sorry I don't have the time and have found another library that suits my needs better.

Feel free to close if you want.
