### ISSUE TITLE
Not able to convert yolov3 CFG/WEIGHT files to cafffe model files

### ISSUE THREAD

**Issue by Prem-compute** [ARM-software/ComputeLibrary#778]
Hello,
Am trying to verifying " graph_yolov3" example application. 

step 1: Download .cfg and .weight file from below link:
    https://pjreddie.com/darknet/yolo/
step 2: Convert yolov3 model to caffe
    convert .cfg and .weight to .prototxt and .caffemodel following link i followed
    https://github.com/marvis/pytorch-caffe-darknet-convert.
-------------------------------------------------------------------------
$ python darknet2caffe_test.py cfg/yolov3.cfg weight/yolov3.weights caffemodel/yolov3.prototxt caffemodel/yolov3.caffemodel

[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 2628:20: Message type "caffe.LayerParameter" has no field named "upsample_param".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1119 19:57:08.753664  6253 upgrade_proto.cpp:90] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: caffemodel/yolov3.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)
------------------------------------------------------------------------------------
Hence not able to generate .NPY files in order to execute  graph_yolov3 example.
Please do help on this.

Or do please help if any other example code, that can be used to verify YOLOV3/YOLO-TINY using arm compute ( from arm compute git hub).

Thanks,
Prem.

**Comment by Prem-compute** [comment]
Any pointers would be much appreciated.

**Comment by Prem-compute** [comment]
Thanks, will download v20.05 and verify yolov3 sample, and will update the status.

Thanks.

**Comment by morgolock** [comment]
Closed due to inactivity. Please reopen if further assistance is needed.
