### ISSUE TITLE
NELSTMLayer gives nan values as output

### ISSUE THREAD

**Issue by nhkrishna** [ARM-software/ComputeLibrary#779]
Hi,

I have implemented LSTM layer for single time step data using the ACL `NELSTMLayer` kernel.
But it was giving `nan` values for the real time data input. Then i have started looking at the outputs of the each gates in the LSTM cell using the [scratch buffer](https://github.com/ARM-software/ComputeLibrary/blob/master/tests/validation/fixtures/LSTMLayerFixture.h#L516). Then i found that `input gate` and `forget gate` are producing the `nan` values.

These gates are mainly responsible for doing `sigmoid` operation and issue #674 states that sigmoid operation will work only for the range `[-40.f, 40.f]`. 
In LSTMs input to the sigmoid operation will go out of the above range for the given real time sequence data.
It would be good to support the higher range of input for sigmoid and other activation kernels also.

Thanks,
Hari

**Comment by nhkrishna** [comment]
Any update on this?

**Comment by GeorgeARM** [comment]
Helllo @nhkrishna,

I ll capture this internally and will try to see if we can find some time to address it.
Some details:
 - Do you have any particular time-frame for this?
 - Do you know the range of your values?
Thank you in advance.
George

**Comment by nhkrishna** [comment]
Hi @GeorgeARM ,

Thanks for your response.

`Do you have any particular time-frame for this?`

- It would be extreme helpful for us if you support this in next release(19.11).  

`Do you know the range of your values?`

- We can not guarantee the input range to  sigmoid operation. Because LSTM applications may take higher rage of real value input.

- Also, Could you please let me know why input range is restricted for sigmoid operation?
  Ideally this operation should handle for any given range of float values.

Thanks,
Hari

**Comment by GeorgeARM** [comment]
Hello @nhkrishna,

I am afraid for 19.11 its a bit late as we already finalizing the release.
I will send a link to the development repo once we address the issue so that you can check if it works.
Thank you.

**Comment by nhkrishna** [comment]
Sure @GeorgeARM , i'm looking forward to see the fix for the issue in next release.

**Comment by LucaFos** [comment]
Hello @nhkrishna,
I'm trying to reproduce the NaN issue, this is what I found:
-there isn't any issue with negative exponents
-with positive exponents, I start getting NaN from 89
From what I've gathered, we can treat NaN as a +inf value.

Can you tell me more about what you were expecting from the exp function? Up until e^88 it works well, but I'm trying to understand if we can do something for your issue.

Thank you,
Luca

**Comment by morgolock** [comment]
Hi @nhkrishna 

We have not been able to reproduce the problem. In order to help you  could you please provide the input data and a sample program reproducing the problem?

**Comment by nhkrishna** [comment]
Hi @morgolock ,

Sorry for the delayed response.
As I mentioned in the first comment, we are seeing 'NaN' values particularly in Sigmoid operation for some of the LSTM gates. We have raised an issue #674, In this we have included real time input values to sigmoid operation which causes NaN values.
Also, issue #674 states that validated input range for the sigmoid operation is [-40f, 40f] otherwise we may end up with NaN values.

It would be good to support larger set of inputs to Sigmoid operation because Its quite often to see out range input values to sigmoid operation in LSTM Networks.

Thank you,
Hari

**Comment by morgolock** [comment]
Hi @nhkrishna 

At present Logistic valid input range is [-40.f,40.f]. We're going to discuss your request for extending support for a wider input range and possibly add it to our roadmap.

**Comment by giorgio-arenarm** [comment]
Hi @nhkrishna could you please tell us what behavior you would expect for exponents greater than 88?

e^88 is already a 128bit number, which in any case doesn't fit into the FP32 elements in the tensor, so given that we allow for these value to be calculated, what value should be store in the output tensor?

**Comment by giorgio-arenarm** [comment]
Hi @nhkrishna after a further analysis I found that this issue has been fixed in 20.05. I'll close this ticket, please feel free to reopen it if you need further assistance with this.

**Comment by Hari-MathWorks** [comment]
Hi @giorgio-arenarm ,

Could you please let me know what is the fix for this problem? Also, Does your fix resolves the problem for the LOGISTIC activation function also(#674 )?

What is the exact release in which the issue was fixed?
