### ISSUE TITLE
Convolution Failed when kernel size is even

### ISSUE THREAD

**Issue by cyberfire** [ARM-software/ComputeLibrary#78]
@mpflanzer  and all , 
I found that when kernel_size is even, ACL cannot calculate the correct value in the right border column.
As there is even kernel_size in real world, this needs to be fixed. Please reproduce the issue by the following code. 
<code>
int main(int argc, char * argv[]) {

     /* kernel_size =3, the result is corret 
        kernel_size=4, the result is wrong */

     constexpr unsigned long width = 4, height = 4, stride = 1, pad = 0, kernel_size = 2, channel_out = 1, channel_in = 1;   
     unsigned long out_w,out_h;

     out_h=(height-kernel_size+2*pad)/stride+1;
     out_w=(width-kernel_size+2*pad)/stride+1;

    TensorShape iShape(width, height, channel_in);
    TensorShape wShape(kernel_size, kernel_size, channel_in, channel_out);
    TensorShape bShape(channel_out);
    TensorShape oShape(out_w, out_h,channel_out);

     PadStrideInfo info(stride, stride, pad, pad, DimensionRoundingType::FLOOR);
    

    Tensor iTensor, wTensor, bTensor, oTensor;
   
    iTensor.allocator()->init(TensorInfo(iShape, Format::F32));
    wTensor.allocator()->init(TensorInfo(wShape, Format::F32));
    bTensor.allocator()->init(TensorInfo(bShape, Format::F32));
    oTensor.allocator()->init(TensorInfo(oShape, Format::F32));

    NEConvolutionLayer layer;
    layer.configure(&iTensor, &wTensor, &bTensor, &oTensor, info);

    iTensor.allocator()->allocate();
    wTensor.allocator()->allocate();
    bTensor.allocator()->allocate();
    oTensor.allocator()->allocate();

    Window iWindow;
    iWindow.use_tensor_dimensions(iTensor.info());
    Window wWindow;
    wWindow.use_tensor_dimensions(wTensor.info());
    Window bWindow;
    bWindow.use_tensor_dimensions(bTensor.info());

    Iterator iIt(&iTensor, iWindow);
    Iterator wIt(&wTensor, wWindow);
    Iterator bIt(&bTensor, bWindow);

    execute_window_loop(iWindow, [&] (const Coordinates &id) {
        *reinterpret_cast<float *>(iIt.ptr()) = 1;
    }, iIt);
    execute_window_loop(wWindow, [&](const Coordinates &id){
        *reinterpret_cast<float *>(wIt.ptr()) =1;
    }, wIt);
    execute_window_loop(bWindow, [&](const Coordinates &id){
        *reinterpret_cast<float *>(bIt.ptr()) = 1;
    }, bIt);

    cout<<"iTensor content ..."<<endl;
    iTensor.print(cout,IOFormatInfo::PrintRegion::ValidRegion);

    cout<<"wTensor content ..."<<endl;
    wTensor.print(cout,IOFormatInfo::PrintRegion::ValidRegion);

    cout<<"bTensor content ..."<<endl;
    bTensor.print(cout,IOFormatInfo::PrintRegion::ValidRegion);

    layer.run();

    cout<<"oTensor content ..."<<endl;
    oTensor.print(cout,IOFormatInfo::PrintRegion::ValidRegion);

}
</code>

Output for kernel_size =2

iTensor content ...
1 1 1 1 
1 1 1 1 
1 1 1 1 
1 1 1 1 

wTensor content ...
1 1 
1 1 

bTensor content ...
1 

oTensor content ...
5 5 4 
5 5 4 
5 5 4 

Output for kernel size=3

iTensor content ...
1 1 1 1 
1 1 1 1 
1 1 1 1 
1 1 1 1 

wTensor content ...
1 1 1 
1 1 1 
1 1 1 

bTensor content ...
1 

oTensor content ...
10 10 
10 10 

Thanks,

Cyberfire

**Comment by mpflanzer** [comment]
Thanks for reporting this problem and for sharing the code to reproduce it. We will be looking into this.

**Comment by GeorgeARM** [comment]
Closing this as it has been addressed in latest release (v17.05). Reopen if issue persists!
