### ISSUE TITLE
How to use libopencl on the 'arch': 'armv7a' ?

### ISSUE THREAD

**Issue by WenguoLi** [ARM-software/ComputeLibrary#780]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

arm_compute_version=v19.08 Build options: {'embed_kernels': '1', 'arch': 'armv7a', 'opencl': '1', 'neon': '1', 'asserts': '1', 'debug': '0', 'os': 'android', 'Werror': '1'} Git hash=975dfe175e3d7c62c27598b1c0e8e77ed90df463

**Platform:**
Android go_32bit

**Operating System:**
Ubuntu 16.04

**Problem description:**
I want to use libopencl on the armv7a, 
build cmd: 
`CXX=clang++ CC=clang scons Werror=1 -j8 debug=0 asserts=1 neon=1 opencl=1 embed_kernels=1 os=android arch=armv7a`

When I run the cl examples, they appear the following error:

```
s9863a1h10_go_32b:/data/armnn # ./cl_convolution                               

./cl_convolution

Usage: ./build/cl_convolution [input_image.ppm]

No input_image provided, creating a dummy 640x480 image
error: unknown argument: '-cl-arm-non-uniform-work-group-size'

terminating with uncaught exception of type cl::Error: clCreateKernel
/buildbot/src/android/ndk-release-r17/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "terminating with uncaught exception of type cl::Error: clCreateKernel" failed
Aborted (core dumped) 
```
or

```
s9863a1h10_go_32b:/data/armnn # ./graph_mobilenet --target=CL

./graph_mobilenet

Threads : 1
Target : CL
Data type : F32
Data layout : NHWC
Tuner enabled? : false
Tuner file : 
Fast math enabled? : false

error: unknown argument: '-cl-arm-non-uniform-work-group-size'

terminating with uncaught exception of type cl::Error: clCreateKernel
/buildbot/src/android/ndk-release-r17/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "terminating with uncaught exception of type cl::Error: clCreateKernel" failed
Aborted (core dumped) 
```
How can I solve the above problem? Please help.

Thanks

**Comment by ggardet** [comment]
What is your target?
`error: unknown argument: '-cl-arm-non-uniform-work-group-size'` suggests you are running openCL 1.x without `cl_arm_non_uniform_work_group_size` [1] support, which is required: https://github.com/ARM-software/ComputeLibrary/blob/master/src/core/CL/CLKernelLibrary.cpp#L1081

[1]: https://www.khronos.org/registry/OpenCL/extensions/arm/cl_arm_non_uniform_work_group_size.txt

**Comment by WenguoLi** [comment]
Thanks，this problem have been solved！
