### ISSUE TITLE
Tests examples are not returning properly when --target=CL is used

### ISSUE THREAD

**Issue by ggardet** [ARM-software/ComputeLibrary#781]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
`arm_compute_version=v19.08 Build options: {'os': 'linux', 'build': 'native', 'set_soname': '1', 'examples': '1', 'gles_compute': '0', 'opencl': '1', 'validation_tests': '0', 'neon': '1', 'arch': 'arm64-v8a', 'extra_cxx_flags': '-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g', 'Werror': '0'} Git hash=unknown`

**Platform:**
HiKey960

**Operating System:**
openSUSE Tumbleweed, with Arm Mali bifrost driver.

**Problem description:**
```graph_alexnet --data=$PATH_ASSETS --image=$PATH_ASSETS/go_kart.ppm --labels=$PATH_ASSETS/labels.txt``` runs fine on NEON backend.
But if I add `--target=CL`, the test run, but test hangs after `Test passed` and do not return to prompt.

**Comment by santo4ul** [comment]
Any updates on this issue? 

I'm facing the same problem when I moved to 19.11. This issue is not observed on 19.02. 

I'm yet to debug this further.

**Comment by GeorgeARM** [comment]
Hello @santo4ul,

We don't see any such issues in our internal testing. We would need the version of the Mali Driver to be able to debug and look further into this.
Thank you in advance.

**Comment by santo4ul** [comment]
Hi @GeorgeARM 

My Mali driver version is r18p0-01rel0-x-7@0

Thank you.

**Comment by santo4ul** [comment]
I'm currently using 19.08 and it works fine with 19.08. Seems something is missing with 19.11.

Thanks,
San

**Comment by morgolock** [comment]
Hi @ggardet 

Could you please try running clinfo and sharing the output here?

If it's not installed on your system you may need to build it from the sources: https://github.com/Oblomov/clinfo

**Comment by ggardet** [comment]
@morgolock Meanwhile I updated to 19.11 and the problem is gone.
