### ISSUE TITLE
How to use   NEFFT2D ?

### ISSUE THREAD

**Issue by helloworldstone** [ARM-software/ComputeLibrary#782]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version: 19.05
**Operating System:**
Android

**Problem description:**

Hello ,all!

Arm compute library 19.05 introduced NEFFT2d  and NEFFT1d:
https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/NEON/functions/NEFFT1D.h
https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/NEON/functions/NEFFT2D.h

**I want to use NEFFT2D to process a image.  But the dst result is all zero!!!
Can someone point out where the error is？Very thankful！
Waiting online！**

 Code like this:

```
class NEONFFTTestExample : public Example
{
public:
bool do_setup(int argc, char **argv) override
{
const int width  = 20;
const int height = 20;

src.allocator()->init(TensorInfo(width, height, Format::F32));
dst.allocator()->init(TensorInfo(width, height, Format::F32));

nefft2d.configure(&src, &dst,config2d);

src.allocator()->allocate();
dst.allocator()->allocate();

for (unsigned int y = 0; y < height; y++) {
for (unsigned int x = 0; x < width; x++) {
*(src.buffer() + src.info()->offset_element_in_bytes(Coordinates(0,y)) +x) =  
(float)((rand()/(double)(RAND_MAX)) * 255);   
}
}

Window window;
window.use_tensor_dimensions(src.info()->tensor_shape());
Iterator it(&src, window);
execute_window_loop(window, [&](const Coordinates & )
{
std::cout << (*reinterpret_cast<float *>(it.ptr())) << " ";
},it);

return true;
}
void do_run() override
{
//Execute the functions:
nefft2d.run();
}
void do_teardown() override
{      
const int width  = 20;
const int height = 20;

Window window;
window.use_tensor_dimensions(dst.info()->tensor_shape());
Iterator it(&dst, window);
execute_window_loop(window, [&](const Coordinates & )
{
std::cout << (*reinterpret_cast<float *>(it.ptr())) << " ";
},it);
std::cout << std::endl;
}

private:
Tensor         src{}, dst{};
NEFFT2D nefft2d{};
FFT2DInfo config2d;
};
```

**Comment by morgolock** [comment]
Hi @helloworldstone 

I do not see anything wrong in your code, could you please try increasing the size of the image to something like 224x224?

Hope this helps.

**Comment by 0b11101010** [comment]
Hi @helloworldstone,
I think your tensor shape for output is in wrong format. Consider that for each element of the input tensor, there will be complex output. Can you also increase input tensor size?

If you still need solution, I can upload example.

**Comment by Che-Cheng-Chang** [comment]
Hi @helloworldstone,
I think I need the example of using NEFFT2D. (Hopefully, from load the image from PPMLoader to output the fft result)
I have tried it for a long time and still get no results.

Could you please send me the example code to my email? 
--> Email: r06921002@ntu.edu.tw

Thanks a lot
