### ISSUE TITLE
Question for GEMM processing?

### ISSUE THREAD

**Issue by knjwhn** [ARM-software/ComputeLibrary#784]
Hi, I'm studying for the gemm multiplication in ACL , and I can't find related information in introduction doc. So, I look into the open source code. and I focus on the NEON backend. 
I find there is three method in gemm_implementation. Hybrid , Interleave , and Native. and in files like  gemm_fp32.cpp used the three method to link different kernel, So , What is the difference among them? and there are some files named fp16,int8? Does it mean it suport such precision General Matrix Multiply or not. Because the introduction says there only suport H/SGEMM(Half and Single precision General Matrix Multiply)?

and I also find in file named NEGEMMMatrixMultilyKernel has implement such function called matrix_matrix_multiply_f32 using neon intrinsic. So, What is the kernel used when I run a sgemm or the difference between the NEGEMMMatrixMultilyKernel and the kernel defined in gemm_fp32.cpp? 

What's more , I know there are some method implement the convolution kernel such as im2col+gemm and direct convolution. But I can't find where is the Convolution called the gemm function in NEConvolutionKernel.cpp. is anyone know where it is?  
Anyone can help? So much thanks and Hoping for your reply.

**Comment by morgolock** [comment]
Hi @knjwhn 

> I find there is three method in gemm_implementation. Hybrid , Interleave , and Native. and in files like gemm_fp32.cpp used the three method to link different kernel, So , What is the difference among them? 

ACL has different kernel implementations highly optimised for various combinations of inputs (shapes and data types). The function NEGEMM will choose the best kernel for the given input when you call NEGEMM::configure().

> Does it mean it suport such precision General Matrix Multiply or not. Because the introduction says there only suport H/SGEMM(Half and Single precision General Matrix Multiply)?

To find what data types are supported by a function I would recommend looking into the relevant header files:
https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/NEON/functions/NEGEMM.h#L77
https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/NEON/functions/NEGEMMLowpMatrixMultiplyCore.h#L83

> and I also find in file named NEGEMMMatrixMultilyKernel has implement such function called matrix_matrix_multiply_f32 using neon intrinsic. So, What is the kernel used when I run a sgemm or the difference between the NEGEMMMatrixMultilyKernel and the kernel defined in gemm_fp32.cpp?

There is no simple answer, the kernel chosen by ACL will depend on the underlying CPU capabilities, compilation options and the input's data type and shapes.

> What's more , I know there are some method implement the convolution kernel such as im2col+gemm and direct convolution. But I can't find where is the Convolution called the gemm function in NEConvolutionKernel.cpp. is anyone know where it is?

NEConvolutionLayer will call into NEGEMMConvolutionLayer, but again this will depend on the input and kernel shapes.

Sometimes NEConvolutionLayer will choose other methods like Winograd or FFT

https://github.com/ARM-software/ComputeLibrary/blob/master/src/runtime/NEON/functions/NEConvolutionLayer.cpp#L53

https://github.com/ARM-software/ComputeLibrary/blob/master/src/runtime/NEON/functions/NEGEMMConvolutionLayer.cpp

Hope this helps.
