### ISSUE TITLE
How to use sgemm api in mxnet or tensorflow?

### ISSUE THREAD

**Issue by knjwhn** [ARM-software/ComputeLibrary#785]
Hello, everyone! I've wrote an cblas_sgemm interface like openblas, and I replace it in https://github.com/apache/incubator-mxnet/blob/master/src/operator/linalg_impl.h#L73 , and I wonder if there have similar gemm api in ACL so that I can made some comparison. What's more is there have some tips that how can i use acl in mxnet or tensorflow with there new version. 
Anyone can help?  So much thanks!

**Comment by GeorgeARM** [comment]
Hello @knjwhn,

We have the `NEGEMM` and `CLGEMM` functions, I don't think they are fully aligned with the interface you posted as the format parameters `trA` and `trB` are not part of our interface.
If your target is Neon you can directly use the low level gemm library that we have which is aligned with the blas interface but will need a bit of manual work on your side. [Here](https://github.com/ARM-software/ComputeLibrary/blob/master/src/runtime/NEON/functions/NEGEMMAssemblyDispatch.cpp#L410) you can see how we wrap the gemm library to our functions.
Hope this helps.

**Comment by morgolock** [comment]
Hi @knjwhn 

You can execute tensorflow models with armnn's `ExecuteNetwork`:

https://github.com/ARM-software/armnn/tree/branches/armnn_20_02/tests/ExecuteNetwork

This in turn will fall back to ACL for acceleration.

Hope this helps.

**Comment by alexeyr** [comment]
@GeorgeARM Does the low-level library also allow choosing between column-major and row-major format? If not, which one does it expect?
