### ISSUE TITLE
Can I choose to change the sgemm kernel implementation?

### ISSUE THREAD

**Issue by knjwhn** [ARM-software/ComputeLibrary#786]
Hi , I wanna to use the kernel with the sve version in order to test the sgemm performance  for the sve sets . like path as ComputeLibrary-19.02\src\core\NEON\kernels\arm_gemm\kernels\sve_interleaved_fp32_mla_3VLx8, is there any advice? Any reply would be appreciated.

**Comment by morgolock** [comment]
Hi @knjwhn 

The function NEGEMM will query the CPU capabilities at runtime and choose the best kernel for the underlying hardware, take a look at the code in:

https://github.com/ARM-software/ComputeLibrary/blob/master/src/runtime/NEON/functions/NEGEMMAssemblyDispatch.cpp#L499

NEGEMM will do the job for you.

**Comment by GeorgeARM** [comment]
Hello @knjwhn,

First of all to enable this you have to build ComputeLibrary with `arm64-v8.2-a-sve` as your target architecture.
This will enable all the sve kernels and the gemm dispatcher as @morgolock mentioned will pick the most appropriate kernel.
Hope this helps.

**Comment by knjwhn** [comment]
> Hello @knjwhn,
> 
> First of all to enable this you have to build ComputeLibrary with `arm64-v8.2-a-sve` as your target architecture.
> This will enable all the sve kernels and the gemm dispatcher as @morgolock mentioned will pick the most appropriate kernel.
> Hope this helps.

Thanks, I used gdb to follow processing of the sgemm and I made a test by changing the kernel defined in src/core/NEON/kernels/assembly/NEGEMMNativeWrapperKernel.cpp and it works when I change to  sgemm_12x8 kernel.  Does it right? and I have a quesstion , is the Acl only used in inference and don't support training? Hope your reply !

**Comment by morgolock** [comment]
Hi @knjwhn 

Yes, ACL is only used for inference.
