### ISSUE TITLE
Question: Optimizing detection output processing

### ISSUE THREAD

**Issue by santo4ul** [ARM-software/ComputeLibrary#787]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v19.08 Build options: {'embed_kernels': '1', 'gles_compute': '1', 'arch': 'arm64-v8a', 'opencl': '1', 'neon': '1', 'benchmark_tests': '1', 'validation_tests': '1', 'asserts': '1', 'debug': '0', 'os': 'android', 'Werror': '1'} Git hash=d32643ab2afe6e1cc838fc1d98136c3832c4c9c6

**Platform:**
Android

**Operating System:**
Andoroid

**Problem description:**

I'm working on Mobilenet+SSD graph and on the output tensor, I'm using the below loop to extract the predictions and the classes from the tensor. With 91 classes and 1927 boxes, this loop is taking a considerable amout of time. Given that padding is involved here, any idea to better implement this loop? Would using memcpy (ignoring the padding) inside the loop a better option?

```
    execute_window_loop(window, [&](const Coordinates & id)
    {
        if (id.x() < NUM_CLASSES) {
            *pClasses = *reinterpret_cast<float *>(tensor.ptr_to_element(id));
            pClasses++;
        } else {
            *pPredctions = *reinterpret_cast<float *>(tensor.ptr_to_element(id));
            pPredctions++;
        }
    });

```

**Comment by GeorgeARM** [comment]
Hello @santo4ul,

Is padding indeed involved in the output? If yes, you can unroll the x dimension and try memcpy and see how faster it is.

**Comment by santo4ul** [comment]
Hi @GeorgeARM, Thanks for your inputs.

Yes, the output tensor has padding in it. 

Sure, i'll try the memcpy in x dimension. I'm still fiddling with the usage of this fancy execute_window_loop :)

**Comment by GeorgeARM** [comment]
Hey @santo4ul,

you can always override the window that you are passing in the `execute_window_loop` and manually unroll across x if you think that this could be more efficient.
We do for example [here](https://github.com/ARM-software/ComputeLibrary/blob/master/src/core/NEON/kernels/NEActivationLayerKernel.cpp#L233) and then we manually unroll across x inside the loop.
Hope this helps.

**Comment by santo4ul** [comment]
Hi @GeorgeARM,

Thanks for info and the link that shows how to unroll across x. That helped a lot.

On my A72 (@ 1.8GHz), earlier this loop was taking ~8ms. After the unroll, now it is < 1ms! 

```
    Window win_collapsed = window.collapse_if_possible(window, Window::DimY);
    win_collapsed.set(Window::DimX, Window::Dimension(0, 1));

    execute_window_loop(win_collapsed, [&](const Coordinates & id)
    {
        memcpy(pClasses, reinterpret_cast<float *>(tensor.ptr_to_element(id)), NUM_CLASSES*sizeof(float));
        pClasses += NUM_CLASSES;
        memcpy(pPredctions, reinterpret_cast<float *>(tensor.ptr_to_element(id))+NUM_CLASSES, 4*sizeof(float));
        pPredctions += 4;
    });

```
Thanks again!
