### ISSUE TITLE
How to convert IYUV to grey

### ISSUE THREAD

**Issue by saicomagic** [ARM-software/ComputeLibrary#788]
Im new to ComputeLibrary. Now I want to convert an image from IYUV to gray. Should I first convert IYUV to RGB888, and then convert RGB888 to U8? Is there a more concise way to fulfill it? Thx!!!

**Comment by morgolock** [comment]
Hi @saicomagic 

ACL does not support direct conversion from IYUV to U8.

You can still convert it with ACL but you need one additional conversion as you described: IYUV -> RGB888 -> U8

**Comment by saicomagic** [comment]
@morgolock Get it! Thx very much!
