### ISSUE TITLE
ACL LSTM layer performs 2X slower than OpenMP implementation

### ISSUE THREAD

**Issue by nhkrishna** [ARM-software/ComputeLibrary#789]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v19.11 Build options: {'cppthreads': '1', 'arch': 'armv7a', 'opencl': '0', 'neon': '1', 'build': 'cross_compile', 'debug': '0', 'openmp': '1', 'os': 'linux', 'Werror': '0'} Git hash=unknown

**Platform:** Raspberry Pi 3 Model-B quad core ARM Cortex @1.2GHz, 1GB RAM

**Operating System:** Linux

**Problem description:**
I have implemented LSTM layer using ACL NELSTMLayer API and OpenMP custom implementation.  I found that ACL performing 2 times slower than OpenMP implementation.

FYI, I have attached source code of both the implementations, you can download these implementation from this [link](https://drive.google.com/open?id=1pI-1kX6P0f33Ewk1NjKJ4wlSBPGxDA6b).

Please follow below steps to see the results:

1. Run toGithub/ACL/lstm_using_acl.cpp to see performance results of the LSTM layer using ACL.
2. Run toGithub/Ccode/lstm_without_acl.cpp to see the performance of the LSTM layer using OpenMp.

Let me know any help to reproduce this issue.

Thanks,
Hari

**Comment by GeorgeARM** [comment]
Hello @nhkrishna,

Do you have the same behavior on 64-bit systems? Would be good to know as we don't have the same number of hand-crafted kernels for 32-bit systems compared to 64-bit.

Best Regards,
George

**Comment by nhkrishna** [comment]
Hi @GeorgeARM ,

I have tested on 64 bit system as well and observed the same behavior.

Here are library and system details that are used for profiling:

**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v19.11 Build options: {'cppthreads': '1', 'arch': 'arm64-v8a', 'opencl': '0', 'neon': '1', 'examples': '0', 'asserts': '0', 'debug': '0', 'openmp': '1', 'os': 'linux', 'Werror': '0', 'build': 'cross_compile'} Git hash=unknown

**System** : Rock960 Dual core A72@1.8GHz + quad core A53@1.4GHz, 4GB RAM

Thanks,
Hari

**Comment by nhkrishna** [comment]
Any update on this?

**Comment by morgolock** [comment]
Hi @nhkrishna 

I tried to run your ACL test but it fails during the call to nelstm.configure()

```
root@acl_dev:~/tmp/pabtel01/graph# LD_LIBRARY_PATH=$LD_LIBRARY_PATH:.  ./lstm_using_acl 
terminate called after throwing an instance of 'std::runtime_error'
  what():  in validate_arguments src/core/NEON/kernels/NEWidthConcatenateLayerKernel.cpp:66: input->dimension(0) + width_offset > output->dimension(0)
Aborted
```

Could you please double check the test code is correct and share the command you type to run it?

**Comment by nhkrishna** [comment]
Hi @morgolock ,

Sorry for the delayed response. I am able to run attached script without any issues.

**Please follow below steps to see the performance of ACL implementation:**
_1. Download the scripts from [this ](https://drive.google.com/file/d/1pI-1kX6P0f33Ewk1NjKJ4wlSBPGxDA6b/view) location. 
2. Change directory to "toGithub/ACL".
3. Open the Makefile and change the **ARM_COMPUTE_PATH** variable to your ARM Compute library root location to find headers and libraries(.so) files properly(Note; In my case i have copied dependent headers to $(ARM_COMPUTE_PATH)/include and libraries to $(ARM_COMPUTE_PATH)/lib locations).
3. Run make command.
4. Run ./lstm_acl_exe_

Now you can see the time  take for each iteration for singleton sequence length.

**Please follow below steps to see the performance of OpenMP implementation:**
_1. Download the scripts from [this ](https://drive.google.com/file/d/1pI-1kX6P0f33Ewk1NjKJ4wlSBPGxDA6b/view) location. 
2. Change directory to "toGithub/Ccode".
3. Run make command.
4. Run ./lstm_c_exe_

Now you can see the time  take for each iteration for singleton sequence length.

You can compare outputs of each implementation from using the generated test_output.txt file.

Let me know if you need any help in reproducing this issue.

Thanks,
Haru

**Comment by nhkrishna** [comment]
Hi @morgolock ,

I have tested using ACL version 19.05 and 20.02. 
Also, i have double checked with shared script using 19.05 and 20.02 and i'm able to reproduce it.

Thanks,
Hari

**Comment by morgolock** [comment]
Hi @nhkrishna 

I think I know what's going on, could you please try building with debug=1 or asserts=1 and run the test?

The function NELSTM is not being properly configured, please make sure your code runs without throwing any exceptions or having failing assertions.

Hope this helps.

**Comment by nhkrishna** [comment]
Hi @morgolock ,

I built the ComputeLibrary using debug=1, Then I'm able to reproduce the error mentioned by you in the above comment.
It seems like scratch buffer was incorrectly configured. Now I have configured scratch buffer properly and I don't see any exceptions. 
I have updated the source code with the scratch buffer fix. Please find the updated scripts from this [link ](https://drive.google.com/drive/folders/13XUE-u6RalKreOFJlXp5kbTUXl4fE8X3?usp=sharing) and follow the steps mentioned in the above comments to reproduce this issue. I'm still observing OpenMP is performing better than ACL.

Let me know if you need any help in reproducing this issue.

Thanks,
Hari

**Comment by uu-praveeng** [comment]
Hi @GeorgeARM ,

We have attached the C code implementation vs ACL implementation in the initial query 
"FYI, I have attached source code of both the implementations, you can download these implementation from this link."

Thank you,
Praveen.

**Comment by morgolock** [comment]
Hi @uu-praveeng 

I ran the two tests you have provided and I found the performance difference is negligible: for this particular execution there is a delta of 0.009494 ms. I don't see ACL 2x slower than the C implementation.

![lstm](https://user-images.githubusercontent.com/5577511/92398965-5f1a5f00-f121-11ea-89a3-1124af717a23.png)
 

I'm linking your acl test with against the HEAD of the master branch.

ACL build options:
```
scons os=linux arch=arm64-v8a neon=0 gles_compute=0 opencl=0 examples=0 validation_tests=0 benchmark_examples=0  Werror=0 standalone=0 cppthreads=0 openmp=1 neon=1 Werror=0 debug=0  -j50
```

Running the test on a hikey board:
```
root@acl_hikey_dev:~/tmp/pabtel01/graph# lscpu 
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   4-7
Off-line CPU(s) list:  0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
CPU max MHz:           1844.0000
CPU min MHz:           533.0000
L1d cache:             64K
L1i cache:             64K
L2 cache:              2048K
```

Hope this helps.

**Comment by morgolock** [comment]
Closing, please reopen if you still need assistance.
