### ISSUE TITLE
where can I find more documents about more technique tricks to faster op(like conv)

### ISSUE THREAD

**Issue by kl456123** [ARM-software/ComputeLibrary#792]
Well I just want to know more  details about how to accelerate the inference of NN. Can someone tell me where  i can find it. 
So far I'm confused about something.
1. why use buffer instead of image_2d.
2. why not use get_local_id.(local mem)

Thanks in advanced.

**Comment by GeorgeARM** [comment]
Hello @kl456123,

Can you elaborate on which context do you want more details on accelerating NN inference?
Concerning your two points:
- We decided to use `cl_buffer` as with `cl_image` we were hitting issues with minimum alignment requirements leading to excessive padding. We are considering evaluating `cl_image` on specific workloads in the future. Is there any reason for this concern?
- Arm GPUs do not have local memory, if you allocate local memory it will be allocated in global memory, so you won;t get any performance improvement.
