### ISSUE TITLE
Need example for image segmentation networks U-net

### ISSUE THREAD

**Issue by abhajaswal** [ARM-software/ComputeLibrary#794]
Can you add theh image segmentation example like U-net to examples for graph ?

**Comment by morgolock** [comment]
Hi @abhajaswal 

We'll evaluate your request.

In the meantime I'll suggest you taking a look at running Deeplab through Armnn (which will in turn call into ACL's neon/opencl backends)

You can run the model on either the CpuAcc or GpuAcc using the **ExecuteNetwork** tool from armnn.

https://www.tensorflow.org/lite/models/segmentation/overview
https://github.com/ARM-software/armnn/issues/260
