### ISSUE TITLE
Can gated recurrent units be deployed on ARM cortex a53?

### ISSUE THREAD

**Issue by Pradeepcbk** [ARM-software/ComputeLibrary#796]
I have a task of performing regression learning on a target board (ARM Cortex A53 processor).

I have completed the tasks of data and feature extraction.

Now, i am analyzing the performances of different learning algorithms (GRUs and LSTM) in tensorflow.

However, my concern is that not all models has the software supports to be deployed on the target board.

Out of the software libraries provided by ARM for ML models, i found out that only ARM NN on top of ARM compute library is the way to go. 

Although ACL has the function defnitions needed for the basic defnition of LSTM, in the description of the compute library - it specifies that it supports only SVM (Binary Classification) and CNN models.

Can anyone confirm if the LSTM models translated by ARM NN works with ACL?

Thanks in advance

**Comment by GeorgeARM** [comment]
Hello @Pradeepcbk,

Yes you can use LSTM functions and they should work in ACL. We have a DeepSpeech example as well [here](https://github.com/ARM-software/ComputeLibrary/blob/master/examples/graph_deepspeech_v0_4_1.cpp)
Hope this helps.
