### ISSUE TITLE
terminate called after throwing an instance of 'cl::Error'

### ISSUE THREAD

**Issue by rahulsharma11** [ARM-software/ComputeLibrary#797]
**libarm_compute.so | grep arm_compute_version:****
arm_compute_version=v19.02 Build options: {'embed_kernels': '1', 'arch': 'arm64-v8a', 'opencl': '1', 'neon': '0', 'asserts': '0', 'debug': '0', 'os': 'linux', 'Werror': '0'} Git hash=514be65ad8d3340f53fd9591035352ed285811ba

**Platform:**
rockpro64 (RK3399) Arm-64

**Operating System:**
Ubuntu18.04
 uname -a
Linux rockpro64 4.4.138-1097-rockchip-ayufan-gb5128c0a1684 #1 SMP Sat Sep 29 15:08:06 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux

Issue is -
While using "export ACL_NHWC=1" in mobilenetSSD(caffe) (91 classes), there is error-
terminate called after throwing an instance of 'cl::Error'
  what():  clEnqueueMapBuffer
Aborted

**Problem description:**
I am using Tengine with ACL in my rockpro64.
I followed this link-
https://github.com/OAID/Tengine/blob/master/doc/gpu_cpu_mssd.md
Tengine provides its 21-classes mobilenetSSD caffemodel.
*) Without using "export ACL_NHWC=1", GPU utilisation is 50-60%, FPS = 3 FPS.
*) With using "export ACL_NHWC=1", GPU utilisation is 60-70% , FPS = 9 FPS.

While using another 91-classes MobilenetSSD caffemodel.
*) Without using "export ACL_NHWC=1", GPU utilisation is 50-60%, FPS = 3 FPS.
*) With using "export ACL_NHWC=1", throws error-
terminate called after throwing an instance of 'cl::Error'
  what():  clEnqueueMapBuffer
Aborted

Not sure What is the exact issue here.
Any suggestion?
Can provide the caffemodel files if required.
Thanks in advance.

**Comment by morgolock** [comment]
Hi @rahulsharma11 

Could you please share the model files?

![model](https://user-images.githubusercontent.com/5577511/75333167-8db7a300-587d-11ea-9cdc-8e7d512efae3.png)

**Comment by morgolock** [comment]
Hi @rahulsharma11 

I cannot reproduce the crash, I checkout out 19.02 and built tengine. See below:

```
root@acl_hikey_dev:~/tmp/pabtel01/graph# env | grep ACL
ACL_NHWC=1
root@acl_hikey_dev:~/tmp/pabtel01/graph# LD_LIBRARY_PATH=$LD_LIBRARY_PATH:.  ./MSSD -d acl_opencl
/mnt/ufs/tmp/pabtel01/graph/MSSD
proto file not specified,using models/MobileNetSSD_deploy.prototxt by default
model file not specified,using models/MobileNetSSD_deploy.caffemodel by default
image file not specified,using tests/images/ssd_dog.jpg by default
ACL Graph Initialized
--------------------------------------
repeat 1 times, avg time per run is 207.087 ms
detect result num: 3 
dog	:100%
BOX:( 138.897 , 209.568 ),( 324.626 , 541.045 )
car	:100%
BOX:( 467.307 , 72.5773 ),( 687.391 , 171.043 )
bicycle	:99%
BOX:( 106.221 , 141.161 ),( 573.894 , 414.775 )
======================================
[DETECTED IMAGE SAVED]:	Mobilenet_SSD
======================================
```

I'm using the model from tengine: https://github.com/OAID/Tengine/blob/master/doc/gpu_cpu_mssd.md

Please provide the model and the command you use to run the test.

**Comment by rahulsharma11** [comment]
Hi @morgolock ,
Thanks for your time.
Attaching my 91 class model files
[91_class_mobilenet_ssd.zip](https://github.com/ARM-software/ComputeLibrary/files/4257119/91_class_mobilenet_ssd.zip)

With default models provided by Tengine Zoo works well.
But i wanted to have more classes with decent speed (ACL with GPU utilisation).
Thanks for the time and your notice.
Please let me know if you find some solution.

**Comment by morgolock** [comment]
Hi @rahulsharma11 

Thanks for sharing the model.

I confirm I can reproduce the problem, it looks like the kernel CLDepthwiseConvolutionLayer3x3NHWCKernel does not support the padding 2222.

```
root@acl_hikey_dev:~/tmp/pabtel01/graph# LD_LIBRARY_PATH=$LD_LIBRARY_PATH:.  ./MSSD -d acl_opencl -m ./deploy.caffemodel -p deploy_upgraded_withslice.prototxt 
/mnt/ufs/tmp/pabtel01/graph/MSSD
image file not specified,using tests/images/ssd_dog.jpg by default
ACL Graph Initialized
terminate called after throwing an instance of 'std::runtime_error'
  what():  in validate_arguments src/core/CL/kernels/CLDepthwiseConvolutionLayer3x3NHWCKernel.cpp:58: std::max(conv_info.pad_top(), conv_info.pad_bottom()) > 1
Aborted
```

**Comment by morgolock** [comment]
Hi @rahulsharma11 

We discussed this and the answer is that the kernel does not support  pad > 1. We have no plans to support this for now.

If you had built ACL with debug=1 you could have noticed this, whenever you get an error like this I'd advice rebuilding with debug=1 and rerunning the test to get more information.
