### ISSUE TITLE
Issue with CL and Neon Deconvolution layer 

### ISSUE THREAD

**Issue by abhajaswal** [ARM-software/ComputeLibrary#798]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

arm_compute_version=v19.11 Build options: {'embed_kernels': '1', 'os': 'linux', 'utils': '1', 'opencl': '1', 'neon': '1', 'benchmark_tests': '0', 'validation_tests': '0', 'arch': 'armv7a', 'asserts': '1', 'debug': '1', 'openmp': '1', 'cppthreads': '1', 'Werror': '0', 'examples': '1'} Git hash=unknown
**Platform:**
arm7va
**Operating System:**
linux

**Problem description:**
I am currently trying to port tensorflow u-net model onto arm-compute library.
I am using graph interface for this.

I am facing issue while porting it i am getting error in deconvolution layer.
for tensorflow deconvolution layer has , 
input shape   [1,1,1,32] float 32
Filter is shape type: float32[5,1,16,32] , strides 1, 1, 1, 1 
output shape is [1,5,1,16]
d
Input_layout is type NCHW
weights layout is type NHWC format set for graph

I have transposed weights for deconvolution in  tensorflow to  in NHWC format and provided like below in graph 
              
                <<DeconvolutionLayer(
                  1U, 5U, 16U,
                  get_weights_accessor(data_path, "UNet_dec6_filter_acl.npy",weights_layout),
                  std::unique_ptr<arm_compute::graph::ITensorAccessor>(nullptr)  ,
                  PadStrideInfo(1, 1, 0, 0)).set_name("deconv6")
              .set_name("deconv6")
But validate function NE/CLDeconvolutionlayer.cpp

ERROR in validate src/runtime/NEON/functions/NEDeconvolutionLayer.cpp:68: weights->dimension(width_idx) != weights->dimension(height_idx) 

Does the Deconvolution layer support only same kernel size dimensions?

If i comment this validation in code  it further gives error as:
!!!!!!!!!!!!!!!!!!!!!!!!!!!

ERROR in data_size_from_type ./arm_compute/core/Utils.h:137: Invalid data type
!!!!!!!!!!!!!!!!!!!!!!!!!!!

Please help in fixing this issue.

Logs are below: 

 [GRAPH][31-12-1969 04:16:52][INFO]  Running mutating pass : NodeFusionMutator

 [GRAPH][31-12-1969 04:16:52][INFO]  Running mutating pass : GroupedConvolutionMutator

 [GRAPH][31-12-1969 04:16:52][INFO]  Running mutating pass : InPlaceOperationMutator

 [GRAPH][31-12-1969 04:16:52][INFO]  Running mutating pass : DepthConcatSubTensorMutator

 [GRAPH][31-12-1969 04:16:52][INFO]  Running mutating pass : SplitLayerSubTensorMutator

 [GRAPH][31-12-1969 04:16:52][INFO]  Running mutating pass : NodeExecutionMethodMutator

 [GRAPH][31-12-1969 04:16:52][INFO]  Instantiated conv1 Type: GEMMConvolutionLayer Target: NEON Data Type: F32 Input shape: 1x256x31 Weights shape: 1x7x7x16 Output shape: 16x125x13 RELU

 [GRAPH][31-12-1969 04:16:52][INFO]  Instantiated conv2 Type: GEMMConvolutionLayer Target: NEON Data Type: F32 Input shape: 16x125x13 Weights shape: 16x5x5x32 Output shape: 32x61x5 RELU

 [GRAPH][31-12-1969 04:16:52][INFO]  Instantiated permute1 Type: PermuteLayer Target: NEON Data Type: F32 Input shape: 32x61x5 Output shape: 32x5x61 Permutation vector: 0x2x1

 [GRAPH][31-12-1969 04:16:52][INFO]  Instantiated conv3 Type: GEMMConvolutionLayer Target: NEON Data Type: F32 Input shape: 32x61x5 Weights shape: 32x5x5x32 Output shape: 32x29 RELU

 [GRAPH][31-12-1969 04:16:52][INFO]  Instantiated permute2 Type: PermuteLayer Target: NEON Data Type: F32 Input shape: 32x29 Output shape: 32x1x29 Permutation vector: 0x2x1

 [GRAPH][31-12-1969 04:16:52][INFO]  Instantiated conv4 Type: GEMMConvolutionLayer Target: NEON Data Type: F32 Input shape: 32x29 Weights shape: 32x5x1x32 Output shape: 32x13 RELU

 [GRAPH][31-12-1969 04:16:52][INFO]  Instantiated permute3 Type: PermuteLayer Target: NEON Data Type: F32 Input shape: 32x13 Output shape: 32x1x13 Permutation vector: 0x2x1

 [GRAPH][31-12-1969 04:16:52][INFO]  Instantiated conv5 Type: GEMMConvolutionLayer Target: NEON Data Type: F32 Input shape: 32x13 Weights shape: 32x5x1x32 Output shape: 32x5 RELU

 [GRAPH][31-12-1969 04:16:52][INFO]  Instantiated permute4 Type: PermuteLayer Target: NEON Data Type: F32 Input shape: 32x5 Output shape: 32x1x5 Permutation vector: 0x2x1

 [GRAPH][31-12-1969 04:16:52][INFO]  Instantiated conv6 Type: GEMMConvolutionLayer Target: NEON Data Type: F32 Input shape: 32x5 Weights shape: 32x5x1x32 Output shape: 32 RELU

weights->dimension(width_idx) = 1 weights->dimension(height_idx)) = 5
!!!!!!!!!!!!!!!!!!!!!!!!!!!

ERROR in validate src/runtime/NEON/functions/NEDeconvolutionLayer.cpp:68: weights->dimension(width_idx) != weights->dimension(height_idx)

**Comment by abhajaswal** [comment]
After commenting the assert code for neon target output comes correct but for target cl output is incorrect..  looking into this further. Kindly advice on same

**Comment by abhajaswal** [comment]
Hi,@ morgolock   @gmiodice can you please let me know any work around on this?

**Comment by abhajaswal** [comment]
The issue with output mismatch fixed by using corrrect activation layer BOUNDED_RELU instead of RELU as per the tensorflow pb file.

But in debug=0, and assert=0 case still the i need to comment out the line

ARM_COMPUTE_RETURN_ERROR_ON(weights->dimension(idx_w) != weights->dimension(idx_h)); 

in function 
Status CLDirectDeconvolutionLayer::validate()
and
NEDeconvolutionLayer::validate()


Is this code piece kept by  mistake in the files?

**Comment by morgolock** [comment]
Hi @abhajaswal 

It looks like it's safe to remove that assertion as you did. This is something we forgot to remove when we made changes to NEDeconvolutionLayer to use GEMM instead of DirectConvolution (which only supports square kernel sizes).
