### ISSUE TITLE
how to select the target OpenCL Device on Multi-platform OpenCL

### ISSUE THREAD

**Issue by peter197321** [ARM-software/ComputeLibrary#799]
Hi,

is there a way to specify and set for build ARM Compute Library within the environment of multiple OpenCL drivers on single SoC?    
So basically how to select the target OpenCL Device which to use?

**Comment by morgolock** [comment]
Hi @peter197321 

Please take a look at this: 
https://github.com/ARM-software/ComputeLibrary/issues/736#issuecomment-516910983
https://github.com/ARM-software/ComputeLibrary/issues/745#issuecomment-529865928

Hope this helps.
