### ISSUE TITLE
Can ACL support group in conv?

### ISSUE THREAD

**Issue by joey2014** [ARM-software/ComputeLibrary#80]
Alexnet uses two groups in conv2, conv4 and conv5.  Can ACL support group in conv?

**Comment by GeorgeARM** [comment]
Hello @joey2014 ,

As mentioned in #40 we currently do not support group in ACL but we are working on it.

Regards,
George

**Comment by mpflanzer** [comment]
Please feel free to re-open the issue if you have any follow-up questions.
