### ISSUE TITLE
Does acl support post training quantized model created by tflite

### ISSUE THREAD

**Issue by abhajaswal** [ARM-software/ComputeLibrary#802]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

**Platform:**

**Operating System:**

**Problem description:**
I want to know how to configure acl for post training quantized option where weights are in int8 and activation and input are in float32.  I'd like know if there is any examples for this? The default examples are with quantization aware training models

**Comment by morgolock** [comment]
Hi @abhajaswal 

Do you mean passing quantized weights into NEConvolutionLayer and FP32 input?. This is not supported by ACL. The weights must be the same data type as the input: https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/NEON/functions/NEConvolutionLayer.h#L84

Hope this helps.
