### ISSUE TITLE
Issue in DepthWise Convolution Layer

### ISSUE THREAD

**Issue by pranathibl** [ARM-software/ComputeLibrary#803]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

arm_compute_version=v19.05 Build options: {'opencl': '1', 'neon': '1', 'build': 'cross_compile', 'asserts': '0', 'debug': '1', 'Werror': '1'} Git hash=4ba87dbdc3b22220eba4a792c1f5c87e7a88c7af

**Platform:**
Raspberry Pi - 4
**Operating System:**
Raspbian Stretch 

**Problem description:**

I was trying to perform Y = MX + C , where M is Vector of shape(H=1,W=1,C=3), C is vector of shape(H=1,W=1,C=3).
My Input X is of shape (5,5,3).
M consists of only one element in channel , It is multiplied with the elements of X first channel (5,5).
C consists of only one element in channel , It is added with the elements of X first channel (5,5).

I was trying to use depthwise convolution for this operation.

I was getting error when I use the following code.
terminate called after throwing an instance of 'std::runtime_error'
  what():  in validate_arguments src/core/NEON/kernels/NEDepthwiseWeightsReshapeKernel.cpp:92: biases->dimension(0) != input->dimension(2)

**It was working as expected  when I compile the Compute Library with debug flag set to false.**

When i set the debug flag to true, I was running into issue.
It was occuring from this file NEDepthwiseWeightsReshapeKernel.cpp from  ARM_COMPUTE_RETURN_ERROR_ON(input->dimension(2) != output->dimension(1));
I have attached the files to reproduce the issue.

**Could you explain why this is kept, What alternative is there to  make this work if ARM Compute Library was built with debug flag set to true.**

[depthconv.txt](https://github.com/ARM-software/ComputeLibrary/files/4235117/depthconv.txt)
[Makefile.txt](https://github.com/ARM-software/ComputeLibrary/files/4235126/Makefile.txt)

**Comment by gmiodice** [comment]
Hi @pranathibl 

and thanks for your message.

When the debug flag is set to false, the error check is ignored unless you have the asserts flag set to true. I would suggest to compile with debug = false and asserts = true so you can trigger the errors as expected

Let us know if this can help.

**Comment by uu-praveeng** [comment]
Hi,

Let us know if this issue is addressed in 20.05.

Thank you,
Praveen.

**Comment by gmiodice** [comment]
Hi,

looking at the test case, it seems that C has only one element and then the size of first dimension does not match the size of the same dimension of the input and output. This is not supported because we cannot broadcast the bias addition. Can you have the input C with 3 elements?

Regards,
Gian Marco
