### ISSUE TITLE
PRelu Layer support as Graph Layer

### ISSUE THREAD

**Issue by krgor** [ARM-software/ComputeLibrary#805]
Hi,

As PRelu got added in 19.08 ACL, is there any plan to provide support of it as Graph Layer? 

To give you more details, I have a pretrained model with below layer and I want to implement it on ACL. It has different scalar for each channel and not like same scalar like Leaky ReLU.
        p_layer = PReLU(shared_axes=[1, 2])(p_layer)

https://www.tensorflow.org/api_docs/python/tf/keras/layers/PReLU

Let me know if there is any alternative available for PReLU on ACL for Graph Layer.

Thanks,
krgor

**Comment by GeorgeARM** [comment]
Hello @krgor,

Should be supported in latest release:
https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/graph/frontend/Layers.h#L906

/George
