### ISSUE TITLE
arm_compute_validation Could not load PGM image: ./data//images/opticalflow_old.pgm

### ISSUE THREAD

**Issue by kp30** [ARM-software/ComputeLibrary#807]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v20.02 Build options: {'pmu': '1', 'install_dir': '/home/kp/ml/acl_v20.02/build/install/acl', 'gles_compute': '1', 'embed_kernels': '1', 'arch': 'arm64-v8a', 'opencl': '1', 'neon': '1', 'build_dir': '/home/kp/ml/acl_v20.02/build/acl', 'benchmark_tests': '1', 'validation_tests': '1', 'asserts': '0', 'mali': '1', 'debug': '0', 'os': 'android', 'Werror': '1'} Git hash=a36878863444bab7713892be8e8808f4035134f6
**Platform:**
Mali-G52
**Operating System:**
Android P

**Problem description:**
COMMAND = ./arm_compute_validation ../data/ --filter-id=333964
Then:

> ...
> INFO: Could not load PGM image: ../data//images/opticalflow_old.pgm 

```
ComputeLibrary (master) $ tree data/
data/
`-- images
    |-- 1280x720.ppm
    |-- 128x128.ppm
    |-- 1920x1080.ppm
    |-- 640x480.ppm
    `-- 800x600.ppm
```

There are only 5 files in data/images/ and no "opticalflow_old.pgm."
Where can I find it?
Thanks

**Comment by morgolock** [comment]
Hi @kp30 

These are the input images for the validation test and we do not normally release them, you could create your own. We'll look into releasing them.
You could also take a look at our optical flow example which will generate the input data if you do not specify the files: https://github.com/ARM-software/ComputeLibrary/blob/master/examples/neon_opticalflow.cpp

Hope this helps.
