### ISSUE TITLE
qasymm8_signed enabling

### ISSUE THREAD

**Issue by uu-praveeng** [ARM-software/ComputeLibrary#809]
Hi,

In ACL 20.02 we have seen QASYMM8_SIGNED support for few layers. 
Does the  QASYMM8_SIGNED and QSYMM8(INT8) are both same?
If not, could you please point us to the documentation for QASYMM8_SIGNED .

Does QASYMM8_SIGNED help in achieving better performance for inference? 

Thank you,
Praveen.

**Comment by morgolock** [comment]
Hi @uu-praveeng 

These are two different data types, for more information please read: 
https://www.tensorflow.org/lite/performance/quantization_spec#signed_integer_vs_unsigned_integer

As tflite is going to prioritize the signed type we are adding support to all our kernels for QASYMM8_SIGNED.

I do not think you'll get a performace improvement using this new data type.

Hope this helps.

**Comment by uu-praveeng** [comment]
To be more specific does the QASYMM8_SIGNED implementation considers zero point to be at zero or some where in the INT8 range[-128,127]?

I assume it would not be at zero. Let me know if I am right.

**Comment by GeorgeARM** [comment]
Hello @uu-praveeng ,
Your assumptions are correct, this has asymmetric behavior as well within a different range though.

**Comment by uu-praveeng** [comment]
Thanks , this helps.
