### ISSUE TITLE
Can you give an example of using  NEIm2ColKernel.cpp

### ISSUE THREAD

**Issue by LYCUESTC** [ARM-software/ComputeLibrary#81]
I want to realize your for example, but  ,No matter,I  can't get the right result.
can you provide a source code examples!!!

/** Interface for the im2col reshape kernel.
 *
 * Rearranges image blocks into columns. It is used to strip out each convolution block to a single column.
 * It is used to transform a convolution to a plain matrix multiplication.
 *
 * For example taking into account the image below and assuming 3x3 image blocks with stride of 1 we have:
 *
 * @f[
 * \left( \begin{array}{cccc}
 * a00 & a01 & a02 & a03 \\
 * a10 & a11 & a12 & a13 \\
 * a20 & a21 & a22 & a23 \\
 * a30 & a31 & a32 & a33 \\
 * \end{array} \right)
 * \rightarrow
 * \left( \begin{array}{ccccccccc}
 * a00 & a01 & a02 & a10 & a11 & a12 & a20 & a21 & a22 \\
 * a01 & a02 & a03 & a11 & a12 & a13 & a21 & a22 & a23 \\
 * a10 & a11 & a12 & a20 & a21 & a22 & a30 & a31 & a32 \\
 * a11 & a12 & a13 & a21 & a22 & a23 & a31 & a32 & a33 \\
 * \end{array} \right)
 * @f]
 */

Thanks very much!

**Comment by LYCUESTC** [comment]
Anyone can solve this problem？

**Comment by LYCUESTC** [comment]
Is there anyone who can solve this problem?

**Comment by GeorgeARM** [comment]
Hello @LYCUESTC ,

Can you post your code on how you are trying to do it?

**Comment by xlxulin1** [comment]
Hello @LYCUESTC,
 plz search this post :  how to use NEIm2ColKernel::configure(.., std::pair<unsigned int, unsigned int> convolved_dims, ..)

**Comment by xlxulin1** [comment]
#63

**Comment by LYCUESTC** [comment]
@GeorgeARM   here's my code
Tensor input, output;
	unsigned int  batch = 1;
	unsigned int  width= 5;
	unsigned int  height= 4;
	float  tmpData;
	auto *src_data = new float[5 * 4 * batch];
	auto *dst_data = new float[3*3 * 2*3*1];

	for(unsigned int b = 0; b < batch; b++)
	{
	    for(unsigned int h = 0; h < 4; h++)
	    {
	        for(unsigned int w = 0; w < 5; w++)
	        {
	            src_data[b * (width * height) + h * width + w] = static_cast<float>(w+h);
	        }
	    }
	}
	
	printf("src_data[");
	for(int i=0;i<19;i++)
	{
		printf("%f,",src_data[i]);
	}
	printf("%f",src_data[19]);
	printf("]\n");
	
	// Initialize the tensors dimensions and type:
	const TensorShape shape(5, 4, batch);
	const TensorShape shape_im2col(3*3, 2 * 3, 1);
	output.allocator()->init(TensorInfo(shape_im2col, 1, DataType::F32));
	input.allocator()->init(TensorInfo(shape, 1, DataType::F32));

	NEIm2ColKernel im2Col;
	std::pair<unsigned int, unsigned int> pair(9, 6);
	PadStrideInfo padStrdInfo(1, 1, 0, 0);

	im2Col.configure(&input, &output, pair, padStrdInfo, false);

	// Allocate the input / output tensors:
	input.allocator()->allocate();
	output.allocator()->allocate();
	
	Window input_window;
	input_window.use_tensor_dimensions(input.info());
	// Create an iterator:
	
	Iterator input_it(&input, input_window);
	execute_window_loop(input_window, [&](const Coordinates & id)
	{
	//std::cout << "Setting item [" << id.x() << "," << id.y() << "," << id.z() << "]\n";
	*reinterpret_cast<float *>(input_it.ptr()) = src_data[id.z() * (4 * 5) + id.y() * 5 + id.x()];
	},
	input_it);

	im2Col.run(input_window);
       for(unsigned int h = 0; h < 6; h++)
	    {
	        printf("row :%d.\n", h);
	        for(unsigned int w = 0; w < 9; w++)
	        {
	            tmpData = *reinterpret_cast<float*>( output.buffer() + output.info()->offset_element_in_bytes(Coordinates(w,h,1)));
	            printf("%f,\n", tmpData);
	        }
	        printf("\n");
	    }

**Comment by GeorgeARM** [comment]
I modified the above code a bit:
```cpp
#include <iostream>
#include "arm_compute/runtime/Tensor.h"
#include "arm_compute/core/NEON/NEKernels.h"
#include "arm_compute/core/Helpers.h"

using namespace arm_compute;

int main(int argc, char**argv)
{
    Tensor input, output;
    unsigned int batch = 1;
    unsigned int width= 5;
    unsigned int height= 4;
    float tmpData;
    auto src_data = new float[5 * 4 * batch];
    auto dst_data = new float[33 * 23*1];

    int counter = 0;
    for(unsigned int b = 0; b < batch; b++)
    {
        for(unsigned int h = 0; h < 4; h++)
        {
            for(unsigned int w = 0; w < 5; w++)
            {
                src_data[b * (width * height) + h * width + w] = counter++;
            }
        }
    }

    //  Initialize the tensors dimensions and type:
    const TensorShape shape(5U, 4U, batch);
    const TensorShape shape_im2col(3U*3U, 2U * 3U, 1U);
    output.allocator()->init(TensorInfo(shape_im2col, 1, DataType::F32));
    input.allocator()->init(TensorInfo(shape, 1, DataType::F32));

    unsigned int conv_w = 0;
    unsigned int conv_h = 0;
    std::tie(conv_w, conv_h) = scaled_dimensions(5U, 4U, 3U, 1, 1, 0, 0, DimensionRoundingType::FLOOR);
    std::pair<unsigned int, unsigned int> pair(conv_w, conv_h);
    PadStrideInfo padStrdInfo(1, 1, 0, 0);

    NEIm2ColKernel im2Col;
    im2Col.configure(&input, &output, pair, padStrdInfo, false);

    // Allocate the input / output tensors:
    input.allocator()->allocate();
    output.allocator()->allocate();

    Window input_window;
    input_window.use_tensor_dimensions(input.info());
    // Create an iterator:

    Iterator input_it(&input, input_window);
    execute_window_loop(input_window, [&](const Coordinates & id)
    {
        //std::cout << "Setting item [" << id.x() << "," << id.y() << "," << id.z() << "]\n";
        *reinterpret_cast<float *>(input_it.ptr()) = src_data[id.z() * (4 * 5) + id.y() * 5 + id.x()];
    },
    input_it);

    // Print input
    input.print(std::cout);

    // Run kernel
    im2Col.run(im2Col.window());

    // Print output tensor
    output.print(std::cout);
}
```
Try it out.

**Comment by LYCUESTC** [comment]
@GeorgeARM  
Now I get the correct value  ！thank you very munch。
