### ISSUE TITLE
Quantization of Bias for QASYMM8_SIGNED Convolution

### ISSUE THREAD

**Issue by uu-praveeng** [ARM-software/ComputeLibrary#817]
Hi,

For Convolution I am passing the input,output,weights as qasymm8_signed quantized values with offset zero . If we consider inputQ = inputF*inputScale and weightsQ=weightsF*weightsScale

Then the BiasINT32  = inputScale*weightsScale*BiasF. This quantization is done by us on Bias .
What would be the best way to do the quantization to INT32. Is it just round(inputScale*weightsScale*BiasF) or do we need to do any extra saturation checks. 

Thank you,
Praveen.

**Comment by GeorgeARM** [comment]
Hello @uu-praveeng,

Compute Library does not perform any quantization at all, this is the quantization's framework responsibility. But from what I am aware of makes sense to do the calculation in `double`  (I think you need the most precision you can get here) then round as you mention and do all the extra checks for saturation and values like NaN etc.

Hope it makes sense.
George

**Comment by GeorgeARM** [comment]
Closing.
Reopen if needed
