### ISSUE TITLE
"Swish" activation function in ACL

### ISSUE THREAD

**Issue by krgor** [ARM-software/ComputeLibrary#819]
Hi,

I am using ACL 20.02 on Android 8.1.

I want to use **swish activation** function in my model which is defined as below:
f(x) =  x · σ(x), where σ(z) = (1 + exp(−z))−1 [Sigmoid/LOGISTIC]

I am not seeing such implementation in ACL. I am primarily using Graph APIs. Can you please consider this as a new feature request and tell if this can be implemented in upcoming releases.

It will be of great help if you can provide some hint if I can replicate swish activation by combination of some other layers.

Thanks,
krgor

**Comment by morgolock** [comment]
Hi @krgor 

Please take a look at this patch adding support for hard swish : https://eu-gerrit-1.euhpc.arm.com/c/VisualCompute/ComputeLibrary/+/227526
This will be supported in 20.05.

Hope this helps.

**Comment by krgor** [comment]
Thanks @morgolock ,

It will definitely help. I will look into it.

Regards,
krgor
