### ISSUE TITLE
HOG detection example

### ISSUE THREAD

**Issue by pradeepkrnik** [ARM-software/ComputeLibrary#820]
HI
  I am learning ARM compute library. 
  Is there any example for how to use HOG from compute library.
  I have built ARM NN for cross compilation on Ubuntu 16.04.
-thanks
Pradeep

**Comment by morgolock** [comment]
Hi @pradeepkrnik 

There are no examples demonstrating how to use HOG detection in ACL.

I'd suggest you looking into our validation tests to see how it works:
https://github.com/ARM-software/ComputeLibrary/blob/master/tests/validation/NEON/HOGMultiDetection.cpp

Hope this helps.

**Comment by pradeepkrnik** [comment]
HI Pablo,
Thanks for the reply.  
How to compile the code and run it .
is there any example on that. 

Also need information on how to use the test in the below directory
../../ComputeLibrary/tests/validation

I have build ACL with following 
scons arch=arm64-v8a neon=1 extra_cxx_flags="-fPIC" benchmark_tests=1 validation_tests=1

-thanks

**Comment by morgolock** [comment]
Hi @pradeepkrnik 

You can compile the validation tests with validation_tests=1. You can then use the --filter option to run any particular tests: --filter=".*HOGMultiDetection"

Hope this helps.

**Comment by morgolock** [comment]
Hi @pradeepkrnik 

You can compile the validation tests with validation_tests=1. You can then use the --filter option to run any particular tests: --filter=".*HOGMultiDetection"

Hope this helps.
