### ISSUE TITLE
Does ACL cpu support armv8.2 for fp16

### ISSUE THREAD

**Issue by ysh329** [ARM-software/ComputeLibrary#821]
Hi, I recently found there's a lot of inference frameworks supporting fp16 using v8.2 character.

Does ACL cpu support armv8.2 for fp16?

thanks in advance.

**Comment by morgolock** [comment]
Hi @ysh329 

Yes, some of the functions like NEConvolutionLayer support FP16 for armv8.2

https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/NEON/functions/NEConvolutionLayer.h#L83

You have to compile with arch=armv8.2-a

Hope this helps.

**Comment by ysh329** [comment]
> Hi @ysh329
> 
> Yes, some of the functions like NEConvolutionLayer support FP16 for armv8.2
> 
> https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/NEON/functions/NEConvolutionLayer.h#L83
> 
> You have to compile with arch=armv8.2-a
> 
> Hope this helps.

Thank u very much~~

**Comment by ysh329** [comment]
I found only armv8.2 fp16 supporting dwconv3x3 and 5x5 according to macro `__ARM_FEATURE_FP16_VECTOR_ARITHMETIC`. no other kernels NEON fp16 supported.

**Comment by morgolock** [comment]
Hi @ysh329 
No, NEConvolutionLayer use NEGEMM for FP16 which supports any kernel size: https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/NEON/functions/NEConvolutionLayer.h#L69

The validate() method will return an error if the kernel size is not supported for a particular data type.

Hope this helps.
