### ISSUE TITLE
is it right that reset the shape in NEGEMM.cpp

### ISSUE THREAD

**Issue by cogbee** [ARM-software/ComputeLibrary#823]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

<arm_compute_version=v20.02.1 Build options: {'arch': 'arm64-v8a', 'opencl': '0', 'neon': '1', 'build': 'native', 'debug': '0', 'os': 'linux', 'Werror': '1'} Git hash=575c81f38edecaa662f3ee45d04ad8efded4fa81

**Platform:**

**Operating System:**
Linux localhost.localdomain 4.14.0-115.el7a.0.1.aarch64 #1 SMP Sun Nov 25 20:54:21 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux

**Problem description:**
I write a demo to use ComputeLibrary to run  one Conv whose **kernel_size** is [2,1]. code likes:

```
arm_compute::NEConvolutionLayer conv;
 arm_compute::Tensor src;
 arm_compute::Tensor weightes;
 arm_compute::Tensor biases;
 arm_compute::Tensor res;
const arm_compute::TensorShape weight_shape(2, 1, src_shape.z(), ofm);
weightes.allocator()->init(arm_compute::TensorInfo(weight_shape, 1, arm_compute::DataType::F32));
......
conv.configure(&src, &weightes, &biases, &res, arm_compute::PadStrideInfo());
....
conv.run();
....
```

the result is not right. but when I reset the weight_shape, everything goes right.

```
const arm_compute::TensorShape weight_shape(1, 2, src_shape.z(), ofm);
```

I read the API in NEConvolutionLayer.h, the weigths format is [kernel_x, kernel_y, IFM, OFM].
But I have search some other clue in NEGEMM.cpp:
https://github.com/ARM-software/ComputeLibrary/blob/master/src/runtime/NEON/functions/NEGEMM.cpp#L114

```
...
TensorShape shape_tmp_a = a->info()->tensor_shape();
TensorShape shape_tmp_b = b->info()->tensor_shape();

shape_tmp_a.set(0, a->info()->dimension(0) * 4);
 shape_tmp_a.set(1, std::ceil(a->info()->dimension(1) / 4.0f));

const unsigned int transpose_w = 16 / data_size_from_type(b->info()->data_type());
shape_tmp_b.set(0, b->info()->dimension(1) * transpose_w);
shape_tmp_b.set(1, std::ceil(b->info()->dimension(0) / static_cast<float>(transpose_w)));

TensorInfo info_a = a->info()->clone()->set_tensor_shape(shape_tmp_a).set_is_resizable(true);
TensorInfo info_b = b->info()->clone()->set_tensor_shape(shape_tmp_b).set_is_resizable(true);
...
```
b is weight. Why shape_tmp_b reset the shape? 

SO My Question is: it is right that reset the shape in NEGEMM.cpp?

**Comment by morgolock** [comment]
Hi @cogbee 

Could you please share the complete code you wrote to configure the function?

Are you calling to allocate() after configure()?

**Comment by cogbee** [comment]
@morgolock https://github.com/cogbee/caffe2-arm/blob/master/operators/conv.cc

**Comment by cogbee** [comment]
@morgolock I think the key point is the kernel_size.............

**Comment by morgolock** [comment]
Hi @cogbee 

Can you please rebuild the library with debug=1 or asserts=1 and run the test to see if you hit any assertions?
