### ISSUE TITLE
Incorrect prefix when cross-compiling for Yocto/armv8 on ubuntu 18.04 x86_64

### ISSUE THREAD

**Issue by macenpav** [ARM-software/ComputeLibrary#825]
https://review.mlplatform.org/plugins/gitiles/ml/ComputeLibrary/+/e7019e8ff13a8e4e965cd811f90cf9e4e6a81592
Commit: e7019e8f COMPMID-3423: Update functions list in Doxygen

**Platform:**
x86_64 cross-cross compile for armv8

**Operating System:**
Ubuntu 18.04

**Problem description:**
When cross-compiling for Yocto Linux running on an armv8 board (NXP i.MX8) on Ubuntu 18.04 x86_64 machine an incorrect compiler prefix is set and thus the compile fails.

The issue lies in SConstruct:
```python
elif env['estate'] == '64' and 'v8' in env['arch']:
        if env['os'] == 'linux':
            #prefix = "aarch64-linux-gnu-" # breaks Yocto - current code
            prefix = "" # workaround
```
The script prepends the prefix "aarch64-linux-gnu-". Within the Yocto cross-compile environment, CXX is already set to something like `aarch64-poky-linux-g++ --sysroot=<yocto_sdk_install>/sysroots/aarch64-poky-linux` so the result is `aarch64-linux-gnu-aarch64-poky-linux-g++ --sysroot=/home/nxf52672/sdk-zeus/sysroots/aarch64-poky-linux`.

Thus the error looks as follows:
```
nxf52672@zcz01-8202:~/ComputeLibrary$ scons os=linux neon=1 opencl=1 embed_kernels=1 gles_compute=0 arch=arm64-v8a build=cross_compile examples=1 -j32
scons: Reading SConscript files ...
Mkdir("build")
ERROR: Compiler ' aarch64-linux-gnu-aarch64-poky-linux-g++  --sysroot=/home/nxf52672/sdk-zeus/sysroots/aarch64-poky-linux' not found
```

**Comment by mpekatsoula** [comment]
Hi @macenpav 

You can use toolchain_prefix in order to override the toolchain with scons:
`scons toolchain_prefix=aarch64-poky-linux- ...`
should do the trick

**Comment by macenpav** [comment]
It's not set as a prefix in the environment, but directly as CC, CXX env variables, so it must be empty in this case.

`toolchain_prefix=' '` (setting it to whitespace) works, there is a check that it is not empty. Thanks!
