### ISSUE TITLE
Is getauxval function has been called incorrect？

### ISSUE THREAD

**Issue by TsinghuaTop** [ARM-software/ComputeLibrary#826]
**Problem description:**

As you can see at https://github.com/ARM-software/ComputeLibrary/blob/6a7771e460abeac7d401d6d38a0fcf0a0d2c3cbe/src/runtime/CPUUtils.cpp#L354,
getauxval had been called for HWCAP, but when we see asm/hwcap.h in __arm__ arch not __aarch64__, the macro HWCAP_CPUID HWCAP_ASIMDHP not defined, And the same macro with same values defined.
 Assuming that HWCAP_THUMBEE is supported on the arm architecture, this code will be judged to support HWCAP_CPUID？

**Comment by morgolock** [comment]
Hi @TsinghuaTop 

ACL uses HWCAPS to detect support for fp16 and dot product in armv8-2.a. 

There are no special features in armv7a to query using HWCAPS so this should not be a problem. Do you get a compiler error? 

Please take a look at:
https://community.arm.com/developer/tools-software/oss-platforms/b/android-blog/posts/runtime-detection-of-cpu-features-on-an-armv8-a-cpu
