### ISSUE TITLE
Incorrect results in conv layer for particluar input

### ISSUE THREAD

**Issue by pranathibl** [ARM-software/ComputeLibrary#827]
arm_compute_version=v19.05 Build options: {'arch': 'armv7a', 'opencl': '0', 'neon': '1', 'build': 'cross_compile', 'debug': '0', 'os': 'linux'} Git hash=unknown

**Platform:Raspberry Pi

**Operating System:**Raspbian Stretch

I have attached the scripts for conv layer, inputs , bias , weights . I was using the 19.05 Compute library. What is the reason for this issue ? Can a patch in 19.05 source code resolves this issue.

[dozip.zip](https://github.com/ARM-software/ComputeLibrary/files/4731957/dozip.zip)

**Comment by morgolock** [comment]
Hi @pranathibl 

19.05 is about a year old, could you please update to 20.05?
