### ISSUE TITLE
Performance on 32bits system with quantized model is very poor 

### ISSUE THREAD

**Issue by vinceab** [ARM-software/ComputeLibrary#829]
Hello,

I have integrated the arm-compute library on the STM32MP15xx STMicroelectronics MPU which have a dual cortex-A7 (up to 800MHz) with 512MB (or 1GB) of RAM depending on the evaluation board used.

The performances of the ACL compared to TensorFlow Lite inference engine is very poor for quantized model.

As example for mobilenet_v1_0.5_128_quant.tflite, ACL is 4 times slower than TensorFlow Lite inference engine.

Find in attached file the perf.json file (in the perf.zip) of the benchmark_graph_mobilenet test:
/benchmark_graph_mobilenet --example_args=--target=neon,--threads=2,--type=qasymm8 --iterations=10 --instruments=scheduler_timer_ms --log-file=perf.json --log-format=json

Vincent
[perf.zip](https://github.com/ARM-software/ComputeLibrary/files/4763344/perf.zip)

**Comment by morgolock** [comment]
Hi @vinceab 

Thanks for reporting this, could you please share with us what's your base line and expectations?

**Comment by vinceab** [comment]
Hi,

I would like to provide to STMicroelectronics customers AI development environment including armNN (ACL) with good performance (same as Tensorflow Lite or even better).
So I was a little bit disapointed when I see the performances of ACL on 32 bits system.

**Comment by morgolock** [comment]
Hi @vinceab 

Sorry to hear that, ACL optimization effort is focused on armv8a and later, mostly aarch64 but we have some gemm kernels for aarch32.

armv7a code in ACL is not as optimised as the other archs I mentioned above. 

It would help if you could share the figures you use as base line from tflite so that we can investigate this further.

**Comment by vinceab** [comment]
What kind of figures do you need? performances figures? like inference time?

**Comment by morgolock** [comment]
Hi @vinceab 

The team will discuss this internally and decide if we are going to optimise armv7a.

ACL focus is on armv8a or later, armv7a kernels are optimized but not to the same level as armv8a and this explains why you see these results.
