### ISSUE TITLE
Can Tensor be reshaped?

### ISSUE THREAD

**Issue by joey2014** [ARM-software/ComputeLibrary#83]
In some test case, tensor should be reshaped, how to do it?  for example, at first the tensor size was initialized to w1xh1, next time we hope to just reshape the  tensor to different size, i.e. w2xh2  instead of doing initialization of whole layer.

**Comment by mpflanzer** [comment]
You could call `init` with a new `TensorShape` on the `TensorInfo` of the tensor you want to reshape. **But that will not work in all situations and you will need to make sure to set the strides and the offset into the buffer correctly.** And it also does only work if the tensor doesn't have any padding. If there is padding you would have holes in the reshaped tensor.

**Comment by joey2014** [comment]
@mpflanzer  Thanks! When reshape occurs, our code delete the ACL layer and the tensors bound to it and then create ACL layer and bind tensors to it again. According to your comment, only that way is safe.

**Comment by GeorgeARM** [comment]
Closing issue. Reopen if required.
