### ISSUE TITLE
 Image->allocator()->allocate() is too slow for large image

### ISSUE THREAD

**Issue by gallex** [ARM-software/ComputeLibrary#830]
**Platform:**
Raspberry PI4
**Operating System:**
Raspbian
**ACL version**
20.05

**Problem descriptio**
when use a large image  it is too slow to allocate memory,  for example, I run NEScharr3x3 : 

```
img.allocator()->init(TensorInfo(4000, 3000, Format::U8));
dx.allocator()->init(TensorInfo(4000, 3000, Format::U8));
dy.allocator()->init(TensorInfo(4000, 3000, Format::U8));

scharr3x3.config(&img, &dx, &dy,  BorderMode::REPLICATE);

src.allocator()->allocate();   <--- 
dx.allocator()->allocate();    <--- 
dx.allocator()->allocate();    <--- about 90ms for all those  allocate.

scharr3x3.run();                    <--  about 40ms 

```
the scharr3x3 run  is **very fast**  about 10 times than opencv,   but allocate memory is very slow

I try to pre-allocate memory myself then use import_memory()  to import it,  it is fast!  but the scharr3x3.run() become slow now.

```
img.allocator()->init(TensorInfo(4000, 3000, Format::U8));
dx.allocator()->init(TensorInfo(4000, 3000, Format::U8));
dy.allocator()->init(TensorInfo(4000, 3000, Format::U8));

scharr3x3.config(&img, &dx, &dy,  BorderMode::REPLICATE);

uint8_t *src_ptr=new uint8_t[src.info()->total_size()];
src.allocator()->import_memory(src_ptr);   
.. import_memory for dx
.. import_memory for dy       <--- it below 1ms  for all those  allocate.

scharr3x3.run();                    <--  about 80ms 

```
what wrong with it ?

**Comment by GeorgeARM** [comment]
Hello @gallex ,
We do have import capabilities in ACL but unfortunately Scharr3x3 is one of the kernels that add implicit padding to the tensors. We are working at the moment to remove padding requirements from our functions thus is will be quite trivial to import memory once done.
Do you have a specific list of kernels that you are interested in?

Hope this helps,
George

**Comment by gallex** [comment]
I this it may cause by unnecessary  memory initial when  run  allocate(),  I try to change runtime/ MemoryRegion.h  line 52  remove parentheses after `new unit8_t[space]` : 

FROM
```
     _mem         = std::shared_ptr<uint8_t>(new uint8_t[space](), [](uint8_t *ptr)
```
TO
```
    _mem         = std::shared_ptr<uint8_t>(new uint8_t[space], [](uint8_t *ptr)
```
then allocate the tensor is very fast now,   But: 1)  I don't know will those change effect other function.  2) function run time is slight longer ,  same as use import_memory()

**Comment by gallex** [comment]
now I use following function :NEScharr3x3, 	NEPhase ,  NEMagnitude

**Comment by GeorgeARM** [comment]
Hello @gallex,

Will note the functions of interest (fyi @mpekatsoula)
What do you time and measure? Do you time the whole program execution or just the call to allocate? If the second is the case then malloc might defer the actual page allocation until you request to access the memory. So you might be seeing allocate being so fast because memory is lazily requested, thus you might see bigger execution time from the function that actually request access to the memory.


Hope this helps,
George

**Comment by gallex** [comment]
Oh, you are right, I only measure the allocate call time. 

But, I still thing initial the memory is unnecessary, set a large block of memory to zero will waste lots time. 

maybe you can add a option params: inital the memory or not.

**Comment by GeorgeARM** [comment]
Hello @gallex, 
Yes I totally understand you suggestion, main reason for doing this was around the implicit padding that we have, we will most likely remove it once we get rid of the implicit padding (we are in the process of doing this).
Will capture this as feature request, will that be fine?

Best Regards,
George
