### ISSUE TITLE
How to use NEScale to resize image? I just tried it but it sames like a crop not resize?

### ISSUE THREAD

**Issue by thlyinyulin** [ARM-software/ComputeLibrary#831]
Image       src{}, dst{};
   
    NEScale     scale{};
   
    std::string output_filename{};
    PPMLoader ppm;
    ppm.open("/data/local/tmp/11-T1-native.ppm");

    ppm.init_image(src, Format::U8);
    constexpr int scale_factor = 2;
    TensorInfo dst_tensor_info(src.info()->dimension(0) / scale_factor, src.info()->dimension(1) /scale_factor, Format::U8);
    dst.allocator()->init(dst_tensor_info);
    scale.configure(&src, &dst, InterpolationPolicy::BILINEAR, BorderMode::UNDEFINED);
    
    src.allocator()->allocate();
    dst.allocator()->allocate();
    
    scale.run();

**Comment by thlyinyulin** [comment]
How do I need to fill in the parameter of scale configure to achieve the effect of resize。

**Comment by morgolock** [comment]
Hi @thlyinyulin 

Please take a look at the fixture in our validation test suite for an example on this: https://github.com/ARM-software/ComputeLibrary/blob/master/tests/validation/fixtures/ScaleFixture.h#L134

scale_y = scale_x = 0.5f will downscale the image to half its original size.

```
   TensorShape shape_scaled(shape);
        shape_scaled.set(idx_width, shape[idx_width] * scale_x);
        shape_scaled.set(idx_height, shape[idx_height] * scale_y);
        TensorType dst = create_tensor<TensorType>(shape_scaled, _data_type, 1, quantization_info, data_layout);
```

Hope this helps.

**Comment by thlyinyulin** [comment]
> downscale
Thanks for your replay! Your code is just creat dst's tensor size. My code creat the dst image's size width and height is just the src image's half. I think my dst image size is OK, but my question is why my dst's image is not the whole image's message, my dst image just cut a image of src image.
I saw the code in ScaleFixture.h
`scale.configure(&src, &dst, policy, border_mode, constant_border_value, sampling_policy, /* use_padding */ true, _align_corners);`
They have four more parameters than me. Is the 4 parameters Impact results？

**Comment by morgolock** [comment]
Hi @thlyinyulin 

Try using border mode = CONSTANT when you call configure.

Hope this helps.

**Comment by thlyinyulin** [comment]
> Hi @thlyinyulin
> 
> Try using border mode = CONSTANT when you call configure.
> 
> Hope this helps.

I tried this but it had no effect.

**Comment by morgolock** [comment]
Hi @thlyinyulin 


Your code looks good to me, it should downscale the input image by 2. How do you fill the input tensor with the ppm's data?

**Comment by thlyinyulin** [comment]
> Hi @thlyinyulin
> 
> Your code looks good to me, it should downscale the input image by 2. How do you fill the input tensor with the ppm's data?

int main(int argc, char **argv)
{
    
    Image       src{}, dst{};
    NEScale     scale{};
    std::string output_filename{};
    PPMLoader ppm;
    ppm.open("/data/local/tmp/11-T1-native.ppm");
   
    ppm.init_image(src, Format::U8);
    constexpr int scale_factor = 2;

    TensorInfo dst_tensor_info(src.info()->dimension(0) / scale_factor, src.info()->dimension(1) / scale_factor,
                                   Format::U8);

    dst.allocator()->init(dst_tensor_info);

    scale.configure(&src, &dst, InterpolationPolicy::BILINEAR, BorderMode::CONSTANT);
    
    src.allocator()->allocate();
    dst.allocator()->allocate();

    scale.run();

    if(ppm.is_open())
        {
            ppm.fill_image(dst);
            output_filename =  "/data/local/tmp/resout.ppm";
        }

     if(!output_filename.empty())
        {
            save_to_ppm(dst, output_filename); // save_to_ppm maps and unmaps the image to store as PPM
        }
    
    cout << dst.info()->dimension(0) << endl;
    cout << dst.info()->dimension(1) << endl;
    return 1;
}
This is all my code. Do I have a problem writing the image？

**Comment by morgolock** [comment]
Hi @thlyinyulin 

I don't see where you load the data into the input image.


Please try replacing:

`ppm.fill_image(dst);`

by
`ppm.fill_image(src);`

**Comment by thlyinyulin** [comment]
> Hi @thlyinyulin
> 
> I don't see where you load the data into the input image.
> 
> Please try replacing:
> 
> `ppm.fill_image(dst);`
> 
> by
> `ppm.fill_image(src);`

I tried the code and got a black image. I think this code may load the data into the input image 
 ppm.init_image(src, Format::U8); Could you please share how you load the data into input image?

**Comment by morgolock** [comment]
Hi @thlyinyulin 

I think the problem is that your code is not filling the input image properly.

Please take a look at : https://github.com/ARM-software/ComputeLibrary/blob/master/examples/neoncl_scale_median_gaussian.cpp#L87

you should be calling ppm.fill_image(src) before the call to run()

**Comment by thlyinyulin** [comment]
> Hi @thlyinyulin
> 
> I think the problem is that your code is not filling the input image properly.
> 
> Please take a look at : https://github.com/ARM-software/ComputeLibrary/blob/master/examples/neoncl_scale_median_gaussian.cpp#L87
> 
> you should be calling ppm.fill_image(src) before the call to run()

 That's the problem, I change the code as you say. It successed. Thank you very much for your help!
