### ISSUE TITLE
How can I import a  Opencv ROI image

### ISSUE THREAD

**Issue by gallex** [ARM-software/ComputeLibrary#832]
opencv cv has a ROI function, which can create a small  image from a large image and share the memory of large image. 

I guess  ROI can be regarded as a Image with "Large Padding" , so if I can correct  set strides_in_bytes, offset_first_element_in_bytes, total_size_in_bytes etc then it would OK?

however when I use following sentence :
```
img.info()->init(TensorShape(w, h), Format::U8, strides_in_bytes, offset_first_element_in_bytes, total_size_in_bytes);
```
compiler report : ITensorInfo has no init method .

I wonder does it possible  to  import  ROI  image to ACL.

**Comment by morgolock** [comment]
Hi @gallex 

Could you please share the full code initializing `img`?

An alternative approach would be to use https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/SubTensor.h

Hope this helps.

**Comment by gallex** [comment]
I think subtensor can't chang width and hight,  maybe  I am wrong.

**Comment by gallex** [comment]
Hi , here is the code

```
Mat img(1000, 2000, CV_8U1C);

roi_img=img(Rect(50, 50, 100, 200);

src_img->info()->init(TensorShape(roi_img.cols, roi_img.rows), Format::U8, roi_img.step[0],  0,  roi_img.step[0]*roi_img.rows);

src_img.allocator()->import_memory(roi_img.data);

```

**Comment by gallex** [comment]
I had  resolved it, just change `src_img->info` to `src_allocator->info()`. 

full code is here :
```
   Mat img(1000, 2000, CV_8U1C);
   roi_img=img(Rect(50, 50, 100, 200);
   Image src_img;

   src_img->allocator()->info().init(
       TensorShape(roi_img.cols, roi_img.rows),
       Format::U8, 
       Strides(1, roi_img.step[0]), 
       0, 
       roi_img.step[0]*roi_img.rows
   );

   src_img.allocator()->import_memory(roi_img.data);
```
