### ISSUE TITLE
rounding modes int qasymm8_signed inference

### ISSUE THREAD

**Issue by uu-praveeng** [ARM-software/ComputeLibrary#834]
Hi ,

We are working on support low precision inference using ACL. Quantization mode that we use qasymm8_signed.

Our resultant network looks similar to this ...nequantize->conv_int8->nedequantize.... All 3 layers use ACL api for execution.we want to increase the int8 inference accuracy. We have observed different rounding modes for different architectures. 

NeQuantize on raspi uses - rounding : tozero (as per line 183 at [link](https://arm-software.github.io/ComputeLibrary/v20.05/_n_e_quantization_layer_kernel_8cpp_source.xhtml))

Is there a reason behind such selection?Do we have option to change the rounding modes to quantize layer?

Thank you,
Praveen.

**Comment by morgolock** [comment]
Hi @uu-praveeng 

It looks like the rounding mode is inconsistent across different architectures, which is wrong. I'll label this as a bug and we'll fix it.

Thanks for reporting this.

**Comment by GeorgeARM** [comment]
Hello @uu-praveeng,

This behavior is intended for armv7, 
For armv8 there is a dedicated instrinsic for converting float to signed integer with the appropriate rounding mode which round to even. Unfortunately for armv7 this does not exist so the fastest way is to round towards zero.
More info: https://arm-software.github.io/ComputeLibrary/v20.05/namespacearm__compute.xhtml#a4ff1249e423ae9bfab075f5317c4d004

Does this cause any issues in your final accuracy evaluation?

**Comment by morgolock** [comment]
Closing, please reopen if needing further assistance.
