### ISSUE TITLE
 undefined reference to `__multi3'

### ISSUE THREAD

**Issue by DroneMesh** [ARM-software/ComputeLibrary#835]
Hi,

I keep running into this issue and unable to resolve i am compiling for armv7 with tfcompile.

Any ides?

obj/main/testboard/graph/graph.o: In function `entry':
__compute_module:(.text+0xafe): undefined reference to `__multi3'
__compute_module:(.text+0xcfa): undefined reference to `__multi3'
__compute_module:(.text+0xe90): undefined reference to `__multi3'
__compute_module:(.text+0x1000): undefined reference to `__multi3'
collect2: error: ld returned 1 exit status

**Comment by morgolock** [comment]
Hi @DroneMesh 

Please let us know what toolchain you're using to compile the library.

Please take a look at the docs: https://arm-software.github.io/ComputeLibrary/v20.05/index.xhtml#S3_2_1_library

For linux try the toolchain: gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf

Hope this helps.
