### ISSUE TITLE
OpenCL missing functions

### ISSUE THREAD

**Issue by NPellet** [ARM-software/ComputeLibrary#838]
Hi,

I was wondering if there's any reason that not all OpenCL 1.2 functions are defined in the stub CL library.

Currently if I understand well, the followings are defined in OpenCL.h (see below). It is my understanding that clEnqueueFillBuffer, among others, is defined in OpenCL 1.2.

We use the ComputeLibrary but also OpenCL as a standalone for our ARM Mali. Would be great if all the functions were defined. My understanding is that this would be very little work as there's no implementation, correct ?

List of OpenCL symbols:

```
    DECLARE_FUNCTION_PTR(clCreateContext);
    DECLARE_FUNCTION_PTR(clCreateContextFromType);
    DECLARE_FUNCTION_PTR(clCreateCommandQueue);
    DECLARE_FUNCTION_PTR(clGetContextInfo);
    DECLARE_FUNCTION_PTR(clBuildProgram);
    DECLARE_FUNCTION_PTR(clEnqueueNDRangeKernel);
    DECLARE_FUNCTION_PTR(clSetKernelArg);
    DECLARE_FUNCTION_PTR(clReleaseKernel);
    DECLARE_FUNCTION_PTR(clCreateProgramWithSource);
    DECLARE_FUNCTION_PTR(clCreateBuffer);
    DECLARE_FUNCTION_PTR(clRetainKernel);
    DECLARE_FUNCTION_PTR(clCreateKernel);
    DECLARE_FUNCTION_PTR(clGetProgramInfo);
    DECLARE_FUNCTION_PTR(clFlush);
    DECLARE_FUNCTION_PTR(clFinish);
    DECLARE_FUNCTION_PTR(clReleaseProgram);
    DECLARE_FUNCTION_PTR(clRetainContext);
    DECLARE_FUNCTION_PTR(clCreateProgramWithBinary);
    DECLARE_FUNCTION_PTR(clReleaseCommandQueue);
    DECLARE_FUNCTION_PTR(clEnqueueMapBuffer);
    DECLARE_FUNCTION_PTR(clRetainProgram);
    DECLARE_FUNCTION_PTR(clGetProgramBuildInfo);
    DECLARE_FUNCTION_PTR(clEnqueueReadBuffer);
    DECLARE_FUNCTION_PTR(clEnqueueWriteBuffer);
    DECLARE_FUNCTION_PTR(clReleaseEvent);
    DECLARE_FUNCTION_PTR(clReleaseContext);
    DECLARE_FUNCTION_PTR(clRetainCommandQueue);
    DECLARE_FUNCTION_PTR(clEnqueueUnmapMemObject);
    DECLARE_FUNCTION_PTR(clRetainMemObject);
    DECLARE_FUNCTION_PTR(clReleaseMemObject);
    DECLARE_FUNCTION_PTR(clGetDeviceInfo);
    DECLARE_FUNCTION_PTR(clGetDeviceIDs);
    DECLARE_FUNCTION_PTR(clGetMemObjectInfo);
    DECLARE_FUNCTION_PTR(clRetainEvent);
    DECLARE_FUNCTION_PTR(clGetPlatformIDs);
    DECLARE_FUNCTION_PTR(clGetKernelWorkGroupInfo);
    DECLARE_FUNCTION_PTR(clGetCommandQueueInfo);
    DECLARE_FUNCTION_PTR(clGetKernelInfo);
    DECLARE_FUNCTION_PTR(clGetEventProfilingInfo);
    DECLARE_FUNCTION_PTR(clSVMAlloc);
    DECLARE_FUNCTION_PTR(clSVMFree);
    DECLARE_FUNCTION_PTR(clEnqueueSVMMap);
    DECLARE_FUNCTION_PTR(clEnqueueSVMUnmap);
    DECLARE_FUNCTION_PTR(clEnqueueMarker);
    DECLARE_FUNCTION_PTR(clWaitForEvents);
```

**Comment by gmiodice** [comment]
Hi @NPellet ,

many thanks for your question and using ACL.

The stub OpenCL Library (OpenCL.h) only includes the OpenCL functions used by the Arm Compute Library. The only reason why we do not have the full set of functions is because the library does not use all the functions defined in OpenCL 1.2. It would be good adding all the functions defined in OpenCL 1.2 however we should also consider how to validate the functions not used within the ACL.

I flag this question as "feature request" and check with the team if there are other implications apart from the validation.

Many thanks for your question/request,
Gian Marco

**Comment by morgolock** [comment]
Hi @NPellet 

There should be no need to add other unused CL functions to the ACL's header file OpenCL.h. If you prebuild the library then when you build your application you have to include the actual OpenCL.h header (not the one in ACL) and link against the actual libOpenCL.

This could be only a problem if you build the library along with your application.

Closing the issue, please reopen if further assistance is required.
