### ISSUE TITLE
expected dimensions in neon_sgemm.cpp

### ISSUE THREAD

**Issue by GalMoore** [ARM-software/ComputeLibrary#839]
I'm trying to run the neon_sgemm.cpp example with a matrix.npy file I created of shape 32x32 and data type is floating point32. .npy created in python. I am getting the error below. Any ideas?
Thanks! 

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!

ERROR in open /home/gal/code/Compute_Library_Comparison/ComputeLibrary/utils/ImageLoader.h:399: Accessing /home/gal/code/compileACL_Neon_CNN/32x32_FP.npy: basic_ios::clear: iostream error 
!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by sanpar02** [comment]
Thanks for your question, @GalMoore 
Based on the message, it looks like reading the file is failed for some reason.
For me to investigate, could you provide your command line so I can try to reproduce myself? If you could provide your 'npy' file as well, it would be easier for me to try.

Thanks.

**Comment by GalMoore** [comment]
@sanpar02 the issue was actually in the compilation part. Thanks!

**Comment by sanpar02** [comment]
@GalMoore 

May I ask if the problem is gone if you resolve the issue in the compilation part?

Thanks.

**Comment by GalMoore** [comment]
Yes it works now thanks.
