### ISSUE TITLE
Sgemm optimize on A53 core

### ISSUE THREAD

**Issue by yiicy** [ARM-software/ComputeLibrary#843]
hello, I have some question on sgemm a53 neon implement,  [https://github.com/ARM-software/ComputeLibrary/blob/6a7771e460abeac7d401d6d38a0fcf0a0d2c3cbe/src/core/NEON/kernels/arm_gemm/kernels/a32_sgemm_8x6/a53.cpp#L89](url)

1. Compare to general implement of sgemm, the A53 implement use two general register load instruction "ldr" instead of a vector load instruction "vldr", this really can improve performance but makes me confused. Can you give me some explanation? thanks
2. There is another question, for i can not find any docs about A53 hardware architecture and software optimize guide on internet, but i guess to optimize a compute-bound task an A53 core is different with other cores, so could you share with me some optimize experience an A53 core, some material is also ok, thanks a lot

**Comment by yiicy** [comment]
any one can give me some opinion...

**Comment by gmiodice** [comment]
@yiicy,

many thanks for posting the question and using ACL.

Regarding question number 2, unfortunately we do not have optimization guides for Cortex-A53 available. 

However, I would like to share the optimization guide for Cortex-A55 (https://static.docs.arm.com/epm128372/20/arm_cortex_a55_software_optimization_guide_v2.pdf) which should help you answering question number 1 (Page 36-37)

Hope this can help.
