### ISSUE TITLE
Example using NEON CNN with dilation

### ISSUE THREAD

**Issue by GalMoore** [ARM-software/ComputeLibrary#844]
Hey, 

Is there  an example of using dilation in a NEON [NEConvolutionalLayer](https://github.com/ARM-software/ComputeLibrary/blob/36ccc90158c65844b3c53c5462c6d7d852b97278/arm_compute/runtime/NEON/functions/NEConvolutionLayer.h) ?

Thanks

**Comment by sanpar02** [comment]
Hi @GalMoore 

Unfortunately, our examples (neon_*, cl_*) don't seem to use dilation.
Are there any specific things you want to see from examples?

Thanks.

**Comment by GalMoore** [comment]
Hey @sanpar02,

I was having an issue with dilations - but after a thorough debugging I discovered the issue was not with dilations at all. It looks like when converting from pytorch to ACL conv layer (neon) requires the following changes:
-> flip H and W dims for input tensor
-> flip kernel and padding order (in case of non symmetrical kernel / padding)
Now it works fine, thanks!

Gal

**Comment by sanpar02** [comment]
Glad to hear you could find a solution.

Thanks for your update!
