### ISSUE TITLE
I compare ComputeLibrary with arch x86_64,how can i run test in pc?

### ISSUE THREAD

**Issue by mathpopo** [ARM-software/ComputeLibrary#845]
I compare ComputeLibrary with arch x86_64,how can i run test in pc?

(base) chenxin@Nitro-AN515:~/Downloads/armnn-onnx/ComputeLibrary/build/tests$ ./benchmark_graph_mnist --example_args=--target=x86_64
Version = arm_compute_version=v20.05 Build options: {'extra_cxx_flags': '-fPIC', 'benchmark_tests': '0', 'validation_tests': '0', 'arch': 'x86_64'} Git hash=b'6a7771e460abeac7d401d6d38a0fcf0a0d2c3cbe'
CommandLine = ./benchmark_graph_mnist --example_args=--target=x86_64 
CL_DEVICE_VERSION = OpenCL 1.2 CUDA
Iterations = 1
Running [0] 'Examples/benchmark_graph_mnist'
WARNING: Skipping invalid option '--target=x86_64'!
Threads : 1
Target : NEON
Data type : F32
Data layout : NHWC
Tuner enabled? : false
Cache enabled? : false
Tuner mode : Normal
Tuner file : 
Fast math enabled? : false

ERROR: in generate_build_options src/core/CL/CLCompileContext.cpp:262: Non uniform workgroup size is not supported!!
Executed 1 test(s) (0 passed, 0 expected failures, 0 failed, 1 crashed, 0 disabled) in 0 second(s)

(base) chenxin@Nitro-AN515:~/Downloads/armnn-onnx/ComputeLibrary/build/tests$ ./benchmark_graph_mnist --example_args=--target=CL
Version = arm_compute_version=v20.05 Build options: {'extra_cxx_flags': '-fPIC', 'benchmark_tests': '0', 'validation_tests': '0', 'arch': 'x86_64'} Git hash=b'6a7771e460abeac7d401d6d38a0fcf0a0d2c3cbe'
CommandLine = ./benchmark_graph_mnist --example_args=--target=CL 
CL_DEVICE_VERSION = OpenCL 1.2 CUDA
Iterations = 1
Running [0] 'Examples/benchmark_graph_mnist'
Threads : 1
Target : CL
Data type : F32
Data layout : NHWC
Tuner enabled? : false
Cache enabled? : true
Tuner mode : Normal
Tuner file : 
Fast math enabled? : false

ERROR: in generate_build_options src/core/CL/CLCompileContext.cpp:262: Non uniform workgroup size is not supported!!
Executed 1 test(s) (0 passed, 0 expected failures, 0 failed, 1 crashed, 0 disabled) in 0 second(s)

**Comment by sanpar02** [comment]
Hi @mathpopo 

If I understand your question correctly and based on your log, it looks like you want to compare two results from ACL's OpenCL benchmark executions on an Arm-based machine and on an x86_64 machine which I suppose supports OpenCL.

If my understanding is correct, the execution of OpenCL backend on x86_64 is not our supported use case even if it might be possible theoretically. In addition to that, it wouldn't give you much meaningful information since you'll lose all the Arm-specific optimization on an x86_64 machine which essentially makes the comparison is a bit unfair.

In the case of NEON, for your information, I don't think we can execute NEON backend on an x86_64 machine at all as the backend is completely written using NEON intrinsics which is not executable on the x86_64 machine.

I hope it helps.

Thanks.

**Comment by mathpopo** [comment]
@sanpar02   i just modify arch from arm to X86_64,Any other modification?

**Comment by sanpar02** [comment]
Hi @mathpopo 

Sorry if I wasn't clear enough.
What I was trying to say was that executing Compute Library on x86_64 is not a supported use case.

I understand ArmNN's `ExecuteNetwork` binary supports the execution on x86_64 (although as far as I understand the implementations are *not* optimized for performance), Compute Library doesn't support the same use case.

Thanks.

**Comment by mathpopo** [comment]
@sanpar02  thank you for you help.i just use armnn (in x86_64 pc)
(base) chenxin@Nitro-AN515:~/Downloads/armnn-onnx/armnn/build$ ./ArmnnQuantizer --help
Convert a Fp32 ArmNN model to a quantized ArmNN model.

Options:
  -h [ --help ]                   Display help messages
  -f [ --infile ] arg             Input file containing float 32 ArmNN Input 
                                  Graph
  -s [ --scheme ] arg (=QAsymmU8) Quantization scheme, "QAsymmU8" or "QAsymmS8"
                                  or "QSymm16", default value QAsymmU8
  -c [ --csvfile ] arg            CSV file containing paths for RAW input 
                                  tensors
  -p [ --preserve-data-type ]     Preserve the input and output data types
  -d [ --outdir ] arg             Directory that output file will be written to
  -o [ --outfile ] arg            ArmNN output file name

(base) chenxin@Nitro-AN515:~/Downloads/armnn-onnx/armnn/build$ ./ArmnnQuantizer -f /home/chenxin/Downloads/models/vision/classification/mobilenet/model/mobilenetv2-7.armnn -c /home/chenxin/Downloads/models/vision/classification/mobilenet/model/mobilenetv2-7.csv -d /home/chenxin/Downloads/models/vision/classification/mobilenet/model/ -o /home/chenxin/Downloads/models/vision/classification/mobilenet/model/mobilenetv2-7-int8.armnn

(base) chenxin@Nitro-AN515:~/Downloads/armnn-onnx/armnn/build$ ./ArmnnConverter -f onnx-binary -m /home/chenxin/Downloads/models/vision/classification/mobilenet/model/mobilenetv2-7.onnx -i data -s 1 3 224 224 -o mobilenetv20_output_flatten0_reshape0 -p /home/chenxin/Downloads/models/vision/classification/mobilenet/model/mobilenetv2-7.armnn


so i doubt maybe computerlibrary can be used in x86_64( optimized for performance  is not important)

and ,  i donot have a device using opencl,so i select x86_64

**Comment by sanpar02** [comment]
Hi @mathpopo 

Theoretically, if you have any Linux-based boards equipped with Arm's Mali GPUs should be fine.

We have some tutorials using Raspberry Pi and Hikey960 [here](https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/profiling-alexnet-on-raspberry-pi-and-hikey-960-with-the-arm-compute-library/build-the-arm-compute-library-on-pi), but again, any of the boards with Arm Mali GPUs should be fine.

I hope it helps.

Thanks.

**Comment by mathpopo** [comment]
@sanpar02 
Raspberry Pi  can use opencl?need mail.so?

**Comment by mathpopo** [comment]
@sanpar02  Adreno(TM) 506  opencl  cost too much time ,because which need Adreno self optimization?

/benchmark_graph_mnist --example_args=--target=CL                             <
Version = arm_compute_version=v20.05 Build options: {'arch': 'arm64-v8a', 'neon': '1', 'opencl': '1', 'embed_kernels': '1', 'extra_cxx_flags': '-fPIC', 'benchmark_tests': '0', 'validation_tests': '0', 'os': 'android'} Git hash=b'6a7771e460abeac7d401d6d38a0fcf0a0d2c3cbe'
CommandLine = ./benchmark_graph_mnist --example_args=--target=CL 
CL_DEVICE_VERSION = OpenCL 2.0 Adreno(TM) 506
Iterations = 1
Running [0] 'Examples/benchmark_graph_mnist'
Threads : 1
Target : CL
Data type : F32
Data layout : NHWC
Tuner enabled? : false
Cache enabled? : true
Tuner mode : Normal
Tuner file : 
Fast math enabled? : false

  Wall clock/Wall clock time:    AVG=4061.0000 us
Executed 1 test(s) (1 passed, 0 expected failures, 0 failed, 0 crashed, 0 disabled) in 7 second(s)
HWBKK-Q:/data/local/tmp $ ./benchmark_graph_mnist                                                                                                                                                          
Version = arm_compute_version=v20.05 Build options: {'arch': 'arm64-v8a', 'neon': '1', 'opencl': '1', 'embed_kernels': '1', 'extra_cxx_flags': '-fPIC', 'benchmark_tests': '0', 'validation_tests': '0', 'os': 'android'} Git hash=b'6a7771e460abeac7d401d6d38a0fcf0a0d2c3cbe'
CommandLine = ./benchmark_graph_mnist 
CL_DEVICE_VERSION = OpenCL 2.0 Adreno(TM) 506
Iterations = 1
Running [0] 'Examples/benchmark_graph_mnist'
Threads : 1
Target : NEON
Data type : F32
Data layout : NHWC
Tuner enabled? : false
Cache enabled? : false
Tuner mode : Normal
Tuner file : 
Fast math enabled? : false

  Wall clock/Wall clock time:    AVG=1895.0000 us
Executed 1 test(s) (1 passed, 0 expected failures, 0 failed, 0 crashed, 0 disabled) in 0 second(s)

**Comment by sanpar02** [comment]
Hi @mathpopo 

I will have to double-check but as far as I understand RPi doesn't support OpenCL officially.

Thanks.
