### ISSUE TITLE
clang++ does support OpenMP

### ISSUE THREAD

**Issue by alexeyr** [ARM-software/ComputeLibrary#847]
See
https://github.com/ARM-software/ComputeLibrary/blob/6a7771e460abeac7d401d6d38a0fcf0a0d2c3cbe/SConstruct#L166-L169

In our experiments these lines can be removed and work fine on Android, tests pass as well.

**Comment by sanpar02** [comment]
Hi @alexeyr 

Thanks for using the library. We noticed that the condition was written a quite while ago.

Let us validate if it is working with our validation process and get back to you. 

Thanks.

**Comment by sanpar02** [comment]
Hi @alexeyr 

With local testing, I could see the lines you spotted are redundant for the toolchain we're currently supporting.
I'll raise this internally and discuss it with other team members to see if we can add this feature.

Thanks.
