### ISSUE TITLE
Different IN_MAP(IN CHANNEL) normalization definitions in Caffe and in ACL

### ISSUE THREAD

**Issue by cyberfire** [ARM-software/ComputeLibrary#85]
Hi, ACL guys,

The CROSS-CHANNEL (CROSS-MAP) result of Caffe implementation and ACL is the same, while ACL has different understanding of IN-CHANNEL(IN-MAP) with Caffe.

Caffe will do a normalization with the square box related, which size is norm_size x norm_size.
Please refers to the illustrative function in src/caffe/test/test_lrn_layer.cpp

template <typename TypeParam>
void LRNLayerTest<TypeParam>::ReferenceLRNForward

ACL just calculates the elements following the width axis (dim==0) for IN-MAP, per my understanding of NENormalizationLayerKernel::normalize().

Please let me know if there is a plan to follow Caffe's IN CHANNEL normalization method?
@AnthonyARM 

Thanks,
Cyberfire

**Comment by GeorgeARM** [comment]
Hello @cyberfire ,

The current IN-MAP normalization that we support follows the OpenVX specification.
Yes we have already identified that the Caffe in-map normalization is different and we are planning to support this as well.

Regards,
George

**Comment by cyberfire** [comment]
@GeorgeARM The answer is clear.  I will close this ticket.
