### ISSUE TITLE
ACL performance with onnxruntime_perf_test

### ISSUE THREAD

**Issue by Dan5002** [ARM-software/ComputeLibrary#850]
I'm using ACL v19.08 with onnxruntime 1.3.1.

I'd like some help interpreting the performance information from onnxruntime_perf_test.  The console output from perf_test with and then without acl is shown below.

Is it true that time spent on operations = 'Average inference time cost' - 'Session creation time cost'  ?

In other words, is there a session creation time cost per inference time cost?

That is the only way I can see that ACL is outperforming native operations.

For ACL:
144.871 ms - 0.127918 s = 16.95 ms

Non-ACL:
84.3236 ms - 0.06094 s = 23.38 ms

But, why the increased session creation time cost for ACL?

And why the decreased CPU utilization?

result.csv shows there is very little variance, so average inference time is a good proxy for any one of the inferences.

# onnxruntime_perf_test -m times -r 10 -e acl /sdcard/testdata/squeezenet1.0-9/model.onnx result.csv
Session creation time cost: 0.127918 s
Total inference time cost: 1.44871 s
Total inference requests: 10
Average inference time cost: 144.871 ms
Total inference run time: 1.44916 s
Avg CPU usage: 68 %
Peak working set size: 158171136 bytes
# onnxruntime_perf_test -m times -r 10 /sdcard/testdata/squeezenet1.0-9/model.onnx result.csv
Session creation time cost: 0.06094 s
Total inference time cost: 0.843236 s
Total inference requests: 10
Average inference time cost: 84.3236 ms
Total inference run time: 0.843345 s
Avg CPU usage: 100 %
Peak working set size: 49754112 bytes
#

**Comment by morgolock** [comment]
Hi @Dan5002 

Could you please run the tests with v20.08? The version of the library you are using is about a year old.

**Comment by skottmckay** [comment]
Session creation time is completely separate to the inferencing time. It includes loading the model and doing any setup in preparation for running the model. This happens once. 
The inferencing time is the time it takes to run the model using the session. This happens as many times as the performance test is configured to do. 

Generally you only care about the inferencing time when doing performance testing, and can ignore the session creation time.
