### ISSUE TITLE
num_groups not passed to NEConvolutionLayer::validate in NEConvolutionLayer::configure

### ISSUE THREAD

**Issue by alexjung** [ARM-software/ComputeLibrary#852]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v20.05 Build options: {'toolchain_prefix': 'gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-', 'arch': 'armv8a', 'opencl': '0', 'neon': '1', 'build_dir': 'build_debug', 'benchmark_tests': '0', 'validation_tests': '0', 'examples': '0', 'asserts': '1', 'debug': '1', 'extra_cxx_flags': '-fPIC', 'os': 'linux', 'Werror': '0'} Git hash=6a7771e460abeac7d401d6d38a0fcf0a0d2c3cbe

**Platform:**
Raspberry Pi 4B

**Operating System:**
Ubuntu 19.10

**Problem description:**
In `NEConvolutionLayer::configure` the parameter `num_groups` is not passed to the `NEConvolutionLayer::validate` [call in line 50](https://github.com/ARM-software/ComputeLibrary/blob/master/src/runtime/NEON/functions/NEConvolutionLayer.cpp#L50). As the default value is `num_groups=1` the error `ARM_COMPUTE_RETURN_ERROR_ON_MSG((num_groups != 1), "Grouping (num_groups != 1) is not supported on NEON");` in line [92](https://github.com/ARM-software/ComputeLibrary/blob/master/src/runtime/NEON/functions/NEConvolutionLayer.cpp#L92) will not be thrown but rather a later error `ARM_COMPUTE_RETURN_ERROR_ON(weights->dimension(idx_channel) != input->dimension(idx_channel));` in line [457](https://github.com/ARM-software/ComputeLibrary/blob/master/src/runtime/NEON/functions/NEGEMMConvolutionLayer.cpp#L457). 

I will submit a pull request referencing this issue.

**Comment by morgolock** [comment]
Hi @alexjung 

We should pass num_groups when calling validate()

Thanks for reporting this.

**Comment by morgolock** [comment]
Hi @alexjung 

Your patch has been merged to master. Thanks.
