### ISSUE TITLE
NEFullyConnectedLayer runtime slower than naive implementation

### ISSUE THREAD

**Issue by alexjung** [ARM-software/ComputeLibrary#854]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v20.05 Build options: {'toolchain_prefix': 'gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-', 'arch': 'armv8a', 'opencl': '0', 'neon': '1', 'benchmark_tests': '0', 'validation_tests': '0', 'examples': '0', 'asserts': '1', 'debug': '0', 'extra_cxx_flags': '-fPIC', 'os': 'linux', 'Werror': '0'} Git hash=6a7771e460abeac7d401d6d38a0fcf0a0d2c3cbe

**Platform:**
Raspberry Pi 4B

**Operating System:**
Ubuntu 19.10

**Problem description:**

Hello,

for our research and student projects we have written naive implementations of various CNN operations. Now I was hoping to use the ComputeLibrary to accelerate the compute intensive operations e.g. Fully-Connected by using the NEON layers of the ComputeLibrary.

Unfortunately the runtime of the networks using the NEON layers did not improve as expected compared to when only using the naive implementations (running on a Raspberry Pi 4B).

After some investigation it turned out that the Fully-Connected layer has a longer runtime compared to our simple implementation. I have isolated the operations into the following self-contained benchmark code (apart from the ComputeLibrary of course): https://gist.github.com/alexjung/604d26fe1f4747a811bc440cffb3c431

It can be cross-compiled with a simple Makefile:
```bash
CXX = aarch64-linux-gnu-g++
CXXFLAGS = -I/PATH_TO/ComputeLibrary -I/PATH_TO/ComputeLibrary/include -Wall -O2 -mcpu=cortex-a72
LDFLAGS = -L/PATH_TO/ComputeLibrary/build
LDLIBS = -larm_compute-static -larm_compute_core-static -pthread

all: fc_benchmark.cpp
	$(CXX) fc_benchmark.cpp $(CXXFLAGS) $(LDFLAGS) $(LDLIBS) -o fc_benchmark

.PHONY: clean
clean:
	rm fc_benchmark

```

When running the benchmark program with the follwing parameters on a Raspberry Pi 4B I have measured the follwing runtimes:
```bash
./fc_benachmark 5000 8000

input (1x5000) * kernel (8000x5000) = output (1x8000)
naive_fc()...
84 ms
compute_library_fc()...
1236 ms
```
Now my question is whether there is an obvious mistake in how I am using the NEON fully-connected layer?

I have also experimented with using a kernel that is already transposed by switching the kernel shape entries in line 54 of the above mentioned gist and adding the following lines to the configuration of the layer (see also the commented lines in the gist):
```c++
arm_compute::FullyConnectedLayerInfo fc_info;
fc_info.transpose_weights = false;

layer->configure(input_tensor.get(), kernel_tensor.get(), nullptr, output_tensor.get(), fc_info);
```
This reduced the measured runtime quite a bit but it is still slower than the naive implementation which doesn't use SIMD or multi-threading:
```bash
./fc_benachmark 5000 8000

input (1x5000) * kernel (8000x5000) = output (1x8000)
naive_fc()...
84 ms
compute_library_fc()...
414 ms
```
Any insight on what I am doing wrong or what the problem could be would be highly appreciated!

Best regards,  
Alexander

**Comment by morgolock** [comment]
Hi @alexjung 

I see your input is 5000x8000, is this a shape for a real use case? What network uses this input?

FC is optimised for the shapes used in popular networks, if you use a real case shape you should see ACL's FC being faster than a naive implementation.

Hope this helps.

**Comment by alexjung** [comment]
Hi @morgolock 

thanks for the reply. Those specific numbers are actually not a real use case shape but rather to get runtimes that are longer than a couple of milliseconds. I originally tried it with a LeNet model which has a 800x500 FC layer. And when I run the benchmark program with 800x500 I get the follwing runtimes:
```
./fc_benchmark 800 500
input (1x800) * kernel (500x800) = output (1x500)
naive_fc()...
1 ms
compute_library_fc()...
7 ms
```
Moreover, AlexNet actually contains a 9216x4096 and a 4096x1000 FC layer which produce the following runtimes on my setup:
```
./fc_benchmark 9216 4096
input (1x9216) * kernel (4096x9216) = output (1x4096)
naive_fc()...
80 ms
compute_library_fc()...
1060 ms

./fc_benchmark 4096 1000
input (1x4096) * kernel (1000x4096) = output (1x1000)
naive_fc()...
8 ms
compute_library_fc()...
85 ms
```
I have experimented with a couple of different shapes and the results where always similar in terms of the ratio between the two implementations.

**Comment by morgolock** [comment]
Hi @alexjung 

The problem is that normally the first iteration for ACL is very costly and your test is just benchmarking the first iteration.

If you modify your test to run more iterations you'll see ACL outperforming the naive implementation as show below:


```
root@acl_hikey_dev:~/tmp/pabtel01/graph# LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./fc_bench 2000 2000
input (1x2000) * kernel (2000x2000) = output (1x2000)
naive_fc()...
29 ms
29 ms
29 ms
29 ms
29 ms
29 ms
29 ms
29 ms
29 ms
29 ms
29 ms
29 ms
29 ms
29 ms
29 ms
29 ms
29 ms
29 ms
29 ms
29 ms
29 ms
29 ms
29 ms
29 ms
30 ms
compute_library_fc()...
38 ms
1 ms
1 ms
1 ms
1 ms
1 ms
1 ms
1 ms
1 ms
1 ms
1 ms
1 ms
1 ms
1 ms
1 ms
1 ms
1 ms
1 ms
1 ms
1 ms
1 ms
1 ms
1 ms
1 ms
1 ms
```

Hope this helps.
