### ISSUE TITLE
Precision issue with Fully Connected layer

### ISSUE THREAD

**Issue by nhkrishna** [ARM-software/ComputeLibrary#856]
Hi,

I have created the FC layer using the **NEFullyConnectedLayer** kernel in ACL 19.05 version(I will try out with the latest version and update it with you).
I have observed a precision issue with FC output. Please find the standalone setup from this [link](https://drive.google.com/drive/folders/1R1N48QkD8mX-KIysjW5DQiPdM36lFYZl?usp=sharing). 

Steps to reproduce this issue:
1. Download source file and supporting files from the above link.
2. Run the source file(onlyFc.cpp using 19.05).
3. Compare the generated output file (**fc_output.txt**) and output reference file (**fc_output_reference.txt**).

Here is the screenshot of the output difference(reference output on left and ACL output on right).
![outputDiff](https://user-images.githubusercontent.com/10693129/91046120-852a0480-e635-11ea-91c6-b15376560d97.PNG)

Because of this 'precision issue' with ACL, I have observed that incorrect output in some of the regression networks. 
Can you please let me know is this expected?

Thank you,
Hari

**Comment by nhkrishna** [comment]
Hi @morgolock,

FYI, I have tried above test setup using ACL latest version(20.08). I don't see any difference and sill observing precision problem.

-Hari

**Comment by morgolock** [comment]
Hi @nhkrishna 

>Because of this 'precision issue' with ACL, I have observed that incorrect output in some of the regression networks.

Could you please let us know which networks are producing wrong results due to the loss of precision in FCLayer?

**Comment by morgolock** [comment]
Hi @nhkrishna 

May I ask the following questions?

- What toolchain did you use to build the test and the library?
- How did you obtain the reference?

I built your test with ACL v19.02 + armv8a but that does not match your reference.

**Comment by nhkrishna** [comment]
Hi @morgolock ,

- Toolchain details:
**Command**: _strings lib/libarm_compute.so | grep 'arm_compute_version'_
**Output**: _arm_compute_version=v19.05 Build options: {'arch': 'armv7a', 'opencl': '0', 'neon': '1', 'build': 'cross_compile', 'debug': '0', 'os': 'linux'} Git hash=unknown_
**Cross compiler toolchain used:** _g++-arm-linux-gnueabihf_

- I have obtained this reference from MATLAB. 

Also, I have reran the script again and below are the precision with the ACL. 
![image](https://user-images.githubusercontent.com/10693129/114610989-272e5800-9cbe-11eb-9649-4cd260a7066a.png)

I'm validating one custom network which has bunch of Conv and FC layers. In above case, FC layer output is almost matching with reference output. But sometimes, this minor difference impacting the output of the entire regression network.

**Comment by morgolock** [comment]
Hi @nhkrishna 

Thanks for sharing this.

Would you please let us know:

- Have you computed the reference (expected) on a x86 CPU?
- Do you see the same results when building for armv8a?

**Comment by nhkrishna** [comment]
Hi @morgolock ,

Thanks for your quick response. I have computed my reference on  x64 CPU. 
I will try my test example on armv8a and let you know.

**Comment by Hari-MathWorks** [comment]
Closing this issue. It seems we will see a slight variation in the output based on the platform.
