### ISSUE TITLE
Running the graph_mnist example w/ real data

### ISSUE THREAD

**Issue by leesera** [ARM-software/ComputeLibrary#857]
I want to execute graph_mnist example w/ real data. e.g. conv2d_weights_quant_FakeQuantWithMinMaxVars.npy, /cnn_data/mnist_qasymm8_model/
But I couldn't find the link about that files.
Where could I get this data?

Thank you:)

**Comment by morgolock** [comment]
Hi @leesera 

We don't distribute the model's weights with ACL.

You should export the weights from the original model as npy files and point the graph example to the folder containing the weights. For more information on this please take a look at this: https://arm-software.github.io/ComputeLibrary/v20.08/data_import.xhtml
