### ISSUE TITLE
Core vs runtime and removing the Example class

### ISSUE THREAD

**Issue by GalMoore** [ARM-software/ComputeLibrary#858]
Hey,

I've built a CNN based on the  [neon_cnn.cpp example](https://github.com/oneapi-src/oneDNN/issues/836). I find that it is running orders of magnitude slower than the exact same network implemented in MKLDNN for Intel CPU. 

1. The MKLDNN implementation does a few things that do not exist here; like fused conv_relu (all of my conv layers are followed by ReLU) and reordering of data. Do these exist in ACL and can you point me to some code?

2. I am also curious if using the Example class might be slowing things down? I understand there is a differentiation between [core and runtime libraries](https://arm-software.github.io/ComputeLibrary/v20.05/architecture.xhtml#S4_1_1) but I haven't found any example of code running it. If I did build my network from scratch rather than using the Example what kind of speed could I expect?

I look forward to hearing from you.
Thanks,

Gal

**Comment by morgolock** [comment]
Hi @GalMoore 

1. ACL supports fused activation in the convolution layer, please look at the documentation: https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/NEON/functions/NEConvolutionLayer.h#L93
2. The example class shouldn't cause any major slowdown. You have two options: a) use the experimental graph api vs b) implement the network using the runtime functions like NEConvolutionLayer. The graph api in ACL is a thin layer on the top of the core and runtime libraries and it should not cause any slowdow.

What CPUs are you comparing? Which intel cpu vs which arm cpu?

Could you please provide an example of the network?

**Comment by GalMoore** [comment]
Hey @morgolock 

Thanks for your reply. 

1. Great! Does fused conv_relu significantly speedup inference? If so, how would I change the [neon_cnn ](https://github.com/ARM-software/ComputeLibrary/blob/master/examples/neon_cnn.cpp) example to make that happen? It could be enabled twice in this network right?
2. Thanks, that saves us the time of trying to separate the class to see if leads to performance change. Yes our network is implemented with the runtime functions - exactly like the neon_cnn example - but with few changes in params like dilation, filter size etc.. What is the experimental graph API?
3. Regarding the hardware (in both cases I'm running inference on a single core/thread and on the same input for 1,000 times):
* The x86 is: 

> 1. - Intel Xeon(R) CPU E5-2680 v3 @ 2.50GHz
> 2. - running Ubuntu 18.04

* The Aarch64 is:

> 
> 1. - ARM Taishan Kunpeng 920 2.6 GHz
> 2. - running EulerOS (similar to fedora centOS)

I wonder if the data reorder in MKLDNN (oneDNN) makes a big difference. Any thoughts?

As I mentioned, the network is very similar to neon_cnn with only few hyper parameter changes. The MKLDNN version is running orders of magnitude faster with the setup above. The ACL implementation is however similar in terms of performance to an optimized network after AutoTVM.

I look forward to hearing from you.
Thanks,

Gal

**Comment by morgolock** [comment]
Hi @GalMoore 

Could you please share the command you use to build ACL? specifically the arch option.
What version of ACL are you using? Please try with the lastest 20.08

> Does fused conv_relu significantly speedup inference? 

There is no easy answer, it depends on the underlying hardware and data types used by the network. But in general yes, you should see an improvement.

>how would I change the neon_cnn example to make that happen?

Please take a look at the API documentation, when you configure the convolution layer you should pass in a struct of the ActivationLayerInfo to enable the fusion.

> What is the experimental graph API?

The graph API in ACL is an internal tool we created to quickly prototype networks and assess their performance and validate them. It's not meant to be used in a production environment. You're not using the graph API from what you described you use the runtime's functions direactly.

Hope this helps.
