### ISSUE TITLE
NEFFT2D Aborted Core Dumped

### ISSUE THREAD

**Issue by Che-Cheng-Chang** [ARM-software/ComputeLibrary#859]
**Platform: arm64-v8a

**Operating System: Linux

** arm_compute_version=v20.08 Build options: {'embed_kernels': '1', 'gles_compute': '1', 'arch': 'arm64-v8a', 'opencl': '0', 'neon': '1', 'examples': '1', 'asserts': '1', 'debug': '0', 'os': 'linux', 'Werror': '1'} Git hash=18b685f5d09ba07aa54e050f881a0befe3e36047

**Problem description: I am going to accelerate object trackers (e.g. KCF, MOSSE, etc.) on ARM CPUs and I found that DFT is the main time-consuming part of such algorithms. Hence I used ACL to perform it.

The following is my code: I read a ppm image and transfer it to Tensor src, and the main problem is on the nefft2d.configure(&src, &dst, config2d), it seem that my config2d is not set correctly.

`
    Tensor src;
    Tensor dst;
    // Open PPM file
    PPMLoader ppm;
    Image src_img;
    Image dst_img;
    constexpr int scale_factor = 1;
    if(argc < 2) {
        // Print help
        std::cerr << "Usage: ./build/neon_cartoon_effect [input_image.ppm]\n\n";
        std::cerr << "No input_image provided\n";
        return -1;
    }
    else {
        ppm.open(argv[1]);
        ppm.init_image(src_img, Format::U8);
    }

    src_img.allocator()->allocate();
    // Fill the input image with the content of the PPM image
    ppm.fill_image(src_img);

    // TensorInfo dst_info(src.info()->dimension(0) / scale_factor, src.info()->dimension(1) / scale_factor, DataType::F32);
    const int height  = src_img.info()->dimension(0);
    const int width   = src_img.info()->dimension(1);
    std::cout << "[ Width, Height ] = " << "[" << width << ", " << height << "]" << std::endl;
    // Configure the temporary and destination images
    
    // src.allocator()->init(TensorInfo(width, height, Format::F32));
    // dst.allocator()->init(TensorInfo(width, height, Format::F32));
    
    src.allocator()->init(TensorInfo(TensorShape(width, height), 1, DataType::F32));
    dst.allocator()->init(TensorInfo(TensorShape(width, height), 2, DataType::F32));
    // src.allocator()->init(TensorShape(width, height), Format::F32,1);
    // dst.allocator()->init(TensorShape(width, height), Format::F32,2);

    // Configure for the FFT function
    NEFFT2D nefft2d;
    FFT2DInfo config2d;

    // Allocate all the images
    src.allocator()->allocate();
    dst.allocator()->allocate();

    // Fill the input tensor:
    // Simplest way: create an iterator to iterate through each element of the input tensor:
    Window input_window;
    input_window.use_tensor_dimensions(src.info()->tensor_shape());

    // Create an iterator and load the data into tensor
    Iterator input_it(&src, input_window);
    execute_window_loop(input_window, [&](const Coordinates & id)  {
        // std::cout << "Setting item [" << id.x() << "," << id.y() << "]= "<< (float)*src_img.ptr_to_element(id.y() * width + id.x()) <<"\n";
        *reinterpret_cast<float *>(input_it.ptr()) = (float)*src_img.ptr_to_element(id.y() * width + id.x());
    },
    input_it);

    // check for the data in src tensot
    // Window window;
    // window.use_tensor_dimensions(src.info()->tensor_shape());
    // Iterator it(&src, window);
    // execute_window_loop(window, [&](const Coordinates & ) {
    //     std::cout << (*reinterpret_cast<float *>(it.ptr())) << std::endl;
    // },it);

    nefft2d.configure(&src, &dst, config2d);

    // Execute the functions:
    nefft2d.run();

And the following is the error message I received: 
`
  terminate called after throwing an instance of 'std::runtime_error'
  what():  in validate src/runtime/NEON/functions/NEFFT1D.cpp:112: decomposed_vector.empty()
  Aborted (core dumped)
`

Can anyone help me point out exactly which setting is wrong and what should I revise it ?

Thanks very much.

**Comment by morgolock** [comment]
Hi @Che-Cheng-Chang 

Please move the code 

```
// Allocate all the images
src.allocator()->allocate();
dst.allocator()->allocate();

/ Fill the input tensor:
// Simplest way: create an iterator to iterate through each element of the input tensor:
Window input_window;
input_window.use_tensor_dimensions(src.info()->tensor_shape());

// Create an iterator and load the data into tensor
Iterator input_it(&src, input_window);
execute_window_loop(input_window, [&](const Coordinates & id)  {
    // std::cout << "Setting item [" << id.x() << "," << id.y() << "]= "<< (float)*src_img.ptr_to_element(id.y() * width + id.x()) <<"\n";
    *reinterpret_cast<float *>(input_it.ptr()) = (float)*src_img.ptr_to_element(id.y() * width + id.x());
},
input_it);
```

after 

`nefft2d.configure(&src, &dst, config2d);`

In general you should always call allocate() after the call to configure() because it is in this method that the padding requirements are computed.

For more information about this please refer to the documentation: https://arm-software.github.io/ComputeLibrary/v20.08/architecture.xhtml#S4_6_1_padding_and_border
