### ISSUE TITLE
How to realize the  cv::resize by computeLibrary?

### ISSUE THREAD

**Issue by Weyne168** [ARM-software/ComputeLibrary#86]
hi, in opencv resize an image we can use the cv::resize.
but, I found in compute library the resize function may not realize such function.
how can I resize an image by compute library?

**Comment by GeorgeARM** [comment]
Hello @Weyne168 ,

I think you can use the Scale (NEScale or CLScale) function to achieve what you want.

**Comment by duhuanxianzi** [comment]
223

**Comment by GeorgeARM** [comment]
@Weyne168 did Scale function meet your needs?

**Comment by GeorgeARM** [comment]
Assuming that this is resolved. Closing. Please reopen if required.
