### ISSUE TITLE
ACL toolchain support for QNX OS

### ISSUE THREAD

**Issue by gilboash** [ARM-software/ComputeLibrary#860]
Is there any references or cmake for compiling Arm Compute Lib for QNX OS, for ADAS applications 

Platform: ARM v8

Operating System: QNX (SDP 7.0/7.1)

I’m trying to compile ACL to QNX OS but couldn’t find any cmake references

**Comment by morgolock** [comment]
Hi @gilboash 

The library builds with scons and not cmake.

Please refer to the documentation on how to build it: https://arm-software.github.io/ComputeLibrary/v20.08/index.xhtml#S3_how_to_build
