### ISSUE TITLE
how to benchmark a model

### ISSUE THREAD

**Issue by bitxsw93** [ARM-software/ComputeLibrary#863]
Hello:

How to benchmark a model(such as a tflite model or a onnx model) running on Andriod device, (OpenCL). to evaluate the performance, and does ACL support benchmark each layers' costing time?

Hope ur reply, Really Thanks

**Comment by morgolock** [comment]
Hi @bitxsw93 

The best way to assess performance is to use armnn's ExecuteNetwork tool:

https://github.com/ARM-software/armnn/blob/branches/armnn_20_08/tests/ExecuteNetwork/ExecuteNetwork.cpp


If you enable the profiling option with "-e 1" the tool will generate a JSON file in which you can see how much time is taking each individual layer.

Hope this helps.
