### ISSUE TITLE
QASYMM_SIGNED support for NEDeconvolutionlayer in 20.02.1

### ISSUE THREAD

**Issue by uu-praveeng** [ARM-software/ComputeLibrary#864]
Hi,

we are trying to support the quantized deconv layer for inference . Version 20.02.1 seems does not support qasymm8_signed for deconv. Could you confirm on this.

The same is supported in 20.05.Hence wanted to confirm if  this was added as part of 20.05.

Thanks in advance,
Praveen.

**Comment by mdigiorgio** [comment]
Hi @uu-praveeng ,

Yes, QASYMM8_SIGNED in NEDeconvolutionLayer is supported since v20.05.

Thanks,
Michele

**Comment by uu-praveeng** [comment]
Thanks @mdigiorgio
