### ISSUE TITLE
Arm Compute Library help wanted 🙏 in Android

### ISSUE THREAD

**Issue by Saikatsaha1996** [ARM-software/ComputeLibrary#869]
**Platform:**
Android termux
Qualcomm Snapdragon 660 processor
64bit
6GB ram
**Operating System:**
Android 10 termux

**Problem description:**
I want help 🙏 how to install arm compute library with termux
Please guide me 🙏

**Comment by morgolock** [comment]
Hi @Saikatsaha1996 

Please take a look at the documentation: https://arm-software.github.io/ComputeLibrary/v20.11/index.xhtml#S3_3_android

Let us know if you have any problems.

Hope this helps.

**Comment by Saikatsaha1996** [comment]
> Hi @Saikatsaha1996
> 
> Please take a look at the documentation: https://arm-software.github.io/ComputeLibrary/v20.11/index.xhtml#S3_3_android
> 
> Let us know if you have any problems.
> 
> Hope this helps.

Ok I understand...
But I am not a software developer... But I have questions my mobile GPU version OpenGL ES 3.2...
And in my device already available OpenCL 2.0 ... Can I replace my GPU OpenGL ES 3.2 to OpenCL 2.0 ?..
Because ... I saw my OpenGL GPU frequency 600 MHz 
But when I run some open source software in my mobile and related with OpenCL .. in app shown my OpenCL 2.0 GPU frequency only 1 MHz... Can you explain me please please... How can I solve this problem?..

**Comment by morgolock** [comment]
Hi @Saikatsaha1996 

You have to build the library for android as described in the documentation above. Make sure the LD_LIBRARY_PATH variable points to the folder containing ACL's shared libs.

The minimum required OpenCL version is 1.2 and the GPU/Driver must also support the non uniform workgroup size extension.

Hope this helps.

**Comment by Saikatsaha1996** [comment]
> Hi @Saikatsaha1996
> 
> You have to build the library for android as described in the documentation above. Make sure the LD_LIBRARY_PATH variable points to the folder containing ACL's shared libs.
> 
> The minimum required OpenCL version is 1.2 and the GPU/Driver must also support the non uniform workgroup size extension.
> 
> Hope this helps.

Can I do it with my android phone ?

**Comment by morgolock** [comment]
Hi @Saikatsaha1996 

Yes, assuming OpenCL is fully functional on your device.

If OpenCL is not working and your device supports it, you may need to update the OS or make manual changes to enable it. For this refer to the phone's manufacturers manual, they should provide the instructions to enable OpenCL.

Hope this helps.

**Comment by Saikatsaha1996** [comment]
Can I install it via termux ?..
Gpu Adreno 650 processor sdm 865 arm64
Please reply... I want to install it via termux
