### ISSUE TITLE
undefined reference to 'std::__exception_ptr::exception_ptr::~exception_ptr()'

### ISSUE THREAD

**Issue by DevilGragon** [ARM-software/ComputeLibrary#87]
Hi,
  I have successfully generated the 32 toolchain by running the following commands:`./make-standalone-toolchain.sh --install-dir=/home/gaor/gaor/my_toolchain --toolchain=arm-linux-androideabi-4.9 --arch=arm --ndk-dir=/home/gaor/gaor/android-ndk-r11c --use-llvm --stl=gnustl` with ndk r11c because of my project. But when I try to cross compile the library on android 32bit using the following commands:`CXX=clang++ CC=clang scons Werror=1 -j8 debug=1 neon=1 opencl=0 os=android arch=armv7a`, it will get these errors:`scons: *** [build/neon_convolution] Error 1
src/runtime/CPP/CPPScheduler.cpp:92: error: undefined reference to 'std::__exception_ptr::exception_ptr::~exception_ptr()'
src/runtime/CPP/CPPScheduler.cpp:134: error: undefined reference to 'std::__exception_ptr::exception_ptr::~exception_ptr()'
src/runtime/CPP/CPPScheduler.cpp:148: error: undefined reference to 'std::current_exception()'
src/runtime/CPP/CPPScheduler.cpp:148: error: undefined reference to 'std::__exception_ptr::exception_ptr::~exception_ptr()'
src/runtime/CPP/CPPScheduler.cpp:108: error: undefined reference to 'std::__exception_ptr::exception_ptr::~exception_ptr()'
src/runtime/CPP/CPPScheduler.cpp:126: error: undefined reference to 'std::__exception_ptr::exception_ptr::exception_ptr(std::__exception_ptr::exception_ptr const&)'` and so on. I figure out that these are caused by libstdc++ and I find there are -static-libstdc++ LINKFLAGS in sconscript file, but why still get this problem?
  I try to export the generated sysroot path to my 64bit ubuntu env but still get this problem. Are there anyone meet the same problem?

**Comment by mpflanzer** [comment]
The Android toolchain is broken (not fully C++11 compatible) when used with `--stl=gnustl`. Could you try to create a toolchain that uses `--stl=libc++` instead?

For more information please see the "How to build" section in the documentation: https://arm-software.github.io/ComputeLibrary/v17.04/index.xhtml#S3_3_1_library

**Comment by DevilGragon** [comment]
Thanks for your help. 

But I have tried to use --stl=libc++ to generate android toolchain and met the same problems when building arm compute library. What's more, there are other problems such as 
`Utils.h:250: error: undefined reference to 'std::basic_ofstream<char, std::char_traits<char> >::basic_ofstream()'`,
`Utils.h:255: error: undefined reference to 'std::basic_ofstream<char, std::char_traits<char> >::open(std::string const&, std::_Ios_Openmode)'`,
`Utils.h:322: error: undefined reference to 'std::basic_ofstream<char, std::char_traits<char> >::~basic_ofstream()'` and so on occur when using --stl=libc++.

I wonder if the version of ndk must be r14 beta2? Or the generated toochain need to be set as the bin/lib path?

**Comment by mpflanzer** [comment]
Just noticed that you're using r11. Unfortunately that will not work as we require r14 (not necessarily the beta. It's just that when we wrote the documentation only the beta was available). The earlier versions have known issues and fail to compile valid code.

**Comment by DevilGragon** [comment]
Thank you. I use r14 and it works.
