### ISSUE TITLE
Got Segmentation fault after run example case

### ISSUE THREAD

**Issue by ZhangWu1140** [ARM-software/ComputeLibrary#870]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

arm_compute_version=v20.08 Build options: {'embed_kernels': '1', 'os': 'android', 'opencl': '1', 'neon': '1', 'benchmark_tests': '1', 'validation_tests': '1', 'asserts': '0', 'debug': '0', 'extra_cxx_flags': '-fPIC', 'arch': 'arm64-v8a'}

**Platform:**
arm64-v8a, G76

**Operating System:**
android

**Problem description:**
after scons  compile the compute libaray in build dir,
binary  file:
build/examples/cl_cl_sgemm
build/libarm_compute_core.so、libarm_compute_graph.so、libarm_compute.so

push these binary files into /data/local/tmp/computelibrary

and run

LD_LIBRARY_PATH=. ./cl_sgemm

I got this 
"
./cl_sgemm

Usage: 1) ./build/cl_sgemm input_matrix_1.npy input_matrix_2.npy [input_matrix_3.npy] [alpha = 1] [beta = 0]
       2) ./build/cl_sgemm M N K [alpha = 1.0f] [beta = 0.0f]

Too few or no input_matrices provided. Using M=7, N=3, K=5, alpha=1.0f and beta=0.0f

Test passed
Segmentation fault
"
and same as cl_convolution.

but when i try the tests case under build/tests/benchmark_cl_sgemm, it seems ok.

Please let me if anything i  did wrong, thank you very much!

**Comment by morgolock** [comment]
Hi @ZhangWu1140 

Could you please try again building with debug=1 and sharing the output?

Hope this helps.

**Comment by ZhangWu1140** [comment]
after enable debug=1, and Output of 'strings libarm_compute.so | grep arm_compute_version':

arm_compute_version=v20.11 Build options: {'embed_kernels': '1', 'arch': 'arm64-v8a', 'opencl': '1', 'neon': '0', 'benchmark_tests': '1', 'validation_tests': '1', 'asserts': '1', 'debug': '1', 'extra_cxx_flags': '-fPIC', 'os': 'android', 'Werror': '1'}

push cl_sgemm binary file into /data/local/tmp/computelibrary

and got the same info:

"
./cl_sgemm

Usage: 1) ./build/cl_sgemm input_matrix_1.npy input_matrix_2.npy [input_matrix_3.npy] [alpha = 1] [beta = 0]
       2) ./build/cl_sgemm M N K [alpha = 1.0f] [beta = 0.0f]

Too few or no input_matrices provided. Using M=7, N=3, K=5, alpha=1.0f and beta=0.0f


Test passed

Wait 1s
Segmentation fault
"


any suggestion  will be Thankful!

**Comment by ZhangWu1140** [comment]
Hi @morgolock
Thankyou for your reply！

after enable debug=1, and Output of 'strings libarm_compute.so | grep arm_compute_version':

arm_compute_version=v20.11 Build options: {'embed_kernels': '1', 'arch': 'arm64-v8a', 'opencl': '1', 'neon': '0', 'benchmark_tests': '1', 'validation_tests': '1', 'asserts': '1', 'debug': '1', 'extra_cxx_flags': '-fPIC', 'os': 'android', 'Werror': '1'}

push cl_sgemm binary file into /data/local/tmp/computelibrary

and got the same info:

"
./cl_sgemm

Usage: 1) ./build/cl_sgemm input_matrix_1.npy input_matrix_2.npy [input_matrix_3.npy] [alpha = 1] [beta = 0]
2) ./build/cl_sgemm M N K [alpha = 1.0f] [beta = 0.0f]

Too few or no input_matrices provided. Using M=7, N=3, K=5, alpha=1.0f and beta=0.0f

Test passed

Wait 1s
Segmentation fault
"

any suggestion will be Thankful!

**Comment by morgolock** [comment]
Hi @ZhangWu1140 

Could you please try with bigger MNK values?

Hope this helps.

**Comment by morgolock** [comment]
Hi @ZhangWu1140 

I cannot reproduce in v21.02, could you please upgrade to the latest release?

```
root@odroid:~/pablo# LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./cl_sgemm 

./cl_sgemm

Usage: 1) ./build/cl_sgemm input_matrix_1.npy input_matrix_2.npy [input_matrix_3.npy] [alpha = 1] [beta = 0]
       2) ./build/cl_sgemm M N K [alpha = 1.0f] [beta = 0.0f]

Too few or no input_matrices provided. Using M=7, N=3, K=5, alpha=1.0f and beta=0.0f

Test passed
```
