### ISSUE TITLE
OpenCL / OpenGL deprecation

### ISSUE THREAD

**Issue by AlexanderSerov** [ARM-software/ComputeLibrary#871]
Entire [list of functions](https://arm-software.github.io/ComputeLibrary/latest/functions_list.xhtml) implementing ML layers using OpenCL / OpenGL is deprecated. I interested in reasons for that.

**Comment by GeorgeARM** [comment]
Hello @AlexanderSerov,

We are not deprecating the ML layers for OpenCL.
Our deprecation plan is to deprecate the Computer Vision related functions along with the OpenGL backend completely.
Ultimate goal is to focus our efforts into improving the Machine Learning primitives for CPU and OpenCL.

Hope this helps,
George
