### ISSUE TITLE
Support QSYMM8 in ComputeLibrary's examples.

### ISSUE THREAD

**Issue by allnes** [ARM-software/ComputeLibrary#872]
Hello!

In your [examples](https://github.com/ARM-software/ComputeLibrary/tree/master/examples) I found QSYMM8 data type for quantized models. But in your examples there are no references to the pre-trained models which support this type. 

I tried to find and substitute models provided by, for example, [tensorflow](https://www.tensorflow.org/lite/guide/hosted_models). But everything collapses at the stage of converting stacks to your graph format (using the presented scripts), or after running the examples it says that models are not supported.

So my question is, how can I run your examples with quantized models?

Thank you :)

**Comment by morgolock** [comment]
Hi @allnes 

I'd suggest running the models through ArmNN's ExecuteNetwork test: https://github.com/ARM-software/armnn/tree/branches/armnn_20_11/tests/ExecuteNetwork

ExcuteNetwork supports different input formats for the models and will run the workloads through ACL.

The graph api in ACL is experimental and support for things like you described is limited.

Hope this helps.

**Comment by allnes** [comment]
@morgolock thank you!
