### ISSUE TITLE
incorrect output from NEDeconvolutionLayer

### ISSUE THREAD

**Issue by pranathibl** [ARM-software/ComputeLibrary#873]
HI,

I am seeing incorrect results for NEDeconvolutionLayer with asymmetric padding size. I have attached the setup with expected output below.

ACL Version used: v20.02.1
[transposed_standalone.zip](https://github.com/ARM-software/ComputeLibrary/files/5853826/transposed_standalone.zip)

**Comment by morgolock** [comment]
Hi @pranathibl 

I think there might be a problem with your functions:

```
void fillBufferToTensor(float* input_data, arm_compute::ITensor& inputTensor) {
void fillTensorToBuffer(float* output_data, arm_compute::ITensor& outputTensor) {
```

Could you please take a look at this https://github.com/ARM-software/ComputeLibrary/issues/770#issuecomment-551030169 and make changes to those functions according to the information explained in that post?

Essentially when you copy your tensors you should use the strides:
`*reinterpret_cast<float *>(input_it.ptr()) = src_data[id.z() * (width * height) + id.y() * width + id.x()];`

**Comment by nhkrishna** [comment]
Hi @morgolock,

I have changed the fillTensorToBuffer and fillBufferToTensor, still i'm seeing numerical mismatch.  Also, In my script i'm using count variable to traverse through the un padded area in output ARM Tensor and copying into the output buffer. We have already discussed about count variable based approach in https://github.com/ARM-software/ComputeLibrary/issues/711 to copy ARM Tensor data to the raw buffer.
Moreover there is no padding to the output arm tensor. I have verified by using has_padding() method on output ARM Tensor. 

It seems like there is an issue with cropping the padded dimensions input.
Also, I have tried passing padded values as zeros and NEDeconvLayer and used NESlice operation to  crop the output of NEDeconvLayer by actual padded dimensions. Then its output matching with the reference output.

Could you take a look into this? Let me know if you face any issues while reproducing this problem.

Thanks,
Hari

**Comment by morgolock** [comment]
Hi @nhkrishna 

I'd advice you always call the validate() method before running configure() and certainly before run().

In this particular case if you call validate() you will notice that this configuration is not supported, that's the reason why run() is generating mismatches.

If validate() tells the configuration is not supported, run() should not be executed as the results will be undefined.

In order to see this you should build with debug=1 and add these lines before the call to configure

```
271     const auto s = NEDeconvolutionLayer::validate(src.info(), m_deConvLayerWgtTensor.info(), m_deConvLayerBiasTensor.info(), out_deConv0.info(),psinfo);
272     std::cout << " validate " << (bool)s << std::endl;
```

Then if you run the test you will get

```
root@odroid:~/pablo# LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./transposedConv_standalone_exe 
 validate 0
terminate called after throwing an instance of 'std::runtime_error'
  what():  in validate src/runtime/NEON/functions/NEGEMMConvolutionLayer.cpp:510: biases->dimension(0) != weights->dimension(idx_kernels)
Aborted
```

Hope this helps.

**Comment by Hari-MathWorks** [comment]
Hi @morgolock ,

Thanks for your suggestion. 
As a workaround, I have performed the NEDeconvolution layer with default padding dimensions. On top of the NEDeconvolution output, I'm using NESlice operation with input asymmetric dimensions. This was giving correct results.

Also, Do you have any plans to support NEDeconvolution with asymmetric padding dimensions?

Thanks,
Hari

**Comment by morgolock** [comment]
HI @Hari-MathWorks 

Good to hear you got it working.

We have no plans to add support for asymmetric padding in NEDeconvolution. We support Android nnapi use cases.

Would you please let us know if this particular configuration is a standalone test you have written or if it comes from a well-known model?

**Comment by Hari-MathWorks** [comment]
Hi @morgolock ,

We had a custom classification network provided by the customer. Basically, it uses a transposedConv2D layer with asymmetric padding dimensions.
