### ISSUE TITLE
Capsule Layer

### ISSUE THREAD

**Issue by krgor** [ARM-software/ComputeLibrary#874]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
strings /data/libs/bkup/libarm_compute.so | grep arm_compute_version           <
arm_compute_version=v20.02 Build options: {'embed_kernels': '1', 'gles_compute': '1', 'logging': '1', 'arch': 'arm64-v8a', 'opencl': '1', 'neon': '1', 'asserts': '1', 'debug': '1', 'os': 'android', 'Werror': '1'} Git hash=36ccc90158c65844b3c53c5462c6d7d852b97278
arm_compute_version.embed

**Platform:**
Firefly Board

**Operating System:**
Android 8.1

**Problem description:**
I am working on to port FSA-NET on ACL and it has requirement to use CapsuleLayer (which quite similar to dense layers). The complete project is provided here: https://github.com/shamangary/FSA-Net.git

I need to have Capsule layer defined at https://github.com/shamangary/FSA-Net/blob/master/lib/capsulelayers.py#L133

For now I don't see any such implementation done in ACL. Can you please help if there is any way to implement this by some graph layer? Does ARM have any plan to provide support for such Capsule layer?

**Comment by morgolock** [comment]
Hi @krgor 

ACL does not implement the Capsule layer.

Are these the models you would like to run: https://github.com/shamangary/FSA-Net/tree/master/pre-trained/converted-models/tf  ? If so I think you could try to run them via armnn's ExecuteNetwork tool: https://github.com/ARM-software/armnn/tree/branches/armnn_21_02/tests/ExecuteNetwork

Hope this helps.
