### ISSUE TITLE
error building ARM_COMPUTE library: 'COMPILER: aarch64-linux-gnu-aarch64-linux-gnu-g++' not found

### ISSUE THREAD

**Issue by suyash-narain** [ARM-software/ComputeLibrary#876]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute version cloned: 20.11
**Platform:**
crosscompiling for arm64 on x86 linux machine
**Operating System:**
Ubuntu

**Problem description:**
While crosscompiling for linux arm64 board Ubuntu 18.04 laptop,
during building  ARM_COMPUTE library, using the following steps:
**$git clone https://github.com/ARM-software/ComputeLibrary.git
$cd ComputeLibrary/
$scons arch=arm64-v8a neon=1 opencl=1 embed_kernels=1 extra_cxx_flags="-fPIC" -j8 internal_only=0**

I get the following error
**scons: Reading SConscript files ...
ERROR: Compiler ' aarch64-linux-gnu-aarch64-linux-gnu-g++' not found**

after getting this error, 
i did set the path to export $PATH=/usr/lib/aarch64-linux-gnu-g++, as thats where this library is located. But there is no file called aarch64-linux-gnu-aarch64-linux-gnu-g++. 
what am i missing?

**Comment by morgolock** [comment]
Hi @suyash-narain 

There seems to be some problem with the path to the compiler. Please try the command below replacing PATH_TO_YOUR_TOOLCHAIN for the absolute path to your toolchain.

Please try the 
```PATH=$PATH:PATH_TO_YOUR_TOOLCHAIN/bin/  scons arch=arm64-v8a neon=1 opencl=1 embed_kernels=1 extra_cxx_flags="-fPIC" -j8 internal_only=0```

**Comment by morgolock** [comment]
Closing, please reopen if you need assistance.
