### ISSUE TITLE
Int8 optimization support

### ISSUE THREAD

**Issue by allnes** [ARM-software/ComputeLibrary#877]
Hello, this issue [https://github.com/ARM-software/armnn/issues/511](https://github.com/ARM-software/armnn/issues/511)  with armnn developers discussed the performance loss of int8 models vs fp32 models. Please tell me, where is it possible to find out the state of optimized cores for int8 models on armv7 and armv8 architectures?

**Comment by morgolock** [comment]
Hi @allnes 

Could you please provide more context for your query?

What model are we talking about?

You need the presence of the dot product instruction to speed up int8 models, this instruction is only available in armv8-2a.

**Comment by morgolock** [comment]
Hi @allnes 

Please take a look at https://github.com/ARM-software/ComputeLibrary/tree/master/src/core/NEON/kernels/arm_gemm/kernels

That folder contains all the optimised kernels written in assembly for the various architectures. The int8 assembly kernels are only available for aarch64 armv8a.

For armv7a you will fallback to a generic implementation in intrinsics: https://github.com/ARM-software/ComputeLibrary/blob/master/src/core/NEON/kernels/NEGEMMLowpMatrixMultiplyKernel.cpp

**Comment by allnes** [comment]
@morgolock thank you!
