### ISSUE TITLE
Build failed on trunk on Ubuntu 20.04

### ISSUE THREAD

**Issue by ek9852** [ARM-software/ComputeLibrary#884]
Platform Ubuntu 20.04
Host: (install arm 64 bits cross-compiler tools )
 sudo apt-get install -y g++-aarch64-linux-gnu libgcc-9-dev-arm64-cross build-essential scons git
 
 git clone https://review.mlplatform.org/ml/ComputeLibrary
 cd ComputeLibrary
 scons arch=armv8
 
 Got:
 
 `aarch64-linux-gnu-g++ -o build/src/runtime/CL/CLPyramid.o -c -Wall -DARCH_ARM -Wextra -pedantic -Wdisabled-optimization -Wformat=2 -Winit-self -Wstrict-overflow=2 -Wswitch-default -std=c++14 -Woverloaded-virtual -Wformat-security -Wctor-dtor-privacy -Wsign-promo -Weffc++ -Wno-overlength-strings -Wlogical-op -Wnoexcept -Wstrict-null-sentinel -C -march=armv8-a -Wno-ignored-attributes -DENABLE_FP16_KERNELS -DENABLE_FP32_KERNELS -DENABLE_QASYMM8_KERNELS -DENABLE_QASYMM8_SIGNED_KERNELS -DENABLE_QSYMM16_KERNELS -DENABLE_INTEGER_KERNELS -DENABLE_NHWC_KERNELS -DENABLE_NCHW_KERNELS -Werror -O3 -D_GLIBCXX_USE_NANOSLEEP -DARM_COMPUTE_CPP_SCHEDULER=1 -DARM_COMPUTE_OPENCL_ENABLED -DEMBEDDED_KERNELS -DARM_COMPUTE_VERSION_MAJOR=22 -DARM_COMPUTE_VERSION_MINOR=0 -DARM_COMPUTE_VERSION_PATCH=0 -Iinclude -I. -Ibuild/build/src/core/CL -Ibuild/src/core/CL -Ibuild/build/src/core -Ibuild/src/core src/runtime/CL/CLPyramid.cpp
aarch64-linux-gnu-g++ -o build/src/runtime/CL/CLRuntimeContext.o -c -Wall -DARCH_ARM -Wextra -pedantic -Wdisabled-optimization -Wformat=2 -Winit-self -Wstrict-overflow=2 -Wswitch-default -std=c++14 -Woverloaded-virtual -Wformat-security -Wctor-dtor-privacy -Wsign-promo -Weffc++ -Wno-overlength-strings -Wlogical-op -Wnoexcept -Wstrict-null-sentinel -C -march=armv8-a -Wno-ignored-attributes -DENABLE_FP16_KERNELS -DENABLE_FP32_KERNELS -DENABLE_QASYMM8_KERNELS -DENABLE_QASYMM8_SIGNED_KERNELS -DENABLE_QSYMM16_KERNELS -DENABLE_INTEGER_KERNELS -DENABLE_NHWC_KERNELS -DENABLE_NCHW_KERNELS -Werror -O3 -D_GLIBCXX_USE_NANOSLEEP -DARM_COMPUTE_CPP_SCHEDULER=1 -DARM_COMPUTE_OPENCL_ENABLED -DEMBEDDED_KERNELS -DARM_COMPUTE_VERSION_MAJOR=22 -DARM_COMPUTE_VERSION_MINOR=0 -DARM_COMPUTE_VERSION_PATCH=0 -Iinclude -I. -Ibuild/build/src/core/CL -Ibuild/src/core/CL -Ibuild/build/src/core -Ibuild/src/core src/runtime/CL/CLRuntimeContext.cpp
In file included from ./src/cpu/CpuContext.h:28,
                 from src/cpu/CpuContext.cpp:24:
./src/common/IContext.h: In constructor ‘arm_compute::IContext::IContext(arm_compute::Target)’:
./src/common/IContext.h:49:54: error: noexcept-expression evaluates to ‘false’ because of a call to ‘arm_compute::detail::Header::Header(arm_compute::detail::ObjectType, arm_compute::IContext*)’ [-Werror=noexcept]
   49 |         : AclContext_(), _target(target), _refcount(0)
      |                                                      ^
In file included from ./src/common/IContext.h:29,
                 from ./src/cpu/CpuContext.h:28,
                 from src/cpu/CpuContext.cpp:24:
./src/common/utils/Object.h:55:5: error: but ‘arm_compute::detail::Header::Header(arm_compute::detail::ObjectType, arm_compute::IContext*)’ does not throw; perhaps it should be declared ‘noexcept’ [-Werror=noexcept]
   55 |     Header(ObjectType type_, IContext *ctx_)
      |     ^~~~~~
aarch64-linux-gnu-g++ -o build/src/runtime/CL/CLScheduler.o -c -Wall -DARCH_ARM -Wextra -pedantic -Wdisabled-optimization -Wformat=2 -Winit-self -Wstrict-overflow=2 -Wswitch-default -std=c++14 -Woverloaded-virtual -Wformat-security -Wctor-dtor-privacy -Wsign-promo -Weffc++ -Wno-overlength-strings -Wlogical-op -Wnoexcept -Wstrict-null-sentinel -C -march=armv8-a -Wno-ignored-attributes -DENABLE_FP16_KERNELS -DENABLE_FP32_KERNELS -DENABLE_QASYMM8_KERNELS -DENABLE_QASYMM8_SIGNED_KERNELS -DENABLE_QSYMM16_KERNELS -DENABLE_INTEGER_KERNELS -DENABLE_NHWC_KERNELS -DENABLE_NCHW_KERNELS -Werror -O3 -D_GLIBCXX_USE_NANOSLEEP -DARM_COMPUTE_CPP_SCHEDULER=1 -DARM_COMPUTE_OPENCL_ENABLED -DEMBEDDED_KERNELS -DARM_COMPUTE_VERSION_MAJOR=22 -DARM_COMPUTE_VERSION_MINOR=0 -DARM_COMPUTE_VERSION_PATCH=0 -Iinclude -I. -Ibuild/build/src/core/CL -Ibuild/src/core/CL -Ibuild/build/src/core -Ibuild/src/core src/runtime/CL/CLScheduler.cpp
cc1plus: all warnings being treated as errors
scons: *** [build/src/cpu/CpuContext.o] Error 1
cc1plus: all warnings being treated as errors
scons: *** [build/src/c/AclContext.o] Error 1
scons: building terminated because of errors.`

**Comment by ek9852** [comment]
Setting  Werror=0  will works, but wonder what's wrong with the code that trigger the error.

**Comment by morgolock** [comment]
Hi @ek9852 

Could you please share the output of the following commands:
```
morg@stoic-box:/mnt/sdb2/ComputeLibrary$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

```
morg@stoic-box:/mnt/sdb2/ComputeLibrary$ aarch64-linux-gnu-g++ -v
Using built-in specs.
COLLECT_GCC=aarch64-linux-gnu-g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc-cross/aarch64-linux-gnu/9/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --without-target-system-zlib --enable-libpth-m2 --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=aarch64-linux-gnu --program-prefix=aarch64-linux-gnu- --includedir=/usr/aarch64-linux-gnu/include
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 
```

**Comment by morgolock** [comment]
Hi @ek9852 

Please cherry pick this patch  https://review.mlplatform.org/c/ml/ComputeLibrary/+/5281

I built the library from the latest code in master using gcc-9.3 after applying this patch

**Comment by ek9852** [comment]
@morgolock  Still failing, but better. Did u compile with neon=1 ?
 scons  arch=armv8a neon=1 

src/runtime/NEON/functions/NEGEMMConvolutionLayer.cpp: In constructor ‘arm_compute::NEGEMMConvolutionLayer::NEGEMMConvolutionLayer(const std::shared_ptr<arm_compute::IMemoryManager>&, arm_compute::IWeightsManager*)’:
src/runtime/NEON/functions/NEGEMMConvolutionLayer.cpp:113:121: error: noexcept-expression evaluates to ‘false’ because of a call to ‘arm_compute::NEConvolutionLayerReshapeWeights::NEConvolutionLayerReshapeWeights()’ [-Werror=noexcept]
  113 |       _data_layout(DataLayout::NCHW), _skip_im2col(false), _skip_col2im(false), _is_quantized(false), _is_prepared(false)
      |                                                                                                                         ^
src/runtime/NEON/functions/NEGEMMConvolutionLayer.cpp:55:1: error: but ‘arm_compute::NEConvolutionLayerReshapeWeights::NEConvolutionLayerReshapeWeights()’ does not throw; perhaps it should be declared ‘noexcept’ [-Werror=noexcept]
   55 | NEConvolutionLayerReshapeWeights::NEConvolutionLayerReshapeWeights()
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by morgolock** [comment]
Hi @ek9852 

Please try again with the latest revision of the patch. I've built the library with neon=1 and opencl=1

Hope this helps.

**Comment by ek9852** [comment]
@morgolock Still failing: patchset 2 applied already.
There are still places need to add the noexcept keyword.

/usr/aarch64-linux-gnu/include/c++/9/bits/unique_ptr.h: In instantiation of ‘typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = arm_compute::cpu::kernels::CpuPoolingKernel; _Args = {}; typename std::_MakeUniq<_Tp>::__single_object = std::unique_ptr<arm_compute::cpu::kernels::CpuPoolingKernel, std::default_delete<arm_compute::cpu::kernels::CpuPoolingKernel> >]’:
src/runtime/cpu/operators/CpuPooling.cpp:63:62:   required from here
./arm_compute/core/Types.h:285:24: error: but ‘constexpr arm_compute::BorderSize::BorderSize(unsigned int)’ does not throw; perhaps it should be declared ‘noexcept’ [-Werror=noexcept]
  285 |     explicit constexpr BorderSize(unsigned int size)
      |                        ^~~~~~~~~~

**Comment by morgolock** [comment]
Hi @ek9852 

Patchset 3 should solve the remaining errors.

Hope this helps.

**Comment by ek9852** [comment]
@morgolock Patchset 3  works. Thank you very much.
