### ISSUE TITLE
Build error on warning

### ISSUE THREAD

**Issue by ek9852** [ARM-software/ComputeLibrary#885]
https://github.com/ARM-software/ComputeLibrary/blob/master/src/core/NEON/kernels/arm_conv/pooling/kernels/a64_s8_nhwc_avg_generic_depthfirst/generic.cpp#L87

rescale_value is of type in32_t so even it is cast to int64_t , it will never be equal to 1ll<<31

src/core/NEON/kernels/arm_conv/pooling/kernels/a64_s8_nhwc_avg_generic_depthfirst/generic.cpp: In function ‘void arm_conv::pooling::a64_s8_nhwc_avg_generic_depthfirst_impl(uint64_t, uint64_t, uint64_t, const int8_t* const*, int8_t*)’:
src/core/NEON/kernels/arm_conv/pooling/kernels/a64_s8_nhwc_avg_generic_depthfirst/generic.cpp:88:45: error: comparison is always false due to limited range of data type [-Werror=type-limits]
     if (static_cast<int64_t>(rescale_value) == (1ll << 31))
                                             ^
cc1plus: all warnings being treated as errors
scons: *** [build/src/core/NEON/kernels/arm_conv/pooling/kernels/a64_s8_nhwc_avg_generic_depthfirst/generic.o] Error 1

**Comment by morgolock** [comment]
Hi @ek9852 

Would you please share the output of `aarch64-linux-gnu-g++ -v` and the build command you use to compile the library?

**Comment by ek9852** [comment]
@morgolock  I just use this ARM provided dockerfile 
https://github.com/ARM-software/armnn/blob/branches/armnn_21_02/docker/x86_64/Dockerfile#L147
But as I said, it is cleanly     if (static_cast<int64_t>(rescale_value) == (1ll << 31)) will always false 
since rescale_value is of type int32_t.

**Comment by morgolock** [comment]
Hi @ek9852 

This patch fixes the problem: https://review.mlplatform.org/c/ml/ComputeLibrary/+/5741

Thanks for reporting this.
