### ISSUE TITLE
TransposeConvolution2d error

### ISSUE THREAD

**Issue by ek9852** [ARM-software/ComputeLibrary#886]
trunk

Related to https://github.com/ARM-software/armnn/issues/520

NEON:
 TransposeConvolution2d is not supported on requested backend CpuAcc for input data type QAsymmS8 and output data type QAsymmS8 (reason: in validate src/runtime/NEON/functions/NEDeconvolutionLayer.cpp:88: Tensors have different data types), falling back to the next backend.
Warning: ERROR: Layer of type TransposeConvolution2d is not supported on any preferred backend [CpuAcc ]

CL:
 TransposeConvolution2d is not supported on requested backend GpuAcc for input data type QAsymmS8 and output data type QAsymmS8 (reason: in validate src/runtime/CL/functions/CLDirectDeconvolutionLayer.cpp:77: Tensors have different data types), falling back to the next backend.

**Comment by morgolock** [comment]
Hi @ek9852 

The following patches solve the problem:

https://review.mlplatform.org/c/ml/ComputeLibrary/+/5364
https://review.mlplatform.org/c/ml/ComputeLibrary/+/5484

Hope this helps.
