### ISSUE TITLE
Arm compute library Neon LK cost more time then openCV lk

### ISSUE THREAD

**Issue by ccion** [ARM-software/ComputeLibrary#889]
Hi, I am  doing the LK time test of openCV and arm compute library Neon, that found the LK time consumption of arm compute neon is greater, what's wrong for me?

**Output of 'strings libarm_compute.so | grep arm_compute_version':**arm_compute_version=v21.02 Build options: {'os': 'linux', 'opencl': '0', 'neon': '1', 'asserts': '0', 'debug': '0', 'arch': 'arm64-v8a', 'Werror': '0'} Git hash=7dcb9fadb98cad05fca72de3273311d570d98b4e

**Platform:**ambera-cv25 , quad-core Arm cortex A53

**Operating System:** linux

this is my code
#include <iostream>
#include <ctype.h>
#include <sys/time.h>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iostream>
#include <memory>
#include <random>
#include <string>
#include <tuple>
#include <vector>
/*opencv include*/
#include "opencv2/video/tracking.hpp"
#include "opencv2/imgproc.hpp"
#include "opencv2/videoio.hpp"
#include "opencv2/highgui.hpp"
/*arm compute include*/
#include "arm_compute/runtime/NEON/NEFunctions.h"
#include "arm_compute/core/Helpers.h"
#include "arm_compute/core/ITensor.h"
#include "arm_compute/core/Types.h"
#include "arm_compute/core/Window.h"
#include "arm_compute/runtime/Tensor.h"
#include "Utils.h"

using namespace cv;
using namespace std;
using namespace arm_compute;

#define GETTIME(time)                                  \
{                                                      \
    struct timeval lTime;                              \
    gettimeofday(&lTime, 0);                           \
    *time = (lTime.tv_sec * 1000000 + lTime.tv_usec);  \
}

void help(char** argv)
{
    cout << "Call:" << argv[0] << "[image1] [image2]" << endl;
    cout << "Demonstrates Pyramid Lucas-Kanade optical flow." << endl;
}

int main( int argc, char** argv )
{
    if(argc != 3){
        help(argv);
        exit(1);
    }
    long  start_time1,end_time1;
    long  start_time2,end_time2;
    long  start_time3,end_time3;
    long  start_time4,end_time4;

    /*arm computer library*/
    Pyramid               pyr_1st{};
    Pyramid               pyr_2nd{};
    NEGaussianPyramidHalf pyrf_1st{};
    NEGaussianPyramidHalf pyrf_2nd{};
    NEOpticalFlow         optkf{};
    Image                 src_1st{}, src_2nd{};
    KeyPointArray         input_points(1000);
    KeyPointArray         output_points(1000);
    KeyPointArray         point_estimates(1000);

    /*Initialize, load two images from the file system, and
      allocate the images and others structures we will need 
      for results*/
    cv::Mat imgA = cv::imread(argv[1], CV_LOAD_IMAGE_GRAYSCALE);
    cv::Mat imgB = cv::imread(argv[2], CV_LOAD_IMAGE_GRAYSCALE);
    int win_size = 10;
    cv::Mat  imgC = cv::imread(argv[2], CV_LOAD_IMAGE_UNCHANGED);
    /*opencv read image  transfer to opticalFlow*/
    /*src_1st image data*/
    printf("imgA.cols:%d -- imgA.rows:%d\n",imgA.cols, imgA.rows);
    src_1st.allocator()->init(TensorInfo(imgA.cols,imgA.rows, Format::U8));
    src_1st.allocator()->allocate();
    memcpy(src_1st.buffer(), imgA.ptr(), imgA.cols * imgA.rows);
    save_to_ppm(src_1st,"1st.ppm");
    /*src_2st image data*/
    printf("imgB.cols:%d -- imgB.rows:%d\n",imgB.cols, imgB.rows);
    src_2nd.allocator()->init(TensorInfo(imgB.cols,imgB.rows, Format::U8));
    src_2nd.allocator()->allocate();
    memcpy(src_2nd.buffer(), imgB.ptr(), imgB.cols * imgB.rows);
    save_to_ppm(src_2nd,"2nd.ppm");

    vector<cv::Point2f> cornersA, cornersB;
    const  int MAX_CORNERS = 500;
    static int seq_num = 0;
    printf("######## %d ########\n",seq_num++);
    //good features track
    GETTIME(&start_time1);
    cv::goodFeaturesToTrack(imgA, cornersA, MAX_CORNERS, 0.01, 5, cv::noArray(), 3, false, 0.04);
    GETTIME(&end_time1);
    printf("goodFeaturesToTrack time:%ldus\n",end_time1 - start_time1);

    //cornersubpix
    GETTIME(&start_time2);
    cv::cornerSubPix(imgA, cornersA, cv::Size(win_size, win_size), cv::Size(-1, -1), cv::TermCriteria(cv::TermCriteria::MAX_ITER|cv::TermCriteria::EPS,20,0.03));
    GETTIME(&end_time2);
    printf("cornerSubPix time:%ldus\n",end_time2 - start_time2);

    input_points.clear();
    input_points.resize(cornersA.size());
    point_estimates.resize(cornersA.size());
    printf("cornersA.size:%ld -- input_points.size:%ld -- point_estimates.size:%ld\n",cornersA.size(),input_points.num_values(),point_estimates.num_values());
    /*tracking points point_estimate*/
    for(size_t k = 0; k < cornersA.size(); k++){
        auto &keypoint1           = input_points.at(k);
        auto &keypoint2           = point_estimates.at(k);
        keypoint1.x = keypoint2.x = cornersA.at(k).x;
        keypoint1.y = keypoint2.y = cornersA.at(k).y;
        keypoint1.tracking_status = keypoint2.tracking_status = 1;
    }
    

    //call the Lucas Kanade algorithm for neon LK
    const unsigned int num_levels = 5;
    // Initialise and allocate pyramids
    PyramidInfo pyramid_info(num_levels, SCALE_PYRAMID_HALF, src_1st.info()->tensor_shape(), src_1st.info()->format());
    pyr_1st.init_auto_padding(pyramid_info);
    pyr_2nd.init_auto_padding(pyramid_info);

    pyrf_1st.configure(&src_1st, &pyr_1st, BorderMode::UNDEFINED, 0);
    pyrf_2nd.configure(&src_2nd, &pyr_2nd, BorderMode::UNDEFINED, 0);
    output_points.resize(input_points.num_values());
    optkf.configure(&pyr_1st, &pyr_2nd,
                        &input_points, &point_estimates, &output_points,
                        Termination::TERM_CRITERIA_BOTH, 0.03f, 20, 21, true, BorderMode::UNDEFINED, 0);
    pyr_1st.allocate();
    pyr_2nd.allocate();
    //Execute the functions:
    GETTIME(&start_time4);
    pyrf_1st.run();
    pyrf_2nd.run();
    optkf.run();
    GETTIME(&end_time4);
    printf("neon lk time:%ldus\n",end_time4 - start_time4);

    //call the Lucas Kanade algorithm for opencv
    vector<uchar> features_found;
    GETTIME(&start_time3);
    cv::calcOpticalFlowPyrLK(imgA,imgB,cornersA,cornersB,features_found,noArray(),cv::Size(win_size*2+1,win_size*2+1),5,cv::TermCriteria(cv::TermCriteria::MAX_ITER|cv::TermCriteria::EPS,20,0.3));
    GETTIME(&end_time3);
    printf("calcOpticalFlowPyrLK time:%ldus\n", end_time3 - start_time3);
    //Now make some image of what we are looking at:
    //Note that if you want to track cornersB further,i.e.
    //pass them as input to the next calcOpticalFlowPyrLK,
    //you would need to "compress" the vector, i.e.,exclude points for which
    //features_found[i] == false.

    for(int i = 0; i < (int)cornersA.size(); i++){
        if(!features_found[i]){
            continue;
        }
        line(imgC, cornersA[i], cornersB[i], Scalar(0, 255, 0), 2, cv::LINE_AA);
    }
    for(int i = 0; i < (int)output_points.num_values();i++){
        auto kp = output_points.at(i);
        if(!kp.tracking_status){
            continue;
        }
        cv::Point2f tmp;
        tmp.x = kp.x;
        tmp.y = kp.y;
        line(imgC,cornersA[i],tmp,Scalar(0, 0, 255), 2, cv::LINE_AA);
    }

    cv::imwrite("imageA.jpg",imgA);
    cv::imwrite("imageB.jpg",imgB);
    cv::imwrite("LK.jpg",imgC);

    return 0;
}

**Problem description:**
time test:
------1---------------
neon lk time:96067us
calcOpticalFlowPyrLK time:80311us
-----2-----------
neon lk time:95831us
calcOpticalFlowPyrLK time:76680us
--------3-------------
neon lk time:92570us
calcOpticalFlowPyrLK time:76689us
------4-------------------
neon lk time:92144us
calcOpticalFlowPyrLK time:76556us
-------5------------------
neon lk time:104801us
calcOpticalFlowPyrLK time:76688us
-------6----------------
neon lk time:92297us
calcOpticalFlowPyrLK time:76713us

------7--------------
neon lk time:94929us
calcOpticalFlowPyrLK time:76667us

**Comment by morgolock** [comment]
Hi @ccion 

Please note that all computer vision functions in ACL have been deprecated and will be removed in 21.05. 

Please see the deprecation notice in 20.11:
https://github.com/ARM-software/ComputeLibrary/blob/master/docs/00_introduction.dox#L361
https://github.com/ARM-software/ComputeLibrary/blob/master/docs/00_introduction.dox#L395

ACL main optimisation efforts are focused on ML functions and we have not been actively working on CV functions. I'd suggest you use OpenCV if that works better for you.

**Comment by ccion** [comment]
Thank you @morgolock 
             What you mean that ACL's optical flow(LK) function may not be optimized by the optical flow(LK) function in openCV? in the Arm A53?

**Comment by morgolock** [comment]
Hi @ccion 

I meant that the optimisation efforts in ACL are focused on machine learning functions like convolution layer and not in vision functions. We have not been actively working on functions like optical flow for a while and these functions have been deprecated and will be removed from the library in the next release 21.05.

Hope this helps.

**Comment by ccion** [comment]
Thank you@morgolock
   Get it.
