### ISSUE TITLE
Looking for suggestions for benchmarking

### ISSUE THREAD

**Issue by kindloaf** [ARM-software/ComputeLibrary#89]
Hi,
I'm trying to run the CLConvolutionLayer a few times to test the run time on a Mali GPU.
The first time I ran it, I initialized the convolution layer once, fixed the input, and ran it over and over.  I got some average number of milliseconds per run.
The second time I ran it, I changed the input each time when I call CLConvolutionLayer::run. Now the average milliseconds per run tripled (I didn't include the time to randomize though).

Why is this happening? Is there a caching effect?
By the way, I changed the input by using a Window and Iterator:
```
    iTensor.map();

    Window iWindow;
    iWindow.use_tensor_dimensions(iTensor.info());
    Iterator iIt(&iTensor, iWindow);

    execute_window_loop(iWindow, [&](const Coordinates &id){
        float val = rand() / RAND_MAX;
        *reinterpret_cast<float *>(iIt.ptr()) = val;
    }, iIt);

    iTensor.unmap();
```

**Comment by kindloaf** [comment]
Another observation:
When I randomly change the input, if I just change one number, the run time is increased by about 50%.
If I change 1% of the input numbers, the run time is increased by 200%

**Comment by AnthonyARM** [comment]
Yes, it's likely to be related to cache maintenance: the cache maintenance associated to the unmap is usually deferred to the first kernel execution.

Also, most platforms' CPU governors don't kick in for cache maintenance which means it's usually performed at a low frequency and possibly on a small core.
Try to set your CPUs to performance mode or execute a kernel which uses the buffer you just filled before you start the timer (Just to double check it's the cache maintenance overhead)

**Comment by kindloaf** [comment]
Thanks for the info!
