### ISSUE TITLE
Ask the bare metal how to use ACL

### ISSUE THREAD

**Issue by Derekduke** [ARM-software/ComputeLibrary#891]
Hello, I hope to use ACL to accelerate the model on cortex-a7 running rtos. I have seen some examples in the code repository. Can these examples run in a bare metal environment? Or which examples are recommended to run as tests?

**Comment by mpekatsoula** [comment]
Hi @Derekduke 

You can build ACL for bare metal alognside with all the examples. A sample build command is the following:
`scons  arch=arm64-v8a os=bare_metal build_dir=bm -j52 Werror=1 opencl=0 neon=1 debug=0 asserts=1 standalone=1 embed_kernels=1 benchmark_tests=0 validation_tests=1 examples=1 openmp=0 cppthreads=0 logging=0`

The above will build the validation tests and examples. If you need some special bootcode to be included in your final binary, create a folder called `bootcode/`, put your asm files there and scons will automatically pick them up.

**Comment by Derekduke** [comment]
In a bare metal environment, now I have a tflite model file or model file of other frameworks, how can I use ACL to complete the operation on cortex-a?

**Comment by morgolock** [comment]
Hi @Derekduke 

You need an OS support for running tflite models, these require many system calls to parse the model.

I'd advice you try running the model with the ExecuteNetwork tool from https://github.com/ARM-software/armnn/tree/branches/armnn_21_02/tests/ExecuteNetwork

Hope this helps.
