### ISSUE TITLE
Build error of neon on Odroid

### ISSUE THREAD

**Issue by Rahn80643** [ARM-software/ComputeLibrary#892]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

**Platform:**
Odroid C4

**Operating System:**
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

**Problem description:**
Hi,
I tried to compile compute library base on [this tutorial](https://arm-software.github.io/armnn/21.02/md_delegate__build_guide_native.xhtml#build-the-tflite-delegate--stand-alone-), but when I set neon=1, I got the following error:
./arm_compute/core/PixelValue.h:38:5: error: `arm_compute::PixelValue::PixelValue()' does not throw; perhaps it should be declared `noexcept` [-Werror=noexcept]

The version of compute library is set as 21.02.

Currently, I set neon=0 and compute library is compiled successfully. I'm not sure if this is a bug on Odroid, compute library, or the version of Ubuntu.

![computelibrary_error](https://user-images.githubusercontent.com/8951991/113641380-15422900-96b0-11eb-9d8f-806a5aba63bc.png)

Thank you,
Rahn

**Comment by morgolock** [comment]
Hi @Rahn80643 

This patch solves the problem:
https://review.mlplatform.org/c/ml/ComputeLibrary/+/5281

Hope this helps

**Comment by Rahn80643** [comment]
Hi @morgolock,
I've successfully built Compute Library with the patch.

Thank you

**Comment by Divy-Jain** [comment]
How to apply the patch?

**Comment by developer-compute** [comment]
Hi,

You have to cherry pick the patch on the top of 21.02.

21.05 and 21.08 already have the fix applied.

Hope this helps.
________________________________
