### ISSUE TITLE
Can it's support Adreno 650 gpu?

### ISSUE THREAD

**Issue by Saikatsaha1996** [ARM-software/ComputeLibrary#894]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

**Platform:**
Android

**Operating System:**
11

**Problem description:**

**Comment by morgolock** [comment]
Hi @Saikatsaha1996 

ACL is optimised for both Arm CPUs and GPUs using SIMD technologies. While it could certainly work on devices with support for OpenCL 2.0 you will see the best results using it in conjunction with arm CPUs or GPUs.

The library requires OpenCL1.1 with support of non uniform workgroup sizes or OpenCL2.0.

Please take a look at the latest documentation for more information: https://arm-software.github.io/ComputeLibrary/v21.02/index.xhtml#S3_7_cl_requirements

Hope this helps

**Comment by Saikatsaha1996** [comment]
Please please can you share any tutorial videos ?..
Actually I don't have knowledge about code c++, jave ,c language but I want to increase my OpenCL gpu performance... My and mobile gpu driver OpenGL ES 3.2 .. but I saw in my device already available OpenCL 2.0 but showing max gpu frequency 1Mhz ... ...

**Comment by morgolock** [comment]
Hi @Saikatsaha1996 

I'd suggest first learning C/C++ or python.
Your GPU manufacturer would advice which is the best solution for you (google adreno gpu sdk). ACL is developed for MALI GPUs and not Adreno. 

Hope this helps.
