### ISSUE TITLE
How to write code using NEArithmeticAdditionKernel especially on broadcasting add.

### ISSUE THREAD

**Issue by JAEWOOKe** [ARM-software/ComputeLibrary#895]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v19.05 Build options: {'arch': 'arm64-v8a', 'opencl': '1', 'neon': '1', 'examples': '1', 'asserts': '0', 'debug': '1', 'openmp': '1', 'os': 'linux', 'Werror': '0'} Git hash=4ba87dbdc3b22220eba4a792c1f5c87e7a88c7af
**Platform:**
HTG_Z920 board
**Operating System:**
Ubuntu 18.04

**Problem description:**

I'm using ACL for ONNX Runtime, with the corresponding ACLExecutionProvider. 

While writing Add operator kernel for ACL, I encountered a problem with broadcast add.

![image](https://user-images.githubusercontent.com/36403422/114397953-3340e980-9bda-11eb-8659-06361306a328.png)

Add node: Add_26
Input 0 Name: 233 Shape: {1, 128, 1}
Input 1 Name: 234 Shape: {}

I'm using the kernel as following:
```
  const Tensor* A = ctx->Input<Tensor>(0);
  const Tensor* B = ctx->Input<Tensor>(1);

  const T* a_data = A->template Data<T>();
  const T* b_data = B->template Data<T>();

  arm_compute::Tensor a {}, b {}, y {};
  
  std::vector<int64_t> Y_dims;
  auto &a_shape = A->Shape().GetDims();
  Y_dims = std::vector<int64_t>(a_shape.begin(), a_shape.end());
  Tensor* Y = ctx->Output(0, TensorShape(Y_dims));
  T* y_data = Y->template MutableData<T>();

  a.allocator()->init(arm_compute::TensorInfo(ACLTensorShape(A->Shape()), arm_compute::Format::F32));
  b.allocator()->init(arm_compute::TensorInfo(ACLTensorShape(B->Shape()), arm_compute::Format::F32));
  y.allocator()->init(arm_compute::TensorInfo(ACLTensorShape(Y->Shape()), arm_compute::Format::F32));

  a.allocator()->import_memory((void*) a_data);
  b.allocator()->import_memory((void*) b_data);
  y.allocator()->import_memory((void*) y_data);

  arm_compute::NEArithmeticAddition add_core;

  add_core.configure(&a, &b, &y, arm_compute::ConvertPolicy::WRAP);
  add_core.run();

```
The error comes from NEArithmeticKernel.cpp:483 @ validate_arguments

`const TensorShape out_shape = TensorShape::broadcast_shape(input1.tensor_shape(), input2.tensor_shape());`

I'm not sure why the output shows as "out_shape.total_size() == 0"

input1 has a dim of 3, and input2 has a dim of 1.

Can anyone help me fix the code?

**Comment by morgolock** [comment]
Hi @JAEWOOKe 

Can you please upgrade to the latest acl release v21.02 and let us know if you still see the problem?

**Comment by JAEWOOKe** [comment]
Thanks for responding. I think the problem was that input2 is a scalar, which was meant to be a tensor with at least one dimension.
