### ISSUE TITLE
Performance difference between GEMM and MatMul.

### ISSUE THREAD

**Issue by JAEWOOKe** [ARM-software/ComputeLibrary#896]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
Output of 'strings libarm_compute.so | grep arm_compute_version':
arm_compute_version=v19.05 Build options: {'arch': 'arm64-v8a', 'opencl': '0', 'neon': '1', 'examples': '1', 'asserts': '0', 'debug': '0', 'openmp': '1', 'os': 'linux', 'Werror': '0'} Git hash=4ba87dbdc3b22220eba4a792c1f5c87e7a88c7af
**Platform:**
XIlinx board (HTB_Z920 board)
**Operating System:**
Ubuntu 18.04

**Problem description:**
I'm using ACL for ONNX Runtime, with the corresponding ACLExecutionProvider.

I wrote a MatMul operator kernel once with NEGEMMMatrixMultiplyKernel.h and the other with NEGEMM.h.

Executing MatMul using NEGEMM shows faster execution than CPU while using NEGEMMMatrixMultiplyKernel was slower than CPU.

Can anyone tell me the reason?

Also I want to know element-wise add, mul kernel than exceeds CPU.

Using NEArithmeticAddition.h and NEPixelWiseMultiplication.h was also slower than CPU.

**Comment by morgolock** [comment]
Hi @JAEWOOKe 

19.05 is two years old now, please try to update to 21.02.

In order to help could you please share the shapes and data types of the workloads you have tested?

What CPU and frequency are you using to run the workloads?
