### ISSUE TITLE
Help wanted experiment purpose Adreno gpu

### ISSUE THREAD

**Issue by Saikatsaha1996** [ARM-software/ComputeLibrary#898]
I am trying to build with termux
Android platform

Please 🙏 help me

Processor Qualcomm Snapdragon 865
Arm V8
Gpu Adreno 650

Os version Android 11

I am trying to build with this commend

Download the Arm Developer compute Library
wget https://github.com/ARM-software/ComputeLibrary/releases/download/v19.05/arm_compute-v19.05-bin-linux.tar.gz 11
extract the downloaded filed
tar -xf arm_compute-v19.05-bin-linux.tar.gz
mv -t arm_compute-v19.05-bin-linux /usr/lib/
export CC=gcc-8
export CXX=g+±8
-->

**Problem description:**
But when I put this commend I am facing problem like this

mv -t arm_compute-v19.05-bin-linux /usr/lib/
![Screenshot_2021-05-18-00-10-43-706_com termux](https://user-images.githubusercontent.com/72664192/118540857-a7892280-b76e-11eb-8f14-5d8dae22f682.jpg)

**Comment by Saikatsaha1996** [comment]
Termux not supported GCC compiler
Only available clang...
Can I compile with clang ?

**Comment by morgolock** [comment]
Hi @Saikatsaha1996 

Yes, you can build ACL with clang.


Please take some time to read the documentation:

https://arm-software.github.io/ComputeLibrary/v21.05/how_to_build.xhtml#S1_2_linux
https://arm-software.github.io/ComputeLibrary/v21.05/how_to_build.xhtml#S1_3_android
