### ISSUE TITLE
Linking issues while building NEON application for baremetal ARM AArch64 (A53 cores)

### ISSUE THREAD

**Issue by agarwal-ayushi** [ARM-software/ComputeLibrary#899]
**Output of 'strings libarm_compute-static.a | grep arm_compute_version':**

arm_compute_version=v19.05 Build options: {'Werror': '0', 'debug': '0', 'asserts': '0', 'neon': '1', 'opencl': '0', 'examples': '1', 'build': 'cross_compile', 'os': 'bare_metal', 'cppthreads': '0', 'openmp': '0', 'arch': 'arm64-v8a', 'standalone': '1'}

Static Library built using above parameters. I link to `-larm_compute-static` and `-larm_compute_core-static` while building the application. 

**Platform:**
Target: AArch64 HW board with A53 cores
Host: Linux System (Toolchain used : aarch64-none-elf-*)

**Operating System:**
Bare Metal

**Problem description:**
I am trying to build NEON application from the examples (Tried two of them : neon_convolution and neon_sgemm. 
I get similar issues for both. 

Compiler used: `aarch64-none-elf-` [ARM GNU 9.2 TOOLCHAIN]

Other included files:
`utils/Utils.cpp`

Other flags:
`-DARMCA53` `-O0 -g3 -Wall -Wl,-no-undefined -c -fmessage-length=0  -DNO_MULTI_THREADING -std=c++14 -ffunction-sections -fdata-sections -mstrict-align -mcpu=cortex-a53 `

Attaching image for LD issues of SGEMM. The error of undefined reference to `IRuntimeContext` is common in both. There are undefined reference to `std::shared_ptr`, this is also common. 
I am building the examples with the required startup code. 

![image](https://user-images.githubusercontent.com/30519597/119348530-9f733a80-bcba-11eb-90d8-5775aadfef95.png)

**Comment by mpekatsoula** [comment]
Hi @agarwal-ayushi 

I was able to build the example using:
`aarch64-none-elf-g++ neon_convolution.cpp ../utils/Utils.cpp  -I./ComputeLibrary/ -I./ComputeLibrary/include/ -larm_compute-static -larm_compute_core-static  -DNO_MULTI_THREADING -DBARE_METAL -std=c++14 -L./ComputeLibrary/build/opencl/ --specs=nosys.specs`

Should be similar in your case, just make sure you change the relative paths to match yours. 

If you use the latest release https://github.com/ARM-software/ComputeLibrary/releases/tag/v21.05,  the examples are built automatically :)

**Comment by agarwal-ayushi** [comment]
@mpekatsoula 

In the command that you have mentioned, I see that you are also linking to `build/opencl` in build directory. However, while building arm compute library for bare-metal, there was no such directory generated. I have used the following command to build the arm compute library before building the example:
`scons Werror=1 -j8 debug=0 neon=1 opencl=0 os=bare_metal arch=arm64-v8a build=cross_compile cppthreads=0 openmp=0 standalone=1`

I think its a constraint that one cannot build for baremetal with `opencl=1`. 

I am not able to build, yet. 

> If you use the latest release https://github.com/ARM-software/ComputeLibrary/releases/tag/v21.05, the examples are built automatically :)
What about the bootcode? Is that taken care as well in the latest version? I am not very sure about this since start up code could be HW dependent. 
Where can I find the commands used to build the examples in this version?

**Comment by mpekatsoula** [comment]
Oh sorry, that is the name of my build folder, it's confusing. When I build, I use `scons build_dir=opencl` so this generated the folder build/opencl. It could be anything and in your case where you don't provide it, all the files should be under build/.

So to fix my above command to match your config:
`aarch64-none-elf-g++ neon_convolution.cpp ../utils/Utils.cpp -I./ComputeLibrary/ -I./ComputeLibrary/include/ -larm_compute-static -larm_compute_core-static -DNO_MULTI_THREADING -DBARE_METAL -std=c++14 -L./ComputeLibrary/build/ --specs=nosys.specs`

We do take care of the bootcode, although it's not very well tested as a feature but you can try. scons will pick up the folder inside Computelibrary with the name `bootcode` if it exists, it will compile the files and link them with the example applications.

**Comment by agarwal-ayushi** [comment]
OK. Understood. I am linking to the build folder that has the *-static.a files. 
Although, I am still getting same issues (as in the image attached). Let me try to build it on a different host. 
![image](https://user-images.githubusercontent.com/30519597/119703131-d93b7100-be73-11eb-9ee3-f4414a812d5f.png)

> We do take care of the bootcode, although it's not very well tested as a feature but you can try. scons will pick up the folder inside ComputeLibrary with the name bootcode if it exists, it will compile the files and link them with the example applications.
>
How do you take care of the inputs like images or the model parameters in bare-metal? Any suggestions?

**Comment by mpekatsoula** [comment]
Can you share the exact command you're using to build the examples?

> How do you take care of the inputs like images or the model parameters in bare-metal? Any suggestions?
I don't think we support running bare metal examples with real mages. As for the model parameters using the --data option will load the weights in .npy form into the example i.e.
` ./build/examples/graph_lenet --data=<path_leading_to_data>`

**Comment by agarwal-ayushi** [comment]
> Can you share the exact command you're using to build the examples?
>
Actually I am currently building the example on Eclipse IDE which should not have any impact if the correct flags and link directories are given. 

In my project `src/main.cpp`, I copied the code for `neon_convolution.cpp`. 
Then I do the following C++ Compiler settings:
Include files (-include): utils/Utils.cpp
Include Paths (-I): `ComputeLibrary` and `ComputeLibrary/include`

All Compiler Options: -DARMCA53 -I"ComputeLibrary" -I"ComputeLibrary\include" -include"utils\Utils.cpp" -O0 -g3 -pedantic -Wall -Wl,-no-undefined -c -fmessage-length=0 -DNO_MULTI_THREADING -std=c++14 -DBARE_METAL -v -ffunction-sections -fdata-sections -mstrict-align -mcpu=cortex-a53 -specs=nosys.specs
 
C++ Linker:
Libraries (-l): arm_compute-static, arm_compute_core-static
Library Path (-L): `ComputeLibrary/build/`

All Linker Options: -L"ComputeLibrary/lib/" -v -T "RAM.ld" -Wl,-Map,"A53.map" -Xlinker --gc-sections -mcpu=cortex-a53 -specs=nosys.specs

**Comment by mpekatsoula** [comment]
I wasn't able to reproduce your issue but please have a look into our SConstruct file and make sure you use the same flags. For example -static-libgcc -static-libstdc++ -static are some of the flags that are used and seems that are missing in your case.

**Comment by agarwal-ayushi** [comment]
Hi @mpekatsoula 

Thanks for the help. I used all the flags that were getting used in the SConstruct file. 

All the Compile flags now are:
`-std=c++14 -DARMCA53 -I"ComputeLibrary-21.05/include" -I"ComputeLibrary-21.05" -O0 -g3 -pedantic -Wall -Wextra -C -fmessage-length=0 -DENABLE_FP16_KERNELS -DENABLE_FP32_KERNELS -DENABLE_QASYMM8_KERNELS -DENABLE_QASYMM8_SIGNED_KERNELS -DENABLE_QSYMM16_KERNELS -DENABLE_INTEGER_KERNELS -DENABLE_NHWC_KERNELS -DENABLE_NCHW_KERNELS -D_GLIBCXX_USE_NANOSLEEP -DNO_MULTI_THREADING -DBARE_METAL -DARM_COMPUTE_CPU_ENABLED -v -fPIC -ffunction-sections -fdata-sections -Wdisabled-optimization -Wformat=2 -Winit-self -Wstrict-overflow=2 -Wswitch-default -Woverloaded-virtual -Wformat-security -Wctor-dtor-privacy -Wsign-promo -Weffc++ -Wno-overlength-strings -Wlogical-op -Wnoexcept -Wstrict-null-sentinel -Wno-ignored-attributes -mstrict-align -march=armv8-a -mcpu=cortex-a53 -specs=nosys.specs`

All Linker flags:
`-L"ComputeLibrary-21.05/build" -static-libgcc -static-libstdc++ -static -T "RAM.ld" -Wl,-Map,"A53.map" -Xlinker
--gc-sections  -march=armv8-a -mcpu=cortex-a53 -specs=nosys.specs -larm_compute-static -larm_compute_core-static`

However I still land into linking issues while building neon_scale.cpp.

Any other pointers at what should I look into?
