### ISSUE TITLE
No image for examples

### ISSUE THREAD

**Issue by SCUTE-ZZ** [ARM-software/ComputeLibrary#9]
Hi , I think supply an image for examples will more friendly.

**Comment by AnthonyARM** [comment]
It should work with *any* PPM file you [can find](https://www.google.co.uk/search?site=imghp&tbm=isch&source=hp&oq=test+filetype:ppm&gs_l=img.3...3000.6225.0.6417.18.11.0.7.7.0.105.620.8j1.9.0....0...1ac.1.64.img..2.12.622.0..0j35i39k1j0i5i30k1j0i8i30k1j0i24k1.-bqWJjWFAds&q=test#tbm=isch&q=landscape&*)
