### ISSUE TITLE
why NEGEMMLowp、resize(NEscale) are very slow on A53？

### ISSUE THREAD

**Issue by Weyne168** [ARM-software/ComputeLibrary#90]
HI，I tested the resize function by NEscale and compared its performance with opencv's resize.
and, I found that the NEscale is slower than opencv 10 times.
besides, I also compared the NEGEMMLowp (used U8 format) with openblas(which only supports f32, and we set it as single thread ). On the same shape matrices, the library also slower than openblas a lot.
so, I feel very confused.  why the performance is not well? and how can I get a performance improvement by this library?
ps:
I compiled this library with "armv7a" architecture and run on unbuntu-32bits operation system.

**Comment by GeorgeARM** [comment]
Hello @Weyne168 ,

Can you please tell us how you build the library (build command) and your program?

**Comment by Weyne168** [comment]
Thank you, I found we did not set the debug=0. when we fixed this problem, the cross compiler can generate high speed program
