### ISSUE TITLE
undefined reference to `arm_compute::Tensor::Tensor(arm_compute::IRuntimeContext*)'

### ISSUE THREAD

**Issue by ObjectDetectADAS** [ARM-software/ComputeLibrary#901]
new.cpp:(.text+0x84): undefined reference to `arm_compute::Tensor::Tensor(arm_compute::IRuntimeContext*)'
/usr/bin/ld: /tmp/ccVFGQqa.o: in function `arm_compute::Tensor::~Tensor()':
new.cpp:(.text._ZN11arm_compute6TensorD2Ev[_ZN11arm_compute6TensorD5Ev]+0xc): undefined reference to `vtable for arm_compute::Tensor'
/usr/bin/ld: new.cpp:(.text._ZN11arm_compute6TensorD2Ev[_ZN11arm_compute6TensorD5Ev]+0x10): undefined reference to `vtable for arm_compute::Tensor'
/usr/bin/ld: new.cpp:(.text._ZN11arm_compute6TensorD2Ev[_ZN11arm_compute6TensorD5Ev]+0x20): undefined reference to `vtable for arm_compute::Tensor'
/usr/bin/ld: new.cpp:(.text._ZN11arm_compute6TensorD2Ev[_ZN11arm_compute6TensorD5Ev]+0x24): undefined reference to `vtable for arm_compute::Tensor'
/usr/bin/ld: new.cpp:(.text._ZN11arm_compute6TensorD2Ev[_ZN11arm_compute6TensorD5Ev]+0x3c): undefined reference to `arm_compute::TensorAllocator::~TensorAllocator()'
collect2: error: ld returned 1 exit status

while trying to add Tensor in my code i getting this error 
can u please help me to sort it out

thanks in advance

**Comment by morgolock** [comment]
Hi @ObjectDetectADAS 

It looks like a linker error, would you please share the command you use to compile your code?

**Comment by ObjectDetectADAS** [comment]
@morgolock 
g++   arm_compute/runtime/MemoryRegion.h arm_compute/core/Helpers.h arm_compute/core/ITensor.h arm_compute/core/Types.h -Iinclude -I file_path/filename.cc

**Comment by morgolock** [comment]
Hi @ObjectDetectADAS 

You must use `-larm_compute -larm_compute_core` in your build command. Make sure also to use `-l path/to/acl/acl_shared_libs_dir` 

For example: `aarch64-linux-gnu-g++ examples/neon_convolution.cpp utils/Utils.cpp -I. -Iinclude -std=c++14 -L. -larm_compute -larm_compute_core -o neon_convolution`

Hope this helps
