### ISSUE TITLE
ACL Sigmoid layer performs slower than OpenMP implemntation

### ISSUE THREAD

**Issue by Hari-MathWorks** [ARM-software/ComputeLibrary#902]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v20.02.1 Build options: {'arch': 'armv7a', 'opencl': '0', 'neon': '1', 'build': 'cross_compile', 'debug': '0', 'os': 'linux'} Git hash=unknown

**Platform: Raspberry Pi 4 Model-B Quad core Cortex-A72 (ARM v8) 64-bit SoC @ 1.5GHz**

**Operating System: Linux**

I have implemented the Sigmoid layer using ACL NEActivationLayer API and OpenMP custom implementation. I found that ACL performs 1.3x slower than OpenMP implementation.

FYI, I have attached the source code of both implementations, you can download this implementation from this [link](https://mathworks-my.sharepoint.com/:f:/p/hnalla/EmQTWJda7adHq8mzvidpH84B2pbs5qUF7HehF6hwNfEEOw?e=TXCbgT).

Please download the scripts and follow the below steps to see the results:
1. Download the benchmark scripts from the above link.
To see ACL results: 
1. Enable USEACLIMPL preprocessor flag in onlySigmoid.cpp.
2. run "make acl" from the terminal.
3. Run onlySigmoid_acl_exe then it will prints runtime in milliseconds.

To see OpenMP implementation results: 
1. Disable USEACLIMPL preprocessor flag in onlySigmoid.cpp.
2. run "make openmp" from the terminal.
3. Run onlySigmoid_openmp_exe then it will prints runtime in milliseconds.

Let me know if need any help to reproduce this issue.

Thanks,
Hari

**Comment by morgolock** [comment]
Hi @Hari-MathWorks 

You will get better performance if you build ACL with `arch=arm64-v8a`. Is there any particular reason why you are using armv7a? If possible please try with v8a. I'd also advice updating to v21.05, v20.02.1 is very old.

I built and ran your test with the head of master and I see ACL doing better than the openmp implementation. 

```
root@acl_hikey_dev:~/tmp/pabtel01/mathworks# LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. ./onlySigmoid_openmp_exe 
Using hand-coded implementation..
Average time:42.400000  
root@acl_hikey_dev:~/tmp/pabtel01/mathworks# 
root@acl_hikey_dev:~/tmp/pabtel01/mathworks# 
root@acl_hikey_dev:~/tmp/pabtel01/mathworks# 
root@acl_hikey_dev:~/tmp/pabtel01/mathworks# LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. ./onlySigmoid_acl_exe 
Using ACL implementation..
Average time:12.200000  
root@acl_hikey_dev:~/tmp/pabtel01/mathworks# 
root@acl_hikey_dev:~/tmp/pabtel01/mathworks# 
root@acl_hikey_dev:~/tmp/pabtel01/mathworks# 
root@acl_hikey_dev:~/tmp/pabtel01/mathworks# 
root@acl_hikey_dev:~/tmp/pabtel01/mathworks# 
root@acl_hikey_dev:~/tmp/pabtel01/mathworks# 
root@acl_hikey_dev:~/tmp/pabtel01/mathworks# LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. ./onlySigmoid_openmp_exe 
Using hand-coded implementation..
Average time:41.200000  
root@acl_hikey_dev:~/tmp/pabtel01/mathworks# LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. ./onlySigmoid_acl_exe 
Using ACL implementation..
Average time:11.400000  
root@acl_hikey_dev:~/tmp/pabtel01/mathworks# LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. ./onlySigmoid_openmp_exe 
Using hand-coded implementation..
Average time:40.600000  
root@acl_hikey_dev:~/tmp/pabtel01/mathworks# LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. ./onlySigmoid_acl_exe 
Using ACL implementation..
Average time:10.400000  
```

**Comment by Hari-MathWorks** [comment]
Hi @morgolock ,

Thanks for your response. It was good to see that ACL performing better on arch=arm64-v8a.
But in my case, I'm trying to deploy on a Raspberry Pi 4 device that has armv7a. Is this performance difference expected on armv7a?

Thanks,
Hari

**Comment by morgolock** [comment]
Hi @Hari-MathWorks 

Please see below the results of the test on armv7a.

ACL is 2 times faster than the openmp implementation.

```
root@acl_hikey_dev:~/tmp/pabtel01/mathworks# LD_LIBRARY_PATH=../acl_neon+cl_release_v7a/ ./onlySigmoid_openmp_exe 
Using hand-coded implementation..
Average time:43.200000  
root@acl_hikey_dev:~/tmp/pabtel01/mathworks# LD_LIBRARY_PATH=../acl_neon+cl_release_v7a/ ./onlySigmoid_acl_exe 
Using ACL implementation..
Average time:22.400000  
```

Could you please share the ouput of the following command?:
`LD_LIBRARY_PATH=../acl_neon+cl_release_v7a/ ./arm_compute_validation  | head -n 20`

You should see something like this:
```
root@acl_hikey_dev:~/tmp/pabtel01/mathworks# LD_LIBRARY_PATH=../acl_neon+cl_release_v7a/ ./arm_compute_validation  | head -n 20
Version = arm_compute_version=v0.0-unreleased Build options: {'test_examples': '0', 'standalone': '0', 'test_filter': 'DirectConvolutionLayer.cpp', 'opencl': '1', 'neon': '1', 'debug': '0', 'validation_tests': '1', 'examples': '0', 'benchmark_tests': '0', 'arch': 'armv7a', 'benchmark_examples': '0'} Git hash=3bf76b1ade354f0b3a4d329a6e80ac4f90fcf11d
CommandLine = ./arm_compute_validation 
Seed = 445901339
CL_DEVICE_VERSION = OpenCL 2.0 not_released.51d50be.a616490a17cf20b2ee8ef25409eb8a1f
cpu_has_fp16 = false
cpu_has_dotprod = false
CPU0 = GENERIC
CPU1 = GENERIC
CPU2 = GENERIC
CPU3 = GENERIC
CPU4 = A73
CPU5 = A73
CPU6 = A73
CPU7 = A73
```
