### ISSUE TITLE
Mali T760 gpu showing 5 mhz help wanted

### ISSUE THREAD

**Issue by Saikatsaha1996** [ARM-software/ComputeLibrary#903]
Asus twinker board
Os asus twinker Debian
Processor rockchip 3288
Gpu Mali T 760
After installation showing OpenCL gpu frequency only 5 mhz

How can I slove gpu max frequency 650 mhz
![IMG_20210603_213829](https://user-images.githubusercontent.com/72664192/120709525-93695300-c4da-11eb-87ab-71cd6ff0ca1b.jpg)
![IMG_20210604_012225](https://user-images.githubusercontent.com/72664192/120709570-9f551500-c4da-11eb-82c5-ed14b8168c76.jpg)

**Comment by morgolock** [comment]
Hi @Saikatsaha1996 

Please take a look at this https://community.arm.com/developer/tools-software/graphics/f/discussions/2741/how-to-get-mali-gpu-s-frequency

Hope this helps.
