### ISSUE TITLE
ACL v20.02 with ONNX-Runtime resnet and inception models fails in last GEMM

### ISSUE THREAD

**Issue by pedwo** [ARM-software/ComputeLibrary#906]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v20.02 Build options: {'arch': 'arm64-v8a', 'opencl': '0', 'neon': '1', 'prefix': '/usr', 'set_soname': '1', 'PREFIX': '/usr', 'benchmark_tests': '1', 'openmp': '1', 'extra_cxx_flags': '-fPIC', 'toolchain_prefix': ' '} Git hash=36ccc90158c65844b3c53c5462c6d7d852b97278

**Platform:**
arm64

**Operating System:**
Linux

**Problem description:**
When ACL v20.02 is used with ONNX-Runtime v1.8.0, resnet and inception models fail in the last GEMM (General Matrix multiplication) node with onnx-rt complaining about missing input. For ResNet it says "Missing Input: resnetv17_dense0_weight" or similar depending on the model.
NXP have added patches to work around this issue in their fork of ACL: git://source.codeaurora.org/external/imx/arm-computelibrary-imx.git See their last two commits on the rel_imx_5.4.70_2.3.2 tag that disables the backend mutating pass.
Note that ONNX-Runtime currently does not support newer versions of ACL, so I cannot test them.
Is there a commit that fixes this issue rather than working around it?

**Comment by morgolock** [comment]
Hi @pedwo 

I'd suggest running any onnx models through armnn's ExecuteNetwork.

For more information please see: 
https://github.com/ARM-software/armnn/tree/branches/armnn_21_08/tests/ExecuteNetwork

Hope this helps.
