### ISSUE TITLE
README.md - Tutorial: Cartoonifying Images on Raspberry Pi with the Compute Library - Page has moved error

### ISSUE THREAD

**Issue by ASR-Engineering-Consulting** [ARM-software/ComputeLibrary#907]
Tutorial link does not work for 
Tutorial: Cartoonifying Images on Raspberry Pi with the Compute Library

We could not find this page
The link that sent you here may be incorrect or the page has moved.

**Output of 'strings libarm_compute.so | grep arm_compute_version':**
"https://community.arm.com/management/archive/b/employee-spotlight/posts/cartoonifying-images-on-raspberry-pi-with-the-compute-library"
" https://github.com/ARM-software/ComputeLibrary"

**Platform:**
Compute Library
**Operating System:**

**Problem description:**

**Comment by EdjeElectronics** [comment]
I'm interested in this tutorial too. Please let us know when it's available again!
