### ISSUE TITLE
FP32 Pooling layer is performing better than QASYMM8_SIGNED Pooling Layer

### ISSUE THREAD

**Issue by pranathibl** [ARM-software/ComputeLibrary#908]
Hi,

I am trying to quantize Pooling Layer and I have observed performance of QASYMM8_SIGNED Pool is degrading w.r.t FP32 instead of improving.
I have attached the setup I have used for benchmarking. 

Size                                                                                       FP32(msec)         QASYMM8_SIGNED (msec)
7x7x71024 (padding[1 1 1 1], stride [1 1], poolDim[2 2])        1.4                       5.48
7x7x71024 (padding[1 1 1 1], stride [1 1], poolDim[3 3])        2.1                        6.8

[avgPoolLayer_int8Standalone.zip](https://github.com/ARM-software/ComputeLibrary/files/6685692/avgPoolLayer_int8Standalone.zip)
I am using ACL v20.02.1 and running this on Raspberrypi 3 Model B.

Could you let me know why is this observed?

Thanks
Pranathi

**Comment by morgolock** [comment]
Hi @pranathibl 

If you use NHWC intead of NCHW, you will get better performance. I modified your test and I see int8 2x faster than fp32 on armv7a.

A potential workaround would be to permute the input tensor to NHWC, run the pooling layer and then permute back to NCHW.

**Comment by morgolock** [comment]
Closing this, please reopen if you still need support.
