### ISSUE TITLE
How can I set the number of threads ?

### ISSUE THREAD

**Issue by Weyne168** [ARM-software/ComputeLibrary#91]
Hi, I found that the library will use all cores on default.
in some cases, I need to run it with given number of threads. how can I set the number?

**Comment by AnthonyARM** [comment]
Hi,

You can call `arm_compute::Scheduler::get().set_num_threads(num_threads);` at the beginning of your program.

**Comment by duhuanxianzi** [comment]
Hi, I found you should put "NEScheduler::get().force_number_of_threads(num_threads);" at the beginning of your program. @AnthonyARM

**Comment by duhuanxianzi** [comment]
Hi, I found you should put "NEScheduler::get().force_number_of_threads(num_threads);" at the beginning of your program. In addition, "NEScheduler.h" should be also include in the header files.

**Comment by ditta95aR** [comment]
#91

**Comment by ditta95aR** [comment]
#91

**Comment by samsun639** [comment]
CPPScheduler::force_number_of_threads() can be used to manually set the number of threads
