### ISSUE TITLE
Gemm   layer  large memory usage ,how to reuse memory by memory manager?

### ISSUE THREAD

**Issue by TPcoding** [ARM-software/ComputeLibrary#911]
arm_compute_version=v21.05 Build options: {'arch': 'arm64-v8a', 'opencl': '0', 'neon': '1', 'build': 'native', 'debug': '1', 'os': 'linux', 'Werror': '1'} Git hash=f7399fd616cc8ccedfae668da3023e589a7ef558

**Platform:**
arm aarch64 linux
**Operating System:**

**Problem description:**
    int m=1024;
    Allocator allocator{};
    auto lifetime_mgr = std::make_shared<BlobLifetimeManager>();
    auto pool_mgr = std::make_shared<PoolManager>();
    auto mm_layers = std::make_shared<MemoryManagerOnDemand>(lifetime_mgr, pool_mgr);

    Tensor a1, b1, c1;
    Tensor a2, b2, c2;
    NEGEMM fc_1(mm_layers);
    NEGEMM fc_2(mm_layers);

    a1.allocator()->init(TensorInfo(TensorShape(m, m), 1, DataType::F32));
    b1.allocator()->init(TensorInfo(TensorShape(m, m), 1, DataType::F32));
    c1.allocator()->init(TensorInfo(TensorShape(m, m), 1, DataType::F32));
    a1.allocator()->allocate();
    b1.allocator()->allocate();
    c1.allocator()->allocate();

    a2.allocator()->init(TensorInfo(TensorShape(m, m), 1, DataType::F32));
    b2.allocator()->init(TensorInfo(TensorShape(m, m), 1, DataType::F32));
    c2.allocator()->init(TensorInfo(TensorShape(m, m), 1, DataType::F32));
    a2.allocator()->allocate();
    b2.allocator()->allocate();
    c2.allocator()->allocate();

    fc_1.configure(&a1, &b1, nullptr, &c1, 1, 0);
    fc_2.configure(&a2, &b2, nullptr, &c2, 1, 0);
    mm_layers->populate(allocator, 1 /* num_pools */);
    fc_1.run();
    fc_2.run();

abc tensor size: 1024*1024*4*6=25165824,but I use valgrind massif, peak memory allocated 39.8M.
I know a b c tensor can use memory manager.But I have a lot of doubts about temporary memory management inside and between layer functions.
After gemm.configure() ,function inner temporary tensor maybe 14M. I think after fc_1 run,fc_2 can use fc_1 temporary memory. I try remove memory manager, it also use 39.8M. 
Does layer need more configured memory to speed up calculate ,avoid to use more temporary allocate ?

**Comment by GeorgeARM** [comment]
Hello @TPcoding ,

Thank you very much for raising this.
So the memory manager will handle the internally memory required by the function. The amount of the memory depends on what kind of GEMM implementation is used. 
So overall, the memory that you will need is the memory needed by your 6 tensors plus the memory needed by the memory manager to transform some of the tensors internally to an optimal format that we can get most performance out of.
You can check how much memory the pool of the manager has allocated and see if the sum matches what massif uses.

The memory could be the same with or without the memory manager depending on the amount of memory needed but if you use two functions that both need auxiliary memory then memory should be reused between them, so you should see less peak memory.

If your pool manager is empty then we need to have a look as it could be a regression on our side.

Hope this helps,
George
