### ISSUE TITLE
Performance issue in NEDepthwiseConvolutionLayerNativeKernel 

### ISSUE THREAD

**Issue by szihs** [ARM-software/ComputeLibrary#913]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v21.02 Build options: {'embed_kernels': '0', 'arch': 'armv7a', 'utils': '1', 'neon': '1', 'build': 'native', 'debug': '0', 'extra_cxx_flags': '-Os', 'os': 'tizen', 'Werror': '0', 'examples': '0'} Git hash=unknown

**Platform:**
armv7l

**Operating System:**
Tizen

**Problem description:**
https://github.com/ARM-software/armnn/issues/563#issue-954499235

NEDepthwiseConvolutionLayerNativeKernel is consuming most of the time for running the below network layer.
![Vej5lD0q0d](https://user-images.githubusercontent.com/675653/127274905-cc0b1d8c-227b-4f87-aaa1-bf34d7e2ba12.png)

I feel the time taken is too high.  Could you please help to root cause the reason for the same & how can i check to improve.

Regards,
Harsh

**Comment by szihs** [comment]
Hello, Is this issue with ACL..? May I know when is the tentative fix date?

**Comment by morgolock** [comment]
Hi @szihs 


In general, ACL's armv7a kernels are not as optimised as aarch64 kernels. Have you tried running the same model on armv8a to compare the performance?

Can you please share the model with us?

**Comment by szihs** [comment]
I will try to run on aarch64.
I cannot share model due to company's policy.

Any other pointers will be helpful.
