### ISSUE TITLE
how to set threads for layer level when run the example neon_cnn.cpp?

### ISSUE THREAD

**Issue by zx854217561** [ARM-software/ComputeLibrary#915]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
v20.08

**Platform:**
rk3399
**Operating System:**
ubuntu

**Problem description:**
Hello,i am trying to set different numbers of cores for different layers.For examples,i set 4 cores for conv0 layer ,and set 2 cores for pool layer. Now i can't even set numbers for this examples.I find function set_num_threads in scheduler.cpp. But i am not know where add it in.Is there any API for CPU to set numbers of cores?

**Comment by morgolock** [comment]
Hi @zx854217561 

You could use the method `void set_num_threads(unsigned int num_threads)` in https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/runtime/IScheduler.h#L146


```
pabtel01@e124551:~/work/acl/ComputeLibrary$ git diff
diff --git a/examples/neon_cnn.cpp b/examples/neon_cnn.cpp
index 5ecf055e60..7504914a43 100644
--- a/examples/neon_cnn.cpp
+++ b/examples/neon_cnn.cpp
@@ -30,6 +30,7 @@
 #include "arm_compute/runtime/PoolManager.h"
 #include "utils/Utils.h"
+#include "arm_compute/runtime/NEON/NEScheduler.h"
 using namespace arm_compute;
 using namespace utils;
@@ -220,7 +221,7 @@ public:
         // Acquire memory for the memory groups
         memory_group0->acquire();
         memory_group1->acquire();
-
+        NEScheduler::get().set_num_threads(2u);
         conv0->run();
         act0.run();
         pool0.run();
```

Hope this helps.
