### ISSUE TITLE
openmp scheduler throwing runtime error for set_num_threads_with_affinity()

### ISSUE THREAD

**Issue by snadampal** [ARM-software/ComputeLibrary#916]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v21.05 Build options: {'Werror': '1', 'debug': '0', 'neon': '1', 'opencl': '0', 'openmp': '1', 'cppthreads': '0', 'os': 'linux', 'arch': 'armv8.2-a', 'build': 'native'} Git hash=b'dfc8109764b0dd97cb35b0664f8d3cb350aeb20b'

**Platform:**
NeoverseN1 

**Operating System:**
Linux (Ubuntu 20.04)

**Problem description:**
When I switch the acl scheduler from cppthreads to openmp, there is a runtime assertion from set_num_threads_affinity() function. However, when I just skipped the check (by commenting the assertion from IScheduler.cpp) I'm able to proceed and use openmp scheduler properly. Would like to understand the rational for this assertion logic and how to overcome this for OpenMP scheduler.

**Steps to reproduce the issue:**
1. build acl with openmp backend
scons Werror=1 -j8 debug=0 neon=1 opencl=0 openmp=1 cppthreads=0 os=linux arch=armv8.2-a build=native

2. Build oneDNN with these ACL libraries and test benchdnn, eg:
DNNL_VERBOSE=1 benchdnn --conv --dtag=nhwc --stag=nhwc --wtag=nhwc --cfg=f32 --mb=1 ih224oh112kh7sh2dh0ph3_iw224ow112kw7sw2dw0pw3_ic3_oc64

3. Here is the error log:
terminate called after throwing an instance of 'std::runtime_error'
 what(): in set_num_threads_with_affinity src/runtime/IScheduler.cpp:50: Feature for affinity setting is not implemented
Aborted (core dumped)

**Comment by sicong-li-arm** [comment]
Hi! Thanks for raising this issue. The `set_num_threads_with_affinity` method is not implemented for OMP scheduler, hence the error. Please use the `set_num_threads` method instead.

**Comment by snadampal** [comment]
Thanks for the details.
