### ISSUE TITLE
How to realize the cv::cvtcolor by computeLibrary?

### ISSUE THREAD

**Issue by duhuanxianzi** [ARM-software/ComputeLibrary#92]
hi, in opencv we can use the function cv::cvtcolor to convert an input image from one color space to another.
but, I don't know which function in compute library the resize function can realize the same function.
how can I convert an input image from one color space to another by compute library?

**Comment by gunasekaran7** [comment]
There are some color space conversion kernel available which can be found in   **ComputeLibrary/src/core/CL/cl_kernels/color_convert.cl**

**Comment by AnthonyARM** [comment]
You have an OpenCL function to do color convert [CLColorConvert](https://arm-software.github.io/ComputeLibrary/v17.05/classarm__compute_1_1_c_l_color_convert.xhtml) and also a NEON one [NEColorConvert](https://arm-software.github.io/ComputeLibrary/v17.05/classarm__compute_1_1_n_e_color_convert.xhtml)

**Comment by duhuanxianzi** [comment]
Thanks a lot! @AnthonyARM @gunasekaran7

**Comment by mpflanzer** [comment]
Feel free to re-open if you run into problems with the color convert functions.

**Comment by zanazakaryaie** [comment]
How can I convert a RGB image to gray?
