### ISSUE TITLE
ARMV7 NEON performance regression for ACL v21.08 vs v21.05

### ISSUE THREAD

**Issue by robinvanemden** [ARM-software/ComputeLibrary#922]
Output of 'strings libarm_compute.so | grep arm_compute_version': v21.05 vs v21.08

Platform: ARMv7

Operating System: Debian

**Problem description:**

We just drop-in replaced ACL v21.05 with the ACL v21.08 library for our NEON oriented framework, then tested a basic CNN and found the performance of ACL v21.08 significantly worse than that of ACL v21.05. Our test system is a single core Arm Cortex-A8 AM3352.

To demonstrate the issue, the results of warmup and post-warmup phases for a basic CNN that makes use of NEGEMM, and, particularly, NEConvolutionLayers and NEDepthwiseConvolutionLayers:

```
NEON supported - Running on ACL v21.05
Warmup pred() call duration: 2.580388 seconds
Postwarmup pred() call duration: 1.898441 seconds

```
versus

```
NEON supported - Running on ACL v21.08
Warmup pred() call duration: 3.020147 seconds
Postwarmup pred() call duration: 2.345052 seconds
```

**Comment by morgolock** [comment]
Hi @robinvanemden 

Would it be possible for you to share a test running the workloads that experience the slowdown in v21.08?

**Comment by robinvanemden** [comment]
Hi @morgolock 
I will see what I can do. It will probably take one or two weeks for me to share a relevant test. Though I suspect this issue should be easily reproducible: Running a DNN with some gemm & convolution layers will probably yield similar results.
