### ISSUE TITLE
Compute Library 21.08 build error of neon on Odroid

### ISSUE THREAD

**Issue by Rahn80643** [ARM-software/ComputeLibrary#923]
Output of 'strings libarm_compute.so | grep arm_compute_version':

Platform:
Odroid C4

Operating System:
Distributor ID: Ubuntu
Description: Ubuntu 20.04.1 LTS
Release: 20.04

Problem description:
Hi,
I tried to compile compute library base on this tutorial, but when I set neon=1, I got the following error:
./arm_compute/core/Size2D.h:38:5: error: arm_compute::Size2D::Size2D(size_t, size_t)' does not throw; perhaps it should be declared noexcept` [-Werror=noexcept]

The version of compute library is set as 21.08.

Currently, I set neon=0 and compute library is compiled successfully.  The issue is similar to #892, is this issue also resulted from the inconsistent use of the noexcept clause to the compiler?
![computeLibraryError](https://user-images.githubusercontent.com/8951991/131299376-698e5729-3e24-4b7c-bc93-65a420fa28a8.png)

**Comment by morgolock** [comment]
Hi @Rahn80643 

Thank you for reporting this.

Could you please share the output of the command as shown below?

```
root@odroid:~# aarch64-linux-gnu-g++ -v
Using built-in specs.
COLLECT_GCC=aarch64-linux-gnu-g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/9/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 

```

**Comment by Rahn80643** [comment]
Hi, 
the following message is the output of `aarch64-linux-gnu-g++ -v`
'''
Using built-in specs.
COLLECT_GCC=aarch64-linux-gnu-g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/9/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 
'''
I solve the issue by adding noexcept after Size2D(size_t w, size_t h), and Compute Library 21.08 can be built successfully.

Thank you
