### ISSUE TITLE
QASYMM8_SIGNED MaxPooling layer produce wrong results

### ISSUE THREAD

**Issue by terfendail** [ARM-software/ComputeLibrary#924]
arm_compute_version=v21.05 Build options: {'embed_kernels': '0', 'arch': 'armv7a', 'opencl': '0', 'neon': '1', 'build_dir': '/armcpu_plugin/openvino_contrib/modules/arm_plugin/build/thirdparty', 'examples': '0', 'internal_only': '0', 'extra_cxx_flags': '-fPIC   -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -fstack-protector-strong -s -fsigned-char -ffunction-sections -fdata-sections -fdiagnostics-show-option -Wundef -Wreturn-type -Wunused-variable -Wuninitialized -Winit-self -Wmaybe-uninitialized -Wno-error=unused-variable -Wno-error=unused-but-set-variable -Wno-error=deprecated-declarations -Wno-undef', 'cppthreads': '1', 'Werror': '0', 'data_layout_support': 'nchw'} Git hash=f7399fd616cc8ccedfae668da3023e589a7ef558

**Platform:** Raspberry PI 4

**Operating System:** Raspbian Buster

**Problem description:**
NEPoolingLayer with PoolingType::MAX, size 2x2 and stride 2x2 produce wrong result in case input tensor W dimension is shorter than 7

**Comment by morgolock** [comment]
Hi @terfendail 

Could you please confirm that you have called to validate() before run() and no error is reported?

Hope this helps.

**Comment by terfendail** [comment]
Reproducer
```
#include "arm_compute/runtime/NEON/NEFunctions.h"

#include "arm_compute/core/Types.h"
#include "utils/ImageLoader.h"
#include "utils/Utils.h"

using namespace arm_compute;
using namespace utils;

class NEONPoolingExample : public Example
{
public:
    bool do_setup(int argc, char **argv) override
    {
        src.allocator()->init(TensorInfo(TensorShape{6, 6}, 1, DataType::QASYMM8_SIGNED, QuantizationInfo(2., 0.)));
        dst.allocator()->init(TensorInfo(TensorShape{3, 3}, 1, DataType::QASYMM8_SIGNED, QuantizationInfo(2., 0.)));

        PoolingLayerInfo pool_info;
        pool_info.data_layout       = DataLayout::NCHW;
        pool_info.pool_size         = Size2D(2, 2);
        pool_info.pad_stride_info   = PadStrideInfo(2, 2, 0, 0, 0, 0, DimensionRoundingType::CEIL);
        pool_info.pool_type = PoolingType::MAX;

        Status test = NEPoolingLayer::validate(src.info(), dst.info(), pool_info);
        test.throw_if_error();

        pool.configure(&src, &dst, pool_info);

        src.allocator()->allocate();
        dst.allocator()->allocate();

        uint8_t *src_d = src.buffer();
        for(int i = 0; i < 36; ++i)
            src_d[i] = i;

        return true;
    }
    void do_run() override
    {
        pool.run();
    }
    void do_teardown() override
    {
        uint8_t *dst_d = dst.buffer();
        for(int i = 0; i < 9; ++i)
            std::cout << "dst_d[" << i << "]" << (int)(dst_d[i]) << std::endl;
    }

private:
    Tensor src{}, dst{};
    NEPoolingLayer pool{};
};

int main(int argc, char **argv)
{
    return utils::run_example<NEONPoolingExample>(argc, argv);
}
```

Expected result
```
dst_d[0]7
dst_d[1]9
dst_d[2]11
dst_d[3]19
dst_d[4]21
dst_d[5]23
dst_d[6]31
dst_d[7]33
dst_d[8]35
```

Actual result
```
dst_d[0]17
dst_d[1]19
dst_d[2]21
dst_d[3]21
dst_d[4]21
dst_d[5]21
dst_d[6]21
dst_d[7]21
dst_d[8]33
```

Actual result will be same as expected if size of input tensor is e.g. 32x32
