### ISSUE TITLE
i.mx8 qxp not support

### ISSUE THREAD

**Issue by benlvzi** [ARM-software/ComputeLibrary#926]
tengine-lite library version: 1.5-dev
ACL initialized
terminate called after throwing an instance of 'std::runtime_error'
  what():  in generate_build_options src/core/CL/CLCompileContext.cpp:262: Non uniform workgroup size is not supported!!
Aborted (core dumped)

Platform: i.mx8 qxp 

Operating System: linux

Problem description:
this platform gpu is vinvante GC7000lite and opencl 1.2 , the acl seem like not support.

**Comment by morgolock** [comment]
Hi @benlvzi 

Quoting from the documentation: https://arm-software.github.io/ComputeLibrary/latest/how_to_build.xhtml

The OpenCL backend in ACL has the following requirements:
 
> Compute Library requires OpenCL 1.1 and above with support of non uniform workgroup sizes, which is officially supported in the Arm® Mali™ OpenCL DDK r8p0 and above as an extension (respective extension flag is **-cl-arm-non-uniform-work-group-size**).

You need a mali gpu with support for -cl-arm-non-uniform-work-group-size
