### ISSUE TITLE
 I compile ACL 21.02 and 21.08 failed.

### ISSUE THREAD

**Issue by Newer2019** [ARM-software/ComputeLibrary#927]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
scons arch=arm64-v8a -j4 neon=1 opencl=1
embed_kernels=1 extra_cxx_flags="-fPIC" internal_only=0
Werror=1 debug=0 asserts=0 examples=0 build=native

**Platform:**
Arm64 aarch64
gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu

**Operating System:**
UOS20 

**Problem description:**
/usr/include/c++/8/bits/unique_ptr.h: In instantiation of ‘typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = arm_compute::cpu::kernels::CpuIm2ColKernel; _Args = {}; typename std::_MakeUniq<_Tp>::__single_object = std::unique_ptr<arm_compute::cpu::kernels::CpuIm2ColKernel>]’:
src/runtime/cpu/operators/CpuGemmConvolution.cpp:291:69: required from here
./arm_compute/core/Size2D.h:44:5: error: but ‘arm_compute::Size2D::Size2D(size_t, size_t)’ does not throw; perhaps it should be declared ‘noexcept’ [-Werror=noexcept]
Size2D(size_t w, size_t h)
^~~~~~

**Comment by morgolock** [comment]
Hi @Newer2019 

Please cherry pick this patch to fix the problem:
https://review.mlplatform.org/c/ml/ComputeLibrary/+/6182

**Comment by Newer2019** [comment]
thanks for your quick response, i will try it tomorrow.

**Comment by Newer2019** [comment]
also i compile onnxruntime 1.8.0 with acl 19.02, gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu

./build.sh --config Release --build_shared_lib --parallel --use_acl ACL_1902

and got

onnxruntime/onnxruntime/core/providers/acl/acl_common.cc:58:41: error: no matching function for call to ‘arm_compute::TensorAllocator::import_memory(void*&)’
return allocator->import_memory(memory);

**Comment by Newer2019** [comment]
@morgolock 

onnxruntime/onnxruntime/core/providers/acl/nn/conv.cc:31:10: 
fatal error: arm_compute/runtime/NEON/functions/assembly/NEDepthwiseConvolutionAssemblyDispatch.h

In which version can i locate this file?

**Comment by morgolock** [comment]
Hi @Newer2019 

Could you please update to a newer version of ACL?

19.02 is more than 2 years old.

Hope this helps.

**Comment by Newer2019** [comment]
> Hi @Newer2019
> 
> Could you please update to a newer version of ACL?
> 
> 19.02 is more than 2 years old.
> 
> Hope this helps.

I use acl  to compile onnxruntime 1.8..0 (arm version) 
when I use 21.05, 21.08, there are some functions not included (only older version works)

at last, i use v19.08 and worked.

if i want to use armnn and acl at the same time, it did not work, because  armnn  using acl 21.02 or above.
they are using different version of acl.

**Comment by morgolock** [comment]
Hi @Newer2019 

> I use acl to compile onnxruntime 1.8..0 (arm version)
when I use 21.05, 21.08, there are some functions not included (only older version works)

Is there a guide you're following? could you please share more information?

**Comment by morgolock** [comment]
Hi @Newer2019 
If the goal is running ONNX models I'd advice you go through armnn and run the model with ExecuteNetwork.

For more information about this please see:
https://github.com/ARM-software/armnn/tree/branches/armnn_21_08/tests/ExecuteNetwork

Hope this helps.
