### ISSUE TITLE
Support ACL + CoreML

### ISSUE THREAD

**Issue by allnes** [ARM-software/ComputeLibrary#932]
Hello, do you plan to support CoreML in the Compute Library?

**Comment by morgolock** [comment]
Hi @allnes 

Do you refer to Apple's framework? https://developer.apple.com/documentation/coreml

**Comment by allnes** [comment]
> Hi @allnes 
> 
> Do you refer to Apple's framework? https://developer.apple.com/documentation/coreml

Yes, Apple framework, because they create the m1 chip

**Comment by morgolock** [comment]
Hi @allnes 

ACL already runs on M1.

CoreML is Apple's proprietary ML framework for training and inference. What do you mean by supporting CoreML? Please provide more details or be more specific.

Hope this helps.

**Comment by allnes** [comment]
> Hi @allnes
> 
> ACL already runs on M1.
> 
> CoreML is Apple's proprietary ML framework for training and inference. What do you mean by supporting CoreML? Please provide more details or be more specific.
> 
> Hope this helps.

ACL supports Apple M1 - does that mean that acl can use the common cpu in the M1 chip?

CoreML uses a special neural processing unit, for inference. Accordingly, I assume that if the ACL supports CoreML, then we can run inference networks on this special NPU via CoreML along with the ARM CPU.

**Comment by morgolock** [comment]
Hi @allnes 

ACL is optimised for ARM-based CPUs and there are 8 arm-based cores in the M1 SoC. It's possible to run the neon functions in ACL on these cpus.

Hope this helps.

**Comment by allnes** [comment]
@morgolock thank you!
