### ISSUE TITLE
How to fix the error "Segmentation fault" when execute the example command "graph_yolov3" in the Orange Pi 4(RK3399)?

### ISSUE THREAD

**Issue by zhangweiwahaha042** [ARM-software/ComputeLibrary#935]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v20.05 Build options: {'embed_kernels': '1', 'arch': 'arm64-v8a', 'opencl': '1', 'neon': '0', 'asserts': '1', 'debug': '0', 'os': 'linux', 'Werror': '1'} Git hash=387b8aef6a22d4df29e408aa8ae68553eab6a726

**Platform:**
Orange Pi 4(RK3399)

**Operating System:**
ubuntu 18.04
orangepi@orangepi4:~$ uname -a
Linux orangepi4 4.4.179-rk3399 #4 SMP Tue Nov 9 11:24:14 JST 2021 aarch64 aarch64 aarch64 GNU/Linux

**Problem description:**
I'm so sorry I need you help.
the error "Segmentation fault" occur when I execute the example command "graph_yolov3".
Could you kindly please tell me how to fix that error or give me a good debug suggestion for that error?
Thanks in advance.

■procedure
(1).download and build the source code of the ACL(ARM Compute Library)
orangepi@orangepi4:\~$ git clone https://github.com/ARM-software/ComputeLibrary.git
orangepi@orangepi4:\~$ cd ComputeLibrary
orangepi@orangepi4:\~/ComputeLibrary$ git checkout v20.05
orangepi@orangepi4:\~/ComputeLibrary$ scons Werror=1 -j4 debug=0 asserts=1 neon=0 opencl=1 embed_kernels=1 os=linux arch=arm64-v8a

(2).the error "Segmentation fault" occur when execute the example command "graph_yolov3"
orangepi@orangepi4:\~/ComputeLibrary$ export LD_LIBRARY_PATH=build
orangepi@orangepi4:\~/ComputeLibrary$ build/examples/graph_yolov3

build/examples/graph_yolov3

Threads : 1
Target : NEON
Data type : F32
Data layout : NHWC
Tuner enabled? : false
Cache enabled? : false
Tuner mode : Normal
Tuner file : 
Fast math enabled? : false

Segmentation fault

**Comment by morgolock** [comment]
Hi @zhangweiwahaha042 

Would you please try with a more recent release of the library? Ideally 21.08.

**Comment by zhangweiwahaha042** [comment]
Dear @morgolock 

Thank you so much for your kindly reply.
I will try it refer to your suggestion.

BR.

**Comment by zhangweiwahaha042** [comment]
Dear @morgolock 

The problem is fixed refer to your good suggestion, so I close this ticket.
Thanks so much again for your kind support.

BR.
