### ISSUE TITLE
hog descriptor calculated by ACL different from opencv HOG descriptor

### ISSUE THREAD

**Issue by sunzk2017** [ARM-software/ComputeLibrary#936]
when I compute hog descriptor use ACL,  the result seems different from the result calculated by opencv.
 whether  the hog descriptor  calculated by ACL is same with the result calculated by opencv?  Thanks a lot

In order to make it sample,  setting:  winSize=blockSize; winStride=blockStride. 

opencv hog descriptors:   size=7 * 3 * 32:

                        0.104599, 0.0939107, 0.0738626, 0.0413416, ........
                        0.349142, 0.0257534, 0.00183144, 0.000329274, ........
                        ..............................
                        0.346539, 0.0944479, 0.0304494, 0.0101547,........

ACL NEHOGDescriptors:  size=7 *3 * 32 :

                        0.270506, 0.304823, 0.114578, 0.119113, ........
                        0.314935, 0.314935, 0.0158787, 0.0539849, ........
                        ..............................
                        0.0998959, 0.278487, 0.127762, 0.0461565, ........

**Comment by sunzk2017** [comment]
whether the hog descriptor calculated by arm computeLibrary is same with the result calculated by opencv?
Is there any difference between the two methods, Thanks a lot

**Comment by sunzk2017** [comment]
The params used in hog is the same. 
I also change the HOG configure paramaters, but the result still different from opencv hog.


           NEHOGDescriptor HOGDescriptors;
           HOGDescriptors.configure(&input, &output, hog, REPLICATE   );   //REPLICATE   CONSTANT    UNDEFINED

**Comment by morgolock** [comment]
Hi @sunzk2017 

ACL has shifted the focus to ML and all HOG functions were deprecated and removed from ACL in 21.05, see: https://arm-software.github.io/ComputeLibrary/latest/versions_changelogs.xhtml#S2_2_changelog

You could see some examples on how to use these functions in the validation fixtures:

- https://github.com/ARM-software/ComputeLibrary/blob/7dcb9fadb98cad05fca72de3273311d570d98b4e/tests/validation/fixtures/HOGDescriptorFixture.h
- https://github.com/ARM-software/ComputeLibrary/blob/7dcb9fadb98cad05fca72de3273311d570d98b4e/tests/validation/fixtures/HOGDetectorFixture.h
- https://github.com/ARM-software/ComputeLibrary/blob/7dcb9fadb98cad05fca72de3273311d570d98b4e/tests/validation/fixtures/HOGMultiDetectionFixture.h

21.05 is no longer maintained I would advice using a different library like OpenCV for this.

Hope this helps.
