### ISSUE TITLE
How to access elements of tensor if tensor have multi channels

### ISSUE THREAD

**Issue by sunzk2017** [ARM-software/ComputeLibrary#937]
How can I get elements of tensor if tensor have multi channels ?
I use TensorAccessor to get values, but it seems invalid.   Thanks a lot 

**arm_compute_version':20.08**

//---------------------------------------
Tensor output;
TensorInfo info;
int num_channels = 32;
info.init(TensorShape(7, 3), num_channels, Format::F32);
output.allocator()->init(info);

//---------------------------------------
TensorAccessor<float>accessor(output);
for (int x = 0; x <7; x++) {
        for (int y = 0; y < 3; y++) {
            for (int n = 0; n < num_channels ; n++) {
                float* ptr = accessor.get_ptr(x, y, z);
                cout << *ptr << ",";
            }
        }
    }
//---------------------------------------

**Comment by morgolock** [comment]
Hi @sunzk2017 

Please take a look at the following example: https://github.com/ARM-software/ComputeLibrary/blob/master/examples/neon_permute.cpp

The recommended to read/write elements from/to a tensor is by using the helper function execute_window_loop()
```
 void validate_result(const Tensor &reference, const Tensor &result)
    {
        Window window;
        window.use_tensor_dimensions(reference.info()->tensor_shape());
        Iterator ref_it(&reference, window);
        Iterator res_it(&result, window);
        execute_window_loop(window, [&](const Coordinates &)
        {
            assert(*reinterpret_cast<unsigned char *>(ref_it.ptr()) == *reinterpret_cast<unsigned char *>(res_it.ptr()));
        },
        ref_it, res_it);
    }

    void fill_tensor(Tensor &tensor)
    {
        Window window;
        window.use_tensor_dimensions(tensor.info()->tensor_shape());
        Iterator      tensor_it(&tensor, window);
        unsigned char val(0);
        execute_window_loop(window, [&](const Coordinates &)
        {
            *reinterpret_cast<unsigned char *>(tensor_it.ptr()) = val++;
        },
        tensor_it);
    }
```

This is all explained in the documentation https://arm-software.github.io/ComputeLibrary/latest/architecture.xhtml#architecture_images_tensors_working_with_objects

Hope this helps.

**Comment by sunzk2017** [comment]
@morgolock  Thanks for the reply, Now I can access elements of tensor with 1channel,  but still cannot access the tensor with multi channels. 
I donot know the difference between the following data layout:
(1)  info.init(TensorShape(7, 3), 32, Format::F32);
(2)  info.init(TensorShape(7, 3, 32), Format::F32);

The num_channels=32, and this two data layouts are both NCHW. How can I get the whole data? 

********************************************
Tensor output;
TensorInfo info;
info.init(TensorShape(7, 3), 32, Format::F32);
output.allocator()->init(info);
********************************************

**Comment by sunzk2017** [comment]
I use this function. It seems to work.

 Window window;
            window.use_tensor_dimensions(output.info()->tensor_shape());
            Iterator it(&output, window);
            execute_window_loop(window, [&](const Coordinates& id)
            {
                for (int i= 0; i< output.info()->num_channels(); i++) {
                    float target_value = reinterpret_cast<float*>(it.ptr())[i];
                }
            }, it);
