### ISSUE TITLE
In NEColorConvert.cpp of ComputeLibrary, which format is the same as CV_GRAY2BGR565  in cv::cvtcolor's code of opencv?

### ISSUE THREAD

**Issue by duhuanxianzi** [ARM-software/ComputeLibrary#94]
Hi, I want to realize the same function between NEColorConvert.cpp in ComputeLibrary and cv::cvtcolor in opencv. And I found some format such 'RGBA8888' and 'UYVY422' in NEColorConvertKernel.cpp.

In NEColorConvert.cpp of ComputeLibrary, which format is the same as CV_GRAY2BGR565 or CV_GRAY2BGR555 in cv::cvtcolor's code of opencv?

**Comment by AnthonyARM** [comment]
The Compute Library doesn't support 555 and 565 formats only RGB888
