### ISSUE TITLE
How to declare CL_TARGET_OPENCL_VERSION & CL_USE_DEPRECATED_OPENCL_1_1_APIS

### ISSUE THREAD

**Issue by alsaleem00** [ARM-software/ComputeLibrary#941]
I followed the instructions to compiling arm compute library. The initial compile was ok with v21.11.
I am specifically interested in the OpenCL part. 

I need to compile "arm_compute.so" and link to openCV 4.5.4. During build, openCV complaints that some functions are not present (linker error). Tracing ACL includes indicates that these functions will be present if I define CL_TARGET_OPENCL_VERSION & CL_USE_DEPRECATED_OPENCL_1_1_APIS directives.

I could not find instructions how to declare these defines. If I define them in cl_version.h i get so many compile errors. 
Or, do I need to use different (lower) arm compute build?

Could someone give me a hint (with scons)?

Thanks.

**Comment by morgolock** [comment]
Hi @alsaleem00 

When building ACL, you can use the scons option `extra_cxx_flags` to create any defines you need, for example `extra_cxx_flags=-DCL_USE_DEPRECATED_OPENCL_1_1_APIS=1`

Hope this helps.

**Comment by alsaleem00** [comment]
Clear. Thanks.
