### ISSUE TITLE
CMake build configuration

### ISSUE THREAD

**Issue by allnes** [ARM-software/ComputeLibrary#942]
Hello, will you support building with cmake? 

Or where can I find its support, of course, if it exists.

**Comment by zhangqicai** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by morgolock** [comment]
Hi @allnes 

At present it's only possible to build ACL with `scons`

CMake support is not in the ACL roadmap and this is a good opportunity/feature for external developers to work on and contribute.

Hope this helps.
