### ISSUE TITLE
CPUInfo::get().has_fp16() returns false on Apple M1 chip

### ISSUE THREAD

**Issue by alvoron** [ARM-software/ComputeLibrary#944]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v21.11 Build options: {'neon': '1', 'opencl': '0', 'cppthreads': '1', 'embed_kernels': '0', 'examples': '0', 'internal_only': '0', 'Werror': '0', 'data_layout_support': 'nchw', 'build_dir': '/Users/automation/avoron4/ie_build/build-modules/arm_plugin/thirdparty', 'arch': 'armv8.6-a', 'os': 'macos', 'build': 'native', 'extra_cxx_flags': '-fPIC  -fsigned-char -ffunction-sections -fdata-sections -fdiagnostics-show-option -Wundef -Wreturn-type -Wunused-variable -Wswitch -Wno-error=deprecated-declarations -Wno-undef -Wno-error=return-stack-address'} Git hash=b'91ee4d0a9ef128b16936921470a0e3ffef347536'

**Platform:**
Apple Mac mini with M1

**Operating System:**
macOS 11.1

**Problem description:**
`CPUInfo::get().has_fp16()` returns `false` on Apple M1 chip. I believe, it should be true.

**Comment by alvoron** [comment]
@morgolock could you please let me know when the fix is available on mlplatform? I may test it on my side.

**Comment by morgolock** [comment]
Hi @alvoron 

This patch fixes the problem: https://review.mlplatform.org/c/ml/ComputeLibrary/+/6989

Hope this helps.
