### ISSUE TITLE
Matrix multiplication problem

### ISSUE THREAD

**Issue by yikox** [ARM-software/ComputeLibrary#946]
Using OpenGL computer shader to calculate matrix multiplication, the speed of Mali GPU is much slower than that of Adreno GPU, and the calculation speed is row x column > column x column > row x row?
What caused this? Any suggestions for optimization?
Problem demo : [ProfilerDemo](https://github.com/yikox/ProfilerDemo)

**Comment by morgolock** [comment]
Hi @yikox 

We used to have a GLES backend in ACL but it was deprecated and removed.

There is only an OpenCL backend in ACL now, I would suggest you use ExecuteNetwork from Armnn to benchmark ACL gemm kernels: https://github.com/ARM-software/armnn/tree/branches/armnn_21_11/tests/ExecuteNetwork

Hope this helps.
