### ISSUE TITLE
Example code for int8 quantized network inference on arm compute library

### ISSUE THREAD

**Issue by abhajaswal** [ARM-software/ComputeLibrary#949]
Hello !

I want to run a int8 quantized tflite version on ACL latest version.
Is there any example available to use ACL interface using int8 quantized weights

**Comment by morgolock** [comment]
Hi @abhajaswal 

The best option to run models through ACL is by using ArmNN's `ExecuteNetwork`

You can download a tflite model from https://storage.googleapis.com/download.tensorflow.org/models/tflite_11_05_08/mobilenet_v2_1.0_224_quant.tgz and then run it as shown below:

`root@acl_hikey_1:~/tmp/pabtel01/armnn# LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH  ./ExecuteNetwork -f tflite-binary -m mobilenet_v2_1.0_224_quant.tflite -i input -o output -c CpuAcc`

For more information about ArmNN please see https://github.com/ARM-software/armnn/tree/branches/armnn_21_11/tests/ExecuteNetwork

Hope this helps.
