### ISSUE TITLE
Tool or method to measure  CPU usage for ACL 

### ISSUE THREAD

**Issue by abhajaswal** [ARM-software/ComputeLibrary#950]
Lately I have been using ACL for model inference ! 
I want to know the CPU utilization when using ACL.

Can i enable some logs or tools for measuring same ?

Kindly guide !

As i use float32 model , for NEON based Inference i get high overall high CPU utilization and CPU contention  for ACL application when seen using Ds5 streamline , But i want to understand exact % division while doing inference.

**Comment by morgolock** [comment]
Hi @abhajaswal 

The best way to analyse ACL performance is to get a layer by layer breakdown of the workloads executed during the inference. For this we use Armnn's ExecuteNetwork with the option `-e 1`

For example
`
root@odroid:~/pablo/armnn/armnn/build# LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./tests/ExecuteNetwork  -m ../../../mobilenet_v2_1.0_224.tflite  -c CpuAcc  -f tflite-binary  -i input -o MobilenetV2/Predictions/Reshape_1 -e 1 --iterations=10 
`

ExecuteNetwork will output a breakdown of the workloads including the time it took to run each particular layer.

For more information about ExecuteNetwork please refer to: https://github.com/ARM-software/armnn/tree/branches/armnn_21_11/tests/ExecuteNetwork

On the top of that, I use a script to process the profiler's output and get a human readable summary of the performance: https://github.com/morgolock/vison

Save the output of the profiler to a file

`root@odroid:~/pablo/armnn/armnn/build# LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./tests/ExecuteNetwork  -m ../../../mobilenet_v2_1.0_224.tflite  -c CpuAcc  -f tflite-binary  -i input -o MobilenetV2/Predictions/Reshape_1 -e 1 > mobilenet_v2_1.0_224.tflite.prof
`

Use vison to generate a report
`root@odroid:~/pablo/armnn/armnn/build# python3 ../../../vison/vison.py -j ./mobilenet_v2_1.0_224.tflite.prof`

```Inference time:  59967.458 us
Total kernel time  50050.66499999999 us

Total time per kernel				Percentage of total time		Kernel name
	 5.1660               us 		% 0.00010322 			  CpuLogits1DMaxKernel/neon_fp32_logits_1d_max
	 85.0000              us 		% 0.00169828 			  CpuLogits1DSoftmaxKernel/neon_fp32_softmax_logits_1d
	 93.4580              us 		% 0.00186727 			  CpuReshapeKernel
	 225.7910             us 		% 0.00451125 			  CpuPool2dAssemblyWrapperKernel
	 1189.1250            us 		% 0.02375843 			  CpuGemmAssemblyWrapperKernel/a64_hybrid_fp32_mla_4x24
	 1196.8330            us 		% 0.02391243 			  CpuIm2ColKernel
	 1602.4160            us 		% 0.03201588 			  CpuAddKernel/neon_fp32_add
	 5294.7500            us 		% 0.10578781 			  CpuGemmAssemblyWrapperKernel/a64_smallK_hybrid_fp32_mla_6x4
	 9634.6240            us 		% 0.19249742 			  CpuGemmAssemblyWrapperKernel/a64_sgemm_8x12
	 13032.4180           us 		% 0.26038451 			  CpuGemmAssemblyWrapperKernel/a64_hybrid_fp32_mla_6x16
	 17691.0840           us 		% 0.35346352 			  CpuDepthwiseConv2dAssemblyWrapperKernel
root@odroid:~/pablo/armnn/armnn/build# 
```

Hope this helps.

**Comment by allnes** [comment]
Hi @morgolock 
I saw this issue and tried run vison.py for my profile log 
[resnet-50-armnn.log](https://github.com/ARM-software/ComputeLibrary/files/7856250/resnet-50-armnn.log)

I got error: 
```
Traceback (most recent call last):
  File "vison/vison.py", line 95, in <module>
    unit = jdict['ArmNN']['inference_measurements_#1']['Wall clock time_#1']['unit']
KeyError: 'inference_measurements_#1'
```
Could you help me, how to use this script?

**Comment by morgolock** [comment]
Hi @allnes 

Could you please share the command to generate the log file?

**Comment by morgolock** [comment]
Hi @allnes 

Please pull the latest version of the tool and use the -k option to specify the inference #

`python3 vison.py -j /home/pabtel01/Downloads/resnet-50-armnn.log -k 64`

Hope this helps.

**Comment by allnes** [comment]
@morgolock thank you, it's helped me
