### ISSUE TITLE
Is arm_compute a replacement/independent of libOpenCL?

### ISSUE THREAD

**Issue by alsaleem00** [ARM-software/ComputeLibrary#951]
Maybe this is a basic question, but I got confused from [this](https://github.com/ARM-software/ComputeLibrary/issues/736) question.

It is getting difficult to use libOpenCL from the device. It is not libOpenCL alone, I had to copy 10's of other libraries along with libOpenCL because of library dependencies.

So, I thought using arm_compute library will provide independent execution of opencl functions without device's libOpenCL. It turns that libarm_compute.so does not have these functions (link errors) although the install folder contains headers (in include) of opencl's.
How to use opencl functions from arm_compute?

This brings another question: does arm_compute+graph require use of a device library (i.e. not independent) ?

Thanks.

**Comment by morgolock** [comment]
Hi @alsaleem00 

ACL isn't a replacement for libOpenCL.so. ACL is just another library which uses the OpenCL driver to run ML workloads on the GPU.

In order to use ACL you need a device with a MALI GPU and OpenCL working on the system. An easy way to determine if OpenCL is working is to use `clinfo` command. If you don't have that tool on the system you can build it from sources: https://github.com/Oblomov/clinfo

Hope this helps.

**Comment by alsaleem00** [comment]
Indeed my device does have libOpenCL and the processor (S922X) does have GPU (G52).

I am looking for away to bypass the use of device's libOpenCL (i.e. direct calls to CPU/GPU).

So, if i want to use arm_compute+graph without openCL functions (i see many "examples" in repository) for performing object detection algorithms (specifically yolo),
Do I still need openCL lib (or any other lib in device)?

Thanks.

**Comment by morgolock** [comment]
Hi @alsaleem00 

Yes, you need OpenCL to be working on the system if you wish to use ACL run workloads on the GPU. For more information please see: https://arm-software.github.io/ComputeLibrary/latest/how_to_build.xhtml#S1_7_cl_requirements

If you just need CPU acceleration you don't need OpenCL on your system.

Hope this helps.

**Comment by alsaleem00** [comment]
Thanks. I understand now.
It looks there is no way to build an app on Android that utilizes GPU without device vendor's opencl. 
This makes app specific for each device/mobile. 
(this is also true for vulkan)

I appreciate your response.
