### ISSUE TITLE
Support Windows ARM 

### ISSUE THREAD

**Issue by allnes** [ARM-software/ComputeLibrary#952]
Hello, 

Will you be support windows arm systems? 

For example acer spin 7 or microsoft surface

**Comment by morgolock** [comment]
Hi @allnes 

The CPU backend runs on all ARM A class based CPUs. Could you please clarify what type of support you refer? Building ACL on Windows?

**Comment by allnes** [comment]
> Hi @allnes
> 
> The CPU backend runs on all ARM A class based CPUs. Could you please clarify what type of support you refer? Building ACL on Windows?

Yes, so that, for example, ComputeLibrary can be built on windows and people could be run samples (also for cross-compilation)

**Comment by morgolock** [comment]
Hi @allnes 

We have added support for native build for WoA in the main branch and this will be present in 22.08.

Please see the instructions here:
https://review.mlplatform.org/c/ml/ComputeLibrary/+/7992/2/docs/user_guide/how_to_build_and_run_examples.dox

Caveat: native builds for WoA are experimental and some features interacting with the OS are missing.

Hope this helps.

**Comment by allnes** [comment]
Thank you!
I'll try and see it soon.
