### ISSUE TITLE
OMPScheduler causing inaccurate inference of mobilenetv2

### ISSUE THREAD

**Issue by rohitmkul** [ARM-software/ComputeLibrary#956]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v19.05 Build options: {'cppthreads': '0', 'arch': 'arm64-v8a', 'opencl': '0', 'neon': '1', 'examples': '0', 'asserts': '0', 'debug': '0', 'openmp': '1', 'os': 'linux', 'Werror': '0', 'build': 'native'} Git hash=4ba87dbdc3b22220eba4a792c1f5c87e7a88c7af
**Platform:**
NXP lx2160a 
**Operating System:**
Ubuntu- 18.04 LTS

OMPScheduler causing inaccurate inference of mobilenetv2. 

**Problem description:**

- Kernel execution on all sub windows ( split from the Kernel window) is not happening, because the workloads size ( having functions for kernel execution of split windows ) and the number of threads is not coming out to be equal. 

- The run_workloads function only launches 'num_threads' number of threads which execute just one function from the workloads vector each , as the number of functions in workloads is more than the launched threads , the remaining functions remain unexecuted which is causing inaccurate activation. 

- I made some changes to the run_workloads functions to make the threads finish execution of all functions from workloads vector , which has corrected the outcome. This is that change 

-------------------------------------------------------------------------------------------------------------------------------------------

    void OMPScheduler::run_workloads(std::vector<arm_compute::IScheduler::Workload> &workloads)
    {
        const unsigned int num_threads = std::min(_num_threads, static_cast<unsigned int>(workloads.size()));
        //std::cout<<" _num_threads = "<<_num_threads<<" run : workloads.size = "<<int(workloads.size())<<std::endl;
        if(num_threads < 1)
        {
            return;
        }
    
        ThreadInfo info;
        info.cpu_info    = &_cpu_info;
        info.num_threads = num_threads;
    
        int wsize=int(workloads.size());
        int limit = wsize/num_threads + ((wsize%num_threads)!=0) ;
    
        for(int i=0;i<limit;i++)
        {
            #pragma omp parallel  firstprivate(info) firstprivate(wsize) firstprivate(i) num_threads(num_threads)
            {
                const int tid  = omp_get_thread_num();
                info.thread_id = tid;
                if((tid +i*num_threads)<wsize)
                    workloads[tid +i*num_threads](info); //when num_threads is less than workload.size 
            }                         //only num_threads number of functions from
                                      //workloads array are executed leading to 
                                      // empty/zero activations on the unexecuted functions   
        }         
    }
-------------------------------------------------------------------------------------------------------------------------------------------
This is the function definition of 'run_workloads' in arm_cl 19.05 : 

    void OMPScheduler::run_workloads(std::vector<arm_compute::IScheduler::Workload> &workloads)
    {
        const unsigned int num_threads = std::min(_num_threads, static_cast<unsigned int>(workloads.size()));
        if(num_threads < 1)
        {
            return;
        }
        ThreadInfo info;
        info.cpu_info    = &_cpu_info;
        info.num_threads = num_threads;
        #pragma omp parallel firstprivate(info) num_threads(num_threads)
        {
            const int tid  = omp_get_thread_num();
            info.thread_id = tid;
            workloads[tid](info);
        }
    }

**Comment by morgolock** [comment]
Hi @rohitmkul 

Could you please update to v21.11? 19.05 is more than two years old.

Hope this helps.
