### ISSUE TITLE
How to parallel the Convolution Layer

### ISSUE THREAD

**Issue by wpy1368064015** [ARM-software/ComputeLibrary#958]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

**Platform: aarch64**

**Operating System:**

**Problem description:If I native build the library with openmp, how can i parallel the process of the NEConvolution->run()? **

**Comment by morgolock** [comment]
Hi @wpy1368064015 

The library will do it automatically for you.

At runtime the library queries the OS to determine the number of cores available on the system and then it will use multiple threads to run the kernels on all CPU cores simultaneously.

For more information please see:  https://github.com/ARM-software/ComputeLibrary/blob/master/src/runtime/OMP/OMPScheduler.cpp#L56

Hope this helps.
