### ISSUE TITLE
ComputeLibrary courses

### ISSUE THREAD

**Issue by allnes** [ARM-software/ComputeLibrary#959]
Hi!
Could you please tell me if you have courses on your Compute Library or ARMNN library for DL

**Comment by morgolock** [comment]
Hi @allnes 

Is there anything in particular you're looking for?

Please see below our ACL guides:

- [Tutorial: Running AlexNet on Raspberry Pi with Compute Library](https://community.arm.com/processors/b/blog/posts/running-alexnet-on-raspberry-pi-with-compute-library)
- [Gian Marco's talk on Performance Analysis for Optimizing Embedded Deep Learning Inference Software](https://www.embedded-vision.com/platinum-members/arm/embedded-vision-training/videos/pages/may-2019-embedded-vision-summit)
- [Gian Marco's talk on optimizing CNNs with Winograd algorithms at the EVS](https://www.embedded-vision.com/platinum-members/arm/embedded-vision-training/videos/pages/may-2018-embedded-vision-summit-iodice)
- [Gian Marco's talk on using SGEMM and FFTs to Accelerate Deep Learning](https://www.embedded-vision.com/platinum-members/arm/embedded-vision-training/videos/pages/may-2016-embedded-vision-summit-iodice)

Hope this helps.

**Comment by allnes** [comment]
> Hi @allnes
> 
> Is there anything in particular you're looking for?
> 
> Please see below our ACL guides:
> 
> * [Tutorial: Running AlexNet on Raspberry Pi with Compute Library](https://community.arm.com/processors/b/blog/posts/running-alexnet-on-raspberry-pi-with-compute-library)
> * [Gian Marco's talk on Performance Analysis for Optimizing Embedded Deep Learning Inference Software](https://www.embedded-vision.com/platinum-members/arm/embedded-vision-training/videos/pages/may-2019-embedded-vision-summit)
> * [Gian Marco's talk on optimizing CNNs with Winograd algorithms at the EVS](https://www.embedded-vision.com/platinum-members/arm/embedded-vision-training/videos/pages/may-2018-embedded-vision-summit-iodice)
> * [Gian Marco's talk on using SGEMM and FFTs to Accelerate Deep Learning](https://www.embedded-vision.com/platinum-members/arm/embedded-vision-training/videos/pages/may-2016-embedded-vision-summit-iodice)
> 
> Hope this helps.

ARM has courses https://www.arm.com/resources/education/online-courses/compendium
I thought that I find information about ACL or ARMNN in ARM compendium

**Comment by morgolock** [comment]
Thanks @allnes 

I'm going to communicate this request internally and see if we can put some ACL/ARMNN content there.
