### ISSUE TITLE
Error：unknown pseudo-: 'variant_pcs'

### ISSUE THREAD

**Issue by Realtyxxx** [ARM-software/ComputeLibrary#964]
**Platform: on the docker uppon amd zen2**

**Operating System: ubuntu19.04**

I was going to built the library with sve supported on my docker environment  , using the gcc-11 and find out these problems when it was assembling:
![image](https://user-images.githubusercontent.com/55488820/160089212-03bd004a-6978-4cfa-82a0-07acceb9ce65.png)
I tried google and change the assembler, but nothing helped

**Problem description:**

**Comment by Realtyxxx** [comment]
fixed , changed the as

**Comment by bluecodezlx** [comment]
I have the same problem, how did I solve it？

**Comment by bluecodezlx** [comment]
make[2]: *** [sleef/src/libm/CMakeFiles/sleefdetsvenofma.dir/build.make:81: sleef/src/libm/CMakeFiles/sleefdetsvenofma.dir/sleefsimdsp.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 17%] Built target ATEN_CPU_FILES_GEN_TARGET
[ 73%] Built target microkernels-all
/tmp/cc8N41pi.s: Assembler messages:
/tmp/cc8N41pi.s:7: Error: unknown pseudo-op: `.variant_pcs'
/tmp/cc8N41pi.s:45: Error: unknown pseudo-op: `.variant_pcs'
/tmp/cc8N41pi.s:91: Error: unknown pseudo-op: `.variant_pcs'
/tmp/cc8N41pi.s:408: Error: unknown pseudo-op: `.variant_pcs'
/tmp/cc8N41pi.s:803: Error: unknown pseudo-op: `.variant_pcs'
/tmp/cc8N41pi.s:1138: Error: unknown pseudo-op: `.variant_pcs'
/tmp/cc8N41pi.s:1555: Error: unknown pseudo-op: `.variant_pcs'
/tmp/cc8N41pi.s:1863: Error: unknown pseudo-op: `.variant_pcs'
/tmp/cc8N41pi.s:2239: Error: unknown pseudo-op: `.variant_pcs'
/tmp/cc8N41pi.s:2423: Error: unknown pseudo-op: `.variant_pcs'
/tmp/cc8N41pi.s:2614: Error: unknown pseudo-op: `.variant_pcs'
/tmp/cc8N41pi.s:2898: Error: unknown pseudo-op: `.variant_pcs'
/tmp/cc8N41pi.s:3304: Error: unknown pseudo-op: `.variant_pcs'
/tmp/cc8N41pi.s:3461: Error: unknown pseudo-op: `.variant_pcs'
/tmp/cc8N41pi.s:3723: Error: unknown pseudo-op: `.variant_pcs'
/tmp/cc8N41pi.s:3809: Error: unknown pseudo-op: `.variant_pcs'
/tmp/cc8N41pi.s:3958: Error: unknown pseudo-op: `.variant_pcs'
/tmp/cc8N41pi.s:4059: Error: unknown pseudo-op: `.variant_pcs'
/tmp/cc8N41pi.s:4237: Error: unknown pseudo-op: `.variant_pcs'
/tmp/cc8N41pi.s:4453: Error: unknown pseudo-op: `.variant_pcs'
/tmp/cc8N41pi.s:4575: Error: unknown pseudo-op: `.variant_pcs'
/tmp/cc8N41pi.s:4674: Error: unknown pseudo-op: `.variant_pcs'
/tmp/cc8N41pi.s:4762: Error: unknown pseudo-op: `.variant_pcs'
/tmp/cc8N41pi.s:4850: Error: unknown pseudo-op: `.variant_pcs'
/tmp/cc8N41pi.s:4947: Error: unknown pseudo-op: `.variant_pcs'
make[2]: *** [sleef/src/libm/CMakeFiles/sleefdetsve.dir/build.make:95: sleef/src/libm/CMakeFiles/sleefdetsve.dir/sleefsimddp.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3976: sleef/src/libm/CMakeFiles/sleefdetsve.dir/all] Error 2

**Comment by Realtyxxx** [comment]
Sorry, I saw this problem a long time ago. I remember that I used the method of modifying an underlying compilation tool to fix it at that time.
ARM seems to have updated a component at the "ld "level.
