### ISSUE TITLE
Sparse computing

### ISSUE THREAD

**Issue by ProgrammerWLY** [ARM-software/ComputeLibrary#965]
Hello! Does ARM provide a sparse matrix computation library?

**Comment by morgolock** [comment]
Hi @ProgrammerWLY 

ACL does not provide support for Sparse Matrix Multiplication.

Would you please provide more details about your requirements? What's your use case?

Hope this helps.

**Comment by ProgrammerWLY** [comment]
Thank you for your reply! It helps me a lot.


| |
computer12315
|
|
***@***.***
|
On 6/9/2022 16:05，Pablo Marquez ***@***.***> wrote：

Hi @ProgrammerWLY

ACL does not provide support for Sparse Matrix Multiplication.

Would you please provide more details about your requirements? What's your use case?

Hope this helps.
