### ISSUE TITLE
ACL stuck in clEnqueueMapBuffer

### ISSUE THREAD

**Issue by steven9046** [ARM-software/ComputeLibrary#968]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**

arm_compute_version=v21.08 Build options: {'embed_kernels': '1', 'opencl': '1', 'neon': '1', 'internal_only': '0', 'extra_cxx_flags': '-fPIC -Wno-type-limits -Wno-strict-overflow', 'arch': 'arm64-v8a'} Git hash=c66f0e08bacd1041a4e5a7fda0eadbd868521a18

**Platform:**

arrch64 RK3399

**Operating System:**

ubuntu16.04

**Problem description:**

When I use armnn to do inference on my mobile device with [ssd_mobilenet_v3_small_coco](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v3_small_coco_2020_01_14.tar.gz). It stuck in this function . 
`clEnqueueMapBuffer`
No error code, just can't return.
You can find the model here:

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md

Any help?

**Comment by steven9046** [comment]
If I don't add these flags:  -Wno-type-limits -Wno-strict-overflow, ACL can't be compiled.

**Comment by steven9046** [comment]
GDB backtrace showed this message about 14000 times:

`#1966 0x0000007faab09e90 in osup_sync_object_wait () from /usr/lib/libOpenCL.so`

**Comment by morgolock** [comment]
Hi @steven9046 

Could you please upgrade to the latest release of ACL (v22.02) and let us know if you still experience the problem ?
