### ISSUE TITLE
Support ARM NEOVERSE N1 ?

### ISSUE THREAD

**Issue by lianghong** [ARM-software/ComputeLibrary#974]
Hi,

Although it is mentioned in the project description that the supported processor are only Arm Cortex-A, , Arm Cortex-R and Arm Cortex-X1. I would still want to get a confirmation, does ACL support Arm Neoverse N1? Thanks.

**Comment by morgolock** [comment]
Hi @lianghong 

Neoverse-N1 is an armv8.2-a arch, ACL has many kernels optimized for this architecture. These kernels use FP16 and dot product instructions to speedup some computation.

You can build ACL for armv8.2 with the option arch=arm64-v8.2-a
Hope this helps.

**Comment by lianghong** [comment]
Thanks !
