### ISSUE TITLE
Neoverse V1 build error with "arch=arm64-v8.2-a-sve"

### ISSUE THREAD

**Issue by taosun1** [ARM-software/ComputeLibrary#978]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v22.02 Git hash=8f587de9214dbc3aee4ff4eeb2ede66747769b19

**Platform:** aws c7g

**Operating System:** ubuntu 18.04.6 LTS

**Problem description:**
I can build successfully with 'arch=arm64-v8.2-a'; but got error with "arch=arm64-v8.2-a-sve" like below, what's the problem?
cc1plus: error: invalid feature modifier in ‘-march=armv8.2-a+sve+fp16+dotprod’

**Comment by morgolock** [comment]
Hi @taosun1 

Your toolchain does not support sve.

Can you please share the output of the following command `aarch64-linux-gnu-g++ --version` ?


Hope this helps.

**Comment by taosun1** [comment]
@morgolock thanks, I finally built successfully inside this container https://hub.docker.com/r/armswdev/tensorflow-arm-neoverse. I guess we can close this issue. Earlier my host complier version is:
    _aarch64-linux-gnu-g++ (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
    Copyright (C) 2017 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE._
