### ISSUE TITLE
Gflops comparetion on gemm compare with other lib like ncnn or mnn?

### ISSUE THREAD

**Issue by jinfagang** [ARM-software/ComputeLibrary#980]
Gflops comparetion on gemm compare with other lib like ncnn or mnn?

**Comment by morgolock** [comment]
Hi @jinfagang 

I'd advice searching for third-party papers doing this analysis and/or ML benchmark figures. ACL targets a wide range of ARM CPUs and GPUs so there is no simple answer to this question.
