### ISSUE TITLE
why  clEnqueueReadImage  is not  linkable in the  built  lib.

### ISSUE THREAD

**Issue by lyz9801** [ARM-software/ComputeLibrary#982]
Dear ,  I  built a program with   arm_compute-v22.05-bin-android-arm64-v8a-cl\lib\arm64-v8a-cl\libarm_compute.so  ,   it got an error  as below:
 undefined reference to **`clEnqueueReadImage**'
clang++.exe: error: linker command failed with exit code 1

other  cl  apis   has  no problem , like  clCreateImage.    

is  the function  clEnqueueReadImage  forbidden  in  the  arm  system?  it  is ok in windows X86 .

**Comment by morgolock** [comment]
Hi @lyz9801 

Could you please share the command you used to build the program? 

Please see the documenation on how to build the examples:
https://arm-software.github.io/ComputeLibrary/latest/how_to_build.xhtml#S1_2_2_examples

Hope this helps

**Comment by lyz9801** [comment]
Hi,  @morgolock
      
 I  havn't  built  the program yet,  just directly  use  the  library  in  the hompage ,   the  linked address is  https://github.com/ARM-software/ComputeLibrary/releases/download/v22.05/arm_compute-v22.05-bin-android-arm64-v8a-cl.tar.gz

  in   ComputeLibrary-main/src/core/CL/OpenCL.cpp,  there is an implementation of  clCreateImage,   but   I cannot find clEnqueueReadImage ,  which is also a standard  api   in  https://www.khronos.org/files/opencl30-reference-guide.pdf .  I‘m not sure  whether  this api  is supported in the embedded computing   system.     As in  the  intel X86 platform, the api  can be found in https://gitlab.freedesktop.org/beignet/beignet/-/blob/master/src/cl_api_mem.c

**Comment by morgolock** [comment]
Hi @lyz9801 

> I havn't built the program yet, just directly use the library in the hompage , the linked address is https://github.com/ARM-software/ComputeLibrary/releases/download/v22.05/arm_compute-v22.05-bin-android-arm64-v8a-cl.tar.gz

Could you please elaborate and explain how do you use the library?

What device and OS are you using?
