### ISSUE TITLE
Build error using GCC 12

### ISSUE THREAD

**Issue by imzhuhl** [ARM-software/ComputeLibrary#983]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v22.05 Build options: {'Werror': '1', 'debug': '1', 'asserts': '1', 'neon': '1', 'opencl': '0', 'os': 'linux', 'build': 'native', 'arch': 'armv8.6-a'} Git hash=b'a175e887d64450decf80ea47d4049832c5805565'
**Platform:**

**Operating System:**
Linux

**Problem description:**
Build error using GCC 12
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/17999964/175205508-efac3b38-873e-4654-972f-38afb313fae0.png">

**Solution:**
I found that adding the corresponding header file can solve this problem.

1. add `#include<iterator>` to `include/libnpy/npy.hpp`
2. add `#include <cstring>` to `utils/command_line/CommandLineParser.h`

I want to share this and ask, is it okay to do so ？

**Comment by morgolock** [comment]
Hi @imzhuhl 

This has been fixed in the main branch with the following patch: https://review.mlplatform.org/c/ml/ComputeLibrary/+/7682

Hope this helps.
