### ISSUE TITLE
Threading in ACL

### ISSUE THREAD

**Issue by allnes** [ARM-software/ComputeLibrary#996]
Hello, I have some questions:
* Could I somewhere find information about use parallel threading  in Arm Compute Library?
* Do you use pinning cores in Arm Compute Library if you use threading?

**Comment by morgolock** [comment]
Hi @allnes 

ACL implements multithreading at the kernel level in `CPPScheduler`, see  https://github.com/ARM-software/ComputeLibrary/blob/main/src/runtime/CPP/CPPScheduler.cpp and https://github.com/ARM-software/ComputeLibrary/blob/main/src/runtime/IScheduler.cpp#L146 .  At runtime the scheduler creates multiple threads and executes the same kernel on different parts of the data. Internally the library uses the concept of executing a kernel in a `window`,

All this happens automatically when you run a function like NEGEMM, the function will configure the kernels and call the CPPScheduler to execute them in multiple threads. See https://arm-software.github.io/ComputeLibrary/latest/implementation_topic.xhtml#implementation_topic_multithreading

ACL does not pin the threads to cores.

Hope this helps.

**Comment by allnes** [comment]
> Hi @allnes
> 
> ACL implements multithreading at the kernel level in `CPPScheduler`, see https://github.com/ARM-software/ComputeLibrary/blob/main/src/runtime/CPP/CPPScheduler.cpp and https://github.com/ARM-software/ComputeLibrary/blob/main/src/runtime/IScheduler.cpp#L146 . At runtime the scheduler creates multiple threads and executes the same kernel on different parts of the data. Internally the library uses the concept of executing a kernel in a `window`,
> 
> All this happens automatically when you run a function like NEGEMM, the function will configure the kernels and call the CPPScheduler to execute them in multiple threads. See https://arm-software.github.io/ComputeLibrary/latest/implementation_topic.xhtml#implementation_topic_multithreading
> 
> ACL does not pin the threads to cores.
> 
> Hope this helps.

Thank you for your answer!
