### ISSUE TITLE
What is the indirect convolution operation?

### ISSUE THREAD

**Issue by Piorosen** [ARM-software/ComputeLibrary#997]
Hello, I have a question while analyzing the internal implementation.

1. What is the indirect convolution? If I think, is it similar to the paper below?
[Paper](https://arxiv.org/abs/1907.02129)
[Code](https://github.com/ARM-software/ComputeLibrary/blob/main/src/core/NEON/kernels/arm_gemm/gemm_hybrid_indirect.hpp)

**Comment by morgolock** [comment]
Hi @Piorosen 

Yes, that kernel is related to indirect convolution.

Hope this helps

**Comment by Piorosen** [comment]
Thank you very much.  @morgolock 
 I'd like to find paper or additional data on the implementation method of ACL.
For example, Google's https://research.google/pubs/ or annotations?

**Comment by morgolock** [comment]
Hi @Piorosen 

Unfortunately we don't have any public documents about the implementation details.

I'll discuss your request with the team and see if we can do something in the future releases.

**Comment by Piorosen** [comment]
@morgolock Thank you! 
I checked the issue.
Thank you very much for answering that question.
This is because there were many questions "indirect convolution" while checking the armcl implementation.
